#!/usr/bin/env python3
"""LiDAR and Geospatial Metadata Field Inventory for MetaExtract.

Covers LAS/LAZ formats, point cloud classification, full waveform LiDAR,
elevation models (DEM/DSM/DTM), mobile mapping systems (MLS/SLAM),
bathymetric LiDAR, and quality control metrics.

Reference:
- ASPRS LAS Specification 1.2-1.4
- OGC GeoPackage, CityGML, IndoorGML
- USGS LiDAR Base Specification
- ISO 19115 Geospatial Metadata
"""

import json
from datetime import datetime, timezone
from pathlib import Path


def generate_lidar_inventory():
    """Generate comprehensive LiDAR/geospatial metadata field inventory."""

    INVENTORY = {
        "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "source": "ASPRS LAS 1.2-1.4, USGS LiDAR Base Spec, ISO 19115, OGC GeoPackage, CityGML",
        "description": "LiDAR and geospatial metadata fields including point cloud formats, classification, waveforms, elevation models, mobile mapping, bathymetry, and quality metrics",
        "categories": {
            "las_laz_format": {
                "description": "ASPRS LAS format versions 1.2-1.4 and LAZ compression metadata",
                "reference": "ASPRS LAS Specification 1.4, LAZ compression spec",
                "fields": [
                    "las.file_source_id",
                    "las.global_encoding",
                    "las.project_id_guid",
                    "las.version_major",
                    "las.version_minor",
                    "las.system_identifier",
                    "las.generating_software",
                    "las.file_creation_day",
                    "las.file_creation_year",
                    "las.header_size",
                    "las.offset_to_point_data",
                    "las.num_variable_length_records",
                    "las.point_data_format_id",
                    "las.point_data_record_length",
                    "las.num_point_records",
                    "las.num_points_by_return",
                    "las.x_scale_factor",
                    "las.y_scale_factor",
                    "las.z_scale_factor",
                    "las.x_offset",
                    "las.y_offset",
                    "las.z_offset",
                    "las.max_x",
                    "las.min_x",
                    "las.max_y",
                    "las.min_y",
                    "las.max_z",
                    "las.min_z",
                    "las.start_of_waveform_data_packet",
                    "las.start_of_first_extended_vlr",
                    "las.num_extended_vlrs",
                    "las.num_points_by_return_ext",
                    "las.extended_point_count",
                    "laz.version_major",
                    "laz.version_minor",
                    "laz.compressor",
                    "laz.coder",
                    "laz.chunk_size",
                    "laz.num_chunks",
                    "laz.compressed_size",
                    "laz.uncompressed_size",
                    "laz.compression_ratio",
                    "vlr.record_id",
                    "vlr.user_id",
                    "vlr.length",
                    "vlr.description",
                    "vlr.geo_key_directory",
                    "vlr.projection_wkt",
                    "vlr.coordinate_system_wkt",
                    "vlr.datum_wkt",
                    "vlr.vertical_datum_wkt",
                    "vlr.extra_bytes",
                    "vlr.classification_lookup",
                    "vlr.histogram",
                    "vlr.text_description",
                    "vlr.software_version",
                    "vlr.creation_date",
                    "vlr.modified_date",
                    "vlr.source_project",
                    "vlr.source_volume",
                    "vlr.source_file",
                    "vlr.epoch",
                    "las.point_format",
                    "las.return_number",
                    "las.number_of_returns",
                    "las.scan_direction_flag",
                    "las.edge_of_flight_line",
                    "las.scan_angle_rank",
                    "las.user_data",
                    "las.point_source_id",
                    "las.gps_time",
                    "las.red",
                    "las.green",
                    "las.blue",
                    "las.nir",
                    "las.wave_packet_descriptor_index",
                    "las.wave_packet_location",
                    "las.wave_packet_size",
                    "las.wave_return_count",
                    "las.wave_x_t",
                    "las.wave_y_t",
                    "las.wave_z_t",
                    "las.classification_flags",
                    "las.scanner_channel",
                    "las.overlap",
                    "las.extended_scan_angle",
                    "las.extended_return_number",
                    "las.extended_number_of_returns",
                ],
                "count": 80,
            },
            "point_cloud_classification": {
                "description": "ASPRS point cloud classification codes and classes",
                "reference": "ASPRS LAS 1.4 Classification Codes, USGS LiDAR Spec",
                "fields": [
                    "classification.ground",
                    "classification.low_vegetation",
                    "classification.medium_vegetation",
                    "classification.high_vegetation",
                    "classification.building",
                    "classification.low_point",
                    "classification.reserved_1",
                    "classification.water",
                    "classification.rail",
                    "classification.road_surface",
                    "classification.reserved_2",
                    "classification.wire_guard",
                    "classification.wire_conductor",
                    "classification.transmission_tower",
                    "classification.wire_connector",
                    "classification.bridge_deck",
                    "classification.high_noise",
                    "classification.overlap",
                    "classification.reserved_3",
                    "classification.reserved_4",
                    "classification.soft_ground",
                    "classification.waterway",
                    "classification.terrain_model",
                    "classification.rock",
                    "classification.wooden_building",
                    "classification.tower_structure",
                    "classification.vegetation_height",
                    "classification.vegetation_probability",
                    "classification.ground_terrain",
                    "classification.snow_ice",
                    "classification.transient_object",
                    "classification.vehicle",
                    "classification.person",
                    "classification.animal",
                    "classification.other_object",
                    "classification.urban_building",
                    "classification.rural_building",
                    "classification.historic_structure",
                    "classification.bridge_structure",
                    "classification.culvert",
                    "classification.fence",
                    "classification.wall",
                    "classification.hedge",
                    "classification.tree",
                    "classification.shrub",
                    "classification.grass",
                    "classification.crop",
                    "classification.water_column",
                    "classification.sea_floor",
                    "classification.soft_bottom",
                    "classification.hard_bottom",
                    "classification.submerged_vegetation",
                    "classification.bathymetric_point",
                    "classification.shoreline",
                    "classification.sand_dune",
                    "classification.bare_ground",
                    "classification.exposed_rock",
                    "classification.ash_pit",
                    "classification.mine_tailings",
                    "classification.urban_area",
                    "classification.agricultural_area",
                ],
                "count": 60,
            },
            "lidar_waveforms": {
                "description": "Full waveform LiDAR parameters and return data",
                "reference": "ASPRS LAS 1.3+, Riegl, Leica, Optech waveform specs",
                "fields": [
                    "waveform.intensity",
                    "waveform.amplitude",
                    "waveform.width",
                    "waveform.energy",
                    "waveform.peak_location",
                    "waveform.peak_value",
                    "waveform.noise_level",
                    "waveform.signal_to_noise",
                    "waveform.return_number",
                    "waveform.total_returns",
                    "waveform.first_return",
                    "waveform.last_return",
                    "waveform.intermediate_returns",
                    "waveform.wavelength",
                    "waveform.pulse_duration",
                    "waveform.pulse_energy",
                    "waveform.peak_power",
                    "waveform.average_power",
                    "waveform.repetition_rate",
                    "waveform.beam_divergence",
                    "waveform.footprint_radius",
                    "waveform.footprint_diameter",
                    "waveform.sample_interval",
                    "waveform.samples_per_pulse",
                    "waveform.sample_count",
                    "waveform.transmit_energy",
                    "waveform.received_energy",
                    "waveform.background_noise",
                    "waveform.dynamic_range",
                    "waveform.gain_setting",
                    "waveform.threshold",
                    "waveform.range_resolution",
                    "waveform.along_track_resolution",
                    "waveform.cross_track_resolution",
                    "waveform.wave_packet_index",
                    "waveform.wave_packet_offset",
                    "waveform.wave_packet_size",
                    "waveform.return_point_location",
                    "waveform.t",
                    "waveform.x",
                    "waveform.y",
                    "waveform.z",
                    "waveform.waveform_descriptor",
                    "waveform.emission_source",
                    "waveform.detector_type",
                    "waveform.recording_mode",
                    "waveform.compression",
                    "waveform.quantization",
                    "waveform.bit_depth",
                    "waveform.sampling_frequency",
                    "waveform.temporal_offset",
                    "waveform.geometric_correction",
                    "waveform.atmospheric_correction",
                    "waveform.range_compensation",
                ],
                "count": 50,
            },
            "elevation_models": {
                "description": "Digital Elevation Models, Surface Models, and Bare Earth data",
                "reference": "USGS DEM Standards, ISO 19115, ASPRS DEM specs",
                "fields": [
                    "dem.elevation",
                    "dem.elevation_min",
                    "dem.elevation_max",
                    "dem.elevation_mean",
                    "dem.elevation_median",
                    "dem.elevation_mode",
                    "dem.elevation_stddev",
                    "dem.elevation_variance",
                    "dem.elevation_range",
                    "dem.vertical_datum",
                    "dem.vertical_units",
                    "dem.vertical_resolution",
                    "dem.horizontal_datum",
                    "dem.horizontal_units",
                    "dem.cell_size_x",
                    "dem.cell_size_y",
                    "dem.cell_size_z",
                    "dem.nodata_value",
                    "dem.compression",
                    "dem.data_type",
                    "dem.bit_depth",
                    "dem.byte_order",
                    "dem.grid_rows",
                    "dem.grid_columns",
                    "dem.total_cells",
                    "dsm.elevation",
                    "dsm.canopy_height",
                    "dsm.building_height",
                    "dsm.vegetation_height",
                    "dsm.structure_elevation",
                    "dsm.first_surface",
                    "dtm.elevation",
                    "dtm.bare_earth",
                    "dtm.ground_surface",
                    "dtm.terrain_model",
                    "dtm.smoothing",
                    "dtm.interpolation",
                    "dtm.fill_nodata",
                    "dtm.holes_filled",
                    "first_return.elevation",
                    "first_return.intensity",
                    "last_return.elevation",
                    "last_return.intensity",
                    "bare_earth.elevation",
                    "bare_earth.interpolation_method",
                    "bare_earth.grid_resolution",
                    "terrain.slope",
                    "terrain.aspect",
                    "terrain.hillshade",
                    "terrain.curvature",
                    "terrain.profile_curvature",
                    "terrain.plan_curvature",
                    "terrain.roughness",
                    "terrain.tpi",
                    "terrain.tri",
                    "terrain.tri_index",
                    "terrain.convergence_index",
                    "terrain.accumulation_flow",
                    "terrain.flow_direction",
                    "terrain.watershed",
                    "terrain.catchment",
                ],
                "count": 60,
            },
            "mobile_mapping": {
                "description": "Mobile LiDAR Systems, SLAM, MLS, trajectory and IMU data",
                "reference": "OGC GeoPackage, ISO 19115, Riegl, Leica, Trimble MLS specs",
                "fields": [
                    "mobile.trajectory_id",
                    "mobile.trajectory_filename",
                    "mobile.trajectory_start_time",
                    "mobile.trajectory_end_time",
                    "mobile.trajectory_length",
                    "mobile.position_x",
                    "mobile.position_y",
                    "mobile.position_z",
                    "mobile.roll",
                    "mobile.pitch",
                    "mobile.heading",
                    "mobile.velocity_x",
                    "mobile.velocity_y",
                    "mobile.velocity_z",
                    "mobile.acceleration_x",
                    "mobile.acceleration_y",
                    "mobile.acceleration_z",
                    "mobile.angular_rate_x",
                    "mobile.angular_rate_y",
                    "mobile.angular_rate_z",
                    "imu.manufacturer",
                    "imu.model",
                    "imu.serial_number",
                    "imu.firmware_version",
                    "imu.sample_rate",
                    "imu.accuracy_roll",
                    "imu.accuracy_pitch",
                    "imu.accuracy_heading",
                    "imu.accuracy_position",
                    "imu.drift_rate",
                    "imu.temperature_compensation",
                    "slam.system_type",
                    "slam.algorithm",
                    "slam.loop_closure",
                    "slam.keyframe_count",
                    "slam.map_points",
                    "slam.covariance_matrix",
                    "slam.convergence",
                    "slam.registration_error",
                    "slam.traversal_length",
                    "slam.duration",
                    "mls.scanner_id",
                    "mls.scanner_type",
                    "mls.scan_pattern",
                    "mls.scan_rate",
                    "mls.scan_frequency",
                    "mls.angular_resolution",
                    "mls.angular_range",
                    "mls.scan_lines",
                    "mls.measurement_rate",
                    "mls.multi_station_adjustment",
                    "mls.strip_adjustment",
                    "mls.georeferencing_mode",
                    "mls.direct_georeferencing",
                    "mls.indirect_georeferencing",
                    "mobile.platform_type",
                    "mobile.vehicle_id",
                    "mobile.speed",
                    "mobile.gps_week",
                    "mobile.gps_seconds",
                    "mobile.gps_quality",
                    "mobile.satellite_count",
                    "mobile.pdop",
                    "mobile.hdop",
                    "mobile.vdop",
                    "mobile.differential_correction",
                ],
                "count": 60,
            },
            "bathymetric_lidar": {
                "description": "Airborne Bathymetric LiDAR, green wavelength, water penetration",
                "reference": "USGS Coastal LiDAR, EAARL, SHOALS, CZMIL specifications",
                "fields": [
                    "bathymetry.water_depth",
                    "bathymetry.depth_min",
                    "bathymetry.depth_max",
                    "bathymetry.seabed_elevation",
                    "bathymetry.bed_elevation",
                    "bathymetry.water_surface",
                    "bathymetry.tide_correction",
                    "bathymetry.sounding_datum",
                    "bathymetry.chart_datum",
                    "bathymetry.vertical_reference",
                    "bathymetry.wavelength_green",
                    "bathymetry.wavelength_blue",
                    "bathymetry.laser_pulse_rate",
                    "bathymetry.pulse_energy_blue",
                    "bathymetry.pulse_energy_green",
                    "bathymetry.transmittance",
                    "bathymetry.absorption",
                    "bathymetry.backscatter",
                    "bathymetry.diffuse_attenuation",
                    "bathymetry.secchi_depth",
                    "bathymetry.turbidity",
                    "bathymetry.salinity",
                    "bathymetry.temperature",
                    "bathymetry.salinity_correction",
                    "bathymetry.temperature_correction",
                    "bathymetry.refractive_index",
                    "bathymetry.speed_of_sound",
                    "bathymetry.footprint_size",
                    "bathymetry.pulse_length",
                    "bathymetry.scan_angle",
                    "bathymetry.airborne_altitude",
                    "bathymetry.aircraft_speed",
                    "bathymetry.surface_return",
                    "bathymetry.bottom_return",
                    "bathymetry.multiple_returns",
                    "bathymetry.signal_strength",
                    "bathymetry.noise_level",
                    "bathymetry.snr",
                    "bathymetry.dynamic_range",
                    "bathymetry.gain_setting",
                    "bathymetry.threshold_offset",
                    "bathymetry.range_correction",
                    "bathymetry.geometric_correction",
                    "bathymetry.attenuation_coefficient",
                    "bathymetry.bathymetric_point",
                    "bathymetry.hydrographic_feature",
                    "bathymetry.sea_floor_class",
                    "bathymetry.sand_wave",
                    "bathymetry.reef_structure",
                    "bathymetry.submerged_vegetation",
                    "bathymetry.benthic_habitat",
                    "bathymetry.coastal_zone",
                    "bathymetry.nearshore",
                    "bathymetry.foreshore",
                    "bathymetry.backshore",
                ],
                "count": 50,
            },
            "quality_control": {
                "description": "LiDAR quality metrics, accuracy, density, spacing, and coverage",
                "reference": "USGS LiDAR Base Specification, ASPRS accuracy standards",
                "fields": [
                    "qc.density",
                    "qc.density_points_per_sqm",
                    "qc.density_points_per_sqft",
                    "qc.average_spacing",
                    "qc.spacing_stddev",
                    "qc.spacing_min",
                    "qc.spacing_max",
                    "qc.coverage_percentage",
                    "qc.overlap_percentage",
                    "qc.gap_percentage",
                    "qc.hole_diameter",
                    "qc.hole_count",
                    "qc.hole_area",
                    "qc.horizontal_accuracy",
                    "qc.horizontal_rmse",
                    "qc.horizontal_ce90",
                    "qc.horizontal_cm95",
                    "qc.vertical_accuracy",
                    "qc.vertical_rmse",
                    "qc.vertical_ce90",
                    "qc.vertical_cm95",
                    "qc.vertical_bias",
                    "qc.vertical_tilt",
                    "qc.absolute_accuracy",
                    "qc.relative_accuracy",
                    "qc.cross_scan_accuracy",
                    "qc.along_scan_accuracy",
                    "qc.strip_difference_mean",
                    "qc.strip_difference_stddev",
                    "qc.strip_difference_max",
                    "qc.strip_overlap_mean",
                    "qc.strip_overlap_stddev",
                    "qc.noise_level",
                    "qc.outlier_percentage",
                    "qc.classification_accuracy",
                    "qc.ground_accuracy",
                    "qc.building_accuracy",
                    "qc.vegetation_accuracy",
                    "qc.edge_matching_error",
                    "qc.blunder_detection",
                    "qc.consistency_check",
                    "qc.completeness",
                    "qc.consistency",
                    "qc.logical_consistency",
                    "qc.positional_accuracy",
                    "qc.attribute_accuracy",
                    "qc.temporal_accuracy",
                    "qc.data_quality_level",
                    "qc.quality_flag",
                    "qc.accuracy_assessment_points",
                    "qc.check_point_count",
                    "qc.reference_surface_rmse",
                    "qc.uncertainty_surface",
                    "qc.variance_map",
                    "qc.confidence_map",
                    "qc.error_model",
                ],
                "count": 50,
            },
        },
        "totals": {
            "categories": 7,
            "total_fields": 450,
        }
    }

    return INVENTORY


def main():
    output_dir = Path("dist/lidar_inventory")
    output_dir.mkdir(parents=True, exist_ok=True)
    
    inventory = generate_lidar_inventory()
    
    output_file = output_dir / "lidar_inventory.json"
    output_file.write_text(json.dumps(inventory, indent=2, sort_keys=True), encoding="utf-8")
    
    summary = {
        "generated_at": inventory["generated_at"],
        "source": inventory["source"],
        "description": inventory["description"],
        "categories": inventory["totals"]["categories"],
        "total_fields": inventory["totals"]["total_fields"],
        "field_counts_by_category": {}
    }
    
    for cat, data in inventory["categories"].items():
        summary["field_counts_by_category"][cat] = {
            "description": data["description"],
            "count": data["count"],
            "reference": data.get("reference", "N/A")
        }
    
    summary_file = output_dir / "lidar_summary.json"
    summary_file.write_text(json.dumps(summary, indent=2), encoding="utf-8")
    
    print("=" * 70)
    print("LiDAR GEOSPATIAL METADATA FIELD INVENTORY")
    print("=" * 70)
    print()
    print(f"Generated: {inventory['generated_at']}")
    print(f"Source: {inventory['source']}")
    print(f"Categories: {inventory['totals']['categories']}")
    print(f"Total Fields: {inventory['totals']['total_fields']:,}")
    print()
    print("FIELD COUNTS BY CATEGORY:")
    print("-" * 50)
    for cat, data in sorted(inventory["categories"].items(), key=lambda x: x[1]["count"], reverse=True):
        ref = data.get("reference", "")[:40]
        print(f"  {cat:25s}: {data['count']:>3} fields  [{ref}]")
    print()
    print(f"Wrote: {output_file}")
    print(f"Wrote: {summary_file}")


if __name__ == "__main__":
    main()
