#!/usr/bin/env python3
"""Virtual Reality, AR, and Metaverse Metadata Field Inventory for MetaExtract.

Covers VR headsets, Unity XR, WebXR, OpenXR, avatar systems, spatial audio, and performance metrics.
"""

from datetime import datetime, timezone
from pathlib import Path
import json


def generate_virtual_reality_inventory():
    """Generate comprehensive VR/AR/metaverse metadata field inventory."""

    INVENTORY = {
        "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "source": "OpenXR Spec, Unity XR Interaction Toolkit, WebXR API, Khronos Group, VRM Consortium, Meta Quest, Valve Index, HTC Vive",
        "description": "VR/AR/metaverse metadata including headsets, Unity XR, WebXR, OpenXR, avatar systems, spatial audio, and performance metrics",
        "categories": {
            "vr_headsets": {
                "description": "VR headset specifications and tracking parameters",
                "reference": "Meta Quest, Valve Index, HTC Vive, PlayStation VR2, Apple Vision Pro specifications",
                "fields": [
                    "headset.vendor",
                    "headset.model",
                    "headset.display_type",
                    "headset.panel_technology",
                    "headset.resolution.width",
                    "headset.resolution.height",
                    "headset.resolution.per_eye",
                    "headset.resolution.total_pixels",
                    "headset.pixel_density",
                    "headset.refresh_rate",
                    "headset.refresh_rate.min",
                    "headset.refresh_rate.max",
                    "headset.refresh_rate.recommended",
                    "headset.fov.horizontal",
                    "headset.fov.vertical",
                    "headset.fov.diagonal",
                    "headset.fov.eye_relief_adjustment",
                    "headset.lens_type",
                    "headset.ippd",
                    "headset.tracking_type",
                    "headset.tracking_inside_out",
                    "headset.tracking_outside_in",
                    "headset.tracking_base_stations",
                    "headset.tracking.controllers",
                    "headset.tracking.hands",
                    "headset.tracking.eyes",
                    "headset.tracking.face",
                    "headset.tracking.foveated",
                    "headset.tracking.haptic_feedback",
                    "headset.tracking.precision",
                    "headset.tracking.latency",
                    "headset.tracking.sample_rate",
                    "headset.controllers.tracking_type",
                    "headset.controllers.haptic_feedback",
                    "headset.controllers.gesture_recognition",
                    "headset.controllers.battery_type",
                    "headset.controllers.battery_life",
                    "headset.audio.integrated",
                    "headset.audio.spatial",
                    "headset.audio.mic",
                    "headset.audio.noise_cancellation",
                    "headset.connectivity.wireless",
                    "headset.connectivity.wifi",
                    "headset.connectivity.bluetooth",
                    "headset.connectivity.usb",
                    "headset.power.battery_type",
                    "headset.power.battery_life",
                    "headset.power.charging",
                    "headset.ergonomics.weight",
                    "headset.ergonomics.balance",
                    "headset.ergonomics.strap_type",
                    "headset.ergonomics.facial_interface",
                    "headset.software.os",
                    "headset.software.runtime",
                    "headset.supported_platforms",
                ],
                "count": 54,
            },
            "unity_xr": {
                "description": "Unity XR Interaction Toolkit and XR plugin management fields",
                "reference": "Unity XR Interaction Toolkit Documentation",
                "fields": [
                    "xr.interaction_mode",
                    "xr.input_actions",
                    "xr.action_based",
                    "xr.device_based",
                    "xr.interactors",
                    "xr.xr_interactor",
                    "xr.xr_direct_interactor",
                    "xr.xr_ray_interactor",
                    "xr.xr_offset_interactor",
                    "xr.xr_interactable",
                    "xr.grabbable",
                    "xr.selectable",
                    "xr.augmented_reality",
                    "xr.xr_origin",
                    "xr.camera_offset",
                    "xr.locomotion_provider",
                    "xr.teleportation_provider",
                    "xr.teleportation_anchor",
                    "xr.teleportation_volume",
                    "xr.snap_turn_provider",
                    "xr_continuous_turn_provider",
                    "xr.move_provider",
                    "xr.continuous_move_provider",
                    "xr.jump_provider",
                    "xr.couch_movement_provider",
                    "xr.hand_tracking",
                    "xr.hand_tracking.enable",
                    "xr.hand_tracking.joints",
                    "xr.hand_tracking.gestures",
                    "xr.hand_tracking.physicall",
                    "xr.haptic_impulse",
                    "xr.haptic_constants",
                    "xr.haptic_audio",
                    "xr.haptic_feedback_controller",
                    "xr.xr_rig",
                    "xr.tracking_origin",
                    "xr.tracking_origin_type",
                    "xr.device_position",
                    "xr.device_rotation",
                    "xr.recenter",
                    "xr.tracking_state",
                    "xr.session_state",
                    "xr.session_tracking_state_changed",
                    "xr.xr_loader",
                    "xr.xr_management",
                    "xr.立体rendering",
                    "xr.stereo_render_mode",
                    "xr.render_mode",
                    "xr.occlusion_culling",
                    "xr.near_clip_plane",
                    "xr.far_clip_plane",
                ],
                "count": 52,
            },
            "webxr": {
                "description": "WebXR Device API and immersive web sessions",
                "reference": "WebXR Device API Specification (W3C)",
                "fields": [
                    "webxr.session_mode",
                    "webxr.session_mode.immersive_vr",
                    "webxr.session_mode.immersive_ar",
                    "webxr.session_mode.inline",
                    "webxr.session_mode.immersive_session_supported",
                    "webxr.request_session",
                    "webxr.xr_session",
                    "webxr.xr_session_mode",
                    "webxr.xr_reference_space_type",
                    "webxr.xr_reference_space_type.local",
                    "webxr.xr_reference_space_type.local_floor",
                    "webxr.xr_reference_space_type.bounded_floor",
                    "webxr.xr_reference_space_type.unbounded",
                    "webxr.xr_reference_space_type.viewer",
                    "webxr.xr_reference_space_type.local_floor",
                    "webxr.xr_frame",
                    "webxr.xr_viewer_pose",
                    "webxr.xr_hand_pose",
                    "webxr.xr_anchors",
                    "webxr.xr_light_probe",
                    "webxr.xr_ref_space",
                    "webxr.xr_hit_test_source",
                    "webxr.xr_hit_test_results",
                    "webxr.xr_hit_test_result",
                    "webxr.xr_bounded_reference_space",
                    "webxr.xr_render_state",
                    "webxr.xr_render_state.base_layer",
                    "webxr.xr_render_state.depth_information",
                    "webxr.xr_layer",
                    "webxr.xr_web_gl_layer",
                    "webxr.xr_canvas",
                    "webxr.xr_compatible",
                    "webxr.xr_input_source",
                    "webxr.xr_input_source.target_ray_space",
                    "webxr.xr_input_source.grip_space",
                    "webxr.xr_input_source.handedness",
                    "webxr.xr_input_source.profiles",
                    "webxr.xr_input_source.gamepad",
                    "webxr.xr_input_source.gamepad.haptic_actuators",
                    "webxr.xr_input_source.select_event",
                    "webxr.xr_input_source.squeeze_event",
                    "webxr.xr_input_source.selectstart_event",
                    "webxr.xr_input_source.squeezestart_event",
                    "webxr.xr_input_source.selectend_event",
                    "webxr.xr_input_source.squeezeend_event",
                    "webxr.xr_input_source.pointer",
                    "webxr.xr_input_source.target_ray_mode",
                    "webxr.xr_views",
                    "webxr.xr_view",
                    "webxr.xr_view.eye",
                    "webxr.xr_view.projection_matrix",
                    "webxr.xr_view.transform",
                    "webxr.xr_view.recommended_webgl_framebuffer_width",
                    "webxr.xr_view.recommended_webgl_framebuffer_height",
                ],
                "count": 56,
            },
            "metaverse_standards": {
                "description": "OpenXR, glTF avatars, USDZ, and HVS standards",
                "reference": "OpenXR Specification, Khronos glTF, Apple USDZ, Metaverse Standards Forum",
                "fields": [
                    "openxr.instance",
                    "openxr.instance.create_info",
                    "openxr.system",
                    "openxr.system.get_properties",
                    "openxr.system.graphics_properties",
                    "openxr.system.tracking_properties",
                    "openxr.session",
                    "openxr.session.create",
                    "openxr.session.state",
                    "openxr.session.state.idle",
                    "openxr.session.state.ready",
                    "openxr.session.state.synchronized",
                    "openxr.session.state.visible",
                    "openxr.session.state.focused",
                    "openxr.session.state.stopping",
                    "openxr.session.state.lost",
                    "openxr.space",
                    "openxr.space.view",
                    "openxr.space.local",
                    "openxr.space.local_floor",
                    "openxr.space.stage",
                    "openxr.space.unbounded",
                    "openxr.reference_space",
                    "openxr.frame",
                    "openxr.frame.wait_frame",
                    "openxr.frame.begin_frame",
                    "openxr.frame.end_frame",
                    "openxr.frame.get_frame_state",
                    "openxr.action_space",
                    "openxr.action",
                    "openxr.action.type",
                    "openxr.action.action_set",
                    "openxr.binding",
                    "openxr.extension",
                    "openxr.extension.hand_tracking",
                    "openxr.extension.eye_tracking",
                    "openxr.extension.foveated_rendering",
                    "openxr.extension.hand_interaction",
                    "openxr.extension.microsoft_motion_controller",
                    "openxr.extension.huawei",
                    "openxr.extension.oculus",
                    "openxr.extension.vive",
                    "openxr.extension.render_model",
                    "openxr.extension.ultrasonic",
                    "gltf.avatar",
                    "gltf.avatar.skin",
                    "gltf.avatar.morph_targets",
                    "gltf.avatar.animations",
                    "usdz.avatar",
                    "usdz.avatar.ar_quicklook",
                    "hvs.haptic",
                    "hvs.haptic_feedback",
                ],
                "count": 56,
            },
            "avatar_systems": {
                "description": "Avatar systems including Ready Player Me, VRM, blendshapes, and inverse kinematics",
                "reference": "Ready Player Me, VRM Consortium, glTF, OpenXR Avatar",
                "fields": [
                    "avatar.platform",
                    "avatar.ready_player_me",
                    "avatar.ready_player_me.url",
                    "avatar.ready_player_me.avatar_id",
                    "avatar.ready_player_me.outfit",
                    "avatar.ready_player_me.animation",
                    "avatar.vrm",
                    "avatar.vrm.version",
                    "avatar.vrm.exporter_version",
                    "avatar.vrm.spec_version",
                    "avatar.vrm.meta",
                    "avatar.vrm.meta.name",
                    "avatar.vrm.meta.version",
                    "avatar.vrm.meta.author",
                    "avatar.vrm.meta.contact_information",
                    "avatar.vrm.meta.permission",
                    "avatar.vrm.meta.allow_modification",
                    "avatar.vrm.meta.commercial_use",
                    "avatar.vrm.meta.texture",
                    "avatar.vrm.blendshape",
                    "avatar.vrm.blendshape.mesh",
                    "avatar.vrm.blendshape.material",
                    "avatar.vrm.blendshape_group",
                    "avatar.vrm.blendshape_group.name",
                    "avatar.vrm.blendshape_group.preset_name",
                    "avatar.vrm.blendshape_group.bindings",
                    "avatar.vrm.secondary_animation",
                    "avatar.vrm.secondary_animation.bone_group",
                    "avatar.vrm.collider_group",
                    "avatar.vrm.physics_collider",
                    "avatar.vrm.physics_rigid_body",
                    "avatar.ik",
                    "avatar.ik.target",
                    "avatar.ik.joints",
                    "avatar.ik.chain_length",
                    "avatar.ik.iterations",
                    "avatar.ik.smoothing",
                    "avatar.ik.tip",
                    "avatar.ik.root",
                    "avatar.blendshape",
                    "avatar.blendshape.mesh",
                    "avatar.blendshape.morph_target",
                    "avatar.blendshape.weight",
                    "avatar.blendshape.count",
                    "avatar.blendshape.preset",
                    "avatar.blendshape.preset.neutral",
                    "avatar.blendshape.preset.a",
                    "avatar.blendshape.preset.e",
                    "avatar.blendshape.preset.i",
                    "avatar.blendshape.preset.o",
                    "avatar.blendshape.preset.u",
                    "avatar.blendshape.preset.blink",
                    "avatar.blendshape.preset.blink_l",
                    "avatar.blendshape.preset.blink_r",
                    "avatar.blendshape.preset.look_up",
                    "avatar.blendshape.preset.look_down",
                    "avatar.blendshape.preset.look_left",
                    "avatar.blendshape.preset.look_right",
                    "avatar.blendshape.preset.happy",
                    "avatar.blendshape.preset.angry",
                    "avatar.blendshape.preset.sad",
                    "avatar.blendshape.preset.surprised",
                    "avatar.blendshape.preset.relaxed",
                    "avatar.blendshape.preset.squeak",
                    "avatar.blendshape.preset.uh",
                    "avatar.blendshape.preset.eee",
                    "avatar.blendshape.preset.oo",
                    "avatar.animation",
                    "avatar.animation.clip",
                    "avatar.animation.loop",
                    "avatar.animation.speed",
                    "avatar.animation.events",
                ],
                "count": 78,
            },
            "spatial_audio": {
                "description": "Spatial audio including HRTF, ambisonics, occlusion, and distance models",
                "reference": "OpenXR Audio, Web Audio API, Ambisonics, HRTF",
                "fields": [
                    "audio.spatial",
                    "audio.hrtf",
                    "audio.hrtf.enable",
                    "audio.hrtf.panning_model",
                    "audio.hrtf.distance_model",
                    "audio.hrtf.ref_distance",
                    "audio.hrtf.max_distance",
                    "audio.hrtf.rolloff_factor",
                    "audio.hrtf.cone_inner_angle",
                    "audio.hrtf.cone_outer_angle",
                    "audio.hrtf.cone_outer_gain",
                    "audio.ambisonics",
                    "audio.ambisonics.order",
                    "audio.ambisonics.mode",
                    "audio.ambisonics.orthogonalize",
                    "audio.ambisonics.decoder",
                    "audio.ambisonics.encoder",
                    "audio.ambisonics.binaural",
                    "audio.ambisonics.fuMa",
                    "audio.ambisonics.sn3d",
                    "audio.ambisonics.n3d",
                    "audio.occlusion",
                    "audio.occlusion.enable",
                    "audio.occlusion.intensity",
                    "audio.occlusion.low_pass_filter",
                    "audio.occlusion.source_directivity",
                    "audio.distance_model",
                    "audio.distance_model.linear",
                    "audio.distance_model.inverse",
                    "audio.distance_model.exponential",
                    "audio.distance_model.custom",
                    "audio.reflection",
                    "audio.reverb",
                    "audio.reverb.room_size",
                    "audio.reverb.damping",
                    "audio.reverb.distance",
                    "audio.reverb.decay_time",
                    "audio.reverb.early_reflections",
                    "audio.reverb.late_reverb",
                    "audio.reverb.wet_dry_mix",
                    "audio.doppler",
                    "audio.doppler.enable",
                    "audio.doppler.factor",
                    "audio.doppler.velocity",
                    "audio.panning",
                    "audio.panning.stereo",
                    "audio.panning.binaural",
                    "audio.panning.3d",
                    "audio.listener",
                    "audio.listener.position",
                    "audio.listener.orientation",
                    "audio.listener.up",
                    "audio.listener.forward",
                    "audio.source",
                    "audio.source.position",
                    "audio.source.orientation",
                    "audio.source.cone_inner_angle",
                    "audio.source.cone_outer_angle",
                    "audio.source.cone_outer_gain",
                    "audio.source.distance_model",
                    "audio.source.ref_distance",
                    "audio.source.max_distance",
                    "audio.source.rolloff_factor",
                    "audio.attenuation",
                    "audio.attenuation.mode",
                    "audio.attenuation.curve",
                    "audio.headphones",
                    "audio.headphones.crosstalk_cancellation",
                    "audio.headphones.eq",
                ],
                "count": 74,
            },
            "performance_metrics": {
                "description": "Performance metrics including FPS, frame time, latency, and draw calls",
                "reference": "XR Performance, GPU Profiling, Frame Timing",
                "fields": [
                    "perf.fps",
                    "perf.fps.target",
                    "perf.fps.current",
                    "perf.fps.min",
                    "perf.fps.max",
                    "perf.fps.average",
                    "perf.frame_time",
                    "perf.frame_time.ms",
                    "perf.frame_time.target",
                    "perf.frame_time.current",
                    "perf.frame_time.variance",
                    "perf.latency",
                    "perf.latency.photon_to_photon",
                    "perf.latency.motion_to_photon",
                    "perf.latency.input_to_photon",
                    "perf.latency.rendering",
                    "perf.latency.display",
                    "perf.latency.total",
                    "perf.draw_calls",
                    "perf.draw_calls.count",
                    "perf.draw_calls.instanced",
                    "perf.draw_calls.batched",
                    "perf.triangles",
                    "perf.triangles.count",
                    "perf.triangles.visible",
                    "perf.triangles.clipped",
                    "perf.triangles.rendered",
                    "perf.textures",
                    "perf.textures.memory",
                    "perf.textures.resident",
                    "perf.textures.upload_time",
                    "perf.meshes",
                    "perf.meshes.count",
                    "perf.meshes.instances",
                    "perf.meshes.bounds",
                    "perf.memory",
                    "perf.memory.vram",
                    "perf.memory.ram",
                    "perf.memory.gpu",
                    "perf.memory.peak",
                    "perf.memory.texture_streaming",
                    "perf.cpu",
                    "perf.cpu.time",
                    "perf.cpu.frame_time",
                    "perf.cpu.render_time",
                    "perf.cpu.update_time",
                    "perf.gpu",
                    "perf.gpu.utilization",
                    "perf.gpu.memory",
                    "perf.gpu.pipeline",
                    "perf.gpu.shaders",
                    "perf.gpu.vertex_shader",
                    "perf.gpu.fragment_shader",
                    "perf.gpu.compute_shader",
                    "perf.gpu.tessellation",
                    "perf.gpu.rasterization",
                    "perf.gpu.depth_stencil",
                    "perf.gpu.blend",
                    "perf.gpu.render_targets",
                    "perf.gpu.texture_sampling",
                    "perf.gpu.bandwidth",
                    "perf.bottleneck",
                    "perf.bottleneck.cpu",
                    "perf.bottleneck.gpu",
                    "perf.bottleneck.memory",
                    "perf.bottleneck.pipeline",
                    "perf.bottleneck.thermal",
                    "perf.bottleneck.power",
                    "perf.power",
                    "perf.power.watts",
                    "perf.power.temperature",
                    "perf.power.throttle",
                    "perf.quality",
                    "perf.quality.settings",
                    "perf.quality.resolution_scale",
                    "perf.quality.anti_aliasing",
                    "perf.quality.anisotropic_filtering",
                    "perf.quality.shadow_quality",
                    "perf.quality.texture_quality",
                    "perf.quality.draw_distance",
                    "perf.vsync",
                    "perf.vsync.enabled",
                    "perf.vsync.interval",
                    "perf.vsync.hz",
                ],
                "count": 96,
            },
        },
        "totals": {
            "categories": 7,
            "total_fields": 466,
        }
    }

    return INVENTORY


def main():
    print("=" * 70)
    print("VIRTUAL REALITY, AR, AND METAVERSE METADATA FIELD INVENTORY")
    print("=" * 70)
    print()

    inventory = generate_virtual_reality_inventory()

    print(f"Generated: {inventory['generated_at']}")
    print(f"Categories: {inventory['totals']['categories']}")
    print(f"Total Fields: {inventory['totals']['total_fields']}")
    print()

    print("FIELD COUNTS BY CATEGORY:")
    print("-" * 50)
    for cat_name, cat_data in sorted(inventory['categories'].items(), key=lambda x: x[1]['count'], reverse=True):
        print(f"  {cat_name:35s}: {cat_data['count']:>4} fields")

    output_dir = Path("dist/virtual_reality_inventory")
    output_dir.mkdir(parents=True, exist_ok=True)

    output_file = output_dir / "virtual_reality_inventory.json"
    output_file.write_text(json.dumps(inventory, indent=2, sort_keys=True), encoding="utf-8")
    print()
    print(f"Wrote: {output_file}")

    summary = {
        "generated_at": inventory["generated_at"],
        "description": inventory["description"],
        "categories": {k: {"count": v["count"], "description": v["description"]} for k, v in inventory["categories"].items()},
        "totals": inventory["totals"],
    }

    summary_file = output_dir / "virtual_reality_summary.json"
    summary_file.write_text(json.dumps(summary, indent=2, sort_keys=True), encoding="utf-8")
    print(f"Wrote: {summary_file}")


if __name__ == "__main__":
    main()
