#!/usr/bin/env python3
"""Astronomy and Cosmology Metadata Field Inventory for MetaExtract.

Covers comprehensive astronomical metadata including FITS observatory parameters,
astronomical catalogs, spectral data, cosmology parameters, solar system elements,
gravitational wave events, and variable star data.
"""

from datetime import datetime, timezone
import json
from pathlib import Path


def generate_astronomy_inventory():
    """Generate comprehensive astronomy/cosmology metadata field inventory."""

    INVENTORY = {
        "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "source": "IVOA Standards, FITS 4.0, NASA/IPAC Extragalactic Database, SIMBAD, Vizier, Gaia, SDSS, LAMOST, LIGO/Virgo, Minor Planet Center",
        "description": "Comprehensive astronomy and cosmology metadata fields covering FITS observatory data, astronomical catalogs, spectral classifications, cosmological parameters, solar system orbital elements, gravitational wave events, and variable star characteristics",
        "categories": {
            "fits_observatory": {
                "description": "FITS telescope parameters, pointing, tracking, and exposure metadata",
                "reference": "FITS 4.0 Specification, IVOA Observation Data Model",
                "fields": [
                    "fits.telescope.name",
                    "fits.telescope.aperture",
                    "fits.telescope.focal_length",
                    "fits.telescope.focal_ratio",
                    "fits.telescope.mount_type",
                    "fits.telescope.encoder_resolution",
                    "fits.telescope.pointing_error",
                    "fits.telescope.tracking_accuracy",
                    "fits.telescope.tracking_mode",
                    "fits.telescope.guide_mode",
                    "fits.telescope. autoguider",
                    "fits.telescope.guider_camera",
                    "fits.telescope.guider_fov",
                    "fits.telescope.pointing.ra",
                    "fits.telescope.pointing.dec",
                    "fits.telescope.pointing.azimuth",
                    "fits.telescope.pointing.elevation",
                    "fits.telescope.pointing.ha",
                    "fits.telescope.pointing.airmass",
                    "fits.telescope.pointing.parallactic_angle",
                    "fits.telescope.tracking.sidereal",
                    "fits.telescope.tracking.solar",
                    "fits.telescope.tracking.lunar",
                    "fits.telescope.tracking.custom",
                    "fits.telescope.observation_mode",
                    "fits.telescope.dither_pattern",
                    "fits.telescope.dither_steps",
                    "fits.telescope.dither_offset",
                    "fits.telescope.exposure.time",
                    "fits.exposure.start_time",
                    "fits.exposure.end_time",
                    "fits.exposure.mid_time",
                    "fits.exposure.duration",
                    "fits.exposure.cycles",
                    "fits.exposure.cycle_time",
                    "fits.exposure.dead_time",
                    "fits.exposure.readout_time",
                    "fits.exposure.overhead",
                    "fits.instrument.name",
                    "fits.instrument.detector",
                    "fits.instrument.detector_type",
                    "fits.instrument.detector_size",
                    "fits.instrument.pixel_size",
                    "fits.instrument.pixel_scale",
                    "fits.instrument.field_of_view",
                    "fits.instrument.readout_mode",
                    "fits.instrument.gain",
                    "fits.instrument.read_noise",
                    "fits.instrument.dark_current",
                    "fits.instrument.saturation_level",
                    "fits.instrument.nonlinearity",
                    "fits.instrument.cooling",
                    "fits.instrument.cooling_setpoint",
                    "fits.instrument.filter_wheel",
                    "fits.instrument.filter_name",
                    "fits.instrument.filter_band",
                    "fits.instrument.filter_center_wavelength",
                    "fits.instrument.filter_bandwidth",
                    "fits.instrument.filter_transmission",
                    "fits.instrument.slit_width",
                    "fits.instrument.slit_length",
                    "fits.instrument.grism",
                    "fits.instrument.grating",
                    "fits.instrument.grating_angle",
                    "fits.instrument.dispersion",
                    "fits.instrument.resolution",
                    "fits.instrument.collimate",
                    "fits.instrument.camera",
                    "fits.instrument.foreoptics",
                    "fits.instrument.aperture_mask",
                    "fits.observer.name",
                    "fits.observer.affiliation",
                    "fits.observation.program",
                    "fits.observation.proposal_id",
                    "fits.observation.target_name",
                    "fits.observation.target_type",
                    "fits.observation.coordinates.ra",
                    "fits.observation.coordinates.dec",
                    "fits.observation.coordinates.epoch",
                    "fits.observation.coordinates.system",
                ],
                "count": 80,
            },
            "astronomical_catalogs": {
                "description": "Astronomical catalog entries from Vizier, SIMBAD, Gaia, Hipparcos, and major surveys",
                "reference": "Vizier Services, SIMBAD Database, ESA Gaia Archive, CDS Strasbourg",
                "fields": [
                    "catalog.vizier.name",
                    "catalog.vizier.table_id",
                    "catalog.vizier.row_count",
                    "catalog.vizier.column_count",
                    "catalog.simbad.main_id",
                    "catalog.simbad.other_names",
                    "catalog.simbad.object_type",
                    "catalog.simbad.coordinates.ra",
                    "catalog.simbad.coordinates.dec",
                    "catalog.simbad.coordinates.epoch",
                    "catalog.simbad.coordinates.system",
                    "catalog.simbad.redshift",
                    "catalog.simbad.radial_velocity",
                    "catalog.simbad.spectral_type",
                    "catalog.simbad.magnitude.v",
                    "catalog.simbad.magnitude.b",
                    "catalog.simbad.magnitude.j",
                    "catalog.simbad.magnitude.h",
                    "catalog.simbad.magnitude.k",
                    "catalog.gaia.source_id",
                    "catalog.gaia.designation",
                    "catalog.gaia.ra",
                    "catalog.gaia.dec",
                    "catalog.gaia.parallax",
                    "catalog.gaia.parallax_error",
                    "catalog.gaia.proper_motion.ra",
                    "catalog.gaia.proper_motion.dec",
                    "catalog.gaia.pm_error",
                    "catalog.gaia.radial_velocity",
                    "catalog.gaia.rv_error",
                    "catalog.gaia.phot_g_mean_mag",
                    "catalog.gaia.phot_bp_mean_mag",
                    "catalog.gaia.phot_rp_mean_mag",
                    "catalog.gaia.phot_bp_rp_excess_factor",
                    "catalog.gaia.teff_gspphot",
                    "catalog.gaia.log_g_gspphot",
                    "catalog.gaia.mh_gspphot",
                    "catalog.gaia.distance_gspphot",
                    "catalog.gaia.agn_flag",
                    "catalog.gaia.duplicated_source",
                    "catalog.hipparcos.hip_id",
                    "catalog.hipparcos.prox",
                    "catalog.hipparcos.ra",
                    "catalog.hipparcos.dec",
                    "catalog.hipparcos.parallax",
                    "catalog.hipparcos.hpmag",
                    "catalog.hipparcos.bv_color",
                    "catalog.hipparcos.spectral_type",
                    "catalog.hipparcos.var_flag",
                    "catalog.hipparcos.multiple_flag",
                    "catalog.gliese.gliese_id",
                    "catalog.gliese.coordinates",
                    "catalog.gliese.parallax",
                    "catalog.gliese.magnitude.v",
                    "catalog.gliese.spectral_type",
                    "catalog.gliese.proper_motion",
                    "catalog.tycho.tyc_id",
                    "catalog.tycho.hip_id",
                    "catalog.tycho.vt_mag",
                    "catalog.tycho.bt_mag",
                    "catalog.tycho.proper_motion",
                    "catalog.2mass.designation",
                    "catalog.2mass.ra",
                    "catalog.2mass.dec",
                    "catalog.2mass.j_mag",
                    "catalog.2mass.h_mag",
                    "catalog.2mass.k_mag",
                    "catalog.2mass.quality_flag",
                    "catalog.ps1.object_id",
                    "catalog.ps1.primary",
                    "catalog.ps1.ra",
                    "catalog.ps1.dec",
                    "catalog.ps1.g_mean",
                    "catalog.ps1.r_mean",
                    "catalog.ps1.i_mean",
                    "catalog.ps1.z_mean",
                    "catalog.ps1.y_mean",
                ],
                "count": 70,
            },
            "spectral_data": {
                "description": "Spectral data metadata from SDSS, LAMOST, spectral classification, and line lists",
                "reference": "SDSS DR17, LAMOST DR8, MILES Spectral Library, VALD",
                "fields": [
                    "spectral.survey.name",
                    "spectral.survey.mjd",
                    "spectral.survey.plate",
                    "spectral.survey.fiber",
                    "spectral.survey.fiberid",
                    "spectral.survey.run2d",
                    "spectral.survey.run1d",
                    "spectral.sdss.specobj_id",
                    "spectral.sdss.bestobj_id",
                    "spectral.sdss.targetobj_id",
                    "spectral.sdss.plate_id",
                    "spectral.sdss.mjd",
                    "spectral.sdss.fiberid",
                    "spectral.sdss.ra",
                    "spectral.sdss.dec",
                    "spectral.sdss.class",
                    "spectral.sdss.subclass",
                    "spectral.sdss.z",
                    "spectral.sdss.z_err",
                    "spectral.sdss.z_conf",
                    "spectral.sdss.z_warning",
                    "spectral.sdss.elodie.object",
                    "spectral.sdss.elodie.spectral_type",
                    "spectral.sdss.elodie.teff",
                    "spectral.sdss.elodie.log_g",
                    "spectral.sdss.elodie.feh",
                    "spectral.sdss.elodie.ebv",
                    "spectral.lamost.lamost_id",
                    "spectral.lamost.obsdate",
                    "spectral.lamost.snr",
                    "spectral.lamost.target_type",
                    "spectral.lamost.subclass",
                    "spectral.lamost.redshift",
                    "spectral.lamost.teff",
                    "spectral.lamost.log_g",
                    "spectral.lamost.feh",
                    "spectral.line_id.element",
                    "spectral.line_id.wavelength",
                    "spectral.line_id.central_wavelength",
                    "spectral.line_id.species",
                    "spectral.line_id.ionization",
                    "spectral.line_id.excitation_potential",
                    "spectral.line_id.log_gf",
                    "spectral.line_id.equivalent_width",
                    "spectral.line_id.flux",
                    "spectral.line_id.amplitude",
                    "spectral.line_id.contrast",
                    "spectral.line_id.fwhm",
                    "spectral.classification.spectral_type",
                    "spectral.classification.luminosity_class",
                    "spectral.classification.metallicity",
                    "spectral.classification.microturbulence",
                    "spectral.classification.surface_gravity",
                    "spectral.classification.effective_temperature",
                    "spectral.classification.binary_flag",
                    "spectral.classification.emission_flag",
                    "spectral.classification.peculiarity",
                    "spectral.continuum.normalization",
                    "spectral.continuum.order",
                    "spectral.continuum.smoothing",
                    "spectral.continuum.fit_flags",
                    "spectral.snr.value",
                    "spectral.snr.blue",
                    "spectral.snr.red",
                    "spectral.snr.median",
                ],
                "count": 60,
            },
            "cosmology": {
                "description": "Cosmological parameters, CMB data, dark energy, and Hubble constant measurements",
                "reference": "Planck 2018 Results, WMAP9, Hubble Space Telescope Key Projects",
                "fields": [
                    "cosmology.h0",
                    "cosmology.h0_error",
                    "cosmology.omega_m",
                    "cosmology.omega_m_error",
                    "cosmology.omega_l",
                    "cosmology.omega_l_error",
                    "cosmology.omega_b",
                    "cosmology.omega_b_error",
                    "cosmology.omega_r",
                    "cosmology.omega_k",
                    "cosmology.omega_cdm",
                    "cosmology.sigma_8",
                    "cosmology.sigma_8_error",
                    "cosmology.n_s",
                    "cosmology.n_s_error",
                    "cosmology.tau",
                    "cosmology.tau_error",
                    "cosmology.y_he",
                    "cosmology.t_cmb",
                    "cosmology.planck_likelihood",
                    "cosmology.planck_ta",
                    "cosmology.planck_ta_error",
                    "cosmology.theta_s",
                    "cosmology.theta_s_error",
                    "cosmology.r",
                    "cosmology.r_upper_limit",
                    "cosmology.a_s",
                    "cosmology.a_s_error",
                    "cosmology.n_run",
                    "cosmology.n_run_error",
                    "cosmology.dark_energy.equation_of_state",
                    "cosmology.dark_energy.w0",
                    "cosmology.dark_energy.wa",
                    "cosmology.dark_energy.wp",
                    "cosmology.dark_energy.de_density",
                    "cosmology.ho_stress",
                    "cosmology.hubble_constant_local",
                    "cosmology.hubble_constant_early",
                    "cosmology.hubble_constant_tension",
                    "cosmology.cmbr.temperature",
                    "cosmology.cmbr.temperature_rms",
                    "cosmology.cmbr.polarization",
                    "cosmology.cmbr.power_spectrum.ell_max",
                    "cosmology.cmbr.power_spectrum.ell_min",
                    "cosmology.cmbr.power_spectrum.dl_tt",
                    "cosmology.cmbr.power_spectrum.dl_ee",
                    "cosmology.cmbr.power_spectrum.dl_te",
                    "cosmology.cmbr.power_spectrum.dl_bb",
                    "cosmology.age_universe",
                    "cosmology.age_universe_error",
                    "cosmology.age_at_z",
                    "cosmology.lookback_time",
                    "cosmology.comoving_distance",
                    "cosmology.luminosity_distance",
                    "cosmology.angular_diameter_distance",
                    "cosmology.distance_modulus",
                    "cosmology.redshift_distance_relation",
                    "cosmology.primordial_spectrum.amplitude",
                    "cosmology.primordial_spectrum.scalar_spectral_index",
                    "cosmology.tensor_to_scalar_ratio",
                    "cosmology.neutrino_mass_sum",
                    "cosmology.neutrino_eff_number",
                    "cosmology.baryon_density",
                    "cosmology.dark_matter_density",
                ],
                "count": 60,
            },
            "solar_system": {
                "description": "Planetary, asteroid, comet, and solar system body orbital elements and physical parameters",
                "reference": "NASA JPL Horizons, Minor Planet Center, IAU Working Group",
                "fields": [
                    "orbital.semimajor_axis",
                    "orbital.semimajor_axis_error",
                    "orbital.eccentricity",
                    "orbital.eccentricity_error",
                    "orbital.inclination",
                    "orbital.inclination_error",
                    "orbital.longitude_of_ascending_node",
                    "orbital.longitude_of_ascending_node_error",
                    "orbital.argument_of_perihelion",
                    "orbital.argument_of_perihelion_error",
                    "orbital.mean_anomaly",
                    "orbital.mean_anomaly_error",
                    "orbital.true_anomaly",
                    "orbital.time_of_perihelion_passage",
                    "orbital.time_of_perihelion_passage_error",
                    "orbital.period",
                    "orbital.period_error",
                    "orbital.daily_motion",
                    "orbital.mean_motion",
                    "orbital.mean_motion_error",
                    "orbital.sidereal_period",
                    "orbital.synodic_period",
                    "orbital.orbital_energy",
                    "orbital.orbital_velocity",
                    "orbital.aphelion",
                    "orbital.perihelion",
                    "orbital.perihelion_distance",
                    "orbital.aphelion_distance",
                    "orbital.orbit_class",
                    "orbital.moid",
                    "orbital.moid_jupiter",
                    "orbital.tisserand_parameter",
                    "orbital.kozai_frequency",
                    "orbital.nongravitational_parameter.A1",
                    "orbital.nongravitational_parameter.A2",
                    "orbital.nongravitational_parameter.A3",
                    "orbital.comet.activity.onset",
                    "orbital.comet.activity.stop",
                    "orbital.comet.nucleus.size",
                    "orbital.comet.nucleus.albedo",
                    "orbital.comet.coma.size",
                    "orbital.comet.tail.length",
                    "orbital.asteroid.diameter",
                    "orbital.asteroid.diameter_error",
                    "orbital.asteroid.albedo",
                    "orbital.asteroid.albedo_error",
                    "orbital.asteroid.mass",
                    "orbital.asteroid.mass_error",
                    "orbital.asteroid.density",
                    "orbital.asteroid.taxonomic_class",
                    "orbital.asteroid.rotation_period",
                    "orbital.asteroid.rotation_period_error",
                    "orbital.asteroid.obliquity",
                    "orbital.asteroid.yarkovsky_parameter",
                    "orbital.planetary.obliquity",
                    "orbital.planetary.precession_rate",
                    "orbital.planetary.nutation",
                    "orbital.planetary.orbital_resonance",
                    "orbital.planetary.moon_count",
                    "orbital.planetary.ring_system",
                    "orbital.planetary.atmospheric_composition",
                    "orbital.planetary.magnetic_moment",
                    "orbital.planetary.lambert_law",
                    "orbital.planetary.bond_albedo",
                    "orbital.planetary.geometric_albedo",
                    "orbital.planetary.phase_integral",
                    "orbital.planetary.hili",
                    "orbital.planetary.limb_darkening",
                    "orbital.planetary.occultation",
                    "orbital.tno.detection",
                    "orbital.tno.sedna_like",
                ],
                "count": 70,
            },
            "gravitational_waves": {
                "description": "LIGO/Virgo/KAGRA gravitational wave event metadata and strain data",
                "reference": "LIGO Scientific Collaboration, Virgo Collaboration, GWTC Catalogs",
                "fields": [
                    "gw.event_id",
                    "gw.event_name",
                    "gw.observation_time",
                    "gw.observation_time_start",
                    "gw.observation_time_end",
                    "gw.detection_statistic",
                    "gw.false_alarm_rate",
                    "gw.false_alarm_rate_error",
                    "gw.false_alarm_probability",
                    "gw.probability_of_astrophysical_origin",
                    "gw.probability_of_noise",
                    "gw.classification.bns",
                    "gw.classification.nsbh",
                    "gw.classification.bbh",
                    "gw.classification.mass_gap",
                    "gw.classification.terrestrial",
                    "gw.classification.igg",
                    "gw.source.redshift",
                    "gw.source.redshift_error",
                    "gw.source.luminosity_distance",
                    "gw.source.luminosity_distance_error",
                    "gw.source.chirp_mass",
                    "gw.source.chirp_mass_error",
                    "gw.source.mass_1",
                    "gw.source.mass_1_error",
                    "gw.source.mass_2",
                    "gw.source.mass_2_error",
                    "gw.source.total_mass",
                    "gw.source.total_mass_error",
                    "gw.source.final_mass",
                    "gw.source.final_mass_error",
                    "gw.source.final_spin",
                    "gw.source.final_spin_error",
                    "gw.source.merger_type",
                    "gw.source.sky_location.ra",
                    "gw.source.sky_location.dec",
                    "gw.source.sky_location.error",
                    "gw.source.sky_location.probability_map",
                    "gw.strain.sample_rate",
                    "gw.strain.duration",
                    "gw.strain.start_time",
                    "gw.strain.central_frequency",
                    "gw.strain.frequency_bandwidth",
                    "gw.strain.snr",
                    "gw.strain.snr_network",
                    "gw.detector.hanford.snr",
                    "gw.detector.livingston.snr",
                    "gw.detector.virgo.snr",
                    "gw.detector.kagra.snr",
                    "gw.detector.network.coherence",
                    "gw.detector.network.localization",
                ],
                "count": 50,
            },
            "variable_stars": {
                "description": "Variable star light curves, periods, amplitudes, and classification types",
                "reference": "AAVSO, GCVS, OGLE, ASAS-SN, ZTF, TESS",
                "fields": [
                    "variable.period",
                    "variable.period_error",
                    "variable.period2",
                    "variable.period2_error",
                    "variable.amplitude",
                    "variable.amplitude_error",
                    "variable.amplitude_b",
                    "variable.amplitude_v",
                    "variable.amplitude_r",
                    "variable.amplitude_i",
                    "variable.amplitude_g",
                    "variable.maximum_magnitude",
                    "variable.minimum_magnitude",
                    "variable.maximum_magnitude_jd",
                    "variable.minimum_magnitude_jd",
                    "variable.epoch_maximum",
                    "variable.epoch_maximum_error",
                    "variable.epoch_minimum",
                    "variable.epoch_minimum_error",
                    "variable.rise_time",
                    "variable.fall_time",
                    "variable.duty_cycle",
                    "variable.light_curve.type",
                    "variable.light_curve.symmetry",
                    "variable.light_curve.observations",
                    "variable.light_curve.time_coverage",
                    "variable.light_curve.sampling",
                    "variable.type.rr_lyrae",
                    "variable.type.rrab",
                    "variable.type.rrc",
                    "variable.type.rrd",
                    "variable.type.cepheid",
                    "variable.type.cepheid_classic",
                    "variable.type.cepheid_type2",
                    "variable.type.angauss",
                    "variable.type.eb_eclipsing",
                    "variable.type.eb_detached",
                    "variable.type.eb_semidetached",
                    "variable.type.eb_contact",
                    "variable.type.mira",
                    "variable.type.semiregular",
                    "variable.type.lpv",
                    "variable.type.long_period_variable",
                    "variable.type.delta_scuti",
                    "variable.type.roth",
                    "variable.type.roap",
                    "variable.type.spots",
                    "variable.type.flare",
                    "variable.type.cataclysmic",
                    "variable.type.dwarf_nova",
                    "variable.type.nova",
                    "variable.type.supernova",
                    "variable.type.sn_ia",
                    "variable.type.sn_ibc",
                    "variable.type.sn_iin",
                    "variable.type.yso",
                    "variable.type.ae",
                    "variable.type.ellipsoidal",
                    "variable.magnitude.system",
                    "variable.magnitude.mean",
                    "variable.magnitude.median",
                    "variable.magnitude.mode",
                    "variable.magnitude.uncertainty",
                    "variable.survey.name",
                    "variable.survey.reference_epoch",
                    "variable.survey.zero_point",
                    "variable.star_id",
                    "variable.designation",
                    "variable.alternate_names",
                ],
                "count": 60,
            },
        },
        "totals": {
            "categories": 7,
            "total_fields": 450,
        }
    }

    return INVENTORY


def main():
    print("=" * 70)
    print("ASTRONOMY AND COSMOLOGY METADATA FIELD INVENTORY")
    print("=" * 70)
    print()

    inventory = generate_astronomy_inventory()

    print(f"Generated: {inventory['generated_at']}")
    print(f"Categories: {inventory['totals']['categories']}")
    print(f"Total Fields: {inventory['totals']['total_fields']}")
    print()

    print("FIELD COUNTS BY CATEGORY:")
    print("-" * 50)
    for cat_name, cat_data in sorted(inventory['categories'].items(), key=lambda x: x[1]['count'], reverse=True):
        print(f"  {cat_name:35s}: {cat_data['count']:>4} fields")

    output_dir = Path("dist/astronomy_inventory")
    output_dir.mkdir(parents=True, exist_ok=True)

    output_file = output_dir / "astronomy_inventory.json"
    output_file.write_text(json.dumps(inventory, indent=2, sort_keys=True), encoding="utf-8")
    print()
    print(f"Wrote: {output_file}")

    summary = {
        "generated_at": inventory["generated_at"],
        "description": inventory["description"],
        "categories": {k: {"count": v["count"], "description": v["description"]} for k, v in inventory["categories"].items()},
        "totals": inventory["totals"],
    }

    summary_file = output_dir / "astronomy_summary.json"
    summary_file.write_text(json.dumps(summary, indent=2, sort_keys=True), encoding="utf-8")
    print(f"Wrote: {summary_file}")


if __name__ == "__main__":
    main()
