#!/usr/bin/env python3
"""Nuclear/Radiation Monitoring Metadata Field Inventory for MetaExtract.

Covers radiation detection, nuclear medicine, environmental monitoring,
reactor operations, IAEA safeguards, and radiation safety standards.
"""

from datetime import datetime, timezone
import json
from pathlib import Path


def generate_nuclear_inventory():
    """Generate comprehensive nuclear/radiation monitoring metadata field inventory."""

    INVENTORY = {
        "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "source": "IAEA Safeguards, IEC 62387, ISO 8529, ANSI N42, NRC, ICRP, NCRP",
        "description": "Nuclear/radiation monitoring metadata fields for detection, medicine, environment, reactor operations, IAEA safeguards, and radiation safety",
        "categories": {
            "radiation_detection": {
                "description": "Radiation detection equipment and measurement fields",
                "reference": "IEC 62387, ANSI N42, ISO 8529, IAEA NMR",
                "fields": [
                    "detector.type",
                    "detector.model",
                    "detector.manufacturer",
                    "detector.serial_number",
                    "detector.count_rate",
                    "detector.count_rate.cpm",
                    "detector.count_rate.dpm",
                    "detector.count_rate.max",
                    "detector.count_rate.avg",
                    "detector.count_rate.live_time",
                    "detector.count_rate.real_time",
                    "detector.energy_range",
                    "detector.energy_range.min",
                    "detector.energy_range.max",
                    "detector.efficiency",
                    "detector.efficiency.absolute",
                    "detector.efficiency.intrinsic",
                    "detector.efficiency.fwhm",
                    "detector.fwhm",
                    "detector.resolution",
                    "detector.resolution.energy",
                    "detector.resolution.time",
                    "detector.sensitivity",
                    "detector.background",
                    "detector.background.count_rate",
                    "detector.background.measurement_time",
                    "detector.background.corrected",
                    "detector.alarm.setpoint",
                    "detector.alarm.threshold",
                    "detector.alarm.mode",
                    "detector.alarm.sound_enabled",
                    "detector.alarm.vibration_enabled",
                    "detector.calibration.date",
                    "detector.calibration.next_due",
                    "detector.calibration.source",
                    "detector.calibration.source.activity",
                    "detector.calibration.source.date",
                    "detector.calibration.factor",
                    "detector.calibration.offset",
                    "detector.calibration.uncertainty",
                    "geiger_counter.tube_type",
                    "geiger_counter.tube_diameter",
                    "geiger_counter.tube_length",
                    "geiger_counter.voltage",
                    "geiger_counter.voltage.nominal",
                    "geiger_counter.voltage.min",
                    "geiger_counter.voltage.max",
                    "geiger_counter.dead_time",
                    "geiger_counter.plateau_length",
                    "geiger_counter.plateau_slope",
                    "scintillation.detector_type",
                    "scintillation.crystal_material",
                    "scintillation.crystal_size",
                    "scintillation.crystal_shape",
                    "scintillation.pm_tube_model",
                    "scintillation.pm_tube_voltage",
                    "scintillation.gain",
                    "scintillation.peak_position",
                    "scintillation.compton_edge",
                    "scintillation.backscatter_peak",
                    "scintillation.total_peak_ratio",
                    "semiconductor.detector_type",
                    "semiconductor.detector_material",
                    "semiconductor.detector_thickness",
                    "semiconductor.detector_area",
                    "semiconductor.dead_layer",
                    "semiconductor.cooling",
                    "semiconductor.preamp_type",
                    "semiconductor.preamp_gain",
                    "semiconductor.processing_time",
                    "spectrometer.manufacturer",
                    "spectrometer.model",
                    "spectrometer.channels",
                    "spectrometer.channel_count",
                    "spectrometer.energy_calibration",
                    "spectrometer.gain_coarse",
                    "spectrometer.gain_fine",
                    "spectrometer.zero_offset",
                    "spectrometer.nonlinearity",
                    "spectrometer.gaussian_fit",
                    "spectrometer.peak_search",
                    "spectrometer.roi",
                    "spectrometer.roi.start",
                    "spectrometer.roi.end",
                    "spectrometer.roi.background",
                    "spectrometer.net_area",
                    "spectrometer.uncertainty",
                    "spectrometer.mdac",
                    "spectrometer.mca_mode",
                    "spectrometer.preset_time",
                    "spectrometer.preset_count",
                    "spectrometer.live_timer",
                    "spectrometer.real_timer",
                    "neutron_detector.type",
                    "neutron_detector.efficiency",
                    "neutron_detector.bf3_tube_pressure",
                    "neutron_detector.he3_pressure",
                    "neutron_detector.moderator_material",
                    "neutron_detector.gamma_rejection",
                    "neutron_detector.alpha_ratio",
                    "neutron_detector.cross_sensitivity",
                    "personal_dosimeter.type",
                    "personal_dosimeter.model",
                    "personal_dosimeter.technology",
                    "personal_dosimeter.dose_range",
                    "personal_dosimeter.energy_range",
                    "personal_dosimeter.angle_response",
                    "personal_dosimeter.alarm_thresholds",
                    "personal_dosimeter.data_logging",
                    "personal_dosimeter.interface",
                    "area_monitor.model",
                    "area_monitor.channels",
                    "area_monitor.alarm_zones",
                    "area_monitor.siren_power",
                    "area_monitor.strobe_power",
                    "area_monitor.communication",
                ],
                "count": 120,
            },
            "nuclear_medicine": {
                "description": "Nuclear medicine imaging and radiopharmaceutical fields",
                "reference": "DICOM, NEMA, ICRU, IAEA TECDOC, EANM, SNMMI",
                "fields": [
                    "pet.scanner_type",
                    "pet.scanner_model",
                    "pet.scanner_manufacturer",
                    "pet.detector_type",
                    "pet.crystal_material",
                    "pet.crystal_thickness",
                    "pet.crystal_size",
                    "pet.number_of_detectors",
                    "pet.number_of_blocks",
                    "pet.number_of_crystals",
                    "pet.axial_fov",
                    "pet.transaxial_fov",
                    "pet.number_of_slices",
                    "pet.slice_thickness",
                    "pet.spatial_resolution",
                    "pet.spatial_resolution.fwhm",
                    "pet.spatial_resolution.tangential",
                    "pet.spatial_resolution.radial",
                    "pet.sensitivity",
                    "pet.scatter_fraction",
                    "pet.true_count_rate",
                    "pet.random_count_rate",
                    "pet.scatter_count_rate",
                    "pet.dead_time",
                    "pet.necr",
                    "pet.scatter_peak",
                    "pet.random_peak",
                    "pet.prompt_peak",
                    "pet.tof_resolution",
                    "pet.tof_timing_resolution",
                    "pet.suv_max",
                    "pet.suv_mean",
                    "pet.suv_peak",
                    "pet.suvbw",
                    "pet.suvbsa",
                    "pet.suvlbm",
                    "pet.suvff",
                    "pet.metabolic_rate",
                    "pet.k1",
                    "pet.k2",
                    "pet.k3",
                    "pet.k4",
                    "pet.vt",
                    "pet.vt_reference",
                    "pet.registration_method",
                    "pet.attenuation_correction",
                    "pet.scatter_correction",
                    "pet.random_correction",
                    "pet.dead_time_correction",
                    "pet.decay_correction",
                    "pet.reconstruction_algorithm",
                    "pet.iterations",
                    "pet.subsets",
                    "pet.filter_type",
                    "pet.filter_cutoff",
                    "pet.post_filter",
                    "pet.osem_params",
                    "pet.tof_weighting",
                    "pet.psf_modeling",
                    "spect.scanner_type",
                    "spect.scanner_model",
                    "spect.collimator_type",
                    "spect.collimator.hole_diameter",
                    "spect.collimator.hole_length",
                    "spect.collimator.septal_thickness",
                    "spect.collimator.material",
                    "spect.collimator_names",
                    "spect.number_of_heads",
                    "spect.angular_coverage",
                    "spect.total_crystal_area",
                    "spect.spatial_resolution",
                    "spect.sensitivity",
                    "spect.energy_resolution",
                    "spect.window_settings",
                    "spect.window.width",
                    "spect.window.center",
                    "spect.scout_scan",
                    "spect.reconstruction_method",
                    "spect.filter_backprojection",
                    "spect.iterative_reconstruction",
                    "spect.osem_iterations",
                    "spect.subsets",
                    "spect.filter_type",
                    "spect.filter_resolution",
                    "radiopharma.isotope",
                    "radiopharma.halflife",
                    "radiopharma.halflife.physical",
                    "radiopharma.halflife.biologic",
                    "radiopharma.halflife.effective",
                    "radiopharma.decay_constant",
                    "radiopharma.energy",
                    "radiopharma.energy.gamma",
                    "radiopharma.energy.beta_max",
                    "radiopharma.particle_type",
                    "radiopharma.chemical_form",
                    "radiopharma.administration_route",
                    "radiopharma.administered_activity",
                    "radiopharma.administered_time",
                    "radiopharma.injection_time",
                    "radiopharma.injection_site",
                    "radiopharma.injection_volume",
                    "radiopharma.blood_sample_time",
                    "radiopharma.plasma_activity",
                    "radiopharma.plasma_activity_concentration",
                    "radiopharma.parent_fraction",
                    "radiopharma.metabolite_fraction",
                    "radiopharma.remaining_fraction",
                    "dicom.radiation_type",
                    "dicom.radiation_measurement_units",
                    "dicom.exposure_index",
                    "dicom.target_exposure_index",
                    "dicom.deviation_index",
                    "dicom.xray_output",
                    "dicom.kvp",
                    "dicom.ma",
                    "dicom.exposure_time",
                    "dicom.total_filter_material",
                    "dicom.total_filter_thickness",
                    "dicom.radiation_dose_sequence",
                    "dicom.irradiation_event_uid",
                    "dicom.specific_characteristics",
                    "dicom.irradiation_event_type",
                    "dicom.landmark_point",
                    "dicom.entrance_exposure",
                    "dicom.exposed_area",
                    "dicom.part_selection",
                ],
                "count": 110,
            },
            "environmental_monitoring": {
                "description": "Environmental radiation monitoring and contamination fields",
                "reference": "IAEA TECDOC, EPA, NRC, ISO 10703, IEC 62396",
                "fields": [
                    "env.station_id",
                    "env.station_name",
                    "env.station_type",
                    "env.latitude",
                    "env.longitude",
                    "env.elevation",
                    "env.location_description",
                    "env.air_sample_id",
                    "env.air_sample.date",
                    "env.air_sample.time",
                    "env.air_sample.volume",
                    "env.air_sample.flow_rate",
                    "env.air_sample.flow_rate.actual",
                    "env.air_sample.filter_type",
                    "env.air_sample.filter_material",
                    "env.air_sample.filter_efficiency",
                    "env.air_sample.count_rate",
                    "env.air_sample.background_rate",
                    "env.air_sample.net_count_rate",
                    "env.air_sample.activity",
                    "env.air_sample.activity.concentration",
                    "env.air_sample.activity.date",
                    "env.air_sample.activity.uncertainty",
                    "env.air_sample.detection_limit",
                    "env.water_sample_id",
                    "env.water_sample.type",
                    "env.water_sample.source",
                    "env.water_sample.location",
                    "env.water_sample.depth",
                    "env.water_sample.date",
                    "env.water_sample.time",
                    "env.water_sample.volume",
                    "env.water_sample.preservation_method",
                    "env.water_sample.ph",
                    "env.water_sample.conductivity",
                    "env.water_sample.activity",
                    "env.water_sample.h3_concentration",
                    "env.water_sample.cs137_concentration",
                    "env.water_sample.sr90_concentration",
                    "env.water_sample.uranium_concentration",
                    "env.water_sample.plutonium_concentration",
                    "env.soil_sample_id",
                    "env.soil_sample.location",
                    "env.soil_sample.depth",
                    "env.soil_sample.date",
                    "env.soil_sample.time",
                    "env.soil_sample.weight",
                    "env.soil_sample.moisture_content",
                    "env.soil_sample.dry_weight",
                    "env.soil_sample.homogenization_method",
                    "env.soil_sample.count_rate",
                    "env.soil_sample.background",
                    "env.soil_sample.activity",
                    "env.soil_sample.activity_concentration",
                    "env.soil_sample.cs137",
                    "env.soil_sample.cs134",
                    "env.soil_sample.k40",
                    "env.soil_sample.ra226",
                    "env.soil_sample.th232",
                    "env.soil_sample.u238",
                    "env.soil_sample.u235",
                    "env.soil_sample.pu239",
                    "env.soil_sample.am241",
                    "env.ground_station.count_rate",
                    "env.ground_station.rate_avg",
                    "env.ground_station.rate_max",
                    "env.ground_station.rate_min",
                    "env.ground_station.rate_std",
                    "env.ground_station.dose_rate",
                    "env.ground_station.dose_rate.unit",
                    "env.ground_station.weather",
                    "env.ground_station.temperature",
                    "env.ground_station.humidity",
                    "env.ground_station.pressure",
                    "env.ground_station.wind_speed",
                    "env.ground_station.wind_direction",
                    "env.ground_station.precipitation",
                    "env.ground_station.solar_activity",
                    "env.ground_station.geo_magnetic_activity",
                    "env.ground_station.gps_time",
                ],
                "count": 100,
            },
            "reactor_operations": {
                "description": "Nuclear power plant operations and monitoring fields",
                "reference": "IAEA, NRC, WANO, INPO, ANSI/ANS standards",
                "fields": [
                    "reactor.reactor_type",
                    "reactor.reactor_model",
                    "reactor.thermal_power",
                    "reactor.thermal_power.mwt",
                    "reactor.electrical_power",
                    "reactor.electrical_power.gross",
                    "reactor.electrical_power.net",
                    "reactor.efficiency",
                    "reactor.core_power_density",
                    "reactor.cycle_length",
                    "reactor.cycle_number",
                    "reactor.days_since_startup",
                    "reactor.days_until_shutdown",
                    "reactor.fuel_assemblies",
                    "reactor.fuel_type",
                    "reactor.enrichment.u235_initial",
                    "reactor.enrichment.u235_average",
                    "reactor.enrichment.u235_discharge",
                    "reactor.burnup",
                    "reactor.burnup.cycle",
                    "reactor.burnup.cumulative",
                    "reactor.coolant_temp.inlet",
                    "reactor.coolant_temp.outlet",
                    "reactor.coolant_pressure",
                    "reactor.coolant_flow_rate",
                    "reactor.coolant.total_flow",
                    "reactor.coolant.pump_status",
                    "reactor.coolant.pump_speed",
                    "reactor.coolant.chemistry",
                    "reactor.coolant.boron_concentration",
                    "reactor.control_rod.position",
                    "reactor.control_rod.group",
                    "reactor.control_rod.insertion",
                    "reactor.control_rod.withdrawn",
                    "reactor.control_rod.scram_time",
                    "reactor.neutron_flux",
                    "reactor.neutron_flux.power_range",
                    "reactor.neutron_flux.intermediate_range",
                    "reactor.neutron_flux.source_range",
                    "reactor.neutron_flux.level",
                    "reactor.neutron_flux.period",
                    "reactor.neutron_flux.reactivity",
                    "reactor.k_eff",
                    "reactor.k_eff.critical",
                    "reactor.void_coefficient",
                    "reactor.doppler_coefficient",
                    "reactor.containment.pressure",
                    "reactor.containment.temperature",
                    "reactor.containment.humidity",
                    "reactor.containment.radiation",
                    "reactor.containment.sump_level",
                    "reactor.containment.spray_status",
                    "reactor.containment.fan_status",
                    "reactor.containment.filter_status",
                    "reactor.containment.isolation_status",
                    "reactor.containment.door_status",
                    "reactor.containment.valve_status",
                    "reactor.primary_system.pressure",
                    "reactor.primary_system.temperature",
                    "reactor.primary_system.flow",
                    "reactor.primary_system.level",
                    "reactor.primary_system.pump_status",
                    "reactor.primary_system.valve_status",
                    "reactor.secondary_system.pressure",
                    "reactor.secondary_system.temperature",
                    "reactor.secondary_system.flow",
                    "reactor.secondary_system.level",
                    "reactor.secondary_system.steam_drum",
                    "reactor.secondary_system.feedwater",
                    "reactor.secondary_system.turbine_status",
                    "reactor.secondary_system.generator_status",
                    "reactor.safety_system.injection_status",
                    "reactor.safety_system.accumulators",
                    "reactor.safety_system.cas",
                    "reactor.safety_system.hpcs",
                    "reactor.safety_system.containment_spray",
                    "reactor.safety_system.afw",
                    "reactor.safety_system.esf_actuation",
                ],
                "count": 110,
            },
            "iaea_safeguards": {
                "description": "IAEA safeguards, containment and surveillance, material accounting",
                "reference": "IAEA Safeguards, INFCIRC/153, INFCIRC/74, IAEA C/S measures",
                "fields": [
                    "iaea.facility_id",
                    "iaea.facility_type",
                    "iaea.facility_name",
                    "iaea.state",
                    "iaea.agreement_type",
                    "iaea.inspector_id",
                    "iaea.inspector_name",
                    "iaea.visit_number",
                    "iaea.visit_date",
                    "iaea.visit_duration",
                    "iaea.cams_serial",
                    "iaea.cams.model",
                    "iaea.cams.location",
                    "iaea.cams.status",
                    "iaea.cams.last_calibration",
                    "iaea.cams.next_calibration",
                    "iaea.cams.battery_level",
                    "iaea.cams.memory_usage",
                    "iaea.cams.alarm_count",
                    "iaea.cams.recording_mode",
                    "iaea.cams.frame_rate",
                    "iaea.cams.resolution",
                    "iaea.ssm.serial",
                    "iaea.ssm.model",
                    "iaea.ssm.location",
                    "iaea.ssm.type",
                    "iaea.ssm.encryption_key",
                    "iaea.ssm.status",
                    "iaea.ssm.battery_status",
                    "iaea.vt.id",
                    "iaea.vt.model",
                    "iaea.vt.location",
                    "iaea.vt.type",
                    "iaea.vt.seal_id",
                    "iaea.vt.seal_type",
                    "iaea.vt.seal_verification",
                    "iaea.dfm.serial",
                    "iaea.dfm.model",
                    "iaea.dfm.location",
                    "iaea.dfm.type",
                    "iaea.dfm.calibration_date",
                    "iaea.dfm.count_rate",
                    "iaea.mva.serial",
                    "iaea.mva.model",
                    "iaea.mva.location",
                    "iaea.mva.item_type",
                    "iaea.mva.item_id",
                    "iaea.mva.item_weight",
                    "iaea.mva.item_enrichment",
                    "iaea.mva.item_diameter",
                    "iaea.mva.item_height",
                    "iaea.mva.measurement_date",
                    "iaea.mva.measurement_time",
                    "iaea.mva.operator",
                    "iaea.mva.background_count",
                    "iaea.mva.sample_count",
                    "iaea.mva.net_count_rate",
                    "iaea.mva.uncertainty",
                    "iaea.mva.detection_limit",
                    "iaea.mva.pass_fail",
                    "iaea.muf.method",
                    "iaea.muf.value",
                    "iaea.muf.uncertainty",
                    "iaea.muf.sigma",
                    "iaea.muf.significance",
                    "iaea.muf.date",
                    "iaea.muf.material_type",
                    "iaea.sg.data_collection",
                    "iaea.sg.notification_time",
                    "iaea.sg.access_time",
                    "iaea.sg.failure_code",
                    "iaea.sg.failure_description",
                    "iaea.sg.resolution_date",
                ],
                "count": 80,
            },
            "radiation_safety": {
                "description": "Radiation safety, dosimetry, ALARA, and shielding fields",
                "reference": "ICRP, NCRP, ANSI/HPS, NRC 10 CFR, ISO 361",
                "fields": [
                    "safety.dose_limit.occupational",
                    "safety.dose_limit.public",
                    "safety.dose_limit.embryo_fetus",
                    "safety.dose_limit.minor",
                    "safety.dose_limit.effective",
                    "safety.dose_limit.equivalent",
                    "safety.dose_limit.skin",
                    "safety.dose_limit.hands",
                    "safety.dose_limit.lens",
                    "safety.dose_rate",
                    "safety.dose_rate.ambient",
                    "safety.dose_rate.directional",
                    "safety.dose_rate.personal",
                    "safety.dose_rate.contamination",
                    "safety.dose_rate.background",
                    "safety.dose_accumulated",
                    "safety.dose.occupational",
                    "safety.dose.quarterly",
                    "safety.dose.annual",
                    "safety.dose.cumulative",
                    "safety.dose.deep",
                    "safety.dose.shallow",
                    "safety.dose.lens",
                    "safety.dose.committed",
                    "safety.dose.internal",
                    "safety.dose.external",
                    "safety.dose.surveillance",
                    "safety.dose.week",
                    "safety.dose.month",
                    "safety.dose.year_to_date",
                    "safety.alara.alara_plan",
                    "safety.alara.optimization",
                    "safety.alara.justification",
                    "safety.alara.constraint",
                    "safety.alara.reference_level",
                    "safety.alara.dose_target",
                    "safety.alara.dose_goal",
                    "safety.alara.work_planning",
                    "safety.alara.time_reduction",
                    "safety.alara.distance_increase",
                    "safety.alara.shielding_addition",
                    "safety.alara.technique_modification",
                    "safety.alara.engineering_controls",
                    "safety.alara.administrative_controls",
                    "safety.alara.audit_date",
                    "safety.alara.review_date",
                    "safety.shielding.material",
                    "safety.shielding.thickness",
                    "safety.shielding.hvl",
                    "safety.shielding.tvl",
                    "safety.shielding.tenth_value",
                    "safety.shielding.linear_attenuation",
                    "safety.shielding.mass_attenuation",
                    "safety.shielding.buildup_factor",
                    "safety.shielding.lead_equivalence",
                    "safety.shielding.lead_thickness",
                    "safety.shielding.concrete_thickness",
                    "safety.shielding.steel_thickness",
                    "safety.shielding.wood_thickness",
                    "safety.shielding.water_thickness",
                    "safety.shielding.borated_concrete",
                    "safety.shielding.paraffin_thickness",
                    "safety.shielding.boron_carbide",
                    "safety.work_control.permit_type",
                    "safety.work_control.permit_number",
                    "safety.work_control.date",
                    "safety.work_control.authorized_by",
                    "safety.work_control.radiation_area",
                    "safety.work_control.high_radiation_area",
                    "safety.work_control.very_high_radiation",
                    "safety.work_control.contamination_area",
                    "safety.work_control.respiratory_protection",
                    "safety.work_control.protective_clothing",
                    "safety.work_control.dosimetry_requirements",
                    "safety.work_control.time_limit",
                    "safety.work_control.distance_requirement",
                ],
                "count": 80,
            },
        },
        "totals": {
            "categories": 6,
            "total_fields": 600,
        }
    }

    return INVENTORY


def main():
    print("=" * 70)
    print("NUCLEAR/RADIATION MONITORING METADATA FIELD INVENTORY")
    print("=" * 70)
    print()

    inventory = generate_nuclear_inventory()

    print(f"Generated: {inventory['generated_at']}")
    print(f"Categories: {inventory['totals']['categories']}")
    print(f"Total Fields: {inventory['totals']['total_fields']:,}")
    print()

    print("FIELD COUNTS BY CATEGORY:")
    print("-" * 50)
    for cat_name, cat_data in sorted(inventory['categories'].items(), key=lambda x: x[1]['count'], reverse=True):
        ref = cat_data.get('reference', '')[:40]
        print(f"  {cat_name:30s}: {cat_data['count']:>4}  [{ref}]")

    output_dir = Path("dist/nuclear_inventory")
    output_dir.mkdir(parents=True, exist_ok=True)

    output_file = output_dir / "nuclear_inventory.json"
    output_file.write_text(json.dumps(inventory, indent=2, sort_keys=True), encoding="utf-8")
    print()
    print(f"Wrote: {output_file}")

    summary = {
        "generated_at": inventory["generated_at"],
        "source": inventory["source"],
        "description": inventory["description"],
        "totals": inventory["totals"],
        "field_counts_by_category": {}
    }

    for cat_name, cat_data in inventory["categories"].items():
        summary["field_counts_by_category"][cat_name] = {
            "description": cat_data["description"],
            "count": cat_data["count"],
            "reference": cat_data.get("reference", "N/A")
        }

    summary_file = output_dir / "nuclear_summary.json"
    summary_file.write_text(json.dumps(summary, indent=2), encoding="utf-8")
    print(f"Wrote: {summary_file}")


if __name__ == "__main__":
    main()
