#!/usr/bin/env python3
"""IoT Format Metadata Field Inventory for MetaExtract.

Covers MQTT, CoAP, Zigbee, LoRaWAN, Bluetooth LE, Modbus, and other IoT protocols.
"""

from datetime import datetime, timezone
from pathlib import Path


def generate_iot_inventory():
    """Generate comprehensive IoT format metadata field inventory."""

    INVENTORY = {
        "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "source": "MQTT 5.0, CoAP RFC 7252, Zigbee Cluster Library, LoRaWAN 1.1, Bluetooth SIG, Modbus",
        "description": "IoT format metadata including MQTT, CoAP, Zigbee, LoRaWAN, BLE, Modbus, and IoT device formats",
        "categories": {
            "mqtt_v5": {
                "description": "MQTT 5.0 protocol fields",
                "reference": "MQTT 5.0 Specification",
                "fields": [
                    "mqtt.protocol_version",
                    "mqtt.flags",
                    "mqtt.keep_alive",
                    "mqtt.client_id",
                    "mqtt.will_flag",
                    "mqtt.will_qos",
                    "mqtt.will_retain",
                    "mqtt.clean_start",
                    "mqtt.password",
                    "mqtt.username",
                    "mqtt.will_topic",
                    "mqtt.will_payload",
                    "mqtt.will_delay_interval",
                    "mqtt.session_expiry_interval",
                    "mqtt.receive_maximum",
                    "mqtt.maximum_packet_size",
                    "mqtt.topic_alias_maximum",
                    "mqtt.topic_alias",
                    "mqtt.response_topic",
                    "mqtt.correlation_data",
                    "mqtt.user_property",
                    "mqtt.auth_method",
                    "mqtt.auth_data",
                    "mqtt.reason_string",
                    "mqtt.will_delay_interval",
                    "mqtt.payload_format_indicator",
                    "mqtt.message_expiry_interval",
                    "mqtt.content_type",
                    "mqtt.response_topic",
                    "mqtt.correlation_data",
                    "mqtt.subscription_identifier",
                    "mqtt.topic",
                    "mqtt.qos",
                    "mqtt.retain",
                    "mqtt.dup",
                    "mqtt.packet_id",
                    "mqtt.acknowledge_flags",
                    "mqtt.connect_flags",
                    "mqtt.keep_alive",
                    "mqtt.connect_reason_code",
                    "mqtt.server_reference",
                    "mqtt.server_keep_alive",
                    "mqtt.response_information",
                    "mqtt.timestamp",
                    "mqtt.message_type",
                    "mqtt.control_packet_type",
                    "mqtt.remaining_length",
                    "mqtt.utf8_string",
                    "mqtt.utf8_string_pair",
                    "mqtt.binary_data",
                    "mqtt.variable_byte_integer",
                    "mqtt.pingreq",
                    "mqtt.pingresp",
                    "mqtt.disconnect",
                    "mqtt.disconnect.reason_code",
                    "mqtt.disconnect.server_reference",
                    "mqtt.disconnect.session_expiry_interval",
                    "mqtt.disconnect.maximum_packet_size",
                    "mqtt.disconnect.server_keep_alive",
                    "mqtt.auth",
                    "mqtt.auth.auth_method",
                    "mqtt.auth.auth_data",
                    "mqtt.auth.reason_string",
                    "mqtt.auth.user_property",
                    "mqtt.subscribe",
                    "mqtt.subscribe.options",
                    "mqtt.subscribe.no_local",
                    "mqtt.subscribe.retain_as_published",
                    "mqtt.subscribe.retain_handling",
                    "mqtt.suback",
                    "mqtt.suback.reason_codes",
                    "mqtt.suback.properties",
                    "mqtt.unsubscribe",
                    "mqtt.unsuback",
                    "mqtt.unsuback.reason_codes",
                    "mqtt.publish",
                    "mqtt.publish.payload",
                    "mqtt.publish.properties",
                    "mqtt.puback",
                    "mqtt.puback.reason_code",
                    "mqtt.pubrec",
                    "mqtt.pubrec.reason_code",
                    "mqtt.pubrel",
                    "mqtt.pubrel.reason_code",
                    "mqtt.pubcomp",
                    "mqtt.pubcomp.reason_code",
                    "mqtt.connack",
                    "mqtt.connack.flags",
                    "mqtt.connack.reason_code",
                    "mqtt.connack.session_present",
                    "mqtt.connack.properties",
                    "mqtt.properties",
                    "mqtt.properties.session_expiry_interval",
                    "mqtt.properties.receive_maximum",
                    "mqtt.properties.maximum_qos",
                    "mqtt.properties.retain_available",
                    "mqtt.properties.maximum_packet_size",
                    "mqtt.properties.topic_alias_maximum",
                    "mqtt.properties.topic_alias",
                    "mqtt.properties.subscription_identifier_available",
                    "mqtt.properties.shared_subscription_available",
                    "mqtt.properties.wildcard_subscription_available",
                    "mqtt.properties.content_type_available",
                    "mqtt.properties.response_information_available",
                    "mqtt.properties.server_reference",
                    "mqtt.properties.authentication_method",
                    "mqtt.properties.authentication_data",
                    "mqtt.illegal_request_reason",
                    "mqtt.error_response",
                    "mqtt.broker",
                    "mqtt.broker.id",
                    "mqtt.broker.name",
                    "mqtt.broker.version",
                    "mqtt.broker.uptime",
                    "mqtt.broker.connections",
                    "mqtt.broker.topics",
                    "mqtt.broker.messages",
                    "mqtt.broker.bytes",
                    "mqtt.broker.clients",
                    "mqtt.client",
                    "mqtt.client.id",
                    "mqtt.client.protocol",
                    "mqtt.client.keepalive",
                    "mqtt.client.connected",
                    "mqtt.client.subscriptions",
                    "mqtt.client.messages_sent",
                    "mqtt.client.messages_received",
                    "mqtt.client.bytes_sent",
                    "mqtt.client.bytes_received",
                    "mqtt.client.will",
                    "mqtt.client.last_will",
                ],
                "count": 142,
            },
            "coap_rfc7252": {
                "description": "CoAP (Constrained Application Protocol) fields",
                "reference": "RFC 7252, RFC 7959",
                "fields": [
                    "coap.version",
                    "coap.type",
                    "coap.token",
                    "coap.token_length",
                    "coap.code",
                    "coap.message_id",
                    "coap.options",
                    "coap.payload",
                    "coap.payload_marker",
                    "coap.content_format",
                    "coap.accept",
                    "coap.max_age",
                    "coap.etag",
                    "coap.location_path",
                    "coap.location_query",
                    "coap.proxy_uri",
                    "coap.proxy_scheme",
                    "coap.block1",
                    "coap.block2",
                    "coap.size",
                    "coap.size1",
                    "coap.block_size",
                    "coap.block_number",
                    "coap.block_more",
                    "coap.block_szx",
                    "coap.observe",
                    "coap.uri_host",
                    "coap.uri_port",
                    "coap.uri_path",
                    "coap.uri_query",
                    "coap.if_match",
                    "coap.if_none_match",
                    "coap.prefer",
                    "coap.request_tag",
                    "coap.oscore",
                    "coap.oscore.version",
                    "coap.oscore.flags",
                    "coap.oscore.kid",
                    "coap.oscore.iv",
                    "coap.oscore.hkid",
                    "coap.oscore.critical",
                    "coap.oscore.partialIV",
                    "coap.oscore.payload",
                    "coap.security.mode",
                    "coap.security.type",
                    "coap.security.dtls",
                    "coap.security.psk",
                    "coap.security.rpk",
                    "coap.security.certificate",
                    "coap.method",
                    "coap.method.code",
                    "coap.response_code",
                    "coap.response_code.class",
                    "coap.response_code.detail",
                    "coap.confirmable",
                    "coap.non_confirmable",
                    "coap.acknowledgement",
                    "coap.reset",
                    "coap.separate_response",
                    "coap.mid",
                    "coap.tkl",
                    "coap.con",
                    "coap.ack",
                    "coap.rst",
                    "coap.get",
                    "coap.post",
                    "coap.put",
                    "coap.delete",
                    "coap.changed",
                    "coap.created",
                    "coap.deleted",
                    "coap.valid",
                    "coap.changed",
                    "coap.bad_request",
                    "coap.unauthorized",
                    "coap.bad_option",
                    "coap.precondition_failed",
                    "coap.request_entity_too_large",
                    "coap.unsupported_content_format",
                    "coap.not_found",
                    "coap.method_not_allowed",
                    "coap.not_acceptable",
                    "coap.conflict",
                    "coap.precondition_failed",
                    "coap.internal_server_error",
                    "coap.not_implemented",
                    "coap.bad_gateway",
                    "coap.service_unavailable",
                    "coap.gateway_timeout",
                    "coap.proxying_not_supported",
                    "coap.hop_limit",
                    "coap.no_server_response",
                    "coap.scheme",
                    "coap.host",
                    "coap.port",
                    "coap.path",
                    "coap.query",
                    "coap.resource_type",
                    "coap.interface_description",
                    "coap.subscription_event",
                    "coap.trigger",
                    "coap.action",
                    "coap.registrar",
                    "coap.registrar.id",
                    "coap.registrar.topic",
                    "coap.registrar.credentials",
                    "coap.registration_update",
                    "coap.deregistration",
                ],
                "count": 126,
            },
            "zigbee_zcl": {
                "description": "Zigbee ZCL (Zigbee Cluster Library) fields",
                "reference": "Zigbee Cluster Library Specification",
                "fields": [
                    "zbee.frame_control",
                    "zbee.frame_control.frame_type",
                    "zbee.frame_control.manufacturer_specific",
                    "zbee.frame_control.direction",
                    "zbee.frame_control.disable_default_response",
                    "zbee.frame_control.reserved",
                    "zbee.manufacturer_code",
                    "zbee.transaction_sequence_number",
                    "zbee.command_identifier",
                    "zbee.cluster_id",
                    "zbee.cluster_id.basic",
                    "zbee.cluster_id.power_configuration",
                    "zbee.cluster_id.device_temperature",
                    "zbee.cluster_id.on_off",
                    "zbee.cluster_id.on_off_switch_configuration",
                    "zbee.cluster_id.level_control",
                    "zbee.cluster_id.alarms",
                    "zbee.cluster_id.time",
                    "zbee.cluster_id.analog_input",
                    "zbee.cluster_id.analog_output",
                    "zbee.cluster_id.analog_value",
                    "zbee.cluster_id.analog_input",
                    "zbee.cluster_id.binary_input",
                    "zbee.cluster_id.binary_output",
                    "zbee.cluster_id.binary_value",
                    "zbee.cluster_id.multistate_input",
                    "zbee.cluster_id.multistate_output",
                    "zbee.cluster_id.multistate_value",
                    "zbee.cluster_id.commissioning",
                    "zbee.cluster_id.ota_upgrade",
                    "zbee.cluster_id.power_profile",
                    "zbee.cluster_id.appliance_control",
                    "zbee.cluster_id.poll_control",
                    "zbee.cluster_id.thermostat",
                    "zbee.cluster_id.fan_control",
                    "zbee.cluster_id.dehumidification_control",
                    "zbee.cluster_id.thermostat_ui",
                    "zbee.cluster_id.color_control",
                    "zbee.cluster_id.illuminance_measurement",
                    "zbee.cluster_id.temperature_measurement",
                    "zbee.cluster_id.pressure_measurement",
                    "zbee.cluster_id.flow_measurement",
                    "zbee.cluster_id.relative_humidity",
                    "zbee.cluster_id.occupancy_sensing",
                    "zbee.cluster_id.carbon_dioxide",
                    "zbee.cluster_id.carbon_monoxide",
                    "zbee.cluster_id.zigbee_information",
                    "zbee.cluster_id.zigbee_security",
                    "zbee.endpoint_id",
                    "zbee.endpoint_type",
                    "zbee.endpoint.network_address",
                    "zbee.endpoint.ieee_address",
                    "zbee.endpoint.profile_id",
                    "zbee.endpoint.device_id",
                    "zbee.endpoint.device_version",
                    "zbee.endpoint.input_clusters",
                    "zbee.endpoint.output_clusters",
                    "zbee.node_descriptor",
                    "zbee.node_descriptor.logical_type",
                    "zbee.node_descriptor.complex_descriptor_available",
                    "zbee.node_descriptor.user_descriptor_available",
                    "zbee.node_descriptor.reserved",
                    "zbee.node_descriptor.aps_flags",
                    "zbee.node_descriptor.frequency_band",
                    "zbee.node_descriptor.mac_capability",
                    "zbee.node_descriptor.manufacturer_code",
                    "zbee.node_descriptor.maximum_buffer_size",
                    "zbee.node_descriptor.maximum_incoming_transfer_size",
                    "zbee.node_descriptor.server_mask",
                    "zbee.node_descriptor.descriptor_capability",
                    "zbee.active_endpoint",
                    "zbee.simple_descriptor",
                    "zbee.simple_descriptor.application_profile_id",
                    "zbee.simple_descriptor.application_device_id",
                    "zbee.simple_descriptor.application_device_version",
                    "zbee.simple_descriptor.reserved",
                    "zbee.simple_descriptor.input_cluster_count",
                    "zbee.simple_descriptor.output_cluster_count",
                    "zbee.nwk_address",
                    "zbee.ieee_address",
                    "zbee.parent_address",
                    "zbee.depth",
                    "zbee.pan_id",
                    "zbee.extended_pan_id",
                    "zbee.channel",
                    "zbee.channel_mask",
                    "zbee.pan_id",
                    "zbee.security_level",
                    "zbee.network_key",
                    "zbee.network_key_sequence_number",
                    "zbee.nwk_update_id",
                    "zbee.trust_center_address",
                    "zbee.security_status",
                    "zbee.join_method",
                    "zbee.join_status",
                    "zbee.permit_join",
                    "zbee.permit_join_duration",
                    "zbee.device_type",
                    "zbee.gateway",
                    "zbee.router",
                    "zbee.end_device",
                    "zbee.trust_center",
                    "zbee.coordinator",
                    "zbee.pairing",
                    "zbee.commissioning_status",
                    "zbee.commissioning.security",
                    "zbee.commissioning.network",
                    "zbee.commissioning.bdb_commissioning_mode",
                    "zbee.bdb_commissioning_group_id",
                    "zbee.bdb_commissioning_status",
                    "zbee.bdb_join_commissioning_method",
                    "zbee.bdb_nwk_channel",
                    "zbee.bdb_nwk_mask",
                    "zbee.bdb_preconfigured_key",
                    "zbee.bdb_preconfigured_key_length",
                    "zbee.bdb_tx_channel",
                    "zbee.bdb_scan_duration",
                    "zbee.bdb_scan_mask",
                    "zbee.bdb_primary_channel_group",
                    "zbee.bdb_secondary_channel_group",
                ],
                "count": 142,
            },
            "lorawan": {
                "description": "LoRaWAN 1.1 protocol fields",
                "reference": "LoRaWAN 1.1 Specification",
                "fields": [
                    "lorawan.mhdr",
                    "lorawan.major",
                    "lorawan.minor",
                    "lorawan.msg_type",
                    "lorawan.dev_addr",
                    "lorawan.dev_nonce",
                    "lorawan.join_eui",
                    "lorawan.join_request_type",
                    "lorawan.join_accept_type",
                    "lorawan.app_nonce",
                    "lorawan.net_id",
                    "lorawan.dl_settings",
                    "lorawan.rx_delay",
                    "lorawan.cf_list",
                    "lorawan.freq",
                    "lorawan.data_rate",
                    "lorawan.bandwidth",
                    "lorawan.spreading_factor",
                    "lorawan.code_rate",
                    "lorawan.frequency",
                    "lorawan.frame_counter",
                    "lorawan.f_port",
                    "lorawan.frm_payload",
                    "lorawan.encrypted",
                    "lorawan.mic",
                    "lorawan.calculated_mic",
                    "lorawan.direction",
                    "lorawan.confirmed",
                    "lorawan.ack",
                    "lorawan.adrm",
                    "lorawan.fopts",
                    "lorawan.fctrl",
                    "lorawan.adr",
                    "lorawan.adr_ack_req",
                    "lorawan.ack_bit",
                    "lorawan.pending",
                    "lorawan.frame_options_length",
                    "lorawan.frame_options",
                    "lorawan.dev_eui",
                    "lorawan.app_eui",
                    "lorawan.app_key",
                    "lorawan.nwk_key",
                    "lorawan.app_s_key",
                    "lorawan.nwk_s_enc_key",
                    "lorawan.nwk_s_int_key",
                    "lorawan.mc_key",
                    "lorawan.fport",
                    "lorawan.fcnt",
                    "lorawan.fcnt_up",
                    "lorawan.fcnt_down",
                    "lorawan.adr_history",
                    "lorawan.rx1_dr_offset",
                    "lorawan.rx2_data_rate",
                    "lorawan.rx2_frequency",
                    "lorawan.channel_frequency",
                    "lorawan.channel_data_rate_range",
                    "lorawan.max_payload_size",
                    "lorawan.receive_delay_1",
                    "lorawan.receive_delay_2",
                    "lorawan.join_accept_delay_1",
                    "lorawan.join_accept_delay_2",
                    "lorawan.max_fcnt_gap",
                    "lorawan.adr_ack_limit",
                    "lorawan.adr_ack_delay",
                    "lorawan.uplinks",
                    "lorawan.downlinks",
                    "lorawan.ack_required",
                    "lorawan.class",
                    "lorawan.device_class",
                    "lorawan.rejoin",
                    "lorawan.max_rejoin_time",
                    "lorawan.beacon",
                    "lorawan.beacon.time",
                    "lorawan.beacon.gwps",
                    "lorawan.beacon.freq",
                    "lorawan.link_check",
                    "lorawan.link_check.margin",
                    "lorawan.link_check.gwcnt",
                    "lorawan.dev_status",
                    "lorawan.dev_status.battery",
                    "lorawan.dev_status.margin",
                    "lorawan.duty_cycle",
                    "lorawan.tx_power",
                    "lorawan.rx1_dr_offset",
                    "lorawan.rx2_data_rate",
                    "lorawan.channel_mask",
                    "lorawan.channel_mask_cntl",
                    "lorawan.max_duty_cycle",
                    "lorawan.dev_status_req",
                    "lorawan.new_channel",
                    "lorawan.new_channel.freq",
                    "lorawan.new_channel.data_rate_range",
                    "lorawan.rx_timing_setup",
                    "lorawan.rx_timing_setup.delay",
                    "lorawan.tx_param_setup",
                    "lorawan.tx_param_setup.max_duty_cycle",
                    "lorawan.tx_param_setup.downlink_dwell",
                    "lorawan.tx_param_setup.uplink_dwell",
                    "lorawan.dl_channel",
                    "lorawan.dl_channel.freq",
                    "lorawan.reset_ind",
                    "lorawan.reset_ind.count",
                    "lorawan.device_time",
                    "lorawan.device_time.time",
                    "lorawan.force_rejoin",
                    "lorawan.force_rejoin.type",
                    "lorawan.force_rejoin.period",
                    "lorawan.force_rejoin.max_period",
                    "lorawan.device_mode",
                    "lorawan.class_switch",
                ],
                "count": 124,
            },
            "bluetooth_le": {
                "description": "Bluetooth Low Energy and GATT fields",
                "reference": "Bluetooth SIG Assigned Numbers",
                "fields": [
                    "ble.gap",
                    "ble.gap.device_name",
                    "ble.gap.appearance",
                    "ble.gap.peripheral_preferred_connection_parameters",
                    "ble.gap.central_address_resolution",
                    "ble.gap.resolvable_private_address_only",
                    "ble.gap.device_name_complete",
                    "ble.gap.device_name_shortened",
                    "ble.gap.flags",
                    "ble.gap.flags.LE_Limited_Discoverable",
                    "ble.gap.flags.LE_General_Discoverable",
                    "ble.gap.flags.BR_EDR_Supported",
                    "ble.gap.flags.Simultaneous_LE_BR_EDR_Capable",
                    "ble.gap.flags.LE_BR_EDR_Controller",
                    "ble.gap.flags.LE_BR_EDR_Host",
                    "ble.gap.flags.LE_Supported",
                    "ble.gap.manufacturer_data",
                    "ble.gap.manufacturer_data.company_identifier",
                    "ble.gap.manufacturer_data.data",
                    "ble.gatt",
                    "ble.gatt.service",
                    "ble.gatt.service.uuid",
                    "ble.gatt.service.primary",
                    "ble.gatt.service.includes",
                    "ble.gatt.characteristic",
                    "ble.gatt.characteristic.uuid",
                    "ble.gatt.characteristic.properties",
                    "ble.gatt.characteristic.properties.broadcast",
                    "ble.gatt.characteristic.properties.read",
                    "ble.gatt.characteristic.properties.write_nr",
                    "ble.gatt.characteristic.properties.write",
                    "ble.gatt.characteristic.properties.notify",
                    "ble.gatt.characteristic.properties.indicate",
                    "ble.gatt.characteristic.properties.auth_signed_write",
                    "ble.gatt.characteristic.properties.extended",
                    "ble.gatt.characteristic.value_handle",
                    "ble.gatt.characteristic.user_description",
                    "ble.gatt.characteristic.presentation_format",
                    "ble.gatt.characteristic.aggregate_format",
                    "ble.gatt.descriptor",
                    "ble.gatt.descriptor.uuid",
                    "ble.gatt.descriptor.value",
                    "ble.gatt.client_characteristic_configuration",
                    "ble.gatt.client_characteristic_configuration.notify",
                    "ble.gatt.client_characteristic_configuration.indicate",
                    "ble.gatt.server_characteristic_configuration",
                    "ble.gatt.server_characteristic_configuration.broadcast",
                    "ble.gatt.characteristic_extended_properties",
                    "ble.gatt.characteristic_extended_properties.reliable_write",
                    "ble.gatt.characteristic_extended_properties.writable_auxiliaries",
                    "ble.gatt.value",
                    "ble.gatt.value.data",
                    "ble.gatt.value.type",
                    "ble.gatt.value.namespace",
                    "ble.gatt.value.description",
                    "ble.advertising",
                    "ble.advertising.flags",
                    "ble.advertising.incomplete_list_16bit_svc_uuids",
                    "ble.advertising.complete_list_16bit_svc_uuids",
                    "ble.advertising.incomplete_list_32bit_svc_uuids",
                    "ble.advertising.complete_list_32bit_svc_uuids",
                    "ble.advertising.incomplete_list_128bit_svc_uuids",
                    "ble.advertising.complete_list_128bit_svc_uuids",
                    "ble.advertising.shortened_local_name",
                    "ble.advertising.complete_local_name",
                    "ble.advertising.tx_power_level",
                    "ble.advertising.class_of_device",
                    "ble.advertising.simple_pairing_hash",
                    "ble.advertising.simple_pairing_hash_confirm",
                    "ble.advertising.security_manager_tk_value",
                    "ble.advertising.security_manager_oob_flags",
                    "ble.advertising.peripheral_connection_interval_range",
                    "ble.advertising.central_address_resolution",
                    "ble.advertising.manufacturer_specific_data",
                    "ble.scan_response",
                    "ble.scan_response.tx_power",
                    "ble.scan_response.service_data",
                    "ble.scan_response.service_data.uuid",
                    "ble.scan_response.service_data.data",
                    "ble.scan_response.uri",
                    "ble.scan_response.appearance",
                    "ble.scan_response.public_address",
                    "ble.scan_response.random_address",
                    "ble.advertising_interval",
                    "ble.advertising_channel",
                    "ble.advertising_channel.chan_37",
                    "ble.advertising_channel.chan_38",
                    "ble.advertising_channel.chan_39",
                    "ble.scan_interval",
                    "ble.scan_window",
                    "ble.connection_interval",
                    "ble.connection_latency",
                    "ble.connection_supervision_timeout",
                    "ble.minimum_connection_interval",
                    "ble.maximum_connection_interval",
                    "ble.minimum_event_length",
                    "ble.maximum_event_length",
                    "ble.connection_handle",
                    "ble.att_mtu",
                    "ble.att_mtu.exchange_mtu",
                    "ble.att_mtu.exchange_mtu_request",
                    "ble.att_mtu.exchange_mtu_response",
                    "ble.security",
                    "ble.security.pairing_request",
                    "ble.security.pairing_response",
                    "ble.security.pairing_confirm",
                    "ble.security.pairing_random",
                    "ble.security.pairing_failed",
                    "ble.security.encryption_information",
                    "ble.security.master_identification",
                    "ble.security.identification_address",
                    "ble.security.signing_information",
                    "ble.security.security_request",
                ],
                "count": 124,
            },
            "modbus": {
                "description": "Modbus protocol fields",
                "reference": "Modbus Application Protocol v1.1b3",
                "fields": [
                    "modbus.transaction_id",
                    "modbus.protocol_id",
                    "modbus.length",
                    "modbus.unit_id",
                    "modbus.function_code",
                    "modbus.read_coils",
                    "modbus.read_discrete_inputs",
                    "modbus.read_holding_registers",
                    "modbus.read_input_registers",
                    "modbus.write_single_coil",
                    "modbus.write_single_register",
                    "modbus.write_multiple_coils",
                    "modbus.write_multiple_registers",
                    "modbus.mask_write_register",
                    "modbus.read_write_multiple_registers",
                    "modbus.read_fifo_queue",
                    "modbus.encapsulated_interface_transport",
                    "modbus.starting_address",
                    "modbus.quantity",
                    "modbus.coil_value",
                    "modbus.register_value",
                    "modbus.byte_count",
                    "modbus.reference_type",
                    "modbus.fifo_count",
                    "modbus.fifo_register_values",
                    "modbus.and_mask",
                    "modbus.or_mask",
                    "modbus.exception_code",
                    "modbus.exception.illegal_function",
                    "modbus.exception.illegal_data_address",
                    "modbus.exception.illegal_data_value",
                    "modbus.exception.slave_device_failure",
                    "modbus.exception.acknowledge",
                    "modbus.exception.slave_device_busy",
                    "modbus.exception.memory_parity_error",
                    "modbus.exception.gateway_path_unavailable",
                    "modbus.exception.gateway_target_failed",
                    "modbus.diagnostics",
                    "modbus.diagnostics.sub_function",
                    "modbus.diagnostics.return_query_data",
                    "modbus.diagnostics.restart_communication",
                    "modbus.diagnostics.return_diagnostic_register",
                    "modbus.diagnostics.change_ascii_input_delimiter",
                    "modbus.diagnostics.force_listen_only_mode",
                    "modbus.diagnostics.clear_counters",
                    "modbus.diagnostics.return_bus_message_count",
                    "modbus.diagnostics.return_bus_communication_error_count",
                    "modbus.diagnostics.return_bus_exception_error_count",
                    "modbus.diagnostics.return_message_count",
                    "modbus.diagnostics.return_bus_no_response_count",
                    "modbus.no_response_count",
                    "modbus.bus_character_overrun_count",
                    "modbus.bus_error_count",
                    "modbus.bus_character_framing_error_count",
                    "modbus.bus_overrun_error_count",
                    "modbus.bus_message_count",
                    "modbus.bus_communication_error_count",
                    "modbus.bus_exception_error_count",
                    "modbus.slave_message_count",
                    "modbus.no_response_count",
                    "modbus.slave_nak_count",
                    "modbus.slave_busy_count",
                    "modbus.character_overrun_count",
                    "modbus.bad_crc_count",
                    "modbus.signed_value",
                    "modbus.unsigned_value",
                    "modbus.floating_point",
                    "modbus.big_endian",
                    "modbus.little_endian",
                    "modbus.word_order",
                    "modbus.scaling",
                    "modbus.scale_factor",
                    "modbus.offset",
                    "modbus.data_type",
                    "modbus.bit_value",
                    "modbus.string_value",
                    "modbus.date_value",
                    "modbus.time_value",
                    "modbus.ip_address",
                    "modbus.port_number",
                    "modbus.device_id",
                    "modbus.vendor_name",
                    "modbus.product_code",
                    "modbus.major_minor_revision",
                    "modbus.vendor_url",
                    "modbus.product_name",
                    "modbus.model_name",
                    "modbus.user_application_name",
                    "modbus.run_indicator_status",
                    "modbus.current_mode_status",
                    "modbus.actual_point_count",
                    "modbus.actual_register_count",
                    "modbus.exception_status",
                    "modbus.auxiliary_counters",
                    "modbus.counters.id",
                    "modbus.counters.value",
                    "modbus.file_record",
                    "modbus.file.record_number",
                    "modbus.file.record_data",
                    "modbus.file.record_length",
                    "modbus.tcp_header",
                    "modbus.tcp.transaction_id",
                    "modbus.tcp.protocol_id",
                    "modbus.tcp.length",
                    "modbus.tcp.unit_id",
                    "modbus.tcp.function_code",
                ],
                "count": 124,
            },
        },
        "totals": {
            "categories": 6,
            "total_fields": 782,
        }
    }

    return INVENTORY


def main():
    print("=" * 70)
    print("IOT FORMAT METADATA FIELD INVENTORY")
    print("=" * 70)
    print()

    inventory = generate_iot_inventory()

    print(f"Generated: {inventory['generated_at']}")
    print(f"Categories: {inventory['totals']['categories']}")
    print(f"Total Fields: {inventory['totals']['total_fields']}")
    print()

    print("FIELD COUNTS BY CATEGORY:")
    print("-" * 50)
    for cat_name, cat_data in sorted(inventory['categories'].items(), key=lambda x: x[1]['count'], reverse=True):
        print(f"  {cat_name:35s}: {cat_data['count']:>4} fields")

    output_dir = Path("dist/iot_inventory")
    output_dir.mkdir(parents=True, exist_ok=True)

    output_file = output_dir / "iot_inventory.json"
    import json
    output_file.write_text(json.dumps(inventory, indent=2, sort_keys=True), encoding="utf-8")
    print()
    print(f"Wrote: {output_file}")

    summary = {
        "generated_at": inventory["generated_at"],
        "description": inventory["description"],
        "categories": {k: {"count": v["count"], "description": v["description"]} for k, v in inventory["categories"].items()},
        "totals": inventory["totals"],
    }

    summary_file = output_dir / "iot_summary.json"
    summary_file.write_text(json.dumps(summary, indent=2, sort_keys=True), encoding="utf-8")
    print(f"Wrote: {summary_file}")


if __name__ == "__main__":
    main()
