#!/usr/bin/env python3
"""Climate and Environmental Data Format Metadata Field Inventory for MetaExtract.

Covers NetCDF, HDF5 climate datasets, GRIB, Bufr, CF conventions, and climate model outputs.
Reference: CF Conventions, NetCDF4, GRIB, WMO standards, IPCC data formats.
"""

from datetime import datetime, timezone
import json
from pathlib import Path


def generate_climate_inventory():
    """Generate comprehensive climate/environmental data metadata field inventory."""

    INVENTORY = {
        "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "source": "CF Conventions 1.8, NetCDF4, GRIB2, BUFR, IPCC, CMIP6, Copernicus",
        "description": "Climate and environmental data format metadata including NetCDF, HDF5 climate datasets, GRIB, Bufr, and climate model outputs",
        "categories": {
            "netcdf_cf_metadata": {
                "description": "NetCDF CF Conventions metadata fields",
                "reference": "CF Conventions 1.8, Unidata NetCDF",
                "fields": [
                    "netcdf.cdf_format",
                    "netcdf.cdf_version",
                    "netcdf.Conventions",
                    "netcdf.institution",
                    "netcdf.source",
                    "netcdf.history",
                    "netcdf.comment",
                    "netcdf.references",
                    "netcdf.title",
                    "netcdf.summary",
                    "netcdf.keywords",
                    "netcdf.keywords_vocabulary",
                    "netcdf.naming_authority",
                    "netcdf.id",
                    "netcdf.naming_authority",
                    "netcdf.cdm_data_type",
                    "netcdf.featureType",
                    "netcdf.geospatial_lat_min",
                    "netcdf.geospatial_lat_max",
                    "netcdf.geospatial_lat_units",
                    "netcdf.geospatial_lat_resolution",
                    "netcdf.geospatial_lon_min",
                    "netcdf.geospatial_lon_max",
                    "netcdf.geospatial_lon_units",
                    "netcdf.geospatial_lon_resolution",
                    "netcdf.geospatial_vertical_min",
                    "netcdf.geospatial_vertical_max",
                    "netcdf.geospatial_vertical_units",
                    "netcdf.geospatial_vertical_resolution",
                    "netcdf.geospatial_vertical_positive",
                    "netcdf.time_coverage_start",
                    "netcdf.time_coverage_end",
                    "netcdf.time_coverage_duration",
                    "netcdf.time_coverage_resolution",
                    "netcdf.standard_name_vocabulary",
                    "netcdf.date_created",
                    "netcdf.date_modified",
                    "netcdf.date_issued",
                    "netcdf.processing_level",
                    "netcdf.product_version",
                    "netcdf.platform",
                    "netcdf.instrument",
                    "netcdf.platform_vocabulary",
                    "netcdf.instrument_vocabulary",
                    "netcdf.cdm_data_type",
                    "netcdf.geospatial_bounds",
                    "netcdf.geospatial_bounds_crs",
                    "netcdf.geospatial_vertical_crs",
                    "netcdf.project",
                    "netcdf.project_vocabulary",
                    "netcdf.acknowledgment",
                    "netcdf.funding",
                    "netcdf.license",
                    "netcdf.stdname",
                    "netcdf.units",
                    "netcdf.missing_value",
                    "netcdf._FillValue",
                    "netcdf.scale_factor",
                    "netcdf.add_offset",
                    "netcdf.valid_min",
                    "netcdf.valid_max",
                    "netcdf.valid_range",
                    "netcdf.actual_range",
                    "netcdf.coordinates",
                    "netcdf.ancillary_variables",
                    "netcdf.cell_methods",
                    "netcdf.bounds",
                    "netcdf.climatology",
                    "netcdf.grid_mapping",
                    "netcdf.grid_mapping_vocabulary",
                    "netcdf.standard_name",
                    "netcdf.long_name",
                    "netcdf.short_name",
                    "netcdf.units",
                ],
                "count": 65,
            },
            "cf_standard_names": {
                "description": "CF standard names for climate variables",
                "reference": "CF Standard Name Table",
                "fields": [
                    "cf.air_temperature",
                    "cf.air_pressure",
                    "cf.air_pressure_at_sea_level",
                    "cf.air_pressure_at_mean_sea_level",
                    "cf.surface_air_pressure",
                    "cf.eastward_wind",
                    "cf.northward_wind",
                    "cf.wind_speed",
                    "cf.wind_direction",
                    "cf.relative_humidity",
                    "cf.specific_humidity",
                    "cf.mixing_ratio",
                    "cf.precipitation_rate",
                    "cf.precipitation_amount",
                    "cf.large_scale_precipitation",
                    "cf.convective_precipitation",
                    "cf.rainfall_rate",
                    "cf.snowfall_rate",
                    "cf.convective_rainfall_amount",
                    "cf.large_scale_rainfall_amount",
                    "cf.large_scale_snowfall_amount",
                    "cf.downward_longwave_radiative_flux",
                    "cf.downward_shortwave_radiative_flux",
                    "cf.upward_longwave_radiative_flux",
                    "cf.upward_shortwave_radiative_flux",
                    "cf.net_downward_longwave_flux",
                    "cf.net_downward_shortwave_flux",
                    "cf.shortwave_heating_rate",
                    "cf.longwave_heating_rate",
                    "cf.surface_temperature",
                    "cf.surface_temperature_change",
                    "cf.skin_temperature",
                    "cf.surface_albedo",
                    "cf.surface_albedo_for_diffuse_radiation",
                    "cf.surface_albedo_for_direct_radiation",
                    "cf.toa_insolated_shortwave_flux",
                    "cf.toa_incoming_shortwave_flux",
                    "cf.toa_outgoing_longwave_flux",
                    "cf.toa_outgoing_shortwave_flux",
                    "cf.surface_net_downward_shortwave_flux",
                    "cf.surface_net_upward_shortwave_flux",
                    "cf.surface_downwelling_shortwave_flux",
                    "cf.surface_upwelling_shortwave_flux",
                    "cf.surface_downwelling_longwave_flux",
                    "cf.surface_upwelling_longwave_flux",
                    "cf.sea_surface_temperature",
                    "cf.sea_surface_salinity",
                    "cf.sea_water_velocity",
                    "cf.eastward_sea_water_velocity",
                    "cf.northward_sea_water_velocity",
                    "cf.sea_surface_height",
                    "cf.sea_surface_height_above_geoid",
                    "cf.ocean_mixed_layer_thickness",
                    "cf.ocean_heat_content",
                    "cf.baroclinic_ocean_vert_velocity",
                    "cf.barotropic_ocean_vert_velocity",
                    "cf.meridional_overturning_streamfunction",
                    "cf.ocean_dye_concentration",
                    "cf.primary_productivity_of_carbon",
                    "cf.mole_concentration_of_dissolved_molecular_oxygen",
                    "cf.mole_concentration_of_nitrate",
                    "cf.mole_concentration_of_silicate",
                    "cf.mole_concentration_of_phosphate",
                    "cf.mole_concentration_of_ammonium",
                    "cf.mole_concentration_of_carbon",
                    "cf.alkalinity",
                    "cf.pH",
                    "cf.dissolved_oxygen",
                    "cf.oxygen_saturation",
                    "cf.dissolved_inorganic_carbon",
                    "cf.dissolved_organic_carbon",
                    "cf.total_carbon",
                    "cf.particulate_organic_carbon",
                    "cf.net_primary_production",
                    "cf.primary_production",
                    "cf.fPAR",
                    "cf.LAI",
                    "cf.vegetation_height",
                    "cf.vegetation_fraction",
                    "cf.vegetation_area_fraction",
                    "cf.land_surface_albedo",
                    "cf.land_surface_temperature",
                    "cf.land_cover_fraction",
                    "cf.root_depth",
                    "cf.leaf_area_index",
                    "cf.photosynthetically_active_radiation",
                    "cf.soil_moisture_content",
                    "cf.soil_temperature",
                    "cf.soil_carbon_content",
                    "cf.organic_carbon_content",
                    "cf.inorganic_carbon_content",
                    "cf.carbon_mass_content",
                    "cf.equivalent_co2",
                    "cf.cumulative_carbon_flux",
                    "cf.vertical_flux_of_carbon_dioxide",
                    "cf.upward_flux_of_carbon_dioxide",
                    "cf.downward_flux_of_carbon_dioxide",
                    "cf.emission_rate",
                    "cf.flux_into_biomass",
                    "cf.respired_carbon",
                    "cf.gross_primary_productivity",
                    "cf.net_primary_productivity",
                    "cf.terrestrial_carbon_flux",
                    "cf.ocean_carbon_flux",
                    "cf.air_sea_carbon_flux",
                    "cf.co2_mole_fraction",
                    "cf.ch4_mole_fraction",
                    "cf.n2o_mole_fraction",
                    "cf.sf6_mole_fraction",
                    "cf.radiative_forcing",
                    "cf.temperature_change",
                    "cf.precipitation_change",
                ],
                "count": 110,
            },
            "cmip6_metadata": {
                "description": "CMIP6 climate model experiment metadata",
                "reference": "CMIP6 Data Reference Syntax, IPCC",
                "fields": [
                    "cmip6.source_id",
                    "cmip6.institution_id",
                    "cmip6.source",
                    "cmip6.institution",
                    "cmip6.activity_id",
                    "cmip6.experiment_id",
                    "cmip6.sub_experiment_id",
                    "cmip6.sub_experiment",
                    "cmip6.parent_experiment_id",
                    "cmip6.parent_activity_id",
                    "cmip6.branch_time_in_parent",
                    "cmip6.branch_time_in_child",
                    "cmip6.calendar",
                    "cmip6.realization_index",
                    "cmip6.initialization_index",
                    "cmip6.physics_index",
                    "cmip6.forcing_index",
                    "cmip6.variant_label",
                    "cmip6.member_id",
                    "cmip6.product",
                    "cmip6.frequency",
                    "cmip6.table_id",
                    "cmip6.variable_id",
                    "cmip6.coordinate",
                    "cmip6.auxiliary_coordinate",
                    "cmip6.scalar_coordinate",
                    "cmip6.cell_methods",
                    "cmip6.cell_measures",
                    "cmip6.remarks",
                    "cmip6.description",
                    "cmip6.model_doi_url",
                    "cmip6.forcing",
                    "cmip6.physics_version",
                    "cmip6.nominal_resolution",
                    "cmip6.resolution",
                    "cmip6.realm",
                    "cmip6.start_time",
                    "cmip6.end_time",
                    "cmip6.data_specs_version",
                    "cmip6.license",
                    "cmip6.project",
                    "cmip6.scenario",
                    "cmip6.experiment",
                    "cmip6.dcpp_experiment_hindcast",
                    "cmip6.dcpp_experiment_amip",
                    "cmip6.dcpp_experiment_future",
                    "cmip6.esm_ssp585",
                    "cmip6.historical",
                    "cmip6.amip",
                    "cmip6.piControl",
                    "cmip6.abrupt-4xCO2",
                    "cmip6.1pctCO2",
                    "cmip6.ssp126",
                    "cmip6.ssp245",
                    "cmip6.ssp370",
                    "cmip6.ssp585",
                    "cmip6.GFDL",
                    "cmip6.HadGEM",
                    "cmip6.EC-Earth",
                    "cmip6.MPI-ESM",
                    "cmip6.CESM",
                    "cmip6.UKESM",
                    "cmip6.IPSL-CM",
                    "cmip6.NorESM",
                    "cmip6.BCC-CSM",
                    "cmip6.MIROC",
                    "cmip6.CAS-ESM",
                ],
                "count": 75,
            },
            "grib2_fields": {
                "description": "GRIB2 message and section metadata",
                "reference": "WMO GRIB2 standard, ECMWF",
                "fields": [
                    "grib2.centre",
                    "grib2.sub_centre",
                    "grib2.master_table_version",
                    "grib2.local_table_version",
                    "grib2.significance_of_reference_time",
                    "grib2.year",
                    "grib2.month",
                    "grib2.day",
                    "grib2.hour",
                    "grib2.minute",
                    "grib2.second",
                    "grib2.production_status",
                    "grib2.type_of_generating_process",
                    "grib2.background_process",
                    "grib2.analysis_or_forecast",
                    "grib2.product_definition_template",
                    "grib2.parameter_category",
                    "grib2.parameter_number",
                    "grib2.parameter_discipline",
                    "grib2.generating_process_type",
                    "grib2.background_process_id",
                    "grib2.analysis_or_forecast_type",
                    "grib2.product_definition_template_number",
                    "grib2.forecast_time",
                    "grib2.first_fixed_surface",
                    "grib2.surface_type",
                    "grib2.scale_factor_of_first_fixed_surface",
                    "grib2.scaled_value_of_first_fixed_surface",
                    "grib2.second_fixed_surface",
                    "grib2.type_of_second_fixed_surface",
                    "grib2.scale_factor_of_second_fixed_surface",
                    "grib2.scaled_value_of_second_fixed_surface",
                    "grib2.type_of_grid",
                    "grib2.grid_definition_template",
                    "grib2.number_of_data_points",
                    "grib2.number_of_octets",
                    "grib2.interpolation_of_grid",
                    "grib2.grid_shape",
                    "grib2.earth_radius",
                    "grib2.earth_major_axis",
                    "grib2.earth_minor_axis",
                    "grib2.omega",
                    "grib2.latitude_of_first_grid_point",
                    "grib2.longitude_of_first_grid_point",
                    "grib2.resolution_and_component_flags",
                    "grib2.latitude_of_last_grid_point",
                    "grib2.longitude_of_last_grid_point",
                    "grib2.i_direction_increment",
                    "grib2.j_direction_increment",
                    "grib2.latitude_of_southern_pole",
                    "grib2.longitude_of_southern_pole",
                    "grib2.scanning_mode",
                    "grib2.nx",
                    "grib2.ny",
                    "grib2.number_of_values",
                    "grib2.data_representation_template",
                    "grib2.number_of_bits_per_value",
                    "grib2.original_field_values",
                    "grib2.reference_value",
                    "grib2.scale_factor",
                    "grib2.binary_scale_factor",
                    "grib2.decimal_scale_factor",
                    "grib2.compression_method",
                    "grib2.accuracy",
                    "grib2.bit_map_indicator",
                    "grib2.bit_map",
                    "grib2.indicator_of_unit_of_time_RANGE",
                    "grib2.forecast_time",
                    "grib2.indicator_of_unit_OF_TIME_FOR_ACCUMULATION",
                    "grib2.accumulation",
                    "grib2.number_of_members",
                    "grib2.total_number",
                    "grib2.starting_time",
                    "grib2.ending_time",
                    "grib2.step_number",
                    "grib2.step_range",
                ],
                "count": 80,
            },
            "bufr_fields": {
                "description": "BUFR message and observation metadata",
                "reference": "WMO BUFR standard, ECMWF BUFR",
                "fields": [
                    "bufr.edition",
                    "bufr.master_table",
                    "bufr.centre",
                    "bufr.sub_centre",
                    "bufr.update_sequence_number",
                    "bufr.optional_section_flag",
                    "bufr.data_category",
                    "bufr.data_subcategory",
                    "bufr.data_category_subcategory",
                    "bufr.master_table_version",
                    "bufr.local_table_version",
                    "bufr.typical_year",
                    "bufr.typical_month",
                    "bufr.typical_day",
                    "bufr.typical_hour",
                    "bufr.typical_minute",
                    "bufr.typical_second",
                    "bufr.uncompressed",
                    "bufr.compressed",
                    "bufr.observed_data",
                    "bufr.contain_subset",
                    "bufr.contain_delayed_replication",
                    "bufr.number_of_subsets",
                    "bufr.compressed_data",
                    "bufr.uncompressed_data",
                    "bufr.descriptor",
                    "bufr.element_descriptor",
                    "bufr.replication_descriptor",
                    "bufr.operator_descriptor",
                    "bufr.sequence_descriptor",
                    "bufr.table_reference",
                    "bufr.table_a",
                    "bufr.table_b",
                    "bufr.table_d",
                    "bufr.station_type",
                    "bufr.station_id",
                    "bufr.station_name",
                    "bufr.latitude",
                    "bufr.longitude",
                    "bufr.station_elevation",
                    "bufr.height",
                    "bufr.year",
                    "bufr.month",
                    "bufr.day",
                    "bufr.hour",
                    "bufr.minute",
                    "bufr.second",
                    "bufr.wind_speed",
                    "bufr.wind_direction",
                    "bufr.temperature",
                    "bufr.dewpoint",
                    "bufr.pressure",
                    "bufr.visibility",
                    "bufr.relative_humidity",
                    "bufr.cloud_cover",
                    "bufr.present_weather",
                    "bufr.past_weather",
                    "bufr.low_cloud_type",
                    "bufr.middle_cloud_type",
                    "bufr.high_cloud_type",
                    "bufr.precipitation",
                    "bufr.snow_depth",
                    "bufr.radiation",
                    "bufr.soil_temperature",
                    "bufr.soil_moisture",
                    "bufr.observation_value",
                    "bufr.observation_time",
                    "bufr.observation_position",
                    "bufr.data_quality",
                    "bufr.quality_status",
                    "bufr.quality_technique",
                    "bufr.quality_information",
                    "bufr.platform_subtype",
                    "bufr.instrument_type",
                    "bufr.height_of_station",
                    "bufr.station_or_site_name",
                    "bufr.ship_or_mobile_land_station",
                    "bufr.national_station_number",
                    "bufr.short_station_name",
                    "bufr.direction_of_motion",
                    "bufr.speed_of_motion",
                    "bufr.vertical_velocity",
                    "bufr.indicator_of_units_OF_ACCELERATION",
                    "bufr.indicator_of_units_OF_SPEED",
                    "bufr.indicator_of_units_OF_LENGTH",
                    "bufr.indicator_of_units_OF_TEMPERATURE",
                    "bufr.indicator_of_units_OF_MOISTURE",
                ],
                "count": 95,
            },
            "hdf5_climate": {
                "description": "HDF5 climate dataset and group metadata",
                "reference": "HDF5, NASA Earth Science Data Systems",
                "fields": [
                    "hdf5.file_id",
                    "hdf5.file_signature",
                    "hdf5.file_version",
                    "hdf5.superblock_version",
                    "hdf5.root_group",
                    "hdf5.free_space_manager",
                    "hdf5.free_space_section",
                    "hdf5.object_header",
                    "hdf5.group.name",
                    "hdf5.group.link_count",
                    "hdf5.group.creation_time",
                    "hdf5.group.modification_time",
                    "hdf5.dataset.name",
                    "hdf5.dataset.shape",
                    "hdf5.dataset.maxshape",
                    "hdf5.dataset.dtype",
                    "hdf5.dataset.chunks",
                    "hdf5.dataset.compression",
                    "hdf5.dataset.compression_opts",
                    "hdf5.dataset.fillvalue",
                    "hdf5.dataset.track_times",
                    "hdf5.dataset.layout",
                    "hdf5.dataset.filters",
                    "hdf5.datatype.name",
                    "hdf5.datatype.class",
                    "hdf5.datatype.size",
                    "hdf5.datatype.base",
                    "hdf5.datatype.order",
                    "hdf5.datatype.fields",
                    "hdf5.attribute.name",
                    "hdf5.attribute.value",
                    "hdf5.attribute.dtype",
                    "hdf5.attribute.shape",
                    "hdf5.reference",
                    "hdf5.region_reference",
                    "hdf5.object_reference",
                    "hdf5.soft_link",
                    "hdf5.external_link",
                    "hdf5.reference_count",
                    "hdf5.creation_order",
                    "hdf5.attribute_creation_order",
                    "hdf5.data_storage.order",
                    "hdf5.data_storage.layout",
                    "hdf5.data_storage.fill_time",
                    "hdf5.data_storage.fill_value",
                    "hdf5.data_storage.external_file",
                    "hdf5.data_storage.external_prefix",
                    "hdf5.data_storage.external_offset",
                    "hdf5.hyperslab.selection",
                    "hdf5.hyperslab.start",
                    "hdf5.hyperslab.count",
                    "hdf5.hyperslab.stride",
                    "hdf5.hyperslab.block",
                    "hdf5.dataspace.rank",
                    "hdf5.dataspace.dims",
                    "hdf5.dataspace.maxdims",
                    "hdf5.dataspace.simple",
                    "hdf5.dataspace.null",
                    "hdf5.property_list",
                    "hdf5.property_list.class",
                    "hdf5.property_list.local",
                    "hdf5.property_list.gen",
                    "hdf5.property_list.access",
                    "hdf5.property_list.file",
                    "hdf5.property_list.group",
                    "hdf5.property_list.dataset",
                    "hdf5.property_list.datatype",
                ],
                "count": 80,
            },
            "climate_indices": {
                "description": "Climate indices and indicator metadata",
                "reference": "NOAA Climate Indices, CLIVAR",
                "fields": [
                    "climate_index.enso_index",
                    "climate_index.nino34",
                    "climate_index.nino12",
                    "climate_index.nino3",
                    "climate_index.nino4",
                    "climate_index.oni",
                    "climate_index.tni",
                    "climate_index.emi",
                    "climate_index.mjo_index",
                    "climate_index.pdo_index",
                    "climate_index.np_index",
                    "climate_index.ao_index",
                    "climate_index.nao_index",
                    "climate_index.we",
                    "climate_index.wa",
                    "climate_index.sea_level_pressure",
                    "climate_index.sam_index",
                    "climate_index.aa_index",
                    "climate_index.fmi",
                    "climate_index.qbo",
                    "climate_index.solar_cycle",
                    "climate_index.ssn",
                    "climate_index.f10.7",
                    "climate_index.mg_index",
                    "climate_index.ap_index",
                    "climate_index.kp_index",
                    "climate_index.ae_index",
                    "climate_index.au_index",
                    "climate_index.al_index",
                    "climate_index.sym_h",
                    "climate_index.asy_h",
                    "climate_index.aei",
                    "climate_index.pc",
                    "climate_index.lpj_index",
                    "climate_index.amoc_index",
                    "climate_index.amoc_strength",
                    "climate_index.amoc_latitude",
                    "climate_index.amoc_depth",
                    "climate_index.nadw_strength",
                    "climate_index.aabw_strength",
                    "climate_index.tii",
                    "climate_index.cci",
                    "climate_index.precipitation_index",
                    "climate_index.temperature_index",
                    "climate_index.drought_index",
                    "climate_index.pdsi",
                    "climate_index.palmers",
                    "climate_index.spi",
                    "climate_index.spei",
                    "climate_index.cmi",
                    "climate_index.hydroindex",
                    "climate_index.fire_weather_index",
                    "climate_index.ffmc",
                    "climate_index.dmc",
                    "climate_index.dc",
                    "climate_index.bui",
                    "climate_index.fwi",
                    "climate_index.isi",
                    "climate_index.landfall_index",
                    "climate_index.intensity_index",
                    "climate_index.frequency_index",
                    "climate_index.duration_index",
                    "climate_index.storm_surge_index",
                    "climate_index.carbon_intensity",
                    "climate_index.emissions_index",
                    "climate_index.carbon_budget",
                    "climate_index.cumulative_emissions",
                    "climate_index.forcing_index",
                    "climate_index.sensitivity_index",
                    "climate_index.transient_response",
                    "climate_index.equilibrium_response",
                    "climate_index.commitment",
                    "climate_index.uncertainties",
                    "climate_index.confidence_level",
                    "climate_index.model_spread",
                    "climate_index.ensemble_spread",
                    "climate_index.percentile_5",
                    "climate_index.percentile_17",
                    "climate_index.percentile_50",
                    "climate_index.percentile_83",
                    "climate_index.percentile_95",
                ],
                "count": 90,
            },
            "satellite_products": {
                "description": "Satellite observation and product metadata",
                "reference": "Copernicus, NASA MODIS, Landsat, Sentinel",
                "fields": [
                    "satellite.platform",
                    "satellite.instrument",
                    "satellite.sensor",
                    "satellite.orbit_type",
                    "satellite.orbit_number",
                    "satellite.orbit_direction",
                    "satellite.sun_elevation_angle",
                    "satellite.sun_azimuth_angle",
                    "satellite.viewing_geometry",
                    "satellite.scan_angle",
                    "satellite.zenith_angle",
                    "satellite.azimuth_angle",
                    "satellite.relative_azimuth_angle",
                    "satellite.solar_zenith_angle",
                    "satellite.solar_azimuth_angle",
                    "satellite.satellite_zenith_angle",
                    "satellite.satellite_azimuth_angle",
                    "satellite.brdf",
                    "satellite.brdf_kernel",
                    "satellite.brdf_parameters",
                    "satellite.nadir_view",
                    "satellite.hot_spot",
                    "satellite.swath_width",
                    "satellite.swath_id",
                    "satellite.scene_id",
                    "satellite.granule_id",
                    "satellite.tile_id",
                    "satellite.spatial_resolution",
                    "satellite.temporal_resolution",
                    "satellite.temporal_coverage",
                    "satellite.cloud_mask",
                    "satellite.cloud_fraction",
                    "satellite.cloud_pressure",
                    "satellite.cloud_top_height",
                    "satellite.cloud_top_temperature",
                    "satellite.cloud_optical_depth",
                    "satellite.cloud_effective_radius",
                    "satellite.cloud_water_path",
                    "satellite.aerosol_type",
                    "satellite.aerosol_optical_depth",
                    "satellite.aerosol_index",
                    "satellite.aerosol_size",
                    "satellite.aerosol_angstrom_exponent",
                    "satellite.aerosol_single_scattering_albedo",
                    "satellite.aerosol_phase_function",
                    "satellite.land_surface_temperature",
                    "satellite.land_surface_emissivity",
                    "satellite.vegetation_index",
                    "satellite.ndvi",
                    "satellite.evi",
                    "satellite.lai",
                    "satellite.fpar",
                    "satellite.albedo",
                    "satellite.brightness_temperature",
                    "satellite.radiance",
                    "satellite.reflectance",
                    "satellite.band_wavelength",
                    "satellite.band_width",
                    "satellite.band_gain",
                    "satellite.radiometric_calibration",
                    "satellite.geometric_calibration",
                    "satellite.terrain_correction",
                    "satellite.atmospheric_correction",
                    "satellite.brdf_correction",
                    "satellite.smile_correction",
                    "satellite.stripe_correction",
                    "satellite.destriping",
                    "satellite.mosaicking",
                    "satellite.tiling",
                    "satellite.reprojection",
                    "satellite.gridding",
                    "satellite.smoothing",
                    "satellite.filtering",
                    "satellite.interpolation",
                    "satellite.resampling",
                    "satellite.coordinate_system",
                    "satellite.projection",
                    "satellite.ellipsoid",
                    "satellite.datum",
                    "satellite.ground_control_points",
                    "satellite.rmse_x",
                    "satellite.rmse_y",
                    "satellite.geolocation_accuracy",
                ],
                "count": 100,
            },
            "reanalysis": {
                "description": "Reanalysis dataset metadata",
                "reference": "ERA5, MERRA-2, JRA-55, NCEP/NCAR",
                "fields": [
                    "reanalysis.product",
                    "reanalysis.version",
                    "reanalysis.resolution",
                    "reanalysis.grid_type",
                    "reanalysis.grid_resolution",
                    "reanalysis.grid_latitude",
                    "reanalysis.grid_longitude",
                    "reanalysis.grid_vertical_levels",
                    "reanalysis.model_levels",
                    "reanalysis.surface_levels",
                    "reanalysis.hybrid_levels",
                    "reanalysis.time_axis",
                    "reanalysis.forecast_time",
                    "reanalysis.analysis_time",
                    "reanalysis.ensemble_member",
                    "reanalysis.ensemble_size",
                    "reanalysis.ensemble_mean",
                    "reanalysis.ensemble_spread",
                    "reanalysis.ensemble_std",
                    "reanalysis.bias_corrected",
                    "reanalysis.bias_correction_method",
                    "reanalysis.uncertainty",
                    "reanalysis.covariance",
                    "reanalysis.rejected_observations",
                    "reanalysis.obs_used",
                    "reanalysis.obs_assimilated",
                    "reanalysis.obs_used_fraction",
                    "reanalysis.humidity_analysis",
                    "reanalysis.humidity_correction",
                    "reanalysis.wind_analysis",
                    "reanalysis.wind_correction",
                    "reanalysis.temperature_analysis",
                    "reanalysis.temperature_correction",
                    "reanalysis.pressure_analysis",
                    "reanalysis.pressure_correction",
                    "reanalysis.land_analysis",
                    "reanalysis.ocean_analysis",
                    "reanalysis.sea_ice_analysis",
                    "reanalysis.chemistry_analysis",
                    "reanalysis.ozone_analysis",
                    "reanalysis.co2_analysis",
                    "reanalysis.aerosol_analysis",
                    "reanalysis.data_assimilation_method",
                    "reanalysis.3dvar",
                    "reanalysis.4dvar",
                    "reanalysis.hybrid_4dvar",
                    "reanalysis.kalman_filter",
                    "reanalysis.ensemble_kalman_filter",
                    "reanalysis.particle_filter",
                    "reanalysis.covariance_inflation",
                    "reanalysis.localization_length_scale",
                    "reanalysis.observation_errors",
                    "reanalysis.background_errors",
                    "reanalysis.analysis_errors",
                    "reanalysis.incremental_analysis_update",
                    "reanalysis.cold_start",
                    "reanalysis.warm_start",
                    "reanalysis.spin_up_period",
                    "reanalysis.output_frequency",
                    "reanalysis.output_variables",
                    "reanalysis.variable_long_name",
                    "reanalysis.variable_standard_name",
                    "reanalysis.variable_units",
                    "reanalysis.output_format",
                    "reanalysis.output_compression",
                    "reanalysis.data_volume",
                    "reanalysis.access_frequency",
                    "reanalysis.data_policy",
                    "reanalysis.citation",
                    "reanalysis.doi",
                    "reanalysis.acknowledgment",
                ],
                "count": 85,
            },
        },
        "totals": {
            "categories": 8,
            "total_fields": 780,
        }
    }

    return INVENTORY


def main():
    print("=" * 70)
    print("CLIMATE AND ENVIRONMENTAL DATA METADATA FIELD INVENTORY")
    print("=" * 70)
    print()

    inventory = generate_climate_inventory()

    print(f"Generated: {inventory['generated_at']}")
    print(f"Categories: {inventory['totals']['categories']}")
    print(f"Total Fields: {inventory['totals']['total_fields']}")
    print()

    print("FIELD COUNTS BY CATEGORY:")
    print("-" * 50)
    for cat_name, cat_data in sorted(inventory['categories'].items(), key=lambda x: x[1]['count'], reverse=True):
        print(f"  {cat_name:30s}: {cat_data['count']:>4} fields")

    output_dir = Path("dist/climate_inventory")
    output_dir.mkdir(parents=True, exist_ok=True)

    output_file = output_dir / "climate_inventory.json"
    output_file.write_text(json.dumps(inventory, indent=2, sort_keys=True), encoding="utf-8")
    print()
    print(f"Wrote: {output_file}")

    summary = {
        "generated_at": inventory["generated_at"],
        "source": inventory["source"],
        "description": inventory["description"],
        "categories": {
            k: {
                "count": v["count"],
                "description": v["description"],
                "reference": v.get("reference", "N/A")
            }
            for k, v in inventory["categories"].items()
        },
        "totals": inventory["totals"],
    }

    summary_file = output_dir / "climate_summary.json"
    summary_file.write_text(json.dumps(summary, indent=2, sort_keys=True), encoding="utf-8")
    print(f"Wrote: {summary_file}")


if __name__ == "__main__":
    main()
