#!/usr/bin/env python3
"""GIS and Mapping Metadata Field Inventory for MetaExtract.

Covers OpenStreetMap, Google KML, Mapbox/Vector Tiles, Topographic Data,
Address/Geocoding, Indoor Mapping, and Cartographic Styles.

Reference:
- OpenStreetMap Wiki and Taginfo
- OGC KML 2.3
- Mapbox Vector Tile Specification 2.1
- USGS DEM Standards
- ISO 19160 Address Components
- IndoorGML and Building Information Modeling
- Mapbox GL Style Specification
"""

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List, Any


def generate_gis_mapping_inventory():
    """Generate comprehensive GIS/mapping metadata field inventory."""

    INVENTORY = {
        "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "source": "OSM Wiki, OGC KML 2.3, Mapbox MVT 2.1, USGS DEM, ISO 19160, IndoorGML, Mapbox GL",
        "description": "GIS and mapping metadata fields including OSM tags, KML, vector tiles, topographic data, geocoding, indoor mapping, and cartographic styles",
        "categories": {
            "openstreetmap": {
                "description": "OpenStreetMap tags, relations, ways, and nodes",
                "reference": "https://wiki.openstreetmap.org/wiki/Map_Features",
                "fields": [
                    "osm.highway_type",
                    "osm.highway_service",
                    "osm.highway_lane_count",
                    "osm.highway_maxspeed",
                    "osm.highway_maxspeed_forward",
                    "osm.highway_maxspeed_backward",
                    "osm.highway_surface",
                    "osm.highway_smoothness",
                    "osm.highway_access",
                    "osm.highway_foot",
                    "osm.highway_bicycle",
                    "osm.highway_motor_vehicle",
                    "osm.railway_type",
                    "osm.railway_tracks",
                    "osm.railway_electrified",
                    "osm.railway_gauge",
                    "osm.waterway_type",
                    "osm.waterway_canals",
                    "osm.waterway_river",
                    "osm.building_type",
                    "osm.building_levels",
                    "osm.building_height",
                    "osm.building_roof_type",
                    "osm.landuse_type",
                    "osm.leisure_type",
                    "osm.amenity_type",
                    "osm.shop_type",
                    "osm.sport_type",
                    "osm.tourism_type",
                    "osm.historic_type",
                    "osm.natural_type",
                    "osm.place_type",
                    "osm.address_housenumber",
                    "osm.address_street",
                    "osm.address_city",
                    "osm.address_suburb",
                    "osm.address_district",
                    "osm.address_county",
                    "osm.address_province",
                    "osm.address_state",
                    "osm.address_postcode",
                    "osm.address_country",
                    "osm.network_type",
                    "osm.operator_type",
                    "osm.brand_name",
                    "osm.brand_network",
                    "osm.route_type",
                    "osm.route_master",
                    "osm.relation_type",
                    "osm.relation_restriction",
                    "osm.relation_boundary",
                    "osm.relation_admin_level",
                    "osm.node_latitude",
                    "osm.node_longitude",
                    "osm.node_elevation",
                    "osm.node_name",
                    "osm.way_nodes",
                    "osm.way_length",
                    "osm.way_area",
                    "osm.changeset_id",
                    "osm.changeset_user",
                    "osm.changeset_timestamp",
                    "osm.changeset_comments",
                    "osm.osm_version",
                    "osm.osm_changeset",
                    "osm.osm_timestamp",
                ],
                "count": 62,
            },
            "google_kml": {
                "description": "Google KML placemarks, styles, and network links",
                "reference": "https://developers.google.com/kml/documentation/kmlreference",
                "fields": [
                    "kml.placemark_id",
                    "kml.placemark_name",
                    "kml.placemark_description",
                    "kml.placemark_visibility",
                    "kml.placemark_snippet",
                    "kml.placemark_address",
                    "kml.placemark_phone",
                    "kml.placemark_timestamp",
                    "kml.placemap_timespan",
                    "kml.placemark_camera",
                    "kml.placemark_lookat",
                    "kml.point_coordinates",
                    "kml.linestring_coordinates",
                    "kml.polygon_coordinates",
                    "kml.polygon_extrude",
                    "kml.polygon_tessellate",
                    "kml.multigeometry",
                    "kml.style_id",
                    "kml.style_url",
                    "kml.icon_style_id",
                    "kml.icon_style_color",
                    "kml.icon_style_scale",
                    "kml.icon_style_heading",
                    "kml.icon_style_icon_href",
                    "kml.label_style_color",
                    "kml.label_style_scale",
                    "kml.line_style_color",
                    "kml.line_style_width",
                    "kml.polygon_style_fill",
                    "kml.polygon_style_outline",
                    "kml.polygon_style_color",
                    "kml.balloon_style_text",
                    "kml.balloon_style_bgcolor",
                    "kml.balloon_style_textcolor",
                    "kml.stylemap_pair_key",
                    "kml.stylemap_pair_style",
                    "kml.networklink_url",
                    "kml.networklink_refreshmode",
                    "kml.networklink_refreshinterval",
                    "kml.networklink_viewrefreshmode",
                    "kml.networklink_viewrefreshseconds",
                    "kml.networklink_httpquery",
                    "kml.groundoverlay_latlonbox",
                    "kml.groundoverlay_altitude",
                    "kml.groundoverlay_altitudemode",
                    "kml.groundoverlay_iconhref",
                    "kml.screenoverlay_overlayxy",
                    "kml.screenoverlay_screenxy",
                    "kml.screenoverlay_size",
                    "kml.screenoverlay_rotation",
                    "kml.photooverlay_coordinates",
                    "kml.photooverlay_shape",
                    "kml.photooverlay_viewvolume",
                    "kml.region_latlonaltbox",
                    "kml.region_lod",
                    "kml.region_minlodpixels",
                    "kml.region_maxlodpixels",
                    "kml.extendeddata_schema",
                    "kml.extendeddata_simpledata",
                    "kml.atom_author",
                    "kml.atom_link",
                    "kml.xal_addressdetails",
                ],
                "count": 60,
            },
            "mapbox_vector_tiles": {
                "description": "Mapbox Vector Tile (MVT) specification and TileJSON",
                "reference": "https://docs.mapbox.com/data/tilesets/reference/vector/",
                "fields": [
                    "mvt.tile_id",
                    "mvt.tile_zoom",
                    "mvt.tile_x",
                    "mvt.tile_y",
                    "mvt.tileExtent",
                    "mvt.tileSize",
                    "mvt.layer_id",
                    "mvt.layer_name",
                    "mvt.layer_version",
                    "mvt.layer_description",
                    "mvt.layer_attribution",
                    "mvt.layer_minzoom",
                    "mvt.layer_maxzoom",
                    "mvt.layer_bounds",
                    "mvt.layer_center",
                    "mvt.feature_id",
                    "mvt.feature_type",
                    "mvt.feature_geometry",
                    "mvt.feature_properties",
                    "mvt.tilejson_url",
                    "mvt.tilejson_scheme",
                    "mvt.tilejson_tiles",
                    "mvt.tilejson_minzoom",
                    "mvt.tilejson_maxzoom",
                    "mvt.tilejson_bounds",
                    "mvt.tilejson_center",
                    "mvt.tilejson_attribution",
                    "mvt.tilejson_description",
                    "mvt.tilejson_name",
                    "mvt.tilejson_version",
                    "mvt.vector_layers",
                    "mvt.vector_layer_id",
                    "mvt.vector_layer_fields",
                    "mvt.vector_layer_minzoom",
                    "mvt.vector_layer_maxzoom",
                    "mvt.source_name",
                    "mvt.source_type",
                    "mvt.source_url",
                    "mvt.source_tiles",
                    "mvt.source_tileSize",
                    "mvt.source_minzoom",
                    "mvt.source_maxzoom",
                    "mvt.source_bounds",
                    "mvt.source_attribution",
                    "mvt.glyphs_url",
                    "mvt.sprite_url",
                    "mvt.tile_compression",
                    "mvt.tile_cache_control",
                    "mvt.tile_max_zoom",
                    "mvt.tile_feature_limit",
                    "mvt.tile_buffer",
                    "mvt.tile_extent",
                    "mvt.tolerance",
                ],
                "count": 52,
            },
            "topographic_data": {
                "description": "DEM, contours, elevation, and bathymetry data",
                "reference": "USGS DEM Standards, ISO 19115",
                "fields": [
                    "dem.elevation",
                    "dem.elevation_min",
                    "dem.elevation_max",
                    "dem.elevation_mean",
                    "dem.elevation_stddev",
                    "dem.vertical_datum",
                    "dem.vertical_units",
                    "dem.vertical_resolution",
                    "dem.cell_size_x",
                    "dem.cell_size_y",
                    "dem.nodata_value",
                    "dem.elevation_units",
                    "dem.projection",
                    "dem.compression",
                    "dem.data_type",
                    "dem.bit_depth",
                    "dem.byte_order",
                    "dem.grid_rows",
                    "dem.grid_columns",
                    "contour.interval",
                    "contour.base",
                    "contour.index_interval",
                    "contour.min_elevation",
                    "contour.max_elevation",
                    "contour.contour_type",
                    "contour.smoothing",
                    "bathymetry.depth",
                    "bathymetry.depth_min",
                    "bathymetry.depth_max",
                    "bathymetry.vertical_datum",
                    "bathymetry.sounding_datum",
                    "bathymetry.chart_datum",
                    "bathymetry.depth_units",
                    "bathymetry.tidal_zone",
                    "elevation_profile.sampling_interval",
                    "elevation_profile.transect_id",
                    "elevation_profile.transect_length",
                    "elevation_profile.max_gradient",
                    "elevation_profile.average_gradient",
                    "terrain.slope",
                    "terrain.aspect",
                    "terrain.hillshade_azimuth",
                    "terrain.hillshade_altitude",
                    "terrain.hillshade_elevation",
                    "terrain.roughness",
                    "terrain.tpi",
                    "tri.tin_vertices",
                    "tri.tin_triangles",
                    "tri.delaunay",
                    "li DARasters",
                ],
                "count": 50,
            },
            "address_geocoding": {
                "description": "Address formatting, postal codes, and geocoding metadata",
                "reference": "ISO 19160, Google Geocoding API",
                "fields": [
                    "address.street",
                    "address.house_number",
                    "address.road",
                    "address.neighbourhood",
                    "address.suburb",
                    "address.city",
                    "address.town",
                    "address.village",
                    "address.county",
                    "address.municipality",
                    "address.state",
                    "address.province",
                    "address.postal_code",
                    "address.postcode",
                    "address.country",
                    "address.country_code",
                    "address.formatted",
                    "address.block",
                    "address.subdivision",
                    "address.dependent_locality",
                    "address.level",
                    "address.staircase",
                    "address.entrance",
                    "address.building",
                    "address.po_box",
                    "address.amenity",
                    "address.shop",
                    "address.office",
                    "address.leisure",
                    "geocoding.query",
                    "geocoding.latitude",
                    "geocoding.longitude",
                    "geocoding.location_type",
                    "geocoding.confidence_score",
                    "geocoding.confidence_level",
                    "geocoding.formatted_address",
                    "geocoding.place_id",
                    "geocoding.types",
                    "geocoding.partial_match",
                    "geocoding.route_name",
                    "geocoding.intersection",
                    "geocoding.administrative_area",
                    "geocoding.neighborhood",
                    "geocoding.ward",
                    "geocoding.postal_town",
                    "geocoding.sublocality",
                    "geocoding.locality",
                    "geocoding.county",
                    "geocoding.region",
                    "geocoding.continent",
                    "geocoding.ocean",
                    "geocoding.bounds",
                ],
                "count": 52,
            },
            "indoor_mapping": {
                "description": "Floor plans, BIM, and indoor positioning",
                "reference": "IndoorGML, IFC 4, BLE Positioning",
                "fields": [
                    "indoor.floor_level",
                    "indoor.floor_number",
                    "indoor.floor_name",
                    "indoor.building_id",
                    "indoor.building_name",
                    "indoor.building_levels",
                    "indoor.building_wing",
                    "indoor.building_section",
                    "indoor.room_id",
                    "indoor.room_name",
                    "indoor.room_type",
                    "indoor.room_number",
                    "indoor.zone_id",
                    "indoor.zone_name",
                    "indoor.zone_type",
                    "indoor.anchor_point",
                    "indoor.beacon_uuid",
                    "indoor.beacon_major",
                    "indoor.beacon_minor",
                    "indoor.rssi_value",
                    "indoor.signal_strength",
                    "indoor.wifi_ssid",
                    "indoor.wifi_bssid",
                    "indoor.wifi_frequency",
                    "indoor.position_accuracy",
                    "indoor.position_latency",
                    "indoor.navigation_graph",
                    "indoor.edges",
                    "indoor.nodes",
                    "indoor.transition",
                    "indoor.door_id",
                    "door_type",
                    "indoor.door_access",
                    "indoor.stairwell_id",
                    "indoor.elevator_id",
                    "indoor.escalator_id",
                    "indoor.ramp_id",
                    "indoor.corridor_width",
                    "indoor.ceiling_height",
                    "indoor.wall_thickness",
                    "indoor.access_control_point",
                    "indoor.security_zone",
                    "indoor.fire_zone",
                    "indoor.evacuation_route",
                    "indoor.wheelchair_accessible",
                    "indoor.occupancy_sensor",
                    "indoor.smoke_detector",
                    "indoor.sprinkler_system",
                    "bim.ifc_class",
                    "bim.ifc_element",
                    "bim.ifc_material",
                    "bim.ifc_property",
                ],
                "count": 53,
            },
            "cartographic_styles": {
                "description": "Mapbox GL, QML, and SLD styling fields",
                "reference": "Mapbox GL Style Spec, QGIS QML, OGC SLD",
                "fields": [
                    "style.layer_id",
                    "style.layer_type",
                    "style.layer_source",
                    "style.layer_sourcelayer",
                    "style.layer_minzoom",
                    "style.layer_maxzoom",
                    "style.layer_filter",
                    "style.layer_paint",
                    "style.layer_layout",
                    "style.layout_visibility",
                    "style.layout_visibility_none",
                    "style.layout_visibility_visible",
                    "style.layout_line_cap",
                    "style.layout_line_join",
                    "style.layout_text_font",
                    "style.layout_text_size",
                    "style.layout_text_field",
                    "style.layout_text_offset",
                    "style.layout_text_anchor",
                    "style.layout_text_justify",
                    "style.paint_fill_color",
                    "style.paint_fill_opacity",
                    "style.paint_fill_pattern",
                    "style.paint_line_color",
                    "style.paint_line_width",
                    "style.paint_line_opacity",
                    "style.paint_line_dasharray",
                    "style.paint_circle_radius",
                    "style.paint_circle_color",
                    "style.paint_circle_stroke_width",
                    "style.paint_circle_stroke_color",
                    "style.paint_fill_extrusion_color",
                    "style.paint_fill_extrusion_height",
                    "style.paint_fill_extrusion_base",
                    "style.paint_background_color",
                    "style.paint_background_pattern",
                    "style.sld_version",
                    "style.sld_namedlayer",
                    "style.sld_userstyle",
                    "style.sld_featuretypestyle",
                    "style.sld_rule",
                    "style.sld_filter",
                    "style.sld_polygonsymbolizer",
                    "style.sld_linesymbolizer",
                    "style.sld_pointsymbolizer",
                    "style.sld_textsymbolizer",
                    "style.sld_rasterSymbolizer",
                    "style.qml_layer_name",
                    "style.qml_rendererror",
                    "style.qml_transform",
                    "style.qml_blendmode",
                ],
                "count": 49,
            },
        },
        "totals": {
            "categories": 7,
            "total_fields": 378,
        }
    }

    return INVENTORY


def main():
    output_dir = Path("dist/gis_mapping_inventory")
    output_dir.mkdir(parents=True, exist_ok=True)
    
    inventory = generate_gis_mapping_inventory()
    
    output_file = output_dir / "gis_mapping_inventory.json"
    output_file.write_text(json.dumps(inventory, indent=2, sort_keys=True), encoding="utf-8")
    
    summary = {
        "generated_at": inventory["generated_at"],
        "source": inventory["source"],
        "description": inventory["description"],
        "categories": inventory["totals"]["categories"],
        "total_fields": inventory["totals"]["total_fields"],
        "field_counts_by_category": {}
    }
    
    for cat, data in inventory["categories"].items():
        summary["field_counts_by_category"][cat] = {
            "description": data["description"],
            "count": data["count"],
            "reference": data.get("reference", "N/A")
        }
    
    summary_file = output_dir / "gis_mapping_summary.json"
    summary_file.write_text(json.dumps(summary, indent=2), encoding="utf-8")
    
    print("=" * 70)
    print("GIS/MAPPING METADATA FIELD INVENTORY")
    print("=" * 70)
    print()
    print(f"Generated: {inventory['generated_at']}")
    print(f"Source: {inventory['source']}")
    print(f"Categories: {inventory['totals']['categories']}")
    print(f"Total Fields: {inventory['totals']['total_fields']:,}")
    print()
    print("FIELD COUNTS BY CATEGORY:")
    print("-" * 50)
    for cat, data in sorted(inventory["categories"].items(), key=lambda x: x[1]["count"], reverse=True):
        ref = data.get("reference", "")[:40]
        print(f"  {cat:25s}: {data['count']:>3} fields  [{ref}]")
    print()
    print(f"Wrote: {output_file}")
    print(f"Wrote: {summary_file}")


if __name__ == "__main__":
    main()
