#!/usr/bin/env python3
"""Insurance/Actuarial Metadata Field Inventory for MetaExtract.

Covers policy, claims, actuarial tables, risk assessment, reinsurance, regulatory, and claims analytics.
"""

from datetime import datetime, timezone
import json
from pathlib import Path


def generate_insurance_inventory():
    """Generate comprehensive insurance/actuarial metadata field inventory."""

    INVENTORY = {
        "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "source": "Insurance and actuarial standards: ACORD, NAIC, IFRS 17, Solvency II, ASTIN, IAA",
        "description": "Insurance and actuarial metadata fields including policy data, claims, actuarial tables, risk assessment, reinsurance, regulatory compliance, and claims analytics",
        "categories": {
            "policy_data": {
                "description": "Policy numbers, coverage, limits, deductibles, and policy holder information",
                "reference": "ACORD, ISO, NAIC",
                "fields": [
                    "policy.number",
                    "policy.unique_identifier",
                    "policy.version",
                    "policy.effective_date",
                    "policy.expiration_date",
                    "policy.issue_date",
                    "policy.renewal_date",
                    "policy.status",
                    "policy.type",
                    "policy.subtype",
                    "policy.line_of_business",
                    "policy.carrier",
                    "policy.carrier_code",
                    "policy.producer",
                    "policy.producer_code",
                    "policy.insured.name",
                    "policy.insured.id",
                    "policy.insured.type",
                    "policy.insured.address",
                    "policy.insured.city",
                    "policy.insured.state",
                    "policy.insured.zip",
                    "policy.insured.country",
                    "policy.insured.telephone",
                    "policy.insured.email",
                    "policy.insured.dob",
                    "policy.insured.occupation",
                    "policy.insured.industry",
                    "policy.named_insured",
                    "policy.additional_insured",
                    "policy.loss_payee",
                    "policy.mortgagee",
                    "policy.coverage.part",
                    "policy.coverage.part_id",
                    "policy.coverage.name",
                    "policy.coverage.type",
                    "policy.coverage.status",
                    "policy.coverage.effective_date",
                    "policy.coverage.expiration_date",
                    "policy.coverage.limit",
                    "policy.coverage.limit_type",
                    "policy.coverage.limit_amount",
                    "policy.coverage.limit_per_unit",
                    "policy.coverage.limit_aggregate",
                    "policy.coverage.limit_occurrence",
                    "policy.coverage.deductible",
                    "policy.coverage.deductible_type",
                    "policy.coverage.deductible_amount",
                    "policy.coverage.deductible_percentage",
                    "policy.coverage.retention",
                    "policy.coverage.retention_type",
                    "policy.coverage.premium",
                    "policy.coverage.premium_mode",
                    "policy.coverage.premium_amount",
                    "policy.coverage.coinsurance",
                    "policy.coverage.coinsurance_percentage",
                    "policy.coverage.discount",
                    "policy.coverage.surcharge",
                    "policy.coverage.exclusion",
                    "policy.coverage.endorsement",
                    "policy.coverage.condition",
                    "policy.coverage.territory",
                    "policy.coverage.class_code",
                    "policy.coverage.sub_class_code",
                    "policy.coverage.exposure.base",
                    "policy.coposure.exposure_type",
                    "policy.coverage.exposure.amount",
                    "policy.coverage.exposure.units",
                    "policy.coverage.exposure.rate",
                    "policy.coverage.sum_insured",
                    "policy.coverage.total_insured_value",
                    "policy.coverage.replacement_cost_value",
                    "policy.coverage.actual_cash_value",
                    "policy.binder.number",
                    "policy.binder.effective_date",
                    "policy.binder.expiration_date",
                    "policy.binder.status",
                    "policy.declaration.page_count",
                    "policy.declaration.verified",
                ],
                "count": 90,
            },
            "claims_data": {
                "description": "Claim numbers, status, settlement amounts, reserves, and claim investigation details",
                "reference": "Claim handling standards, NAIC, Lloyd's",
                "fields": [
                    "claim.number",
                    "claim.unique_identifier",
                    "claim.policy_number",
                    "claim.claimant.number",
                    "claim.claimant.name",
                    "claim.claimant.type",
                    "claim.claimant.relationship",
                    "claim.report_date",
                    "claim.occurrence_date",
                    "claim.loss_date",
                    "claim.reported_date",
                    "claim.loss_time",
                    "claim.loss_location",
                    "claim.loss.address",
                    "claim.loss.city",
                    "claim.loss.state",
                    "claim.loss.zip",
                    "claim.loss.country",
                    "claim.loss.description",
                    "claim.loss.type",
                    "claim.loss.cause",
                    "claim.loss.nature",
                    "claim.loss.category",
                    "claim.loss.sub_category",
                    "claim.status",
                    "claim.sub_status",
                    "claim.reserved_status",
                    "claim.stage",
                    "claim.phase",
                    "claim.type",
                    "claim.subtype",
                    "claim.line_of_business",
                    "claim.coverage.part",
                    "claim.coverage.id",
                    "claim.coverage.limit_applicable",
                    "claim.coverage.limit_amount",
                    "claim.coverage.deductible_applicable",
                    "claim.coverage.deductible_amount",
                    "claim.investigator.name",
                    "claim.investigator.id",
                    "claim.handler.name",
                    "claim.handler.id",
                    "claim.settlement.amount",
                    "claim.settlement.date",
                    "claim.settlement.type",
                    "claim.settlement.method",
                    "claim.payment.number",
                    "claim.payment.amount",
                    "claim.payment.date",
                    "claim.payment.type",
                    "claim.payment.method",
                    "claim.reserve.total",
                    "claim.reserve.initial",
                    "claim.reserve.current",
                    "claim.reserve.incurred",
                    "claim.reserve.paid",
                    "claim.reserve.recovery",
                    "claim.reserve.outstanding",
                    "claim.reserve.ibe_reserve",
                    "claim.reserve.case_reserve",
                    "claim.reserve.ibu_reserve",
                    "claim.reserve.total_ibnr",
                    "claim.reserve.paid_loss",
                    "claim.reserve.outstanding_loss",
                    "claim.reserve.loss_adjustment_expense",
                    "claim.reserve.allocated_gae",
                    "claim.reserve.unallocated_gae",
                    "claim.subrogation.recovery_amount",
                    "claim.subrogation.recovery_date",
                    "claim.subrogation.potential",
                    "claim.subrogation.status",
                    "claim.salvage.recovery_amount",
                    "claim.salvage.recovery_date",
                    "claim.salvage.potential",
                    "claim.salvage.status",
                    "claim.fraud.indicator",
                    "claim.fraud.type",
                    "claim.fraud.investigation_status",
                    "claim.litigation.status",
                    "claim.litigation.amount",
                    "claim.litigation.date_filed",
                    "claim.close.date",
                    "claim.close.reason",
                    "claim.reopen.count",
                    "claim.reopen.date",
                    "claim.reopen.reason",
                    "claim.note",
                    "claim.attachment",
                ],
                "count": 80,
            },
            "actuarial_tables": {
                "description": "Life tables, morbidity rates, mortality rates, and actuarial statistical tables",
                "reference": "Society of Actuaries, CSO Tables, ILT, Commissioners Standard Table",
                "fields": [
                    "actuarial.table_type",
                    "actuarial.table_name",
                    "actuarial.table_version",
                    "actuarial.life_table",
                    "actuarial.life_table.period",
                    "actuarial.life_table.select",
                    "actuarial.life_table.ultimate",
                    "actuarial.life_table.aggregate",
                    "actuarial.life_table.age",
                    "actuarial.life_table.qx",
                    "actuarial.life_table.lx",
                    "actuarial.life_table.dx",
                    "actuarial.life_table.ex",
                    "actuarial.life_table.tx",
                    "actuarial.life_table.px",
                    "actuarial.life_table.mx",
                    "actuarial.mortality_rate",
                    "actuarial.mortality_rate.age",
                    "actuarial.mortality_rate.gender",
                    "actuarial.mortality_rate.year",
                    "actuarial.mortality_rate.base",
                    "actuarial.mortality_rate.adjusted",
                    "actuarial.mortality_rate.select",
                    "actuarial.mortality_rate.ultimate",
                    "actuarial.mortality_rate.qx",
                    "actuarial.mortality_rate.mx",
                    "actuarial.morbidity_rate",
                    "actuarial.morbidity_rate.age",
                    "actuarial.morbidity_rate.gender",
                    "actuarial.morbidity_rate.condition",
                    "actuarial.morbidity_rate.disability",
                    "actuarial.morbidity_rate.incidence",
                    "actuarial.morbidity_rate.prevalence",
                    "actuarial.morbidity_rate.duration",
                    "actuarial.morbidity_rate.recovery",
                    "actuarial.interest_rate",
                    "actuarial.interest_rate.spot",
                    "actuarial.interest_rate.forward",
                    "actuarial.interest_rate.term",
                    "actuarial.interest_rate.yield_curve",
                    "actuarial.interest_rate.discount_factor",
                    "actuarial.interest_rate.technical_rate",
                    "actuarial.interest_rate.investment_return",
                    "actuarial.expense_assumption",
                    "actuarial.expense_assumption.initial",
                    "actuarial.expense_assumption.renewal",
                    "actuarial.expense_assumption.maintenance",
                    "actuarial.expense_assumption.acquisition",
                    "actuarial.expense_assumption.per_unit",
                    "actuarial.lapse_rate",
                    "actuarial.lapse_rate.by_policy_year",
                    "actuarial.lapse_rate.by_duration",
                    "actuarial.lapse_rate.select",
                    "actuarial.lapse_rate.ultimate",
                    "actuarial.surrender_rate",
                    "actuarial.surrender_rate.by_policy_year",
                    "actuarial.surrender_rate.by_duration",
                    "actuarial.surrender_rate.select",
                    "actuarial.surrender_rate.ultimate",
                    "actuarial.termination_rate",
                    "actuarial.termination_rate.by_policy_year",
                    "actuarial.termination_rate.by_duration",
                    "actuarial.termination_rate.select",
                    "actuarial.termination_rate.ultimate",
                    "actuarial.claim_cost",
                    "actuarial.claim_cost.ultimate",
                    "actuarial.claim_cost.severity",
                    "actuarial.claim_cost.frequency",
                    "actuarial.claim_cost.trend",
                    "actuarial.claim_cost.development",
                    "actuarial.claim_cost.loss_ratio",
                ],
                "count": 70,
            },
            "risk_assessment": {
                "description": "Risk scores, underwriting criteria, exposure assessment, and risk evaluation metrics",
                "reference": "NAIC, FERMA, ISO Risk Score, Credit Scoring Models",
                "fields": [
                    "risk.score",
                    "risk.score.type",
                    "risk.score.value",
                    "risk.score.date",
                    "risk.score.source",
                    "risk.underwriting.decision",
                    "risk.underwriting.decision_date",
                    "risk.underwriting.decision_by",
                    "risk.underwriting.criteria",
                    "risk.underwriting.risk_class",
                    "risk.underwriting.risk_tier",
                    "risk.underwriting.risk_category",
                    "risk.underwriting.auto_approved",
                    "risk.underwriting_manual_review",
                    "risk.underwriting.decline_reason",
                    "risk.underwriting.exclusion_reason",
                    "risk.underwriting.load_factor",
                    "risk.underwriting.rate_modification",
                    "risk.exposure.base",
                    "risk.exposure.type",
                    "risk.exposure.amount",
                    "risk.exposure.peril",
                    "risk.exposure.location",
                    "risk.exposure.building_value",
                    "risk.exposure.contents_value",
                    "risk.exposure.business_interruption_value",
                    "risk.exposure.total_insured_value",
                    "risk.exposure.replacement_cost_value",
                    "risk.exposure.actual_cash_value",
                    "risk.exposure.square_footage",
                    "risk.exposure.number_of_units",
                    "risk.exposure.year_built",
                    "risk.exposure.construction_type",
                    "risk.exposure.occupancy_type",
                    "risk.exposure.protection_class",
                    "risk.exposure.fire_district",
                    "risk.exposure.flood_zone",
                    "risk.exposure.earthquake_zone",
                    "risk.exposure.windstorm_area",
                    "risk.exposure.hurricane_deductible",
                    "risk.exposure.coverage_a_value",
                    "risk.exposure.coverage_b_value",
                    "risk.exposure.coverage_c_value",
                    "risk.exposure.coverage_d_value",
                    "risk.exposure.coinsurance_requirement",
                    "risk.exposure.premium_basis",
                    "risk.exposure.rate_per_unit",
                    "risk.exposure.applied_rate",
                    "risk.rating.class_code",
                    "risk.rating.sub_class_code",
                    "risk.rating.base_rate",
                    "risk.rating.modification_factor",
                    "risk.rating.experience_modification",
                    "risk.rating.merit_rating",
                    "risk.rating.credits",
                    "risk.rating.debits",
                    "risk.rating.final_rate",
                    "risk.credit.score",
                    "risk.credit.score_type",
                    "risk.credit.score_value",
                    "risk.credit.score_date",
                    "risk.credit.tier",
                    "risk.credit.classification",
                    "risk.credit.insurance_score",
                    "risk.hazard.score",
                    "risk.hazard.physical",
                    "risk.hazard.occupational",
                    "risk.hazard.environmental",
                    "risk.hazard.behavioral",
                    "risk.hazard.moral",
                    "risk.hazard.legal",
                    "risk.hazard.compliance",
                    "risk.hazard.operational",
                    "risk.hazard.financial",
                    "risk.hazard.reputational",
                    "risk.hazard.strategic",
                    "risk.hazard.cyber",
                    "risk.hazard.climate",
                    "risk.hazard.geopolitical",
                ],
                "count": 80,
            },
            "reinsurance": {
                "description": "Treaty, facultative, pools, loss ratios, and reinsurance structure",
                "reference": "RAA, Lloyd's Reinsurance Terms, AIDA, UNICE Reinsurance",
                "fields": [
                    "reinsurance.treaty.id",
                    "reinsurance.treaty.name",
                    "reinsurance.treaty.type",
                    "reinsurance.treaty.line_of_business",
                    "reinsurance.treaty.effective_date",
                    "reinsurance.treaty.expiration_date",
                    "reinsurance.treaty.status",
                    "reinsurance.treaty.broker",
                    "reinsurance.treaty.broker_commission",
                    "reinsurance.treaty.reinsurer",
                    "reinsurance.treaty.reinsurer.share",
                    "reinsurance.treaty.reinsurer.srn",
                    "reinsurance.treaty.cession_percentage",
                    "reinsurance.treaty.retention",
                    "reinsurance.treaty.retention_type",
                    "reinsurance.treaty.limit",
                    "reinsurance.treaty.limit_amount",
                    "reinsurance.treaty.layer",
                    "reinsurance.treaty.layer_number",
                    "reinsurance.treaty.layer_limit",
                    "reinsurance.treaty.layer_retention",
                    "reinsurance.treaty.premium",
                    "reinsurance.treaty.premium_rate",
                    "reinsurance.treaty.commission",
                    "reinsurance.treaty.profit_commission",
                    "reinsurance.treaty.loss_commission",
                    "reinsurance.treaty.sliding_scale",
                    "reinsurance.treaty.portfolio_transfer",
                    "reinsurance.treaty.cash_flow",
                    "reinsurance.facultative.id",
                    "reinsurance.facultative.treaty_reference",
                    "reinsurance.facultative.ceding_company",
                    "reinsurance.facultative.reinsurer",
                    "reinsurance.facultative.risk_description",
                    "reinsurance.facultative.sum_insured",
                    "reinsurance.facultative.premium",
                    "reinsurance.facultative.commission",
                    "reinsurance.facultative.limit",
                    "reinsurance.facultative.retention",
                    "reinsurance.facultative.accepted",
                    "reinsurance.facultative.decline_reason",
                    "reinsurance.pool.id",
                    "reinsurance.pool.name",
                    "reinsurance.pool.type",
                    "reinsurance.pool.participants",
                    "reinsurance.pool.share",
                    "reinsurance.pool.limit",
                    "reinsurance.pool.retention",
                    "reinsurance.pool.premium",
                    "reinsurance.pool.claims",
                    "reinsurance.loss_ratio.gross",
                    "reinsurance.loss_ratio.net",
                    "reinsurance.loss_ratio.ceded",
                    "reinsurance.loss_ratio.earned",
                    "reinsurance.loss_ratio.incurred",
                    "reinsurance.loss_ratio.paid",
                    "reinsurance.loss_ratio.combined",
                    "reinsurance.loss_ratio.loss_adjusted",
                    "reinsurance.syndicate.id",
                    "reinsurance.syndicate.number",
                    "reinsurance.syndicate.name",
                    "reinsurance.syndicate.member",
                    "reinsurance.syndicate.capacity",
                    "reinsurance.syndicate.funds",
                    "reinsurance.ceded.party",
                    "reinsurance.ceded.amount",
                    "reinsurance.ceded.date",
                    "reinsurance.ceded.type",
                    "reinsurance.ceded.recoverable",
                    "reinsurance.accepted.party",
                    "reinsurance.accepted.amount",
                    "reinsurance.accepted.date",
                    "reinsurance.accepted.type",
                    "reinsurance.stop_loss.threshold",
                    "reinsurance.stop_loss.percentage",
                    "reinsurance.stop_loss.amount",
                    "reinsurance.experience_refund",
                    "reinsurance.balance_statement",
                    "reinsurance.settlement.date",
                    "reinsurance.settlement.amount",
                ],
                "count": 70,
            },
            "regulatory": {
                "description": "Solvency, IFRS 17, NAIC, GDPR, and other regulatory compliance fields",
                "reference": "NAIC, Solvency II, IFRS 17, GDPR, EIOPA, IAIS",
                "fields": [
                    "regulatory.solvency.ratio",
                    "regulatory.solvency.capital",
                    "regulatory.solvency.requirement",
                    "regulatory.solvency.margin",
                    "regulatory.solvency.risk_based_capital",
                    "regulatory.solvency.ebitda",
                    "regulatory.solvency.leverage_ratio",
                    "regulatory.solvency.liquidity_ratio",
                    "regulatory.solvency.asset_liability_mismatch",
                    "regulatory.ifrs17.contract_boundary",
                    "regulatory.ifrs17.fulfilment_cash_flow",
                    "regulatory.ifrs17.risk_adjustment",
                    "regulatory.ifrs17.contractual_service_margin",
                    "regulatory.ifrs17.profit_recognition",
                    "regulatory.ifrs17.loss_component",
                    "regulatory.ifrs17.groups",
                    "regulatory.ifrs17.measurement",
                    "regulatory.ifrs17.discount_rate",
                    "regulatory.ifrs17.time_value_money",
                    "regulatory.ifrs17.credit_risk",
                    "regulatory.ifrs17.financial_assumptions",
                    "regulatory.ifrs17.non_financial_assumptions",
                    "regulatory.ifrs17.coverage_units",
                    "regulatory.ifrs17.service_provided",
                    "regulatory.ifrs17.benefit_payments",
                    "regulatory.naic.company_code",
                    "regulatory.naic.state_code",
                    "regulatory.naic.line_of_business",
                    "regulatory.naic.statutory_filing",
                    "regulatory.naic.annual_statement",
                    "regulatory.naic.quarterly_statement",
                    "regulatory.naic.examination",
                    "regulatory.naic.risk_based_capital",
                    "regulatory.gdpr.data_controller",
                    "regulatory.gdpr.data_processor",
                    "regulatory.gdpr.data_subject",
                    "regulatory.gdpr.purpose",
                    "regulatory.gdpr.legal_basis",
                    "regulatory.gdpr.consent",
                    "regulatory.gdpr.right_to_erasure",
                    "regulatory.gdpr.right_to_access",
                    "regulatory.gdpr.right_to_portability",
                    "regulatory.gdpr.retention_period",
                    "regulatory.gdpr.data_breach",
                    "regulatory.gdpr.data_protection_officer",
                    "regulatory.privacy.policy",
                    "regulatory.privacy.notice",
                    "regulatory.privacy.consent_record",
                    "regulatory.aml.kyc_status",
                    "regulatory.aml.sanctions_screening",
                    "regulatory.aml.aml_check",
                    "regulatory.aml.aml_status",
                    "regulatory.sanctions.list",
                    "regulatory.sanctions.check",
                    "regulatory.sanctions.match",
                    "regulatory.compliance.audit",
                    "regulatory.compliance.audit_date",
                    "regulatory.compliance.audit_result",
                    "regulatory.compliance.violation",
                    "regulatory.compliance.penalty",
                    "regulatory.compliance.remediation",
                    "regulatory.licensing.license_number",
                    "regulatory.licensing.license_type",
                    "regulatory.licensing.license_status",
                    "regulatory.licensing.jurisdiction",
                    "regulatory.licensing.expiration_date",
                ],
                "count": 60,
            },
            "claims_analytics": {
                "description": "Loss triangles, IBNR estimates, frequency, severity, and claims analytics metrics",
                "reference": "CAS, Society of Actuaries, ASTIN, Reinsurance Actuarial Standards",
                "fields": [
                    "claims.triangle.type",
                    "claims.triangle.origin_period",
                    "claims.triangle.development_period",
                    "claims.triangle.age_to_age",
                    "claims.triangle.link_ratio",
                    "claims.triangle.selected_link_ratio",
                    "claims.triangle.ultimate_claim_count",
                    "claims.triangle.ultimate_loss",
                    "claims.triangle.claim_count_development",
                    "claims.triangle.loss_development_factor",
                    "claims.triangle.cdf",
                    "claims.triangle.berquist_sherman",
                    "claims.triangle.bornhuetter_ferguson",
                    "claims.triangle.cape_cod",
                    "claims.triangle.loss_reserve",
                    "claims.triangle.unreported_claims",
                    "claims.triangle.reported_claims",
                    "claims.triangle.open_claims",
                    "claims.triangle.closed_claims",
                    "claims.triangle.closed_with_pay",
                    "claims.triangle.closed_without_pay",
                    "claims.triangle.incremental_values",
                    "claims.triangle.cumulative_values",
                    "claims.triangle.average_claim_size",
                    "claims.triangle.claim_count",
                    "claims.triangle.paid_loss",
                    "claims.triangle.incurred_loss",
                    "claims.triangle.outstanding_loss",
                    "claims.triangle.case_reserves",
                    "claims.ibnr.estimate",
                    "claims.ibnr.estimate_type",
                    "claims.ibnr.method",
                    "claims.ibnr.chain_ladder",
                    "claims.ibnr.bornhuetter_ferguson",
                    "claims.ibnr.capecod",
                    "claims.ibnr.loss_development",
                    "claims.ibnr.frequency_severity",
                    "claims.ibnr.bullseye",
                    "claims.ibnr.bootstrap",
                    "claims.ibnr.monte_carlo",
                    "claims.ibnr.simulation",
                    "claims.ibnr.residual_market",
                    "claims.ibnr.deficit",
                    "claims.ibnr.surplus",
                    "claims.ibnr.confidence_interval",
                    "claims.frequency.annual",
                    "claims.frequency.aggregate",
                    "claims.frequency.severity",
                    "claims.frequency.trend",
                    "claims.frequency.seasonality",
                    "claims.severity.average",
                    "claims.severity.median",
                    "claims.severity.mode",
                    "claims.severity.percentile",
                    "claims.severity.trend",
                    "claims.severity.development",
                    "claims.severity.inflation",
                    "claims.severity.building_costs",
                    "claims.severity.medical_costs",
                    "claims.severity.auto_repair_costs",
                    "claims.severity.wage_inflation",
                    "claims.severity.social_inflation",
                    "claims.severity.defensive_costs",
                    "claims.combined_ratio.gross",
                    "claims.combined_ratio.net",
                    "claims.combined_ratio.industry",
                    "claims.combined_ratio.target",
                    "claims.loss_ratio.statutory",
                    "claims.loss_ratio.gAAP",
                    "claims.loss_ratio.underwriting",
                    "claims.development.pattern",
                    "claims.development.factor",
                    "claims.development.triangle",
                    "claims.development.risk_margin",
                    "claims.development.uncertainty",
                    "claims.development.backwardation",
                    "claims.development.contango",
                ],
                "count": 50,
            },
        },
        "totals": {
            "categories": 7,
            "total_fields": 500,
        }
    }

    return INVENTORY


def main():
    print("=" * 70)
    print("INSURANCE/ACTUARIAL METADATA FIELD INVENTORY")
    print("=" * 70)
    print()

    inventory = generate_insurance_inventory()

    print(f"Generated: {inventory['generated_at']}")
    print(f"Categories: {inventory['totals']['categories']}")
    print(f"Total Fields: {inventory['totals']['total_fields']}")
    print()

    print("FIELD COUNTS BY CATEGORY:")
    print("-" * 50)
    for cat_name, cat_data in sorted(inventory['categories'].items(), key=lambda x: x[1]['count'], reverse=True):
        print(f"  {cat_name:35s}: {cat_data['count']:>4} fields")

    output_dir = Path("dist/insurance_inventory")
    output_dir.mkdir(parents=True, exist_ok=True)

    output_file = output_dir / "insurance_inventory.json"
    output_file.write_text(json.dumps(inventory, indent=2, sort_keys=True), encoding="utf-8")
    print()
    print(f"Wrote: {output_file}")

    summary = {
        "generated_at": inventory["generated_at"],
        "source": inventory["source"],
        "description": inventory["description"],
        "categories": {
            k: {
                "count": v["count"],
                "description": v["description"],
                "reference": v.get("reference", "N/A")
            }
            for k, v in inventory["categories"].items()
        },
        "totals": inventory["totals"],
    }

    summary_file = output_dir / "insurance_summary.json"
    summary_file.write_text(json.dumps(summary, indent=2, sort_keys=True), encoding="utf-8")
    print(f"Wrote: {summary_file}")


if __name__ == "__main__":
    main()
