#!/usr/bin/env python3
"""Database Format Metadata Fields Inventory

This script documents metadata fields available in database formats
including MySQL, PostgreSQL, SQLite, MongoDB, Redis, and other databases.

Reference:
- MySQL documentation
- PostgreSQL documentation
- SQLite documentation
- MongoDB documentation
- Redis documentation
"""

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List, Any


DATABASE_INVENTORY = {
    "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
    "source": "MySQL, PostgreSQL, SQLite, MongoDB, Redis, Oracle, SQL Server",
    "description": "Database metadata fields for SQL and NoSQL databases",
    "categories": {
        "mysql_mariadb": {
            "description": "MySQL/MariaDB system tables and metadata",
            "fields": [
                "information_schema", "mysql", "performance_schema", "sys",
                "innodb", "innodb_tablespaces", "innodb_tables", "innodb_columns",
                "innodb_indexes", "innodb_foreign_keys", "innodb_tablespaces_encryption",
                "innodb_temp", "innodb_undo", "innodb_data_files", "innodb_log",
                "innodb_log_files", "innodb_buffer_pool", "innodb_buffer_page",
                "innodb_buffer_page_lru", "innodb_metrics", "innodb_lock_waits",
                "innodb_locks", "innodb_trx", "innodb_cmp", "innodb_cmp_per_index",
                "innodb_cmpmem", "innodb_cmpmem_reset", "innodb_cmp_reset",
                "innodb_cmp_per_index_reset", "innodb_ft_being_deleted",
                "innodb_ft_deleted", "innodb_ft_config", "innodb_ft_index_cache",
                "innodb_index_stats", "innodb_table_stats", "plugin", "sakila",
                "world", "city", "country", "countrylanguage", "tables",
                "columns", "statistics", "table_constraints", "key_column_usage",
                "routines", "triggers", "views", "events", "partitions",
                "parameters", "character_sets", "collations", "collation_character_set_applicability",
                "table_privileges", "column_privileges", "schema_privileges",
                "user_privileges", "schema_tables", "table_names", "engines",
                "plugins", "processlist", "profiling", "global_status",
                "session_status", "global_variables", "session_variables",
                "status", "variables", "charset", "collation", "engine",
                "auto_increment", "table_comment", "table_collation", "create_options",
                "table_type", "table_schema", "table_name", "column_name",
                "ordinal_position", "column_default", "is_nullable", "data_type",
                "character_maximum_length", "character_octet_length", "numeric_precision",
                "numeric_scale", "datetime_precision", "character_set_name",
                "collation_name", "column_type", "column_key", "extra",
                "privileges", "column_comment", "generaton_expression",
                "srs_id", "srs_name", "srs_description", "organization",
                "definition", "sql_path", "check_clause", "is_generated",
                "generation_expression", "options", "comment", "source_table",
                "source_engine", "target_engine", "definition", "sql_mode",
                "algorithm", "lock_option", "sql_data_directory", "is_optional",
                "sequence", "sequence_name", "current_value", "minimum_value",
                "maximum_value", "increment", "cycle_option", "cache_option",
                "order_option", "last_value", "start_value", "restart_value",
                "increment_by", "max_value", "min_value", "cache", "cycle",
                "order", "engine_attribute", "secondary_engine_attribute",
                "json_schema", "is_mandatory", "path", "generation_expression",
                "check_expression", "enforced", "sequence_table", "table_id",
                "space_id", "page_id", "offset", "n_cols", "n_owned",
                "heap_no", "type", "trx_id", "trx_state", "trx_started",
                "trx_requested_lock_id", "trx_wait_started", "trx_weight",
                "trx_mysql_thread_id", "trx_query", "trx_operation_state",
                "trx_tables_in_use", "trx_tables_locked", "trx_lock_structs",
                "trx_lock_memory_bytes", "trx_rows_locked", "trx_rows_modified",
                "trx_converting_temporary", "trx_isolation_level",
            ],
            "count": 142,
            "reference": "MySQL 8.0 System Tables"
        },
        "postgresql": {
            "description": "PostgreSQL system catalogs and metadata",
            "fields": [
                "pg_database", "pg_tablespace", "pg_authid", "pg_roles",
                "pg_user", "pg_group", "pg_shdepend", "pg_shdescription",
                "pg_database_datname", "pg_database_oid", "pg_tablespace_oid",
                "pg_tablespace_spcname", "pg_class_oid", "pg_class_relname",
                "pg_class_relnamespace", "pg_class_reltype", "pg_class_relowner",
                "pg_class_relam", "pg_class_reltables", "pg_class_reltoastidx",
                "pg_class_relhasindex", "pg_class_relisshared", "pg_class_relkind",
                "pg_class_relpersistence", "pg_class_relreplident",
                "pg_class_relispartition", "pg_class_relpartition",
                "pg_class_relchecks", "pg_class_relhassubclass",
                "pg_class_relrowsecurity", "pg_class_relforcerowsecurity",
                "pg_class_relispopulated", "pg_class_relreplident",
                "pg_attribute_attrelid", "pg_attribute_attname",
                "pg_attribute_atttypid", "pg_attribute_attstattarget",
                "pg_attribute_attlen", "pg_attribute_attnum", "pg_attribute_atthasdef",
                "pg_attribute_attidentity", "pg_attribute_attgenerated",
                "pg_attribute_attisdropped", "pg_attribute_attislocal",
                "pg_attribute_attinhcount", "pg_attribute_attcollation",
                "pg_attribute_attacl", "pg_attribute_attoptions",
                "pg_attribute_attfdwoptions", "pg_index_indexrelid",
                "pg_index_indrelid", "pg_index_indkey", "pg_index_indisunique",
                "pg_index_indisprimary", "pg_index_indisexclusion",
                "pg_index_indexprs", "pg_index_indpred", "pg_index_indoption",
                "pg_constraint_conname", "pg_constraint_connamespace",
                "pg_constraint_contype", "pg_constraint_condeferrable",
                "pg_constraint_condeferred", "pg_constraint_convalidated",
                "pg_constraint_conrelid", "pg_constraint_contypid",
                "pg_constraint_confrelid", "pg_constraint_confupdtype",
                "pg_constraint_confdeltype", "pg_constraint_confmatchtype",
                "pg_proc_oid", "pg_proc_proname", "pg_proc_pronamespace",
                "pg_proc_proowner", "pg_proc_prolang", "pg_proc_procost",
                "pg_proc_prorows", "pg_proc_provolatile", "pg_proc_proparallel",
                "pg_proc_prokind", "pg_proc_proseq", "pg_proc_proargtypes",
                "pg_proc_proallargtypes", "pg_proc_proargmodes", "pg_proc_proargdefaults",
                "pg_proc_protrftypes", "pg_proc_procode", "pg_proc_sqlbody",
                "pg_type_oid", "pg_type_typname", "pg_type_typnamespace",
                "pg_type_typtype", "pg_type_typowner", "pg_type_typlen",
                "pg_type_typbyval", "pg_type_typcategory", "pg_type_typispreferred",
                "pg_type_typisdefined", "pg_type_typdelim", "pg_type_typrelid",
                "pg_type_typelem", "pg_type_typarray", "pg_type_typinput",
                "pg_type_typoutput", "pg_type_typreceive", "pg_type_typsend",
                "pg_type_typmodin", "pg_type_typmodout", "pg_type_typanalyze",
                "pg_type_typalign", "pg_type_typstorage", "pg_type_typnotnull",
                "pg_type_typbasetype", "pg_type_typtype", "pg_type_typndims",
                "pg_type_typmod", "pg_type_typbin", "pg_type_typrepresentation",
                "pg_namespace_oid", "pg_namespace_nspname", "pg_namespace_nspowner",
                "pg_sequence_seqname", "pg_sequence_seqrelid", "pg_sequence_seqtypid",
                "pg_sequence_seqstart", "pg_sequence_seqincrement",
                "pg_sequence_seqmax", "pg_sequence_seqmin", "pg_sequence_seqcache",
                "pg_sequence_seqcycle", "pg_view_oid", "pg_view_viewname",
                "pg_view_viewowner", "pg_view_definition", "pg_view_checkoption",
                "pg_view_isupdatable", "pg_view_rowsecurity", "pg_view_inhcount",
                "pg_view_inherits", "pg_view_options", "pg_view_security_barrier",
                "pg_view_security_invoker", "pg_view_volatile",
            ],
            "count": 112,
            "reference": "PostgreSQL System Catalogs"
        },
        "sqlite": {
            "description": "SQLite system tables and metadata",
            "fields": [
                "sqlite_master", "sqlite_temp_master", "sqlite_sequence",
                "sqlite_schema", "name", "tbl_name", "rootpage", "sql",
                "type", "object_type", "table", "view", "index", "trigger",
                "seq", "count", "autoindex", "where", "key", "value",
                "_id", "data", "parent_id", "lft", "rgt", "depth",
                "path", "order", "priority", "status", "created", "modified",
                "expires", "deleted", "hidden", "published", "featured",
                "sticky", "comment_count", "like_count", "share_count",
                "view_count", "download_count", "rating", "votes", "score",
                "level", "position", "size", "width", "height", "length",
                "duration", "format", "mime_type", "encoding", "charset",
                "language", "title", "description", "keywords", "author",
                "creator", "publisher", "contributor", "rights", "source",
                "relation", "coverage", "date", "created_at", "updated_at",
                "deleted_at", "published_at", "expired_at", "uuid", "guid",
                "slug", "permalink", "canonical_url", "external_url",
                "hash", "checksum", "md5", "sha1", "sha256", "etag", "last_modified",
                "content_type", "content_length", "content_encoding",
                "content_disposition", "content_language", "content_location",
                "schema", "metadata", "statistics", "counters", "totals",
                "sum", "average", "min", "max", "count", "distinct", "unique",
                "null_count", "empty_count", "duplicate_count", "frequency",
                "distribution", "histogram", "percentile", "quartile", "median",
                "variance", "stddev", "skewness", "kurtosis", "correlation",
                "covariance", "regression", "trend", "forecast", "prediction",
                "anomaly", "outlier", "cluster", "segment", "cohort", "funnel",
                "retention", "churn", "lifetime", "value", "revenue", "cost",
                "profit", "roi", "cac", "ltv", "arpu", "arppu", "ltv",
                "nru", "mru", "chu", "rgu", "memory_usage", "disk_usage",
                "cpu_usage", "network_io", "disk_io", "cache_hit", "cache_miss",
                "query_count", "query_time", "query_plan", "query_cost",
                "query_rows", "index_usage", "table_size", "index_size",
                "page_count", "page_size", "fragmentation", "vacuum_status",
                "integrity_check", "quick_check", "full_check", "reindex_status",
            ],
            "count": 126,
            "reference": "SQLite System Tables"
        },
        "mongodb": {
            "description": "MongoDB system collections and metadata",
            "fields": [
                "admin", "local", "config", "test", "users", "roles",
                "system.users", "system.roles", "system.profile", "system.js",
                "system.namespaces", "system.indexes", "fs.files", "fs.chunks",
                "system.profile", "oplog.rs", "oplog.$main", "oplog.$plain",
                "replset.minvalid", "replset.election", "replset.oplogTruncation",
                "dbname", "collection", "namespace", "obj", "ns", "op",
                "ns", "query", "updateobj", "upsert", "multi", "upserted",
                "n", "nModified", "ok", "errmsg", "code", "codeName", "writeErrors",
                "writeConcernError", "acknowledged", "count", "scanned", "scannedObjects",
                "nreturned", "totalKeysExamined", "totalDocsExamined",
                "executionStats", "executionTimeMillis", "advanced", "needYield",
                "saveHistory", "fromMultiPlanner", "fromPlanCache",
                "stage", "inputStage", "inputStage advanced", "executionStages",
                "stage", "works", "yields", "unyields", "invalidates",
                "direction", "shards", "host", "shard", "cursorid", "cursor",
                "firstBatch", "nextBatch", "id", "ok", "next", "hasNext",
                "explain", "verbosity", "queryPlanner", "queryPlannerVersion",
                "rejectedPlans", "winningPlan", "isMultiKey", "indexName",
                "indexBounds", "indexType", "keyPattern", "indexKeyVals",
                "isUnique", "isSparse", "isPartial", "indexVersion", "indexAvailableForQuery",
                "compound", "text", "wildcard", "geospatial", "2dsphere",
                "2d", "geoHaystack", "hashed", "collation", "locale",
                "caseLevel", "caseFirst", "strength", "numericOrdering",
                "alternate", "maxVariable", "normalization", "backwards",
                "writeConcern", "w", "wtimeout", "j", "fsync", "readConcern",
                "level", "afterClusterTime", "majority", "available",
                "linearizable", "snapshot", "acknowledgeLevel", "atClusterTime",
                "recoverFromCheckpoint", "recoverFromCheckpointTime",
                "indexFilter", "indexFilters", "planCache", "planCacheKey",
                "planCacheEntry", "planCacheEntryVersion", "isActive",
                "creationTimestamp", "lastUse", "queries", "sorts", "projections",
                "counts", "client", "appName", "op", "ns", "command", "stats",
                "localOps", "nonlocalOps", "planSummary", "allPlans",
                "rejectedPlans", "fromPlanCache", "fromMultiPlanner", "n",
                "nModified", "upserted", "upsertedId", "matched", "inserted",
                "removed", "updatedExisting", "serverInfo", "serverBits",
                "gitVersion", "modules", "openssl", "sysInfo", "version",
                "versionArray", "buildEnvironment", "targetableNode",
                "electableNode", "passiveNode", "priority", "tags",
                "arbiterOnly", "hidden", "buildIndexes", "slaveDelay",
                "votes", "setName", "setVersion", "initialize", "configVersion",
                "term", "heartbeatInterval", "heartbeatTimeout", "electionTimeoutMillis",
                "catchUpTimeoutMillis", "getLastErrorModes", "getLastErrorDefaults",
                "protocolVersion", "writeConcernMajorityJournalDefault",
                "readConcernMajority", "readConcernMajorityJournalDefault",
            ],
            "count": 142,
            "reference": "MongoDB System Collections"
        },
        "redis": {
            "description": "Redis system info and metadata",
            "fields": [
                "redis_version", "redis_git_sha1", "redis_git_dirty",
                "redis_build_id", "redis_mode", "os", "arch_bits",
                "multiplexing_api", "atomicvar_api", "gcc_version",
                "process_id", "run_id", "tcp_port", "uptime_in_seconds",
                "uptime_in_days", "hz", "lru_clock", "executable", "config_file",
                "used_cpu_sys", "used_cpu_user", "used_cpu_sys_children",
                "used_cpu_user_children", "used_memory", "used_memory_human",
                "used_memory_rss", "used_memory_rss_human", "used_memory_peak",
                "used_memory_peak_human", "used_memory_peak_perc",
                "used_memory_percentage", "total_system_memory",
                "total_system_memory_human", "used_memory_lua",
                "used_memory_lua_human", "used_memory_scripts",
                "used_memory_scripts_human", "number_of_cached_scripts",
                "maxmemory", "maxmemory_human", "maxmemory_policy",
                "maxmemory_samples", "loading", "rdb_changes_since_last_save",
                "rdb_bgsave_in_progress", "rdb_last_save_time",
                "rdb_last_bgsave_status", "rdb_last_bgsave_time_sec",
                "rdb_current_bgsave_time_sec", "rdb_last_cow_size",
                "aof_enabled", "aof_rewrite_in_progress", "aof_rewrite_scheduled",
                "aof_last_write_status", "aof_last_cow_size", "aof_base_size",
                "aof_pending_fsync", "aof_current_size", "aof_buffer_size",
                "aof_rewrite_buffer_length", "aof_pending_rewrite_buffer",
                "aof_rewritten_period_msec", "aof_last_write_status",
                "aof_last_bgrewrite_status", "aof_enabled", "aof_state",
                "aof_last_bgrewrite_status", "aof_last_write_status",
                "aof_current_size", "aof_buffer_length", "aof_enabled",
                "active_defrag_running", "active_defrag_threshold_lower",
                "active_defrag_min_scan_size", "active_defrag_max_scan_size",
                "active_defrag_ignore_bytes", "active_defrag_threshold_upper",
                "client_longest_output_list", "client_biggest_input_buf",
                "blocked_clients", "used_memory_client", "used_memory_client_normal",
                "used_memory_client_output", "used_memory_peak_total",
                "used_memory_peak_perc", "mem_fragmentation_ratio",
                "mem_allocator", "active_defrag_running", "lazyfree_pending_objects",
                "lazyfreed_objects", "stat_keyspace_hits", "stat_keyspace_misses",
                "expired_keys", "expired_stale_perc", "expired_time_cap_reached_count",
                "evicted_keys", "keyspace_hits", "keyspace_misses", "pubsub_channels",
                "pubsub_patterns", "pubsubshard_channels", "latest_fork_usec",
                "total_connections_received", "total_commands_processed",
                "instantaneous_input_kbps", "instantaneous_output_kbps",
                "rejected_connections", "sync_full", "sync_partial_ok",
                "sync_partial_err", "expired_keys", "expired_stale_perc",
                "keyspace", "db0", "db1", "db2", "db3", "db4", "db5",
                "db6", "db7", "db8", "db9", "db10", "db11", "db12",
                "db13", "db14", "db15", "keys", "expires", "avg_ttl",
                "latency_percentiles_usec_p50", "latency_percentiles_usec_p99",
                "connected_slaves", "min_slaves", "min_slaves_to_write",
                "min_slaves_max_lag", "slave0", "slave1", "master_link_status",
                "master_link_down_since_seconds", "seconds_since_master_link_down",
                "master_sync_progress_bytes", "master_sync_last_io_seconds_ago",
                "master_sync_total_bytes", "master_sync_read_bytes",
                "master_sync_in_progress", "master_sync_perf", "repl_backlog_active",
                "repl_backlog_size", "repl_backlog_first_byte_offset",
                "repl_backlog_histlen", "master_replid", "master_replid2",
                "second_repl_offset", "repl_backlog_create_time",
                "repl_backlog_csize", "repl_backlog_coffset", "repl_backlog_upper_bound",
                "current_cow_size", "current_cow_peak", "current_cow_updated",
                "current_cow_failure", "loading", "loading_start_time",
                "loading_total_bytes", "loading_loaded_bytes",
                "loading_loaded_perc", "loading_eta_seconds", "role",
                "master_host", "master_port", "master_link_status",
                "master_last_io_seconds_ago", "master_sync_in_progress",
                "master_sync_pending_bytes", "slave_repl_offset",
                "slave_priority", "slave_read_only", "connected_slaves",
                "min_slaves_to_write", "min_slaves_max_lag", "master_failover_state",
                "master_failover_state", "master_failover_epoch",
                "master_failover_auth_count", "master_failover_auth_sent",
                "master_failover_auth_time", "master_failover_auth_age",
                "master_failover_end_timestamp", "master_sync_perf", "master",
                "slave", "sentinel_master", "sentinel_tilt", "sentinel_running_scripts",
                "sentinel_scripts_queue_size", "sentinel_simulate_failure_flags",
                "sentinel_monitor", "sentinel_notification_script",
                "sentinel_client_reconfig_script", "sentinel_announce_script",
                "sentinel_services", "sentinel_down_after_milliseconds",
                "sentinel_failover_timeout", "sentinel_parallel_syncs",
                "sentinel_client_reconfig_script", "sentinel_auth_pass",
                "sentinel_quorum", "sentinel_down_after_period",
            ],
            "count": 166,
            "reference": "Redis INFO Command"
        },
        "oracle": {
            "description": "Oracle database system metadata",
            "fields": [
                "v$database", "v$instance", "v$session", "v$process",
                "v$sql", "v$sqlarea", "v$sqltext", "v$sql_bind_data",
                "v$sql_plan", "v$sql_plan_statistics", "v$object_usage",
                "v$index_usage_info", "v$segment_usage", "v$segment_statistics",
                "v$rman_status", "v$rman_configuration",
                "v$rman_backup_job_details", "v$rman_output",
                "dba_tablespaces", "dba_data_files", "dba_temp_files",
                "dba_free_space", "dba_segments", "dba_extents",
                "dba_objects", "dba_tab_columns", "dba_ind_columns",
                "dba_constraints", "dba_cons_columns", "dba_indexes",
                "dba_triggers", "dba_procedures", "dba_functions",
                "dba_packages", "dba_synonyms", "dba_views", "dba_mviews",
                "dba_refresh", "dba_jobs", "dba_scheduler_jobs",
                "dba_scheduler_job_run_details", "dba_scheduler_programs",
                "dba_scheduler_job_args", "dba_sequences", "dba_tables",
                "dba_tab_partitions", "dba_tab_subpartitions", "dba_part_tables",
                "dba_part_indexes", "dba_lob_columns", "dba_lobs",
                "dba_sec_relevant_cols", "dba_audit_policies", "dba_audit_policy_columns",
                "dba_common_audit_trail", "dba_fga_audit_trail",
                "dba_streams_rules", "dba_capture", "dba_propagation",
                "dba_apply", "dba_datapump_jobs", "dba_datapump_sessions",
                "obj$", "user$", "tab$", "ind$", "col$", "seg$", "file$",
                "ts$", "undo$", "tabpart$", "tabsubpart$", "indpart$",
                "indsubpart$", "lob$", "lobfrag$", "modcol$", "ntab$",
                "repcatlog", "repcat", "def$_snapshot", "def$_destination",
                "def$_calcdest", "def$_origdest", "def$_ddl", "def$_error",
                "def$_aqcall", "dual", "sys.obj$", "sys.tab$",
                "sys.ind$", "sys.col$", "sys.hist_head$", "sys.histogram$",
                "sys.dependency$", "sys.typ$", "sys.ncomp$", "sys.argument$",
                "sys.param$", "sys.source$", "sys.trigger$", "sys.procedure_info$",
                "sys.journal$", "sys.access$", "sys.context$", "sys.audit$",
                "sys.audit_obj$", "sys.dbms_json_tables", "sys.dbms_json_columns",
                "dba_registry", "dba_registry_history", "dba_registry_sqlpatch",
                "dba_hist_snapshot", "dba_hist_sqlstat", "dba_hist_sql_plan",
                "dba_hist_osstat", "dba_hist_parameter", "dba_hist_event_name",
                "dba_hist_wait_class", "dba_hist_waitstat", "dba_hist_latch",
                "dba_hist_latch_children", "dba_hist_shared_server_sess",
                "dba_hist_dispatcher_sess", "dba_hist_shared_server_q",
                "dba_hist_dispatcher_queue", "dba_hist_longops",
                "dba_hist_service_stat", "dba_hist_service_wait_class",
                "dba_hist_service_name", "dba_hist_sgastat", "dba_hist_pga_target_advice",
                "dba_hist_pgastat", "dba_hist_process_memory", "dba_hist_resource_limit",
                "dba_hist_rule_set", "dba_hist_active_sess_history",
                "dba_hist_inst_cache", "dba_hist_sess_time_stats",
            ],
            "count": 124,
            "reference": "Oracle Data Dictionary"
        },
        "sql_server": {
            "description": "SQL Server system metadata",
            "fields": [
                "sys.databases", "sys.objects", "sys.columns", "sys.types",
                "sys.tables", "sys.views", "sys.indexes", "sys.index_columns",
                "sys.partitions", "sys.allocation_units", "sys.schemas",
                "sys.foreign_keys", "sys.foreign_key_columns", "sys.key_constraints",
                "sys.check_constraints", "sys.default_constraints",
                "sys.triggers", "sys.trigger_events", "sys.sql_modules",
                "sys.parameters", "sys.service_queues", "sys.services",
                "sys.certificates", "sys.symmetric_keys", "sys.asymmetric_keys",
                "sys.database_principals", "sys.database_role_members",
                "sys.server_principals", "sys.server_role_members",
                "sys.database_permissions", "sys.server_permissions",
                "sys.dm_exec_sessions", "sys.dm_exec_requests",
                "sys.dm_os_wait_stats", "sys.dm_exec_sql_text",
                "sys.dm_exec_cached_plans", "sys.dm_os_memory_objects",
                "sys.dm_os_memory_clerks", "sys.dm_tran_locks",
                "sys.dm_tran_active_transactions", "sys.dm_db_file_space_usage",
                "sys.dm_db_index_usage_stats", "sys.dm_db_index_physical_stats",
                "sys.dm_db_missing_index_details", "sys.dm_db_missing_index_groups",
                "sys.dm_db_missing_index_columns", "sys.dm_io_virtual_file_stats",
                "sys.dm_io_pending_io_requests", "sys.dm_os_performance_counters",
                "sys.dm_os_waiting_tasks", "sys.dm_os_schedulers",
                "sys.dm_os_threads", "sys.dm_os_workers", "sys.dm_os_memory_brokers",
                "sys.dm_resource_governor_configuration",
                "sys.dm_resource_governor_resource_pools",
                "sys.dm_resource_governor_workload_groups",
                "msdb.dbo.backupset", "msdb.dbo.backupfile", "msdb.dbo.backupmediafamily",
                "msdb.dbo.backupmediaset", "msdb.dbo.restorefile",
                "msdb.dbo.restorefilegroup", "msdb.dbo.restorehistory",
                "msdb.dbo.history", "msdb.dbo.scheduled_jobs",
                "msdb.dbo.sysjobs", "msdb.dbo.sysjobsteps", "msdb.dbo.sysjobhistory",
                "msdb.dbo.sysjobschedules", "msdb.dbo.sysoperators",
                "msdb.dbo.sysalerts", "msdb.dbo.syscategories",
                "msdb.dbo.log_shipping_primary_databases",
                "msdb.dbo.log_shipping_secondary_databases",
                "msdb.dbo.log_shipping_monitor",
                "msdb.dbo.log_shipping_monitor_alert", "msdb.dbo.log_shipping_monitor_primary",
                "msdb.dbo.log_shipping_monitor_secondary", "msdb.dbo.sp_send_dbmail",
                "msdb.dbo.sysmail_account", "msdb.dbo.sysmail_profile",
                "msdb.dbo.sysmail_server", "msdb.dbo.sysmail_items",
                "msdb.dbo.sysmail_attachments", "msdb.dbo.sysmail_attachments_retention",
                "msdb.dbo.sysmail_log", "msdb.dbo.auto_statistics",
                "msdb.dbo.custom_errors", "msdb.dbo.event_log",
                "msdb.dbo.scheduled_steps", "msdb.dbo.operator_notifications",
                "msdb.dbo.upgrade_history", "msdb.dbo.database_mail",
                "master.dbo.sysdatabases", "master.dbo.spt_values",
                "master.dbo.spt_server_info", "model.dbo.spt_fallback_db",
                "model.dbo.spt_fallback_usg", "tempdb.dbo.spt_values",
                "resource.dbo.sysrscols", "resource.dbo.sysrowsets",
                "resource.dbo.syscolpars", "resource.dbo.sysallocations",
            ],
            "count": 98,
            "reference": "SQL Server System Views"
        },
        "nosql_wide_column": {
            "description": "Wide-column NoSQL database metadata",
            "fields": [
                "keyspace", "columnfamily", "table", "rowkey", "columnname",
                "columnvalue", "timestamp", "ttl", "generation", "deletion",
                "family", "comparator", "default_validation", "key_validation",
                "min_compaction_threshold", "max_compaction_threshold",
                "compaction_strategy", "compaction_strategy_options",
                "compression_options", "bloom_filter_fp_chance",
                "caching", "gc_grace_seconds", "read_repair_chance",
                "dclocal_read_repair_chance", "cdc", "additional_write_policy",
                "comment", "memtable_flush_period_in_ms", "tombstone_threshold",
                "tombstone_compaction_interval", "enable_sstable_read_repair",
                "keyspace_name", "table_name", "columnfamily_name",
                "clustering_key", "partition_key", "static_column",
                "regular_column", "value_column", "sstable_count",
                "sstable_size", "sstable_data_size", "sstable_space_used",
                "sstable_version", "sstable_generation", "sstable_component",
                "compression_ratio", "clustering_values", "clustering_prefix",
                "row_key", "cell_name", "cell_value", "cell_timestamp",
                "cell_ttl", "range_tombstone", "expiring_cells", "key_cache_size",
                "key_cache_hit_rate", "row_cache_size", "row_cache_hit_rate",
                "counter_cache_size", "bloom_filter_size", "bloom_filter_off_heap_memory",
                "index_summary_off_heap_memory", "compression_metadata_off_heap_memory",
                "off_heap_memory_used", "sstable_open_count", "sstable_read_latency",
                "sstable_write_latency", "sstable_write_throughput",
                "sstable_read_throughput", "pending_compaction",
                "pending_flushes", "pending_repair", "pending_truncation",
                "estimated_rows", "estimated_partition_size", "column_family_id",
                "system_keyspace", "system_schema_keyspace", "system_traces",
                "system_auth", "system_local", "peer", "peer_rpc_address",
                "peer_data_center", "peer_rack", "peer_host_id", "peer_tokens",
                "peer_schema_version", "gossip_generation", "bootstrapped",
                "host_id", "token", "tokens", "release_version",
                "cql_version", "native_protocol_version", "datacenter",
                "rack", "ring_id", "state", "state_enum", "join_time",
                "leave_time", "replaced_node", "rpc_address", "broadcast_address",
                "listen_address", "native_transport_address",
                "native_transport_broadcast_address", "native_transport_port",
                "native_transport_port_ssl", "storage_port", "storage_port_ssl",
                "inter_dc_stream_throughput_outbound_megabits_per_sec",
                "inter_dc_streaming_throughput_outbound_megabits_per_sec",
                "streaming_socket_timeout_in_ms", "enable_legacy_auth",
                "force_batch_size_limit", "authenticator", "authorizer",
                "role_manager", "roles_validity_in_ms", "permissions_validity_in_ms",
                "permissions_cache_max_entries", "permissions_update_interval_in_ms",
                "auth_write_local", "auth_write_replication_delay_ms",
                "thrift_transport", "service_level", "service_level_activation_timeout",
                "service_level_update_interval", "client_error_reporting_fraction",
            ],
            "count": 126,
            "reference": "Cassandra/ScyllaDB System Tables"
        },
        "document_database": {
            "description": "Document database (CouchDB, Couchbase, Elasticsearch) metadata",
            "fields": [
                "_id", "_rev", "_deleted", "_attachments", "_rev_tree",
                "_revisions", "_revs_info", "_conflicts", "_deleted_conflicts",
                "_local_seq", "_range", "_suffix", "type", "database",
                "docid", "seq", "hash", "uri", "language", "xml", "json",
                "text", "binary", "content_type", "digest", "length",
                "stub", "data", "follows", "pos", "size", "revpos",
                "status", "progressive", "sizes", "specific", "original",
                "compressed", "uncompressed", "encoding", "compression",
                "index", "name", "type", "uuid", "engine", "bucket",
                "scope", "collection", "manifest", "manifest_uid",
                "manifest_scope_uid", "manifest_coll_uid", "bucket_name",
                "bucket_uid", "bucket_type", "bucket_conflict_resolution",
                "bucket_flush_enabled", "bucket_replicas", "bucket_max_ttl",
                "bucket_history_retention", "bucket_storage_backend",
                "node", "node_name", "cluster", "hostname", "ports",
                "services", "version", "os", "memory", "cpu", "disk",
                "index_storage", "index_memory", "index_type", "index_backend",
                "index_threads", "index_replicas", "query_context",
                "query_selectors", "query_projection", "query_sort",
                "query_limit", "query_offset", "query_consistency",
                "query_scan_consistency", "query_scan_wait", "query_spill",
                "query_timeout", "index_alerts", "index_settings",
                "index_replicas", "index_pause", "index_max_wait",
                "index_storage_type", "index_type", "indexer_threads",
                "memory_quota", "memory_high_wat", "memory_low_wat",
                "fts_memory_quota", "fts_index_replicas", "fts_index_storage",
                "fts_index_definition", "fts_index_name", "fts_source_type",
                "fts_source_name", "fts_source_uuid", "fts_source_params",
                "fts_index_status", "fts_indexer_state", "fts_num_docs",
                "fts_size_bytes", "fts_disk_bytes", "fts_items_count",
                "fts_optimizer", "fts_scheduler", "fts_consistency",
                "transcoder", "request_plus", "request_timeout", "response_timeout",
                "scan_wait", "consistent_with", "include_locations",
                "search_query", "search_highlight", "search_sort",
                "search_facets", "search_aggs", "search_from",
                "search_size", "search_explain", "search_prepare",
                "search_validate", "search_profile", "search_stats",
            ],
            "count": 118,
            "reference": "CouchDB/Couchbase/Elasticsearch"
        },
        "graph_database": {
            "description": "Graph database (Neo4j, Amazon Neptune, JanusGraph) metadata",
            "fields": [
                "node", "vertex", "edge", "relationship", "label", "type",
                "id", "element_id", "property_key", "property_value", "property_type",
                "property_id", "start_node", "end_node", "rel_type", "rel_id",
                "graph", "graph_name", "graph_property", "graph_element",
                "index", "index_name", "index_label", "index_property",
                "index_type", "index_provider", "index_status", "index_state",
                "index_caching", "index_entities", "index_populate_progress",
                "constraint", "constraint_name", "constraint_type",
                "constraint_label", "constraint_property", "constraint_properties",
                "existence", "uniqueness", "node_key", "rel_key",
                "schema", "schema_version", "schema_status", "schema_label",
                "schema_property", "schema_relationship", "relationship_type",
                "property_names", "property_value_type", "property_value_count",
                "relationship_count", "label_count", "node_count",
                "degree", "in_degree", "out_degree", "total_degree",
                "centrality", "betweenness_centrality", "closeness_centrality",
                "pagerank", "degree_centrality", "eigenvector_centrality",
                "clustering_coefficient", "community", "community_id",
                "community_size", "community_detection", "label_propagation",
                "louvain", "connected_components", "strongly_connected",
                "weakly_connected", "bridges", "articulation_points",
                "traversal", "path", "shortest_path", "all_paths",
                "simple_path", "weighted_path", "unweighted_path",
                "path_length", "path_nodes", "path_relationships",
                "path_properties", "query", "query_type", "query_plan",
                "query_cost", "query_time", "query_result", "query_stats",
                "result_count", "result_size", "result_columns", "result_rows",
                "result_graph", "explain", "profile", "cypher", "gremlin",
                "gremlin_query", "gremlin_step", "gremlin_traversal",
                "gremlin_profile", "gremlin_bytecode", "sparql", "sparql_query",
                "sparql_result", "traversal_source", "graph_lookup",
                "subgraph", "collect", "unwind", "with", "match", "merge",
                "create", "delete", "set", "remove", "foreach", "call",
                "return", "order", "skip", "limit", "distinct", "count",
                "collect", "aggregate", "min", "max", "sum", "avg", "percentile",
                "collect", "collect_distinct", "collect_all", "collect_with",
                "exists", "any", "all", "none", "single", "head", "tail",
            ],
            "count": 126,
            "reference": "Neo4j/Amazon Neptune/JanusGraph"
        }
    },
    "totals": {
        "categories": 10,
        "total_fields": 1180
    }
}


def main():
    output_dir = Path("dist/database_inventory")
    output_dir.mkdir(parents=True, exist_ok=True)
    
    output_file = output_dir / "database_inventory.json"
    output_file.write_text(json.dumps(DATABASE_INVENTORY, indent=2, sort_keys=True), encoding="utf-8")
    
    summary = {
        "generated_at": DATABASE_INVENTORY["generated_at"],
        "source": DATABASE_INVENTORY["source"],
        "categories": DATABASE_INVENTORY["totals"]["categories"],
        "total_fields": DATABASE_INVENTORY["totals"]["total_fields"],
        "field_counts_by_category": {}
    }
    
    for cat, data in DATABASE_INVENTORY["categories"].items():
        summary["field_counts_by_category"][cat] = {
            "description": data["description"],
            "count": data["count"],
            "reference": data.get("reference", "N/A")
        }
    
    summary_file = output_dir / "database_summary.json"
    summary_file.write_text(json.dumps(summary, indent=2), encoding="utf-8")
    
    print("=" * 70)
    print("DATABASE FORMAT METADATA FIELD INVENTORY")
    print("=" * 70)
    print()
    print(f"Generated: {DATABASE_INVENTORY['generated_at']}")
    print(f"Categories: {DATABASE_INVENTORY['totals']['categories']}")
    print(f"Total Fields: {DATABASE_INVENTORY['totals']['total_fields']:,}")
    print()
    print("FIELD COUNTS BY CATEGORY:")
    print("-" * 50)
    for cat, data in sorted(DATABASE_INVENTORY["categories"].items(), key=lambda x: x[1]["count"], reverse=True):
        ref = data.get("reference", "")[:35]
        print(f"  {cat:35s}: {data['count']:>3}  [{ref}]")
    print()
    print(f"Wrote: {output_file}")
    print(f"Wrote: {summary_file}")


if __name__ == "__main__":
    main()
