#!/usr/bin/env python3
"""Sports Analytics/Wearable Metadata Field Inventory for MetaExtract.

Covers wearable sensors, player tracking, performance metrics, team sports, biomechanics, sports metadata, and betting/odds.
"""

from datetime import datetime, timezone
import json
from pathlib import Path


def generate_sports_inventory():
    """Generate comprehensive sports analytics/wearable metadata field inventory."""

    INVENTORY = {
        "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "source": "Wearable device specifications, GPS tracking systems, sports analytics platforms, league data standards, biomechanics research, sports betting APIs",
        "description": "Sports analytics metadata including wearable sensors, player tracking, performance metrics, team sports data, biomechanics, sports metadata, and betting/odds",
        "categories": {
            "wearable_sensors": {
                "description": "Wearable device sensor fields for heart rate, GPS, accelerometer, gyroscope, cadence",
                "reference": "Wearable device specifications, Garmin, Apple Watch, Whoop, Oura, Polar, Wahoo standards",
                "fields": [
                    "wearable.heart_rate",
                    "wearable.heart_rate_resting",
                    "wearable.heart_rate_max",
                    "wearable.heart_rate_min",
                    "wearable.heart_rate_average",
                    "wearable.heart_rate_variability",
                    "wearable.hrv_sdnn",
                    "wearable.hrv_rmssd",
                    "wearable.hrv_pnn50",
                    "wearable.hrv_lf",
                    "wearable.hrv_hf",
                    "wearable.hrv_lf_hf_ratio",
                    "wearable.heart_rate_recovery",
                    "wearable.heart_rate_zone_1",
                    "wearable.heart_rate_zone_2",
                    "wearable.heart_rate_zone_3",
                    "wearable.heart_rate_zone_4",
                    "wearable.heart_rate_zone_5",
                    "wearable.gps_latitude",
                    "wearable.gps_longitude",
                    "wearable.gps_altitude",
                    "wearable.gps_speed",
                    "wearable.gps_course",
                    "wearable.gps_accuracy",
                    "wearable.gps_horizontal_dilution",
                    "wearable.gps_vertical_dilution",
                    "wearable.gps_position_dilution",
                    "wearable.gps_satellite_count",
                    "wearable.gps_fix_status",
                    "wearable.gps_timestamp",
                    "wearable.accelerometer_x",
                    "wearable.accelerometer_y",
                    "wearable.accelerometer_z",
                    "wearable.accelerometer_magnitude",
                    "wearable.accelerometer_peak",
                    "wearable.accelerometer_rms",
                    "wearable.gyroscope_x",
                    "wearable.gyroscope_y",
                    "wearable.gyroscope_z",
                    "wearable.gyroscope_magnitude",
                    "wearable.gyroscope_angular_velocity",
                    "wearable.cadence",
                    "wearable.cadence_running",
                    "wearable.cadence_cycling",
                    "wearable.cadence_strike_rate",
                    "wearable.stride_length",
                    "wearable.vertical_oscillation",
                    "wearable.ground_contact_time",
                    "wearable.ground_contact_balance",
                    "wearable.training_load",
                    "wearable.acute_training_load",
                    "wearable.chronic_training_load",
                    "wearable.training_stress_score",
                    "wearable.recovery_time",
                    "wearable.strain_score",
                    "wearable.sleep_score",
                    "wearable.sleep_duration",
                    "wearable.sleep_deep",
                    "wearable.sleep_light",
                    "wearable.sleep_rem",
                    "wearable.sleep_awake",
                    "wearable.sleep_restlessness",
                    "wearable.respiratory_rate",
                    "wearable.oxygen_saturation",
                    "wearable.skin_temperature",
                    "wearable.blood_glucose",
                    "wearable.blood_lactate",
                    "wearable.emg_signal",
                    "wearable.muscle_oxygenation",
                    "wearable.body_fat_percentage",
                    "wearable.muscle_mass",
                    "wearable.bone_mass",
                    "wearable.basal_metabolic_rate",
                    "wearable.wearable_device_id",
                    "wearable.firmware_version",
                    "wearable.battery_level",
                    "wearable.sampling_rate",
                    "wearable.sensor_fusion",
                    "wearable.magnetometer_x",
                    "wearable.magnetometer_y",
                    "wearable.magnetometer_z",
                    "wearable.barometric_pressure",
                    "wearable.elevation_gain",
                    "wearable.elevation_loss",
                    "wearable.grade",
                    "wearable.vertical_speed",
                    "wearable.step_count",
                    "wearable.calories_burned",
                    "wearable.active_calories",
                    "wearable.distance",
                    "wearable.pace",
                    "wearable.speed_zone",
                ],
                "count": 80,
            },
            "player_tracking": {
                "description": "Player tracking fields for position, velocity, acceleration, heat maps",
                "reference": "Player tracking systems, Catapult, Stats Perform, Second Spectrum, ChyronHego, TRACAB",
                "fields": [
                    "tracking.player_id",
                    "tracking.player_name",
                    "tracking.team_id",
                    "tracking.team_name",
                    "tracking.jersey_number",
                    "tracking.position",
                    "tracking.position_x",
                    "tracking.position_y",
                    "tracking.position_z",
                    "tracking.velocity_x",
                    "tracking.velocity_y",
                    "tracking.velocity_z",
                    "tracking.speed",
                    "tracking.velocity_magnitude",
                    "tracking.velocity_direction",
                    "tracking.acceleration_x",
                    "tracking.acceleration_y",
                    "tracking.acceleration_z",
                    "tracking.acceleration_magnitude",
                    "tracking.deceleration",
                    "tracking.deceleration_peak",
                    "tracking.acceleration_peak",
                    "tracking.jumps",
                    "tracking.jump_height",
                    "tracking.jump_count",
                    "tracking.jump_landing",
                    "tracking.sprints",
                    "tracking.sprint_count",
                    "tracking.sprint_distance",
                    "tracking.sprint_speed",
                    "tracking.sprint_duration",
                    "tracking.high_speed_running",
                    "tracking.high_speed_distance",
                    "tracking.high_speed_duration",
                    "tracking.total_distance",
                    "tracking.distance_covered",
                    "tracking.heat_map_x",
                    "tracking.heat_map_y",
                    "tracking.heat_map_density",
                    "tracking.heat_map_zone",
                    "tracking.time_in_zone",
                    "tracking.time_in_attacking_zone",
                    "tracking.time_in_defensive_zone",
                    "tracking.possession_time",
                    "tracking.duels_won",
                    "tracking.duels_lost",
                    "tracking.interceptions",
                    "tracking.tackles",
                    "tracking.tackles_successful",
                    "tracking.tackles_unsuccessful",
                    "tracking.blocks",
                    "tracking.clearances",
                    "tracking.recoveries",
                    "tracking.losses",
                    "tracking.turnovers",
                    "tracking.touches",
                    "tracking.touches_ball",
                    "tracking.passing",
                    "tracking.passes_completed",
                    "tracking.passes_attempted",
                    "tracking.pass_accuracy",
                    "tracking.pass_length",
                    "tracking.pass_angle",
                    "tracking.key_passes",
                    "tracking.assists",
                    "tracking.chances_created",
                    "tracking.shots",
                    "tracking.shots_on_target",
                    "tracking.shots_off_target",
                    "tracking.goals",
                    "tracking.xg_expected_goals",
                    "tracking.xa_expected_assists",
                    "tracking.xg_chain",
                    "tracking.xg_buildup",
                    "tracking.progressive_passes",
                    "tracking.progressive_carries",
                    "tracking.progressive_runs",
                    "tracking.beat_opponent",
                    "tracking.fouls_drawn",
                    "tracking.fouls_committed",
                    "tracking.yellow_cards",
                    "tracking.red_cards",
                    "tracking.substitutions",
                    "tracking.minutes_played",
                    "tracking.playing_time",
                    "tracking.formation",
                    "tracking.formation_slot",
                    "tracking.tracking_confidence",
                    "tracking.tracking_quality",
                    "tracking.gps_satellite_count",
                    "tracking.tracking_timestamp",
                ],
                "count": 90,
            },
            "performance_metrics": {
                "description": "Performance metrics fields for VO2 max, power output, fatigue index",
                "reference": "Sports science research, exercise physiology, performance testing standards",
                "fields": [
                    "performance.vo2max",
                    "performance.vo2max_relative",
                    "performance.vo2max_percentile",
                    "performance.power_output",
                    "performance.power_watts",
                    "performance.power_weight_ratio",
                    "performance.fatigue_index",
                    "performance.fatigue_resistance",
                    "performance.fatigue_rate",
                    "performance.perceived_exertion",
                    "performance.rpe_score",
                    "performance.rpe_session",
                    "performance.rpe_load",
                    "performance.monark_load",
                    "performance.sessions_rpe",
                    "performance.arsenal_load",
                    "performance.trimp_score",
                    "performance.trimp_zonal",
                    "performance.heart_rate_ratio",
                    "performance.hr_recovery_slope",
                    "performance.lactate_threshold",
                    "performance.lactate_turnpoint",
                    "performance.personal_best",
                    "performance.season_best",
                    "performance.peak_speed",
                    "peak_power_output",
                    "performance.maximal_speed",
                    "performance.minimal_speed",
                    "performance.speed_range",
                    "performance.speed_decline",
                    "performance.elastic_strength",
                    "performance.reactive_strength",
                    "performance.cmj_height",
                    "performance.squat_jump_height",
                    "performance.drop_jump_height",
                    "performance.standing_long_jump",
                    "performance.shuttle_run",
                    "performance.t_drill",
                    "performance.agility_score",
                    "performance.change_of_direction",
                    "performance.coi",
                    "performance.combined_score",
                    "performance.readiness_score",
                    "performance.readiness_strain",
                    "performance.readiness_recovery",
                    "performance.fitness_score",
                    "performance.freshness_index",
                    "performance.wellness_score",
                    "performance.mood_score",
                    "performance.soreness_score",
                    "performance.soreness_muscle",
                    "performance.injury_risk",
                    "performance.injury_prediction",
                    "performance.load_management",
                    "performance.load_compliance",
                    "performance.soft_tissue_risk",
                    "performance.muscle_damage",
                    "performance.inflammation",
                    "performance.creatine_kinase",
                    "performance.c_reactive_protein",
                    "performance.testosterone",
                    "performance.cortisol",
                    "performance.testosterone_cortisol_ratio",
                    "performance.hrv_readiness",
                    "performance.satellite_cell_count",
                    "performance.muscle_glycogen",
                    "performance.hydration_status",
                    "performance.body_mass",
                    "performance.skinfold_measurements",
                    "performance.lean_mass",
                    "performance.fat_mass",
                    "performance.aerobic_capacity",
                    "performance.anaerobic_capacity",
                    "performance.anaerobic_threshold",
                    "performance.aerobic_threshold",
                    "performance.zone_1_time",
                    "performance.zone_2_time",
                    "performance.zone_3_time",
                    "performance.zone_4_time",
                    "performance.zone_5_time",
                    "performance.work_rest_ratio",
                    "performance.intensity_domain",
                    "performance.speed_index",
                    "performance.grade_adjusted_pace",
                    "performance.training_effect",
                    "performance.training_impulse",
                    "performance.cardiac_drift",
                    "performance.cardiac_stroke_volume",
                    "performance.cardiac_output",
                ],
                "count": 95,
            },
            "team_sports": {
                "description": "Team sports tracking data for soccer, basketball, football",
                "reference": "League data standards, FIFA, NBA, NFL, MLB, NHL tracking specifications",
                "fields": [
                    "team_sports.soccer",
                    "team_sports.soccer.ball_possession",
                    "team_sports.soccer.territorial_possession",
                    "team_sports.soccer.pass_network",
                    "team_sports.soccer.pass_map",
                    "team_sports.soccer.heat_map",
                    "team_sports.soccer.coordinates",
                    "team_sports.soccer.events",
                    "team_sports.soccer.shot_map",
                    "team_sports.soccer.goal_conversion",
                    "team_sports.soccer.build_up_play",
                    "team_sports.soccer.pressing_intensity",
                    "team_sports.soccer.pressing_success",
                    "team_sports.soccer.counter_press",
                    "team_sports.soccer.transition_play",
                    "team_sports.soccer.set_pieces",
                    "team_sports.soccer.corners",
                    "team_sports.soccer.free_kicks",
                    "team_sports.soccer.penalties",
                    "team_sports.basketball",
                    "team_sports.basketball.player_tracking",
                    "team_sports.basketball.player_movement",
                    "team_sports.basketball.positions",
                    "team_sports.basketball.player_speed",
                    "team_sports.basketball.player_acceleration",
                    "team_sports.basketball.player_deceleration",
                    "team_sports.basketball.court_coverage",
                    "team_sports.basketball.touches",
                    "team_sports.basketball.touch_time",
                    "team_sports.basketball.touch_location",
                    "team_sports.basketball.shot_attempts",
                    "team_sports.basketball.shot_chart",
                    "team_sports.basketball.three_pointers",
                    "team_sports.basketball.free_throws",
                    "team_sports.basketball.rebounds",
                    "team_sports.basketball.assists",
                    "team_sports.basketball.steals",
                    "team_sports.basketball.blocks",
                    "team_sports.basketball.turnovers",
                    "team_sports.basketball.fast_breaks",
                    "team_sports.basketball.second_chance",
                    "team_sports.basketball.time_of_possession",
                    "team_sports.basketball.pace",
                    "team_sports.american_football",
                    "team_sports.american_football.play_tracking",
                    "team_sports.american_football.player_tracking",
                    "team_sports.american_football.qb_metrics",
                    "team_sports.american_football.receiver_routes",
                    "team_sports.american_football.route_running",
                    "team_sports.american_football.coverage_defense",
                    "team_sports.american_football.blitz_pressure",
                    "team_sports.american_football.run_gap",
                    "team_sports.american_football.pass_rush",
                    "team_sports.american_football.rush_yards",
                    "team_sports.american_football.pass_yards",
                    "team_sports.american_football.tackles_missed",
                    "team_sports.american_football.separation",
                    "team_sports.american_football.targets",
                    "team_sports.american_football.receptions",
                    "team_sports.american_football.contested_catches",
                    "team_sports.american_football.drop_rate",
                    "team_sports.baseball",
                    "team_sports.baseball.bat_speed",
                    "team_sports.baseball.exit_velocity",
                    "team_sports.baseball.launch_angle",
                    "team_sports.baseball.spin_rate",
                    "team_sports.baseball.spin_axis",
                    "team_sports.baseball.horizontal_break",
                    "team_sports.baseball.vertical_break",
                    "team_sports.baseball.pitch_velocity",
                    "team_sports.baseball.pitch_movement",
                    "team_sports.baseball.release_point",
                    "team_sports.baseball.extension",
                    "team_sports.baseball.sprint_speed",
                    "team_sports.baseball.lead_distance",
                    "team_sports.baseball.pop_time",
                    "team_sports.hockey",
                    "team_sports.hockey.skating_speed",
                    "team_sports.hockey.skating_agility",
                    "team_sports.hockey.shot_velocity",
                    "team_sports.hockey.pass_accuracy",
                    "team_sports.hockey.ice_coverage",
                    "team_sports.hockey.faceoff_wins",
                    "team_sports.hockey.puck_battles",
                    "team_sports.hockey.cycle_play",
                    "team_sports.hockey.net_front",
                ],
                "count": 85,
            },
            "biomechanics": {
                "description": "Biomechanics fields for gait analysis, joint angles, ground reaction forces",
                "reference": "Biomechanics research, motion capture systems, force plate standards, gait labs",
                "fields": [
                    "biomechanics.gait_analysis",
                    "biomechanics.gait_cycle",
                    "biomechanics.gait_phase",
                    "biomechanics.stance_phase",
                    "biomechanics.swing_phase",
                    "biomechanics.double_support",
                    "biomechanics.single_support",
                    "biomechanics.step_length",
                    "biomechanics.step_width",
                    "biomechanics.cadence_gait",
                    "biomechanics.stance_time",
                    "biomechanics.swing_time",
                    "biomechanics.step_time",
                    "biomechanics.stride_time",
                    "biomechanics.velocity_gait",
                    "biomechanics.ground_reaction_force",
                    "biomechanics.grf_peak_vertical",
                    "biomechanics.grf_loading_rate",
                    "biomechanics.grf_braking",
                    "biomechanics.grf_propulsion",
                    "biomechanics.joint_angle_hip",
                    "biomechanics.joint_angle_knee",
                    "biomechanics.joint_angle_ankle",
                    "biomechanics.joint_angle_shoulder",
                    "biomechanics.joint_angle_elbow",
                    "biomechanics.joint_angle_wrist",
                    "biomechanics.joint_angle_spine",
                    "biomechanics.joint_angular_velocity",
                    "biomechanics.joint_moment_hip",
                    "biomechanics.joint_moment_knee",
                    "biomechanics.joint_moment_ankle",
                    "biomechanics.muscle_activation_emg",
                    "biomechanics.muscle_onset",
                    "biomechanics.muscle_peak",
                    "biomechanics.muscle_offset",
                    "biomechanics.muscle_duration",
                    "biomechanics.muscle_co_contraction",
                    "biomechanics.center_of_mass",
                    "biomechanics.center_of_pressure",
                    "biomechanics.cop_displacement",
                    "biomechanics.cop_velocity",
                    "biomechanics.stability_index",
                    "biomechanics.dynamic_balance",
                    "biomechanics.static_balance",
                    "biomechanics.postural_sway",
                    "biomechanics.landing_impact",
                    "biomechanics.impact_force",
                    "biomechanics.impact_absorption",
                    "biomechanics.mechanical_work",
                    "biomechanics.mechanical_power",
                    "biomechanics.kinetic_energy",
                    "biomechanics.potential_energy",
                    "biomechanics.segment_position",
                    "biomechanics.segment_velocity",
                    "biomechanics.segment_acceleration",
                    "biomechanics.body_rotation",
                    "biomechanics.angular_momentum",
                    "biomechanics.inertia_tensor",
                    "biomechanics.center_of_mass_velocity",
                    "biomechanics.braking_force",
                    "biomechanics.propulsive_force",
                    "biomechanics.leg_stiffness",
                    "biomechanics.vertical_stiffness",
                    "biomechanics.runnings_economy",
                    "biomechanics.oxygen_cost",
                    "biomechanics.metabolic_power",
                    "biomechanics.barefoot_pressure",
                    "biomechanics.pressure_distribution",
                    "biomechanics.heel_strike",
                    "biomechanics.toe_off",
                    "biomechanics.midstance",
                    "biomechanics.midswing",
                    "biomechanics.kinematic_chain",
                    "biomechanics.inter_segmental_coordination",
                    "biomechanics.phase_relationship",
                    "biomechanics.variance_ratio",
                    "biomechanics.consistency_index",
                ],
                "count": 85,
            },
            "sports_metadata": {
                "description": "Sports metadata fields for league standards, equipment, venue",
                "reference": "League data standards, sports governing bodies, equipment specifications, venue standards",
                "fields": [
                    "sports_metadata.league",
                    "sports_metadata.league_id",
                    "sports_metadata.season",
                    "sports_metadata.season_year",
                    "sports_metadata.season_phase",
                    "sports_metadata.regular_season",
                    "sports_metadata.playoffs",
                    "sports_metadata.finals",
                    "sports_metadata.conference",
                    "sports_metadata.division",
                    "sports_metadata.game_id",
                    "sports_metadata.game_date",
                    "sports_metadata.game_time",
                    "sports_metadata.game_day",
                    "sports_metadata.venue_name",
                    "sports_metadata.venue_location",
                    "sports_metadata.venue_city",
                    "sports_metadata.venue_state",
                    "sports_metadata.venue_country",
                    "sports_metadata.venue_capacity",
                    "sports_metadata.venue_surface",
                    "sports_metadata.venue_indoor_outdoor",
                    "sports_metadata.weather_conditions",
                    "sports_metadata.temperature",
                    "sports_metadata.humidity",
                    "sports_metadata.wind_speed",
                    "sports_metadata.wind_direction",
                    "sports_metadata.precipitation",
                    "sports_metadata.altitude",
                    "sports_metadata.equipment_type",
                    "sports_metadata.ball_type",
                    "sports_metadata.ball_brand",
                    "sports_metadata.ball_model",
                    "sports_metadata.ball_circumference",
                    "sports_metadata.ball_weight",
                    "sports_metadata.bat_type",
                    "sports_metadata.bat_material",
                    "sports_metadata.bat_length",
                    "sports_metadata.bat_weight",
                    "sports_metadata.racket_type",
                    "sports_metadata.racket_string_tension",
                    "sports_metadata.clothing_type",
                    "sports_metadata.footwear_type",
                    "sports_metadata.protective_gear",
                    "sports_metadata.helmet_type",
                    "sports_metadata.padding_type",
                    "sports_metadata.referee_id",
                    "sports_metadata.referee_name",
                    "sports_metadata.official_id",
                    "sports_metadata.commissioner",
                    "sports_metadata.team_management",
                    "sports_metadata.coach_id",
                    "sports_metadata.coach_name",
                    "sports_metadata.head_coach",
                    "sports_metadata.assistant_coach",
                    "sports_metadata.team_captain",
                    "sports_metadata.lineup_status",
                    "sports_metadata.injury_status",
                    "sports_metadata.suspension_status",
                    "sports_metadata.trade_status",
                    "sports_metadata.draft_status",
                    "sports_metadata.contract_type",
                    "sports_metadata.salary_cap",
                    "sports_metadata.player_salary",
                    "sports_metadata.sponsorship",
                    "sports_metadata.broadcast_network",
                    "sports_metadata.broadcast_stream",
                    "sports_metadata.attendance",
                    "sports_metadata.ticket_revenue",
                    "sports_metadata.merchandise_sales",
                    "sports_metadata.viewership",
                    "sports_metadata.social_engagement",
                    "sports_metadata.media_coverage",
                    "sports_metadata.data_provider",
                    "sports_metadata.tracking_system",
                    "sports_metadata.camera_system",
                    "sports_metadata.sensor_type",
                    "sports_metadata.sampling_rate_metadata",
                    "sports_metadata.data_quality",
                    "sports_metadata.data_validity",
                    "sports_metadata.calibration_status",
                    "sports_metadata.sync_timestamp",
                    "sports_metadata.time_zone",
                    "sports_metadata.utc_offset",
                ],
                "count": 90,
            },
            "betting_odds": {
                "description": "Betting and odds fields for Vegas lines, spreads, over/under, player props",
                "reference": "Sports betting APIs, Vegas lines, OddsJam, Action Network, DraftKings, FanDuel, MGM",
                "fields": [
                    "betting.spread",
                    "betting.spread_line",
                    "betting.spread_odds",
                    "betting.spread_closing",
                    "betting.spread_movement",
                    "betting.moneyline",
                    "betting.moneyline_home",
                    "betting.moneyline_away",
                    "betting.moneyline_draw",
                    "betting.moneyline_odds",
                    "betting.total_points",
                    "betting.over_under",
                    "betting.over_odds",
                    "betting.under_odds",
                    "betting.over_under_closing",
                    "betting.total_movement",
                    "betting.first_half_spread",
                    "betting.first_half_total",
                    "betting.first_quarter_spread",
                    "betting.first_quarter_total",
                    "betting.second_half_spread",
                    "betting.second_half_total",
                    "betting.team_totals",
                    "betting.home_team_total",
                    "betting.away_team_total",
                    "betting.alternate_spread",
                    "betting.alternate_total",
                    "betting.prop_bet",
                    "betting.player_props",
                    "betting.player_points",
                    "betting.player_rebounds",
                    "betting.player_assists",
                    "betting.player_threes",
                    "betting.player_steals",
                    "betting.player_blocks",
                    "betting.player_turnovers",
                    "betting.player_passes",
                    "betting.player_tackles",
                    "betting.player_interceptions",
                    "betting.player_sacks",
                    "betting.player_tds",
                    "betting.player_yards",
                    "betting.player_completions",
                    "betting.player_shots",
                    "betting.player_goals",
                    "betting.player_assists_sports",
                    "betting.player_shutouts",
                    "betting.player_kills",
                    "betting.player_aces",
                    "betting.player_blocks_sports",
                    "betting.player_digs",
                    "betting.player_goals_games",
                    "betting.player_points_odds",
                    "betting.player_rebounds_odds",
                    "betting.player_assists_odds",
                    "betting.live_betting",
                    "betting.in_game_odds",
                    "betting.period_betting",
                    "betting.innings_betting",
                    "betting.kitche_betting",
                    "betting.most_valuable_player_odds",
                    "betting.series_winner",
                    "betting.series_spread",
                    "betting.futures",
                    "betting.championship_odds",
                    "betting.conference_odds",
                    "betting.division_odds",
                    "betting.season_wins",
                    "betting.season_losses",
                    "betting.playoff_odds",
                    "betting.tournament_odds",
                    "betting.matchup_odds",
                    "betting.head_to_head",
                    "betting.margin_victory",
                    "betting.margin_victory_odds",
                    "betting.correct_score",
                    "betting.half_time_fulltime",
                    "betting.both_teams_score",
                    "betting.away_team_score",
                    "betting.home_team_score",
                    "betting.first_team_score",
                    "betting.last_team_score",
                    "betting.overtime",
                    "betting.overtime_yes_no",
                    "betting.shootout",
                    "betting.penalty_shootout",
                    "betting.bet_type",
                    "betting.bet_amount",
                    "betting.bet_odds",
                    "betting.payout",
                    "betting.profit",
                    "betting.bankroll",
                    "betting.bet_status",
                    "betting.settled",
                    "betting.pending",
                    "betting.void",
                    "betting.cashout",
                    "betting.cashout_value",
                    "betting.boosted_odds",
                    "betting.promotion",
                    "betting.free_bet",
                    "betting.risk_free_bet",
                    "betting.deposit_bonus",
                    "betting.odds_provider",
                    "betting.last_updated",
                    "betting.line_history",
                    "betting.steam_move",
                    "betting.reverse_line_movement",
                    "betting.line_shade",
                    "betting.public_betting",
                    "betting.percent_bets",
                    "betting.percent_money",
                    "betting.sharp_money",
                    "betting.sharp_bettors",
                    "betting.fade_public",
                    "betting.expected_value",
                    "betting.implied_probability",
                    "betting.closing_line_value",
                    "betting.roi",
                    "betting.yield",
                    "betting.roi_percent",
                ],
                "count": 120,
            },
        },
        "totals": {
            "categories": 7,
            "total_fields": 545,
        }
    }

    return INVENTORY


def main():
    print("=" * 70)
    print("SPORTS ANALYTICS/WEARABLE METADATA FIELD INVENTORY")
    print("=" * 70)
    print()

    inventory = generate_sports_inventory()

    print(f"Generated: {inventory['generated_at']}")
    print(f"Categories: {inventory['totals']['categories']}")
    print(f"Total Fields: {inventory['totals']['total_fields']}")
    print()

    print("FIELD COUNTS BY CATEGORY:")
    print("-" * 50)
    for cat_name, cat_data in sorted(inventory['categories'].items(), key=lambda x: x[1]['count'], reverse=True):
        print(f"  {cat_name:30s}: {cat_data['count']:>4} fields")

    output_dir = Path("dist/sports_inventory")
    output_dir.mkdir(parents=True, exist_ok=True)

    output_file = output_dir / "sports_inventory.json"
    output_file.write_text(json.dumps(inventory, indent=2, sort_keys=True), encoding="utf-8")
    print()
    print(f"Wrote: {output_file}")

    summary = {
        "generated_at": inventory["generated_at"],
        "source": inventory["source"],
        "description": inventory["description"],
        "categories": {
            k: {
                "count": v["count"],
                "description": v["description"],
                "reference": v.get("reference", "N/A")
            }
            for k, v in inventory["categories"].items()
        },
        "totals": inventory["totals"],
    }

    summary_file = output_dir / "sports_summary.json"
    summary_file.write_text(json.dumps(summary, indent=2, sort_keys=True), encoding="utf-8")
    print(f"Wrote: {summary_file}")


if __name__ == "__main__":
    main()
