#!/usr/bin/env python3
"""Radar and Remote Sensing Metadata Field Inventory for MetaExtract.

Covers NEXRAD weather radar, LIDAR point clouds, SAR, WMO BUFR, ODIM/H5,
and aviation weather formats.
"""

from datetime import datetime, timezone
from pathlib import Path


def generate_radar_inventory():
    """Generate comprehensive radar and remote sensing metadata field inventory."""

    INVENTORY = {
        "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "source": "NEXRAD Level II/III, ASR, LAS/LAZ, WMO BUFR, ODIM/H5, METAR/TAF, ICAO",
        "description": "Radar and remote sensing metadata fields for weather radar, LIDAR, SAR, and aviation weather data",
        "categories": {
            "nexrad_weather_radar": {
                "description": "NEXRAD Level II and Level III weather radar data fields",
                "reference": "NEXRAD ICD, RDA RPG ICD, WMO OPM",
                "fields": [
                    "nexrad.radar_id",
                    "nexrad.radar_name",
                    "nexrad.wmo_id",
                    "nexrad.icao_id",
                    "nexrad.latitude",
                    "nexrad.longitude",
                    "nexrad.elevation",
                    "nexrad.scan_time",
                    "nexrad.scan_time.start",
                    "nexrad.scan_time.end",
                    "nexrad.scan_date",
                    "nexrad.scan_mode",
                    "nexrad.scan_strategy",
                    "nexrad.scan_elevation",
                    "nexrad.scan_azimuth",
                    "nexrad.scan_prf",
                    "nexrad.scan_pulse_count",
                    "nexrad.scan_pulse_width",
                    "nexrad.scan_wavelength",
                    "nexrad.scan_frequency",
                    "nexrad.scan_beam_width",
                    "nexrad.scan_gain",
                    "nexrad.scan_antenna_speed",
                    "nexrad.reflectivity",
                    "nexrad.reflectivity.dbz",
                    "nexrad.reflectivity.z_max",
                    "nexrad.reflectivity.z_min",
                    "nexrad.reflectivity.z_avg",
                    "nexrad.reflectivity.quality",
                    "nexrad.reflectivity.threshold",
                    "nexrad.reflectivity.unbiased",
                    "nexrad.reflectivity.corrected",
                    "nexrad.reflectivity.product",
                    "nexrad.velocity",
                    "nexrad.velocity.doppler",
                    "nexrad.velocity.v_mean",
                    "nexrad.velocity.v_max",
                    "nexrad.velocity.v_min",
                    "nexrad.velocity.v_std",
                    "nexrad.velocity.shear",
                    "nexrad.velocity.quality",
                    "nexrad.velocity.corrected",
                    "nexrad.velocity.alias",
                    "nexrad.spectrum_width",
                    "nexrad.spectrum_width.sw_max",
                    "nexrad.spectrum_width.sw_min",
                    "nexrad.spectrum_width.sw_avg",
                    "nexrad.spectrum_width.quality",
                    "nexrad.differential_reflectivity",
                    "nexrad.differential_reflectivity.zdr",
                    "nexrad.differential_reflectivity.zdr_max",
                    "nexrad.differential_reflectivity.zdr_min",
                    "nexrad.differential_reflectivity.zdr_avg",
                    "nexrad.differential_reflectivity.zdr_std",
                    "nexrad.differential_reflectivity.quality",
                    "nexrad.differential_phase",
                    "nexrad.differential_phase.phi_dp",
                    "nexrad.differential_phase.kdp",
                    "nexrad.differential_phase.kdp_max",
                    "nexrad.differential_phase.kdp_min",
                    "nexrad.differential_phase.kdp_avg",
                    "nexrad.differential_phase.quality",
                    "nexrad.cross_correlation",
                    "nexrad.cross_correlation.rho_hv",
                    "nexrad.cross_correlation.rho_hv_max",
                    "nexrad.cross_correlation.rho_hv_min",
                    "nexrad.cross_correlation.rho_hv_avg",
                    "nexrad.cross_correlation.quality",
                    "nexrad.rainfall_rate",
                    "nexrad.rainfall_rate.rr",
                    "nexrad.rainfall_rate.rr_max",
                    "nexrad.rainfall_rate.zr_relation",
                    "nexrad.rainfall_rate.zr_a",
                    "nexrad.rainfall_rate.zr_b",
                    "nexrad.hydrometeor_type",
                    "nexrad.hydrometeor_type.h_class",
                    "nexrad.hydrometeor_type.probability",
                    "nexrad.hail_detection",
                    "nexrad.hail_detection.posh",
                    "nexrad.hail_detection.mesh",
                    "nexrad.hail_detection.phi",
                    "nexrad.mesocyclone",
                    "nexrad.mesocyclone.id",
                    "nexrad.mesocyclone.location",
                    "nexrad.mesocyclone.base",
                    "nexrad.mesocyclone.top",
                    "nexrad.mesocyclone.rotation",
                    "nexrad.tornado_vortex_signature",
                    "nexrad.tvs.id",
                    "nexrad.tvs.location",
                    "nexrad.tvs.shear",
                    "nexrad.tvs.omega",
                    "nexrad.storm_tracking",
                    "nexrad.storm_tracking.id",
                    "nexrad.storm_tracking.position",
                    "nexrad.storm_tracking.velocity",
                    "nexrad.storm_tracking.area",
                    "nexrad.storm_tracking.vil",
                    "nexrad.storm_tracking.max_reflectivity",
                    "nexrad.storm_tracking.hail_prob",
                    "nexrad.vel_acceleration",
                    "nexrad.vel_acceleration.val",
                    "nexrad.vel_acceleration.shear",
                    "nexrad.alias_velocity",
                    "nexrad.nyquist_velocity",
                    "nexrad.unambiguous_range",
                    "nexrad.unambiguous_velocity",
                    "nexrad.target_identification",
                    "nexrad.status",
                    "nexrad.status.rda_status",
                    "nexrad.status.rpg_status",
                    "nexrad.status.rda_health",
                    "nexrad.vcp",
                    "nexrad.vcp_number",
                    "nexrad.vcp_description",
                    "nexrad.data_type",
                    "nexrad.data_type.level2",
                    "nexrad.data_type.level3",
                    "nexrad.data_type.archive3",
                ],
                "count": 120,
            },
            "lidar_point_clouds": {
                "description": "LIDAR point cloud format fields (LAS/LAZ)",
                "reference": "ASPRS LAS Specification 1.4, LAZ compression",
                "fields": [
                    "lidar.file_source_id",
                    "lidar.global_encoding",
                    "lidar.project_id",
                    "lidar.version_major",
                    "lidar.version_minor",
                    "lidar.system_identifier",
                    "lidar.generating_software",
                    "lidar.file_creation_date",
                    "lidar.year",
                    "lidar.header_size",
                    "lidar.offset_to_point_data",
                    "lidar.num_variable_length_records",
                    "lidar.point_data_format",
                    "lidar.point_data_record_length",
                    "lidar.num_point_records",
                    "lidar.num_points_by_return",
                    "lidar.return_number",
                    "lidar.return_count",
                    "lidar.number_of_returns",
                    "lidar.x",
                    "lidar.y",
                    "lidar.z",
                    "lidar.intensity",
                    "lidar.raw_time",
                    "lidar.scan_angle",
                    "lidar.scan_direction",
                    "lidar.edge_flight_line",
                    "lidar.classification",
                    "lidar.classification.ground",
                    "lidar.classification.low_vegetation",
                    "lidar.classification.medium_vegetation",
                    "lidar.classification.high_vegetation",
                    "lidar.classification.building",
                    "lidar.classification.low_point",
                    "lidar.classification.reserved",
                    "lidar.classification.water",
                    "lidar.classification.rail",
                    "lidar.classification.road_surface",
                    "lidar.classification.reserved2",
                    "lidar.classification.wire_guard",
                    "lidar.classification.wire_conductor",
                    "lidar.classification.transmission_tower",
                    "lidar.classification.wire_connector",
                    "lidar.classification.bridge_deck",
                    "lidar.classification.high_noise",
                    "lidar.classification.overlap",
                    "lidar.user_data",
                    "lidar.point_source_id",
                    "lidar.gps_time",
                    "lidar.red",
                    "lidar.green",
                    "lidar.blue",
                    "lidar.nir",
                    "lidar.wave_packet",
                    "lidar.wave_packet.descriptor_index",
                    "lidar.wave_packet.byte_offset",
                    "lidar.wave_packet.packet_size",
                    "lidar.wave_packet.returns",
                    "lidar.wave_packet.t",
                    "lidar.wave_packet.x",
                    "lidar.wave_packet.y",
                    "lidar.wave_packet.z",
                    "lidar.scan_channel",
                    "lidar.overlap",
                    "lidar.scanner_channel",
                    "lidar.classification_flags",
                    "lidar.classification_flags.synthetic",
                    "lidar.classification_flags.keypoint",
                    "lidar.classification_flags.withheld",
                    "lidar.classification_flags.overlap",
                    "lidar.extended_returns",
                    "lidar.num_returns",
                    "lidar.return_number_ext",
                    "lidar.classification_ext",
                    "lidar.scan_angle_ext",
                    "lidar.laz_compressed",
                    "lidar.laz_version_major",
                    "lidar.laz_version_minor",
                    "lidar.laz_point_format",
                    "lidar.laz_chunk_size",
                    "lidar.laz.num_chunks",
                    "lidar.laz.compressed_size",
                    "lidar.laz.uncompressed_size",
                    "lidar.laz.compression_ratio",
                    "lidar.ground_elevation",
                    "lidar.min_elevation",
                    "lidar.max_elevation",
                    "lidar.bounding_box",
                    "lidar.bounding_box.min_x",
                    "lidar.bounding_box.min_y",
                    "lidar.bounding_box.min_z",
                    "lidar.bounding_box.max_x",
                    "lidar.bounding_box.max_y",
                    "lidar.bounding_box.max_z",
                    "lidar.spatial_reference",
                    "lidar.utm_zone",
                    "lidar.coordinate_system",
                    "lidar.datum",
                    "lidar.vertical_datum",
                    "lidar.horizontal_resolution",
                    "lidar.vertical_resolution",
                    "lidar.geoid_model",
                    "lidar.ellipsoid_model",
                    "lidar.wavelength",
                    "lidar.pulse_energy",
                    "lidar.pulse_duration",
                    "lidar.beam_divergence",
                    "lidar.scan_rate",
                    "lidar.scan_pattern",
                    "lidar.scan_pattern.parallel",
                    "lidar.scan_pattern.zigzag",
                    "lidar.scan_pattern.palm",
                    "lidar.scan_pattern.oscillating",
                ],
                "count": 110,
            },
            "sar_remote_sensing": {
                "description": "Synthetic Aperture Radar (SAR) remote sensing metadata",
                "reference": "CEOS SAR规格, Sentinel-1, RADARSAT, TerraSAR-X",
                "fields": [
                    "sar.product_id",
                    "sar.product_type",
                    "sar.processing_level",
                    "sar.satellite_name",
                    "sar.sensor_name",
                    "sar.acquisition_time",
                    "sar.acquisition_start",
                    "sar.acquisition_stop",
                    "sar.orbit_number",
                    "sar.orbit_direction",
                    "sar.orbit_state_vector",
                    "sar.position",
                    "sar.velocity",
                    "sar.attitude",
                    "sar.roll",
                    "sar.pitch",
                    "sar.yaw",
                    "sar.look_direction",
                    "sar.look_side",
                    "sar.incidence_angle",
                    "sar.incidence_angle_center",
                    "sar.incidence_angle_near",
                    "sar.incidence_angle_far",
                    "sar.incidence_angle_min",
                    "sar.incidence_angle_max",
                    "sar.acquisition_mode",
                    "sar.beam_id",
                    "sar.swath_id",
                    "sar.polarisation",
                    "sar.polarisation.transmit",
                    "sar.polarisation.receive",
                    "sar.polarisation.channels",
                    "sar.polarisation.hh",
                    "sar.polarisation.hv",
                    "sar.polarisation.vh",
                    "sar.polarisation.vv",
                    "sar.doppler_centroid",
                    "sar.doppler_rate",
                    "sar.doppler_frequency",
                    "sar.range_resolution",
                    "sar.azimuth_resolution",
                    "sar.ground_range_resolution",
                    "sar.spatial_resolution",
                    "sar.pixel_spacing",
                    "sar.pixel_spacing.range",
                    "sar.pixel_spacing.azimuth",
                    "sar.sampling_frequency",
                    "sar.pulse_repetition_frequency",
                    "sar.pulse_duration",
                    "sar.bandwidth",
                    "sar.chirp_slope",
                    "sar.wavelength",
                    "sar.frequency",
                    "sar.noise_equivalent_sigma0",
                    "sar.nesz",
                    "sar.sigma0",
                    "sar.sigma0_scale",
                    "sar.beta0",
                    "sar.beta0_scale",
                    "sar.gamma0",
                    "sar.gamma0_scale",
                    "sar.calibration_constant",
                    "sar.calibration_factor",
                    "sar.radiometric_calibration",
                    "sar.radiometric_terrain_correction",
                    "sar.speckle_filter",
                    "sar.speckle_filter.type",
                    "sar.speckle_filter.window",
                    "sar.multi_look",
                    "sar.multi_look.range",
                    "sar.multi_look.azimuth",
                    "sar.range_looks",
                    "sar.azimuth_looks",
                    "sar.baseline",
                    "sar.baseline.perpendicular",
                    "sar.baseline.parallel",
                    "sar.baseline.temporal",
                    "sar.interferogram",
                    "sar.interferogram.coherence",
                    "sar.interferogram.phase",
                    "sar.interferogram.unwrapped_phase",
                    "sar.dem_name",
                    "sar.dem_version",
                    "sar.dem_resampling",
                    "sar.dem_ellipsoid",
                    "sar.geoid_model",
                    "sar.orthorectification",
                    "sar.terrain_correction",
                    "sar.earth_radius",
                    "sar.earth_radius_nadir",
                    "sar.slant_range",
                    "sar.ground_range",
                    "sar.zero_doppler_time",
                    "sar.zero_doppler_time_start",
                    "sar.zero_doppler_time_stop",
                    "sar.azimuth_time_start",
                    "sar.azimuth_time_stop",
                    "sar.line_time_interval",
                    "sar.number_of_lines",
                    "sar.number_of_samples",
                    "sar.sample_type",
                    "sar.bit_depth",
                    "sar.data_type",
                    "sar.compression",
                    "sar.compression.type",
                    "sar.compression.ratio",
                    "sar.noise_correction",
                    "sar.gain_correction",
                    "sar.amplitude",
                    "sar.phase",
                    "sar.real",
                    "sar.imaginary",
                    "sar.footprint",
                    "sar.footprint.corner",
                    "sar.bounds",
                    "sar.center",
                    "sar.total_size",
                    "sar.product_size",
                    "sar.manifest_size",
                    "sar.checksum",
                    "sar.checksum.algorithm",
                ],
                "count": 130,
            },
            "wmo_bufr": {
                "description": "WMO Binary Universal Form for Representation (BUFR) meteorological data",
                "reference": "WMO BUFR Edition 4, FM 94 BUFR",
                "fields": [
                    "bufr.master_table",
                    "bufr.originating_centre",
                    "bufr.originating_sub_centre",
                    "bufr.update_sequence_number",
                    "bufr.optional_section",
                    "bufr.data_category",
                    "bufr.data_sub_category",
                    "bufr.master_table_version",
                    "bufr.local_table_version",
                    "bufr.typical_year",
                    "bufr.typical_month",
                    "bufr.typical_day",
                    "bufr.typical_hour",
                    "bufr.typical_minute",
                    "bufr.typical_second",
                    "bufr.number_of_subsets",
                    "bufr.flags",
                    "bufr.compressed",
                    "bufr.descriptor_count",
                    "bufr.temperature",
                    "bufr.temperature.air",
                    "bufr.temperature.dewpoint",
                    "bufr.temperature.wet_bulb",
                    "bufr.temperature.virtual",
                    "bufr.temperature.potential",
                    "bufr.temperature.equivalent_potential",
                    "bufr.temperature.soil",
                    "bufr.pressure",
                    "bufr.pressure.station",
                    "bufr.pressure.sea_level",
                    "bufr.pressure.3hour_change",
                    "bufr.pressure.24hour_change",
                    "bufr.pressure.tendency",
                    "bufr.wind",
                    "bufr.wind.direction",
                    "bufr.wind.speed",
                    "bufr.wind.gust",
                    "bufr.wind.u_component",
                    "bufr.wind.v_component",
                    "bufr.wind.speed_10m",
                    "bufr.wind.direction_10m",
                    "bufr.humidity",
                    "bufr.humidity.relative",
                    "bufr.humidity.specific",
                    "bufr.humidity.mixing_ratio",
                    "bufr.humidity.precipitable",
                    "bufr.visibility",
                    "bufr.visibility.horizontal",
                    "bufr.visibility.vertical",
                    "bufr.visibility.slant",
                    "bufr.clouds",
                    "bufr.clouds.amount",
                    "bufr.clouds.type",
                    "bufr.clouds.base_height",
                    "bufr.clouds.top_height",
                    "bufr.clouds.conv_type",
                    "bufr.clouds.low",
                    "bufr.clouds.middle",
                    "bufr.clouds.high",
                    "bufr.precipitation",
                    "bufr.precipitation.amount",
                    "bufr.precipitation.rate",
                    "bufr.precipitation.duration",
                    "bufr.precipitation.gauge_type",
                    "bufr.precipitation.quality",
                    "bufr.radiation",
                    "bufr.radiation.global",
                    "bufr.radiation.direct",
                    "bufr.radiation.diffuse",
                    "bufr.radiation.longwave",
                    "bufr.radiation.net",
                    "bufr.radiation.uv",
                    "bufr.radiation.uvb",
                    "bufr.radiation.albedo",
                    "bufr.evaporation",
                    "bufr.evaporation.amount",
                    "bufr.evaporation.pan",
                    "bufr.evaporation.type",
                    "bufr.soil",
                    "bufr.soil.temperature",
                    "bufr.soil.moisture",
                    "bufr.soil.type",
                    "bufr.soil.heat_flux",
                    "bufr.state",
                    "bufr.state.weather",
                    "bufr.state.present",
                    "bufr.state.past",
                    "bufr.state.significant",
                    "bufr.station",
                    "bufr.station.id",
                    "bufr.station.name",
                    "bufr.station.type",
                    "bufr.station.latitude",
                    "bufr.station.longitude",
                    "bufr.station.elevation",
                    "bufr.station.land_use",
                    "bufr.station.timezone",
                    "bufr.time",
                    "bufr.time.observation",
                    "bufr.time.report",
                    "bufr.time.valid",
                    "bufr.time.elapsed",
                ],
                "count": 100,
            },
            "odim_h5": {
                "description": "ODIM (OPERA Data Model) HDF5 radar data format",
                "reference": "OPERA ODIM 3.0, HDF5 radar",
                "fields": [
                    "odim.version",
                    "odim.object",
                    "odim.source",
                    "odime.what",
                    "odime.object",
                    "odime.version",
                    "odime.date",
                    "odime.time",
                    "odime.quantity",
                    "odime.unit",
                    "odime.gain",
                    "odime.offset",
                    "odime.nodata",
                    "odime.undetect",
                    "odim.where",
                    "odim.where.latitude",
                    "odim.where.longitude",
                    "odim.where.height",
                    "odim.where.maxrange",
                    "odim.where.minrange",
                    "odim.where.a1gate",
                    "odim.how",
                    "odim.how.system",
                    "odim.how.software",
                    "odim.how.hostname",
                    "odim.how.scan_number",
                    "odim.how.scan_rate",
                    "odim.how.prf",
                    "odim.how.frequency",
                    "odim.how.wavelength",
                    "odim.how.beam_width",
                    "odim.how.pulse_width",
                    "odim.how.gain",
                    "odim.how.antenna_speed",
                    "odim.how.azimuth",
                    "odim.how.elevation",
                    "odim.how.nyquist_velocity",
                    "odim.how.unambiguous_range",
                    "odim.how.snr_threshold",
                    "odim.how.clutter_filter",
                    "odim.how.polarization",
                    "odim.how.transmit_pulse",
                    "odim.how.receiver_gain",
                    "odim.how.receiver_slope",
                    "odim.how.receiver_offset",
                    "odim.how.radome_loss",
                    "odim.how.radome_type",
                    "odim.how.radar_constant",
                    "odim.how.dynamic_range",
                    "odim.how.sample_range",
                    "odim.how.sample_interval",
                    "odim.how.pulse_count",
                    "odim.how.integrated_samples",
                    "odim.how.azimuth_correction",
                    "odim.how.elevation_correction",
                    "odim.how.range_correction",
                    "odim.how.time_correction",
                    "odim.how.phidp_correction",
                    "odim.how.rho_hv_correction",
                    "odim.how.calibration_date",
                    "odim.hoy",
                    "odim.hoy.task_name",
                    "odim.hoy.task_mode",
                    "odim.hoy.scan_type",
                    "odim.hoy.scan_strategy",
                    "odim.hoy.start_angle",
                    "odim.hoy.stop_angle",
                    "odim.hoy.step_angle",
                    "odim.hoy.nrays",
                    "odim.hoy.nbins",
                    "odim.hoy.start_range",
                    "odim.hoy.range_step",
                    "odim.product",
                    "odim.product.type",
                    "odim.product.name",
                    "odim.product.unit",
                    "odim.product.gain",
                    "odim.product.offset",
                    "odim.product.nodata",
                    "odim.product.undetect",
                    "odim.dataset",
                    "odim.dataset.n1",
                    "odim.dataset.n2",
                    "odim.dataset.startdate",
                    "odim.dataset.starttime",
                    "odim.dataset.enddate",
                    "odim.dataset.endtime",
                    "odim.dataset.data",
                ],
                "count": 90,
            },
            "aviation_weather": {
                "description": "Aviation weather report fields (METAR, TAF, AIRMET, SIGMET)",
                "reference": "ICAO Annex 3, WMO FM 94 BUFR, METAR/TAF codes",
                "fields": [
                    "metar.station_id",
                    "metar.station_name",
                    "metar.latitude",
                    "metar.longitude",
                    "metar.elevation",
                    "metar.report_type",
                    "metar.auto",
                    "metar.auto_station",
                    "metar.cor",
                    "metar.observation_time",
                    "metar.observation_time.day",
                    "metar.observation_time.hour",
                    "metar.observation_time.minute",
                    "metar.wind_speed",
                    "metar.wind_direction",
                    "metar.wind_gust",
                    "metar.wind_variable_direction",
                    "metar.wind_variable_direction_from",
                    "metar.wind_variable_direction_to",
                    "metar.wind_unit",
                    "metar.visibility",
                    "metar.visibility.horizontal",
                    "metar.visibility.horizontal_min",
                    "metar.visibility.horizontal_max",
                    "metar.visibility.vertical",
                    "metar.visibility.direction",
                    "metar.visibility.runway",
                    "metar.visibility.runway.visual_range",
                    "metar.visibility.runway.designator",
                    "metar.weather",
                    "metar.weather.intensity",
                    "metar.weather.phenomena",
                    "metar.weather.descriptor",
                    "metar.weather.vicinity",
                    "metar.ceiling",
                    "metar.ceiling.height",
                    "metar.ceiling.alternate",
                    "metar.cloud",
                    "metar.cloud.amount",
                    "metar.cloud.type",
                    "metar.cloud.height",
                    "metar.cloud.convective",
                    "metar.temperature",
                    "metar.temperature.air",
                    "metar.temperature.dewpoint",
                    "metar.temperature.relative_humidity",
                    "metar.pressure",
                    "metar.pressure.qnh",
                    "metar.pressure.qfe",
                    "metar.pressure.inhg",
                    "metar.pressure.tendency",
                    "metar.wx_codes",
                    "metar.wx_codes.current",
                    "metar.wx_codes.past",
                    "metar.wx_codes.recent",
                    "metar.visibility_trend",
                    "metar.visibility_trend.nosig",
                    "metar.visibility_trend.change",
                    "metar.visibility_trend.from",
                    "metar.visibility_trend.to",
                    "metar.runway_state",
                    "metar.runway_state.designator",
                    "metar.runway_state.condition",
                    "metar.runway_state.contamination",
                    "metar.runway_state.depth",
                    "metar.runway_state.friction",
                    "taf.station_id",
                    "taf.issue_time",
                    "taf.valid_time_start",
                    "taf.valid_time_end",
                    "taf.amendment",
                    "taf.correction",
                    "taf.automated",
                    "taf.wind",
                    "taf.wind.speed",
                    "taf.wind.direction",
                    "taf.wind.gust",
                    "taf.wind.unit",
                    "taf.wind.variable",
                    "taf.visibility",
                    "taf.visibility.main",
                    "taf.visibility.min",
                    "taf.visibility.max",
                    "taf.weather",
                    "taf.weather.intensity",
                    "taf.weather.phenomena",
                    "taf.weather.descriptor",
                    "taf.clouds",
                    "taf.clouds.base",
                    "taf.clouds.amount",
                    "taf.clouds.type",
                    "taf.clouds.vertical",
                    "taf.temperature",
                    "taf.temperature.max",
                    "taf.temperature.min",
                    "taf.temperature.probability",
                    "taf.change_indicator",
                    "taf.change_indicator.fm",
                    "taf.change_indicator.becmg",
                    "taf.change_indicator.tempo",
                    "taf.change_indicator.prob",
                    "taf.probability",
                    "airmet.sigmet",
                    "airmet.phenomenon",
                    "airmet.severity",
                    "airmet.observation_time",
                    "airmet.forecast_time",
                    "airmet.altitude",
                    "airmet.altitude.min_ft",
                    "airmet.altitude.max_ft",
                    "airmet.movement",
                    "airmet.movement.direction",
                    "airmet.movement.speed",
                    "airmet.intensity_change",
                    "airmet.area",
                    "airmet.area.description",
                ],
                "count": 100,
            },
        },
        "totals": {
            "categories": 6,
            "total_fields": 650,
        }
    }

    return INVENTORY


def main():
    print("=" * 70)
    print("RADAR AND REMOTE SENSING METADATA FIELD INVENTORY")
    print("=" * 70)
    print()

    inventory = generate_radar_inventory()

    print(f"Generated: {inventory['generated_at']}")
    print(f"Categories: {inventory['totals']['categories']}")
    print(f"Total Fields: {inventory['totals']['total_fields']:,}")
    print()

    print("FIELD COUNTS BY CATEGORY:")
    print("-" * 50)
    for cat_name, cat_data in sorted(inventory['categories'].items(), key=lambda x: x[1]['count'], reverse=True):
        ref = cat_data.get('reference', '')[:40]
        print(f"  {cat_name:30s}: {cat_data['count']:>4}  [{ref}]")

    output_dir = Path("dist/radar_inventory")
    output_dir.mkdir(parents=True, exist_ok=True)

    output_file = output_dir / "radar_inventory.json"
    import json
    output_file.write_text(json.dumps(inventory, indent=2, sort_keys=True), encoding="utf-8")
    print()
    print(f"Wrote: {output_file}")

    summary = {
        "generated_at": inventory["generated_at"],
        "source": inventory["source"],
        "description": inventory["description"],
        "totals": inventory["totals"],
        "field_counts_by_category": {}
    }

    for cat_name, cat_data in inventory["categories"].items():
        summary["field_counts_by_category"][cat_name] = {
            "description": cat_data["description"],
            "count": cat_data["count"],
            "reference": cat_data.get("reference", "N/A")
        }

    summary_file = output_dir / "radar_summary.json"
    summary_file.write_text(json.dumps(summary, indent=2), encoding="utf-8")
    print(f"Wrote: {summary_file}")


if __name__ == "__main__":
    main()
