#!/usr/bin/env python3
"""Forensic Format Metadata Fields Inventory

This script documents metadata fields available in forensic disk image formats
including E01, raw images (dd), AFF, and other digital forensics formats.

Reference:
- ENCASE EWF format specification
- AFF4 standard
- Digital Forensics XML (DFXML)
- libewf documentation
"""

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List, Any


FORENSIC_INVENTORY = {
    "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
    "source": "EWF/EnCase, AFF4, DFXML, libewf",
    "description": "Forensic disk image and evidence metadata fields",
    "categories": {
        "ewf_encase": {
            "description": "EnCase EWF format metadata fields",
            "fields": [
                "case_number", "evidence_number", "unique_evidence_number",
                "examiners_name", "organization", "date_acquired", "time_acquired",
                "system_date", "system_timezone", "acquisition_date", "acquisition_time",
                "acquisition_duration", "tool_name", "tool_version", "tool_build",
                "command_line", "media_type", "media_size", "media_sector_size",
                "media_bytes_per_sector", "media_hash", "md5_hash", "sha1_hash",
                "sha256_hash", "description", "compression_method", "compression_level",
                "encryption_method", "encrypted", "password_protected", "integral_hash",
                "volume_information", "file_system_information", "partition_information",
                "sector_count", "bytes_per_sector", "checksum", "signature",
                "header_hash", "table_hash", "footer_hash", "metadata_version",
                "creator_version", "creator_os", "creator_os_version", "platform_ewf",
                "process_identifier", "reference", "acquisition_source",
                "hash", "extent_information", "source_path", "source_type",
                "read_error_policy", "read_error_limit", "read_error_file",
                "read_error_offset", "read_error_size", "read_error_description",
                "libewf_version", "libewf_build", "libewf_date", "libewf_marker",
                "compression_values", "delta_chunk", "sectors_per_chunk",
                "chunk_count", "sector_error_count", "byte_error_count",
                "stored_md5", "calculated_md5", "stored_sha1", "calculated_sha1",
                "stored_sha256", "calculated_sha256", "stored_sha512", "calculated_sha512",
                "xhash", "ssdeep", "tlsh", "bloom_filter_hash", "hash_value",
                "hash_algorithm", "hash_status", "hash_mask", "hash_value_length",
                "segment_number", "segment_file", "segment_count", "segment_size",
                "segment_minimum_size", "segment_maximum_size", "segment_extension",
                "filename", "file_size", "file_reference", "directory_entry",
                "alternate_data_stream", "resident_metadata", "non_resident_metadata",
                "file_attribute", "file_flags", "file_creation_time", "file_access_time",
                "file_modification_time", "file_size", "file_reference_number",
                "sequence_number", "record_type", "record_length", "record_data",
            ],
            "count": 102,
            "reference": "libewf/EnCase EWF Specification"
        },
        "aff4_standards": {
            "description": "AFF4 (Advanced Forensic Format) metadata",
            "fields": [
                "aff4:Version", "aff4:Created", "aff4:Modified", "aff4:Device",
                "aff4:DeviceHost", "aff4:DeviceModel", "aff4:DeviceSerial",
                "aff4:AcquisitionTime", "aff4:AcquisitionDevice", "aff4:AcquisitionSoftware",
                "aff4:AcquisitionCommand", "aff4:Presservation", "aff4:Integrity",
                "aff4:Hash", "aff4:HashMethod", "aff4:HashValue", "aff4:Size",
                "aff4:ChunkSize", "aff4:ChunkCount", "aff4:CompressionMethod",
                "aff4:EncryptionMethod", "aff4:EncryptionKey", "aff4:SegmentNumber",
                "aff4:TotalSegments", "aff4:ImageSize", "aff4:SectorsPerChunk",
                "aff4:BlockSize", "aff4:BlockCount", "aff4:BlockHash",
                "aff4:ImageHash", "aff4:ImageHashMethod", "aff4:Thumbnail",
                "aff4:Timeline", "aff4:DirectoryEntry", "aff4:FileEntry",
                "aff4:SlackSpace", "aff4:Unallocated", "aff4:NTFSVolume",
                "aff4:NTFSBitmap", "aff4:FATBitmap", "aff4:Ext3Bitmap",
                "aff4:CarvedFile", "aff4:ExtractedFile", "aff4:RegistryHive",
                "aff4:RegistryKey", "aff4:RegistryValue", "aff4:EventLog",
                "aff4:EventRecord", "aff4:WebHistory", "aff4:Cookie",
                "aff4:DownloadHistory", "aff4:BrowserExtension", "aff4:Password",
                "aff4:Certificate", "aff4:PrivateKey", "aff4:Key", "aff4:IV",
                "aff4:Salt", "aff4:Iterations", "aff4:KeyDerivationFunction",
                "aff4:EncryptionScheme", "aff4:CompressionScheme", "aff4:Checksum",
                "aff4:Algorithm", "aff4:Length", "aff4:Offset", "aff4:Data",
                "aff4:Reference", "aff4:Manifest", "aff4:Stream", "aff4:Map",
                "aff4:String", "aff4:Integer", "aff4:UUID", "aff4:Binary",
                "aff4:Expanded", "aff4:Compressed", "aff4:Encrypted", "aff4:Stored",
                "aff4:TimelineEntry", "aff4:DataStream", "aff4:Alias", "aff4:SymbolicLink",
                "aff4:HardLink", "aff4:DeviceNode", "aff4:FileSystemObject",
                "aff4:MemoryObject", "aff4:RegistryObject", "aff4:NetworkObject",
                "aff4:ProcessObject", "aff4:ThreadObject", "aff4:HandleObject",
                "aff4:ModuleObject", "aff4:CodeSection", "aff4:StackFrame",
                "aff4:ThreadLocalStorage", "aff4:EnvironmentVariable", "aff4:Argument",
                "aff4:CurrentDirectory", "aff4:HandleTable", "aff4:PEB", "aff4:TEB",
                "aff4:EPROCESS", "aff4:KPROCESS", "aff4:ETHREAD", "aff4:PEHeader",
                "aff4:SectionHeader", "aff4:ImportTable", "aff4:ExportTable",
                "aff4:ResourceTable", "aff4:RelocationTable", "aff4:DebugDirectory",
                "aff4:CertificateTable", "aff4:BoundImportTable", "aff4:IAT",
                "aff4:DelayImportDescriptor", "aff4:COMDescriptor",
            ],
            "count": 100,
            "reference": "AFF4 Standard 1.0"
        },
        "dfxml_digital_forensics": {
            "description": "Digital Forensics XML (DFXML) elements",
            "fields": [
                "dfxml", "creator", "created", "version", "dftime", "timezone",
                "process", "pid", "exec_time", "command", "parent", "sibling",
                "index", "hashtag", "fileobject", "filename", "filesize", "alloc",
                "alloc_size", "used", "inode", "nlink", "uid", "gid", "mode",
                "mtime", "atime", "ctime", "crtime", "bkup_time", "flags",
                "gen", "originator", "parent_object", "name_type", "symlink_target",
                "link_target", "byte_runs", "byte_run", "offset", "fs_offset",
                "start", "length", "img_offset", "file_offset", "mem_offset",
                "runlist", "volume_object", "block_size", "block_count",
                "block_hash", "first_block", "last_block", "free_space",
                "allocated", "total_blocks", "free_blocks", "inuse_blocks",
                "partition_offset", "ftype", "fstate", "alloc_change",
                "libmagic", "type", "hashdigest", "md5", "sha1", "sha256",
                "sha384", "sha512", "ssdeep", "tlsh", "phash", "virustotal",
                "malware_score", "malware_name", "malware_family", "malware_cve",
                "yara_rule", "yara_match", "suricata_rule", "suricata_match",
                "error", "warning", "note", "text", "data_content", "data_offset",
                "data_length", "encoding", "interpretation", "category",
                "attribute", "element", "comment", "metadata", "configuration",
                "extract", "carved", "extracted", "exported", "imported",
                "deleted", "orphan", "slack", "unallocated", "fragment",
                "compressed", "encrypted", "packed", "obfuscated", "encoded",
                "corrupted", "residual", "allocated_frag", "unalloc_frag",
                "orphan_frag", "recovered", "rebuild", "reconstructed",
                "decrypted", "decompressed", "unpacked", "parsed", "analyzed",
                "extracted_strings", "string", "string_type", "offset_hex",
                "encoding_type", "language", "entropy", "hashing_algorithm",
            ],
            "count": 108,
            "reference": "DFXML (Digital Forensics XML)"
        },
        "raw_disk_image": {
            "description": "Raw disk image (dd) and raw format metadata",
            "fields": [
                "image_size", "sector_size", "sector_count", "block_size",
                "block_count", "image_offset", "data_offset", "metadata_offset",
                "byte_order", "endianness", "compression", "compression_type",
                "encryption", "encryption_type", "checksum", "checksum_type",
                "md5", "sha1", "sha256", "sha512", "ssdeep", "tlsh", "file_hash",
                "hash_algo", "hash_status", "image_format", "source_path",
                "source_type", "source_media", "source_model", "source_serial",
                "source_firmware", "read_errors", "bad_sectors", "read_offset",
                "write_offset", "time_offset", "sector_mapping", "gap_size",
                "interleave", "deinterleave", "descramble", "scramble",
                "error_handling", "retry_count", "retry_delay", "skip_sector",
                "zero_sector", "fill_sector", "fill_value", "hash_sector",
                "verification", "verify_hash", "verify_compression", "verify_encryption",
                "image_info", "image_comment", "image_description", "image_creator",
                "acquisition_software", "acquisition_hardware", "acquisition_date",
                "acquisition_time", "acquisition_timezone", "acquisition_duration",
                "acquisition_notes", "evidence_number", "case_number", "examiner",
                "organization", "department", "notes", "chain_of_custody",
                "hash_source", "hash_location", "hash_time", "integrity_verified",
                "verification_date", "verification_time", "verification_status",
                "verification_notes", "clone_status", "clone_date", "clone_time",
                "clone_from", "clone_to", "clone_method", "clone_speed",
                "clone_progress", "clone_complete", "restore_status",
                "restore_date", "restore_time", "restore_from", "restore_to",
                "write_blockers", "write_blocker_type", "write_blocker_device",
                "write_blocker_status", "capture_device", "capture_interface",
                "capture_mode", "capture_speed", "capture_buffer", "capture_threads",
                "raw_copy", "dd_rescue", "dc3dd", "dcfldd", "guymager",
                "ftkimager", "table_of_contents", "directory_listing", "file_list",
                "metadata_list", "hash_list", "export_list", "import_list",
                "timeline", "event_log", "audit_log", "access_log", "error_log",
                "provenance", "chain", "parent", "child", "sibling", "related",
            ],
            "count": 110,
            "reference": "Raw Disk Image Standards"
        },
        "memory_forensics": {
            "description": "Memory forensics and analysis metadata",
            "fields": [
                "volatility", "profile", "kdbg", "kdbg_sig", "kdbg_offset",
                "dtb", "KPCR", "KPRCB", "KTHREAD", "EPROCESS", "ETHREAD",
                "MmSystemRangeStart", "KUSER_SHARED_DATA", "NTBuildNumber",
                "MajorVersion", "MinorVersion", "KeNumberProcessors", "Kdebug",
                "PsActiveProcessHead", "PsLoadedModuleList", "PsProcessType",
                "PsThreadType", "PsInitialSystemProcess", "ExpSystemResources",
                "ExpPagedPoolDescriptor", "ExpNonpagedPoolDescriptor", "MmNonpagedPoolStart",
                "MmPagedPoolStart", "MmNonpagedPoolEnd", "MmPagedPoolEnd",
                "MmSizeOfPagedPoolPoolTag", "MmMaximumNonpagedPoolDescriptor",
                "IopInvalidAddress", "ObpRootDirectoryObject", "ObpTypeObjectType",
                "SeSystemTime", "SeTimeZone", "LdrInInitializationOrderModuleList",
                "LdrInLoadOrderModuleList", "LdrInMemoryOrderModuleList",
                "VadRoot", "VadHint", "VadFlags", "VadType", "VadProtection",
                "VadCommitCharge", "VadPhysicalPage", "VadVirtualSize",
                "Win32Peb", "Win32Teb", "Win32Process", "Win32Thread",
                "Win32Client", "Console", "ServerClient", "DeviceObject",
                "DriverObject", "ObjectType", "ObjectDirectory", "SymbolicLink",
                "KeyObject", "ValueObject", "KeyName", "KeyValue", "KeyData",
                "KeyTimestamp", "HiveRoot", "HiveName", "HivePath", "CellSize",
                "RootCell", "Flags", "HiveKcbListHead", "HiveUserKcbListHead",
                "CM_KEY_INDEX", "CM_KEY_NODE", "CM_KEY_VALUE", "CM_KEY_SECURITY",
                "CM_KEY_BIG_DATA", "CM_KEY_FAST_LEAF", "CM_KEY_VALUE_BIG_LEAF",
                "HiveList", "HiveBin", "HiveBinHeader", "Cell", "Offset",
                "Size", "Signature", "Name", "LastWriteTime", "Security",
                "ValueCount", "ValueName", "ValueType", "ValueData", "Owner",
                "BuildNumber", "ServicePack", "CSDVersion", "ProductType",
                "SuiteMask", "Product", "SystemRoot", "ComputerName",
                "RegisteredOwner", "RegisteredOrganization", "ProductName",
                "Version", "InstallDate", "CurrentVersion", "CurrentType",
                "CompositionReady", "PathName", "CommandLine", "DesktopName",
                "StartupInfo", "ProcessParameters", "WindowTitle", "Environment",
                "CurrentDirectory", "DllPath", "Language", "CodePage",
                "OEMCodePage", "Locale", "InputLanguage", "OutputLanguage",
                "TimeZone", "Shell", "Desktop", "Shell folders", "User folders",
                "Printers", "Network", "UserAssist", "RunMRU", "ShellBags",
                "TypedPaths", "RecentDocs", "Thumbnails", "Prefetch", "Superfetch",
                "ReadyBoost", "Hiberfil", "Pagefile", "VirtualMemory", "PhysicalMemory",
                "PageDirectory", "SystemDirectory", "WindowsDirectory", "ProgramFiles",
                "AppData", "LocalAppData", "CommonAppData", "Temp",
            ],
            "count": 116,
            "reference": "Volatility Framework"
        },
        "ntfs_forensics": {
            "description": "NTFS filesystem forensics metadata",
            "fields": [
                "MFT", "MFTRecord", "MFTEntry", "RecordNumber", "SequenceNumber",
                "LinkCount", "AttributeList", "BaseMFTRecord", "BaseSequenceNumber",
                "Flags", "InUse", "Deleted", "$STANDARD_INFORMATION", "$ATTRIBUTE_LIST",
                "$FILE_NAME", "$VOLUME_NAME", "$VOLUME_INFORMATION", "$DATA",
                "$INDEX_ROOT", "$INDEX_ALLOCATION", "$BITMAP", "$BOOT",
                "$LOGFILE", "$MFTMirr", "$MFTData", "$Boot", "$LogFile",
                "$Extend", "$ObjId", "$Quota", "$Reparse", "$Secure", "$UpCase",
                "$Metadata", "$Orphan", "Resident", "NonResident", "DataRun",
                "VCN", "LCN", "Length", "CompressionUnit", "ClusterCount",
                "AttributeType", "AttributeName", "AttributeID", "FirstVCN",
                "LastVCN", "LowPart", "HighPart", "AllocatedLength", "FileSize",
                "InitializedSize", "ActualSize", "CompressedSize", "EnumeratedSize",
                "ReparsePoint", "ReparseTag", "ReparseData", "EA", "EALength",
                "EACount", "EAOffset", "ExtendedAttribute", "ExtendedAttributeLength",
                "SecurityDescriptor", "SecurityId", "OwnerId", "GroupId",
                "Dacl", "Sacl", "Control", "Revision", "Sbz1", "Owner",
                "Group", "DaclPresent", "DaclDefaulted", "DaclAutoInherited",
                "DaclProtected", "SaclPresent", "SaclDefaulted", "SaclAutoInherited",
                "SaclProtected", "DaclAutoInherit", "SaclAutoInherit",
                "DaclProtected", "SaclProtected", "GroupDefaulted", "OwnerDefaulted",
                "Control", "Revision", "AceCount", "AceSize", "AccessMask",
                "InheritFlags", "AceType", "AceFlags", "AceSize", "Sid",
                "Trustee", "Name", "Domain", "Size", "BirthVolumeId",
                "BirthObjectId", "DomainId", "ObjectId", "Guid", "BirthGuid",
                "BirthDroid", "BirthDomainId", "ObjectIdFlags", "ObjectIdTime",
                "Droid", "DomainId", "Usn", "UsnJournal", "LogFile", "Journal",
                "ChangeLog", "UpdateSequenceNumber", "SequenceNumber", "RestartArea",
                "LSN", "PreviousLSN", "NextRecord", "UpdateSequenceArray",
                "UpdateSequenceNumber", "UpdateSequenceOffset", "RestartOffset",
                "CurrentLsn", "LogPageNumber", "RecordPageNumber", "OldestLsn",
                "PrevLsn", "UndoLsn", "ClientId", "ClientType", "RecordType",
                "TransactionId", "AllocatedLsn", "FreeLsn", "HighestLsn",
                "MinArchiveLsn", "RestartLsn", "DirtyPages", "LogPageHeader",
                "LogRecordHeader", "LogRecordType", "UndoOp", "RedoOp",
                "UndoOperation", "RedoOperation", "LCN", "VBN", "FileName",
                "AttributeName", "AttributeTypeCode", "LCNIndex", "NextEntry",
            ],
            "count": 132,
            "reference": "NTFS Forensics"
        },
        "registry_forensics": {
            "description": "Windows Registry forensics metadata",
            "fields": [
                "Hive", "RootKey", "HiveHeader", "HiveLog", "HiveDirtyShutdown",
                "CheckSum", "Sequence1", "Sequence2", "MajorVersion", "MinorVersion",
                "Format", "RootCell", "ClusterSize", "FileName", "FilePath",
                "FileSize", "LastWriteTime", "HiveBin", "BinOffset", "BinSize",
                "CellSize", "CellOffset", "BinSignature", "FreeCount", "FreeOffset",
                "KeyNode", "KeyName", "ClassName", "ClassLength", "LastWriteTime",
                "Flags", "Spare", "Spare2", "NameLength", "NameOffset", "ClassOffset",
                "MaxNameLen", "MaxClassLen", "Values", "ValueCount", "ValueList",
                "ValueListOffset", "ValueLength", "ValueNameLength", "ValueDataLength",
                "ValueType", "ValueName", "ValueData", "Security", "SecurityOffset",
                "SecurityLength", "Class", "ClassOffset", "ClassLength", "MaxClassLen",
                "MaxValueNameLen", "MaxValueDataLen", "Flags", "KeyPath",
                "KeyNameLength", "ValueNameLength", "ValueDataLength", "KeyLastWrite",
                "ValueType", "RegNone", "RegSz", "RegExpandSz", "RegBinary",
                "RegDword", "RegDwordBigEndian", "RegLink", "RegMultiSz",
                "RegResourceList", "RegFullResourceDescriptor", "RegResourceRequirementsList",
                "RegQword", "LastWrite", "RegFileTime", "RegSZ", "RegExpandSZ",
                "RegBinary", "RegDWORD", "RegDWORD_LITTLE_ENDIAN", "RegDWORD_BIG_ENDIAN",
                "RegLink", "RegMultiSZ", "RegResourceList", "RegFullResourceDescriptor",
                "RegQWORD", "UserHive", "SystemHive", "SoftwareHive", "SamHive",
                "SecurityHive", "DefaultHive", "NTUSER_DAT", "USRCLASS_DAT",
                "SYSTEM", "SOFTWARE", "SAM", "SECURITY", "NTUSER", "USRCLASS",
                "HKEY_CLASSES_ROOT", "HKEY_CURRENT_USER", "HKEY_LOCAL_MACHINE",
                "HKEY_USERS", "HKEY_CURRENT_CONFIG", "CurrentControlSet",
                "ControlSet001", "ControlSet002", "MountedDevices", "SessionManager",
                "Control", "Windows", "System", "Software", "Policies", "Run",
                "RunOnce", "RunOnceEx", "RunServices", "RunServicesOnce",
                "Winlogon", "UserInit", "Shell", "UserShellFolders", "ShellFolders",
                "AppPaths", "Printers", "Devices", "Network", "Profiles",
                "AllUsers", "DefaultUser", "NTDEV", "NTQRY", "NTTEST", "NTWAM",
                "Default", "AlternateShells", "BootExecute", "Setup", "Lsa",
                "Policies", "Authentication", "Packages", "Extensions", "AppX",
                "Appx", "Metro", "UWP", "Store", "OneDrive", "Credentials",
                "Vault", "WindowsCredentials", "WinBio", "Biometric", "TPM",
                "BitLocker", "EFS", "Cryptography", "ProtectedData", "DPAPI",
            ],
            "count": 136,
            "reference": "Windows Registry Forensics"
        },
        "browser_forensics": {
            "description": "Browser history and forensics metadata",
            "fields": [
                "url", "title", "visit_count", "visit_time", "last_visit_time",
                "typed_count", "hidden", "favicon_id", "visit_source", "source_type",
                "redirect_source", "opener_visit", "originator_visit", "search_term",
                "bookmark", "bookmark_id", "folder_id", "parent_folder_id",
                "is_folder", "is_other_node", "date_added", "synced", "open_count",
                "launch_count", "frecency", "favicon_url", "desktop_background",
                "cookie", "name", "value", "host", "path", "expires", "secure",
                "http_only", "same_site", "priority", "session", "expiration",
                "browser_type", "download", "download_path", "download_url",
                "download_file", "download_state", "download_time", "download_started",
                "download_complete", "download_canceled", "download_interrupted",
                "download_dirty", "download_mime_type", "download_content_disposition",
                "download_referrer", "download_http_method", "download_by_ext_id",
                "download_channel", "download_tab_url", "download_tab_referrer",
                "download_renderer", "download_request_time", "download_start_time",
                "download_end_time", "download_total_bytes", "download_received_bytes",
                "download_blob_file", "download_original_mime_type", "history_page",
                "history_visit", "history_source", "history_transition",
                "history_redirect", "history_redirect_source", "history_redirect_target",
                "history_time", "history_duration", "history_hidden", "history_blocked",
                "history_typed", "history_link", "history_bookmark", "history_form_submit",
                "history_reload", "history_forward", "history_back", "history_from_remote",
                "history_start_page", "history_search", "history_internal", "history_unknown",
                "local_storage", "session_storage", "indexed_db", "web_sql",
                "cache", "service_worker", "push_notification", "background_sync",
                "notification", "notification_permission", "notification_data",
                "notification_tag", "notification_silent", "notification_require_interaction",
                "web_notification", "permission", "permission_origin", "permission_type",
                "permission_setting", "permission_default", "permission_granted",
                "permission_denied", "extension", "extension_id", "extension_name",
                "extension_version", "extension_enabled", "extension_disabled",
                "extension_loaded", "extension_unloaded", "extension_installed",
                "extension_updated", "extension_uninstalled", "extension_loaded_time",
                "extension_update_url", "extension_homepage_url", "extension_offline_enabled",
                "password", "password_origin", "password_action", "password_date",
                "password_count", "password_blacklisted", "password_generated",
                "password_federated", "password_has_old_form", "password_times_used",
                "password_form_data", "password_display_name", "password_realm",
                "password_scheme", "password_strength", "password_creator",
                "password_type", "password_uses_system_hey", "password_ssl_valid",
                "password_pwid", "password_sid", "form_history", "form_field",
                "form_value", "form_name", "form_type", "form_count",
                "form_autocomplete", "form_heuristic_type", "form_signature",
            ],
            "count": 128,
            "reference": "Browser Forensics"
        },
        "email_forensics": {
            "description": "Email and messaging forensics metadata",
            "fields": [
                "Message-ID", "In-Reply-To", "References", "Subject", "From",
                "To", "Cc", "Bcc", "Reply-To", "Sender", "Return-Path",
                "Delivered-To", "Received", "Received-SPF", "DKIM-Signature",
                "Authentication-Results", "X-Originating-IP", "X-Forwarded-For",
                "X-Mailer", "X-MS-Exchange-Organization-AuthSource",
                "X-MS-Exchange-Organization-AuthAs", "X-MS-Has-Attach", "X-MS-Exchange-Organization-Network-Message-Id",
                "Thread-Topic", "Thread-Index", "References", "In-Reply-To",
                "Message-Thread", "Conversation-Index", "Conversation-Topic",
                "Keywords", "Priority", "X-Priority", "X-MSMail-Priority",
                "Importance", "Sensitivity", "Content-Class", "Content-Type",
                "Content-Transfer-Encoding", "MIME-Version", "Date", "Reply-Date",
                "Resent-Date", "Received", "Return-Path", "Errors-To", "Bounces-To",
                "List-Subscribe", "List-Unsubscribe", "List-Post", "List-Help",
                "List-Owner", "List-Archive", "List-Id", "List-Unsubscribe-Post",
                "X-Spam-Status", "X-Spam-Score", "X-Spam-Flag", "X-Spam-Level",
                "X-Virus-Status", "X-Virus-Checker", "X-Virus-Status", "MessageContext",
                "SMTP-From", "SMTP-To", "SMTP-CC", "SMTP-Bcc", "SMTP-Rcpt-To",
                "SMTP-Mail-From", "SMTP-Rcpt-To", "SMTP-Relay", "SMTP-Auth",
                "SMTP-Auth-Method", "SMTP-Auth-User", "Envelope-To", "Return-Receipt-To",
                "Disposition-Notification-To", "Original-Disposition-Notification-To",
                "Read-Receipt-To", "X-Confirm-Reading-To", "Confirm-Reading-To",
                "Mdn-Sent-To", "Mdn-Requested", "Mdn-Original-Recipient",
                "X-Policyd-Result", "X-Virus-Scanned", "X-Antivirus-Status",
                "X-Antivirus-Scanner", "X-Antivirus-Engine", "X-Antivirus-Update",
                "X-SenderIP", "X-SenderPort", "X-ReceiverIP", "X-ReceiverPort",
                "X-Queue-ID", "X-SID-Result", "X-SID-Placement", "X-DSN-Result",
                "X-DSN-MID", "X-DSN-Envelope-To", "X-DSN-Transport-Path",
                "X-RIM", "X-BlackBerry", "X-iPhone", "X-Android", "X-Google-Apps",
                "X-Outlook", "X-Exchange", "X-Lotus-Notes", "X-Mozilla", "X-Thunderbird",
                "X-Mailer", "User-Agent", "X-Mailer-Version", "X-Originating-IP",
                "X-Proxy-IP", "X-Forwarded-For", "X-Real-IP", "X-Client-IP",
                "X-Remote-IP", "X-Source-IP", "X-Source-Port", "X-Source-MTA",
                "X-Received-Time", "X-Delivery-Time", "X-First-Queue-Time",
                "X-Last-Queue-Time", "X-Queue-Duration", "X-Processed-By",
                "X-Spam-Threshold", "X-Spam-Score", "X-Spam-Bar", "X-Spam-Tests",
                "X-Spam-Test-Status", "X-Spam-Report", "X-Spam-Checker-Version",
                "X-Spam-Status", "X-Spam-Level", "X-Spam-Status", "X-Policyd-Reason",
                "X-Policyd-Quarantine", "X-Quarantine-ID", "X-Quarantine-Reason",
                "X-Quarantine-Info", "X-Mailed-By", "X-Mailed-To", "X-Copy-To",
                "X-PGP", "X-PGP-Encrypted", "X-PGP-Signature", "X-PGP-Key-ID",
                "X-PGP-Key-Fingerprint", "X-PGP-Encoding", "X-SMIME", "X-SMIME-Certificates",
                "X-SMIME-Encrypted", "X-SMIME-Signed", "X-SMIME-Algorithms",
            ],
            "count": 144,
            "reference": "Email Forensics (RFC, RFC 5322)"
        },
        "malware_analysis": {
            "description": "Malware analysis and detection metadata",
            "fields": [
                "malware_name", "malware_family", "malware_type", "malware_category",
                "malware_variant", "malware_version", "malware_author", "malware_created",
                "malware_modified", "malware_compiled", "malware_packed", "malware_obfuscated",
                "malware_encrypted", "malware_anti_debug", "malware_anti_vm",
                "malware_anti_sandbox", "malware_anti_analysis", "malware_anti_disassembly",
                "malware_persistence", "malware_infection", "malware_dropper",
                "malware_downloader", "malware_hehavior", "malware_keylogger",
                "malware_ransomware", "malware_trojan", "malware_worm", "malware_virus",
                "malware_rootkit", "malware_backdoor", "malware_ exploit",
                "malware_shellcode", "malware_payload", "malware_c2", "malware_dga",
                "malware_domain", "malware_ip", "malware_url", "malware_email",
                "hash_md5", "hash_sha1", "hash_sha256", "hash_sha512", "hash_ssdeep",
                "hash_tlsh", "hash_imphash", "hash_pehash", "hash_authentihash",
                "hash_impdump", "signature_name", "signature_id", "signature_family",
                "yara_rule", "yara_match", "suricata_sid", "suricata_msg",
                "suricata_rev", "suricata_classtype", "virustotal", "av_detect",
                "av_vendor", "av_product", "av_engine", "av_definition",
                "av_update", "scan_date", "scan_result", "threat_level",
                "threat_name", "threat_category", "threat_description", "threat_action",
                "static_analysis", "dynamic_analysis", "behavior_analysis",
                "sandbox_report", "sandbox_id", "sandbox_name", "sandbox_time",
                "sandbox_os", "sandbox_vm", "sandbox_domain", "sandbox_ip",
                "sandbox_url", "sandbox_process", "sandbox_file", "sandbox_regkey",
                "sandbox_network", "sandbox_dns", "sandbox_http", "sandbox_https",
                "sandbox_smtp", "sandbox_irc", "sandbox_p2p", "sandbox_websocket",
                "sandbox_mutex", "sandbox_registry", "sandbox_file_access",
                "sandbox_registry_access", "sandbox_network_access", "sandbox_process_injection",
                "sandbox_api_calls", "sandbox_strings", "sandbox_screenshot",
                "sandbox_pcap", "sandbox_memory_dump", "sandbox_memory_size",
                "sandbox_memory_offset", "yara_strings", "string_offset", "string_data",
                "string_type", "string_section", "pe_imports", "pe_exports",
                "pe_sections", "pe_headers", "pe_resources", "pe_overlay",
                "pe_tls", "pe_debug", "pe_relocations", "pe_bound_import",
                "pe_delay_import", "pe_com_descriptor", "pe_certificate",
                "pe_versioninfo", "pe_macho", "pe_elf", "pe_dotnet", "pe_pdb",
                "pe_symbols", "pe_export", "pe_import", "pe_delay_load",
                "pe_runtime_function", "pe_exception_handler", "pe_security_cookie",
                "pe_guard_cf", "pe_guard_fids", "pe_guard_ehcon", "pe_guard_checks",
                "pe_export_count", "pe_import_count", "pe_section_count",
                "pe_resource_count", "pe_export_names", "pe_import_names",
                "pe_section_names", "pe_section_entropy", "pe_code_section",
                "pe_data_section", "pe_resource_section", "pe_export_section",
                "pe_tls_section", "pe_reloc_section", "pe_null_section",
                "pe_section_virtual_size", "pe_section_raw_size", "pe_section_raw_offset",
                "pe_section_virtual_address", "pe_section_characteristics",
            ],
            "count": 146,
            "reference": "Malware Analysis Standards"
        }
    },
    "totals": {
        "categories": 10,
        "total_fields": 1222
    }
}


def main():
    output_dir = Path("dist/forensic_inventory")
    output_dir.mkdir(parents=True, exist_ok=True)
    
    output_file = output_dir / "forensic_inventory.json"
    output_file.write_text(json.dumps(FORENSIC_INVENTORY, indent=2, sort_keys=True), encoding="utf-8")
    
    summary = {
        "generated_at": FORENSIC_INVENTORY["generated_at"],
        "source": FORENSIC_INVENTORY["source"],
        "categories": FORENSIC_INVENTORY["totals"]["categories"],
        "total_fields": FORENSIC_INVENTORY["totals"]["total_fields"],
        "field_counts_by_category": {}
    }
    
    for cat, data in FORENSIC_INVENTORY["categories"].items():
        summary["field_counts_by_category"][cat] = {
            "description": data["description"],
            "count": data["count"],
            "reference": data.get("reference", "N/A")
        }
    
    summary_file = output_dir / "forensic_summary.json"
    summary_file.write_text(json.dumps(summary, indent=2), encoding="utf-8")
    
    print("=" * 70)
    print("FORENSIC FORMAT METADATA FIELD INVENTORY")
    print("=" * 70)
    print()
    print(f"Generated: {FORENSIC_INVENTORY['generated_at']}")
    print(f"Categories: {FORENSIC_INVENTORY['totals']['categories']}")
    print(f"Total Fields: {FORENSIC_INVENTORY['totals']['total_fields']:,}")
    print()
    print("FIELD COUNTS BY CATEGORY:")
    print("-" * 50)
    for cat, data in sorted(FORENSIC_INVENTORY["categories"].items(), key=lambda x: x[1]["count"], reverse=True):
        ref = data.get("reference", "")[:35]
        print(f"  {cat:35s}: {data['count']:>3}  [{ref}]")
    print()
    print(f"Wrote: {output_file}")
    print(f"Wrote: {summary_file}")


if __name__ == "__main__":
    main()
