#!/usr/bin/env python3
"""Satellite and Scientific Remote Sensing Metadata Field Inventory.

Covers satellite remote sensing formats including GeoTIFF/COG, NetCDF/Climate,
HDF5/EOS, Landsat, MODIS, Copernicus/Sentinel, and Planet Labs metadata.
"""

from datetime import datetime, timezone
import json
from pathlib import Path
from typing import Dict, List, Any


def generate_satellite_inventory():
    """Generate comprehensive satellite and scientific remote sensing metadata field inventory."""

    INVENTORY = {
        "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "source": "GeoTIFF Spec, CF Conventions, HDF5/EOS, USGS Landsat, NASA MODIS, ESA Copernicus, Planet Labs",
        "description": "Satellite and scientific remote sensing metadata fields for Earth observation data",
        "categories": {
            "geotiff_cog": {
                "description": "Cloud-Optimized GeoTIFF tags and geographic metadata",
                "reference": "https://gdal.org/en/stable/drivers/raster/gtiff.html",
                "fields": [
                    "geotiff.tag_id",
                    "geotiff.gdal_nodata",
                    "geotiff.gdal_data_type",
                    "geotiff.gdal_pixel_type",
                    "geotiff.gdal_scale",
                    "geotiff.gdal_offset",
                    "geotiff.interleave",
                    "geotiff.compression",
                    "geotiff.photometric",
                    "geotiff.planarconfig",
                    "geotiff.bitdepth",
                    "geotiff.sampleformat",
                    "geotiff.rowsperstrip",
                    "geotiff.stripoffsets",
                    "geotiff.stripbytecounts",
                    "geotiff.tilewidth",
                    "geotiff.tilelength",
                    "geotiff.tileoffsets",
                    "geotiff.tilebytecounts",
                    "geotiff.extrasamples",
                    "geotiff.samplesperpixel",
                    "geotiff.datatype",
                    "geotiff.bitspersample",
                    "geotiff.predictor",
                    "geotiff.whitelevel",
                    "geotiff.targetprintersresolution",
                    "geotiff.numberoffirs",
                    "geotiff.firstor",
                    "geotiff.lastor",
                    "geotiff.colormapentries",
                    "geotiff.resolutionunit",
                    "geotiff.xresolution",
                    "geotiff.yresolution",
                    "geotiff.xposition",
                    "geotiff.yposition",
                    "geotiff.zposition",
                    "geotiff.tiepoints",
                    "geotiff.pixelscale",
                    "geotiff.modeltransformation",
                    "geotiff.wms_metadata",
                    "geotiff.jpegtables",
                    "geotiff.jpegdctables",
                    "geotiff.jpegactables",
                    "geotiff.ycbcrcoefficients",
                    "geotiff.ycbcrsubsampling",
                    "geotiff.ycbcrpositioning",
                    "geotiff.referenceblackwhite",
                    "geotiff.exififd",
                    "geotiff.gpsinfo",
                    "geotiff.photoshop",
                    "geotiff.iccprofile",
                    "geotiff.iptcdata",
                    "geotiff.xmp",
                    "geotiff.gdal_area_or_point",
                    "geotiff.gdal_ucrlf",
                    "geotiff.gdal_json_md",
                    "geotiff.gdal_metadata",
                    "geotiff.gdal_ncores",
                    "geotiff.gdal_overviews",
                    "geotiff.gdal_nodata_for_gray",
                    "geotiff.gdal_thumbnail",
                    "geotiff.gdal_implicit_nodata",
                    "geotiff.gdal_xmp_box",
                    "geotiff.gdal_nodata_exceptional",
                    "geotiff.internal_geokey",
                    "geotiff.gdal_md_cpanel",
                    "geotiff.gdal_te_density",
                    "geotiff.gdal_te_unit",
                    "geotiff.gtiff_metadata",
                    "geotiff.gtiff_num_threads",
                    "geotiff.gtiff_reuse_external_overviews",
                    "geotiff.gtiff_jpeg_quality",
                    "geotiff.gtiff_jpeg_overview_quality",
                    "geotiff.gtiff_predictor",
                    "geotiff.gtiff_skip_pixels",
                    "geotiff.gtiff_skip_last_eol",
                    "geotiff.gtiff_direct_io",
                    "geotiff.gtiff_accurate_geokey",
                    "geotiff.gtiff_tiling_scheme",
                    "geotiff.gtiff_read_geo_keys",
                    "geotiff.gtiff_inline_geo_key",
                    "geotiff.gtiff_geo_keys",
                    "geotiff.gtiff_geo_keys_version",
                    "geotiff.gtiff_rcs",
                    "geotiff.geostandard_metadata",
                    "geotiff.proxy",
                    "geotiff.rpc",
                    "geotiff.bottom_cf",
                    "geotiff.gdal_metadata_ada",
                    "geotiff.gdal_nodata_mask",
                    "cog.byte_order",
                    "cog.skip_bytes",
                    "cog.overview_count",
                    "cog.overview_offsets",
                    "cog.overview_byte_counts",
                    "cog.tile_offsets",
                    "cog.tile_byte_counts",
                    "cog.iend",
                    "cog.valid",
                    "cog.mime_type",
                    "cog.tile_width",
                    "cog.tile_height",
                    "cog.interleave",
                    "cog.compression",
                    "cog.cloud_optimized",
                    "cog.rgba_photometric",
                    "cog.is_tiled",
                    "cog.has_levels",
                    "cog.uses_lzw",
                    "cog.uses_deflate",
                    "cog.uses_png",
                    "cog.uses_jpeg",
                    "cog.uses_zstd",
                    "cog.has_alpha",
                    "cog.mask_flags",
                    "cog.nodata_mask",
                    "cog.overviews_offsets",
                    "cog.overviews_pixel_size",
                    "cog.overviews_bytes",
                    "cog.ifd_offset",
                    "cog.first_ifd",
                    "cog.last_ifd",
                    "cog.validate_checksum",
                    "cog.validate_image",
                    "cog.geo_keys",
                    "geokey.model_type",
                    "geokey.raster_type",
                    "geokey.citation",
                    "geokey.geographic_type",
                    "geokey.geog_citation",
                    "geokey.geog_angular_units",
                    "geokey.geog_azimuth_units",
                    "geokey.prime_meridian",
                    "geokey.prime_meridian_long",
                    "geokey.to_em_sphere",
                    "geokey.greenwich_longitude",
                    "geokey.equatorial_radius",
                    "geokey.semi_major_axis",
                    "geokey.semi_minor_axis",
                    "geokey.inverse_flattening",
                    "geokey.linear_unit_size",
                    "geokey.projected_cs_type",
                    "geokey.proj_citation",
                    "geokey.proj_linear_units",
                    "geokey.proj_std_parallel1",
                    "geokey.proj_std_parallel2",
                    "geokey.proj_nat_origin_lat",
                    "geokey.proj_nat_origin_long",
                    "geokey.proj_false_easting",
                    "geokey.proj_false_northing",
                    "geokey.proj_false_origin_lat",
                    "geokey.proj_false_origin_long",
                    "geokey.proj_center_lat",
                    "geokey.proj_center_long",
                    "geokey.proj_azimuth_angle",
                    "geokey.proj_straight_vert_pole_long",
                    "geokey.vertical_cs_type",
                    "geokey.vert_citation",
                    "geokey.vert_datum",
                    "geokey.vertical_units",
                ],
                "count": 150,
            },
            "netcdf_climate": {
                "description": "NetCDF Climate and Forecast conventions metadata",
                "reference": "https://cfconventions.org/",
                "fields": [
                    "netcdf.title",
                    "netcdf.institution",
                    "netcdf.source",
                    "netcdf.history",
                    "netcdf.references",
                    "netcdf.comment",
                    "netcdf.Conventions",
                    "netcdf.featureType",
                    "netcdf.cdm_data_type",
                    "netcdf.long_name",
                    "netcdf.standard_name",
                    "netcdf.units",
                    "netcdf.axis",
                    "netcdf.positive",
                    "netcdf.bounds",
                    "netcdf.climatology",
                    "netcdf.coordinates",
                    "netcdf.grid_mapping",
                    "netcdf.ancillary_variables",
                    "netcdf.associated_variables",
                    "netcdf.cell_methods",
                    "netcdf.cell_measures",
                    "netcdf.comment",
                    "netcdf.compress",
                    "netcdf.contiguous",
                    "netcdf.chunk_sizes",
                    "netcdf.coordinates",
                    "netcdf.flag_meanings",
                    "netcdf.flag_values",
                    "netcdf.instrument",
                    "netcdf.instrument_type",
                    "netcdf.measurement_method",
                    "netcdf.platform",
                    "netcdf.platform_type",
                    "netcdf.processing_level",
                    "netcdf.product_version",
                    "netcdf.program",
                    "netcdf.project",
                    "netcdf.realization",
                    "netcdf.sensor",
                    "netcdf.sensor_type",
                    "netcdf.source_type",
                    "netcdf.spatial_representation",
                    "netcdf.spatial_resolution",
                    "netcdf.time_coverage_duration",
                    "netcdf.time_coverage_end",
                    "netcdf.time_coverage_resolution",
                    "netcdf.time_coverage_start",
                    "netcdf.time_mean",
                    "netcdf.valid_max",
                    "netcdf.valid_min",
                    "netcdf.valid_range",
                    "netcdf.missing_value",
                    "netcdf._FillValue",
                    "netcdf.scale_factor",
                    "netcdf.add_offset",
                    "netcdf.calendar",
                    "netcdf.calendar_type",
                    "netcdf.calendar_month_lengths",
                    "netcdf.leap_year",
                    "netcdf.leap_month",
                    "netcdf.month_lengths",
                    "netcdf.days_since",
                    "netcdf.time_origin",
                    "netcdf.tendencies",
                    "netcdf.original_units",
                    "netcdf.original_name",
                    "netcdf.original_range",
                    "netcdf.standard_name_vocabulary",
                    "netcdf.geospatial_lat_units",
                    "netcdf.geospatial_lon_units",
                    "netcdf.geospatial_lat_resolution",
                    "netcdf.geospatial_lon_resolution",
                    "netcdf.geospatial_vertical_units",
                    "netcdf.geospatial_vertical_resolution",
                    "netcdf.geospatial_vertical_positive",
                    "netcdf.date_created",
                    "netcdf.date_modified",
                    "netcdf.date_issued",
                    "netcdf.geospatial_bounds",
                    "netcdf.geospatial_bounds_crs",
                    "netcdf.time_coverage_period_name",
                    "netcdf.time_coverage_reference",
                    "netcdf.crs_wkt",
                    "netcdf.grid_mapping_name",
                    "netcdf.latitude_of_projection_origin",
                    "netcdf.longitude_of_projection_origin",
                    "netcdf.straight_vertical_longitude_from_pole",
                    "netcdf.scale_factor_at_projection_origin",
                    "netcdf.scale_factor_at_central_pivot",
                    "netcdf.semi_major_axis",
                    "netcdf.semi_minor_axis",
                    "netcdf.inverse_flattening",
                    "netcdf.false_easting",
                    "netcdf.false_northing",
                    "netcdf.horizontal_resolution",
                    "netcdf.vertical_resolution",
                    "netcdf.surface_resolution",
                    "netcdf.orbit_number",
                    "netcdf.orbit_start_time",
                    "netcdf.orbit_end_time",
                    "netcdf.platform_longitude",
                    "netcdf.platform_latitude",
                    "netcdf.platform_altitude",
                    "netcdf.satellite_longitude",
                    "netcdf.satellite_latitude",
                    "netcdf.satellite_altitude",
                    "netcdf.solar_azimuth",
                    "netcdf.solar_elevation",
                    "netcdf.satellite_azimuth",
                    "netcdf.satellite_view_angle",
                    "netcdf.wavelength",
                    "netcdf.wavelength_units",
                    "netcdf.band_width",
                    "netcdf.band_center",
                    "netcdf.pulse_repetition_frequency",
                    "netcdf.pulse_duration",
                    "netcdf.peak_power",
                    "netcdf.average_power",
                    "netcdf.noise_equivalent_sigma0",
                    "netcdf.sigma0_scale_factor",
                    "netcdf.beta0_scale_factor",
                    "netcdf.gamma0_scale_factor",
                    "netcdf.speckle_filter",
                    "netcdf.multi_look",
                    "netcdf.azimuth_looks",
                    "netcdf.range_looks",
                    "netcdf.doppler_centroid",
                    "netcdf.doppler_rate",
                    "netcdf.baseline",
                    "netcdf.perp_baseline",
                    "netcdf.parallel_baseline",
                    "netcdf.temporal_baseline",
                    "netcdf.incidence_angle",
                    "netcdf.incidence_angle_mid",
                    "netcdf.incidence_angle_near",
                    "netcdf.incidence_angle_far",
                    "netcdf.slant_range",
                    "netcdf.ground_range",
                    "netcdf.acquisition_mode",
                    "netcdf.beam_id",
                    "netcdf.polarisation",
                    "netcdf.polarisation_channels",
                    "netcdf.transmit_polarisation",
                    "netcdf.receive_polarisation",
                    "netcdf.look_direction",
                    "netcdf.look_side",
                    "netcdf.noise_calibration",
                    "netcdf.radiometric_calibration",
                    "netcdf.absolute_calibration_factor",
                ],
                "count": 160,
            },
            "hdf5_eos": {
                "description": "HDF5 Earth Observing System format metadata",
                "reference": "https://eos.nasa.gov/",
                "fields": [
                    "hdf5.version",
                    "hdf5.creation_date",
                    "hdf5.modification_date",
                    "hdf5.file_size",
                    "hdf5.number_of_objects",
                    "hdf5.root_group",
                    "hdf5.super_block_version",
                    "hdf5.free_space_manager",
                    "hdf5.object_header",
                    "hdf5.btree",
                    "hdf5.local_heap",
                    "hdf5.global_heap",
                    "hdf5.object_directory",
                    "hdf5.symbol_table",
                    "hdf5.fractal_heap",
                    "hdf5.free_space",
                    "hdf5.chunk_index",
                    "hdf5.small_data",
                    "hdf5.driver_information",
                    "hdf5.file_address_size",
                    "hdf5.base_address",
                    "hdf5.offset_size",
                    "hdf5.length_size",
                    "hdf5.maximum_file_size",
                    "hdf5.epoch_timestamp",
                    "hdf5.eos.creator",
                    "hdf5.eos.satellite",
                    "hdf5.eos.sensor",
                    "hdf5.eos.product",
                    "hdf5.eos.product_level",
                    "hdf5.eos.acquisition_time",
                    "hdf5.eos.start_time",
                    "hdf5.eos.stop_time",
                    "hdf5.eos.day_night_flag",
                    "hdf5.eos.solar_zenith",
                    "hdf5.eos.solar_azimuth",
                    "hdf5.eos.observer_zenith",
                    "hdf5.eos.observer_azimuth",
                    "hdf5.eos.latitude",
                    "hdf5.eos.longitude",
                    "hdf5.eos.altitude",
                    "hdf5.eos.roll",
                    "hdf5.eos.pitch",
                    "hdf5.eos.yaw",
                    "hdf5.eos.velocity",
                    "hdf5.eos.track_direction",
                    "hdf5.eos.sun_glint_angle",
                    "hdf5.eos.quality_flag",
                    "hdf5.eos.science_quality_flag",
                    "hdf5.eos.geometry_flag",
                    "hdf5.eos.calibration_flag",
                    "hdf5.eos.l1b_granule_number",
                    "hdf5.eos.l1b_granule_pointer",
                    "hdf5.eos.aggregation_flag",
                    "hdf5.eos.aggregation_parms",
                    "hdf5.eos.auto_flag",
                    "hdf5.eos.auto_corrected",
                    "hdf5.eos.horizontal_averaging",
                    "hdf5.eos.vertical_averaging",
                    "hdf5.eos.num_averaged_profiles",
                    "hdf5.eos.sounding_ident",
                    "hdf5.eos.height",
                    "hdf5.eos.surface_pressure",
                    "hdf5.eos.temperature",
                    "hdf5.eos.relative_humidity",
                    "hdf5.eos.ozone",
                    "hdf5.eos.water_vapor",
                    "hdf5.eos.aerosol",
                    "hdf5.eos.albedo",
                    "hdf5.eos.reflectance",
                    "hdf5.eos.emissivity",
                    "hdf5.eos.brightness_temperature",
                    "hdf5.eos.radiance",
                    "hdf5.eos.radiance_units",
                    "hdf5.eos.radiance_scale",
                    "hdf5.eos.radiance_offset",
                    "hdf5.eos.noise_equivalent",
                    "hdf5.eos.signal_to_noise",
                    "hdf5.eos.dynamic_range",
                    "hdf5.eos.saturation_level",
                    "hdf5.eos.detector_id",
                    "hdf5.eos.track",
                    "hdf5.eos.frame",
                    "hdf5.eos.scan",
                    "hdf5.eos.ground_pixel",
                    "hdf5.eos.scan_row",
                    "hdf5.eos.scan_col",
                    "hdf5.eos.alignment_offset",
                    "hdf5.eos.gain_setting",
                    "hdf5.eos.integration_time",
                    "hdf5.eos.coadding_factor",
                    "hdf5.eos.coadding_method",
                    "hdf5.eos.band_id",
                    "hdf5.eos.band_name",
                    "hdf5.eos.wavelength_center",
                    "hdf5.eos.wavelength_width",
                    "hdf5.eos.spectral_response",
                    "hdf5.eos.nadir_pixel_size",
                    "hdf5.eos.swath_width",
                    "hdf5.eos.footprint",
                    "hdf5.eos.glint_geometry",
                    "hdf5.eos.tropo_geometry",
                    "hdf5.eos.aerosol_index",
                    "hdf5.eos.aerosol_type",
                    "hdf5.eos.cloud_fraction",
                    "hdf5.eos.cloud_pressure",
                    "hdf5.eos.cloud_temperature",
                    "hdf5.eos.cloud_height",
                    "hdf5.eos.cloud_mask",
                    "hdf5.eos.land_water_mask",
                    "hdf5.eos.snow_ice_mask",
                    "hdf5.eos.daily_flag",
                    "hdf5.eos.ascending_flag",
                    "hdf5.eos.nadir_flag",
                    "hdf5.eos.limb_flag",
                    "hdf5.eos.dimming_flag",
                    "hdf5.eos.earth_sun_distance",
                    "hdf5.eos.experiment_id",
                    "hdf5.eos.orbit_mode",
                    "hdf5.eos.orbit_direction",
                    "hdf5.eos.orbit_period",
                    "hdf5.eos.repeat_cycle",
                    "hdf5.eos.equator_crossing_time",
                    "hdf5.eos.equator_crossing_longitude",
                    "hdf5.eos.saa_flag",
                    "hdf5.eos.saa_lon_min",
                    "hdf5.eos.saa_lon_max",
                    "hdf5.eos.saa_lat_min",
                    "hdf5.eos.saa_lat_max",
                    "hdf5.eos.saa_start_time",
                    "hdf5.eos.saa_stop_time",
                    "hdf5.eos.eclipse_flag",
                    "hdf5.eos.eclipse_entry_time",
                    "hdf5.eos.eclipse_exit_time",
                ],
                "count": 140,
            },
            "landsat": {
                "description": "Landsat 8/9 Collection 2 metadata and MTL files",
                "reference": "https://www.usgs.gov/landsat-missions/landsat-collection-2",
                "fields": [
                    "landsat.product_id",
                    "landsat.collection_number",
                    "landsat.landsat_scene_id",
                    "landsat.landsat_product_identifier",
                    "landsat.processing_level",
                    "landsat.tier_level",
                    "landsat.sensor_id",
                    "landsat.spacecraft_id",
                    "landsat.acquisition_date",
                    "landsat.scene_center_time",
                    "landsat.date_updated",
                    "landsat.satellite",
                    "landsat.wrs_path",
                    "landsat.wrs_row",
                    "landsat.wrs_type",
                    "landsat.target_wrs_path",
                    "landsat.target_wrs_row",
                    "landsat.utm_zone",
                    "landsat.datum",
                    "landsat.ellipsoid",
                    "landsat.origin",
                    "landsat.grid_origin",
                    "landsat.map_projection",
                    "landsat.resampling_option",
                    "landsat.cloud_cover",
                    "landsat.cloud_cover_land",
                    "landsat.image_quality_oli",
                    "landsat.image_quality_tirs",
                    "landsat.roll_angle",
                    "landsat.sun_elevation",
                    "landsat.sun_azimuth",
                    "landsat.earth_sun_distance",
                    "landsat.ground_control_points_version",
                    "landsat.ground_control_points_model",
                    "landsat.geometric_rmse_model",
                    "landsat.geometric_rmse_model_x",
                    "landsat.geometric_rmse_model_y",
                    "landsat.geometric_rmse_model_z",
                    "landsat.elevation_source",
                    "landsat.dem_version",
                    "landsat.data_type_oli",
                    "landsat.data_type_tirs",
                    "landsat.radiometric_rescaling",
                    "landsat.reflective_slope",
                    "landsat.reflective_offset",
                    "landsat.thermal_slope",
                    "landsat.thermal_offset",
                    "landsat.ctl_version",
                    "landsat.ctl_date",
                    "landsat.horizontal_error",
                    "landsat.vertical_error",
                    "landsat.scene_start_time",
                    "landsat.scene_end_time",
                    "landsat.sunsensor_distance",
                    "landsat.illumination_azimuth",
                    "landsat.illumination_elevation",
                    "landsat.illumination_extraterrestrial",
                    "landsat.azimuth_angle",
                    "landsat.zenith_angle",
                    "landsat.gain_bridge",
                    "landsat.gain_header",
                    "landsat.output_format",
                    "landsat.band1_min",
                    "landsat.band1_max",
                    "landsat.band2_min",
                    "landsat.band2_max",
                    "landsat.band3_min",
                    "landsat.band3_max",
                    "landsat.band4_min",
                    "landsat.band4_max",
                    "landsat.band5_min",
                    "landsat.band5_max",
                    "landsat.band6_min",
                    "landsat.band6_max",
                    "landsat.band7_min",
                    "landsat.band7_max",
                    "landsat.band9_min",
                    "landsat.band9_max",
                    "landsat.band10_min",
                    "landsat.band10_max",
                    "landsat.band11_min",
                    "landsat.band11_max",
                    "landsat.k1_const_band10",
                    "landsat.k2_const_band10",
                    "landsat.k1_const_band11",
                    "landsat.k2_const_band11",
                    "landsat.band_storage_order",
                    "landsat.support_data",
                    "landsat.ephemeris_type",
                    "landsat.ephemeris_units",
                    "landsat.ephemeris_interval",
                    "landsat.start_x",
                    "landsat.start_y",
                    "landsat.start_z",
                    "landsat.start_velocity_x",
                    "landsat.start_velocity_y",
                    "landsat.start_velocity_z",
                    "landsat.end_x",
                    "landsat.end_y",
                    "landsat.end_z",
                    "landsat.end_velocity_x",
                    "landsat.end_velocity_y",
                    "landsat.end_velocity_z",
                    "landsat.attitude_count",
                    "landsat.attitude_time",
                    "landsat.attitude_quaternion",
                    "landsat.full_disk",
                    "landsat.sr_apply_qa",
                    "landsat.pixel_size",
                    "landsat.product_size",
                    "landsat.corner_ul_lon",
                    "landsat.corner_ul_lat",
                    "landsat.corner_ur_lon",
                    "landsat.corner_ur_lat",
                    "landsat.corner_ll_lon",
                    "landsat.corner_ll_lat",
                    "landsat.corner_lr_lon",
                    "landsat.corner_lr_lat",
                    "landsat.corner_lc_lon",
                    "landsat.corner_lc_lat",
                ],
                "count": 130,
            },
            "modis": {
                "description": "MODIS land and atmospheric product metadata",
                "reference": "https://modis.gsfc.nasa.gov/data/",
                "fields": [
                    "modis.product_name",
                    "modis.product_identifier",
                    "modis.local GranuleID",
                    "modis.day_night_flag",
                    "modis.production_status",
                    "modis.local_version_id",
                    "modis.pge_version",
                    "modis.pge_name",
                    "modis.science_quality_flag",
                    "modis.science_quality_explanation",
                    "modis.qc_精华云检测标志",
                    "modis.qc_land_surface_temperature",
                    "modis.qc_emis_错误状态",
                    "modis.input_granules",
                    "modis.reprocessing_activated",
                    "modis.reprocessing_planned",
                    "modis.algorithm_version",
                    "modis.algorithm_l2_version",
                    "modis.algorithm_l3_version",
                    "modis.processing_environment",
                    "modis.processing_center",
                    "modis.instrument_name",
                    "modis.instrument_short_name",
                    "modis.product_level",
                    "modis.satellite_name",
                    "modis.satellite_short_name",
                    "modis.ascending_descending_flag",
                    "modis.equator_crossing_longitude",
                    "modis.equator_crossing_time",
                    "modis.equator_crossing_date",
                    "modis.geolocation_grid_from_hdf",
                    "modis.start_time",
                    "modis.end_time",
                    "modis.local_granule_start_time",
                    "modis.local_granule_end_time",
                    "modis.production_datetime",
                    "modis.northBoundingCoord",
                    "modis.southBoundingCoord",
                    "modis.eastBoundingCoord",
                    "modis.westBoundingCoord",
                    "modis.gring_latitude",
                    "modis.gring_longitude",
                    "modis.granule_pointer",
                    "modis.number_of_granules",
                    "modis.total_aod_retrievals",
                    "modis.total_observations",
                    "modis.day_view_zenith",
                    "modis.day_view_zenith_range",
                    "modis.day_view_time",
                    "modis.night_view_zenith",
                    "modis.night_view_zenith_range",
                    "modis.night_view_time",
                    "modis.solar_zenith",
                    "modis.solar_zenith_range",
                    "modis.relative_azimuth",
                    "modis.relative_azimuth_range",
                    "modis scattering_angle",
                    "modis.glint_angle",
                    "modis.cloud_fraction",
                    "modis.cloud_fraction_land",
                    "modis snow_ice_fraction",
                    "modis.land_sea_mask",
                    "modis.aerosol_type",
                    "modis.fine_mode_fraction",
                    "modis.effective_optical_depth",
                    "modis.optical_depth_land",
                    "modis.angstrom_exponent",
                    "modis.angstrom_exponent_land",
                    "modis.single_scattering_albedo",
                    "modis.surface_reflectance",
                    "modis.nbar_brdf_corrected",
                    "modis.brdf_alphas",
                    "modis.brdf_greeks",
                    "modis.brdf_normals",
                    "modis.l2_flags",
                    "modis.land_sea_fraction",
                    "modis.land_surface_temperature",
                    "modis.emissivity",
                    "modis.emissivity_band29",
                    "modis.emissivity_band31",
                    "modis.emissivity_band32",
                    "modis.l3_stdv",
                    "modis.l3_number_of_observations",
                    "modis.l3_number_of_pixels",
                    "modis.l3_valid_pixels",
                    "modis.l3_missing_pixels",
                    "modis.l3_cloud_pixels",
                    "modis.l3_weights",
                    "modis.l3_mean_visibility",
                    "modis.l3_sensitivity",
                    "modis.wavelengths",
                    "modis.band_numbers",
                    "modis.radiance_scales",
                    "modis.radiance_offsets",
                    "modis.reflectance_scales",
                    "modis.reflectance_offsets",
                    "modis.brightness_temp_scales",
                    "modis.brightness_temp_offsets",
                    "modis.quality_scales",
                    "modis.quality_offsets",
                    "modis.band_26_nir",
                    "modis.band_26_qf",
                    "modis.nadir_brdf",
                    "modis.time_diff",
                    "modis.sensor_zenith",
                    "modis.sensor_azimuth",
                    "modis.solar_zenith",
                    "modis.solar_azimuth",
                ],
                "count": 120,
            },
            "copernicus_sentinel": {
                "description": "Sentinel-1, 2, 3 product metadata from ESA Copernicus",
                "reference": "https://sentinels.copernicus.eu/",
                "fields": [
                    "sentinel.product_id",
                    "sentinel.product_type",
                    "sentinel.processing_level",
                    "sentinel.satellite_name",
                    "sentinel.mission_phase",
                    "sentinel.start_time",
                    "sentinel.stop_time",
                    "sentinel.sensing_time",
                    "sentinel.ascending_node_time",
                    "sentinel.cycle_number",
                    "sentinel.relative_orbit_number",
                    "sentinel.absolute_orbit_number",
                    "sentinel.orbit_state_vector",
                    "sentinel.position",
                    "sentinel.velocity",
                    "sentinel.attitude",
                    "sentinel.roll",
                    "sentinel.pitch",
                    "sentinel.yaw",
                    "sentinel.instrument_mode",
                    "sentinel.instrument_swath",
                    "sentinel.polarisation",
                    "sentinel.antenna_pointing",
                    "sentinel.look_direction",
                    "sentinel.incidence_angle",
                    "sentinel.incidence_angle_mid",
                    "sentinel.incidence_angle_near",
                    "sentinel.incidence_angle_far",
                    "sentinel.acquisition_mode",
                    "sentinel.beam_id",
                    "sentinel.swath_id",
                    "sentinel.footprint",
                    "sentinel.bounds",
                    "sentinel.center",
                    "sentinel.gml_footprint",
                    "sentinel.wkt_footprint",
                    "sentinel.data_slice_number",
                    "sentinel.number_of_samples",
                    "sentinel.number_of_lines",
                    "sentinel.sample_type",
                    "sentinel.sample_bit_width",
                    "sentinel.compression",
                    "sentinel.noise_calibration",
                    "sentinel.noise_vector",
                    "sentinel.range_spectrum_noise",
                    "sentinel.azimuth_spectrum_noise",
                    "sentinel.radiometric_calibration",
                    "sentinel.calibration_constant",
                    "sentinel.sigma0",
                    "sentinel.beta0",
                    "sentinel.gamma0",
                    "sentinel.dn",
                    "sentinel.speckle_filter",
                    "sentinel.orthorectification",
                    "sentinel.dem_name",
                    "sentinel.dem_resampling",
                    "sentinel.dem_ellipsoid",
                    "sentinel.geoid_model",
                    "sentinel.mgrs_latitude_band",
                    "sentinel.mgrs_square_id",
                    "sentinel.mgrs_tile_id",
                    "sentinel.tile_id",
                    "sentinel.cloud_mask",
                    "sentinel.cloud_coverage",
                    "sentinel.cloud_probability",
                    "sentinel.scene_classification",
                    "sentinel.snow_mask",
                    "sentinel.water_mask",
                    "sentinel.land_mask",
                    "sentinel.nodata_mask",
                    "sentinel.saturated_mask",
                    "sentinel.detector_id",
                    "sentinel.detector_footprint",
                    "sentinel.sensor_azimuth",
                    "sentinel.sensor_zenith",
                    "sentinel.sun_azimuth",
                    "sentinel.sun_zenith",
                    "sentinel.relative_azimuth",
                    "sentinel.time_difference",
                    "sentinel.ground_range_resolution",
                    "sentinel.azimuth_resolution",
                    "sentinel.range_resolution",
                    "sentinel.pixel_spacing",
                    "sentinel.ground_sample_distance",
                    "sentinel.swath_width",
                    "sentinel.total_size",
                    "sentinel.product_size",
                    "sentinel.manifest_size",
                    "sentinel.checksum",
                    "sentinel.checksum_algorithm",
                    "sentinel.thumbnail",
                    "sentinel.preview_image",
                    "sentinel.preview_quality",
                    "sentinel.preview_mode",
                    "sentinel.quality_assessment",
                    "sentinel.quality_indicators",
                    "sentinel.classification",
                    "sentinel.classification_quality",
                    "sentinel.band_id",
                    "sentinel.band_name",
                    "sentinel.band_wavelength",
                    "sentinel.band_width",
                    "sentinel.band_resolution",
                    "sentinel.band_scale",
                    "sentinel.band_offset",
                    "sentinel.band_unit",
                    "sentinel.spectral_response",
                    "sentinel.central_wavelength",
                    "sentinel.band_characteristics",
                    "sentinel.cubic_coefficient",
                    "sentinel.s2_msi_crc",
                    "sentinel.s2_msi_image_template",
                    "sentinel.s2_msi_tile_template",
                    "sentinel.s2_msi_granule_template",
                    "sentinel.generation_time",
                    "sentinel.processing_baseline",
                    "sentinel.processing_software_version",
                    "sentinel.parent_id",
                    "sentinel.s2_datastrip_id",
                    "sentinel.s2_tile_id",
                    "sentinel.s2_datastrip_metadata",
                    "sentinel.s2_tile_metadata",
                    "sentinel.gipp_filename",
                    "sentinel.gipp_l1_version",
                    "sentinel.gipp_type",
                    "sentinel.aot_quantile",
                    "sentinel.aot_retrieval",
                    "sentinel.wvp_quantile",
                    "sentinel.ec",
                    "sentinel.l2a_product_id",
                    "sentinel.l2a_granule_id",
                    "sentinel.l2a_tile_id",
                ],
                "count": 140,
            },
            "planet_labs": {
                "description": "PlanetScope and SkySat satellite imagery metadata",
                "reference": "https://developers.planet.com/",
                "fields": [
                    "planet.product_id",
                    "planet.product_bundle",
                    "planet.item_type",
                    "planet.catalog_id",
                    "planet.acquired_at",
                    "planet.acquisition_date",
                    "planet.acquisition_time",
                    "planet.satellite_id",
                    "planet.satellite_name",
                    "planet.ground_control_points_model",
                    "planet.ground_control_points_verify",
                    "planet.horizontal_accuracy",
                    "planet.vertical_accuracy",
                    "planet.geometric_accuracy",
                    "planet.cloud_cover",
                    "planet.ground_sample_distance",
                    "planet.pixel_resolution",
                    "planet.pixel_size",
                    "planet.pixel_type",
                    "planet.band_order",
                    "planet.sensor_band_map",
                    "planet.spectra_response",
                    "planet.band_name",
                    "planet.band_center",
                    "planet.band_width",
                    "planet.band_order",
                    "planet.nir_band",
                    "planet.red_band",
                    "planet.green_band",
                    "planet.blue_band",
                    "planet.alpha_band",
                    "planet.pan_band",
                    "planet.solar_azimuth",
                    "planet.solar_elevation",
                    "planet.sun_elevation",
                    "planet.sun_azimuth",
                    "planet.view_angle",
                    "planet.off_nadir_angle",
                    "planet.pitch",
                    "planet.roll",
                    "planet.yaw",
                    "planet.attitude_quaternion",
                    "planet.attitude_euler",
                    "planet.attitude_rate",
                    "planet.velocity_vector",
                    "planet.position",
                    "planet.velocity",
                    "planet.nadir_latitude",
                    "planet.nadir_longitude",
                    "planet.nadir_altitude",
                    "planet.footprint",
                    "planet.center_latitude",
                    "planet.center_longitude",
                    "planet.gsd",
                    "planet.gsd_ceres",
                    "planet.azimuth_angle",
                    "planet.incidence_angle",
                    "planet.azimuth_angle",
                    "planet.compression",
                    "planet.image_quality",
                    "planet.light_id",
                    "planet.scene_id",
                    "planet.frame_id",
                    "planet.capture_id",
                    "planet.camera_id",
                    "planet.camera_orientation",
                    "planet.camera_version",
                    "planet.lens_id",
                    "planet.focal_length",
                    "planet.f_stop",
                    "planet.integration_time",
                    "planet.gain",
                    "planet.analog_gain",
                    "planet.digital_gain",
                    "planet.exposure_time",
                    "planet.aperture",
                    "planet.iso",
                    "planet.radiometric_calibration",
                    "planet.radiometric_scale_factor",
                    "planet.radiometric_offset",
                    "planet.radiometric_units",
                    "planet.reflectance_gain",
                    "planet.reflectance_offset",
                    "planet.reflectance_units",
                    "planet.temperature",
                    "planet.temperature_gain",
                    "planet.dark_current",
                    "planet.flat_field",
                    "planet.defect_map",
                    "planet.blemish_map",
                    "planet.pixel_defect_map",
                    "planet.line_defect_map",
                    "planet.column_defect_map",
                    "planet.bad_pixel_replacement",
                    "planet.cosmic_ray_filter",
                    "planet.cosmic_ray_rejection",
                    "planet.noise_reduction",
                    "planet.sharpening",
                    "planet.sharpening_factor",
                    "planet.pan_sharpen_method",
                    "planet.pan_sharpen_weights",
                    "planet.color_correction",
                    "planet.white_balance",
                    "planet.manual_white_balance",
                    "planet.auto_white_balance",
                    "planet.tone_mapping",
                    "planet.gamma_correction",
                    "planet.contrast",
                    "planet.saturation",
                    "planet.vignetting_correction",
                    "planet.distortion_correction",
                    "planet.lens_distortion",
                    "planet.affine_transform",
                    "planet.rpc00",
                    "planet.rpc01",
                    "planet.rpc02",
                    "planet.rpc03",
                    "planet.rpc04",
                    "planet.rpc05",
                    "planet.rpc06",
                    "planet.rpc07",
                    "planet.rpc08",
                    "planet.rpc09",
                    "planet.rpc10",
                    "planet.rpc11",
                    "planet.rpc12",
                    "planet.rpc13",
                    "planet.rpc14",
                    "planet.rpc15",
                    "planet.rpc16",
                    "planet.rpc17",
                    "planet.rpc18",
                    "planet.rpc19",
                    "planet.rpc20",
                    "planet.updatable_metadata",
                    "planet.license_type",
                    "planet.license_id",
                    "planet.data_space",
                    "planet.security_classification",
                    "planet.compression_type",
                    "planet.orientation",
                    "planet.time_reference",
                    "planet.coordinated_utc",
                    "planet.ground_control_points",
                ],
                "count": 100,
            },
        },
        "totals": {
            "categories": 7,
            "total_fields": 940,
        }
    }

    return INVENTORY


def main():
    print("=" * 70)
    print("SATELLITE AND SCIENTIFIC REMOTE SENSING METADATA FIELD INVENTORY")
    print("=" * 70)
    print()

    inventory = generate_satellite_inventory()

    print(f"Generated: {inventory['generated_at']}")
    print(f"Categories: {inventory['totals']['categories']}")
    print(f"Total Fields: {inventory['totals']['total_fields']:,}")
    print()

    print("FIELD COUNTS BY CATEGORY:")
    print("-" * 50)
    for cat_name, cat_data in sorted(inventory['categories'].items(), key=lambda x: x[1]['count'], reverse=True):
        ref = cat_data.get('reference', '')[:40]
        print(f"  {cat_name:30s}: {cat_data['count']:>4}  [{ref}]")

    output_dir = Path("dist/satellite_inventory")
    output_dir.mkdir(parents=True, exist_ok=True)

    output_file = output_dir / "satellite_inventory.json"
    output_file.write_text(json.dumps(inventory, indent=2, sort_keys=True), encoding="utf-8")
    print()
    print(f"Wrote: {output_file}")

    summary = {
        "generated_at": inventory["generated_at"],
        "source": inventory["source"],
        "description": inventory["description"],
        "totals": inventory["totals"],
        "field_counts_by_category": {}
    }

    for cat_name, cat_data in inventory["categories"].items():
        summary["field_counts_by_category"][cat_name] = {
            "description": cat_data["description"],
            "count": cat_data["count"],
            "reference": cat_data.get("reference", "N/A")
        }

    summary_file = output_dir / "satellite_summary.json"
    summary_file.write_text(json.dumps(summary, indent=2), encoding="utf-8")
    print(f"Wrote: {summary_file}")


if __name__ == "__main__":
    main()
