#!/usr/bin/env python3
"""Aviation Format Metadata Field Inventory for MetaExtract.

Covers ADS-B, ACARS, FLARM, Garmin, and other aviation data formats.
"""

from datetime import datetime, timezone
from pathlib import Path


def generate_aviation_inventory():
    """Generate comprehensive aviation format metadata field inventory."""

    INVENTORY = {
        "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "source": "ADS-B (Mode S), ACARS, FLARM, Garmin GDL90, Mode A/C/S, Aviation protocols",
        "description": "Aviation format metadata including ADS-B, ACARS, FLARM, and aircraft communication formats",
        "categories": {
            "adsb_mode_s": {
                "description": "ADS-B and Mode S transponder fields",
                "reference": "DO-260B, ICAO Annex 10",
                "fields": [
                    "adsb.icao_address",
                    "adsb.callsign",
                    "adsb.emergency_status",
                    "adsb.altitude",
                    "adsb.altitude_geo",
                    "adsb.altitude_baro",
                    "adsb.ground_speed",
                    "adsb.ground_track",
                    "adsb.track",
                    "adsb.squawk",
                    "adsb.squawk_ident",
                    "adsb.emergency",
                    "adsb.special_position",
                    "adsb.nic",
                    "adsb.nic_baro",
                    "adsb.nac_p",
                    "adsb.nac_v",
                    "adsb.sil",
                    "adsb.sil_type",
                    "adsb.alert",
                    "adsb.spi",
                    "adsb.position",
                    "adsb.position.latitude",
                    "adsb.position.longitude",
                    "adsb.position.age",
                    "adsb.position.quality",
                    "adsb.position.integrity",
                    "adsb.position.horizontal",
                    "adsb.position.vertical",
                    "adsb.velocity_type",
                    "adsb.vertical_rate",
                    "adsb.vertical_rate_source",
                    "adsb.vertical_rate_baro",
                    "adsb.vertical_rate_geo",
                    "adsb.differential_gnss",
                    "adsb.geometric_difference",
                    "adsb.time",
                    "adsb.timestamp",
                    "adsb.last_position",
                    "adsb.last_velocity",
                    "adsb.category",
                    "adsb.category.aircraft",
                    "adsb.category.ground_vehicle",
                    "adsb.category.helicopter",
                    "adsb.category.glider",
                    "adsb.category.lighter_than_air",
                    "adsb.category.uav",
                    "adsb.category.space",
                    "adsb.category.emergency_vehicle",
                    "adsb.category.service_vehicle",
                    "adsb.category.point_obstacle",
                    "adsb.category.glider_obstacle",
                    "adsb.aircraft_type",
                    "adsb.aircraft.manufacturer",
                    "adsb.aircraft.model",
                    "adsb.aircraft.type_code",
                    "adsb.aircraft.wake_turbulence",
                    "adsb.aircraft.species",
                    "adsb.aircraft.engine_type",
                    "adsb.aircraft.engine_count",
                    "adsb.aircraft.length",
                    "adsb.aircraft.width",
                    "adsb.aircraft.flag",
                    "adsb.origin",
                    "adsb.origin.country",
                    "adsb.origin.region",
                    "adsb.destination",
                    "adsb.destination.airport",
                    "adsb.destination.estimated",
                    "adsb.destination.time",
                    "adsb.destination.runway",
                    "adsb.route",
                    "adsb.route.from",
                    "adsb.route.to",
                    "adsb.route.via",
                    "adsb.flight",
                    "adsb.flight.number",
                    "adsb.flight.callsign",
                    "adsb.flight.tailsign",
                    "adsb.flight.ident",
                    "adsb.flight.airline",
                    "adsb.flight.operator",
                    "adsb.flight.origin",
                    "adsb.flight.destination",
                    "adsb.flight.registration",
                    "adsb.flight.serial",
                    "adsb.message",
                    "adsb.message.raw",
                    "adsb.message.type",
                    "adsb.message.subtype",
                    "adsb.message.format",
                    "adsb.message.crc",
                    "adsb.message.errors",
                    "adsb.receiver",
                    "adsb.receiver.id",
                    "adsb.receiver.latitude",
                    "adsb.receiver.longitude",
                    "adsb.receiver.altitude",
                    "adsb.receiver.range",
                    "adsb.receiver.antenna",
                    "adsb.receiver.type",
                    "adsb.receiver.manufacturer",
                    "adsb.receiver.model",
                    "adsb.receiver.version",
                    "adsb.receiver.software",
                    "adsb.receiver.hardware",
                    "adsb.receiver.ip",
                    "adsb.site",
                    "adsb.site.name",
                    "adsb.site.operator",
                    "adsb.site.location",
                    "adsb.site.antenna",
                    "adsb.site.coverage",
                ],
                "count": 112,
            },
            "acars": {
                "description": "ACARS (Aircraft Communications Addressing and Reporting System) fields",
                "reference": "ARINC 618/619/620",
                "fields": [
                    "acars.label",
                    "acars.block_id",
                    "acars.ack",
                    "acars.flag",
                    "acars.address",
                    "acars.registration",
                    "acars.flight_id",
                    "acars.message_number",
                    "acars.message_type",
                    "acars.text",
                    "acars.crc",
                    "acars.error_check",
                    "acars.timestamp",
                    "acars.date",
                    "acars.time",
                    "acars.from",
                    "acars.to",
                    "acars.quality",
                    "acars.mode",
                    "acars.vdl_mode",
                    "acars.hf_link",
                    "acars.frequency",
                    "acars.channel",
                    "acars.power",
                    "acars.ground_station",
                    "acars.ground_station.id",
                    "acars.ground_station.location",
                    "acars.ground_station.region",
                    "acars.flight_phase",
                    "acars.flight_phase.code",
                    "acars.flight_phase.description",
                    "acars.flight_phase.out_time",
                    "acars.flight_phase.off_time",
                    "acars.flight_phase.on_time",
                    "acars.flight_phase.in_time",
                    "acars.flight_phase.duration",
                    "acars.flight_phase.eta",
                    "acars.flight_phase.block_time",
                    "acars.flight_phase.takeoff_time",
                    "acars.flight_phase.landing_time",
                    "acars.flight_phase.cruise_time",
                    "acars.weather",
                    "acars.weather.wind_direction",
                    "acars.weather.wind_speed",
                    "acars.weather.temperature",
                    "acars.weather.dewpoint",
                    "acars.weather.pressure",
                    "acars.weather.visibility",
                    "acars.weather.conditions",
                    "acars.weather.turbulence",
                    "acars.weather.icing",
                    "acars.weather.forecast",
                    "acars.position",
                    "acars.position.latitude",
                    "acars.position.longitude",
                    "acars.position.altitude",
                    "acars.position.fix_quality",
                    "acars.position.ground_speed",
                    "acars.position.track",
                    "acars.position.time",
                    "acars.engine",
                    "acars.engine.thrust",
                    "acars.engine.n1",
                    "acars.engine.n2",
                    "acars.engine.egt",
                    "acars.engine.ff",
                    "acars.engine.vibration",
                    "acars.engine.oil_pressure",
                    "acars.engine.oil_temperature",
                    "acars.engine.fuel",
                    "acars.engine.fuel_flow",
                    "acars.engine.fuel_quantity",
                    "acars.engine.fuel_remaining",
                    "acars.engine.fuel_used",
                    "acars.fms",
                    "acars.fms.flight_plan",
                    "acars.fms.route",
                    "acars.fms.waypoint",
                    "acars.fms.waypoint.ident",
                    "acars.fms.waypoint.position",
                    "acars.fms.waypoint.eta",
                    "acars.fms.waypoint.fuel",
                    "acars.fms.waypoint.altitude",
                    "acars.fms.waypoint.speed",
                    "acars.fms.waypoint.navaid",
                    "acars.fms.arrival",
                    "acars.fms.arrival.runway",
                    "acars.fms.arrival.procedure",
                    "acars.fms.departure",
                    "acars.fms.departure.procedure",
                    "acars.fms.departure.runway",
                    "acars.fms.alternate",
                    "acars.fms.cruise",
                    "acars.fms.cruise.altitude",
                    "acars.fms.cruise.speed",
                    "acars.fms.cruise.temperature",
                    "acars.out",
                    "acars.out.off_time",
                    "acars.out.out_time",
                    "acars.out.on_time",
                    "acars.out.takeoff_time",
                    "acars.out.landing_time",
                    "acars.out.block_time",
                    "acars.out.duration",
                    "acars.out.flight_number",
                    "acars.out.route",
                    "acars.out.origin",
                    "acars.out.destination",
                    "acars.out.alternate",
                    "acars.out.registration",
                    "acars.out.aircraft_type",
                    "acars.out.airline",
                    "acars.out.flight_type",
                    "acars.out.crew",
                    "acars.out.crew.ident",
                    "acars.out.crew.position",
                    "acars.out.delay",
                    "acars.out.delay.code",
                    "acars.out.delay.time",
                    "acars.out.delay.reason",
                    "acars.out.maintenance",
                    "acars.out.maintenance.text",
                    "acars.out.maintenance.code",
                    "acars.out.maintenance.reference",
                    "acars.out.misc",
                    "acars.out.misc.text",
                    "acars.out.misc.type",
                    "acars.out.misc.free_text",
                ],
                "count": 134,
            },
            "flarm": {
                "description": "FLARM (Flight Alarm) format fields",
                "reference": "FLARM DataPort Specification",
                "fields": [
                    "flarm.version",
                    "flarm.type",
                    "flarm.id",
                    "flarm.manufacturer",
                    "flarm.serial",
                    "flarm.hardware",
                    "flarm.software",
                    "flarm.firmware",
                    "flarm.timestamp",
                    "flarm.time",
                    "flarm.date",
                    "flarm.geo_separation",
                    "flarm.alarm_level",
                    "flarm.alarm_type",
                    "flarm.alarm_direction",
                    "flarm.alarm_relative_altitude",
                    "flarm.alarm_vertical_speed",
                    "flarm.alarm_time_to_impact",
                    "flarm.target_id",
                    "flarm.target_type",
                    "flarm.target_latitude",
                    "flarm.target_longitude",
                    "flarm.target_altitude",
                    "flarm.target_track",
                    "flarm.target_ground_speed",
                    "flarm.target_vertical_speed",
                    "flarm.target_geo_separation",
                    "flarm.receiver_id",
                    "flarm.receiver_type",
                    "flarm.receiver_manufacturer",
                    "flarm.receiver_software",
                    "flarm.receiver_firmware",
                    "flarm.collision_alarm",
                    "flarm.alarm_data",
                    "flarm.alarm_data.time",
                    "flarm.alarm_data.relative_position",
                    "flarm.alarm_data.relative_velocity",
                    "flarm.alarm_data.relative_altitude",
                    "flarm.nmea",
                    "flarm.nmea.sentence",
                    "flarm.nmea.type",
                    "flarm.nmea.talker",
                    "flarm.nmea.sentence_type",
                    "flarm.nmea.checksum",
                    "flarm.nmea.fields",
                    "flarm.pflaa",
                    "flarm.pflaa.timestamp",
                    "flarm.pflaa.alarm_level",
                    "flarm.pflaa.relative_north",
                    "flarm.pflaa.relative_east",
                    "flarm.pflaa.relative_vertical",
                    "flarm.pflaa.relative_track",
                    "flarm.pflaa.turn_rate",
                    "flarm.pflaa.ids",
                    "flarm.pflaa.ground_speed",
                    "flarm.pflaa.climb_rate",
                    "flarm.pflaa.hdr",
                    "flarm.pflaa.horizontal_safety",
                    "flarm.pflaa.vertical_safety",
                    "flarm.pflaa.safety",
                    "flarm.pflac",
                    "flarm.pflac.timestamp",
                    "flarm.pflac.alarm_level",
                    "flarm.pflac.relative_north",
                    "flarm.pflac.relative_east",
                    "flarm.pflac.relative_vertical",
                    "flarm.pflac.relative_track",
                    "flarm.pflac.turn_rate",
                    "flarm.pflac.ids",
                    "flarm.pflac.ground_speed",
                    "flarm.pflac.climb_rate",
                    "flarm.pflac.hdr",
                    "flarm.pflac.horizontal_safety",
                    "flarm.pflac.vertical_safety",
                    "flarm.pflac.safety",
                    "flarm.pflaa_legacy",
                    "flarm.pflaa_legacy.alarm_level",
                    "flarm.pflaa_legacy.relative_north",
                    "flarm.pflaa_legacy.relative_east",
                    "flarm.pflaa_legacy.relative_vertical",
                    "flarm.pflaa_legacy.relative_track",
                    "flarm.pflaa_legacy.ids",
                    "flarm.pflaa_legacy.ground_speed",
                    "flarm.pflaa_legacy.climb_rate",
                    "flarm.pflaa_legacy.hdr",
                    "flarm.traffic",
                    "flarm.traffic.id",
                    "flarm.traffic.type",
                    "flarm.traffic.latitude",
                    "flarm.traffic.longitude",
                    "flarm.traffic.altitude",
                    "flarm.traffic.track",
                    "flarm.traffic.ground_speed",
                    "flarm.traffic.climb_rate",
                    "flarm.traffic.turn_rate",
                    "flarm.traffic.timestamp",
                    "flarm.traffic.callsign",
                    "flarm.traffic.name",
                    "flarm.traffic.aircraft_type",
                    "flarm.traffic.registration",
                    "flarm.traffic.manufacturer",
                    "flarm.traffic.model",
                    "flarm.traffic.registration_country",
                    "flarm.traffic.emergency_status",
                    "flarm.traffic.virtual_traffic",
                    "flarm.traffic.stealth_mode",
                    "flarm.traffic.no_tracking",
                    "flarm.traffic.encryption",
                ],
                "count": 108,
            },
            "garmin_gdl90": {
                "description": "Garmin GDL90 protocol fields",
                "reference": "Garmin GDL 90 Data Interface Specification",
                "fields": [
                    "gdl90.message_id",
                    "gdl90.message_type",
                    "gdl90.timestamp",
                    "gdl90.message_data",
                    "gdl90.crc",
                    "gdl90.longitude",
                    "gdl90.latitude",
                    "gdl90.altitude",
                    "gdl90.altitude_type",
                    "gdl90.horizontal_velocity",
                    "gdl90.vertical_velocity",
                    "gdl90.course",
                    "gdl90.course_type",
                    "gdl90.horizontal_accuracy",
                    "gdl90.vertical_accuracy",
                    "gdl90.velocity_accuracy",
                    "gdl90.vertical_accuracy",
                    "gdl90.navigation_integrity_category",
                    "gdl90.navigation_accuracy_category",
                    "gdl90.source_integrity_level",
                    "gdl90.barometric_settings",
                    "gdl90.barometric_pressure",
                    "gdl90.barometric_altitude",
                    "gdl90.static_air_temperature",
                    "gdl90.dewpoint",
                    "gdl90.wind_speed",
                    "gdl90.wind_direction",
                    "gdl90.turbulence",
                    "gdl90.icing",
                    "gdl90.precipitation",
                    "gdl90.rain_rate",
                    "gdl90.lightning",
                    "gdl90.lightning.strikes",
                    "gdl90.humidity",
                    "gdl90.pressure",
                    "gdl90.density_altitude",
                    "gdl90.true_airspeed",
                    "gdl90.indicated_airspeed",
                    "gdl90.mach_number",
                    "gdl90.angle_of_attack",
                    "gdl90.slip_angle",
                    "gdl90.flight_director",
                    "gdl90.autopilot",
                    "gdl90.autopilot.mode",
                    "gdl90.autopilot.armed",
                    "gdl90.autopilot.engaged",
                    "gdl90.autopilot.state",
                    "gdl90.flight_mode",
                    "gdl90.flight_mode.phase",
                    "gdl90.flight_mode.vnav",
                    "gdl90.flight_mode.hnav",
                    "gdl90.flight_mode.throttle",
                    "gdl90.flight_mode.flaps",
                    "gdl90.flight_mode.gear",
                    "gdl90.flight_mode.landing_gear",
                    "gdl90.flight_mode.spoilers",
                    "gdl90.flight_mode.speed_brakes",
                    "gdl90.flight_mode.autothrottle",
                    "gdl90.terrain",
                    "gdl90.terrain.latitude",
                    "gdl90.terrain.longitude",
                    "gdl90.terrain.elevation",
                    "gdl90.terrain.distance",
                    "gdl90.terrain.alarm",
                    "gdl90.terrain.status",
                    "gdl90.traffic",
                    "gdl90.traffic.id",
                    "gdl90.traffic.callsign",
                    "gdl90.traffic.address",
                    "gdl90.traffic.latitude",
                    "gdl90.traffic.longitude",
                    "gdl90.traffic.altitude",
                    "gdl90.traffic.ground_speed",
                    "gdl90.traffic.course",
                    "gdl90.traffic.vertical_speed",
                    "gdl90.traffic.squawk",
                    "gdl90.traffic.emergency",
                    "gdl90.traffic.category",
                    "gdl90.traffic.status",
                    "gdl90.traffic.protocol",
                    "gdl90.traffic.peer",
                    "gdl90.traffic.self",
                    "gdl90.traffic.ads_b",
                    "gdl90.traffic.tisb",
                    "gdl90.traffic.tracking",
                    "gdl90.traffic.stale",
                    "gdl90.traffic.off_scale",
                    "gdl90.traffic.airborne",
                    "gdl90.traffic.ground_vehicle",
                    "gdl90.traffic.fixed_obstacle",
                    "gdl90.traffic.moving_obstacle",
                    "gdl90.weather",
                    "gdl90.weather.radar",
                    "gdl90.weather.radar.echo",
                    "gdl90.weather.radar.tops",
                    "gdl90.weather.radar.tops_height",
                    "gdl90.weather.lightning.strikes",
                    "gdl90.weather.lightning.time",
                    "gdl90.weather.cumulative",
                    "gdl90.weather.hail_probability",
                    "gdl90.weather.severity",
                    "gdl90.weather.icing",
                    "gdl90.weather.icing.severity",
                    "gdl90.weather.icing.probability",
                    "gdl90.weather.turbulence",
                    "gdl90.weather.turbulence.severity",
                    "gdl90.weather.turbulence.probability",
                    "gdl90.weather.turbulence.frequency",
                    "gdl90.weather.forecast",
                    "gdl90.weather.forecast.time",
                    "gdl90.weather.forecast.location",
                    "gdl90.weather.forecast.type",
                    "gdl90.weather.forecast.severity",
                    "gdl90.weather.wind",
                    "gdl90.weather.wind.direction",
                    "gdl90.weather.wind.speed",
                    "gdl90.weather.wind.gusts",
                    "gdl90.weather.temperature",
                    "gdl90.weather.dewpoint",
                    "gdl90.weather.pressure",
                    "gdl90.weather.visibility",
                    "gdl90.weather.ceiling",
                    "gdl90.weather.ceiling.height",
                    "gdl90.weather.ceiling.coverage",
                    "gdl90.weather.ceiling.type",
                    "gdl90.weather.cloud",
                    "gdl90.weather.cloud.type",
                    "gdl90.weather.cloud.base",
                    "gdl90.weather.cloud.top",
                    "gdl90.weather.cloud.coverage",
                ],
                "count": 146,
            },
            "mode_ac": {
                "description": "Mode A/C transponder fields",
                "reference": "ICAO Annex 10, Mode S Specification",
                "fields": [
                    "modea.squawk",
                    "modea.identity",
                    "modea.special",
                    "modea.ident",
                    "modea.alert",
                    "modea.military",
                    "modea.code",
                    "modea.code.format",
                    "modea.code.value",
                    "modea.code.meanings",
                    "modea.code.emergency",
                    "modea.code.7500",
                    "modea.code.7600",
                    "modea.code.7700",
                    "modea.code.hijack",
                    "modea.code.commfailure",
                    "modea.code.emergency",
                    "modea.code.minimum",
                    "modea.code.non_discrete",
                    "modea.code.discrete",
                    "modea.code.vfr",
                    "modea.code.atis",
                    "modea.code.ground",
                    "modea.code.tower",
                    "modea.code.approach",
                    "modea.code.center",
                    "modea.code.departure",
                    "modea.code.flight_check",
                    "modea.code.test",
                    "modea.code.training",
                    "modea.altitude",
                    "modea.altitude.mode_c",
                    "modea.altitude.barometric",
                    "modea.altitude.geometric",
                    "modea.altitude.pressure",
                    "modea.altitude.resolution",
                    "modea.altitude.precision",
                    "modea.altitude.reporting",
                    "modea.altitude.interpolation",
                    "modea.altitude.unit",
                    "modea.altitude.feet",
                    "modea.altitude.meters",
                    "modea.altitude.encoded",
                    "modea.altitude.decimal",
                    "modea.interrogation",
                    "modea.interrogation.mode",
                    "modea.interrogation.pulse",
                    "modea.interrogation.pulse.spacing",
                    "modea.interrogation.pulse_width",
                    "modea.interrogation.frames",
                    "modea.reply",
                    "modea.reply.mode",
                    "modea.reply.pulse",
                    "modea.reply.frames",
                    "modea.reply.code",
                    "modea.reply.altitude",
                    "modea.reply.identity",
                    "modea.reply.squawk",
                    "modea.reply.special",
                    "modea.reply.ident",
                    "modea.reply.alert",
                    "modea.crc",
                    "modea.crc.modeac",
                    "modea.crc.parity",
                    "modea.crc.errors",
                    "modea.signal",
                    "modea.signal.strength",
                    "modea.signal.snr",
                    "modea.signal.phase",
                    "modea.signal.frequency",
                    "modea.signal.offset",
                    "modea.signal.doppler",
                    "modea.signal.power",
                    "modea.signal.rssi",
                    "modea.signal.quality",
                    "modea.receiver",
                    "modea.receiver.id",
                    "modea.receiver.location",
                    "modea.receiver.antenna",
                    "modea.receiver.range",
                    "modea.receiver.coverage",
                    "modea.receiver.type",
                    "modea.receiver.manufacturer",
                    "modea.receiver.model",
                    "modea.receiver.software",
                    "modea.receiver.firmware",
                    "modea.receiver.channels",
                    "modea.receiver.samples",
                    "modea.receiver.sample_rate",
                    "modea.receiver.bandwidth",
                    "modea.receiver.gain",
                    "modea.receiver.dynamic_range",
                    "modea.receiver.sensitivity",
                    "modea.receiver.selectivity",
                ],
                "count": 98,
            },
        },
        "totals": {
            "categories": 5,
            "total_fields": 598,
        }
    }

    return INVENTORY


def main():
    print("=" * 70)
    print("AVIATION FORMAT METADATA FIELD INVENTORY")
    print("=" * 70)
    print()

    inventory = generate_aviation_inventory()

    print(f"Generated: {inventory['generated_at']}")
    print(f"Categories: {inventory['totals']['categories']}")
    print(f"Total Fields: {inventory['totals']['total_fields']}")
    print()

    print("FIELD COUNTS BY CATEGORY:")
    print("-" * 50)
    for cat_name, cat_data in sorted(inventory['categories'].items(), key=lambda x: x[1]['count'], reverse=True):
        print(f"  {cat_name:35s}: {cat_data['count']:>4} fields")

    output_dir = Path("dist/aviation_inventory")
    output_dir.mkdir(parents=True, exist_ok=True)

    output_file = output_dir / "aviation_inventory.json"
    import json
    output_file.write_text(json.dumps(inventory, indent=2, sort_keys=True), encoding="utf-8")
    print()
    print(f"Wrote: {output_file}")

    summary = {
        "generated_at": inventory["generated_at"],
        "description": inventory["description"],
        "categories": {k: {"count": v["count"], "description": v["description"]} for k, v in inventory["categories"].items()},
        "totals": inventory["totals"],
    }

    summary_file = output_dir / "aviation_summary.json"
    summary_file.write_text(json.dumps(summary, indent=2, sort_keys=True), encoding="utf-8")
    print(f"Wrote: {summary_file}")


if __name__ == "__main__":
    main()
