#!/usr/bin/env python3
"""Aerospace and Satellite Operations Metadata Field Inventory.

Covers satellite operations, spacecraft systems, CCSDS protocols,
ADCS parameters, mission planning, and ground segment metadata.
"""

from datetime import datetime, timezone
import json
from pathlib import Path
from typing import Dict, List, Any


def generate_aerospace_inventory():
    """Generate comprehensive aerospace and satellite operations metadata field inventory."""

    INVENTORY = {
        "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "source": "CCSDS 131.0-B, ECSS 70, NASA Mission Operations, ESA Flight Operations",
        "description": "Aerospace and satellite operations metadata fields for spacecraft mission data",
        "categories": {
            "satellite_operations": {
                "description": "Satellite TT&C, orbit parameters, and attitude control",
                "reference": "CCSDS 231.0-B, NASA 5322.1-R",
                "fields": [
                    "satellite.norad_cat_id",
                    "satellite.international_designator",
                    "satellite.cospar_id",
                    "satellite.name",
                    "satellite.tle_line1",
                    "satellite.tle_line2",
                    "satellite.tle_epoch",
                    "satellite.tle_epoch_microseconds",
                    "satellite.tle_mean_motion",
                    "satellite.tle_mean_motion_dot",
                    "satellite.tle_mean_motion_ddot",
                    "satellite.tle_bstar",
                    "satellite.tle_element_number",
                    "satellite.tle_revolution_number",
                    "satellite.tle_checksum_line1",
                    "satellite.tle_checksum_line2",
                    "satellite.orbit_semi_major_axis",
                    "satellite.orbit_eccentricity",
                    "satellite.orbit_inclination",
                    "satellite.orbit_raan",
                    "satellite.orbit_arg_perigee",
                    "satellite.orbit_true_anomaly",
                    "satellite.orbit_mean_anomaly",
                    "satellite.orbit_period",
                    "satellite.orbit_perigee_altitude",
                    "satellite.orbit_apogee_altitude",
                    "satellite.orbit_mean_altitude",
                    "satellite.orbit_ra_dec",
                    "satellite.orbit_lon_ascending_node",
                    "satellite.orbit_ground_track",
                    "satellite.orbit_inertial_frame",
                    "satellite.orbit_epoch_time",
                    "satellite.orbit_position_vector",
                    "satellite.orbit_velocity_vector",
                    "satellite.orbit_ephemeris_type",
                    "satellite.orbit_maneuvers_planned",
                    "satellite.orbit_maneuvers_executed",
                    "satellite.orbit_decay_rate",
                    "satellite.orbit_lifetime",
                    "satellite.orbit_reentry_prediction",
                    "satellite.orbit_slot_position",
                    "satellite.orbit_constellation_slot",
                    "satellite.ttc_antenna_id",
                    "satellite.ttc_antenna_type",
                    "satellite.ttc_antenna_gain",
                    "satellite.ttc_transmitter_frequency",
                    "satellite.ttc_transmitter_power",
                    "satellite.ttc_receiver_frequency",
                    "satellite.ttc_receiver_sensitivity",
                    "satellite.ttc_modulation_type",
                    "satellite.ttc_data_rate",
                    "satellite.ttc_encoding",
                    "satellite.ttc_frame_sync",
                    "satellite.ttc_subcommutation",
                    "satellite.ttc_command_valid",
                    "satellite.ttc_telemetry_valid",
                    "satellite.ttc_ uplink_status",
                    "satellite.ttc_downlink_status",
                    "satellite.ttc_signal_strength",
                    "satellite.ttc_carrier_lock",
                    "satellite.ttc_symbol_sync",
                    "satellite.ttc_viterbi_enable",
                    "satellite.ttc_reed_solomon_enable",
                    "satellite.ttc_convolutional_code_rate",
                    "satellite.ttc_interleaver_depth",
                    "satellite.ttc_ber",
                    "satellite.ttc_snr",
                    "satellite.ttc_agc_voltage",
                    "satellite.attitude_mode",
                    "satellite.attitude_detumbling",
                    "satellite.attitude_nadir_pointing",
                    "satellite.attitude_sun_pointing",
                    "satellite.attitude_momentum_steering",
                    "satellite.attitude_three_axis_stable",
                    "satellite.attitude_spin_stabilized",
                    "satellite.attitude_bias_momentum",
                    "satellite.attitude_zero_momentum",
                    "satellite.attitude_control_error",
                    "satellite.attitude_reference_frame",
                    "satellite.attitude_roll_error",
                    "satellite.attitude_pitch_error",
                    "satellite.attitude_yaw_error",
                    "satellite.attitude_roll_rate",
                    "satellite.attitude_pitch_rate",
                    "satellite.attitude_yaw_rate",
                    "satellite.attitude_angular_momentum",
                    "satellite.attitude_angular_velocity",
                    "satellite.attitude_torque_command",
                    "satellite.attitude_torque_internal",
                    "satellite.attitude_reaction_wheel_speed",
                    "satellite.attitude_reaction_wheel_rpm",
                    "satellite.attitude_magnetorquer_current",
                    "satellite.attitude_thruster_pulse_count",
                    "satellite.attitude_thruster_on_time",
                    "satellite.attitude_control_cycle",
                    "satellite.attitude_coning_angle",
                    "satellite.attitude_delta_v_expended",
                    "satellite.attitude_delta_v_remaining",
                    "satellite.health_status",
                    "satellite.safe_mode_active",
                    "satellite.safe_mode_cause",
                    "satellite.safe_mode_entry_time",
                    "satellite.safe_mode_recovery_time",
                    "satellite.safe_mode_count",
                    "satellite.fault_detection_count",
                    "satellite.fault_isolation_count",
                    "satellite.fault_recovery_count",
                    "satellite.operational_mode",
                    "satellite.pass_start_time",
                    "satellite.pass_duration",
                    "satellite.pass_max_elevation",
                    "satellite.pass_aos_time",
                    "satellite.pass_los_time",
                    "satellite.pass_tca_time",
                    "satellite.pass_ground_station",
                    "satellite.pass_data_volume",
                    "satellite.pass_command_load",
                    "satellite.pass_telemetry_dump",
                    "satellite.pass_ranging_measured",
                    "satellite.pass_doppler_measured",
                    "satellite.pass_angles_measured",
                ],
                "count": 140,
            },
            "spacecraft_systems": {
                "description": "Power, thermal, propulsion, and communication subsystems",
                "reference": "ECSS E-ST-10C, NASA-HDBK-4002",
                "fields": [
                    "power.generation_total",
                    "power.consumption_total",
                    "power.battery_voltage",
                    "power.battery_current",
                    "power.battery_temperature",
                    "power.battery_state_of_charge",
                    "power.battery_state_of_health",
                    "power.battery_cycle_count",
                    "power.battery_capacity_initial",
                    "power.battery_capacity_current",
                    "power.battery_discharge_depth",
                    "power.battery_charge_current",
                    "power.battery_charge_source",
                    "power.battery_heater_state",
                    "power.solar_array_string_count",
                    "power.solar_array_panel_count",
                    "power.solar_array_area",
                    "power.solar_array_efficiency",
                    "power.solar_array_degradation",
                    "power.solar_array_current",
                    "power.solar_array_voltage",
                    "power.solar_array_temperature",
                    "power.solar_array_power",
                    "power.solar_array_illumination",
                    "power.solar_array_sun_angle",
                    "power.solar_array_pointing_error",
                    "power.power_source_primary",
                    "power.power_source_secondary",
                    "power.power_bus_voltage",
                    "power.power_bus_current",
                    "power.power_bus_ripple",
                    "power.power_distribution_unit",
                    "power.power_switch_status",
                    "power.power_overload_status",
                    "power.power_fuse_status",
                    "power.power_regulator_mode",
                    "power.powerConverter_efficiency",
                    "power.power_sequential_load",
                    "thermal.heater_zone1_state",
                    "thermal.heater_zone2_state",
                    "thermal.heater_zone3_state",
                    "thermal.heater_zone4_state",
                    "thermal.heater_zone5_state",
                    "thermal.heater_duty_cycle",
                    "thermal.thermal_sensor_temperature",
                    "thermal.temperature_internal",
                    "thermal.temperature_external",
                    "thermal.temperature_battery",
                    "thermal.temperature_electronics",
                    "thermal.temperature_instrument",
                    "thermal.temperature_sensor",
                    "thermal.temperature_radiator",
                    "thermal.temperature_amplifier",
                    "thermal.temperature_heater",
                    "thermal.temperature_louvers",
                    "thermal.heat_pipe_temperature",
                    "thermal.heat_pipe_heat_rate",
                    "thermal.thermal_gradient",
                    "thermal.thermal_heater_power",
                    "thermal.thermal_radiator_emissivity",
                    "thermal.thermal_absorptivity",
                    "thermal.thermal_balance",
                    "thermal.thermal_model",
                    "thermal.thermal_control_mode",
                    "thermal.thermal_override",
                    "propulsion.propellant_type",
                    "propulsion.propellant_mass",
                    "propellant_mass_remaining",
                    "propulsion.oxidizer_mass",
                    "propulsion.pressurant_mass",
                    "propulsion.tank_pressure",
                    "propulsion.tank_temperature",
                    "propulsion.thrust_level",
                    "propulsion.thrust_vector",
                    "propulsion.impulse_bits",
                    "propulsion.impulse_total",
                    "propulsion.burn_count",
                    "propulsion.burn_duration",
                    "propulsion.burn_start_time",
                    "propulsion.burn_end_time",
                    "propulsion.burn_delta_v",
                    "propulsion.fuel_consumption",
                    "propulsion.oxidizer_consumption",
                    "propulsion.nozzle_efficiency",
                    "propulsion.thruster_ignition",
                    "propulsion.thruster_valve_cycle",
                    "propulsion.feed_line_pressure",
                    "propulsion.catalyst_bed_temperature",
                    "propulsion.cold_gas_pressure",
                    "propulsion.cold_gas_mass",
                    "propulsion.electric_power",
                    "propulsion.electric_thrust",
                    "propulsion.electric_isp",
                    "propulsion.electric_efficiency",
                    "propulsion.ion_beam_current",
                    "propulsion.ion_beam_voltage",
                    "propulsion.neutralizer_current",
                    "comm.transmitter_frequency",
                    "comm.transmitter_power",
                    "comm.transmitter_status",
                    "comm.transmitter_mode",
                    "comm.transmitter_data_rate",
                    "comm.transmitter_modulation",
                    "comm.transmitter_encoding",
                    "comm.receiver_frequency",
                    "comm.receiver_sensitivity",
                    "comm.receiver_status",
                    "comm.receiver_data_rate",
                    "comm.amplifier_gain",
                    "comm.amplifier_temperature",
                    "comm.amplifier_status",
                    "comm.antenna_id",
                    "comm.antenna_type",
                    "comm.antenna_gain",
                    "comm.antenna_pointing_azimuth",
                    "comm.antenna_pointing_elevation",
                    "comm.antenna_pointing_roll",
                    "comm.antenna polarization",
                    "comm.antenna_axial_ratio",
                    "comm.antenna_sidelobe_level",
                    "comm.antenna_beamwidth",
                    "comm.antenna_efficiency",
                    "comm.antenna_noise_temperature",
                    "comm.link_margin",
                    "comm.link_budget",
                    "comm.bit_error_rate",
                    "comm.frame_error_rate",
                    "comm.packet_loss_rate",
                    "comm.channel_capacity",
                    "comm.throughput",
                    "comm.latency",
                    "comm.jitter",
                    "comm.spread_spectrum_code",
                    "comm.spread_spectrum_rate",
                    "comm.crypto_key_id",
                    "comm.crypto_mode",
                    "comm.encryption_status",
                    "comm.authentication_status",
                ],
                "count": 120,
            },
            "ccsds": {
                "description": "CCSDS packet telemetry, TM/TC, and space link protocols",
                "reference": "CCSDS 131.0-B, 732.0-B, 231.0-B",
                "fields": [
                    "ccsds.packet_id",
                    "ccsds.packet_sequence_control",
                    "ccsds.packet_data_length",
                    "ccsds.packet_version_number",
                    "ccsds.packet_type",
                    "ccsds.secondary_header_flag",
                    "ccsds.app_id",
                    "ccsds.sequence_flags",
                    "ccsds.sequence_count",
                    "ccsds.packet_error_control",
                    "ccsds.primary_header_length",
                    "ccsds.transfer_frame_version_number",
                    "ccsds.spacecraft_id",
                    "ccsds.virtual_channel_id",
                    "ccsds.virtual_channel_frame_count",
                    "ccsds.opaque_data_flag",
                    "ccsds.ground_command_flag",
                    "ccsds.priority_flag",
                    "ccsds.service_type",
                    "ccsds.service_subtype",
                    "ccsds.source_entity_id",
                    "ccsds.destination_entity_id",
                    "ccsds.app_proc_id",
                    "ccsds.sequence_flags",
                    "ccsds.acknowledgment",
                    "ccsds.cadu_sync_marker",
                    "ccsds.cadu_reassembly",
                    "ccsds.vcdu_control_word",
                    "ccsds.vcdu_primary_header",
                    "ccsds.vcdu_secondary_header",
                    "ccsds.frame_error_control",
                    "ccsds.insert_zone_length",
                    "ccsds.insert_zone_data",
                    "ccsds.trailer_size",
                    "ccsds.trailer_error_control",
                    "ccsds.segmentation_flags",
                    "ccsds.segmentation_length",
                    "ccsds.segmentation_sequence",
                    "ccsds.segmentation_first_header",
                    "ccsds.packet_map_channel",
                    "ccsds.multiplexing_mode",
                    "ccsds.Statistical_Decorrelation",
                    "ccsds.packet_rate",
                    "ccsds.packet_size",
                    "ccsds.buffer_occupancy",
                    "ccsds.buffer_overflow",
                    "ccsds.packet_priority",
                    "ccsds.packet_category",
                    "ccsds.packet_generation_time",
                    "ccsds.packet_reception_time",
                    "ccsds.packet_sequence_number",
                    "ccsds.packet_source_id",
                    "ccsds.packet_destination_id",
                    "ccsds.packet_checksum",
                    "ccsds.telemetry_sync_pattern",
                    "ccsds.telemetry_transfer_frame",
                    "ccsds.telemetry_source_packet",
                    "ccsds.telemetry_pus_version",
                    "ccsds.telemetry_space_packet_protocol",
                    "ccsds.telemetry_data_field_header",
                    "ccsds.telemetry_data_source_id",
                    "ccsds.telemetry_sequence_control",
                    "ccsds.telemetry_pus_service_type",
                    "ccsds.telemetry_pus_service_subtype",
                    "ccsds.telemetry_acknowledge_flags",
                    "ccsds.telemetry_error_control",
                    "ccsds.telemetry_quality_indicator",
                    "ccsds.telemetry_spacelink_extension",
                    "ccsds.telemetry_time_reference",
                    "ccsds.telemetry_time_code",
                    "ccsds.telemetry_ground_reception",
                    "ccsds.telemetry_ground_processing",
                    "ccsds.telemetry_onboard_storage",
                    "ccsds.telemetry_playback_status",
                    "ccsds.telemetry_playback_time",
                    "ccsds.telemetry_playback_rate",
                    "ccsds.telemetry_recording_time",
                    "ccsds.telemetry_dump_priority",
                    "ccsds.telemetry_dump_schedule",
                    "ccsds.telemetry_dump_sequence",
                    "ccsds.telemetry_dump_interrupted",
                    "ccsds.command_function_id",
                    "ccsds.command_function_name",
                    "ccsds.command_step_id",
                    "ccsds.command_absolute_relative",
                    "ccsds.command_execution_time",
                    "ccsds.command_acknowledgment",
                    "ccsds.command_progress_report",
                    "ccsds.command_completion_status",
                    "ccsds.command_verification",
                    "ccsds.command_source",
                    "ccsds.command_destination",
                    "ccsds.command_priority",
                    "ccsds.command_counter",
                    "ccsds.command_deferred",
                    "ccsds.command_queue_size",
                    "ccsds.command_queue_status",
                    "ccsds.command_rejection_reason",
                    "ccsds.command_parameter_count",
                    "ccsds.command_parameter_value",
                    "ccsds.command_parameter_name",
                    "ccsds.command_parameter_type",
                    "ccsds.command_parameter_range",
                    "ccsds.command_parameter_units",
                    "ccsds.command_parameter_description",
                ],
                "count": 110,
            },
            "adcs": {
                "description": "Attitude Determination and Control System, quaternion, Euler angles",
                "reference": "CCSDS 504.0-B, NASA SP-8016",
                "fields": [
                    "adcs.quaternion_scalar",
                    "adcs.quaternion_vector",
                    "adcs.quaternion_x",
                    "adcs.quaternion_y",
                    "adcs.quaternion_z",
                    "adcs.quaternion_norm",
                    "adcs.quaternion_rate",
                    "adcs.quaternion_error",
                    "adcs.quaternion_validity",
                    "adcs.quaternion_timestamp",
                    "adcs.euler_roll",
                    "adcs.euler_pitch",
                    "adcs.euler_yaw",
                    "adcs.euler_sequence",
                    "adcs.euler_rotation_matrix",
                    "adcs.euler_axis_angle",
                    "adcs.euler_rate_roll",
                    "adcs.euler_rate_pitch",
                    "adcs.euler_rate_yaw",
                    "adcs.rotation_matrix_element",
                    "adcs.direction_cosine_matrix",
                    "adcs.angular_velocity_body_x",
                    "adcs.angular_velocity_body_y",
                    "adcs.angular_velocity_body_z",
                    "adcs.angular_velocity_inertial",
                    "adcs.angular_momentum_wheel1",
                    "adcs.angular_momentum_wheel2",
                    "adcs.angular_momentum_wheel3",
                    "adcs.angular_momentum_wheel4",
                    "adcs.angular_momentum_total",
                    "adcs.angular_momentum_bias",
                    "adcs.angular_momentum_saturation",
                    "adcs.reaction_wheel_speed",
                    "adcs.reaction_wheel_acceleration",
                    "adcs.reaction_wheel_torque",
                    "adcs.reaction_wheel_current",
                    "adcs.reaction_wheel_temperature",
                    "adcs.reaction_wheel_status",
                    "adcs.magnetorquer_axis_x",
                    "adcs.magnetorquer_axis_y",
                    "adcs.magnetorquer_axis_z",
                    "adcs.magnetorquer_dipole",
                    "adcs.magnetorquer_current",
                    "adcs.magnetorquer_temperature",
                    "adcs.magnetometer_reading_x",
                    "adcs.magnetometer_reading_y",
                    "adcs.magnetometer_reading_z",
                    "adcs.magnetometer_bias",
                    "adcs.magnetometer_scale_factor",
                    "adcs.magnetometer_temperature",
                    "adcs.magnetometer_status",
                    "adcs.gyro_reading_x",
                    "adcs.gyro_reading_y",
                    "adcs.gyro_reading_z",
                    "adcs.gyro_rate_x",
                    "adcs.gyro_rate_y",
                    "adcs.gyro_rate_z",
                    "adcs.gyro_bias",
                    "adcs.gyro_scale_factor",
                    "adcs.gyro_temperature",
                    "adcs.gyro_drift",
                    "adcs.gyro_status",
                    "adcs.sun_sensor_reading",
                    "adcs.sun_sensor_x",
                    "adcs.sun_sensor_y",
                    "adcs.sun_sensor_z",
                    "adcs.sun_sensor_valid",
                    "adcs.sun_sensor_temperature",
                    "adcs.star_tracker_reading",
                    "adcs.star_tracker_quaternion",
                    "adcs.star_tracker_error",
                    "adcs.star_tracker_star_count",
                    "adcs.star_tracker_catalog_id",
                    "adcs.star_tracker_integration_time",
                    "adcs.star_tracker_exposure",
                    "adcs.star_tracker_temperature",
                    "adcs.star_tracker_status",
                    "adcs.earth_sensor_reading",
                    "adcs.earth_sensor_roll",
                    "adcs.earth_sensor_pitch",
                    "adcs.earth_sensor_horizon_crossing",
                    "adcs.horizon_sensor_reading",
                    "adcs.horizon_sensor_temperature",
                    "adcs.horizon_sensor_status",
                    "adcs.gps_receiver_position",
                    "adcs.gps_receiver_velocity",
                    "adcs.gps_receiver_time",
                    "adcs.gps_satellite_count",
                    "adcs.gps_position_accuracy",
                    "adcs.gps_velocity_accuracy",
                    "adcs.gps_dilution_of_precision",
                    "adcs.attitude_determination_mode",
                    "adcs.attitude_filter_type",
                    "adcs.attitude_filter_gain",
                    "adcs.attitude_filter_covariance",
                    "adcs.attitude_estimate_valid",
                    "adcs.attitude_estimate_uncertainty",
                    "adcs.attitude_controller_type",
                    "adcs.attitude_controller_gain_p",
                    "adcs.attitude_controller_gain_i",
                    "adcs.attitude_controller_gain_d",
                    "adcs.attitude_control_torque",
                    "adcs.attitude_control_momentum",
                    "adcs.attitude_detumble_status",
                    "adcs.attitude_slew_rate",
                    "adcs.attitude_slew_time",
                    "adcs.attitude_pointing_accuracy",
                    "adcs.attitude_stability",
                    "adcs.attitude_jitter",
                    "adcs.attitude_nadir_offset",
                    "adcs.attitude_sun_pointing_error",
                    "adcs.attitude_target_quaternion",
                    "adcs.attitude_matching_window",
                ],
                "count": 100,
            },
            "mission_planning": {
                "description": "Pass scheduling, downlink windows, and maneuver planning",
                "reference": "NASA Mission Operations Handbook, ESA Mission Planning Guide",
                "fields": [
                    "mission.pass_id",
                    "mission.pass_number",
                    "mission.pass_sequence",
                    "mission.pass_start_utc",
                    "mission.pass_end_utc",
                    "mission.pass_duration",
                    "mission.pass_max_elevation",
                    "mission.pass_aos_azimuth",
                    "mission.pass_los_azimuth",
                    "mission.pass_tca_time",
                    "mission.pass_tca_elevation",
                    "mission.pass_ground_station",
                    "mission.pass_station_name",
                    "mission.pass_station_location",
                    "mission.pass_station_latitude",
                    "mission.pass_station_longitude",
                    "mission.pass_station_elevation",
                    "mission.pass_station_antenna",
                    "mission.pass_visibility_start",
                    "mission.pass_visibility_end",
                    "mission.pass_rf_visibility_start",
                    "mission.pass_rf_visibility_end",
                    "mission.pass_track_antenna",
                    "mission.pass_track_sun",
                    "mission.pass_track_moon",
                    "mission.pass_track_target",
                    "mission.pass_data_volume",
                    "mission.pass_telemetry_dump",
                    "mission.pass_playback",
                    "mission.pass_command_load",
                    "mission.pass_ranging",
                    "mission.pass_doppler",
                    "mission.pass_angles_report",
                    "mission.pass_health_check",
                    "mission.pass_configuration",
                    "mission.pass_priority",
                    "mission.pass_status",
                    "mission.pass_type",
                    "mission.pass_confidence",
                    "mission.pass_conflict",
                    "mission.pass_conflict_station",
                    "mission.pass_conflict_time",
                    "mission.pass_recovery_plan",
                    "mission.pass_alternate_station",
                    "mission.downlink_window_start",
                    "mission.downlink_window_end",
                    "mission.downlink_window_duration",
                    "mission.downlink_data_rate",
                    "mission.downlink_frequency",
                    "mission.downlink_modulation",
                    "mission.downlink_coding",
                    "mission.downlink_frame_format",
                    "mission.downlink_priority",
                    "mission.downlink_data_volume",
                    "mission.downlink_data_type",
                    "mission.downlink_data_source",
                    "mission.downlink_schedule_id",
                    "mission.downlink_conflict",
                    "mission.downlink_available",
                    "mission.maneuver_id",
                    "maneuver_number",
                    "mission.maneuver_type",
                    "mission.maneuver_purpose",
                    "mission.maneuver_planned_time",
                    "mission.maneuver_execution_time",
                    "mission.maneuver_duration",
                    "mission.maneuver_delta_v",
                    "mission.maneuver_delta_v_x",
                    "mission.maneuver_delta_v_y",
                    "mission.maneuver_delta_v_z",
                    "mission.maneuver_thrust",
                    "mission.maneuver_fuel_estimate",
                    "mission.maneuver_fuel_actual",
                    "mission.maneuver_orbit_before",
                    "mission.maneuver_orbit_after",
                    "mission.maneuver_perigee_change",
                    "mission.maneuver_apogee_change",
                    "mission.maneuver_inclination_change",
                    "mission.maneuver_plane_change",
                    "mission.maneuver_nodal_precession",
                    "mission.maneuver_argument_perigee",
                    "mission.maneuver_true_anomaly",
                    "mission.maneuver_eccentricity_change",
                    "mission.maneuver_semimajor_axis",
                    "mission.maneuver_rev_number",
                    "maneuver_relative_position",
                    "mission.maneuver_ground_track_shift",
                    "mission.maneuver_collision_avoidance",
                    "mission.maneuver_collision_threshold",
                    "mission.maneuver_collision_probability",
                    "mission.maneuver_debris_avoidance",
                    "mission.maneuver_status",
                    "mission.maneuver_success",
                    "mission.maneuver_delayed",
                    "mission.maneuver_cancelled",
                    "mission.maneuver_rescheduled",
                    "mission.maneuver_ground_track",
                    "mission.maneuver_visibility",
                    "mission.maneuver_ground_station",
                    "mission.maneuver_tle_update",
                    "mission.maneuver_report_time",
                    "mission.maneuver_post_burn_time",
                    "mission.maneuver_pre_burn_time",
                    "mission.maneuver_tca",
                ],
                "count": 110,
            },
            "ground_segment": {
                "description": "Ground stations, networks, DSN, and antenna parameters",
                "reference": "CCSDS 310.0-B, NASA 2100-3",
                "fields": [
                    "ground.station_id",
                    "ground.station_name",
                    "ground.station_type",
                    "ground.station_network",
                    "ground.station_location",
                    "ground.station_latitude",
                    "ground.station_longitude",
                    "ground.station_elevation",
                    "ground.station_country",
                    "ground.station_timezone",
                    "ground.station_operator",
                    "ground.station_owner",
                    "ground.station_status",
                    "ground.station_availability",
                    "ground.station_uptime",
                    "ground.station_downtime",
                    "ground.station_scheduled_maintenance",
                    "ground.station_unscheduled_maintenance",
                    "ground.station_commissioning_date",
                    "ground.station_decommissioning_date",
                    "ground.antenna_id",
                    "ground.antenna_name",
                    "ground.antenna_type",
                    "ground.antenna_diameter",
                    "ground.antenna_gain",
                    "ground.antenna_gain_t",
                    "ground.antenna_efficiency",
                    "ground.antenna_noise_temperature",
                    "ground.antenna_system_noise",
                    "ground.antenna_pointing_type",
                    "ground.antenna_mount_type",
                    "ground.antenna_azimuth_range",
                    "ground.antenna_elevation_range",
                    "ground.antenna_azimuth_rate",
                    "ground.antenna_elevation_rate",
                    "ground.antenna_azimuth_accuracy",
                    "ground.antenna_elevation_accuracy",
                    "ground.antenna_tracking_type",
                    "ground.antenna_tracking_accuracy",
                    "ground.antenna_pointing_loss",
                    "ground.antenna_polarization",
                    "ground.antenna_polarization_type",
                    "ground.antenna_axial_ratio",
                    "ground.antenna_sidelobe_mask",
                    "ground.antenna_frequency_band",
                    "ground.antenna_frequency_range",
                    "ground.antenna_voltage_standing_wave_ratio",
                    "ground.antenna_receive_frequency",
                    "ground.antenna_transmit_frequency",
                    "ground.antenna_receive_gain",
                    "ground.antenna_transmit_gain",
                    "ground.antenna_motor_status",
                    "ground.antenna_brake_status",
                    "ground.antenna_interlock_status",
                    "ground.rf_system_id",
                    "ground.rf_system_type",
                    "ground.rf_receive_frequency",
                    "ground.rf_transmit_frequency",
                    "ground.rf_receive_bandwidth",
                    "ground.rf_transmit_bandwidth",
                    "ground.rf_receive_sensitivity",
                    "ground.rf_transmit_power",
                    "ground.rf_power_amplifier_type",
                    "ground.rf_power_amplifier_power",
                    "ground.rf_low_noise_amplifier",
                    "ground.rf_lna_temperature",
                    "ground.rf_converter_type",
                    "ground.rf_converter_frequency",
                    "ground.rf_upconverter_status",
                    "ground.rf_downconverter_status",
                    "ground.rf_mixer_status",
                    "ground.rf_filter_status",
                    "ground.rf_attenuator_status",
                    "ground.rf_switch_status",
                    "ground.rf_coupler_status",
                    "ground.rf_duplexer_status",
                    "ground.rf_isolator_status",
                    "ground.rf_signal_strength",
                    "ground.rf_carrier_lock",
                    "ground.rf_symbol_sync",
                    "ground.rf_carrier_to_noise",
                    "ground.rf_eb_no",
                    "ground.rf_bit_error_rate",
                    "ground.rf_frame_error_rate",
                    "ground.rf_modulation_type",
                    "ground.rf_coding_type",
                    "ground.rf_convolutional_rate",
                    "ground.rf_reed_solomon_status",
                    "ground.rf_viterbi_status",
                    "ground.rf_turbo_status",
                    "ground.rf_ldpc_status",
                    "ground.network_id",
                    "ground.network_name",
                    "ground.network_type",
                    "ground.network_topology",
                    "ground.network_bandwidth",
                    "ground.network_latency",
                    "ground.network_jitter",
                    "ground.network_availability",
                    "ground.network_redundancy",
                    "ground.network_backup",
                    "ground.dsn_complex_id",
                    "ground.dsn_dss_id",
                    "ground.dsn_dss_name",
                    "ground.dsn_dss_location",
                    "ground.dsn_dss_diameter",
                    "ground.dsn_dss_availability",
                    "ground.dsn_antenna_number",
                    "ground.dsn_signal_processing_center",
                    "ground.dsn_mission_control_center",
                    "ground.dsn_network_operation_center",
                    "ground.dsn_station_status",
                    "ground.dsn_coverage",
                    "ground.dsn_pass_schedule",
                    "ground.dsn_track_data",
                    "ground.dsn_rf_equipment",
                    "ground.dsn_upswitch_request",
                    "ground.dsn_ground_communication",
                    "ground.dsn_telemetry_forward",
                    "ground.dsn_command_back",
                    "ground.ground_contact_id",
                    "ground.ground_contact_time",
                    "ground.ground_contact_type",
                    "ground.ground_contact_station",
                    "ground.ground_contact_vehicle",
                    "ground.ground_contact_frequency",
                    "ground.ground_contact_data_rate",
                    "ground.ground_contact_modulation",
                    "ground.ground_contact_coding",
                    "ground.ground_contact_signal_strength",
                    "ground.ground_contact_snr",
                    "ground.ground_contact_status",
                    "ground.ground_contact_result",
                    "ground.ground_contact_duration",
                    "ground.ground_contact_data_volume",
                    "ground.ground_contact_telemetry",
                    "ground.ground_contact_command",
                    "ground.ground_contact_ranging",
                    "ground.ground_contact_doppler",
                ],
                "count": 120,
            },
        },
        "totals": {
            "categories": 6,
            "total_fields": 700,
        }
    }

    return INVENTORY


def main():
    print("=" * 70)
    print("AEROSPACE AND SATELLITE OPERATIONS METADATA FIELD INVENTORY")
    print("=" * 70)
    print()

    inventory = generate_aerospace_inventory()

    print(f"Generated: {inventory['generated_at']}")
    print(f"Categories: {inventory['totals']['categories']}")
    print(f"Total Fields: {inventory['totals']['total_fields']:,}")
    print()

    print("FIELD COUNTS BY CATEGORY:")
    print("-" * 50)
    for cat_name, cat_data in sorted(inventory['categories'].items(), key=lambda x: x[1]['count'], reverse=True):
        ref = cat_data.get('reference', '')[:40]
        print(f"  {cat_name:30s}: {cat_data['count']:>4}  [{ref}]")

    output_dir = Path("dist/aerospace_inventory")
    output_dir.mkdir(parents=True, exist_ok=True)

    output_file = output_dir / "aerospace_inventory.json"
    output_file.write_text(json.dumps(inventory, indent=2, sort_keys=True), encoding="utf-8")
    print()
    print(f"Wrote: {output_file}")

    summary = {
        "generated_at": inventory["generated_at"],
        "source": inventory["source"],
        "description": inventory["description"],
        "totals": inventory["totals"],
        "field_counts_by_category": {}
    }

    for cat_name, cat_data in inventory["categories"].items():
        summary["field_counts_by_category"][cat_name] = {
            "description": cat_data["description"],
            "count": cat_data["count"],
            "reference": cat_data.get("reference", "N/A")
        }

    summary_file = output_dir / "aerospace_summary.json"
    summary_file.write_text(json.dumps(summary, indent=2), encoding="utf-8")
    print(f"Wrote: {summary_file}")


if __name__ == "__main__":
    main()
