#!/usr/bin/env python3
"""Cybersecurity and Threat Intelligence Metadata Field Inventory

This script documents metadata fields for cybersecurity and threat intelligence
including IOCs, MITRE ATT&CK, CVEs, threat intel feeds, network security,
malware analysis, and incident response.

References:
- MITRE ATT&CK Framework
- STIX 2.1 / TAXII 2.1
- CVSS v3.1/v4.0
- YARA Rule Specification
- SNORT / Suricata IDS Rules
- NIST Cybersecurity Framework
"""

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List, Any


IOC_FIELDS = [
    "ioc.md5_hash",
    "ioc.sha1_hash",
    "ioc.sha256_hash",
    "ioc.sha384_hash",
    "ioc.sha512_hash",
    "ioc.ssdeep_hash",
    "ioc.tlsh_hash",
    "ioc.imphash",
    "ioc.pehash",
    "ioc.authentihash",
    "ioc.cert_hash",
    "ioc.ipv4_address",
    "ioc.ipv6_address",
    "ioc.domain_name",
    "ioc.subdomain",
    "ioc.domain_registration_date",
    "ioc.domain_expiration_date",
    "ioc.domain_registrar",
    "ioc.domain_nameserver",
    "ioc.url",
    "ioc.url_path",
    "ioc.url_parameters",
    "ioc.url_scheme",
    "ioc.url_port",
    "ioc.email_address",
    "ioc.email_subject",
    "ioc.email_sender",
    "ioc.email_recipient",
    "ioc.email_attachment",
    "ioc.email_attachment_hash",
    "ioc.email_attachment_name",
    "ioc.email_mailto",
    "ioc.file_name",
    "ioc.file_path",
    "ioc.file_size",
    "ioc.file_type",
    "ioc.mime_type",
    "ioc.registry_key",
    "ioc.registry_value",
    "ioc.registry_data",
    "ioc.mutex_name",
    "ioc.service_name",
    "ioc.service_display_name",
    "ioc.service_description",
    "ioc.wmi_query",
    "ioc.event_id",
    "ioc.event_log",
    "ioc.process_name",
    "ioc.process_path",
    "ioc.process_command_line",
    "ioc.process_id",
    "ioc.parent_process_id",
    "ioc.thread_id",
    "ioc.module_name",
    "ioc.module_path",
    "ioc.driver_name",
    "ioc.driver_path",
    "ioc.network_protocol",
    "ioc.network_port",
    "ioc.network_direction",
    "ioc.network_bytes_in",
    "ioc.network_bytes_out",
    "ioc.dns_query",
    "ioc.dns_response",
    "ioc.dns_record_type",
    "ioc.http_method",
    "ioc.http_user_agent",
    "ioc.http_referer",
    "ioc.http_host",
    "ioc.http_uri",
    "ioc.user_agent",
    "ioc.cve_id",
    "ioc.cve_description",
    "ioc.btc_address",
    "ioc.monero_address",
    "ioc.xmr_address",
    "ioc.cryptocurrency_wallet",
    "ioc.api_key",
    "ioc.access_token",
    "ioc.jwt_token",
    "ioc.oledb_connection",
    "ioc.jdbc_connection",
    "ioc.smb_share",
    "ioc.smb_file",
    "ioc.ldap_dn",
    "ioc.ssh_fingerprint",
    "ioc.ssh_public_key",
]


MITRE_ATTACK_FIELDS = [
    "mitre.enterprise_attack",
    "mitre.mobile_attack",
    "mitre.ics_attack",
    "mitre.pre_attack",
    "mitre.tactic_id",
    "mitre.tactic_name",
    "mitre.tactic_description",
    "mitre.tactic_order",
    "mitre.technique_id",
    "mitre.technique_name",
    "mitre.technique_description",
    "mitre.technique_url",
    "mitre.technique_data_sources",
    "mitre.technique_platforms",
    "mitre.technique_permissions_required",
    "mitre.technique_detection",
    "mitre.technique_mitigation",
    "mitre.subtechnique_id",
    "mitre.subtechnique_name",
    "mitre.subtechnique_description",
    "mitre.subtechnique_url",
    "mitre.group_id",
    "mitre.group_name",
    "mitre.group_aliases",
    "mitre.group_description",
    "mitre.group_url",
    "mitre.software_id",
    "mitre.software_name",
    "mitre.software_type",
    "mitre.software_aliases",
    "mitre.software_description",
    "mitre.software_url",
    "mitre.campaign_id",
    "mitre.campaign_name",
    "mitre.campaign_description",
    "mitre.campaign_url",
    "mitre.campaign_first_seen",
    "mitre.campaign_last_seen",
    "mitre.attack_pattern_id",
    "mitre.attack_pattern_name",
    "mitre.attack_pattern_description",
    "mitre.kill_chain_phase",
    "mitre.kill_chain_order",
    "mitre.navigator_layers",
    "mitre.attack_matrix",
    "mitre.technique_count",
    "mitre.tactic_coverage",
    "mitre.technique_coverage",
    "mitre.detection_rules",
    "mitre.detection_rule_source",
    "mitre.emulation_plan",
    "mitre.adversary_emulation",
    "mitre.red_team_tool",
    "mitre.apt_group",
    "mitre.nation_state_actor",
    "mitre.cyber_criminal",
    "mitre.hacktivist",
    "mitre.script_kiddie",
    "mitre.insider_threat",
    "mitre.threat_actor",
    "mitre.threat_actor_motivation",
    "mitre.threat_actor_sophistication",
    "mitre.threat_actor_intent",
    "mitre.threat_actor_targeting",
    "mitre.asset_id",
    "mitre.asset_name",
    "mitre.asset_type",
    "mitre.control_objective_id",
    "mitre.control_objective_name",
    "mitre.control_objective_description",
    "mitre.indicator_id",
    "mitre.indicator_name",
    "mitre.indicator_description",
]


CVE_FIELDS = [
    "cve.cve_id",
    "cve.cve_year",
    "cve.cve_sequence",
    "cve.description",
    "cve.references",
    "cve.references_url",
    "cve.cvss_version",
    "cve.cvss_base_score",
    "cve.cvss_base_severity",
    "cve.cvss_impact_score",
    "cve.cvss_exploitability_score",
    "cve.cvss_attack_vector",
    "cve.cvss_attack_complexity",
    "cve.cvss_privileges_required",
    "cve.cvss_user_interaction",
    "cve.cvss_scope",
    "cve.cvss_confidentiality",
    "cve.cvss_integrity",
    "cve.cvss_availability",
    "cve.cvss_vector_string",
    "cve.cvss3_version",
    "cve.cvss3_base_score",
    "cve.cvss3_base_severity",
    "cve.cvss4_base_score",
    "cve.cvss4_base_severity",
    "cve.cwe_id",
    "cve.cwe_name",
    "cve.cwe_description",
    "cve.cwe_category",
    "cve.cpe_product",
    "cve.cpe_vendor",
    "cve.cpe_version",
    "cve.cpe_update",
    "cve.cpe_edition",
    "cve.cpe_language",
    "cve.cpe_sw_edition",
    "cve.cpe_target_sw",
    "cve.cpe_target_hw",
    "cve.cpe_other",
    "cve.affected_product",
    "cve.affected_vendor",
    "cve.affected_version",
    "cve.published_date",
    "cve.last_modified_date",
    "cve.date_published",
    "cve.date_updated",
    "cve.status",
    "cve.vulnerability_type",
    "cve.attack_vector",
    "cve.attack_complexity",
    "cve.authentication_required",
    "cve.user_interaction_required",
    "cve.privileges_required",
    "cve.scope_changed",
    "cve.confidentiality_impact",
    "cve.integrity_impact",
    "cve.availability_impact",
    "cve.exploit_available",
    "cve.exploit_code_maturity",
    "cve.exploitability_subscore",
    "cve.remediation_level",
    "cve.report_confidence",
    "cve.epss_score",
    "cve.epss_percentile",
    "cve.cisa_kev",
    "cve.cisa_kev_date_added",
    "cve.cisa_kev_due_date",
]


THREAT_INTEL_FIELDS = [
    "threatintel.stix_version",
    "threatintel.stix_id",
    "threatintel.stix_bundle",
    "threatintel.taxii_server",
    "threatintel.taxii_collection",
    "threatintel.taxii_api_root",
    "threatintel.threat_indicator",
    "threatintel.threat_actor_object",
    "threatintel.threat_indicator_type",
    "threatintel.indicator_pattern",
    "threatintel.indicator_labels",
    "threatintel.indicator_pattern_language",
    "threatintel.yara_rule_name",
    "threatintel.yara_rule_source",
    "threatintel.yara_rule_author",
    "threatintel.yara_rule_date",
    "threatintel.yara_rule_description",
    "threatintel.yara_rule_strings",
    "threatintel.yara_condition",
    "threatintel.yara_meta",
    "threatintel.yara_reference",
    "threatintel.yara_version",
    "threatintel.yara_score",
    "threatintel.ioc_feed_source",
    "threatintel.ioc_feed_type",
    "threatintel.ioc_feed_url",
    "threatintel.ioc_feed_update",
    "threatintel.threat_feed",
    "threatintel.threat_feed_type",
    "threatintel.threat_feed_provider",
    "threatintel.threat_feed_confidence",
    "threatintel.threat_feed_rating",
    "threatintel.attack_source",
    "threatintel.attack_attribution",
    "threatintel.adversary_intelligence",
    "threatintel.campaign_intelligence",
    "threatintel.vulnerability_intelligence",
    "threatintel.vendor_report",
    "threatintel.vendor_advisory",
    "threatintel.security_bulletin",
    "threatintel.security_advisory",
    "threatintel.patch_information",
    "threatintel.threat_bulletin",
    "threatintel.weekly_intelligence",
    "threatintel.daily_intelligence",
    "threatintel.reconnaissance_report",
    "threatintel.malware_report",
    "threatintel.phishing_report",
    "threatintel.ransomware_report",
    "threatintel.ddos_report",
    "threatintel.state_actor_report",
    "threatintel.criminal_report",
    "threatintel.apt_report",
    "threatintel.intelligence_source",
    "threatintel.intelligence_confidence",
    "threatintel.intelligence_reliability",
    "threatintel.intelligence_tlp",
    "threatintel.intelligence_share",
    "threatintel.osint_source",
    "threatintel.humint_source",
    "threatintel.sigint_source",
    "threatintel.geoint_source",
    "threatintel.threat_model",
    "threatintel.threat_landscape",
    "threatintel.threat_trends",
    "threatintel.threat_forecast",
    "threatintel.adversary_profiling",
    "threatintel.victim_profiling",
    "threatintel.target_profiling",
]


NETWORK_SECURITY_FIELDS = [
    "network.firewall_rule_id",
    "network.firewall_action",
    "network.firewall_direction",
    "network.firewall_protocol",
    "network.firewall_source_ip",
    "network.firewall_source_port",
    "network.firewall_dest_ip",
    "network.firewall_dest_port",
    "network.firewall_interface",
    "network.firewall_timestamp",
    "network.ids_rule_sid",
    "network.ids_rule_msg",
    "network.ids_rule_rev",
    "network.ids_rule_classtype",
    "network.ids_rule_priority",
    "network.ids_rule_gid",
    "network.ids_alert_severity",
    "network.ids_alert_priority",
    "network.ids_alert_category",
    "network.ips_rule_action",
    "network.ips_rule_state",
    "network.snort_rule",
    "network.suricata_rule",
    "network.zeek_log",
    "network.packet_info",
    "network.packet_timestamp",
    "network.packet_length",
    "network.packet_header",
    "network.packet_payload",
    "network.packet_stream_id",
    "network.flow_id",
    "network.flow_start_time",
    "network.flow_end_time",
    "network.flow_duration",
    "network.flow_bytes",
    "network.flow_packets",
    "network.flow_direction",
    "network.flow_state",
    "network.flow_proto",
    "network.netflow_version",
    "network.netflow_src_ip",
    "network.netflow_dst_ip",
    "network.netflow_src_port",
    "network.netflow_dst_port",
    "network.netflow_bytes",
    "network.netflow_packets",
    "network.netflow_tos",
    "network.netflow_flags",
    "network.netflow_tcp_flags",
    "network.proxy_log",
    "network.proxy_request",
    "network.proxy_response",
    "network.proxy_user",
    "network.proxy_host",
    "network.proxy_url",
    "network.vpn_connections",
    "network.vpn_tunnel_id",
    "network.vpn_protocol",
    "network.vpn_remote_ip",
    "network.vpn_local_ip",
    "network.waf_rule",
    "network.waf_action",
    "network.waf_blocked",
    "network.ddos_detection",
    "network.ddos_type",
    "network.ddos_source_ip",
    "network.ddos_target_ip",
]


MALWARE_ANALYSIS_FIELDS = [
    "malware.sample_name",
    "malware.sample_path",
    "malware.sample_size",
    "malware.sample_type",
    "malware.sha256",
    "malware.sha1",
    "malware.md5",
    "malware.ssdeep",
    "malware.tlsh",
    "malware.imphash",
    "malware.static_analysis",
    "malware.dynamic_analysis",
    "malware.behavior_analysis",
    "malware.sandbox_name",
    "malware.sandbox_id",
    "malware.sandbox_url",
    "malware.sandbox_analysis_time",
    "malware.sandbox_environment",
    "malware.sandbox_os_version",
    "malware.sandbox_installed_software",
    "malware.yara_match",
    "malware.yara_rule_name",
    "malware.yara_rule_source",
    "malware.yara_strings",
    "malware.yara_condition",
    "malware.pe_imports",
    "malware.pe_exports",
    "malware.pe_sections",
    "malware.pe_headers",
    "malware.pe_resources",
    "malware.pe_overlay",
    "malware.pe_tls",
    "malware.pe_debug",
    "malware.pe_relocations",
    "malware.pe_version_info",
    "malware.pe_pdb_path",
    "malware.pe_signatures",
    "malware.pe_certificate",
    "malware.elf_analysis",
    "malware.elf_sections",
    "malware.elf_imports",
    "malware.elf_exports",
    "malware.macho_analysis",
    "malware.macho_imports",
    "malware.macho_exports",
    "malware.macho_uuid",
    "malware.android_apk_analysis",
    "malware.android_activities",
    "malware.android_services",
    "malware.android_receivers",
    "malware.android_providers",
    "malware.android_permissions",
    "malware.strings_extracted",
    "malware.string_count",
    "malware.interesting_string",
    "malware.encoded_string",
    "malware.encrypted_string",
]


INCIDENT_RESPONSE_FIELDS = [
    "incident.case_id",
    "incident.case_number",
    "incident.case_status",
    "incident.case_severity",
    "incident.case_priority",
    "incident.case_type",
    "incident.case_category",
    "incident.case_description",
    "incident.case_summary",
    "incident.case_owner",
    "incident.case_team",
    "incident.case_created",
    "incident.case_modified",
    "incident.case_closed",
    "incident.case_opened_date",
    "incident.case_resolved_date",
    "incident.timeline_id",
    "incident.timeline_timestamp",
    "incident.timeline_event",
    "incident.timeline_description",
    "incident.timeline_source",
    "incident.timeline_artifact",
    "incident.timeline_entry_type",
    "incident.containment_id",
    "incident.containment_action",
    "incident.containment_status",
    "incident.containment_timestamp",
    "incident.containment_method",
    "incident.containment_description",
    "incident.eradication_id",
    "incident.eradication_action",
    "incident.eradication_status",
    "incident.eradication_timestamp",
    "incident.recovery_id",
    "incident.recovery_action",
    "incident.recovery_status",
    "incident.recovery_timestamp",
    "incident.lessons_learned",
    "incident.root_cause",
    "incident.impact_assessment",
    "incident.impact_severity",
    "incident.impact_scope",
    "incident.affected_systems",
    "incident.affected_users",
    "incident.affected_data",
    "incident.evidence_id",
    "incident.evidence_type",
    "incident.evidence_source",
    "incident.evidence_location",
    "incident.evidence_acquired",
    "incident.evidence_preserved",
    "incident.evidence_chain_of_custody",
    "incident.alert_id",
    "incident.alert_name",
    "incident.alert_source",
    "incident.alert_timestamp",
    "incident.alert_severity",
    "incident.alert_status",
    "incident.alert_owner",
    "incident.correlation_id",
    "incident.correlation_rule",
    "incident.correlation_score",
]


CYBERSECURITY_INVENTORY = {
    "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
    "source": "MITRE ATT&CK, STIX/TAXII, CVSS, YARA, SNORT/Suricata, NIST CSF",
    "description": "Cybersecurity and threat intelligence metadata fields",
    "categories": {
        "indicators_of_compromise": {
            "description": "IOC fields for hashes, IPs, domains, URLs, and artifacts",
            "fields": sorted(IOC_FIELDS),
            "count": len(IOC_FIELDS),
            "reference": "IOC Standards (MISP, STIX)"
        },
        "mitre_attack": {
            "description": "MITRE ATT&CK framework tactics, techniques, and procedures",
            "fields": sorted(MITRE_ATTACK_FIELDS),
            "count": len(MITRE_ATTACK_FIELDS),
            "reference": "MITRE ATT&CK Framework v14"
        },
        "cve_exploits": {
            "description": "CVE entries, CVSS scores, and vulnerability data",
            "fields": sorted(CVE_FIELDS),
            "count": len(CVE_FIELDS),
            "reference": "NVD, CVSS v3.1/v4.0"
        },
        "threat_intelligence": {
            "description": "STIX/TAXII, YARA rules, and threat intel feeds",
            "fields": sorted(THREAT_INTEL_FIELDS),
            "count": len(THREAT_INTEL_FIELDS),
            "reference": "STIX 2.1, TAXII 2.1, YARA"
        },
        "network_security": {
            "description": "Firewall rules, IDS/IPS signatures, and packet analysis",
            "fields": sorted(NETWORK_SECURITY_FIELDS),
            "count": len(NETWORK_SECURITY_FIELDS),
            "reference": "SNORT, Suricata, Zeek, NetFlow"
        },
        "malware_analysis": {
            "description": "Static/dynamic analysis, sandbox results, and malware metadata",
            "fields": sorted(MALWARE_ANALYSIS_FIELDS),
            "count": len(MALWARE_ANALYSIS_FIELDS),
            "reference": "PE, ELF, MachO, APK Analysis"
        },
        "incident_response": {
            "description": "Case management, timeline, containment, and IR artifacts",
            "fields": sorted(INCIDENT_RESPONSE_FIELDS),
            "count": len(INCIDENT_RESPONSE_FIELDS),
            "reference": "NIST Incident Response Lifecycle"
        }
    },
    "totals": {
        "categories": 7,
        "total_fields": (
            len(IOC_FIELDS) + len(MITRE_ATTACK_FIELDS) + len(CVE_FIELDS) +
            len(THREAT_INTEL_FIELDS) + len(NETWORK_SECURITY_FIELDS) +
            len(MALWARE_ANALYSIS_FIELDS) + len(INCIDENT_RESPONSE_FIELDS)
        )
    }
}


def main():
    output_dir = Path("dist/cybersecurity_inventory")
    output_dir.mkdir(parents=True, exist_ok=True)
    
    output_file = output_dir / "cybersecurity_inventory.json"
    output_file.write_text(json.dumps(CYBERSECURITY_INVENTORY, indent=2, sort_keys=True), encoding="utf-8")
    
    summary = {
        "generated_at": CYBERSECURITY_INVENTORY["generated_at"],
        "source": CYBERSECURITY_INVENTORY["source"],
        "description": CYBERSECURITY_INVENTORY["description"],
        "categories": CYBERSECURITY_INVENTORY["totals"]["categories"],
        "total_fields": CYBERSECURITY_INVENTORY["totals"]["total_fields"],
        "field_counts_by_category": {}
    }
    
    for cat, data in CYBERSECURITY_INVENTORY["categories"].items():
        summary["field_counts_by_category"][cat] = {
            "description": data["description"],
            "count": data["count"],
            "reference": data.get("reference", "N/A")
        }
    
    summary_file = output_dir / "cybersecurity_summary.json"
    summary_file.write_text(json.dumps(summary, indent=2), encoding="utf-8")
    
    print("=" * 70)
    print("CYBERSECURITY & THREAT INTELLIGENCE METADATA FIELD INVENTORY")
    print("=" * 70)
    print()
    print(f"Generated: {CYBERSECURITY_INVENTORY['generated_at']}")
    print(f"Categories: {CYBERSECURITY_INVENTORY['totals']['categories']}")
    print(f"Total Fields: {CYBERSECURITY_INVENTORY['totals']['total_fields']:,}")
    print()
    print("FIELD COUNTS BY CATEGORY:")
    print("-" * 50)
    for cat, data in sorted(CYBERSECURITY_INVENTORY["categories"].items(), key=lambda x: x[1]["count"], reverse=True):
        ref = data.get("reference", "")[:35]
        print(f"  {cat:35s}: {data['count']:>3}  [{ref}]")
    print()
    print(f"Wrote: {output_file}")
    print(f"Wrote: {summary_file}")


if __name__ == "__main__":
    main()
