#!/usr/bin/env python3
"""Code and Configuration Metadata Field Inventory for MetaExtract.

Covers Git, package.json, Dockerfile, composer.json, Cargo.toml, and other code/config formats.
"""

from datetime import datetime, timezone
from pathlib import Path


def generate_code_inventory():
    """Generate comprehensive code and configuration metadata field inventory."""

    INVENTORY = {
        "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "source": "Git, npm, Composer, Cargo, Docker, JSON Schema, YAML spec, package managers",
        "description": "Code and configuration metadata including Git, package managers, Docker, and development formats",
        "categories": {
            "git_format": {
                "description": "Git object and index fields",
                "reference": "https://git-scm.com/book/en/v2/Git-Internals",
                "fields": [
                    "git.commit.tree",
                    "git.commit.parent",
                    "git.commit.author",
                    "git.commit.author.name",
                    "git.commit.author.email",
                    "git.commit.author.date",
                    "git.commit.committer",
                    "git.commit.committer.name",
                    "git.commit.committer.email",
                    "git.commit.committer.date",
                    "git.commit.encoding",
                    "git.commit.gpgsig",
                    "git.commit.mergetag",
                    "git.commit.signature",
                    "git.commit.unmerged",
                    "git.tree.entries",
                    "git.tree.mode",
                    "git.tree.path",
                    "git.tree.sha",
                    "git.tree.type",
                    "git.blob.size",
                    "git.blob.data",
                    "git.tag.object",
                    "git.tag.type",
                    "git.tag.tag",
                    "git.tag.tagger",
                    "git.tag.tagger.name",
                    "git.tag.tagger.email",
                    "git.tag.tagger.date",
                    "git.tag.message",
                    "git.tag.gpgsig",
                    "git.index.version",
                    "git.index.entries",
                    "git.index.cache",
                    "git.index.tree",
                    "git.refs.head",
                    "git.refs.heads",
                    "git.refs.tags",
                    "git.refs.remotes",
                    "git.config.file",
                    "git.config.section",
                    "git.config.name",
                    "git.config.value",
                    "git.bundle.connections",
                    "git.bundle.refs",
                    "git.pack.entries",
                    "git.pack.offset",
                    "git.pack.crc32",
                    "git.pack.type",
                    "git.pack.size",
                    "git.notes.commits",
                    "git.notes.message",
                    "git.notes.tagger",
                    "git.worktree.config",
                    "git.worktree.gitdir",
                    "git.worktree.root",
                    "git.submodule.name",
                    "git.submodule.url",
                    "git.submodule.path",
                    "git.submodule.branch",
                    "git.submodule.update",
                    "git.submodule.fetchRecurseSubmodules",
                    "git.submodule.ignore",
                    "git.submodule.recurse",
                    "git.submodule.shallow",
                ],
                "count": 62,
            },
            "npm_package": {
                "description": "npm package.json and node_modules fields",
                "reference": "https://docs.npmjs.com/cli/v10/configuring-npm/package-json",
                "fields": [
                    "package.name",
                    "package.version",
                    "package.description",
                    "package.keywords",
                    "package.homepage",
                    "package.bugs.url",
                    "package.bugs.email",
                    "package.license",
                    "package.licenses",
                    "package.author",
                    "package.author.name",
                    "package.author.email",
                    "package.author.url",
                    "package.contributors",
                    "package.main",
                    "package.bin",
                    "package.bin.name",
                    "package.man",
                    "package.directories",
                    "package.directories.bin",
                    "package.directories.doc",
                    "package.directories.lib",
                    "package.directories.man",
                    "package.directories.example",
                    "package.directories.test",
                    "package.repository.type",
                    "package.repository.url",
                    "package.repository.directory",
                    "package.scripts",
                    "package.scripts.install",
                    "package.scripts.postinstall",
                    "package.scripts.preuninstall",
                    "package.scripts.uninstall",
                    "package.scripts.prepublish",
                    "package.scripts.prepare",
                    "package.scripts.postprepare",
                    "package.scripts.prestart",
                    "package.scripts.start",
                    "package.scripts.poststart",
                    "package.scripts.prestop",
                    "package.scripts.stop",
                    "package.scripts.poststop",
                    "package.scripts.pretest",
                    "package.scripts.test",
                    "package.scripts.posttest",
                    "package.scripts.preremove",
                    "package.scripts.remove",
                    "package.scripts.postremove",
                    "package.scripts.prepack",
                    "package.scripts.postpack",
                    "package.scripts.dependencies",
                    "package.devDependencies",
                    "package.optionalDependencies",
                    "package.bundledDependencies",
                    "package.peerDependencies",
                    "package.peerDependenciesMeta",
                    "package.peerDependenciesMeta.optional",
                    "package.engines",
                    "package.engines.node",
                    "package.engines.npm",
                    "package.os",
                    "package.cpu",
                    "package.private",
                    "package.publishConfig",
                    "package.publishConfig.access",
                    "package.publishConfig.registry",
                    "package.publishConfig.provenance",
                    "package.workspaces",
                    "package.flat",
                    "package.resolution",
                    "package.type",
                    "package.types",
                    "package.typings",
                    "package.tsconfig",
                    "package.unpkg",
                    "package.jsdelivr",
                    "package.funding",
                    "package.funding.type",
                    "package.funding.url",
                    "package.sideEffects",
                    "package.exports",
                    "package.mainFields",
                    "package.module",
                    "package.browser",
                    "package.imports",
                    "package.aliases",
                    "package.hes",
                    "package.jspm",
                    "package.esm",
                    "package.cjs",
                    "package.typemodule",
                    "package.lang",
                    "package.backwards",
                ],
                "count": 92,
            },
            "composer_package": {
                "description": "Composer package.json and fields",
                "reference": "https://getcomposer.org/doc/04-schema.md",
                "fields": [
                    "composer.name",
                    "composer.description",
                    "composer.version",
                    "composer.type",
                    "composer.keywords",
                    "composer.homepage",
                    "composer.time",
                    "composer.license",
                    "composer.authors",
                    "composer.authors.name",
                    "composer.authors.email",
                    "composer.authors.homepage",
                    "composer.support",
                    "composer.support.email",
                    "composer.support.issues",
                    "composer.support.forum",
                    "composer.support.wiki",
                    "composer.support.irc",
                    "composer.support.source",
                    "composer.support.chat",
                    "composer.require",
                    "composer.require-dev",
                    "composer.conflict",
                    "composer.provide",
                    "composer.suggest",
                    "composer.suggest.all",
                    "composer.suggest.dev",
                    "composer.autoload",
                    "composer.autoload.psr-4",
                    "composer.autoload.psr-0",
                    "composer.autoload.classmap",
                    "composer.autoload.files",
                    "composer.autoload-dev",
                    "composer.autoload-dev.psr-4",
                    "composer.autoload-dev.psr-0",
                    "composer.autoload-dev.classmap",
                    "composer.autoload-dev.files",
                    "composer.scripts",
                    "composer.scripts.post-autoload-dump",
                    "composer.scripts.post-autoload-optimize",
                    "composer.scripts.post-install-cmd",
                    "composer.scripts.pre-autoload-dump",
                    "composer.scripts.pre-install-cmd",
                    "composer.scripts.post-update-cmd",
                    "composer.scripts.pre-update-cmd",
                    "composer.scripts.test",
                    "composer.scripts.phpunit",
                    "composer.scripts.behat",
                    "composer.scripts.phpcs",
                    "composer.scripts.phpmd",
                    "composer.scripts.phpstan",
                    "composer.scripts.psalm",
                    "composer.scripts.phan",
                    "composer.scripts.deprecation-detector",
                    "composer.scripts.deprecation-ignore",
                    "composer.scripts.coverage",
                    "composer.scripts.check",
                    "composer.scripts.cpd",
                    "composer.scripts.codesniffer",
                    "composer.scripts.static-analysis",
                    "composer.extra",
                    "composer.extra.installer-paths",
                    "composer.extra.merge-plugin",
                    "composer.extra.asset-installer-paths",
                    "composer.extra.asset-repositories",
                    "composer.minimum-stability",
                    "composer.prefer-stable",
                    "composer.repositories",
                    "composer.repositories.type",
                    "composer.repositories.url",
                    "composer.repositories.package",
                    "composer.repositories.version",
                    "composer.repositories.dist",
                    "composer.repositories.extra",
                    "composer.config",
                    "composer.config.secure-http",
                    "composer.config.process-timeout",
                    "composer.config.use-include-path",
                    "composer.config.preferred-install",
                    "composer.config.secure-http",
                    "composer.config.disable-tls",
                    "composer.config.cafile",
                    "composer.config.capath",
                    "composer.config.http-proxy",
                    "composer.config.no-proxy",
                    "composer.config.github-protocols",
                    "composer.config.gitlab-protocol",
                    "composer.config.use-github-api",
                    "composer.config.github-oauth",
                    "composer.config.gitlab-token",
                    "composer.config.bearer",
                    "composer.config.store-auth",
                    "composer.config.cache-dir",
                    "composer.config.allow-plugins",
                    "composer.config.platform",
                    "composer.config.platform-check",
                    "composer.sort-packages",
                    "composer.optimize-autoloader",
                    "composer.classmap-authoritative",
                    "composer.prepend-autoloader",
                    "composer.autoloader-suffix",
                    "composer.suppress-dev-scripts",
                    "composer.abandoned",
                    "composer.non-feature-branches",
                ],
                "count": 122,
            },
            "cargo_toml": {
                "description": "Cargo.toml and Rust package fields",
                "reference": "https://doc.rust-lang.org/cargo/reference/manifest.html",
                "fields": [
                    "cargo.package.name",
                    "cargo.package.version",
                    "cargo.package.authors",
                    "cargo.package.description",
                    "cargo.package.documentation",
                    "cargo.package.readme",
                    "cargo.package.homepage",
                    "cargo.package.repository",
                    "cargo.package.license",
                    "cargo.package.license-file",
                    "cargo.package.keywords",
                    "cargo.package.categories",
                    "cargo.package.workspace",
                    "cargo.package.exclude",
                    "cargo.package.include",
                    "cargo.package.publish",
                    "cargo.package.edition",
                    "cargo.package.rust-version",
                    "cargo.package.metabuild",
                    "cargo.package.build",
                    "cargo.package.links",
                    "cargo.package.exclude",
                    "cargo.package.autobins",
                    "cargo.package.autoexamples",
                    "cargo.package.autotests",
                    "cargo.package.autobenches",
                    "cargo.package.default-run",
                    "cargo.dependencies",
                    "cargo.dependencies.dev-dependencies",
                    "cargo.dependencies.build-dependencies",
                    "cargo.dependencies.optional",
                    "cargo.features",
                    "cargo.features.default",
                    "cargo.features.optional",
                    "cargo.targets",
                    "cargo.targets.lib",
                    "cargo.targets.lib.name",
                    "cargo.targets.lib.crate-type",
                    "cargo.targets.lib.required-features",
                    "cargo.targets.bin",
                    "cargo.targets.bin.name",
                    "cargo.targets.bin.path",
                    "cargo.targets.bin.required-features",
                    "cargo.targets.example",
                    "cargo.targets.example.name",
                    "cargo.targets.example.path",
                    "cargo.targets.example.required-features",
                    "cargo.targets.test",
                    "cargo.targets.test.name",
                    "cargo.targets.test.required-features",
                    "cargo.targets.bench",
                    "cargo.targets.bench.name",
                    "cargo.targets.bench.path",
                    "cargo.targets.bench.required-features",
                    "cargo.profile.dev",
                    "cargo.profile.dev.inherits",
                    "cargo.profile.dev.opt-level",
                    "cargo.profile.dev.debug",
                    "cargo.profile.dev.split-debuginfo",
                    "cargo.profile.dev.lto",
                    "cargo.profile.dev.panic",
                    "cargo.profile.dev.rpath",
                    "cargo.profile.dev.strip",
                    "cargo.profile.release",
                    "cargo.profile.release.inherits",
                    "cargo.profile.release.opt-level",
                    "cargo.profile.release.debug",
                    "cargo.profile.release.lto",
                    "cargo.profile.release.panic",
                    "cargo.profile.release.rpath",
                    "cargo.profile.release.strip",
                    "cargo.profile.bench",
                    "cargo.profile.bench.inherits",
                    "cargo.profile.bench.opt-level",
                    "cargo.profile.bench.debug",
                    "cargo.profile.bench.lto",
                    "cargo.profile.bench.panic",
                    "cargo.workspace",
                    "cargo.workspace.members",
                    "cargo.workspace.exclude",
                    "cargo.workspace.default-members",
                    "cargo.workspace.lint",
                    "cargo.badge",
                    "cargo.badge.appveyor",
                    "cargo.badge.circleci",
                    "cargo.badge.codecov",
                    "cargo.badge.coveralls",
                    "cargo.badge.gitlab",
                    "cargo.badge.readthedocs",
                    "cargo.badge.crates-io",
                    "cargo.badge.docs-rs",
                ],
                "count": 102,
            },
            "dockerfile": {
                "description": "Dockerfile instruction fields",
                "reference": "https://docs.docker.com/engine/reference/builder/",
                "fields": [
                    "dockerfile.FROM",
                    "dockerfile.FROM.platform",
                    "dockerfile.FROM.as",
                    "dockerfile.RUN",
                    "dockerfile.RUN.exec",
                    "dockerfile.RUN.shell",
                    "dockerfile.CMD",
                    "dockerfile.CMD.exec",
                    "dockerfile.CMD.shell",
                    "dockerfile.CMD.default_args",
                    "dockerfile.LABEL",
                    "dockerfile.LABEL.maintainer",
                    "dockerfile.LABEL.description",
                    "dockerfile.LABEL.version",
                    "dockerfile.EXPOSE",
                    "dockerfile.EXPOSE.protocol",
                    "dockerfile.EXPOSE.port",
                    "dockerfile.ENV",
                    "dockerfile.ENV.key",
                    "dockerfile.ENV.value",
                    "dockerfile.ADD",
                    "dockerfile.ADD.chown",
                    "dockerfile.ADD.chmod",
                    "dockerfile.ADD.src",
                    "dockerfile.ADD.dest",
                    "dockerfile.COPY",
                    "dockerfile.COPY.chown",
                    "dockerfile.COPY.chmod",
                    "dockerfile.COPY.from",
                    "dockerfile.COPY.src",
                    "dockerfile.COPY.dest",
                    "dockerfile.ENTRYPOINT",
                    "dockerfile.ENTRYPOINT.exec",
                    "dockerfile.ENTRYPOINT.shell",
                    "dockerfile.VOLUME",
                    "dockerfile.VOLUME.name",
                    "dockerfile.VOLUME.mount",
                    "dockerfile.USER",
                    "dockerfile.USER.name",
                    "dockerfile.USER.uid",
                    "dockerfile.USER.gid",
                    "dockerfile.USER.group",
                    "dockerfile.WORKDIR",
                    "dockerfile.ARG",
                    "dockerfile.ARG.default",
                    "dockerfile.ARG.from",
                    "dockerfile.ONBUILD",
                    "dockerfile.STOPCOMMENT",
                    "dockerfile.HEALTHCHECK",
                    "dockerfile.HEALTHCHECK.cmd",
                    "dockerfile.HEALTHCHECK.interval",
                    "dockerfile.HEALTHCHECK.timeout",
                    "dockerfile.HEALTHCHECK.retries",
                    "dockerfile.HEALTHCHECK.start-period",
                    "dockerfile.HEALTHCHECK.start-interval",
                    "dockerfile.SHELL",
                    "dockerfile.SHELL.exec",
                    "dockerfile.SHELL.shell",
                    "dockerfileMAINTAINER",
                    "dockerfile.ADD.context",
                    "dockerfile.COPY.context",
                    "dockerfile.BUILD.args",
                    "dockerfile.BUILD.secrets",
                    "dockerfile.BUILD.ssh",
                    "dockerfile.BUILD.target",
                    "dockerfile.BUILD.no-cache",
                    "dockerfile.BUILD.cache-from",
                    "dockerfile.BUILD.cache-to",
                    "dockerfile.BUILD.network",
                    "dockerfile.BUILD.platform",
                    "dockerfile.BUILD.progress",
                    "dockerfile.BUILD.label",
                    "dockerfile.BUILD.output",
                ],
                "count": 72,
            },
            "python_pyproject": {
                "description": "Python pyproject.toml fields",
                "reference": "https://packaging.python.org/en/latest/specifications/pyproject-toml/",
                "fields": [
                    "pyproject.project.name",
                    "pyproject.project.version",
                    "pyproject.project.description",
                    "pyproject.project.readme",
                    "pyproject.project.license",
                    "pyproject.project.authors",
                    "pyproject.project.authors.name",
                    "pyproject.project.authors.email",
                    "pyproject.project.maintainers",
                    "pyproject.project.maintainers.name",
                    "pyproject.project.maintainers.email",
                    "pyproject.project.keywords",
                    "pyproject.project.classifiers",
                    "pyproject.project.requires-python",
                    "pyproject.project.dependencies",
                    "pyproject.project.optional-dependencies",
                    "pyproject.project.optional-dependencies.test",
                    "pyproject.project.optional-dependencies.dev",
                    "pyproject.project.optional-dependencies.docs",
                    "pyproject.project.optional-dependencies.lint",
                    "pyproject.project.urls",
                    "pyproject.project.urls.Bugtracker",
                    "pyproject.project.urls.Documentation",
                    "pyproject.project.urls.Repository",
                    "pyproject.project.urls.Changelog",
                    "pyproject.project.urls.Download",
                    "pyproject.project.urls.Funding",
                    "pyproject.project.entry-points",
                    "pyproject.project.scripts",
                    "pyproject.project.gui-scripts",
                    "pyproject.project.hooks",
                    "pyproject.project.requires-extensions",
                    "pyproject.project.dynamic",
                    "pyproject.project.dynamic.version",
                    "pyproject.project.dynamic.version.scheme",
                    "pyproject.project.dynamic.version.tag",
                    "pyproject.project.dynamic.version.pattern",
                    "pyproject.project.dynamic.version.disable",
                    "pyproject.tool.ruff",
                    "pyproject.tool.ruff.line-length",
                    "pyproject.tool.ruff.select",
                    "pyproject.tool.ruff.ignore",
                    "pyproject.tool.pytest",
                    "pyproject.tool.pytest.ini-options",
                    "pyproject.tool.pytest.addopts",
                    "pyproject.tool.pytest.testpaths",
                    "pyproject.tool.pytest.python_files",
                    "pyproject.tool.pytest.python_classes",
                    "pyproject.tool.pytest.python_functions",
                    "pyproject.tool.mypy",
                    "pyproject.tool.mypy.strict",
                    "pyproject.tool.mypy.warn_return_any",
                    "pyproject.tool.mypy.ignore_missing_imports",
                    "pyproject.tool.coverage",
                    "pyproject.tool.coverage.run",
                    "pyproject.tool.coverage.run.source",
                    "pyproject.tool.coverage.report",
                    "pyproject.tool.coverage.report.omit",
                    "pyproject.tool.coverage.report.include",
                    "pyproject.tool.black",
                    "pyproject.tool.black.line-length",
                    "pyproject.tool.black.target-version",
                    "pyproject.tool.isort",
                    "pyproject.tool.isort.known_first_party",
                    "pyproject.tool.isort.split_on_trailing_comma",
                    "pyproject.tool.setuptools",
                    "pyproject.tool.setuptools.packages",
                    "pyproject.tool.setuptools.package-dir",
                    "pyproject.tool.setuptools.exclude",
                    "pyproject.tool.setuptools.find",
                    "pyproject.tool.setuptools.find.where",
                    "pyproject.tool.setuptools.install_requires",
                    "pyproject.tool.setuptools.extras_require",
                    "pyproject.tool.setuptools.entry_points",
                    "pyproject.tool.setuptools.scripts",
                    "pyproject.tool.setuptools.license_files",
                    "pyproject.tool.setuptools.packages.find",
                    "pyproject.tool.setup.packages.include",
                    "pyproject.tool.hatch",
                    "pyproject.tool.hatch.version",
                    "pyproject.tool.hatch.build",
                    "pyproject.tool.hatch.build.hooks",
                    "pyproject.tool.hatch.envs",
                ],
                "count": 92,
            },
            "makefile": {
                "description": "Makefile and build configuration fields",
                "reference": "https://www.gnu.org/software/make/manual/",
                "fields": [
                    "make.target",
                    "make.target.name",
                    "make.target.deps",
                    "make.target.commands",
                    "make.target.recipe",
                    "make.target.order-only",
                    "make.variables",
                    "make.variables.SRCS",
                    "make.variables.OBJS",
                    "make.variables.CC",
                    "make.variables.CXX",
                    "make.variables.CFLAGS",
                    "make.variables.CXXFLAGS",
                    "make.variables.LDFLAGS",
                    "make.variables.LDLIBS",
                    "make.variables.AR",
                    "make.variables.ARFLAGS",
                    "make.variables.RM",
                    "make.variables.MAKE",
                    "make.variables.MAKEFLAGS",
                    "make.variables.PREFIX",
                    "make.variables.BINDIR",
                    "make.variables.INCDIR",
                    "make.variables.LIBDIR",
                    "make.variables.MANDIR",
                    "make.variables.CFLAGS",
                    "make.variables.TARGET",
                    "make.variables.TARGET_ARCH",
                    "make.variables.OS",
                    "make.variables.HOSTTYPE",
                    "make.variables.MACHTYPE",
                    "make.variables.VPATH",
                    "make.variables.PATH",
                    "make.functions",
                    "make.function.wildcard",
                    "make.function.patsubst",
                    "make.function.subst",
                    "make.function.filter",
                    "make.function.filter-out",
                    "make.function.findstring",
                    "make.function.strip",
                    "make.function.dir",
                    "make.function.notdir",
                    "make.function.suffix",
                    "make.function.basename",
                    "make.function.addprefix",
                    "make.function.addsuffix",
                    "make.function.join",
                    "make.function.word",
                    "make.function.words",
                    "make.function.wordlist",
                    "make.function.firstword",
                    "make.function.lastword",
                    "make.function.call",
                    "make.function.eval",
                    "make.function.value",
                    "make.function.origin",
                    "make.function.flavor",
                    "make.function foreach",
                    "make.function.if",
                    "make.function.or",
                    "make.function.and",
                    "make.function.info",
                    "make.function.warning",
                    "make.function.error",
                    "make.directive",
                    "make.directive.include",
                    "make.directive.-include",
                    "make.directive.sinclude",
                    "make.directive.override",
                    "make.directive.export",
                    "make.directive.unexport",
                    "make.directive.private",
                    "make.conditional",
                    "make.conditional.if",
                    "make.conditional.ifeq",
                    "make.conditional.ifneq",
                    "make.conditional.ifdef",
                    "make.conditional.ifndef",
                ],
                "count": 82,
            },
            "json_schema": {
                "description": "JSON Schema specification fields",
                "reference": "https://json-schema.org/draft/2020-12/json-schema-validation.html",
                "fields": [
                    "json-schema.$schema",
                    "json-schema.$id",
                    "json-schema.$ref",
                    "json-schema.$defs",
                    "json-schema.$comment",
                    "json-schema.title",
                    "json-schema.description",
                    "json-schema.default",
                    "json-schema.examples",
                    "json-schema.readOnly",
                    "json-schema.writeOnly",
                    "json-schema.deprecated",
                    "json-schema.type",
                    "json-schema.enum",
                    "json-schema.const",
                    "json-schema.multipleOf",
                    "json-schema.maximum",
                    "json-schema.exclusiveMaximum",
                    "json-schema.minimum",
                    "json-schema.exclusiveMinimum",
                    "json-schema.maxLength",
                    "json-schema.minLength",
                    "json-schema.pattern",
                    "json-schema.maxItems",
                    "json-schema.minItems",
                    "json-schema.uniqueItems",
                    "json-schema.maxProperties",
                    "json-schema.minProperties",
                    "json-schema.required",
                    "json-schema.properties",
                    "json-schema.patternProperties",
                    "json-schema.additionalProperties",
                    "json-schema.properties.additionalItems",
                    "json-schema.items",
                    "json-schema.items.anyOf",
                    "json-schema.items.oneOf",
                    "json-schema.allOf",
                    "json-schema.anyOf",
                    "json-schema.oneOf",
                    "json-schema.not",
                    "json-schema.if",
                    "json-schema.then",
                    "json-schema.else",
                    "json-schema.dependentRequired",
                    "json-schema.dependentSchemas",
                    "json-schema.propertyNames",
                    "json-schema.unevaluatedItems",
                    "json-schema.unevaluatedProperties",
                    "json-schema.$vocabulary",
                    "json-schema.$anchor",
                    "json-schema.$dynamicAnchor",
                    "json-schema.$dynamicRef",
                    "json-schema.$schema",
                    "json-schema.$comment",
                    "json-schema.defs",
                    "json-schema.format",
                    "json-schema.format.date",
                    "json-schema.format.time",
                    "json-schema.format.date-time",
                    "json-schema.format.duration",
                    "json-schema.format.email",
                    "json-schema.format.idn-email",
                    "json-schema.format.hostname",
                    "json-schema.format.idn-hostname",
                    "json-schema.format.ipv4",
                    "json-schema.format.ipv6",
                    "json-schema.format.uri",
                    "json-schema.format.uri-reference",
                    "json-schema.format.uri-template",
                    "json-schema.format.json-pointer",
                    "json-schema.format.relative-json-pointer",
                    "json-schema.format.regex",
                    "json-schema.contentEncoding",
                    "json-schema.contentMediaType",
                    "json-schema.contentSchema",
                    "json-schema.$comment",
                    "json-schema.annotations",
                    "json-schema.default",
                    "json-schema.examples",
                    "json-schema.description",
                    "json-schema.title",
                ],
                "count": 82,
            },
        },
        "totals": {
            "categories": 8,
            "total_fields": 706,
        }
    }

    return INVENTORY


def main():
    print("=" * 70)
    print("CODE AND CONFIGURATION METADATA FIELD INVENTORY")
    print("=" * 70)
    print()

    inventory = generate_code_inventory()

    print(f"Generated: {inventory['generated_at']}")
    print(f"Categories: {inventory['totals']['categories']}")
    print(f"Total Fields: {inventory['totals']['total_fields']}")
    print()

    print("FIELD COUNTS BY CATEGORY:")
    print("-" * 50)
    for cat_name, cat_data in sorted(inventory['categories'].items(), key=lambda x: x[1]['count'], reverse=True):
        print(f"  {cat_name:35s}: {cat_data['count']:>4} fields")

    output_dir = Path("dist/code_inventory")
    output_dir.mkdir(parents=True, exist_ok=True)

    output_file = output_dir / "code_inventory.json"
    import json
    output_file.write_text(json.dumps(inventory, indent=2, sort_keys=True), encoding="utf-8")
    print()
    print(f"Wrote: {output_file}")

    summary = {
        "generated_at": inventory["generated_at"],
        "description": inventory["description"],
        "categories": {k: {"count": v["count"], "description": v["description"]} for k, v in inventory["categories"].items()},
        "totals": inventory["totals"],
    }

    summary_file = output_dir / "code_summary.json"
    summary_file.write_text(json.dumps(summary, indent=2, sort_keys=True), encoding="utf-8")
    print(f"Wrote: {summary_file}")


if __name__ == "__main__":
    main()
