#!/usr/bin/env python3
"""Education/EdTech Metadata Field Inventory for MetaExtract.

Covers LMS data, assessments, learning analytics, credentialing, accessibility, standards, and OER licensing.
"""

from datetime import datetime, timezone
import json
from pathlib import Path


def generate_education_inventory():
    """Generate comprehensive education/edtech metadata field inventory."""

    INVENTORY = {
        "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "source": "Canvas LMS API, Blackboard Learn, Moodle, QTI, IMS Global, LTI, Common Core, NGSS, WCAG, Creative Commons, OER Commons",
        "description": "Education metadata including LMS course data, assessments, learning analytics, credentials, accessibility, standards, and OER licensing",
        "categories": {
            "lms_data": {
                "description": "LMS (Canvas, Blackboard, Moodle) course metadata and student data fields",
                "reference": "Canvas API Documentation, Blackboard Learn REST API, Moodle Web Services, IMS LTI 1.3",
                "fields": [
                    "lms.course_id",
                    "lms.course_name",
                    "lms.course_code",
                    "lms.course_description",
                    "lms.course_workflow_state",
                    "lms.course_start_at",
                    "lms.course_end_at",
                    "lms.course_time_zone",
                    "lms.course_enrollment_term_id",
                    "lms.course_blueprint_course_id",
                    "lms.course_blueprint_restrictions",
                    "lms.course_template_course_id",
                    "lms.course_is_public",
                    "lms.course_is_public_to_auth_users",
                    "lms.course_public_syllabus",
                    "lms.course_public_syllabus_to_auth",
                    "lms.course_environment_id",
                    "lms.course_hide_final_grades",
                    "lms.course_apply_assignment_group_weights",
                    "lms.course.default_view",
                    "lms.course.default_timeout",
                    "lms.course.default_tab",
                    "lms.course.conclude_at",
                    "lms.course.delete_at",
                    "lms.course.workflow_state",
                    "lms.course_complete_at",
                    "lms.course.term_id",
                    "lms.course_enrollment_count",
                    "lms.course_total_students",
                    "lms.course_active_students",
                    "lms.course_instructors",
                    "lms.course_ta_count",
                    "lms.course_designer_count",
                    "lms.course_observer_count",
                    "lms.module_id",
                    "lms.module_name",
                    "lms.module_position",
                    "lms.module_unlock_at",
                    "lms.module_requirement_count",
                    "lms.module_requirement_completed_count",
                    "lms.module_items",
                    "lms.module_item_id",
                    "lms.module_item_title",
                    "lms.module_item_type",
                    "lms.module_item_position",
                    "lms.module_item_external_url",
                    "lms.module_item_html_url",
                    "lms.assignment_id",
                    "lms.assignment_name",
                    "lms.assignment_description",
                    "lms.assignment_due_at",
                    "lms.assignment_points_possible",
                    "lms.assignment_grading_type",
                    "lms.assignment_submission_types",
                    "lms.assignment_peer_reviews",
                    "lms.assignment_automatic_peer_reviews",
                    "lms.assignment_peer_review_count",
                    "lms.assignment_anonymous_peer_reviews",
                    "lms.assignment_group_id",
                    "lms.assignment_moderated_grading",
                    "lms.assignment_grader_count",
                    "lms.assignment_final_grader_id",
                    "lms.assignment_grading_standard_id",
                    "lms.assignment_omit_from_final_grade",
                    "lms.assignment_quiz_id",
                    "lms.discussion_id",
                    "lms.discussion_topic_id",
                    "lms.discussion_title",
                    "lms.discussion_message",
                    "lms.discussion_type",
                    "lms.discussion_pinned",
                    "lms.discussion_require_initial_post",
                    "lms.discussion_participant_count",
                    "lms.discussion_entry_count",
                    "lms.file_id",
                    "lms.file_folder_id",
                    "lms.file_display_name",
                    "lms.file_filename",
                    "lms.file_upload_status",
                    "lms.file_size",
                    "lms.file_content_type",
                    "lms.file_created_at",
                    "lms.file_updated_at",
                    "lms.user_id",
                    "lms.user_name",
                    "lms.user_email",
                    "lms.user_login_id",
                    "lms.user_sis_user_id",
                    "lms.user_enrollment_state",
                    "lms.user_enrollment_type",
                    "lms.user_enrollment_role",
                    "lms.user_section_id",
                    "lms.user_sis_import_id",
                    "lms.grade_id",
                    "lms.grade_course_id",
                    "lms.grade_user_id",
                    "lms.grade_assignment_id",
                    "lms.grade_score",
                    "lms.grade_grade",
                    "lms.grade_letter_grade",
                    "lms.grade_percentage",
                    "lms.grade_points_earned",
                    "lms.grade_points_possible",
                    "lms.grade_submitted_at",
                    "lms.grade_graded_at",
                    "lms.grade_graded_by",
                    "lms.grade_excused",
                ],
                "count": 105,
            },
            "assessment_tests": {
                "description": "Assessment, test, question, response, score, and rubric fields",
                "reference": "QTI 2.1/3.0, IMS Question and Test Interoperability, Rubric interoperability",
                "fields": [
                    "assessment.id",
                    "assessment.title",
                    "assessment.description",
                    "assessment.instructions",
                    "assessment.type",
                    "assessment.subtype",
                    "assessment.accessible",
                    "assessment.total_time",
                    "assessment.time_limit",
                    "assessment.time_limit_minutes",
                    "assessment.allowed_attempts",
                    "assessment.allowed_attempts_count",
                    "assessment.allowed_attempts_score_policy",
                    "assessment.scoring_policy",
                    "assessment.grading_type",
                    "assessment.passing_percentage",
                    "assessment.passing_score",
                    "assessment.hide_results",
                    "assessment.hide_score_distribution",
                    "assessment.ip_filter",
                    "assessment.require_lockdown_browser",
                    "assessment.require_lockdown_browser_for_results",
                    "assessment.require_proctoring",
                    "assessment.proctoring_settings",
                    "assessment.moderation_enabled",
                    "assessment.moderation_count",
                    "assessment.manual_rubric_assessment",
                    "assessment.automatic_grading",
                    "assessment.question_count",
                    "assessment.question_pool_count",
                    "assessment.randomize_questions",
                    "assessment.randomize_answers",
                    "assessment.shuffle_answers",
                    "assessment.show_correct_answers",
                    "assessment.show_correct_answers_at",
                    "assessment.hide_correct_answers_at",
                    "assessment.solution_visibility",
                    "assessment.answer_key_visibility",
                    "assessment.one_question_at_a_time",
                    "assessment.cannot_go_back",
                    "assessment.require_question_descent",
                    "assessment.require_secure_browser",
                    "question.id",
                    "question.title",
                    "question.name",
                    "question.type",
                    "question.subtype",
                    "question.question_type",
                    "question.text",
                    "question.presentation_type",
                    "question.interaction_type",
                    "question.correct_response",
                    "question.correct_responses",
                    "question.points_possible",
                    "question.points_earned",
                    "question.partial_credit",
                    "question.difficulty",
                    "question.difficulty_level",
                    "question.bloom_level",
                    "question.taxonomy_level",
                    "question.objective_id",
                    "question.alignment_id",
                    "question.learning_objective",
                    "question.standard_id",
                    "question.standard_code",
                    "question.answer_key",
                    "question.answer_options",
                    "question.response_identifier",
                    "question.correct_answer_id",
                    "question.incorrect_answer_ids",
                    "question.correct_answer_text",
                    "question.incorrect_answer_texts",
                    "question.response_template",
                    "question.variables",
                    "question.formulas",
                    "question.hints",
                    "question.hint_text",
                    "question.feedback",
                    "question.positive_feedback",
                    "question.negative_feedback",
                    "question.general_feedback",
                    "question.solution",
                    "question.rubric_ref",
                    "question.rubric_association",
                    "response.id",
                    "response.assessment_id",
                    "response.question_id",
                    "response.user_id",
                    "response.attempt_id",
                    "response.attempt_number",
                    "response.started_at",
                    "response.completed_at",
                    "response.submitted_at",
                    "response.time_spent",
                    "response.answers",
                    "response.selected_answers",
                    "response.text_entry",
                    "response.file_upload",
                    "response.oral_response",
                    "response.drawing_response",
                    "response.order",
                    "response.score",
                    "response.points_earned",
                    "response.percentage",
                    "response.graded_at",
                    "response.graded_by",
                    "response.grade",
                    "response.feedback",
                    "response.comments",
                    "response.flagged",
                    "response.needs_grading",
                    "response.manually_scored",
                    "response.autograded",
                    "rubric.id",
                    "rubric.title",
                    "rubric.description",
                    "rubric.points_possible",
                    "rubric.criteria_count",
                    "rubric.criteria",
                    "rubric.criterion_id",
                    "rubric.criterion_description",
                    "rubric.criterion_points",
                    "rubric.ratings",
                    "rubric.rating_id",
                    "rubric.rating_description",
                    "rubric.rating_points",
                ],
                "count": 150,
            },
            "learning_analytics": {
                "description": "Learning analytics fields for engagement, time-on-task, completion, and performance tracking",
                "reference": "xAPI, Experience API, IMS Caliper Analytics, Learning Record Store",
                "fields": [
                    "analytics.engagement_score",
                    "analytics.engagement_level",
                    "analytics.engagement_trend",
                    "analytics.time_on_task",
                    "analytics.time_on_task_total",
                    "analytics.time_on_task_average",
                    "analytics.time_on_task_per_session",
                    "analytics.time_on_task_per_activity",
                    "analytics.session_duration",
                    "analytics.session_count",
                    "analytics.session_frequency",
                    "analytics.login_count",
                    "analytics.login_frequency",
                    "analytics.login_streak",
                    "analytics.last_login",
                    "analytics.last_activity",
                    "analytics.completion_rate",
                    "analytics.course_completion_rate",
                    "analytics.module_completion_rate",
                    "analytics.assignment_completion_rate",
                    "analytics.quiz_completion_rate",
                    "analytics.discussion_participation",
                    "analytics.discussion_posts",
                    "analytics.discussion_replies",
                    "analytics.discussion_views",
                    "analytics.content_access",
                    "analytics.content_access_count",
                    "analytics.video_watched",
                    "analytics.video_watch_time",
                    "analytics.video_progress",
                    "analytics.video_completion_rate",
                    "analytics.reading_completion",
                    "analytics.reading_time",
                    "analytics.file_downloads",
                    "analytics.resource_access",
                    "analytics.external_tool_access",
                    "analytics.clickstream",
                    "analytics.clickstream_events",
                    "analytics.event_count",
                    "analytics.event_sequence",
                    "analytics.grade_distribution",
                    "analytics.average_grade",
                    "analytics.median_grade",
                    "analytics.grade_change",
                    "analytics.grade_improvement",
                    "analytics.score_improvement",
                    "analytics.performance_level",
                    "analytics.proficiency_level",
                    "analytics.milestone_achievement",
                    "analytics.milestone_count",
                    "analytics.skill_mastery",
                    "analytics.competency_attainment",
                    "analytics.learning_path_progress",
                    "analytics.adaptive_path_completion",
                    "analytics.risk_score",
                    "analytics.at_risk_indicator",
                    "analytics.at_risk_student",
                    "analytics.intervention_recommended",
                    "analytics.intervention_triggered",
                    "analytics.intervention_type",
                    "analytics.early_warning_status",
                    "analytics.retention_prediction",
                    "analytics.dropout_prediction",
                    "analytics.engagement_index",
                    "analytics.social_network_analysis",
                    "analytics.collaboration_measure",
                    "analytics.peer_interaction",
                    "analytics.help_seeking_behavior",
                    "analytics.self_regulation",
                    "analytics.goal_setting",
                    "analytics.goal_completion",
                    "analytics.motivation_level",
                    "analytics.participation_score",
                    "analytics.activity_completion",
                    "analytics.assignment_submission_rate",
                    "analytics.late_submission_rate",
                    "analytics.early_submission_rate",
                    "analytics.retry_count",
                    "analytics.attempt_distribution",
                    "analytics.success_rate",
                    "analytics.failure_rate",
                    "analytics.drop_rate",
                    "analytics.passing_rate",
                ],
                "count": 100,
            },
            "credentialing": {
                "description": "Credentialing, badge, certificate, degree, and transcript fields",
                "reference": "Open Badges 2.0/3.0, Credential Engine, PESC, Ed-Fi, xAPI Credentials",
                "fields": [
                    "credential.badge_id",
                    "credential.badge_name",
                    "credential.badge_description",
                    "credential.badge_issuer",
                    "credential.badge_issuer_name",
                    "credential.badge_issuer_url",
                    "credential.badge_issued_at",
                    "credential.badge_expires_at",
                    "credential.badge_endorsement",
                    "credential.badge_alignment",
                    "credential.badge_alignment_target_name",
                    "credential.badge_alignment_target_url",
                    "credential.badge_alignment_target_description",
                    "credential.badge_criteria",
                    "credential.badge_criteria_url",
                    "credential.badge_criteria_narrative",
                    "credential.badge_evidence",
                    "credential.badge_evidence_url",
                    "credential.badge_evidence_name",
                    "credential.badge_evidence_description",
                    "credential.badge_image",
                    "credential.badge_image_url",
                    "credential.badge_recipient",
                    "credential.badge_recipient_email",
                    "credential.badge_recipient_name",
                    "credential.badge_recipient_identifier",
                    "credential.badge_verification",
                    "credential.badge_verification_url",
                    "credential.badge_verification_type",
                    "credential.badge_class",
                    "credential.badge_class_id",
                    "credential.certificate_id",
                    "credential.certificate_name",
                    "credential.certificate_description",
                    "credential.certificate_type",
                    "credential.certificate_issuer",
                    "credential.certificate_template",
                    "credential.certificate_template_url",
                    "credential.certificate_issued_at",
                    "credential.certificate_completion_date",
                    "credential.certificate_expiration_date",
                    "credential.certificate_recipient",
                    "credential.certificate_recipient_name",
                    "credential.certificate_verification_url",
                    "credential.degree_id",
                    "credential.degree_name",
                    "credential.degree_type",
                    "credential.degree_level",
                    "credential.degree_major",
                    "credential.degree_minor",
                    "credential.degree_concentration",
                    "credential.degree_specialization",
                    "credential.degree_institution",
                    "credential.degree_institution_name",
                    "credential.degree_institution_code",
                    "credential.degree_awarded_at",
                    "credential.degree_graduation_date",
                    "credential.degree_gpa",
                    "credential.degree_credits_earned",
                    "credential.degree_credits_required",
                    "credential.transcript_id",
                    "credential.transcript_type",
                    "credential.transcript_student",
                    "credential.transcript_student_name",
                    "credential.transcript_student_id",
                    "credential.transcript_institution",
                    "credential.transcript_institution_name",
                    "credential.transcript_institution_code",
                    "credential.transcript_term",
                    "credential.transcript_course",
                    "credential.transcript_course_code",
                    "credential.transcript_course_title",
                    "credential.transcript_grade",
                    "credential.transcript_grade_points",
                    "credential.transcript_credits",
                    "credential.transcript_credit_type",
                    "credential.transcript_quality_points",
                    "credential.transcript_cumulative_gpa",
                    "credential.transcript_cumulative_credits",
                    "credential.transcript_term_gpa",
                    "credential.transcript_term_credits",
                    "credential.transcript_attempted_credits",
                    "credential.transcript_completed_credits",
                    "credential.microcredential_id",
                    "credential.microcredential_name",
                    "credential.microcredential_competency",
                    "credential.microcredential_renewal_date",
                    "credential.microcredential_continuing_education",
                    "credential.license_id",
                    "credential.license_type",
                    "credential.license_name",
                    "credential.license_issuing_body",
                    "credential.license_issue_date",
                    "credential.license_expiration_date",
                    "credential.license_status",
                    "credential.credential_type",
                    "credential.credential_category",
                    "credential.credential_level",
                    "credential.credential_awarding_body",
                    "credential.credential_awarding_body_name",
                ],
                "count": 120,
            },
            "accessibility": {
                "description": "Accessibility fields including WCAG compliance, accommodations, IEP, and 504 plans",
                "reference": "WCAG 2.1/2.2, Section 508, ADA, IDEA, IMS AccessForAll, UDL Guidelines",
                "fields": [
                    "accessibility.accommodation",
                    "accessibility.accommodation_type",
                    "accessibility.accommodation_description",
                    "accessibility.individualized_education_plan",
                    "accessibility.iep_id",
                    "accessibility.iep_status",
                    "accessibility.iep_review_date",
                    "accessibility.iep_goal",
                    "accessibility.iep_objective",
                    "accessibility.iep_service",
                    "accessibility.iep_service_type",
                    "accessibility.iep_service_provider",
                    "accessibility.iep_service_frequency",
                    "accessibility.iep_service_duration",
                    "accessibility.section_504_plan",
                    "accessibility.section_504_id",
                    "accessibility.section_504_status",
                    "accessibility.section_504_accommodation",
                    "accessibility.section_504_modification",
                    "accessibility.section_504_service",
                    "accessibility.wcag_compliance_level",
                    "accessibility.wcag_a_compliant",
                    "accessibility.wcag_aa_compliant",
                    "accessibility.wcag_aaa_compliant",
                    "accessibility.section_508_compliant",
                    "accessibility.accessibility_feature",
                    "accessibility.alternative_text",
                    "accessibility.caption",
                    "accessibility.caption_type",
                    "accessibility.closed_caption",
                    "accessibility.open_caption",
                    "accessibility.transcript",
                    "accessibility.transcript_type",
                    "accessibility.audio_description",
                    "accessibility.sign_language_interpretation",
                    "accessibility.sign_language_translation",
                    "accessibility.screen_reader_compatible",
                    "accessibility.keyboard_navigable",
                    "accessibility.focus_indicator",
                    "accessibility.color_contrast",
                    "accessibility.color_contrast_ratio",
                    "accessibility.text_scaling",
                    "accessibility.magnification",
                    "accessibility.reduced_motion",
                    "accessibility.custom_cursor",
                    "accessibility.high_contrast_mode",
                    "accessibility.reading_guide",
                    "accessibility.extended_time",
                    "accessibility.extended_time_multiplier",
                    "accessibility.calculator",
                    "accessibility.calculator_type",
                    "accessibility.text_to_speech",
                    "accessibility.tts_engine",
                    "accessibility.tts_voice",
                    "accessibility.tts_rate",
                    "accessibility.dictation",
                    "accessibility.speech_to_text",
                    "accessibility.stt_engine",
                    "accessibility.assistive_technology",
                    "accessibility.assistive_device",
                    "accessibility.preferences",
                    "accessibility.preference_setting",
                    "accessibility.preference_value",
                    "accessibility.udl_principle",
                    "accessibility.udl_representation",
                    "accessibility.udl_action_expression",
                    "accessibility.udl_engagement",
                    "accessibility.flexible_format",
                    "accessibility.large_print",
                    "accessibility.braille",
                    "accessibility.braille_grade",
                    "accessibility.accessible_pdf",
                    "accessibility.tagged_pdf",
                    "accessibility.accessible_document",
                    "accessibility.accessible_video",
                    "accessibility.accessible_audio",
                    "accessibility.accessible_interactive",
                    "accessibility.sensory_accommodation",
                    "accessibility.motor_accommodation",
                    "accessibility.cognitive_accommodation",
                    "accessibility.learning_accommodation",
                    "accessibility.testing_accommodation",
                    "accessibility.presentation_accommodation",
                    "accessibility.response_accommodation",
                    "accessibility.timing_accommodation",
                    "accessibility.environment_accommodation",
                    "accessibility.notification_accommodation",
                ],
                "count": 100,
            },
            "standards": {
                "description": "Educational standards fields including Common Core, NGSS, state standards, and competency frameworks",
                "reference": "Common Core State Standards, NGSS, State Standards, Competency-Based Education, Credential Engine",
                "fields": [
                    "standard.code",
                    "standard.id",
                    "standard.identifier",
                    "standard.notation",
                    "standard.title",
                    "standard.description",
                    "standard.full_description",
                    "standard.grade_level",
                    "standard.grade_level_min",
                    "standard.grade_level_max",
                    "standard.subject",
                    "standard.domain",
                    "standard.cluster",
                    "standard.standard_category",
                    "standard.standard_type",
                    "standard.version",
                    "standard.version_date",
                    "standard.source",
                    "standard.source_name",
                    "standard.source_url",
                    "standard.common_core",
                    "standard.common_core_math",
                    "standard.common_core_ela",
                    "standard.common_core_math_ccss_code",
                    "standard.common_core_ela_ccss_code",
                    "standard.ngss",
                    "standard.ngss_code",
                    "standard.ngss_discipline",
                    "standard.ngss_core_idea",
                    "standard.ngss_crosscutting_concept",
                    "standard.ngss_science_practice",
                    "standard.ngss_performance_expectation",
                    "standard.state_standard",
                    "standard.state_code",
                    "standard.state_name",
                    "standard.state_subject",
                    "standard.competency_framework",
                    "standard.competency_framework_id",
                    "standard.competency_framework_name",
                    "standard.competency_id",
                    "standard.competency_code",
                    "standard.competency_name",
                    "standard.competency_description",
                    "standard.competency_level",
                    "standard.competency_alignment",
                    "standard.competency_relationship",
                    "standard.competency_prerequisite",
                    "standard.competency_child",
                    "standard.competency_parent",
                    "standard.competency_equivalent",
                    "standard.learning_standard",
                    "standard.learning_objective",
                    "standard.learning_outcome",
                    "standard.educational_level",
                    "standard.benchmark",
                    "standard.milestone",
                    "standard.indicator",
                    "standard.requirement",
                    "standard.requirement_type",
                    "standard.requirement_level",
                    "standard.alignment_type",
                    "standard.alignment_target",
                    "standard.alignment_object",
                    "standard.alignment_quality",
                    "standard.alignment_percent",
                    "standard.depth_of_knowledge",
                    "standard.dok_level",
                    "standard.dok_description",
                    "standard.webb_depth_of_knowledge",
                    "standard.bloom_taxonomy",
                    "standard.bloom_level",
                    "standard.cognitive_level",
                    "standard.evidence_outcome",
                    "standard.content_framework",
                    "standard.process_framework",
                    "standard.skill_framework",
                    "standard.framework_version",
                    "standard.framework_publisher",
                    "standard.framework_publication_date",
                    "standard.framework_localized",
                    "standard.framework_language",
                    "standard.industry_framework",
                    "standard.professional_standard",
                    "standard.certification_requirement",
                    "standard.licensure_requirement",
                    "standard.regulatory_requirement",
                ],
                "count": 110,
            },
            "oer_licensing": {
                "description": "Open Educational Resources and licensing fields including Creative Commons, OER Commons, and open license metadata",
                "reference": "Creative Commons, OER Commons, OpenStax, UNESCO OER Recommendation, Open Definition",
                "fields": [
                    "oer.license_type",
                    "oer.license_url",
                    "oer.license_version",
                    "oer.license_name",
                    "oer.license_identifier",
                    "oer.creative_commons",
                    "oer.cc_license_code",
                    "oer.cc_by",
                    "oer.cc_by_sa",
                    "oer.cc_by_nc",
                    "oer.cc_by_nc_sa",
                    "oer.cc_by_nd",
                    "oer.cc_by_nc_nd",
                    "oer.cc_zero",
                    "oer.cc_public_domain",
                    "oer.public_domain_mark",
                    "oer.copyright",
                    "oer.copyright_holder",
                    "oer.copyright_notice",
                    "oer.copyright_year",
                    "oer.copyright_statement",
                    "oer.rights_statement",
                    "oer.rights_description",
                    "oer.usage_rights",
                    "oer.permissions",
                    "oer.permit_reproduction",
                    "oer.permit_distribution",
                    "oer.permit_derivative_works",
                    "oer.require_attribution",
                    "oer.require_share_alike",
                    "oer.prohibit_commercial_use",
                    "oer.prohibit_high_income_nation_use",
                    "oer.open_license",
                    "oer.open_content",
                    "oer.open_educational_resource",
                    "oer.oer_status",
                    "oer.oer_type",
                    "oer.oer_subject",
                    "oer.oer_grade_level",
                    "oer.oer_educational_use",
                    "oer.oer_aggregation_level",
                    "oer.oer_interactivity_type",
                    "oer.oer_resource_type",
                    "oer.oer_media_type",
                    "oer.oer_format",
                    "oer.oer_language",
                    "oer.oer_duration",
                    "oer.oer_size",
                    "oer.oer_source_url",
                    "oer.oer_download_url",
                    "oer.oer_repository",
                    "oer.oer_repository_name",
                    "oer.oer_collection",
                    "oer.oer_collection_name",
                    "oer.oer_curriculum",
                    "oer.oer_curriculum_standards",
                    "oer.oer_quality_rating",
                    "oer.oer_review_status",
                    "oer.oer_reviewed_by",
                    "oer.oer_reviewed_date",
                    "oer.oer_quality_score",
                    "oer.oer_peer_review",
                    "oer.oer_adoption",
                    "oer.oer_adoption_count",
                    "oer.oer_adoption_institution",
                    "oer.oer_adoption_course",
                    "oer.oer_remix",
                    "oer.oer_remix_allowed",
                    "oer.oer_remix_instructions",
                    "oer.oer_translation",
                    "oer.oer_translation_allowed",
                    "oer.oer_derivative_work",
                    "oer.attribution_name",
                    "oer.attribution_url",
                    "oer.attribution_logo",
                    "oer.attribution_required",
                    "oer.attribution_notice",
                    "oer.source_material",
                    "oer.source_material_url",
                    "oer.source_material_license",
                    "oer.modification_date",
                    "oer.work_status",
                    "oer.version_notes",
                    "oer.change_log",
                    "oer.error_report",
                    "oer.support_contact",
                    "oer.support_link",
                    "oer.maintainer",
                    "oer.maintainer_email",
                    "oer.contributor",
                    "oer.contributor_role",
                    "oer.funding_statement",
                    "oer.funding_id",
                    "oer.grant_number",
                    "oer.acknowledgment",
                    "oer.supported_by",
                ],
                "count": 120,
            },
        },
        "totals": {
            "categories": 7,
            "total_fields": 805,
        }
    }

    return INVENTORY


def main():
    print("=" * 70)
    print("EDUCATION/EDTECH METADATA FIELD INVENTORY")
    print("=" * 70)
    print()

    inventory = generate_education_inventory()

    print(f"Generated: {inventory['generated_at']}")
    print(f"Categories: {inventory['totals']['categories']}")
    print(f"Total Fields: {inventory['totals']['total_fields']}")
    print()

    print("FIELD COUNTS BY CATEGORY:")
    print("-" * 50)
    for cat_name, cat_data in sorted(inventory['categories'].items(), key=lambda x: x[1]['count'], reverse=True):
        print(f"  {cat_name:30s}: {cat_data['count']:>4} fields")

    output_dir = Path("dist/education_inventory")
    output_dir.mkdir(parents=True, exist_ok=True)

    output_file = output_dir / "education_inventory.json"
    output_file.write_text(json.dumps(inventory, indent=2, sort_keys=True), encoding="utf-8")
    print()
    print(f"Wrote: {output_file}")

    summary = {
        "generated_at": inventory["generated_at"],
        "source": inventory["source"],
        "description": inventory["description"],
        "categories": {
            k: {
                "count": v["count"],
                "description": v["description"],
                "reference": v.get("reference", "N/A")
            }
            for k, v in inventory["categories"].items()
        },
        "totals": inventory["totals"],
    }

    summary_file = output_dir / "education_summary.json"
    summary_file.write_text(json.dumps(summary, indent=2, sort_keys=True), encoding="utf-8")
    print(f"Wrote: {summary_file}")


if __name__ == "__main__":
    main()
