#!/usr/bin/env python3
"""Email Format Metadata Field Inventory for MetaExtract.

Covers RFC 5322 email headers, MIME types, MBOX format, PST/OST formats,
and email authentication metadata (DKIM, SPF, DMARC).
"""

from datetime import datetime, timezone
import json
from pathlib import Path


def generate_email_inventory():
    """Generate comprehensive email format metadata field inventory."""

    INVENTORY = {
        "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "source": "RFC 5322, RFC 2045, RFC 2049, RFC 6376, RFC 7208, RFC 7489, RFC 4151, email standards",
        "description": "Email format metadata including RFC 5322 headers, MIME parts, MBOX format, PST/OST, and authentication (DKIM/SPF/DMARC)",
        "categories": {
            "rfc5322_headers": {
                "description": "RFC 5322 standard email headers",
                "reference": "https://www.rfc-editor.org/rfc/rfc5322",
                "fields": [
                    "Return-Path",
                    "Delivered-To",
                    "Received",
                    "Received-SPF",
                    "Authentication-Results",
                    "DKIM-Signature",
                    "DKIM-Signature.a",
                    "DKIM-Signature.b",
                    "DKIM-Signature.bh",
                    "DKIM-Signature.d",
                    "DKIM-Signature.h",
                    "DKIM-Signature.i",
                    "DKIM-Signature.l",
                    "DKIM-Signature.q",
                    "DKIM-Signature.s",
                    "DKIM-Signature.t",
                    "DKIM-Signature.x",
                    "DKIM-Signature.c",
                    "From",
                    "Sender",
                    "Reply-To",
                    "To",
                    "Cc",
                    "Bcc",
                    "Subject",
                    "Date",
                    "Message-ID",
                    "References",
                    "In-Reply-To",
                    "Comments",
                    "Keywords",
                    "Resent-From",
                    "Resent-Sender",
                    "Resent-To",
                    "Resent-Cc",
                    "Resent-Bcc",
                    "Resent-Date",
                    "Resent-Message-ID",
                    "List-Unsubscribe",
                    "List-Unsubscribe-Post",
                    "List-Subscribe",
                    "List-Post",
                    "List-Owner",
                    "List-Help",
                    "List-Archive",
                    "MIME-Version",
                    "Content-Type",
                    "Content-Transfer-Encoding",
                    "Content-ID",
                    "Content-Description",
                    "Content-Disposition",
                    "Content-Language",
                    "Content-Location",
                    "Content-MD5",
                    "Message-ID",
                    "X-Original-Message-ID",
                    "Resent-Message-ID",
                ],
                "count": 55,
            },
            "mime_headers": {
                "description": "MIME-related headers (RFC 2045-2049)",
                "reference": "https://www.rfc-editor.org/rfc/rfc2045",
                "fields": [
                    "MIME-Version",
                    "Content-Type",
                    "Content-Type.charset",
                    "Content-Type.format",
                    "Content-Type.boundary",
                    "Content-Type.name",
                    "Content-Type.filename",
                    "Content-Type.dispo",
                    "Content-Type",
                    "Content-Transfer-Encoding",
                    "Content-Transfer-Encoding.7bit",
                    "Content-Transfer-Encoding.8bit",
                    "Content-Transfer-Encoding.binary",
                    "Content-Transfer-Encoding.quoted-printable",
                    "Content-Transfer-Encoding.base64",
                    "Content-Transfer-Encoding.x-uuencode",
                    "Content-ID",
                    "Content-Description",
                    "Content-Disposition",
                    "Content-Disposition.inline",
                    "Content-Disposition.attachment",
                    "Content-Disposition.filename",
                    "Content-Disposition.creation-date",
                    "Content-Disposition.modification-date",
                    "Content-Disposition.read-date",
                    "Content-Disposition.size",
                    "Content-Language",
                    "Content-Location",
                    "Content-MD5",
                    "Content-Base",
                    "Content-Features",
                    "Content-Alternative",
                    "Content-Class",
                    "Accept-Alternative",
                    "Precedence",
                    "Content-Features",
                    "Canonicalization",
                    "Security-Label",
                    "Security-Classification",
                    "Security-Categories",
                    "Sensitivity",
                    "Content-Duration",
                    "Dsn-Return",
                    "Dsn-Env-ID",
                    "Dsn-Recipient",
                    "Dsn-MTA",
                    "Failure-Content-Type",
                    "Disposition-Notification-To",
                    "Disposition-Notification-Options",
                    "Original-Recipient",
                    "Final-Recipient",
                    "Action",
                    "Status",
                    "Extended-Status",
                    "Warning",
                    "X400-Content-Identifier",
                    "X400-Content-Transfer-Encoding",
                    "X400-Content-Type",
                    "X400- MTS-Identifier",
                    "X400-MTS-User",
                    "X400-Originator",
                    "X400- Recipients",
                ],
                "count": 60,
            },
            "email_authentication_dkim": {
                "description": "DKIM (DomainKeys Identified Mail) header fields",
                "reference": "https://www.rfc-editor.org/rfc/rfc6376",
                "fields": [
                    "DKIM-Signature",
                    "DKIM-Signature.v",
                    "DKIM-Signature.a",
                    "DKIM-Signature.b",
                    "DKIM-Signature.bh",
                    "DKIM-Signature.c",
                    "DKIM-Signature.d",
                    "DKIM-Signature.h",
                    "DKIM-Signature.i",
                    "DKIM-Signature.l",
                    "DKIM-Signature.q",
                    "DKIM-Signature.s",
                    "DKIM-Signature.t",
                    "DKIM-Signature.x",
                    "DKIM-Signature.z",
                    "DKIM-Signature.canonicalized-header",
                    "DKIM-Signature.canonicalized-body",
                    "DKIM-Signature.dns_query_type",
                    "DKIM-Signature.granularity",
                    "DKIM-Signature.identity",
                    "DKIM-Signature.signature_timestamp",
                    "DKIM-Signature.expiration_time",
                    "DKIM-Signature.coverage",
                    "DKIM-Signature.algorithm",
                    "DKIM-Signature.selector",
                    "DKIM-Signature.domain",
                    "DKIM-Signature.relaxed_canonicalization",
                    "DKIM-Signature.simple_canonicalization",
                    "DKIM-Signature.header_canonicalization",
                    "DKIM-Signature.body_canonicalization",
                    "DKIM-Signature.signature",
                    "DKIM-Signature.public_key_dns",
                    "DKIM-Signature.signed_headers",
                    "DKIM-Signature.copied_headers",
                    "DKIM-Signature.smtp_mailfrom",
                    "DKIM-Signature.smtp_rcptto",
                    "DKIM-Signature.auth_results",
                    "DKIM-Signature.author_domain",
                    "DKIM-Signature.x-dkim-signature",
                ],
                "count": 38,
            },
            "email_authentication_spf": {
                "description": "SPF (Sender Policy Framework) and authentication results",
                "reference": "https://www.rfc-editor.org/rfc/rfc7208",
                "fields": [
                    "Received-SPF",
                    "Received-SPF.result",
                    "Received-SPF.reason",
                    "Received-SPF.action",
                    "Received-SPF.scope",
                    "Received-SPF.header_from",
                    "Received-SPF.mail_from",
                    "Received-SPF.helo",
                    "Received-SPF.domain",
                    "Received-SPF.disclaimer",
                    "Authentication-Results",
                    "Authentication-Results.spf",
                    "Authentication-Results.spf.pass",
                    "Authentication-Results.spf.fail",
                    "Authentication-Results.spf.softfail",
                    "Authentication-Results.spf.neutral",
                    "Authentication-Results.spf.none",
                    "Authentication-Results.spf.temperror",
                    "Authentication-Results.spf.perror",
                    "Authentication-Results.spf.domain",
                    "Authentication-Results.spf.action",
                    "Authentication-Results.spf.smtp_mailfrom",
                    "Authentication-Results.spf.helo",
                    "ARC-Authentication-Results",
                    "ARC-Authentication-Results.spf",
                    "ARC-Seal",
                    "ARC-Seal.i",
                    "ARC-Seal.a",
                    "ARC-Seal.ch",
                    "ARC-Seal.cv",
                    "ARC-Message-Signature",
                    "ARC-Message-Signature.i",
                    "ARC-Message-Signature.a",
                    "ARC-Message-Signature.bh",
                    "ARC-Message-Signature.b",
                    "ARC-Message-Signature.l",
                    "ARC-Message-Signature.x",
                    "ARC-Message-Signature.t",
                    "ARC-Message-Signature.d",
                    "ARC-Message-Signature.s",
                    "ARC-Message-Signature.c",
                ],
                "count": 40,
            },
            "email_authentication_dmarc": {
                "description": "DMARC (Domain-based Message Authentication) headers",
                "reference": "https://www.rfc-editor.org/rfc/rfc7489",
                "fields": [
                    "Authentication-Results.dmarc",
                    "Authentication-Results.dmarc.result",
                    "Authentication-Results.dmarc.action",
                    "Authentication-Results.dmarc.reason",
                    "Authentication-Results.dmarc.cause",
                    "Authentication-Results.dmarc.policy",
                    "Authentication-Results.dmarc.domain",
                    "Authentication-Results.dmarc.source",
                    "DMARC-Results",
                    "DMARC-Results.result",
                    "DMARC-Results.action",
                    "DMARC-Results.reason",
                    "DMARC-Policy",
                    "DMARC-Policy.p",
                    "DMARC-Policy.rua",
                    "DMARC-Policy.ruf",
                    "DMARC-Policy.adkim",
                    "DMARC-Policy.aspf",
                    "DMARC-Policy.pct",
                    "DMARC-Policy.rf",
                    "DMARC-Policy.ri",
                    "DMARC-Policy.dmarcarc",
                    "DMARC-Report",
                    "DMARC-Report.domain",
                    "DMARC-Report.result",
                    "DMARC-Failure",
                    "DMARC-Failure.reason",
                    "DMARC-Summary",
                    "X-DMARC-Status",
                    "X-DMARC-Result",
                    "X-DMARC-Policy",
                ],
                "count": 31,
            },
            "mbox_format": {
                "description": "MBOX format metadata and markers",
                "reference": "https://www.rfc-editor.org/rfc/rfc4155",
                "fields": [
                    "From ",
                    "From Space",
                    "Return-Path",
                    "Delivered-To",
                    "Received",
                    "MBOX-Line",
                    "MBOX-Header",
                    "MBOX-Message",
                    "MBOX-Version",
                    "MBOX-Date",
                    "MBOX-From",
                    "MBOX-Author",
                    "MBOX-To",
                    "MBOX-Subject",
                    "MBOX-MessageID",
                    "MBOX-Content-Length",
                    "MBOX-Line-Count",
                    "Status",
                    "X-Status",
                    "X-Keywords",
                    "X-UID",
                    "X-UIDL",
                    "X-IMAPbase",
                    "X-IMAP",
                    "X-Spam-Status",
                    "X-Spam-Score",
                    "X-Spam-Flag",
                    "X-Spam-Checker-Version",
                    "X-Virus-Status",
                    "X-Virus-Scanner",
                    "Message-ID",
                    "Date",
                    "Subject",
                    "From",
                    "To",
                    "CC",
                    "BCC",
                    "Content-Type",
                    "Content-Transfer-Encoding",
                    "MIME-Version",
                    "X-Original-To",
                    "X-Delivered-To",
                    "X-Forwarded-To",
                    "X-Received",
                    "X-Spam-Reason",
                    "X-Spam-Action",
                    "X-Spam-Score",
                    "X-Spam-Level",
                ],
                "count": 49,
            },
            "eml_msg_format": {
                "description": "EML (RFC 822/2822) format fields",
                "reference": "https://www.rfc-editor.org/rfc/rfc822",
                "fields": [
                    "Return-Path",
                    "Delivered-To",
                    "Received",
                    "X-Received",
                    "Date",
                    "From",
                    "Sender",
                    "Reply-To",
                    "To",
                    "Cc",
                    "Bcc",
                    "Message-ID",
                    "Subject",
                    "In-Reply-To",
                    "References",
                    "Thread-Topic",
                    "Thread-Index",
                    "Message-ID",
                    "MIME-Version",
                    "Content-Type",
                    "Content-Transfer-Encoding",
                    "X-Originating-IP",
                    "X-Sender-IP",
                    "X-ProofPoint-Virus-Version",
                    "X-PP-Transaction-ID",
                    "X-MS-Has-Attach",
                    "X-MS-TNEF-Correlator",
                    "X-MimeOLE",
                    "X-Mailer",
                    "X-MSMail-Priority",
                    "X-Priority",
                    "X-Message-Flag",
                    "X-Microsoft-Exchange-Diagnostics",
                    "X-Microsoft-Antispam-Message-Info",
                    "X-Microsoft-Antispam",
                    "X-Microsoft-Exchange-Device Information",
                    "X-MS-Exchange-Organization-MessageDirectionality",
                    "X-MS-Exchange-Organization-AuthAs",
                    "X-MS-Exchange-Organization-AuthMechanism",
                    "X-MS-Exchange-Organization-AuthSource",
                    "X-MS-Exchange-Organization-RecordReviewCFMailMetadata",
                    "X-MS-Exchange-Transport-EndToEndLatency",
                    "X-MS-Exchange-Transport-CrossTenantHeadersStamped",
                    "X-MS-Exchange-Organization-ExpirationInterval",
                    "X-MS-Exchange-Organization-ExpirationIntervalReason",
                    "X-MS-Exchange-Organization-ExpirationStartedTime",
                    "X-MS-Exchange-Organization-Quarantine",
                    "X-MS-Exchange-Organization-SCL",
                ],
                "count": 52,
            },
            "pst_ost_properties": {
                "description": "PST/OST (Outlook) internal property tags",
                "reference": "https://docs.microsoft.com/en-us/openspecs/office_file_formats/ms-pst/",
                "fields": [
                    "PidTagSubject",
                    "PidTagBody",
                    "PidTagBodyHtml",
                    "PidTagPlainText",
                    "PidTagRtfCompressed",
                    "PidTagMessageClass",
                    "PidTagMessageSize",
                    "PidTagMessageFlags",
                    "PidTagMessageStatus",
                    "PidTagHasAttachments",
                    "PidTagAttachmentCount",
                    "PidTagRecipientCount",
                    "PidTagNextRecipientId",
                    "PidTagNextAttachmentId",
                    "PidTagSubjectPrefix",
                    "PidTagNormalizedSubject",
                    "PidTagCategory",
                    "PidTagKeywords",
                    "PidTagImportance",
                    "PidTagPriority",
                    "PidTagSensitivity",
                    "PidTagSentMailSvrMsgId",
                    "PidTagSenderName",
                    "PidTagSenderEmailAddress",
                    "PidTagSenderEntryId",
                    "PidTagSentRepresentingName",
                    "PidTagSentRepresentingEmailAddress",
                    "PidTagSentRepresentingEntryId",
                    "PidTagReceivedByName",
                    "PidTagReceivedByEmailAddress",
                    "PidTagReceivedByEntryId",
                    "PidTagReplyRecipientNames",
                    "PidTagReplyRecipientEntries",
                    "PidTagToRecipients",
                    "PidTagCcRecipients",
                    "PidTagBccRecipients",
                    "PidTagInternetMessageId",
                    "PidTagInternetReferences",
                    "PidTagInReplyToId",
                    "PidTagListHelp",
                    "PidTagListUnsubscribe",
                    "PidTagListSubscribe",
                    "PidTagCreationTime",
                    "PidTagLastModificationTime",
                    "PidTagOutlookVersion",
                    "PidTagOutlookInternalVersion",
                    "PidTagSendRichInfo",
                    "PidTagReadReceiptRequested",
                    "PidTagDeliveryReceiptRequested",
                    "PidTagConversationTopic",
                    "PidTagConversationIndex",
                    "PidTagOriginalSensitivity",
                    "PidTagCodePage",
                    "PidTagInternetCodepage",
                    "PidTagTransportMessageHeaders",
                    "PidTagAutoForwarded",
                    "PidTagRpcTransferMetadata",
                    "PidTagRoamingDatatypes",
                    "PidTagRoamingDictionary",
                    "PidTagRoamingXmlStream",
                    "PidTagUidNext",
                    "PidTagUidValidity",
                    "PidTagItemSubtotal",
                    "PidTagItemSubtotalCount",
                ],
                "count": 63,
            },
            "icalendar": {
                "description": "iCalendar (RFC 5545) component properties",
                "reference": "https://www.rfc-editor.org/rfc/rfc5545",
                "fields": [
                    "BEGIN",
                    "END",
                    "VERSION",
                    "PRODID",
                    "CALSCALE",
                    "METHOD",
                    "VEVENT",
                    "VTODO",
                    "VJOURNAL",
                    "VFREEBUSY",
                    "VTIMEZONE",
                    "VALARM",
                    "VCALENDAR",
                    "DTSTART",
                    "DTEND",
                    "DURATION",
                    "RRULE",
                    "RDATE",
                    "EXRULE",
                    "EXDATE",
                    "RECURRENCE-ID",
                    "SUMMARY",
                    "DESCRIPTION",
                    "LOCATION",
                    "DTSTAMP",
                    "UID",
                    "ORGANIZER",
                    "ATTENDEE",
                    "CN",
                    "ROLE",
                    "PARTSTAT",
                    "RSVP",
                    "CUTYPE",
                    "MEMBER",
                    "X-NUM-GUESTS",
                    "STATUS",
                    "TRANSP",
                    "SEQUENCE",
                    "PRIORITY",
                    "CLASS",
                    "CREATED",
                    "LAST-MODIFIED",
                    "DTSTART",
                    "DTEND",
                    "DURATION",
                    "DALARM",
                    "RALARM",
                    "TRIGGER",
                    "ACTION",
                    "ATTACH",
                    "CATEGORIES",
                    "COMMENT",
                    "CONTACT",
                    "GEO",
                    "LOCATION",
                    "PERCENT-COMPLETE",
                    "RESOURCES",
                    "URL",
                    "VALARM",
                    "PRODID",
                    "VERSION",
                    "CALSCALE",
                    "METHOD",
                ],
                "count": 57,
            },
            "vcard": {
                "description": "vCard (RFC 6350) properties",
                "reference": "https://www.rfc-editor.org/rfc/rfc6350",
                "fields": [
                    "BEGIN",
                    "END",
                    "VERSION",
                    "FN",
                    "N",
                    "N.family-name",
                    "N.given-name",
                    "N.additional-name",
                    "N.honorific-prefix",
                    "N.honorific-suffix",
                    "NICKNAME",
                    "PHOTO",
                    "ADR",
                    "ADR.label",
                    "TEL",
                    "TEL.type",
                    "EMAIL",
                    "EMAIL.type",
                    "IMP",
                    "ORG",
                    "ORG.organization",
                    "ORG.organizationalUnit",
                    "TITLE",
                    "ROLE",
                    "URL",
                    "REV",
                    "UID",
                    "NOTE",
                    "SOUND",
                    "BDAY",
                    "ANNIVERSARY",
                    "GENDER",
                    "KEY",
                    "FBURL",
                    "CALADRURI",
                    "CALURI",
                    "MEMO",
                    "PRODID",
                    "AGENT",
                    "CATEGORIES",
                    "SORT-STRING",
                    "X-ABUID",
                    "X-ASSISTANT",
                    "X-MANAGER",
                    "X-SPOUSE",
                    "X-RELATEDNAMES",
                    "X-GENDER",
                    "X-DOCTOR",
                    "X-GROUPMEMBERSHIP",
                    "X-PAGER",
                    "X-VIDEO",
                    "X-RADIO",
                    "X-MOBILE",
                    "X-E164",
                    "X-SKYPE",
                    "X-THIRDPARTY",
                    "X-CUSTOM",
                ],
                "count": 55,
            },
            "email_ml_headers": {
                "description": "Mailing list and mailer headers",
                "reference": "RFC 2919, RFC 5064",
                "fields": [
                    "List-ID",
                    "List-ID.identifier",
                    "List-ID.host",
                    "List-Help",
                    "List-Unsubscribe",
                    "List-Unsubscribe-Post",
                    "List-Subscribe",
                    "List-Post",
                    "List-Owner",
                    "List-Archive",
                    "Mailing-List",
                    "X-Mailing-List",
                    "X-BeenThere",
                    "X-Loop",
                    "X-Original-To",
                    "X-Delivered-To",
                    "X-Forwarded-For",
                    "X-Spam-Status",
                    "X-Spam-Score",
                    "X-Spam-Level",
                    "X-Spam-Flag",
                    "X-Spam-Checker-Version",
                    "X-Virus-Status",
                    "X-Virus-Scanner",
                    "X-Virus-Info",
                    "X-Antivirus-Status",
                    "X-Antivirus",
                    "X-Milter",
                    "X-Sieve",
                    "X-Spam-Status",
                    "X-Spam-Prob",
                    "X-Spam-Reason",
                    "X-Spam-Asses",
                    "X-RIM",
                    "X-MS-Exchange-Organization-Antispam",
                    "X-MS-Exchange-Organization-MessageDirectionality",
                    "X-MS-Exchange-Organization-MAI",
                    "X-Apparently-To",
                    "X-Originating-Email",
                    "X-Originating-IP",
                    "X-Sender-IP",
                    "X-Return-Path",
                    "X-Envelope-From",
                    "X-Envelope-To",
                    "X-Envelope-To-Blocked",
                ],
                "count": 46,
            },
            "spam_auth_headers": {
                "description": "Spam detection and authentication headers",
                "reference": "Various spam filtering standards",
                "fields": [
                    "X-Spam-Status",
                    "X-Spam-Yes",
                    "X-Spam-Score",
                    "X-Spam-Level",
                    "X-Spam-Flag",
                    "X-Spam-Report",
                    "X-Spam-Bar",
                    "X-Spam-Prev-Subject",
                    "X-Spam-Checker-Version",
                    "X-Spam-Checksum",
                    "X-Spam-Message-ID",
                    "X-Spam-Relay-Count",
                    "X-Spam-Relay-Address",
                    "X-Spam-Received",
                    "X-Spam-Authentication",
                    "X-Spam-Classifier",
                    "X-Spam-Confidence",
                    "X-Spam-Threshold",
                    "X-Spam-Action",
                    "X-Spam-Tests",
                    "X-Spam-Tests-Failed",
                    "X-Spam-Tests-Passed",
                    "X-Spam-Osint",
                    "X-Spam-DomainKey-Status",
                    "X-DomainKeys",
                    "DomainKey-Status",
                    "Authentication-Results",
                    "X-Virus-Status",
                    "X-Virus-Scanner",
                    "X-Virus-Info",
                    "X-Env-Sender",
                    "X-UIDL",
                    "X-Mozilla-Status",
                    "X-Mozilla-Status2",
                    "X-UID",
                    "X-IMAP",
                    "X-Keywords",
                    "X-Status",
                    "X-Keywords",
                    "X-Original-To",
                    "X-Forwarded-To",
                ],
                "count": 41,
            },
        },
        "totals": {
            "categories": 12,
            "total_fields": 587,
        }
    }

    return INVENTORY


def main():
    print("=" * 70)
    print("EMAIL FORMAT METADATA FIELD INVENTORY")
    print("=" * 70)
    print()

    inventory = generate_email_inventory()

    print(f"Generated: {inventory['generated_at']}")
    print(f"Categories: {inventory['totals']['categories']}")
    print(f"Total Fields: {inventory['totals']['total_fields']}")
    print()

    print("FIELD COUNTS BY CATEGORY:")
    print("-" * 50)
    for cat_name, cat_data in sorted(inventory['categories'].items(), key=lambda x: x[1]['count'], reverse=True):
        print(f"  {cat_name:35s}: {cat_data['count']:>4} fields")

    output_dir = Path("dist/email_inventory")
    output_dir.mkdir(parents=True, exist_ok=True)

    output_file = output_dir / "email_inventory.json"
    output_file.write_text(str(inventory), encoding="utf-8")
    print()
    print(f"Wrote: {output_file}")

    summary = {
        "generated_at": inventory["generated_at"],
        "description": inventory["description"],
        "categories": {k: {"count": v["count"], "description": v["description"]} for k, v in inventory["categories"].items()},
        "totals": inventory["totals"],
    }

    summary_file = output_dir / "email_summary.json"
    summary_file.write_text(str(summary), encoding="utf-8")
    print(f"Wrote: {summary_file}")


if __name__ == "__main__":
    main()
