#!/usr/bin/env python3
"""Messaging Format Metadata Field Inventory for MetaExtract.

Covers Slack, Discord, Signal, WhatsApp, Telegram, and other messaging platform metadata.
"""

from datetime import datetime, timezone
from pathlib import Path


def generate_messaging_inventory():
    """Generate comprehensive messaging format metadata field inventory."""

    INVENTORY = {
        "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "source": "Slack API, Discord API, Signal Protocol, WhatsApp, Telegram, iMessage, Matrix",
        "description": "Messaging platform metadata including Slack, Discord, Signal, WhatsApp, Telegram, and related formats",
        "categories": {
            "slack_api": {
                "description": "Slack API and message metadata fields",
                "reference": "https://api.slack.com/docs",
                "fields": [
                    "slack.message.ts",
                    "slack.message.thread_ts",
                    "slack.message.type",
                    "slack.message.subtype",
                    "slack.message.user",
                    "slack.message.bot_id",
                    "slack.message.text",
                    "slack.message.attachments",
                    "slack.message.attachments.title",
                    "slack.message.attachments.text",
                    "slack.message.attachments.fallback",
                    "slack.message.attachments.color",
                    "slack.message.attachments.image_url",
                    "slack.message.attachments.thumb_url",
                    "slack.message.attachments.footer",
                    "slack.message.attachments.ts",
                    "slack.message.blocks",
                    "slack.message.blocks.type",
                    "slack.message.blocks.text",
                    "slack.message.blocks.elements",
                    "slack.message.files",
                    "slack.message.files.id",
                    "slack.message.files.name",
                    "slack.message.files.title",
                    "slack.message.files.mimetype",
                    "slack.message.files.size",
                    "slack.message.files.url",
                    "slack.message.files.permalink",
                    "slack.message.files.created",
                    "slack.message.files.timestamp",
                    "slack.message.files.height",
                    "slack.message.files.width",
                    "slack.message.reactions",
                    "slack.message.reactions.name",
                    "slack.message.reactions.count",
                    "slack.message.reactions.users",
                    "slack.message.reply_count",
                    "slack.message.reply_users_count",
                    "slack.message.latest_reply",
                    "slack.message.reply_users",
                    "slack.message.edited",
                    "slack.message.edited.ts",
                    "slack.channel.id",
                    "slack.channel.name",
                    "slack.channel.is_private",
                    "slack.channel.is_member",
                    "slack.channel.topic",
                    "slack.channel.purpose",
                    "slack.channel.num_members",
                    "slack.user.id",
                    "slack.user.name",
                    "slack.user.real_name",
                    "slack.user.email",
                    "slack.user.is_bot",
                    "slack.user.is_admin",
                    "slack.user.is_owner",
                    "slack.user.is_primary_owner",
                    "slack.user.is_restricted",
                    "slack.user.is_ultra_restricted",
                    "slack.user.status",
                    "slack.user.status_text",
                    "slack.user.status_emoji",
                    "slack.workspace.id",
                    "slack.workspace.name",
                    "slack.workspace.domain",
                    "slack.workspace.icon",
                    "slack.workspace.email_domain",
                    "slack.workspace.enterprise_id",
                    "slack.workspace.enterprise_name",
                    "slack.workspace.members",
                    "slack.file.id",
                    "slack.file.title",
                    "slack.file.name",
                    "slack.file.mimetype",
                    "slack.file.filetype",
                    "slack.file.size",
                    "slack.file.url_private",
                    "slack.file.permalink",
                    "slack.file.created",
                    "slack.file.timestamp",
                    "slack.file.uploader",
                    "slack.file.mode",
                    "slack.file.is_public",
                    "slack.file.public_url_shared",
                    "slack.file.shares",
                    "slack.file.comments_count",
                    "slack.file.reactions_count",
                ],
                "count": 84,
            },
            "discord_api": {
                "description": "Discord API and message metadata fields",
                "reference": "https://discord.com/developers/docs/reference",
                "fields": [
                    "discord.message.id",
                    "discord.message.type",
                    "discord.message.content",
                    "discord.message.author",
                    "discord.message.author.id",
                    "discord.message.author.username",
                    "discord.message.author.discriminator",
                    "discord.message.author.avatar",
                    "discord.message.author.banner",
                    "discord.message.author.flags",
                    "discord.message.author.public_flags",
                    "discord.message.author.is_bot",
                    "discord.message.author.system",
                    "discord.message.author.premium_type",
                    "discord.message.timestamp",
                    "discord.message.edited_timestamp",
                    "discord.message.tts",
                    "discord.message.mention_everyone",
                    "discord.message.mentions",
                    "discord.message.mention_roles",
                    "discord.message.attachments",
                    "discord.message.attachments.id",
                    "discord.message.attachments.filename",
                    "discord.message.attachments.size",
                    "discord.message.attachments.url",
                    "discord.message.attachments.proxy_url",
                    "discord.message.attachments.height",
                    "discord.message.attachments.width",
                    "discord.message.attachments.content_type",
                    "discord.message.attachments.ephemeral",
                    "discord.message.embeds",
                    "discord.message.embeds.type",
                    "discord.message.embeds.title",
                    "discord.message.embeds.description",
                    "discord.message.embeds.url",
                    "discord.message.embeds.timestamp",
                    "discord.message.embeds.color",
                    "discord.message.embeds.footer",
                    "discord.message.embeds.footer.text",
                    "discord.message.embeds.footer.icon_url",
                    "discord.message.embeds.image",
                    "discord.message.embeds.image.url",
                    "discord.message.embeds.image.height",
                    "discord.message.embeds.image.width",
                    "discord.message.embeds.thumbnail",
                    "discord.message.embeds.thumbnail.url",
                    "discord.message.embeds.thumbnail.height",
                    "discord.message.embeds.thumbnail.width",
                    "discord.message.embeds.video",
                    "discord.message.embeds.provider",
                    "discord.message.embeds.author",
                    "discord.message.embeds.author.name",
                    "discord.message.embeds.author.url",
                    "discord.message.embeds.author.icon_url",
                    "discord.message.embeds.fields",
                    "discord.message.reactions",
                    "discord.message.reactions.emoji",
                    "discord.message.reactions.emoji.id",
                    "discord.message.reactions.emoji.name",
                    "discord.message.reactions.count",
                    "discord.message.reactions.me",
                    "discord.message.reactions.me_count",
                    "discord.message.reactions.user_count",
                    "discord.channel.id",
                    "discord.channel.type",
                    "discord.channel.name",
                    "discord.channel.topic",
                    "discord.channel.guild_id",
                    "discord.channel.position",
                    "discord.channel.permission_overwrites",
                    "discord.channel.parent_id",
                    "discord.channel.nsfw",
                    "discord.channel.last_message_id",
                    "discord.guild.id",
                    "discord.guild.name",
                    "discord.guild.icon",
                    "discord.guild.splash",
                    "discord.guild.owner_id",
                    "discord.guild.permissions",
                    "discord.guild.afk_channel_id",
                    "discord.guild.afk_timeout",
                    "discord.guild.embed_enabled",
                    "discord.guild.embed_channel_id",
                    "discord.guild.verification_level",
                    "discord.guild.default_message_notifications",
                    "discord.guild.explicit_content_filter",
                    "discord.guild.mfa_level",
                    "discord.guild.application_id",
                    "discord.guild.system_channel_id",
                    "discord.guild.rules_channel_id",
                    "discord.guild.max_presences",
                    "discord.guild.max_members",
                    "discord.guild.member_count",
                    "discord.guild.premium_tier",
                    "discord.guild.premium_subscription_count",
                    "discord.role.id",
                    "discord.role.name",
                    "discord.role.color",
                    "discord.role.hoist",
                    "discord.role.position",
                    "discord.role.permissions",
                    "discord.role.managed",
                    "discord.role.mentionable",
                ],
                "count": 122,
            },
            "signal_protocol": {
                "description": "Signal Protocol and message fields",
                "reference": "https://signal.org/docs/",
                "fields": [
                    "signal.timestamp",
                    "signal.id",
                    "signal.source",
                    "signal.sourceDevice",
                    "signal.message",
                    "signal.messageType",
                    "signal.expireTimer",
                    "signal.exported",
                    "signal.receivedAt",
                    "signal.readAt",
                    "signal.velope.type",
                    "signal.velope.source",
                    "signal.velope.sourceDevice",
                    "signal.velope.timestamp",
                    "signal.velope.expireTimer",
                    "signal.velope.content",
                    "signal.velope.dataMessage",
                    "signal.velope.syncMessage",
                    "signal.velope.callMessage",
                    "signal.velope.nullMessage",
                    "signal.velope.receiptMessage",
                    "signal.velope.typingMessage",
                    "signal.velope.typingIndicator",
                    "signal.velope.typingIndicator.action",
                    "signal.velope.typingIndicator.timestamp",
                    "signal.velope.typingIndicator.groupId",
                    "signal.content",
                    "signal.content.dataMessage",
                    "signal.content.dataMessage.timestamp",
                    "signal.content.dataMessage.message",
                    "signal.content.dataMessage.attachments",
                    "signal.content.dataMessage.attachments.contentType",
                    "signal.content.dataMessage.attachments.id",
                    "signal.content.dataMessage.attachments.size",
                    "signal.content.dataMessage.attachments.filename",
                    "signal.content.dataMessage.attachments.cdnKey",
                    "signal.content.dataMessage.attachments.uploadTimestamp",
                    "signal.content.dataMessage.attachments.voiceNote",
                    "signal.content.dataMessage.attachments.borderless",
                    "signal.content.dataMessage.attachments.width",
                    "signal.content.dataMessage.attachments.height",
                    "signal.content.dataMessage.attachments.caption",
                    "signal.content.dataMessage.quote",
                    "signal.content.dataMessage.quote.id",
                    "signal.content.dataMessage.quote.author",
                    "signal.content.dataMessage.quote.text",
                    "signal.content.dataMessage.quote.attachments",
                    "signal.content.dataMessage.group",
                    "signal.content.dataMessage.group.id",
                    "signal.content.dataMessage.group.name",
                    "signal.content.dataMessage.group.type",
                    "signal.content.dataMessage.group.members",
                    "signal.content.dataMessage.contacts",
                    "signal.content.dataMessage.preview",
                    "signal.content.dataMessage.sticker",
                    "signal.content.dataMessage.sticker.packId",
                    "signal.content.dataMessage.sticker.packKey",
                    "signal.content.dataMessage.sticker.stickerId",
                    "signal.content.dataMessage.reaction",
                    "signal.content.dataMessage.reaction.emoji",
                    "signal.content.dataMessage.reaction.targetAuthorId",
                    "signal.content.dataMessage.reaction.targetTimestamp",
                    "signal.content.dataMessage.mentions",
                    "signal.syncMessage",
                    "signal.syncMessage.sent",
                    "signal.syncMessage.sent.destination",
                    "signal.syncMessage.sent.expirationStartTimestamp",
                    "signal.syncMessage.sent.message",
                    "signal.syncMessage.sent.attachments",
                    "signal.syncMessage.sent.quote",
                    "signal.syncMessage.contacts",
                    "signal.syncMessage.groups",
                    "signal.syncMessage.blocked",
                    "signal.syncMessage.blocked.numbers",
                    "signal.syncMessage.blocked.aci",
                    "signal.syncMessage.blocked.pni",
                    "signal.callMessage",
                    "signal.callMessage.offer",
                    "signal.callMessage.answer",
                    "signal.callMessage.iceCandidates",
                    "signal.callMessage.id",
                    "signal.callMessage.type",
                    "signal.callMessage.offer.type",
                    "signal.callMessage.offer.sdp",
                    "signal.callMessage.answer.sdp",
                    "signal.callMessage.iceCandidates.sdp",
                ],
                "count": 108,
            },
            "whatsapp": {
                "description": "WhatsApp message and media metadata",
                "reference": "https://developers.facebook.com/docs/whatsapp",
                "fields": [
                    "whatsapp.id",
                    "whatsapp.timestamp",
                    "whatsapp.from",
                    "whatsapp.to",
                    "whatsapp.type",
                    "whatsapp.message_type",
                    "whatsapp.text",
                    "whatsapp.caption",
                    "whatsapp.media",
                    "whatsapp.media_url",
                    "whatsapp.media_mime_type",
                    "whatsapp.media_size",
                    "whatsapp.media_name",
                    "whatsapp.media_sha256",
                    "whatsapp.media_duration",
                    "whatsapp.media_width",
                    "whatsapp.media_height",
                    "whatsapp.media_page_count",
                    "whatsapp.media_page_label",
                    "whatsapp.media_filename",
                    "whatsapp.media_file_path",
                    "whatsapp.media_thumbnail",
                    "whatsapp.location",
                    "whatsapp.location.latitude",
                    "whatsapp.location.longitude",
                    "whatsapp.location.name",
                    "whatsapp.location.address",
                    "whatsapp.location.url",
                    "whatsapp.contact",
                    "whatsapp.contact.name",
                    "whatsapp.contact.vcard",
                    "whatsapp.contact.wa_id",
                    "whatsapp.group",
                    "whatsapp.group.id",
                    "whatsapp.group.name",
                    "whatsapp.group.participants",
                    "whatsapp.system",
                    "whatsapp.system.body",
                    "whatsapp.system.type",
                    "whatsapp.system.invite_type",
                    "whatsapp.message_template",
                    "whatsapp.message_template.namespace",
                    "whatsapp.message_template.name",
                    "whatsapp.message_template.language",
                    "whatsapp.message_template.components",
                    "whatsapp.message_template.components.type",
                    "whatsapp.message_template.components.parameters",
                    "whatsapp.reaction",
                    "whatsapp.reaction.message_id",
                    "whatsapp.reaction.emoji",
                    "whatsapp.reaction.from",
                    "whatsapp.reaction.timestamp",
                    "whatsapp.order",
                    "whatsapp.order.product_id",
                    "whatsapp.order.text",
                    "whatsapp.order.catalog_id",
                    "whatsapp.order.business_id",
                    "whatsapp.sticker",
                    "whatsapp.sticker.mime_type",
                    "whatsapp.sticker.width",
                    "whatsapp.sticker.height",
                    "whatsapp.sticker.is_animated",
                    "whatsapp.sticker.is_ai_generated",
                    "whatsapp.status",
                    "whatsapp.status.from",
                    "whatsapp.status.timestamp",
                    "whatsapp.status.type",
                    "whatsapp.status.forward",
                    "whatsapp.status.frequently_forwarded",
                    "whatsapp.contacts",
                    "whatsapp.contacts.name",
                    "whatsapp.contacts.wa_id",
                    "whatsapp.contacts.pushname",
                    "whatsapp.profile",
                    "whatsapp.profile.name",
                    "whatsapp.profile.status",
                    "whatsapp.profile.picture",
                    "whatsapp.verified",
                    "whatsapp.verified.level",
                    "whatsapp.verified.business",
                    "whatsapp.forwarded",
                    "whatsapp.forwarded_many_times",
                    "whatsapp.referral",
                    "whatsapp.referral.type",
                    "whatsapp.referral.caption",
                    "whatsapp.referral.source_type",
                    "whatsapp.referral.source_url",
                    "whatsapp.referral.campaign_id",
                    "whatsapp.referral.campaign_creative_id",
                ],
                "count": 98,
            },
            "telegram": {
                "description": "Telegram API and message metadata",
                "reference": "https://core.telegram.org/api",
                "fields": [
                    "telegram.message.id",
                    "telegram.message.peer_id",
                    "telegram.message.from_id",
                    "telegram.message.date",
                    "telegram.message.message",
                    "telegram.message.out",
                    "telegram.message.mentioned",
                    "telegram.message.media_unread",
                    "telegram.message.silent",
                    "telegram.message.post",
                    "telegram.message.replies.replies",
                    "telegram.message.replies.channel_id",
                    "telegram.message.replies.max_id",
                    "telegram.message.replies.read_max_id",
                    "telegram.message.forwards",
                    "telegram.message.author_signature",
                    "telegram.message.views",
                    "telegram.message.forum_topic",
                    "telegram.message.forward",
                    "telegram.message.forward.from_id",
                    "telegram.message.forward.from_name",
                    "telegram.message.forward.date",
                    "telegram.message.forward.channel_post",
                    "telegram.message.forward.post_author",
                    "telegram.message.forward.saved_from",
                    "telegram.message.forward.saved_from_bot_api_id",
                    "telegram.message.reply_to",
                    "telegram.message.reply_to.reply_to_msg_id",
                    "telegram.message.reply_to.reply_to_top_id",
                    "telegram.message.entities",
                    "telegram.message.entities.offset",
                    "telegram.message.entities.length",
                    "telegram.message.entities.type",
                    "telegram.message.entities.url",
                    "telegram.message.entities.user_id",
                    "telegram.message.media",
                    "telegram.message.media.type",
                    "telegram.message.media.id",
                    "telegram.message.media.access_hash",
                    "telegram.message.media.file_reference",
                    "telegram.message.media.date",
                    "telegram.message.media.mime_type",
                    "telegram.message.media.size",
                    "telegram.message.media.dc_id",
                    "telegram.message.media.attributes",
                    "telegram.message.media.width",
                    "telegram.message.media.height",
                    "telegram.message.media.duration",
                    "telegram.message.media.thumbs",
                    "telegram.message.media.video_thumbs",
                    "telegram.message.media.photo",
                    "telegram.message.media.webpage",
                    "telegram.message.media.webpage.url",
                    "telegram.message.media.webpage.display_url",
                    "telegram.message.media.webpage.type",
                    "telegram.message.media.webpage.title",
                    "telegram.message.media.webpage.description",
                    "telegram.message.media.webpage.image",
                    "telegram.message.media.webpage.author",
                    "telegram.message.media.webpage.site_name",
                    "telegram.message.media.webpage.embed_url",
                    "telegram.message.media.webpage.embed_type",
                    "telegram.message.action",
                    "telegram.message.action.type",
                    "telegram.message.action.user",
                    "telegram.message.action.users",
                    "telegram.message.action.title",
                    "telegram.message.action.description",
                    "telegram.message.action.photo",
                    "telegram.message.action，旧.geo",
                    "telegram.message.action.geo_point",
                    "telegram.message.action.geo_point.lat",
                    "telegram.message.action.geo_point.long",
                    "telegram.message.action.invited_by",
                    "telegram.message.action.channel",
                    "telegram.message.action.chat",
                    "telegram.message.action.migrate_to",
                    "telegram.message.action.migrate_from",
                    "telegram.chat.id",
                    "telegram.chat.type",
                    "telegram.chat.title",
                    "telegram.chat.photo",
                    "telegram.chat.participants_count",
                    "telegram.chat.admin_rights",
                    "telegram.chat.banned_rights",
                    "telegram.chat.default_banned_rights",
                    "telegram.user.id",
                    "telegram.user.access_hash",
                    "telegram.user.first_name",
                    "telegram.user.last_name",
                    "telegram.user.username",
                    "telegram.user.phone",
                    "telegram.user.photo",
                    "telegram.user.status",
                    "telegram.user.bot",
                    "telegram.user.verified",
                    "telegram.user.premium",
                    "telegram.user.lang_code",
                    "telegram.channel.id",
                    "telegram.channel.access_hash",
                    "telegram.channel.title",
                    "telegram.channel.username",
                    "telegram.channel.broadcast",
                    "telegram.channel.verifies",
                    "telegram.channel.signatures",
                    "telegram.channel.min",
                    "telegram.channel.geo_distance",
                    "telegram.channel.restriction_reason",
                ],
                "count": 130,
            },
            "imessage": {
                "description": "iMessage and Apple Messages metadata",
                "reference": "Apple iOS Forensics",
                "fields": [
                    "imessage.rowid",
                    "imessage.guid",
                    "imessage.text",
                    "imessage.handle_id",
                    "imessage.subject",
                    "imessage.country",
                    "imessage.attributedBody",
                    "imessage.version",
                    "imessage.service",
                    "imessage.account",
                    "imessage.account_guid",
                    "imessage.error",
                    "imessage.date",
                    "imessage.date_read",
                    "imessage.date_delivered",
                    "imessage.is_delivered",
                    "imessage.is_finished",
                    "imessage.is_emote",
                    "imessage.is_from_me",
                    "imessage.is_empty",
                    "imessage.is_delay",
                    "imessage.is_auto_reply",
                    "imessage.is_pre_filter",
                    "imessage.is_expirable",
                    "imessage.expire_state",
                    "imessage.is_mad",
                    "imessage.cache_roomnames",
                    "imessage.is_spam",
                    "imessage.has_dd_results",
                    "imessage.is_audio_ited",
                    "imessage.date_composed",
                    "imessage.date_retrieved",
                    "imessage.is_reply",
                    "imessage.c_guid",
                    "imessage.message_update_date",
                    "imessage.message_source",
                    "imessage.item_type",
                    "imessage.group_title",
                    "imessage.group_action_type",
                    "imessage.share_status",
                    "imessage.share_direction",
                    "imessage.associated_message_guid",
                    "imessage.associated_message_type",
                    "imessage.balloon_bundle_id",
                    "imessage.payload_data",
                    "imessage.express_as_crypto",
                    "imessage.message_type",
                    "imessage.semantic_type",
                    "imessage.semantic_data",
                    "imessage.sticker_user_xattrs",
                    "imessage.message_summary_info",
                    "imessage.collapse_translations",
                    "imessage.time_expressed_display",
                    "imessage.time_expressed_abbreviated",
                    "imessage.reply_to_uuid",
                    "imessage.guid",
                    "imessage.handle.id",
                    "imessage.handle.address",
                    "imessage.handle.uncanonicalized_address",
                    "imessage.handle.country",
                    "imessage.handle.service",
                    "imessage.handle.person_id",
                    "imessage.chat.ROWID",
                    "imessage.chat.guid",
                    "imessage.chat.service_name",
                    "imessage.chat.account_id",
                    "imessage.chat.account_guid",
                    "imessage.chat.property",
                    "imessage.chat.display_name",
                    "imessage.chat.avatar_tmpl",
                    "imessage.chat.last_addressed_handle",
                    "imessage.chat.group_ids",
                    "imessage.chat.is_archived",
                    "imessage.chat.muted_until",
                    "imessage.chat.has_unread_count",
                    "imessage.chat.roomname",
                    "imessage.chat.chat_identifier",
                    "imessage.chat.is_filtered",
                    "imessage.chat.ignore_alerts",
                    "imessage.chat.auto_reply",
                    "imessage.chat.auto_reply_text",
                    "imessage.attachment.ROWID",
                    "imessage.attachment.guid",
                    "imessage.attachment.created_date",
                    "imessage.attachment.start_date",
                    "imessage.attachment.end_date",
                    "imessage.attachment.filename",
                    "imessage.attachment.uti",
                    "imessage.attachment.mime_type",
                    "imessage.attachment.transfer_state",
                    "imessage.attachment.is_incoming",
                    "imessage.attachment.direction",
                    "imessage.attachment.is_sticker",
                    "imessage.attachment.magic",
                    "imessage.attachment.exif_time",
                    "imessage.attachment.caption",
                    "imessage.attachment.orientation",
                    "imessage.attachment.height",
                    "imessage.attachment.width",
                    "imessage.attachment.scale",
                    "imessage.attachment.duration",
                    "imessage.attachment.latitude",
                    "imessage.attachment.longitude",
                    "imessage.attachment.location_hash",
                ],
                "count": 115,
            },
            "matrix_protocol": {
                "description": "Matrix protocol and room metadata",
                "reference": "https://matrix.org/docs/spec/",
                "fields": [
                    "matrix.event_id",
                    "matrix.type",
                    "matrix.content",
                    "matrix.sender",
                    "matrix.origin_server_ts",
                    "matrix.room_id",
                    "matrix.prev_events",
                    "matrix.depth",
                    "matrix.auth_events",
                    "matrix.returns_state",
                    "matrix.unsigned.age",
                    "matrix.unsigned.redacted_because",
                    "matrix.unsigned.transaction_id",
                    "matrix.content.msgtype",
                    "matrix.content.body",
                    "matrix.content.format",
                    "matrix.content.formatted_body",
                    "matrix.content.mimetype",
                    "matrix.content.info",
                    "matrix.content.info.size",
                    "matrix.content.info.width",
                    "matrix.content.info.height",
                    "matrix.content.info.duration",
                    "matrix.content.info.thumbnail_url",
                    "matrix.content.info.thumbnail_info",
                    "matrix.content.info.thumbnail_info.width",
                    "matrix.content.info.thumbnail_info.height",
                    "matrix.content.info.thumbnail_info.size",
                    "matrix.content.info.blurhash",
                    "matrix.content.info.thumbnail_file",
                    "matrix.content.url",
                    "matrix.content.file",
                    "matrix.content.file.url",
                    "matrix.content.file.mimetype",
                    "matrix.content.file.size",
                    "matrix.content.file.thumbnail_url",
                    "matrix.content.file.thumbnail_info",
                    "matrix.content.file.v",
                    "matrix.content.file.key",
                    "matrix.content.file.iv",
                    "matrix.content.hashes",
                    "matrix.content.hashes.sha256",
                    "matrix.content.geo_uri",
                    "matrix.content.latitude",
                    "matrix.content.longitude",
                    "matrix.content.location_description",
                    "matrix.content.alt_text",
                    "matrix.content.relates_to",
                    "matrix.content.relates_to.event_id",
                    "matrix.content.relates_to.rel_type",
                    "matrix.content.relates_to.is_reply",
                    "matrix.content.relates_to.in_reply_to",
                    "matrix.content.relates_to.in_reply_to.event_id",
                    "matrix.content.reply_to",
                    "matrix.state_key",
                    "matrix.state_key.room_version",
                    "matrix.state_key.m.room.name",
                    "matrix.state_key.m.room.aliases",
                    "matrix.state_key.m.room.member",
                    "matrix.state_key.m.room.power_levels",
                    "matrix.state_key.m.room.join_rules",
                    "matrix.state_key.m.room.history_visibility",
                    "matrix.state_key.m.room.encryption",
                    "matrix.state_key.m.room.guest_access",
                    "matrix.state_key.m.room.topic",
                    "matrix.state_key.m.room.avatar",
                    "matrix.state_key.m.room.canonical_alias",
                    "matrix.state_key.m.room.pinned_events",
                    "matrix.state_key.m.room.related_groups",
                    "matrix.state_key.m.room.creation_content",
                    "matrix.state_key.m.room.tombstone",
                    "matrix.state_key.m.room.tombstone.replacement_room",
                    "matrix.room_version",
                    "matrix.room_version.id",
                    "matrix.room_version.protocol",
                    "matrix.room_version.exists",
                    "matrix.presence.status",
                    "matrix.presence.last_active_ago",
                    "matrix.presence.presence",
                    "matrix.presence.status_msg",
                    "matrix.presence.currently_active",
                    "matrix.presence.avatar_url",
                    "matrix.presence.avatar",
                    "matrix.typing.user_id",
                    "matrix.typing.typing",
                    "matrix.receipt.type",
                    "matrix.receipt.user_id",
                    "matrix.receipt.ephemeral",
                    "matrix.read_markers.fully_read",
                    "matrix.read_markers.arrival",
                    "matrix.account_data.type",
                    "matrix.account_data.content",
                    "matrix.to_device.event_type",
                    "matrix.to_device.content",
                    "matrix.to_device.transaction_id",
                ],
                "count": 132,
            },
        },
        "totals": {
            "categories": 7,
            "total_fields": 789,
        }
    }

    return INVENTORY


def main():
    print("=" * 70)
    print("MESSAGING FORMAT METADATA FIELD INVENTORY")
    print("=" * 70)
    print()

    inventory = generate_messaging_inventory()

    print(f"Generated: {inventory['generated_at']}")
    print(f"Categories: {inventory['totals']['categories']}")
    print(f"Total Fields: {inventory['totals']['total_fields']}")
    print()

    print("FIELD COUNTS BY CATEGORY:")
    print("-" * 50)
    for cat_name, cat_data in sorted(inventory['categories'].items(), key=lambda x: x[1]['count'], reverse=True):
        print(f"  {cat_name:35s}: {cat_data['count']:>4} fields")

    output_dir = Path("dist/messaging_inventory")
    output_dir.mkdir(parents=True, exist_ok=True)

    output_file = output_dir / "messaging_inventory.json"
    import json
    output_file.write_text(json.dumps(inventory, indent=2, sort_keys=True), encoding="utf-8")
    print()
    print(f"Wrote: {output_file}")

    summary = {
        "generated_at": inventory["generated_at"],
        "description": inventory["description"],
        "categories": {k: {"count": v["count"], "description": v["description"]} for k, v in inventory["categories"].items()},
        "totals": inventory["totals"],
    }

    summary_file = output_dir / "messaging_summary.json"
    summary_file.write_text(json.dumps(summary, indent=2, sort_keys=True), encoding="utf-8")
    print(f"Wrote: {summary_file}")


if __name__ == "__main__":
    main()
