#!/usr/bin/env python3
"""Materials Science and Metrology Metadata Field Inventory for MetaExtract.

Covers crystallography, spectroscopy, electron microscopy, surface analysis, thermal analysis, mechanical testing, and metrology standards.
"""

from datetime import datetime, timezone
import json
from pathlib import Path


def generate_materials_inventory():
    """Generate comprehensive materials science and metrology metadata field inventory."""

    INVENTORY = {
        "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "source": "ICDSD, JCPDS, ASTM Standards, ISO Standards, NIST, IUPAC, Materials Project",
        "description": "Materials science and metrology metadata including crystallography, spectroscopy, electron microscopy, surface analysis, thermal analysis, mechanical testing, and metrology standards",
        "categories": {
            "crystallography": {
                "description": "XRD, crystal structures, Miller indices, space groups, and crystallographic parameters",
                "reference": "International Tables for Crystallography, ICDSD, JCPDS, ASTM E7",
                "fields": [
                    "xrd.2theta",
                    "xrd.theta",
                    "xrd.intensity",
                    "xrd.counts",
                    "xrd.scan_speed",
                    "xrd.step_size",
                    "xrd.count_time",
                    "xrd.scan_range",
                    "xrd.divergence_slit",
                    "xrd.receiving_slit",
                    "xrd.soller_slits",
                    "xrd.mask",
                    "xrd.monochromator",
                    "xrd.filter",
                    "xrd.radiation_type",
                    "xrd.wavelength",
                    "xrd.k_alpha1",
                    "xrd.k_alpha2",
                    "xrd.k_beta",
                    "xrd.voltage",
                    "xrd.current",
                    "xrd.goniometer_radius",
                    "xrd.detector_type",
                    "xrd.detector_window",
                    "xrd.measurement_mode",
                    "xrd.scan_type",
                    "xrd.continuous_scan",
                    "xrd.step_scan",
                    "xrd.rocking_curve",
                    "xrd.omega_angle",
                    "xrd.chi_angle",
                    "xrd.phi_angle",
                    "xrd.sample_rotation",
                    "xrd.incident_angle",
                    "xrd.diffraction_angle",
                    "xrd.reflection",
                    "xrd.plane_hkl",
                    "xrd.miller_indices_h",
                    "xrd.miller_indices_k",
                    "xrd.miller_indices_l",
                    "xrd.d_spacing",
                    "xrd.lattice_parameter_a",
                    "xrd.lattice_parameter_b",
                    "xrd.lattice_parameter_c",
                    "xrd.lattice_parameter_alpha",
                    "xrd.lattice_parameter_beta",
                    "xrd.lattice_parameter_gamma",
                    "xrd.unit_cell_volume",
                    "xrd.unit_cell_angle",
                    "xrd.crystal_system",
                    "xrd.space_group",
                    "xrd.space_group_number",
                    "xrd.point_group",
                    "xrd.symmetry",
                    "xrd.crystal_class",
                    "xrd.lattice_type",
                    "xrd.primitive_lattice",
                    "xrd.body_centered",
                    "xrd.face_centered",
                    "xrd.base_centered",
                    "xrd.rhombohedral",
                    "xrd.hexagonal",
                    "xrd.metric_tensor",
                    "xrd.reciprocal_lattice",
                    "xrd.bragg_angle",
                    "xrd.bragg_law",
                    "xrd.diffraction_condition",
                    "xrd.structure_factor",
                    "xrd.phase_identification",
                    "xrd.phase_quantification",
                    "xrd.rietveld_refinement",
                    "xrd.whole_pattern_fit",
                    "xrd.peak_profile",
                    "xrd.peak_width",
                    "xrd.peak_shape",
                    "xrd.peak_asymmetry",
                    "xrd.background",
                    "xrd.zero_shift",
                    "xrd.sample_displacement",
                    "xrd.preferred_orientation",
                    "xrd.texture",
                    "xrd.pole_figure",
                    "xrd.inverse_pole_figure",
                    "xrd.orientation_distribution",
                    "xrd.crystallite_size",
                    "xrd.microstrain",
                    "xrd.strain_tensor",
                    "xrd.stress_calculation",
                    "xrd.residual_stress",
                    "xrd.stress_tensor",
                ],
                "count": 90,
            },
            "spectroscopy": {
                "description": "FTIR, Raman, NMR, XPS, UV-Vis, mass spectrometry parameters",
                "reference": "ASTM E1421, ISO 17025, NIST Chemistry WebBook",
                "fields": [
                    "ftir.wavenumber",
                    "ftir.transmittance",
                    "ftir.absorbance",
                    "ftir.interferogram",
                    "ftir.resolution",
                    "ftir.scan_count",
                    "ftir.scan_speed",
                    "ftir.aperture",
                    "ftir.beam_splitter",
                    "ftir.detector",
                    "ftir.source",
                    "ftir.zerofilling",
                    "ftir.phase_correction",
                    "ftir.apodization",
                    "ftir.derivative",
                    "ftir.baseline_correction",
                    "ftir.attenuated_total_reflection",
                    "ftir.ATR_crystal",
                    "ftir.diffuse_reflectance",
                    "ftir.microscope",
                    "ftir.imaging",
                    "raman.shift",
                    "raman.intensity",
                    "raman.stokes",
                    "raman.anti_stokes",
                    "raman.laser_wavelength",
                    "raman.laser_power",
                    "raman.magnification",
                    "raman.objective",
                    "raman.accumulation",
                    "raman.integration_time",
                    "raman.grating",
                    "raman.filter",
                    "raman.slit_width",
                    "raman.pinhole",
                    "raman.confocal",
                    "raman.map",
                    "raman.line_scan",
                    "raman.depth_profile",
                    "raman.inelastically_scattered",
                    "nmr.frequency",
                    "nmr.chemical_shift",
                    "nmr.ppm",
                    "nmr.integration",
                    "nmr.multiplicity",
                    "nmr.coupling_constant",
                    "nmr.splitting",
                    "nmr.j_coupling",
                    "nmr.noise",
                    "nmr.signal_to_noise",
                    "nmr.pulse_sequence",
                    "nmr.flip_angle",
                    "nmr.repetition_time",
                    "nmr.acquisition_time",
                    "nmr.spectral_width",
                    "nmr.transients",
                    "nmr relaxation_time_t1",
                    "nmr.relaxation_time_t2",
                    "nmr.relaxation_time_t2_star",
                    "nmr.nuclear_overhauser_effect",
                    "nmrCOSY",
                    "nmr.NMR",
                    "nmr.NMR",
                    "xps.binding_energy",
                    "xps.kinetic_energy",
                    "xps.photoelectron",
                    "xps.survey_scan",
                    "xps.high_resolution_scan",
                    "xps.sputter_depth",
                    "xps.etch_rate",
                    "xps.takeoff_angle",
                    "xps.analyzer_mode",
                    "xps.pass_energy",
                    "xps.resolution",
                    "xps.charge_neutralization",
                    "xps.monochromator",
                    "xps.source",
                    "xps.al_kalpha",
                    "xps.mg_kalpha",
                    "mass_spec.mz",
                    "mass_spec.mass_to_charge",
                    "mass_spec.intensity",
                    "mass_spec.resolution",
                    "mass_spec.accuracy",
                    "mass_spec.scan_range",
                    "mass_spec.ionization",
                    "mass_spec.electron_impact",
                    "mass_spec.chemical_ionization",
                    "mass_spec.electrospray",
                    "mass_spec.maldi",
                    "mass_spec.fragmentation",
                    "mass_spec.tandem_ms",
                ],
                "count": 80,
            },
            "electron_microscopy": {
                "description": "SEM, TEM, EDS, EBSD, STEM, and electron beam parameters",
                "reference": "ASTM E766, ASTM E975, ASTM E1554, ASTM E1941",
                "fields": [
                    "sem.accelerating_voltage",
                    "sem.beam_current",
                    "sem.working_distance",
                    "sem.magnification",
                    "sem.detector",
                    "sem.secondary_electron",
                    "sem.backscattered_electron",
                    "sem.electron_detector",
                    "sem.etd_detector",
                    "sem.vcd_detector",
                    "sem.lds_detector",
                    "sem.chamber_pressure",
                    "sem.vacuum_mode",
                    "sem.high_vacuum",
                    "sem.low_vacuum",
                    "sem.variable_pressure",
                    "sem.esem_mode",
                    "sem.scan_speed",
                    "sem.scan_area",
                    "sem.pixel_size",
                    "sem.resolution",
                    "sem.depth_of_field",
                    "sem.focus",
                    "sem.stigmation",
                    "sem.astigmatism",
                    "sem.beam_diameter",
                    "sem.spot_size",
                    "sem.convergence_angle",
                    "sem.tilt_angle",
                    "sem.rotation",
                    "sem.image_histogram",
                    "sem.brightness",
                    "sem.contrast",
                    "sem.gamma",
                    "sem.lut",
                    "sem.false_color",
                    "tem.accelerating_voltage",
                    "tem.beam_current",
                    "tem.magnification",
                    "tem.resolution",
                    "tem. diffraction_mode",
                    "tem.imaging_mode",
                    "tem.bright_field",
                    "tem.dark_field",
                    "tem.high_resolution",
                    "tem.lattice_imaging",
                    "tem.selected_area_diffraction",
                    "tem.convergent_beam_diffraction",
                    "tem.nanobeam_diffraction",
                    "tem.spot_size",
                    "tem.probe_size",
                    "tem.condenser_aperture",
                    "tem.objective_aperture",
                    "tem.selected_area_aperture",
                    "tem.camera_length",
                    "tem.camera_constant",
                    "tem.defocus",
                    "tem.scherzer_defocus",
                    "tem.through_focus_series",
                    "tem.phase_plate",
                    "tem.holography",
                    "tem.energy_filter",
                    "tem.zero_loss_peak",
                    "tem.plasmon_loss",
                    "tem.core_loss",
                    "tem.thickness_map",
                    "tem.eels_spectrum",
                    "eds.detector",
                    "eds.silicon_drift",
                    "eds.sdd_detector",
                    "eds.energy_resolution",
                    "eds.count_rate",
                    "eds.deadtime",
                    "eds.peak_overlap",
                    "eds.quantification",
                    "eds.standardless",
                    "eds.standard_based",
                    "eds.zaf_correction",
                    "eds.piece_correction",
                    "eds.oxygen_calculation",
                    "eds.mapping",
                    "eds.line_scan",
                    "eds.point_spectrum",
                    "ebsd.detector",
                    "ebsd.pattern",
                    "ebsd.hough_transform",
                    "ebsd.indexing",
                    "ebsd.band_detection",
                    "ebsd.hkl_measurement",
                    "ebsd.orientation",
                    "ebsd.misorientation",
                    "ebsd.grain_boundary",
                    "ebsd.texture",
                    "ebsd.pole_figure",
                    "ebsd.inverse_pole_figure",
                    "ebsd.orientation_map",
                    "ebsd.grain_size",
                    "ebsd.grain_detection",
                    "ebsd.strain_mapping",
                    "ebsd.confidence_index",
                    "ebsd.fit_index",
                ],
                "count": 80,
            },
            "surface_analysis": {
                "description": "AFM, XPS, SIMS, contact angle, surface energy, and surface characterization",
                "reference": "ASTM D7334, ASTM D5946, ASTM D4779, ISO 15989",
                "fields": [
                    "afm.mode",
                    "afm.contact_mode",
                    "afm.tapping_mode",
                    "afm.non_contact_mode",
                    "afm.intermittent_contact",
                    "afm.scan_size",
                    "afm.scan_rate",
                    "afm.scan_angle",
                    "afm.resolution",
                    "afm.line_count",
                    "afm.point_per_line",
                    "afm.z_range",
                    "afm.z_speed",
                    "afm.setpoint",
                    "afm.gain",
                    "afm.proportional_gain",
                    "afm.integral_gain",
                    "afm.feedback",
                    "afm.tip_radius",
                    "afm.tip_material",
                    "afm.tip_shape",
                    "afm.cantilever",
                    "afm.force_constant",
                    "afm.resonance_frequency",
                    "afm.quality_factor",
                    "afm.height",
                    "afm.amplitude",
                    "afm.phase",
                    "afm.adhesion",
                    "afm.friction",
                    "afm.stiffness",
                    "afm.elasticity",
                    "afm.viscoelasticity",
                    "afm.magnetic_force",
                    "afm.electrostatic_force",
                    "afm.kelvin_probe",
                    "afm.conductive_afm",
                    "afm.sem_afm",
                    "afm.crosstalk",
                    "afm.noise_level",
                    "xps.surface_energy",
                    "xps.work_function",
                    "xps.contact_potential",
                    "sims.primary_ion",
                    "sims.ion_type",
                    "sims.ion_energy",
                    "sims.ion_current",
                    "sims.sputter_rate",
                    "sims.depth_resolution",
                    "sims.lateral_resolution",
                    "sims.mass_resolution",
                    "sims.dynamic_sims",
                    "sims.static_sims",
                    "sims.secondary_ion",
                    "sims.positive_ion",
                    "sims.negative_ion",
                    "sims.csem_sims",
                    "sims.ims_sims",
                    "sims.tof_sims",
                    "contact_angle.contact_angle",
                    "contact_angle.advancing",
                    "contact_angle.receding",
                    "contact_angle.hysteresis",
                    "contact_angle.drop_volume",
                    "contact_angle.drop_shape",
                    "contact_angle.sessile_drop",
                    "contact_angle.pendant_drop",
                    "contact_angle.wilhelmy_plate",
                    "contact_angle.dyne_ink",
                    "contact_angle.surface_tension",
                    "surface_energy.total_surface_energy",
                    "surface_energy.dispersive",
                    "surface_energy.polar",
                    "surface_energy.acid_base",
                    "surface_energy.lifshitz_van_der_waals",
                    "surface_energy.electron_donor",
                    "surface_energy.electron_acceptor",
                ],
                "count": 70,
            },
            "thermal_analysis": {
                "description": "DSC, TGA, DTA, thermal conductivity, and thermal properties",
                "reference": "ASTM E967, ASTM E968, ASTM E1131, ASTM E1461, ISO 11357",
                "fields": [
                    "dsc.heat_flow",
                    "dsc.temperature",
                    "dsc.onset_temperature",
                    "dsc.peak_temperature",
                    "dsc.endset_temperature",
                    "dsc.heat_of_fusion",
                    "dsc.heat_of_crystallization",
                    "dsc.heat_of_reaction",
                    "dsc.glass_transition",
                    "dsc.tg_temperature",
                    "dsc.enthalpy",
                    "dsc.heat_capacity",
                    "dsc.specific_heat",
                    "dsc.cp",
                    "dsc.scan_rate",
                    "dsc.heating_rate",
                    "dsc.cooling_rate",
                    "dsc.isothermal",
                    "dsc.modulated_dsc",
                    "dsc.reverse_heat_flow",
                    "dsc.non_reversible",
                    "dsc.step_scan",
                    "dsc.heat_cool_heat",
                    "dsc.baseline",
                    "dsc.calibration",
                    "dsc.indium",
                    "dsc.zinc",
                    "dsc.tin",
                    "dsc.lead",
                    "dsc.sample_mass",
                    "dsc.sample_pan",
                    "dsc.reference_pan",
                    "dsc.atmosphere",
                    "dsc.nitrogen",
                    "dsc.air",
                    "dsc.oxygen",
                    "dsc.hermetic_seal",
                    "dsc.tga_mass",
                    "dsc.tga_loss",
                    "dsc.tga.gain",
                    "dsc.tga.residue",
                    "dsc.tga.decomposition",
                    "dsc.tga.derivative_thermogravimetry",
                    "dsc.tga.dtg",
                    "dsc.tga.isothermal",
                    "dsc.tga.step_isothermal",
                    "dsc.tga.evolved_gas",
                    "dsc.tga.coupling",
                    "dta.temperature_difference",
                    "dta.heat_flow",
                    "dta.onset",
                    "dta.peak",
                    "dta.peak_area",
                    "dta.sensitivity",
                    "dta.differential_temperature",
                    "dta.reference_material",
                    "thermal_conductivity",
                    "thermal.diffusivity",
                    "thermal.heat_capacity",
                    "thermal.density",
                    "thermal.conductivity_method",
                    "thermal.guarded_hot_plate",
                    "thermal.heat_flow_meter",
                    "thermal.laser_flash",
                    "thermal.transient_hot_wire",
                    "thermal.thermal_resistance",
                    "thermal.thermal_insulation",
                    "thermal.thermal_gradient",
                    "thermal.steady_state",
                    "thermal.transient",
                ],
                "count": 70,
            },
            "mechanical_testing": {
                "description": "Tensile, hardness, fatigue, fracture toughness, and mechanical properties",
                "reference": "ASTM E8, ASTM E10, ASTM E399, ASTM E466, ISO 6892",
                "fields": [
                    "tensile.stress",
                    "tensile.strain",
                    "tensile.yield_strength",
                    "tensile.yield_0.2_offset",
                    "tensile.ultimate_tensile",
                    "tensile.uts",
                    "tensile.breaking_strength",
                    "tensile.fracture_strength",
                    "tensile.elastic_modulus",
                    "tensile.youngs_modulus",
                    "tensile.poissons_ratio",
                    "tensile.uniform_elongation",
                    "tensile.total_elongation",
                    "tensile.area_reduction",
                    "tensile.section_reduction",
                    "tensile.strain_rate",
                    "tensile.crosshead_speed",
                    "tensile.gauge_length",
                    "tensile.specimen_type",
                    "tensile.flat_specimen",
                    "tensile.round_specimen",
                    "tensile.subsize_specimen",
                    "tensile.full_size_specimen",
                    "tensile.temperature",
                    "tensile.humidity",
                    "hardness.vickers",
                    "hardness.hv",
                    "hardness.brinell",
                    "hardness.hb",
                    "hardness.rockwell",
                    "hardness.hr",
                    "hardness.rockwell_scale",
                    "hardness.rockwell_a",
                    "hardness.rockwell_b",
                    "hardness.rockwell_c",
                    "hardness.microhardness",
                    "hardness.knoop",
                    "hardness.hk",
                    "hardness.load",
                    "hardness.dwell_time",
                    "hardness.indenter",
                    "hardness.indenter_material",
                    "hardness.indenter_geometry",
                    "hardness.indentation_size",
                    "hardness.indentation_diagonal",
                    "hardness.indentation_depth",
                    "hardness.meyer_hardness",
                    "fatigue.cycles",
                    "fatigue.stress",
                    "fatigue.strain",
                    "fatigue.s_n_curve",
                    "fatigue.epsilon_n_curve",
                    "fatigue.runout",
                    "fatigue.failure",
                    "fatigue.limit",
                    "fatigue.endurance_limit",
                    "fatigue.fatigue_strength",
                    "fatigue.fatigue_life",
                    "fatigue.stress_ratio",
                    "fatigue.r_ratio",
                    "fatigue.mean_stress",
                    "fatigue.alternating_stress",
                    "fracture_toughness.kic",
                    "fracture_toughness.kq",
                    "fracture_toughness.jic",
                    "fracture_toughness.ctod",
                    "fracture_toughness.precrack",
                    "fracture_toughness.specimen_type",
                    "fracture_toughness.ct_specimen",
                    "fracture_toughness.seb_specimen",
                    "fracture_toughness.double_cantilever",
                ],
                "count": 60,
            },
            "metrology_standards": {
                "description": "NIST traceable, calibration, uncertainty, and metrology standards",
                "reference": "NIST Handbook 150, ISO/IEC 17025, ISO GUM, BIPM",
                "fields": [
                    "nist_traceable.certificate",
                    "nist_traceable.standard",
                    "nist_traceable.reference_material",
                    "nist_traceable.srm",
                    "nist_traceable.crm",
                    "nist_traceable.calibration_laboratory",
                    "nist_traceable.accreditation",
                    "nist_traceable.a2la",
                    "nist_traceable.ansi",
                    "nist_traceable.iso_17025",
                    "calibration.date",
                    "calibration.due_date",
                    "calibration.interval",
                    "calibration.periodicity",
                    "calibration.procedure",
                    "calibration.method",
                    "calibration.standard",
                    "calibration.reference",
                    "calibration.traceability",
                    "calibration.uncertainty",
                    "calibration.expanded_uncertainty",
                    "calibration.coverage_factor",
                    "calibration.confidence_level",
                    "calibration.result",
                    "calibration.pass_fail",
                    "calibration.as_found",
                    "calibration.as_left",
                    "calibration.tolerance",
                    "calibration.limit",
                    "calibration.deviation",
                    "calibration.error",
                    "calibration.correction",
                    "calibration.offset",
                    "calibration.gain",
                    "calibration.linearity",
                    "calibration.hysteresis",
                    "calibration.repeatability",
                    "calibration.reproducibility",
                    "calibration.resolution",
                    "calibration.stability",
                    "calibration.drift",
                    "calibration.environmental",
                    "calibration.temperature",
                    "calibration.humidity",
                    "calibration.pressure",
                    "uncertainty.type_a",
                    "uncertainty.type_b",
                    "uncertainty.standard",
                    "uncertainty.combined",
                    "uncertainty.expanded",
                    "uncertainty.coverage_factor",
                    "uncertainty.propagation",
                    "uncertainty.monte_carlo",
                    "uncertainty.sensitivity",
                    "uncertainty.correlation",
                ],
                "count": 50,
            },
        },
        "totals": {
            "categories": 7,
            "total_fields": 500,
        }
    }

    return INVENTORY


def main():
    print("=" * 70)
    print("MATERIALS SCIENCE AND METROLOGY METADATA FIELD INVENTORY")
    print("=" * 70)
    print()

    inventory = generate_materials_inventory()

    print(f"Generated: {inventory['generated_at']}")
    print(f"Categories: {inventory['totals']['categories']}")
    print(f"Total Fields: {inventory['totals']['total_fields']}")
    print()

    print("FIELD COUNTS BY CATEGORY:")
    print("-" * 50)
    for cat_name, cat_data in sorted(inventory['categories'].items(), key=lambda x: x[1]['count'], reverse=True):
        print(f"  {cat_name:30s}: {cat_data['count']:>4} fields")

    output_dir = Path("dist/materials_inventory")
    output_dir.mkdir(parents=True, exist_ok=True)

    output_file = output_dir / "materials_inventory.json"
    output_file.write_text(json.dumps(inventory, indent=2, sort_keys=True), encoding="utf-8")
    print()
    print(f"Wrote: {output_file}")

    summary = {
        "generated_at": inventory["generated_at"],
        "source": inventory["source"],
        "description": inventory["description"],
        "categories": {
            k: {
                "count": v["count"],
                "description": v["description"],
                "reference": v.get("reference", "N/A")
            }
            for k, v in inventory["categories"].items()
        },
        "totals": inventory["totals"],
    }

    summary_file = output_dir / "materials_summary.json"
    summary_file.write_text(json.dumps(summary, indent=2, sort_keys=True), encoding="utf-8")
    print(f"Wrote: {summary_file}")


if __name__ == "__main__":
    main()
