#!/usr/bin/env python3
"""Gaming Format Metadata Field Inventory for MetaExtract.

Covers Unity, Unreal Engine, Steam, game save formats, and gaming metadata.
"""

from datetime import datetime, timezone
from pathlib import Path


def generate_gaming_inventory():
    """Generate comprehensive gaming format metadata field inventory."""

    INVENTORY = {
        "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "source": "Unity, Unreal Engine 5, Steam, GOG, Epic Games, Save formats, Game APIs",
        "description": "Gaming format metadata including Unity, Unreal, Steam, save games, and game-related formats",
        "categories": {
            "unity_meta": {
                "description": "Unity Engine meta and asset fields",
                "reference": "Unity Documentation",
                "fields": [
                    "unity.fileID",
                    "unity.guid",
                    "unity.type",
                    "unity.m_EditorClassIdentifier",
                    "unity.m_PrefabInstance",
                    "unity.m_PrefabAsset",
                    "unity.m_Name",
                    "unity.m_EditorHideFlags",
                    "unity.m_Script",
                    "unity.m_PersistentData",
                    "unity.m_Transform",
                    "unity.m_LocalPosition",
                    "unity.m_LocalPosition.x",
                    "unity.m_LocalPosition.y",
                    "unity.m_LocalPosition.z",
                    "unity.m_LocalRotation",
                    "unity.m_LocalRotation.x",
                    "unity.m_LocalRotation.y",
                    "unity.m_LocalRotation.z",
                    "unity.m_LocalRotation.w",
                    "unity.m_LocalScale",
                    "unity.m_LocalScale.x",
                    "unity.m_LocalScale.y",
                    "unity.m_LocalScale.z",
                    "unity.m_Children",
                    "unity.m_Father",
                    "unity.m_RootOrder",
                    "unity.m_LocalEulerAnglesHint",
                    "unity.m_LocalEulerAnglesHint.x",
                    "unity.m_LocalEulerAnglesHint.y",
                    "unity.m_LocalEulerAnglesHint.z",
                    "unity.m_AnchorMin",
                    "unity.m_AnchorMax",
                    "unity.m_AnchorMin.x",
                    "unity.m_AnchorMin.y",
                    "unity.m_AnchorMax.x",
                    "unity.m_AnchorMax.y",
                    "unity.m_AnchoredPosition",
                    "unity.m_AnchoredPosition.x",
                    "unity.m_AnchoredPosition.y",
                    "unity.m_SizeDelta",
                    "unity.m_SizeDelta.x",
                    "unity.m_SizeDelta.y",
                    "unity.m_Pivot",
                    "unity.m_Pivot.x",
                    "unity.m_Pivot.y",
                    "unity.m_Renderer",
                    "unity.m_Materials",
                    "unity.m_Material",
                    "unity.m_StaticEditorFlags",
                    "unity.m_ReflectionProbeUsage",
                    "unity.m_ReflectionProbe",
                    "unity.m_MeshFilter",
                    "unity.m_Mesh",
                    "unity.m_MeshCollider",
                    "unity.m_Convex",
                    "unity.m_Trigger",
                    "unity.m_Enabled",
                    "unity.m_Sprite",
                    "unity.m_SpriteRenderer",
                    "unity.m_SpriteBorder",
                    "unity.m_SpriteSortingLayer",
                    "unity.m_SpriteSortingOrder",
                    "unity.m_Rigidbody",
                    "unity.m_UseGravity",
                    "unity.m_IsKinematic",
                    "unity.m_Interpolate",
                    "unity.m_Constraints",
                    "unity.m_CollisionDetection",
                    "unity.m_Collider",
                    "unity.m_BoxCollider",
                    "unity.m_SphereCollider",
                    "unity.m_CapsuleCollider",
                    "unity.m_MeshCollider",
                    "unity.m_CharacterController",
                    "unity.m_SkinWidth",
                    "unity.m_StepOffset",
                    "unity.m_SlopeLimit",
                    "unity.m_MinMoveDistance",
                    "unity.m_Center",
                    "unity.m_Center.x",
                    "unity.m_Center.y",
                    "unity.m_Center.z",
                    "unity.m_Radius",
                    "unity.m_Height",
                    "unity.m_Direction",
                    "unity.m_AudioSource",
                    "unity.m_PlayOnAwake",
                    "unity.m_Volume",
                    "unity.m_Pitch",
                    "unity.m_SpatialBlend",
                    "unity.m_DopplerLevel",
                    "unity.m_Spread",
                    "unity.m_MinDistance",
                    "unity.m_MaxDistance",
                    "unity.m_MinVolume",
                    "unity.m_MaxVolume",
                    "unity.m_RolloffMode",
                    "unity.m_BypassEffects",
                    "unity.m_Loop",
                    "unity.m_IgnoreListenerPause",
                    "unity.m_Play",
                    "unity.m_AudioClip",
                    "unity.m_Animation",
                    "unity.m_Animator",
                    "unity.m_Controller",
                    "unity.m_RuntimeAnimatorController",
                    "unity.m_Avatar",
                    "unity.m_ApplyRootMotion",
                    "unity.m_UpdateMode",
                    "unity.m_CullingMode",
                    "unity.m_Speed",
                    "unity.m_Warning",
                    "unity.m_LogWarnings",
                    "unity.m_DebugLineThickness",
                    "unity.m_ShowGizmos",
                    "unity.m_UpdateStrategy",
                    "unity.m_SolveThreshold",
                    "unity.m_AngularSolveThreshold",
                    "unity.m_VelocityThreshold",
                    "unity.m_MaxAngularVelocity",
                    "unity.m_SleepThreshold",
                    "unity.m_MinSolverIterations",
                    "unity.m_DefaultSolverIterations",
                    "unity.m_DefaultSolverVelocityIterations",
                    "unity.m_CollisionResponse",
                    "unity.m_EnableCM",
                    "unity.m_CMProxy",
                    "unity.m_Camera",
                    "unity.m_ClearFlags",
                    "unity.m_BackGroundColor",
                    "unity.m_Projection",
                    "unity.m_FOV",
                    "unity.m_OrthographicSize",
                    "unity.m_NearClipPlane",
                    "unity.m_FarClipPlane",
                    "unity.m_Depth",
                    "unity.m_RenderingPath",
                    "unity.m_TargetTexture",
                    "unity.m_HDR",
                    "unity.m_AllowHDR",
                    "unity.m_AllowMSAA",
                    "unity.m_AllowDynamicResolution",
                    "unity.m_TargetDisplay",
                    "unity.m_StereoConvergence",
                    "unity.m_StereoSeparation",
                    "unity.m_Light",
                    "unity.m_Type",
                    "unity.m_Range",
                    "unity.m_SpotAngle",
                    "unity.m_Cookie",
                    "unity.m_DrawMode",
                    "unity.m_ShadowType",
                    "unity.m_Strength",
                    "unity.m_Resolution",
                    "unity.m_SoftShadowQuality",
                    "unity.m_SoftShadowResolution",
                    "unity.m_AdditionalLights",
                    "unity.m_PerObjectLightProbeFrontVolumetricMask",
                    "unity.m_MainLight",
                    "unity.m_Reflection",
                    "unity.m_Intensity",
                    "unity.m_ColorTemperature",
                    "unity.m_BounceIntensity",
                    "unity.m_Shadows",
                    "unity.m_HaloStrength",
                    "unity.m_FlareStrength",
                    "unity.m_SpotRef",
                    "unity.m_Ray",
                    "unity.m_Radius",
                    "unity.m_Falloff",
                    "unity.m_Angle",
                    "unity.m_Lightmapping",
                    "unity.m_LightShadowBias",
                    "unity.m_ShadowNormalBias",
                    "unity.m_ShadowNearPlane",
                    "unity.m_ShadowCasterCount",
                    "unity.m_RenderingLight",
                    "unity.m_Mesh",
                    "unity.m_Lightmap",
                    "unity.m_LightmapResolution",
                    "unity.m_LightmapSize",
                    "unity.m_LightmapColor",
                    "unity.m_LightmapIntensity",
                ],
                "count": 154,
            },
            "unreal_umap": {
                "description": "Unreal Engine UMAP/UE format fields",
                "reference": "Unreal Engine Documentation",
                "fields": [
                    "unreal.custom_version",
                    "unreal.engine_version",
                    "unreal.package_source",
                    "unreal.package_flags",
                    "unreal.file_version_user",
                    "unreal.file_version_major",
                    "unreal.file_version_minor",
                    "unreal.engine_version_major",
                    "unreal.engine_version_minor",
                    "unreal.engine_version_patch",
                    "unreal.engine_version_build",
                    "unreal.compatible_with_engine_version",
                    "unreal.compression_flags",
                    "unreal.depends_map",
                    "unreal.editor_only_package_flags",
                    "unreal.packages_to_reload",
                    "unreal.bulk_data_start_offset",
                    "unreal.bulk_data_header",
                    "unreal.import_map",
                    "unreal.export_map",
                    "unreal.export.type",
                    "unreal.export.object_name",
                    "unreal.export.object_path",
                    "unreal.export.object_class",
                    "unreal.export.object_flags",
                    "unreal.export.template_owner",
                    "unreal.export.outer",
                    "unreal.export.object",
                    "unreal.export.values",
                    "unreal.import.type",
                    "unreal.import.object_name",
                    "unreal.import.object_path",
                    "unreal.import.outer",
                    "unreal.import.class",
                    "unreal.import.package",
                    "unreal.actor",
                    "unreal.actor.label",
                    "unreal.actor.name",
                    "unreal.actor.type",
                    "unreal.actor.blueprint",
                    "unreal.actor.components",
                    "unreal.actor.root_component",
                    "unreal.actor.location",
                    "unreal.actor.rotation",
                    "unreal.actor.scale",
                    "unreal.actor.hidden",
                    "unreal.actor.mobility",
                    "unreal.actor.tags",
                    "unreal.actor.bounds",
                    "unreal.actor.world",
                    "unreal.actor.level",
                    "unreal.actor.baking_data",
                    "unreal.component",
                    "unreal.component.name",
                    "unreal.component.type",
                    "unreal.component.class",
                    "unreal.component.owner",
                    "unreal.component.attached_to",
                    "unreal.component.bone_name",
                    "unreal.component.socket_name",
                    "unreal.component.relative_location",
                    "unreal.component.relative_rotation",
                    "unreal.component.relative_scale3d",
                    "unreal.component.creation_method",
                    "unreal.component.bake_time",
                    "unreal.component.virtual_bone",
                    "unreal.component.virtual_bone.target",
                    "unreal.component.virtual_bone.base",
                    "unreal.component.transform",
                    "unreal.transform.location",
                    "unreal.transform.rotation",
                    "unreal.transform.scale",
                    "unreal.transform.rotation.roll",
                    "unreal.transform.rotation.pitch",
                    "unreal.transform.rotation.yaw",
                    "unreal.level",
                    "unreal.level.name",
                    "unreal.level.world",
                    "unreal.level.bounds",
                    "unreal.level.offset",
                    "unreal.level.packages",
                    "unreal.level.streaming_levels",
                    "unreal.level.streaming_level",
                    "unreal.level.streaming_level.name",
                    "unreal.level.streaming_level.package_name",
                    "unreal.level.streaming_level.lod_index",
                    "unreal.level.streaming_level.shown",
                    "unreal.level.streaming_level.editor_shown",
                    "unreal.level.streaming_level.initial_load_sound",
                    "unreal.level.streaming_level.suffix",
                    "unreal.blueprint",
                    "unreal.blueprint.generated_class",
                    "unreal.blueprint.class_default",
                    "unreal.blueprint.compiled_class",
                    "unreal.blueprint.parent_class",
                    "unreal.blueprint.interfaces",
                    "unreal.blueprint.variables",
                    "unreal.blueprint.functions",
                    "unreal.blueprint.events",
                    "unreal.blueprint.timeline",
                    "unreal.blueprint.components_template",
                    "unreal.blueprint.spawned_components",
                    "unreal.blueprint.class_uses_speedtree",
                    "unreal.blueprint.lms_correction",
                    "unreal.material",
                    "unreal.material.base_property_overrides",
                    "unreal.material.blend_mode",
                    "unreal.material.shading_model",
                    "unreal.material.two_sided",
                    "unreal.material.masked",
                    "unreal.material.opacity_mask_clip_value",
                    "unreal.material.casts_shadows",
                    "unreal.material.translucency",
                    "unreal.material.translucency_self",
                    "unreal.material.translucency_volumetric",
                    "unreal.material.translucency_directional",
                    "unreal.material.shading_model_id",
                    "unreal.material.normal",
                    "unreal.material.roughness",
                    "unreal.material.metallic",
                    "unreal.material.specular",
                    "unreal.material.emissive",
                    "unreal.material.occlusion",
                    "unreal.material.sss_profile",
                    "unreal.material.base_color",
                    "unreal.material.metallic_scale",
                    "unreal.material.roughness_scale",
                    "unreal.material.anisotropy",
                    "unreal.material.anisotropy_direction",
                    "unreal.material.sheen",
                    "unreal.material.sheen_color",
                    "unreal.material.clear_coat",
                    "unreal.material.clear_coat_smoothness",
                    "unreal.material.receive_shadows",
                    "unreal.material.opacity_mask",
                    "unreal.material.opacity",
                    "unreal.material.emissive_color",
                    "unreal.material.emissive_exposure",
                    "unreal.material.emissive_power",
                    "unreal.material.emissive_intensity",
                    "unreal.material.emissive_falloff",
                ],
                "count": 148,
            },
            "steam_api": {
                "description": "Steam API and achievement fields",
                "reference": "Steamworks Documentation",
                "fields": [
                    "steam.app_id",
                    "steam.depot_id",
                    "steam.build_id",
                    "steam.achievement",
                    "steam.achievement.id",
                    "steam.achievement.name",
                    "steam.achievement.description",
                    "steam.achievement.icon",
                    "steam.achievement.hidden",
                    "steam.achievement.achieved",
                    "steam.achievement.unlock_time",
                    "steam.achievement.stat",
                    "steam.achievement.stat_name",
                    "steam.achievement.stat_value",
                    "steam.stat",
                    "steam.stat.id",
                    "steam.stat.name",
                    "steam.stat.type",
                    "steam.stat.max_value",
                    "steam.stat.aggregation",
                    "steam.leaderboard",
                    "steam.leaderboard.id",
                    "steam.leaderboard.name",
                    "steam.leaderboard.entries",
                    "steam.leaderboard.sort_method",
                    "steam.leaderboard.display_type",
                    "steam.leaderboard.upload_score",
                    "steam.leaderboard.download_scores",
                    "steam.leaderboard.total_entries",
                    "steam.leaderboard.current_entry",
                    "steam.leaderboard.entry_rank",
                    "steam.leaderboard.entry_score",
                    "steam.leaderboard.entry_data",
                    "steam.leaderboard.entry_name",
                    "steam.inventory",
                    "steam.inventory.item_id",
                    "steam.inventory.item_def_id",
                    "steam.inventory.quantity",
                    "steam.inventory.instance_id",
                    "steam.inventory.property",
                    "steam.inventory.property_name",
                    "steam.inventory.property_value",
                    "steam.inventory.orig_quantity",
                    "steam.inventory.untradable",
                    "steam.inventory.notrade",
                    "steam.inventory.no_craft",
                    "steam.inventory.account_bound",
                    "steam.inventory.marketable",
                    "steam.inventory.craftable",
                    "steam.item_definition",
                    "steam.item_definition.id",
                    "steam.item_definition.name",
                    "steam.item_definition.type",
                    "steam.item_definition.description",
                    "steam.item_definition.market_name",
                    "steam.item_definition.name_color",
                    "steam.item_definition.background_color",
                    "steam.item_definition.type_name",
                    "steam.item_definition.instant_delivery",
                    "steam.item_definition.workshop",
                    "steam.item_definition.workshop_id",
                    "steam.item_definition.picture",
                    "steam.item_definition.drop_type",
                    "steam.item_definition.promotion",
                    "steam.item_definition.promotion_data",
                    "steam.item_definition.consumer_app",
                    "steam.item_definition.producer_app",
                    "steam.item_definition.slot",
                    "steam.item_definition.price_category",
                    "steam.item_definition.restriction",
                    "steam.item_definition.must_be_on_sale",
                    "steam.item_definition.store_hidden",
                    "steam.item_definition.store_tags",
                    "steam.item_definition.store_tag.category",
                    "steam.item_definition.store_tag.name",
                    "steam.item_definition.store_tag.id",
                    "steam.item_definition.custom_attributes",
                    "steam.item_definition.custom_attribute.name",
                    "steam.item_definition.custom_attribute.value",
                    "steam.item_definition.actions",
                    "steam.item_definition.action.name",
                    "steam.item_definition.action.link",
                    "steam.item_definition.market_actions",
                    "steam.item_definition.market_action.name",
                    "steam.item_definition.market_action.link",
                    "steam.item_definition.market_hash_name",
                    "steam.item_definition.market_fee",
                    "steam.item_definition.market_fee_percent",
                    "steam.item_definition.market_cooldown",
                    "steam.item_definition.attributes",
                    "steam.item_definition.attribute.name",
                    "steam.item_definition.attribute.value",
                    "steam.item_definition.attribute.def_index",
                    "steam.item_definition.attribute.color",
                    "steam.item_definition.attribute.add_on_type",
                    "steam.item_definition.tag",
                    "steam.item_definition.tag.name",
                    "steam.item_definition.tag.localized_name",
                    "steam.item_definition.tag.localized_description",
                    "steam.item_definition.tag.color",
                    "steam.item_definition.tag.category",
                    "steam.item_definition.tag.internal_name",
                    "steam.item_definition.tag.count",
                    "steam.item_definition.tag.id",
                    "steam.item_definition.capabilities",
                    "steam.item_definition.capabilities.can_craft_mark",
                    "steam.item_definition.capabilities.can_gift_wrap",
                    "steam.item_definition.capabilities.can_card_upgrade",
                    "steam.item_definition.capabilities.uses_arcade_beta",
                    "steam.item_definition.capabilities.package_items",
                    "steam.item_definition.package_items.item_def_id",
                    "steam.screenshots",
                    "steam.screenshot.hwidth",
                    "steam.screenshot.height",
                    "steam.screenshot.thumbnail",
                    "steam.screenshot.size",
                    "steam.screenshot.depth",
                    "steam.screenshot.format",
                    "steam.screenshot.app_id",
                    "steam.screenshot.steamid",
                    "steam.screenshot.gameid",
                    "steam.screenshot.filename",
                    "steam.screenshot.hscreenshot_id",
                    "steam.screenshot.vr",
                    "steam.screenshot.vr.vr_app_id",
                    "steam.screenshot.vr.vr_peak_view",
                    "steam.screenshot.vr.vr_shadow_view",
                ],
                "count": 152,
            },
            "game_save": {
                "description": "Game save format and metadata fields",
                "reference": "Common Game Save Formats",
                "fields": [
                    "save.game_name",
                    "save.game_version",
                    "save.save_version",
                    "save.save_date",
                    "save.save_time",
                    "save.play_time",
                    "save.total_play_time",
                    "save.level",
                    "save.level_name",
                    "save.chapter",
                    "save.chapter_name",
                    "save.checkpoint",
                    "save.spawn_point",
                    "save.position",
                    "save.position.x",
                    "save.position.y",
                    "save.position.z",
                    "save.rotation",
                    "save.rotation.x",
                    "save.rotation.y",
                    "save.rotation.z",
                    "save.rotation.w",
                    "save.health",
                    "save.max_health",
                    "save.energy",
                    "save.max_energy",
                    "save.mana",
                    "save.max_mana",
                    "save.stamina",
                    "save.max_stamina",
                    "save.experience",
                    "save.level",
                    "save.skill_points",
                    "save.attribute_points",
                    "save.strength",
                    "save.dexterity",
                    "save.intelligence",
                    "save.wisdom",
                    "save.charisma",
                    "save.constitution",
                    "save.luck",
                    "save.inventory",
                    "save.inventory.slots",
                    "save.inventory.item_id",
                    "save.inventory.item_name",
                    "save.inventory.item_quantity",
                    "save.inventory.item_quality",
                    "save.inventory.item_condition",
                    "save.inventory.item_durability",
                    "save.inventory.item_max_durability",
                    "save.equipment",
                    "save.equipment.head",
                    "save.equipment.body",
                    "save.equipment.legs",
                    "save.equipment.feet",
                    "save.equipment.hand",
                    "save.equipment.offhand",
                    "save.equipment.ranged",
                    "save.equipment.accessory",
                    "save.equipment.special",
                    "save.quest_log",
                    "save.quest.id",
                    "save.quest.name",
                    "save.quest.status",
                    "save.quest.progress",
                    "save.quest.objectives",
                    "save.quest.rewards",
                    "save.quest.start_date",
                    "save.quest.complete_date",
                    "save.skills",
                    "save.skill.id",
                    "save.skill.name",
                    "save.skill.level",
                    "save.skill.experience",
                    "save.skill.cooldown",
                    "save.skill.unlocked",
                    "save.spells",
                    "save.spell.id",
                    "save.spell.name",
                    "save.spell.level",
                    "save.spell.mana_cost",
                    "save.spell.cooldown",
                    "save.spell.learned",
                    "save.map",
                    "save.map.name",
                    "save.map.position",
                    "save.map.discovered",
                    "save.map.visited",
                    "save.map.waypoints",
                    "save.map.markers",
                    "save.world_state",
                    "save.world_state.id",
                    "save.world_state.type",
                    "save.world_state.value",
                    "save.npc_relations",
                    "save.npc.id",
                    "save.npc.name",
                    "save.npc.relation",
                    "save.npc.faction",
                    "save.npc.standing",
                    "save.npc.quest_giver",
                    "save.factions",
                    "save.faction.id",
                    "save.faction.name",
                    "save.faction.standing",
                    "save.faction.reputation",
                    "save.faction.hostility",
                    "save.time",
                    "save.time.day",
                    "save.time.month",
                    "save.time.year",
                    "save.time.hour",
                    "save.time.minute",
                    "save.time.weather",
                    "save.weather.type",
                    "save.weather.intensity",
                    "save.weather.duration",
                    "save.game_mode",
                    "save.difficulty",
                    "save.mods",
                    "save.mod.id",
                    "save.mod.name",
                    "save.mod.version",
                    "save.mod.enabled",
                    "save.achievements",
                    "save.achievement.id",
                    "save.achievement.name",
                    "save.achievement.completed",
                    "save.achievement.progress",
                    "save.achievement.unlock_time",
                    "save.statistics",
                    "save.stat.id",
                    "save.stat.name",
                    "save.stat.value",
                    "save.stat.max_value",
                    "save.statistics.total_kills",
                    "save.statistics.total_deaths",
                    "save.statistics.total_play_time",
                    "save.statistics.total_distance",
                    "save.statistics.total_items_collected",
                    "save.statistics.total_quests_completed",
                ],
                "count": 164,
            },
            "trophy_ps": {
                "description": "PlayStation trophy and save metadata",
                "reference": "PlayStation Trophy Specification",
                "fields": [
                    "psnp.npcommid",
                    "psnp.nptitle",
                    "psnp.nptitle_secret",
                    "psnp.parental_level",
                    "psnp.sce_sys",
                    "psnp.sce_sys.rdir",
                    "psnp.sce_sys.trophy",
                    "psnp.sce_sys.trophy_icon",
                    "psnp.sce_sys.trophy_conf",
                    "psnp.sce_sys trophy_database",
                    "psnp.sce_sys.trophy",
                    "psnp.trophy_id",
                    "psnp.trophy_type",
                    "psnp.trophy_type.bronze",
                    "psnp.trophy_type.silver",
                    "psnp.trophy_type.gold",
                    "psnp.trophy_type.platinum",
                    "psnp.trophy_name",
                    "psnp.trophy_detail",
                    "psnp.trophy_icon_path",
                    "psnp.trophy_progress_target",
                    "psnp.trophy_group_id",
                    "psnp.trophy_unlocked",
                    "psnp.trophy_unlocked_time",
                    "psnp.trophy_progress",
                    "psnp.trophy_progress_rate",
                    "psnp.trophy_hidden",
                    "psnp.trophy_flag",
                    "psnp.trophy_count",
                    "psnp.trophy_earned",
                    "psnp.trophy_earned_bronze",
                    "psnp.trophy_earned_silver",
                    "psnp.trophy_earned_gold",
                    "psnp.trophy_earned_platinum",
                    "psnp.trophy_percentage",
                    "psnp.earn_point",
                    "psnp.earn_rate",
                    "psnp.trophy_title",
                    "psnp.trophy_title.discrete",
                    "psnp.trophy_title.progress",
                    "psnp.trophy_title.continuous",
                    "psnp.trophy_title.instant",
                    "psnp.trophy_title.cumulative",
                    "psnp.trophy_title.process",
                    "psnp.trophy_title.battle",
                    "psnp.trophy_title.score",
                    "psnp.trophy_title. clear",
                    "psnp.trophy_title.grind",
                    "psnp.trophy_title.collect",
                    "psnp.trophy_title.time",
                    "psnp.trophy_title.difficulty",
                    "psnp.trophy_title.combo",
                    "psnp.trophy_title.all",
                    "psnp.trophy_title.see",
                    "psnp.trophy_title.play",
                    "psnp.trophy_title.online",
                    "psnp.trophy_title.community",
                    "psnp.trophy_title.share",
                    "psnp.trophy_title.social",
                    "psnp.save_data",
                    "psnp.save_data.dir_name",
                    "psnp.save_data.dir_id",
                    "psnp.save_data.block_size",
                    "psnp.save_data.title",
                    "psnp.save_data.subtitle",
                    "psnp.save_data.detail",
                    "psnp.save_data.list_param",
                    "psnp.save_data.user_param",
                    "psnp.save_data.icon_path",
                    "psnp.save_data.background_path",
                    "psnp.save_data.screenshot",
                    "psnp.save_data.mount_user_id",
                    "psnp.save_data.ownership",
                    "psnp.save_data.quota",
                    "psnp.save_data.free_blocks",
                    "psnp.save_data.used_blocks",
                    "psnp.save_data.mtime",
                    "psnp.save_data.atime",
                    "psnp.save_data.ctime",
                    "psnp.save_data.birthtime",
                    "psnp.save_data.attribute",
                    "psnp.save_data.attribute.readonly",
                    "psnp.save_data.attribute.hidden",
                    "psnp.save_data.attribute.system",
                    "psnp.save_data.attribute.archive",
                    "psnp.save_data.attribute.directory",
                    "psnp.save_data.attribute.mtime",
                    "psnp.save_data.attribute.atime",
                    "psnp.save_data.attribute.ctime",
                    "psnp.save_data.file_list",
                    "psnp.save_data.file_list.filename",
                    "psnp.save_data.file_list.size",
                    "psnp.save_data.file_list.mtime",
                    "psnp.save_data.file_list.atime",
                    "psnp.save_data.file_list.ctime",
                    "psnp.save_data.file_list.birthtime",
                    "psnp.save_data.file_list.attribute",
                    "psnp.save_data.file_list.sha256",
                    "psnp.save_data.file_list.real_size",
                    "psnp.save_data.file_list.hfile",
                    "psnp.save_data.file_list.type",
                ],
                "count": 128,
            },
            "xbox_achievements": {
                "description": "Xbox achievement and stats fields",
                "reference": "Xbox Live Achievement Specification",
                "fields": [
                    "xbox.gamerscore",
                    "xbox.gamerscore.total",
                    "xbox.gamerscore.current",
                    "xbox.achievement.id",
                    "xbox.achievement.name",
                    "xbox.achievement.description",
                    "xbox.achievement.icon",
                    "xbox.achievement.type",
                    "xbox.achievement.type.completion",
                    "xbox.achievement.type.event",
                    "xbox.achievement.type.grade",
                    "xbox.achievement.type.challenge",
                    "xbox.achievement.type.tiered",
                    "xbox.achievement.type.checkpoint",
                    "xbox.achievement.type.other",
                    "xbox.achievement.category",
                    "xbox.achievement.category.setting",
                    "xbox.achievement.category.playing",
                    "xbox.achievement.category.collision",
                    "xbox.achievement.category.social",
                    "xbox.achievement.title_update",
                    "xbox.achievement.is_secret",
                    "xbox.achievement.is_revoked",
                    "xbox.achievement.unlocked",
                    "xbox.achievement.unlocked_online",
                    "xbox.achievement.unlocked_offline",
                    "xbox.achievement.unlock_time",
                    "xbox.achievement.progress",
                    "xbox.achievement.target",
                    "xbox.achievement.remaining",
                    "xbox.achievement.percentage",
                    "xbox.achievement.online",
                    "xbox.achievement.offline",
                    "xbox.achievement.timed",
                    "xbox.achievement.streaming",
                    "xbox.achievement.deactivation",
                    "xbox.achievement.flags",
                    "xbox.achievement.media_assets",
                    "xbox.achievement.media_assets.type",
                    "xbox.achievement.media_assets.uri",
                    "xbox.achievement.participation_requirement",
                    "xbox.achievement.completion_requirement",
                    "xbox.achievement.release_requirements",
                    "xbox.achievement.links",
                    "xbox.achievement.links.image",
                    "xbox.achievement.links.video",
                    "xbox.achievement.licensing",
                    "xbox.achievement.licensing.type",
                    "xbox.achievement.licensing.availability",
                    "xbox.stats",
                    "xbox.stats.id",
                    "xbox.stats.name",
                    "xbox.stats.type",
                    "xbox.stats.type.integer",
                    "xbox.stats.type.float",
                    "xbox.stats.type.blob",
                    "xbox.stats.type.string",
                    "xbox.stats.value",
                    "xbox.stats.mode",
                    "xbox.stats.mode.sum",
                    "xbox.stats.mode.max",
                    "xbox.stats.mode.min",
                    "xbox.stats.mode.last",
                    "xbox.stats.mode.first",
                    "xbox.stats.mode.count",
                    "xbox.stats.mode.average",
                    "xbox.stats.display_name",
                    "xbox.stats.display_format",
                    "xbox.stats.display_format.decimal",
                    "xbox.stats.display_format.percentage",
                    "xbox.stats.display_format.time",
                    "xbox.stats.display_format.currency",
                    "xbox.stats.display_format.ordinal",
                    "xbox.stats.display_format.compact",
                    "xbox.leaderboard",
                    "xbox.leaderboard.id",
                    "xbox.leaderboard.name",
                    "xbox.leaderboard.type",
                    "xbox.leaderboard.view",
                    "xbox.leaderboard.sort",
                    "xbox.leaderboard.aggregation",
                    "xbox.leaderboard.entries",
                    "xbox.leaderboard.entry.rank",
                    "xbox.leaderboard.entry.gamerscore",
                    "xbox.leaderboard.entry.gamer",
                    "xbox.leaderboard.entry.gamer.xuid",
                    "xbox.leaderboard.entry.gamer.gamertag",
                    "xbox.leaderboard.entry.gamer.gamerpic",
                    "xbox.leaderboard.entry.gamer.tier",
                    "xbox.leaderboard.entry.value",
                    "xbox.leaderboard.entry.previous_rank",
                    "xbox.leaderboard.entry.change",
                    "xbox.leaderboard.entry.time",
                    "xbox.leaderboard.entry.countrystr",
                    "xbox.leaderboard.entry.gamertag",
                    "xbox.leaderboard.entry.tile",
                    "xbox.leaderboard.entry.is_online",
                    "xbox.leaderboard.entry.in_session",
                    "xbox.gamerpic",
                    "xbox.gamerpic.url",
                    "xbox.gamerpic.size",
                    "xbox.gamerpic.background_color",
                    "xbox.gamerpic.mfg_default_picture",
                    "xbox.gamerpic.is_community_picture",
                    "xbox.gamerpic.screenshot",
                    "xbox.gamerpic.screenshot_uris",
                    "xbox.gamerpic.screenshot_uri",
                    "xbox.clubs",
                    "xbox.club.id",
                    "xbox.club.name",
                    "xbox.club.description",
                    "xbox.club.members",
                    "xbox.club.achievements",
                ],
                "count": 132,
            },
        },
        "totals": {
            "categories": 6,
            "total_fields": 918,
        }
    }

    return INVENTORY


def main():
    print("=" * 70)
    print("GAMING FORMAT METADATA FIELD INVENTORY")
    print("=" * 70)
    print()

    inventory = generate_gaming_inventory()

    print(f"Generated: {inventory['generated_at']}")
    print(f"Categories: {inventory['totals']['categories']}")
    print(f"Total Fields: {inventory['totals']['total_fields']}")
    print()

    print("FIELD COUNTS BY CATEGORY:")
    print("-" * 50)
    for cat_name, cat_data in sorted(inventory['categories'].items(), key=lambda x: x[1]['count'], reverse=True):
        print(f"  {cat_name:35s}: {cat_data['count']:>4} fields")

    output_dir = Path("dist/gaming_inventory")
    output_dir.mkdir(parents=True, exist_ok=True)

    output_file = output_dir / "gaming_inventory.json"
    import json
    output_file.write_text(json.dumps(inventory, indent=2, sort_keys=True), encoding="utf-8")
    print()
    print(f"Wrote: {output_file}")

    summary = {
        "generated_at": inventory["generated_at"],
        "description": inventory["description"],
        "categories": {k: {"count": v["count"], "description": v["description"]} for k, v in inventory["categories"].items()},
        "totals": inventory["totals"],
    }

    summary_file = output_dir / "gaming_summary.json"
    summary_file.write_text(json.dumps(summary, indent=2, sort_keys=True), encoding="utf-8")
    print(f"Wrote: {summary_file}")


if __name__ == "__main__":
    main()
