#!/usr/bin/env python3
"""Medical/Healthcare Metadata Field Inventory for MetaExtract.

Covers HL7 v2.x, FHIR R4, DICOM, CDA, ICD-10, SNOMED, LOINC, and IHE/XDS standards.
"""

from datetime import datetime, timezone
import json
from pathlib import Path


def generate_medical_inventory():
    """Generate comprehensive medical/healthcare metadata field inventory."""

    INVENTORY = {
        "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "source": "HL7 v2.x, FHIR R4, DICOM, CDA, ICD-10, SNOMED CT, LOINC, IHE XDS specifications",
        "description": "Medical/healthcare metadata fields including HL7 v2.x, FHIR R4, DICOM, CDA, ICD-10, SNOMED, LOINC, and IHE/XDS",
        "categories": {
            "hl7_v2_msh": {
                "description": "HL7 v2.x MSH (Message Header) segment fields",
                "reference": "HL7 v2.x Specification",
                "fields": [
                    "hl7.msh.field_separator",
                    "hl7.msh.encoding_characters",
                    "hl7.msh.sending_application",
                    "hl7.msh.sending_facility",
                    "hl7.msh.receiving_application",
                    "hl7.msh.receiving_facility",
                    "hl7.msh.date_time_of_message",
                    "hl7.msh.security",
                    "hl7.msh.message_type",
                    "hl7.msh.message_control_id",
                    "hl7.msh.processing_id",
                    "hl7.msh.version_id",
                    "hl7.msh.sequence_number",
                    "hl7.msh.continuation_pointer",
                    "hl7.msh.accept_acknowledgment_type",
                    "hl7.msh.application_acknowledgment_type",
                    "hl7.msh.country_code",
                    "hl7.msh.character_set",
                    "hl7.msh.principal_language_of_message",
                    "hl7.msh.alternate_character_set_handling_scheme",
                    "hl7.msh.message_profile_identifier",
                    "hl7.msh.sending_network_address",
                    "hl7.msh.receiving_network_address",
                ],
                "count": 23,
            },
            "hl7_v2_evn": {
                "description": "HL7 v2.x EVN (Event Type) segment fields",
                "reference": "HL7 v2.x Specification",
                "fields": [
                    "hl7.evn.event_type_code",
                    "hl7.evn.recorded_date_time",
                    "hl7.evn.event_planned_date_time",
                    "hl7.evn.event_reason_code",
                    "hl7.evn.operator_id",
                    "hl7.evn.event_occurred",
                    "hl7.evn.event_source",
                    "hl7.evn.event_dependent_pl",
                ],
                "count": 8,
            },
            "hl7_v2_pid": {
                "description": "HL7 v2.x PID (Patient Identification) segment fields",
                "reference": "HL7 v2.x Specification",
                "fields": [
                    "hl7.pid.set_id",
                    "hl7.pid.patient_id",
                    "hl7.pid.patient_identifier_list",
                    "hl7.pid.alternate_patient_id",
                    "hl7.pid.patient_name",
                    " hl7.pid.mother_maiden_name",
                    "hl7.pid.date_of_birth",
                    "hl7.pid.administrative_sex",
                    "hl7.pid.patient_alias",
                    "hl7.pid.race",
                    "hl7.pid.patient_address",
                    "hl7.pid.county_code",
                    "hl7.pid.phone_number_home",
                    "hl7.pid.phone_number_business",
                    "hl7.pid.primary_language",
                    "hl7.pid.marital_status",
                    "hl7.pid.religion",
                    "hl7.pid.patient_account_number",
                    "hl7.pid.ssn_number",
                    "hl7.pid.driver_license_number",
                    "hl7.pid.mother_identifier",
                    "hl7.pid.certified_death_date",
                    "hl7.pid.citizenship",
                    "hl7.pid.veterans_military_status",
                    "hl7.pid.nationality",
                    "hl7.pid.patient_death_date_time",
                    "hl7.pid.patient_death_indicator",
                    "hl7.pid.identity_unknown_indicator",
                    "hl7.pid.last_update_date_time",
                    "hl7.pid.last_update_facility",
                    "hl7.pid.species_code",
                    "hl7.pid.breed_code",
                    "hl7.pid.strain",
                    "hl7.pid.production_class_code",
                    "hl7.pid.tribal_citizenship",
                    "hl7.pid.patient_telecommunication_information",
                ],
                "count": 36,
            },
            "hl7_v2_pv1": {
                "description": "HL7 v2.x PV1 (Patient Visit) segment fields",
                "reference": "HL7 v2.x Specification",
                "fields": [
                    "hl7.pv1.set_id",
                    "hl7.pv1.patient_class",
                    "hl7.pv1.assigned_patient_location",
                    "hl7.pv1.admission_type",
                    "hl7.pv1.preadmit_number",
                    "hl7.pv1.prior_patient_location",
                    "hl7.pv1.attending_doctor",
                    "hl7.pv1.referring_doctor",
                    "hl7.pv1.consulting_doctor",
                    "hl7.pv1.hospital_service",
                    "hl7.pv1.temporary_location",
                    "hl7.pv1.pre_admit_test_indicator",
                    "hl7.pv1.re_admission_indicator",
                    "hl7.pv1.admit_source",
                    "hl7.pv1.ambulatory_status",
                    "hl7.pv1.vip_indicator",
                    "hl7.pv1.admitting_doctor",
                    "hl7.pv1.patient_type",
                    "hl7.pv1.visit_number",
                    "hl7.pv1.financial_class",
                    "hl7.pv1.charge_price_indicator",
                    "hl7.pv1.courtesy_code",
                    "hl7.pv1.credit_rating_code",
                    "hl7.pv1.contract_code",
                    "hl7.pv1.contract_effective_date",
                    "hl7.pv1.contract_amount",
                    "hl7.pv1.contract_period",
                    "hl7.pv1.interest_code",
                    "hl7.pv1.transfer_to_bad_debt_code",
                    "hl7.pv1.transfer_to_bad_debt_date",
                    "hl7.pv1.bad_debt_agency_code",
                    "hl7.pv1.bad_debt_transfer_amount",
                    "hl7.pv1.bad_debt_recovery_amount",
                    "hl7.pv1.delete_account_indicator",
                    "hl7.pv1.delete_account_date",
                    "hl7.pv1.discharge_disposition",
                    "hl7.pv1.discharged_to_location",
                    "hl7.pv1.diet_type",
                    "hl7.pv1.servicing_facility",
                    "hl7.pv1.bed_status",
                    "hl7.pv1.account_status",
                    "hl7.pv1.pending_location",
                    "hl7.pv1.prior_temporary_location",
                    "hl7.pv1.admit_date_time",
                    "hl7.pv1.discharge_date_time",
                ],
                "count": 43,
            },
            "hl7_v2_orc": {
                "description": "HL7 v2.x ORC (Order Control) segment fields",
                "reference": "HL7 v2.x Specification",
                "fields": [
                    "hl7.orc.order_control",
                    "hl7.orc.placer_order_number",
                    "hl7.orc.filler_order_number",
                    "hl7.orc.placer_group_number",
                    "hl7.orc.order_status",
                    "hl7.orc.response_flag",
                    "hl7.orc.quantity_timing",
                    "hl7.orc.parent_order",
                    "hl7.orc.date_time_of_transaction",
                    "hl7.orc.enter_by_person",
                    "hl7.orc.enter_by_organization",
                    "hl7.orc.enter_by_location",
                    "hl7.orc.parent_result",
                    "hl7.orc.filler_status",
                    "hl7.orc.placer_group_number",
                    "hl7.orc.order_type",
                    "hl7.orc.enterer",
                    "hl7.orc.order_group_number",
                    "hl7.orc.response_flag_code",
                    "hl7.orc.timing_quantity",
                    "hl7.orc.order_sequence",
                    "hl7.orc.transaction_code",
                    "hl7.orc.instruction",
                ],
                "count": 23,
            },
            "hl7_v2_obr": {
                "description": "HL7 v2.x OBR (Order Observation) segment fields",
                "reference": "HL7 v2.x Specification",
                "fields": [
                    "hl7.obr.set_id",
                    "hl7.obr.placer_order_number",
                    "hl7.obr.filler_order_number",
                    "hl7.obr.universal_service_id",
                    "hl7.obr.priority",
                    "hl7.obr.requested_date_time",
                    "hl7.obr.observation_date_time",
                    "hl7.obr.collection_date_time",
                    "hl7.obr.collection_volume",
                    "hl7.obr.authority",
                    "hl7.obr.remarks",
                    "hl7.obr.priority_obr",
                    "hl7.obr.parent_number",
                    "hl7.obr.filler_status",
                    "hl7.obr.results_status",
                    "hl7.obr.parent_result",
                    "hl7.obr.quantity_timing",
                    "hl7.obr.result_copies_to",
                    "hl7.obr.ancillary_services",
                    "hl7.obr.scope_of_coded_result",
                    "hl7.obr.identifier_type",
                    "hl7.obr.placer_group_number",
                    "hl7.obr.observation_category",
                    "hl7.obr.abortion_indication",
                    "hl7.obr.partial_completion_date_time",
                    "hl7.obr.number_of_sample_containers",
                    "hl7.obr.container_type",
                    "hl7.obr.container_condition",
                    "hl7.obr.relative_priority",
                ],
                "count": 29,
            },
            "hl7_v2_obx": {
                "description": "HL7 v2.x OBX (Observation/Result) segment fields",
                "reference": "HL7 v2.x Specification",
                "fields": [
                    "hl7.obx.set_id",
                    "hl7.obx.value_type",
                    "hl7.obx.observation_identifier",
                    "hl7.obx.observation_sub_id",
                    "hl7.obx.observation_value",
                    "hl7.obx.units",
                    "hl7.obx.reference_range",
                    "hl7.obx.abnormal_flags",
                    "hl7.obx.probability",
                    "hl7.obx.nature_of_abnormal_test",
                    "hl7.obx.observation_result_status",
                    "hl7.obx.effective_date_of_reference_range",
                    "hl7.obx.user_defined_access_checks",
                    "hl7.obx.date_time_of_the_observation",
                    "hl7.obx.producer_reference",
                    "hl7.obx.method_identifier",
                    "hl7.obx.equipment_instance_identifier",
                    "hl7.obx.material_id",
                    "hl7.obx.observation_site",
                    "hl7.obx.instance_identifier",
                    "hl7.obx.participation",
                    "hl7.obx.privacy_level",
                    "hl7.obx.observation_method",
                    "hl7.obx.species_code",
                    "hl7.obx.breed_code",
                    "hl7.obx.specimen_type",
                    "hl7.obx.container_type",
                    "hl7.obx.container_condition",
                    "hl7.obx.observation_description",
                    "hl7.obx.observation_value_parsed",
                ],
                "count": 30,
            },
            "fhir_patient": {
                "description": "FHIR R4 Patient resource fields",
                "reference": "FHIR R4 Specification",
                "fields": [
                    "fhir.patient.id",
                    "fhir.patient.meta",
                    "fhir.patient.implicitRules",
                    "fhir.patient.language",
                    "fhir.patient.text",
                    "fhir.patient.contained",
                    "fhir.patient.extension",
                    "fhir.patient.modifierExtension",
                    "fhir.patient.identifier",
                    "fhir.patient.active",
                    "fhir.patient.name",
                    "fhir.patient.telecom",
                    "fhir.patient.gender",
                    "fhir.patient.birthDate",
                    "fhir.patient.deceasedBoolean",
                    "fhir.patient.deceasedDateTime",
                    "fhir.patient.address",
                    "fhir.patient.maritalStatus",
                    "fhir.patient.multipleBirthBoolean",
                    "fhir.patient.multipleBirthInteger",
                    "fhir.patient.photo",
                    "fhir.patient.contact",
                    "fhir.patient.contact.relationship",
                    "fhir.patient.contact.name",
                    "fhir.patient.contact.telecom",
                    "fhir.patient.contact.address",
                    "fhir.patient.contact.gender",
                    "fhir.patient.contact.organization",
                    "fhir.patient.contact.period",
                    "fhir.patient.communication",
                    "fhir.patient.communication.language",
                    "fhir.patient.communication.preferred",
                    "fhir.patient.generalPractitioner",
                    "fhir.patient.managingOrganization",
                    "fhir.patient.link",
                    "fhir.patient.link.other",
                    "fhir.patient.link.type",
                ],
                "count": 36,
            },
            "fhir_observation": {
                "description": "FHIR R4 Observation resource fields",
                "reference": "FHIR R4 Specification",
                "fields": [
                    "fhir.observation.id",
                    "fhir.observation.meta",
                    "fhir.observation.implicitRules",
                    "fhir.observation.language",
                    "fhir.observation.text",
                    "fhir.observation.contained",
                    "fhir.observation.extension",
                    "fhir.observation.modifierExtension",
                    "fhir.observation.identifier",
                    "fhir.observation.basedOn",
                    "fhir.observation.partOf",
                    "fhir.observation.status",
                    "fhir.observation.category",
                    "fhir.observation.code",
                    "fhir.observation.subject",
                    "fhir.observation.focus",
                    "fhir.observation.encounter",
                    "fhir.observation.effectiveDateTime",
                    "fhir.observation.effectivePeriod",
                    "fhir.observation.issued",
                    "fhir.observation.performer",
                    "fhir.observation.valueQuantity",
                    "fhir.observation.valueCodeableConcept",
                    "fhir.observation.valueString",
                    "fhir.observation.valueBoolean",
                    "fhir.observation.valueInteger",
                    "fhir.observation.valueRange",
                    "fhir.observation.valueRatio",
                    "fhir.observation.valueSampledData",
                    "fhir.observation.valueTime",
                    "fhir.observation.valueDateTime",
                    "fhir.observation.valuePeriod",
                    "fhir.observation.dataAbsentReason",
                    "fhir.observation.interpretation",
                    "fhir.observation.note",
                    "fhir.observation.bodySite",
                    "fhir.observation.method",
                    "fhir.observation.specimen",
                    "fhir.observation.device",
                    "fhir.observation.referenceRange",
                    "fhir.observation.referenceRange.low",
                    "fhir.observation.referenceRange.high",
                    "fhir.observation.referenceRange.type",
                    "fhir.observation.referenceRange.appliesTo",
                    "fhir.observation.referenceRange.age",
                    "fhir.observation.referenceRange.text",
                    "fhir.observation.component",
                    "fhir.observation.component.code",
                    "fhir.observation.component.valueQuantity",
                    "fhir.observation.component.valueCodeableConcept",
                    "fhir.observation.component.valueString",
                    "fhir.observation.component.valueBoolean",
                    "fhir.observation.component.valueInteger",
                    "fhir.observation.component.valueRange",
                    "fhir.observation.component.valueRatio",
                    "fhir.observation.component.dataAbsentReason",
                    "fhir.observation.component.interpretation",
                    "fhir.observation.component.referenceRange",
                ],
                "count": 56,
            },
            "fhir_condition": {
                "description": "FHIR R4 Condition resource fields",
                "reference": "FHIR R4 Specification",
                "fields": [
                    "fhir.condition.id",
                    "fhir.condition.meta",
                    "fhir.condition.implicitRules",
                    "fhir.condition.language",
                    "fhir.condition.text",
                    "fhir.condition.contained",
                    "fhir.condition.extension",
                    "fhir.condition.modifierExtension",
                    "fhir.condition.identifier",
                    "fhir.condition.clinicalStatus",
                    "fhir.condition.verificationStatus",
                    "fhir.condition.category",
                    "fhir.condition.severity",
                    "fhir.condition.code",
                    "fhir.condition.bodySite",
                    "fhir.condition.subject",
                    "fhir.condition.encounter",
                    "fhir.condition.onsetDateTime",
                    "fhir.condition.onsetAge",
                    "fhir.condition.onsetPeriod",
                    "fhir.condition.onsetRange",
                    "fhir.condition.onsetString",
                    "fhir.condition.abatementDateTime",
                    "fhir.condition.abatementAge",
                    "fhir.condition.abatementPeriod",
                    "fhir.condition.abatementRange",
                    "fhir.condition.abatementString",
                    "fhir.condition.recordedDate",
                    "fhir.condition.recorder",
                    "fhir.condition.asserter",
                    "fhir.condition.stage",
                    "fhir.condition.stage.summary",
                    "fhir.condition.stage.assessment",
                    "fhir.condition.stage.type",
                    "fhir.condition.evidence",
                    "fhir.condition.evidence.code",
                    "fhir.condition.evidence.detail",
                    "fhir.condition.note",
                ],
                "count": 40,
            },
            "fhir_procedure": {
                "description": "FHIR R4 Procedure resource fields",
                "reference": "FHIR R4 Specification",
                "fields": [
                    "fhir.procedure.id",
                    "fhir.procedure.meta",
                    "fhir.procedure.implicitRules",
                    "fhir.procedure.language",
                    "fhir.procedure.text",
                    "fhir.procedure.contained",
                    "fhir.procedure.extension",
                    "fhir.procedure.modifierExtension",
                    "fhir.procedure.identifier",
                    "fhir.procedure.instantiatesCanonical",
                    "fhir.procedure.instantiatesUri",
                    "fhir.procedure.basedOn",
                    "fhir.procedure.partOf",
                    "fhir.procedure.status",
                    "fhir.procedure.statusReason",
                    "fhir.procedure.category",
                    "fhir.procedure.code",
                    "fhir.procedure.subject",
                    "fhir.procedure.encounter",
                    "fhir.procedure.performedDateTime",
                    "fhir.procedure.performedPeriod",
                    "fhir.procedure.performedString",
                    "fhir.procedure.performedRange",
                    "fhir.procedure.recorder",
                    "fhir.procedure.asserter",
                    "fhir.procedure.performer",
                    "fhir.procedure.performer.function",
                    "fhir.procedure.performer.actor",
                    "fhir.procedure.performer.onBehalfOf",
                    "fhir.procedure.location",
                    "fhir.procedure.reasonCode",
                    "fhir.procedure.reasonReference",
                    "fhir.procedure.bodySite",
                    "fhir.procedure.outcome",
                    "fhir.procedure.report",
                    "fhir.procedure.complication",
                    "fhir.procedure.complicationDetail",
                    "fhir.procedure.followUp",
                    "fhir.procedure.usedCode",
                    "fhir.procedure.usedReference",
                    "fhir.procedure.note",
                ],
                "count": 42,
            },
            "fhir_medication": {
                "description": "FHIR R4 Medication and MedicationRequest resource fields",
                "reference": "FHIR R4 Specification",
                "fields": [
                    "fhir.medication.id",
                    "fhir.medication.meta",
                    "fhir.medication.extension",
                    "fhir.medication.modifierExtension",
                    "fhir.medication.identifier",
                    "fhir.medication.code",
                    "fhir.medication.status",
                    "fhir.medication.manufacturer",
                    "fhir.medication.form",
                    "fhir.medication.amount",
                    "fhir.medication.amount.numerator",
                    "fhir.medication.amount.denominator",
                    "fhir.medication.synonym",
                    "fhir.medication.batch",
                    "fhir.medication.batch.lotNumber",
                    "fhir.medication.batch.expirationDate",
                    "fhir.medication.ingredient",
                    "fhir.medication.ingredient.itemCodeableConcept",
                    "fhir.medication.ingredient.itemReference",
                    "fhir.medication.ingredient.isActive",
                    "fhir.medication.ingredient.strength",
                    "fhir.medication.ingredient.strength.numerator",
                    "fhir.medication.ingredient.strength.denominator",
                    "fhir.medication.ingredient.strength.code",
                    "fhir.medicationRequest.id",
                    "fhir.medicationRequest.meta",
                    "fhir.medicationRequest.identifier",
                    "fhir.medicationRequest.status",
                    "fhir.medicationRequest.statusReason",
                    "fhir.medicationRequest.intent",
                    "fhir.medicationRequest.category",
                    "fhir.medicationRequest.priority",
                    "fhir.medicationRequest.doNotPerform",
                    "fhir.medicationRequest.reportedBoolean",
                    "fhir.medicationRequest.reportedReference",
                    "fhir.medicationRequest.medicationCodeableConcept",
                    "fhir.medicationRequest.medicationReference",
                    "fhir.medicationRequest.subject",
                    "fhir.medicationRequest.encounter",
                    "fhir.medicationRequest.authoredOn",
                    "fhir.medicationRequest.requester",
                    "fhir.medicationRequest.performer",
                    "fhir.medicationRequest.performerType",
                    "fhir.medicationRequest.recorder",
                    "fhir.medicationRequest.reasonCode",
                    "fhir.medicationRequest.reasonReference",
                    "fhir.medicationRequest.dosage",
                    "fhir.medicationRequest.dosage.sequence",
                    "fhir.medicationRequest.dosage.text",
                    "fhir.medicationRequest.dosage.timing",
                    "fhir.medicationRequest.dosage.route",
                    "fhir.medicationRequest.dosage.method",
                    "fhir.medicationRequest.dosage.doseAndRate",
                ],
                "count": 58,
            },
            "fhir_diagnostic_report": {
                "description": "FHIR R4 DiagnosticReport resource fields",
                "reference": "FHIR R4 Specification",
                "fields": [
                    "fhir.diagnosticReport.id",
                    "fhir.diagnosticReport.meta",
                    "fhir.diagnosticReport.implicitRules",
                    "fhir.diagnosticReport.language",
                    "fhir.diagnosticReport.text",
                    "fhir.diagnosticReport.contained",
                    "fhir.diagnosticReport.extension",
                    "fhir.diagnosticReport.modifierExtension",
                    "fhir.diagnosticReport.identifier",
                    "fhir.diagnosticReport.basedOn",
                    "fhir.diagnosticReport.status",
                    "fhir.diagnosticReport.category",
                    "fhir.diagnosticReport.code",
                    "fhir.diagnosticReport.subject",
                    "fhir.diagnosticReport.encounter",
                    "fhir.diagnosticReport.effectiveDateTime",
                    "fhir.diagnosticReport.effectivePeriod",
                    "fhir.diagnosticReport.issued",
                    "fhir.diagnosticReport.performer",
                    "fhir.diagnosticReport.resultsInterpreter",
                    "fhir.diagnosticReport.specimen",
                    "fhir.diagnosticReport.result",
                    "fhir.diagnosticReport.imagingStudy",
                    "fhir.diagnosticReport.media",
                    "fhir.diagnosticReport.media.comment",
                    "fhir.diagnosticReport.media.link",
                    "fhir.diagnosticReport.conclusion",
                    "fhir.diagnosticReport.conclusionCode",
                    "fhir.diagnosticReport.presentedForm",
                ],
                "count": 28,
            },
            "dicom_patient_study": {
                "description": "DICOM Patient and Study related tags",
                "reference": "DICOM PS3.6 (Data Dictionary)",
                "fields": [
                    "dicom.patient_name",
                    "dicom.patient_id",
                    "dicom.patient_birth_date",
                    "dicom.patient_sex",
                    "dicom.patient_age",
                    "dicom.patient_weight",
                    "dicom.patient_height",
                    "dicom.patient_address",
                    "dicom.patient_telephone_numbers",
                    "dicom.patient_mother_maiden_name",
                    "dicom.medical_record_locator",
                    "dicom.ethnic_group",
                    "dicom.occupation",
                    "dicom.smoking_status",
                    "dicom.additional_patient_history",
                    "dicom.patient_comments",
                    "dicom.study_instance_uid",
                    "dicom.study_date",
                    "dicom.study_time",
                    "dicom.referring_physician_name",
                    "dicom.referring_physician_telephone_numbers",
                    "dicom.study_id",
                    "dicom.accession_number",
                    "dicom.study_description",
                    "dicom.procedure_code_sequence",
                    "dicom.series_number",
                    "dicom.instance_number",
                    "dicom.isrc_number",
                    "dicom.study_priority_id",
                    "dicom.current_patient_location",
                    "dicom.order_phone_number",
                    "dicom.order_placer_facility_name",
                    "dicom.order_placer_facility_address",
                    "dicom.order_placer_contact_person",
                    "dicom.order_placer_contact_manufacturer",
                    "dicom.placer_order_number",
                    "dicom.filler_order_number",
                    "dicom.placer_order_number_of_supplier",
                    "dicom.supplier_order_number",
                ],
                "count": 39,
            },
            "dicom_image": {
                "description": "DICOM Image related tags",
                "reference": "DICOM PS3.6 (Data Dictionary)",
                "fields": [
                    "dicom.modality",
                    "dicom.series_instance_uid",
                    "dicom.series_description",
                    "dicom.series_type",
                    "dicom.series_number",
                    "dicom.technical_executives",
                    "dicom.series_date",
                    "dicom.series_time",
                    "dicom.series_modality",
                    "dicom.anatomic_regions_in_image",
                    "dicom.protocol_name",
                    "dicom.references",
                    "dicom.position_reference_indicator",
                    "dicom.slice_location",
                    "dicom.slice_thickness",
                    "dicom.slice_sensitivity_factors",
                    "dicom.slice_orientation",
                    "dicom.spacing_between_slices",
                    "dicom.number_of_slices",
                    "dicom.number_of_time_slots",
                    "dicom.number_of_tomographic_levels",
                    "dicom.total_number_of_slices",
                    "dicom.number_of_frames",
                    "dicom.frame_increment_pointer",
                    "dicom.frame_dimension_pointer",
                    "dicom.rows",
                    "dicom.columns",
                    "dicom.pixel_spacing",
                    "dicom.pixel_aspect_ratio",
                    "dicom.bits_allocated",
                    "dicom.bits_stored",
                    "dicom.high_bit",
                    "dicom.pixel_representation",
                    "dicom.smallest_image_pixel_value",
                    "dicom.largest_image_pixel_value",
                    "dicom.pixel_padding_value",
                    "dicom.pixel_value_relationship",
                    "dicom.window_center",
                    "dicom.window_width",
                    "dicom.rescale_intercept",
                    "dicom.rescale_slope",
                    "dicom.voilut_function",
                    "dicom.window_center_width_explanation",
                    "dicom.image_orientation_patient",
                    "dicom.image_position_patient",
                    "dicom.privacy_filter_flg",
                    "dicom.privacy_filter_type",
                    "dicom.encryption_type",
                    "dicom.encrypted_content_type",
                ],
                "count": 49,
            },
            "dicom_equipment": {
                "description": "DICOM Equipment related tags",
                "reference": "DICOM PS3.6 (Data Dictionary)",
                "fields": [
                    "dicom.manufacturer",
                    "dicom.institution_name",
                    "dicom.institution_address",
                    "dicom.station_name",
                    "dicom.institutional_department_name",
                    "dicom.manufacturer_model_name",
                    "dicom.device_serial_number",
                    "dicom.software_versions",
                    "dicom.spatial_resolution",
                    "dicom.date_of_last_calibration",
                    "dicom.time_of_last_calibration",
                    "dicom.pixel_padding_value",
                    "dicom.foreign_image_reconstruction",
                    "dicom.encoding_process",
                    "dicom.axial_detector_configuration",
                    "dicom.number_of_detector_rows",
                    "dicom.number_of_detector_columns",
                    "dicom.detector_active_shape",
                    "dicom.detector_active_dimensions",
                    "dicom.detector_element_spacing",
                    "dicom.focal_spot",
                    "dicom.highest_axial_spatial_resolution",
                    "dicom.focus_to_detector_distance",
                    "dicom.focus_to_isocenter_distance",
                    "dicom.table_relationship",
                    "dicom.table_position",
                    "dicom.table_motion",
                    "dicom.table_type",
                    "dicom.collimator_type",
                    "dicom.xray_output",
                    "dicom.half_value_layer",
                    "dicom.filter_material",
                    "dicom.filter_type",
                    "dicom.filter_thickness_min",
                    "dicom.filter_thickness_max",
                    "dicom.kvp",
                    "dicom.generator_power",
                    "dicom.xray_tube_current",
                    "dicom.exposure",
                    "dicom.exposure_in_mas",
                    "dicom.xray_tube_current_in_ua",
                    "dicom.distance_source_to_detector",
                    "dicom.distance_source_to_patient",
                    "dicom.exposure_index",
                    "dicom.target_exposure_index",
                    "dicom.deviation_index",
                ],
                "count": 45,
            },
            "cda_header": {
                "description": "CDA (Clinical Document Architecture) header fields",
                "reference": "HL7 CDA R2 Specification",
                "fields": [
                    "cda.type_id",
                    "cda.set_id",
                    "cda.version_number",
                    "cda.document_type_code",
                    "cda.title",
                    "cda.effective_time",
                    "cda.confidentiality_code",
                    "cda.language_code",
                    "cda.set_id_version_number",
                    "cda.document_id",
                    "cda.derived_from",
                    "cda.service_event",
                    "cda.service_event.code",
                    "cda.service_event.effective_time",
                    "cda.service_event.performer",
                    "cda.service_event.performer.type_code",
                    "cda.service_event.performer.assigned_entity",
                    "cda.service_event.performer.assigned_entity.id",
                    "cda.service_event.performer.assigned_entity.code",
                    "cda.service_event.performer.assigned_entity.addr",
                    "cda.service_event.performer.assigned_entity.telecom",
                    "cda.author",
                    "cda.author.type_code",
                    "cda.author.time",
                    "cda.author.assigned_author",
                    "cda.author.assigned_author.id",
                    "cda.author.assigned_author.code",
                    "cda.author.assigned_author.addr",
                    "cda.author.assigned_author.telecom",
                    "cda.custodian",
                    "cda.custodian.type_code",
                    "cda.custodian.assigned_custodian",
                    "cda.custodian.assigned_custodian.represented_custodian_organization",
                    "cda.custodian.assigned_custodian.represented_custodian_organization.name",
                    "cda.custodian.assigned_custodian.represented_custodian_organization.telecom",
                    "cda.custodian.assigned_custodian.represented_custodian_organization.addr",
                    "cda.authenticator",
                    "cda.authenticator.type_code",
                    "cda.authenticator.time",
                    "cda.authenticator.signature_code",
                    "cda.authenticator.assigned_entity",
                    "cda.legal_authenticator",
                    "cda.legal_authenticator.type_code",
                    "cda.legal_authenticator.time",
                    "cda.legal_authenticator.signature_code",
                    "cda.legal_authenticator.assigned_entity",
                ],
                "count": 46,
            },
            "cda_section_entry": {
                "description": "CDA Section and Entry metadata fields",
                "reference": "HL7 CDA R2 Specification",
                "fields": [
                    "cda.section.template_id",
                    "cda.section.id",
                    "cda.section.code",
                    "cda.section.title",
                    "cda.section.text",
                    "cda.section.confidentiality_code",
                    "cda.section.language_code",
                    "cda.section.subject",
                    "cda.section.author",
                    "cda.section.data_enterer",
                    "cda.section.informant",
                    "cda.section.participant",
                    "cda.section.entry",
                    "cda.entry.type_code",
                    "cda.entry.context_conduction_ind",
                    "cda.entry.act",
                    "cda.entry.act.template_id",
                    "cda.entry.act.id",
                    "cda.entry.act.code",
                    "cda.entry.act.text",
                    "cda.entry.act.status_code",
                    "cda.entry.act.effective_time",
                    "cda.entry.act.confidentiality_code",
                    "cda.entry.observation",
                    "cda.entry.observation.template_id",
                    "cda.entry.observation.id",
                    "cda.entry.observation.code",
                    "cda.entry.observation.text",
                    "cda.entry.observation.value",
                    "cda.entry.observation.status_code",
                    "cda.entry.observation.effective_time",
                    "cda.entry.observation.interpretation_code",
                    "cda.entry.observation.method_code",
                    "cda.entry.observation.target_site_code",
                    "cda.entry.observation.reference_range",
                    "cda.entry.observation.reference_range.observation_range",
                    "cda.entry.observation.reference_range.observation_range.text",
                    "cda.entry.observation.reference_range.observation_range.value",
                    "cda.entry.procedure",
                    "cda.entry.procedure.template_id",
                    "cda.entry.procedure.id",
                    "cda.entry.procedure.code",
                    "cda.entry.procedure.text",
                    "cda.entry.procedure.status_code",
                    "cda.entry.procedure.effective_time",
                    "cda.entry.encounter",
                    "cda.entry.encounter.template_id",
                    "cda.entry.encounter.id",
                    "cda.entry.encounter.code",
                    "cda.entry.encounter.text",
                    "cda.entry.encounter.status_code",
                    "cda.entry.encounter.effective_time",
                    "cda.entry.encounter.participant",
                ],
                "count": 52,
            },
            "icd10_diagnosis": {
                "description": "ICD-10 Diagnosis coding fields",
                "reference": "ICD-10 WHO Classification",
                "fields": [
                    "icd10.code",
                    "icd10.short_description",
                    "icd10.full_description",
                    "icd10.category",
                    "icd10.block",
                    "icd10.chapter",
                    "icd10.diagnosis_type",
                    "icd10.primary_diagnosis",
                    "icd10.secondary_diagnosis",
                    "icd10.external_cause_code",
                    "icd10.intent",
                    "icd10.mechanism",
                    "icd10.place_of_occurrence",
                    "icd10.activity_code",
                    "icd10.relationship_type",
                    "icd10.laterality",
                    "icd10.severity",
                    "icd10.episode_of_care",
                    "icd10.clinical_modification",
                    "icd10.diagnostic_certainty",
                    "icd10.date_of_onset",
                    "icd10.date_of_diagnosis",
                    "icd10.resolved_date",
                    "icd10.additional_code",
                    "icd10.specific_location",
                    "icd10.anatomical_site",
                    "icd10.complication",
                    "icd10.manifestation",
                    "icd10.cause_origin",
                    "icd10.blood_alcohol_content",
                    "icd10.injury_severity_score",
                    "icd10.transferred_from",
                    "icd10.transferred_to",
                    "icd10.study_id",
                    "icd10.revision_number",
                    "icd10.country_extension",
                    "icd10.state_extension",
                    "icd10.age_range",
                    "icd10.gender_restriction",
                    "icd10.mdc_code",
                    "icd10.drg_code",
                    "icd10.drg_type",
                    "icd10.ms_drg",
                    "icd10.ap_drg",
                    "icd10.ssi_drg",
                ],
                "count": 44,
            },
            "snomed_ct": {
                "description": "SNOMED CT coding fields",
                "reference": "SNOMED CT International Edition",
                "fields": [
                    "snomedct.concept_id",
                    "snomedct.term",
                    "snomedct.fully_specified_name",
                    "snomedct.preferred_term",
                    "snomedct.synonym",
                    "snomedct.definition_status",
                    "snomedct.module_id",
                    "snomedct.effective_time",
                    "snomedct.is_active",
                    "snomedct.referenced_component",
                    "snomedct.hierarchy",
                    "snomedct.parent_concept",
                    "snomedct.child_concept",
                    "snomedct.ancestors",
                    "snomedct.descendants",
                    "snomedct.isa_relationship",
                    "snomedct.is_a",
                    "snomedct.part_of",
                    "snomedct.has_part",
                    "snomedct.finding_site",
                    "snomedct.associated_morphology",
                    "snomedct.causative_agent",
                    "snomedct.procedure_site",
                    "snomedct.procedure_device",
                    "snomedct.pathological_process",
                    "snomedct.occurrence",
                    "snomedct.severity",
                    "snomedct.episodicity",
                    "snomedct.intent",
                    "snomedct.method",
                    "snomedct.approach",
                    "snomedct.access",
                    "snomedct.object",
                    "snomedct.substance",
                    "snomedct.specimen",
                    "snomedct.disposable",
                    "snomedct.clinical_drug",
                    "snomedct.dose_form",
                    "snomedct.route_of_administration",
                    "snomedct.modifier",
                    "snomedct.attribute",
                    "snomedct.qualifier",
                    "snomedct.stated_relationship",
                    "snomedct.inferred_relationship",
                    "snomedct.equivalence",
                    "snomedct.annotation",
                    "snomedct.map_target",
                    "snomedct.map_category",
                    "snomedct.mapping_guid",
                ],
                "count": 48,
            },
            "loinc": {
                "description": "LOINC laboratory observation codes",
                "reference": "LOINC Database",
                "fields": [
                    "loinc.code",
                    "loinc.component",
                    "loinc.property",
                    "loinc.time_aspect",
                    "loinc.system",
                    "loinc.scale_type",
                    "loinc.method_type",
                    "loinc.class",
                    "loinc.short_name",
                    "loinc.long_common_name",
                    "loinc.display_name",
                    "loinc.status",
                    "loinc.approved",
                    "loinc.version_approved",
                    "loinc.version_changed",
                    "loinc.last_changed",
                    "loinc.normal_range",
                    "loinc.normal_range_low",
                    "loinc.normal_range_high",
                    "loinc.precision",
                    "loinc.units",
                    "loinc.unit",
                    "loinc.order_obs",
                    "loinc.classtype",
                    "loinc.source",
                    "loinc.reg_status",
                    "loinc.mapped_to",
                    "loinc.panel_type",
                    "loinc.membership",
                    "loinc.common_components",
                    "loinc.formula",
                    "loinc.excluded_from_panels",
                    "loinc.related_names",
                    "loinc.short_name_derived",
                    "loinc.hl7_v2_mapping",
                    "loinc.hl7_v3_mapping",
                    "loinc.cpt_mapping",
                    "loinc.snomed_ct_mapping",
                    "loinc.lonic_component_id",
                    "loinc.time_lag",
                    "loinc.time_of_day",
                    "loinc.rank",
                    "loinc.standard_units",
                    "loinc.precision_status",
                    "loinc.answerlist_id",
                    "loinc.survey_question_text",
                    "loinc.survey_question_term",
                    "loinc.survey_question_ucum",
                    "loinc.consumers_name",
                ],
                "count": 50,
            },
            "ihe_xds": {
                "description": "IHE XDS (Cross-Enterprise Document Sharing) metadata",
                "reference": "IHE IT Infrastructure Technical Framework",
                "fields": [
                    "ihe.xds.SubmissionSet.uniqueId",
                    "ihe.xds.SubmissionSet.author",
                    "ihe.xds.SubmissionSet.authorPerson",
                    "ihe.xds.SubmissionSet.authorInstitution",
                    "ihe.xds.SubmissionSet.authorRole",
                    "ihe.xds.SubmissionSet.authorSpecialty",
                    "ihe.xds.SubmissionSet.createdTime",
                    "ihe.xds.SubmissionSet.sourcePatientId",
                    "ihe.xds.SubmissionSet.sourcePatientInfo",
                    "ihe.xds.SubmissionSet.intendedRecipient",
                    "ihe.xds.SubmissionSet.contentTypeCode",
                    "ihe.xds.SubmissionSet.comments",
                    "ihe.xds.DocumentEntry.uniqueId",
                    "ihe.xds.DocumentEntry.uri",
                    "ihe.xds.DocumentEntry.mimeType",
                    "ihe.xds.DocumentEntry.languageCode",
                    "ihe.xds.DocumentEntry.serviceStartTime",
                    "ihe.xds.DocumentEntry.serviceStopTime",
                    "ihe.xds.DocumentEntry.generationTime",
                    "ihe.xds.DocumentEntry.hashedUri",
                    "ihe.xds.DocumentEntry.size",
                    "ihe.xds.DocumentEntry.legalAuthenticator",
                    "ihe.xds.DocumentEntry.patientId",
                    "ihe.xds.DocumentEntry.title",
                    "ihe.xds.DocumentEntry.comments",
                    "ihe.xds.DocumentEntry.status",
                    "ihe.xds.DocumentEntry.documentAvailability",
                    "ihe.xds.Folder.uniqueId",
                    "ihe.xds.Folder.lastUpdateTime",
                    "ihe.xds.Folder.patientId",
                    "ihe.xds.Folder.title",
                    "ihe.xds.Folder.comments",
                    "ihe.xds.Folder.status",
                    "ihe.xds.Folder.codeList",
                    "ihe.xds.registry.package",
                    "ihe.xds.registry.isOpaque",
                    "ihe.xds.document_inquiry",
                    "ihe.xds.adhoc_query",
                    "ihe.xds.sql_query",
                    "ihe.xds.cross_gateway_query",
                    "ihe.xds.stored_query",
                    "ihe.xds.retrieve_imaging_document_set",
                    "ihe.xds.retrieve_document_set",
                    "ihe.xds.provided_reports",
                    "ihe.xds.imaging_study_report",
                    "ihe.xds.referenced_manifest",
                ],
                "count": 48,
            },
        },
        "totals": {
            "categories": 21,
            "total_fields": 802,
        }
    }

    return INVENTORY


def main():
    print("=" * 70)
    print("MEDICAL/HEALTHCARE METADATA FIELD INVENTORY")
    print("=" * 70)
    print()

    inventory = generate_medical_inventory()

    print(f"Generated: {inventory['generated_at']}")
    print(f"Categories: {inventory['totals']['categories']}")
    print(f"Total Fields: {inventory['totals']['total_fields']}")
    print()

    print("FIELD COUNTS BY CATEGORY:")
    print("-" * 50)
    for cat_name, cat_data in sorted(inventory['categories'].items(), key=lambda x: x[1]['count'], reverse=True):
        print(f"  {cat_name:30s}: {cat_data['count']:>4} fields")

    output_dir = Path("dist/medical_inventory")
    output_dir.mkdir(parents=True, exist_ok=True)

    output_file = output_dir / "medical_inventory.json"
    output_file.write_text(json.dumps(inventory, indent=2, sort_keys=True), encoding="utf-8")
    print()
    print(f"Wrote: {output_file}")

    summary = {
        "generated_at": inventory["generated_at"],
        "source": inventory["source"],
        "description": inventory["description"],
        "categories": {
            k: {
                "count": v["count"],
                "description": v["description"],
                "reference": v.get("reference", "N/A")
            }
            for k, v in inventory["categories"].items()
        },
        "totals": inventory["totals"],
    }

    summary_file = output_dir / "medical_summary.json"
    summary_file.write_text(json.dumps(summary, indent=2, sort_keys=True), encoding="utf-8")
    print(f"Wrote: {summary_file}")


if __name__ == "__main__":
    main()
