#!/usr/bin/env python3
"""Defense and Military Metadata Field Inventory.

Covers military standards, tactical data links, mission planning,
NATO standards, C4ISR systems, and military geospatial data.
"""

from datetime import datetime, timezone
import json
from pathlib import Path


def generate_defense_inventory():
    """Generate comprehensive defense and military metadata field inventory."""

    INVENTORY = {
        "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "source": "MIL-STD-1553, MIL-STD-1760, STANAG 5511, ADatP-3, NATO STANAGs, C4ISR standards",
        "description": "Defense and military metadata fields for defense systems, tactical data links, and military operations",
        "categories": {
            "military_standards": {
                "description": "MIL-STD-1553, MIL-STD-1760, STANAG military standards",
                "reference": "MIL-STD-1553B, MIL-STD-1760C, STANAG 4586, MIL-STD-1472",
                "fields": [
                    "milstd1553.bus_controller",
                    "milstd1553.remote_terminal",
                    "milstd1553.bus_monitor",
                    "milstd1553.bus_address",
                    "milstd1553.subaddress",
                    "milstd1553.word_count",
                    "milstd1553.command_word",
                    "milstd1553.data_word",
                    "milstd1553.status_word",
                    "milstd1553.sync_pattern",
                    "milstd1553.bit_rate",
                    "milstd1553.word_length",
                    "milstd1553.message_error",
                    "milstd1553.service_request",
                    "milstd1553.busy",
                    "milstd1553.subsystem_flag",
                    "milstd1553.dynamic_bus_control",
                    "milstd1553.terminal_flag",
                    "milstd1553.data_busy",
                    "milstd1553.instrumentation_flag",
                    "milstd1553.terminal_address",
                    "milstd1553.receive_command",
                    "milstd1553.transmit_command",
                    "milstd1553.mode_code",
                    "milstd1553.mode_code.transmit_status",
                    "milstd1553.mode_code.transmit_vector",
                    "milstd1553.mode_code.sync_time",
                    "milstd1553.mode_code.transmit_last_command",
                    "milstd1553.mode_code.transmit_bit_word",
                    "milstd1553.mode_code.transmit_switch_position",
                    "milstd1553.mode_code.selected_transmit",
                    "milstd1553.mode_code.synchronize",
                    "milstd1553.mode_code.transmit_word_count",
                    "milstd1553.mode_code.transmit_address",
                    "milstd1553.mode_code.reset_remote_terminal",
                    "milstd1553.mode_code.transmit_tbit_request",
                    "milstd1553.mode_code.transmit_opcode_request",
                    "milstd1553.mode_code.overwrite_data",
                    "milstd1553.bus_controller_id",
                    "milstd1553.terminal_id",
                    "milstd1553.message_length",
                    "milstd1553.message_time",
                    "milstd1553.response_time",
                    "milstd1553.retry_count",
                    "milstd1553.retry_limit",
                    "milstd1553.bit_error_rate",
                    "milstd1553.bus_utilization",
                    "milstd1553.async_errors",
                    "milstd1553.sync_errors",
                    "milstd1553.framing_errors",
                    "milstd1553.parity_errors",
                    "milstd1553.data_inhibit",
                    "milstd1553.illegal_command",
                    "milstd1553.illegal_subaddress",
                    "milstd1553.illegal_word_count",
                    "milstd1553.terminal_timeout",
                    "milstd1553.bus_timeout",
                    "milstd1553.protocol_error",
                    "milstd1553.buffer_overflow",
                    "milstd1553.buffer_underflow",
                    "milstd1553.clock_sync",
                    "milstd1553.time_slot",
                    "milstd1553.frame_sync",
                    "milstd1553.subframe",
                    "milstd1553.major_frame",
                    "milstd1553.minor_frame",
                    "milstd1553.bus_controller_switch",
                    "milstd1553.backup_controller",
                    "milstd1553.redundancy_mode",
                    "milstd1553.bus_a_active",
                    "milstd1553.bus_b_active",
                    "milstd1553.bus_select",
                    "milstd1553.loopback_test",
                    "milstd1553.built_in_test",
                    "milstd1553.bite_result",
                    "milstd1553.maintenance_mode",
                    "milstd1553.calibration_mode",
                    "milstd1553.data_validity",
                    "milstd1553.timestamp",
                    "milstd1553.sequence_number",
                    "milstd1553.priority",
                    "milstd1553.security_classification",
                    "milstd1553.compartment",
                    "milstd1553.ciphertext",
                    "milstd1553.key_reference",
                    "milstd1553.crypto_key",
                    "milstd1553.transmission_security",
                    "milstd1553.emission_control",
                    "milstd1553.jamming_resistance",
                    "milstd1553.low_probability_intercept",
                    "milstd1553.low_probability_detection",
                    "milstd1760.weapon_id",
                    "milstd1760.weapon_type",
                    "milstd1760.station_number",
                    "milstd1760.ordnance_code",
                    "milstd1760.ladder_logical_unit",
                    "milstd1760.load_sequence",
                    "milstd1760.weapon_status",
                    "milstd1760.fuze_setting",
                    "milstd1760.arming_setting",
                    "milstd1760.store_sequence",
                    "milstd1760.store_identity",
                    "milstd1760.store_type",
                    "milstd1760.store_weight",
                    "milstd1760.store_center_of_gravity",
                    "milstd1760.store_length",
                    "milstd1760.store_diameter",
                    "milstd1760.store_drag_factor",
                    "milstd1760.store_velocity_scale",
                    "milstd1760.rail_shaker",
                    "milstd1760.eject_force",
                    "milstd1760.eject_velocity",
                    "milstd1760.eject_timing",
                    "milstd1760.separation_status",
                    "milstd1760.interface_standard",
                    "milstd1760.analog_discrete",
                    "milstd1760.serial_digital",
                    "milstd1760.milstd1553_compliant",
                    "milstd1760.flight_control_computer",
                ],
                "count": 100,
            },
            "tactical_data_links": {
                "description": "Link 11, Link 16, Link 22, NATO STANAG 5511, ADatP-3",
                "reference": "STANAG 5511, STANAG 5616, STANAG 5624, ADatP-3, MIL-STD-6011",
                "fields": [
                    "link11.network_id",
                    "link11.net_number",
                    "link11.track_number",
                    "link11.unit_id",
                    "link11.battle_group",
                    "link11.element",
                    "link11.track_quality",
                    "link11.track_status",
                    "link11.position",
                    "link11.position_latitude",
                    "link11.position_longitude",
                    "link11.position_altitude",
                    "link11.position_accuracy",
                    "link11.velocity",
                    "link11.velocity_course",
                    "link11.velocity_speed",
                    "link11.velocity_vertical",
                    "link11.identification",
                    "link11.identification_friendly",
                    "link11.identification_hostile",
                    "link11.identification_unknown",
                    "link11.platform",
                    "link11.platform__typeechelon",
                    "link11.mission_type",
                    "link11.weapon_type",
                    "link11.weapon_status",
                    "link11.fuel_status",
                    "link11.emcon_status",
                    "link11.tactical_action",
                    "link11.information_type",
                    "link11.reference_point",
                    "link11.relative_position",
                    "link11.course_made_good",
                    "link11.destination",
                    "link11.speed_made_good",
                    "link11.tgt_designator",
                    "link11.elapsed_time",
                    "link11.subpoint_position",
                    "link11.point_position",
                    "link11.projection_point",
                    "link11.engagement_zone",
                    "link11.deployment",
                    "link11.hibernate",
                    "link11.acknowledge",
                    "link11.well_known_reference",
                    "link11.special_points",
                    "link11.hq_station",
                    "link11.marine_radio",
                    "link11.air_strike",
                    "link11.attack_direction",
                    "link11.tac_aos",
                    "link11.tac_gci",
                    "link11.tac_link",
                    "link11.tac_mission",
                    "link11.tac_recon",
                    "link16.network_id",
                    "link16.net_number",
                    "link16.track_number",
                    "link16.track_quality",
                    "link16.identity",
                    "link16.identity_friend_or_foe",
                    "link16.position",
                    "link16.position_geodetic",
                    "link16.position_latitude",
                    "link16.position_longitude",
                    "link16.position_altitude",
                    "link16.position_hae",
                    "link16.position_msl",
                    "link16.velocity",
                    "link16.velocity_vector",
                    "link16.velocity_course",
                    "link16.velocity_speed",
                    "link16.acceleration",
                    "link16.altitude",
                    "link16.altimeter_setting",
                    "link16.mach_number",
                    "link16.turn_rate",
                    "link16.climb_dive",
                    "link16.heading",
                    "link16.aoa",
                    "link16.aos",
                    "link16.affiliation",
                    "link16.domain",
                    "link16.platform_type",
                    "link16.equipment",
                    "link16.mission",
                    "link11_16.tadil_a",
                    "link11_16.tadil_b",
                    "link11_16.tadil_c",
                    "link11_16.tadil_d",
                    "link11_16.tadil_e",
                    "link11_16.jtids",
                    "link11_16.link_22",
                    "link22.network_id",
                    "link22.federated",
                    "link22.directory",
                    "link22.message_header",
                    "link22.message_type",
                    "link22.pdu_type",
                    "link22.pdu_family",
                    "link22.protocol_version",
                    "link22.exercise_id",
                    "link22.time_interval",
                    "link22.length",
                    "link22.pdu_status",
                    "link22.padding",
                    "link22.secondary_missing_data",
                    "link22.variable_parameter",
                    "link22.entity_id",
                    "link22.force_id",
                    "link22.articulation",
                    "link22.total_number_of_sdes",
                    "link22.event_type",
                    "link22.event_id",
                    "link22.reliability",
                    "link22.subevent_type",
                    "link22.zero_state_response",
                    "link22.first_state_request",
                    "link22.first_state",
                    "link22.second_state_request",
                    "link22.second_state",
                    "aditp3.p_prefix",
                    "aditp3.message_type",
                    "aditp3.transfer_layer",
                    "aditp3.application_layer",
                    "aditp3.nato_standard",
                    "aditp3.interoperability",
                    "aditp3.secure_communication",
                    "aditp3.jtac_net",
                    "aditp3.close_air_support",
                    "aditp3.air_coordination",
                    "aditp3.air_mission_planning",
                ],
                "count": 110,
            },
            "mission_planning": {
                "description": "Route planning, threat assessment, weapons loadout, mission parameters",
                "reference": "AFI 11-2, MIL-STD-1472, NATO ATP-3.3.1",
                "fields": [
                    "mission.route_name",
                    "mission.route_id",
                    "mission.mission_type",
                    "mission.mission_id",
                    "mission.tasking_number",
                    "mission.mission_start",
                    "mission.mission_end",
                    "mission.departure_base",
                    "mission.departure_latitude",
                    "mission.departure_longitude",
                    "mission.arrival_base",
                    "mission.arrival_latitude",
                    "mission.arrival_longitude",
                    "mission.alternate_base",
                    "mission.formation",
                    "mission.call_sign",
                    "mission.frequency",
                    "mission.code_word",
                    "mission.clearance_level",
                    "mission.airspace_coordination",
                    "mission.airspace_restriction",
                    "mission.tfr_zone",
                    "mission.mission_essential_position",
                    "mission.target_location",
                    "mission.target_latitude",
                    "mission.target_longitude",
                    "mission.target_altitude",
                    "mission.target_type",
                    "mission.target_number",
                    "mission.target_priority",
                    "mission.target_remarks",
                    "mission.threat_area",
                    "mission.threat_type",
                    "mission.threat_level",
                    "mission.threat_radius",
                    "mission.threat_frequency",
                    "mission.threat_bearing",
                    "mission.threat_elevation",
                    "mission.radar_coverage",
                    "mission.sam_coverage",
                    "mission.aaa_coverage",
                    "mission.friendly_coverage",
                    "mission.armi",
                    "mission.cas_request",
                    "mission.airlift_request",
                    "mission.refueling_request",
                    "mission.weapon_loadout",
                    "mission.weapon_station",
                    "mission.weapon_type",
                    "mission.weapon_quantity",
                    "mission.weapon_fuze",
                    "mission.weapon_arm_time",
                    "mission.weapon_release_altitude",
                    "mission.weapon_release_speed",
                    "mission.weapon_release_point",
                    "mission.fuel_load",
                    "mission.fuel_reserve",
                    "mission.fuel_consumption",
                    "mission.fuel_dump",
                    "mission.external_tanks",
                    "mission.internal_fuel",
                    "mission.ferry_fuel",
                    "mission.tactical_fuel",
                    "mission.virtual_fuel",
                    "mission.af_afac",
                    "mission.mission_combat",
                    "mission.mission_combat_support",
                    "mission.mission_reconnaissance",
                    "mission.mission_sar",
                    "mission.mission_escort",
                    "mission.mission_strike",
                    "mission.mission_sead",
                    "mission.mission_dead",
                    "mission.mission_bai",
                    "mission.mission_interdiction",
                    "mission.route_waypoint",
                    "mission.waypoint_sequence",
                    "mission.waypoint_name",
                    "mission.waypoint_latitude",
                    "mission.waypoint_longitude",
                    "mission.waypoint_altitude",
                    "mission.waypoint_speed",
                    "mission.waypoint_course",
                    "mission.waypoint_radius",
                    "mission.waypoint_turn_rate",
                    "mission.waypoint_leg_length",
                    "mission.waypoint_time_over_target",
                    "mission.waypoint_egress",
                    "mission.waypoint_inbound",
                    "mission.waypoint_outbound",
                    "mission.waypoint_abort",
                    "mission.stealth_route",
                    "mission.low_level_route",
                    "mission.night_route",
                    "mission.weather_minimum",
                    "mission.cee",
                ],
                "count": 100,
            },
            "nato_standards": {
                "description": "STANAGs for data exchange, interoperability, and alliance standards",
                "reference": "NATO STANAG 1000, 2000, 3000, 4000, 5000 series",
                "fields": [
                    "stanag.1000",
                    "stanag.1052",
                    "stanag.1241",
                    "stanag.2002",
                    "stanag.2014",
                    "stanag.2060",
                    "stanag.2083",
                    "stanag.2103",
                    "stanag.2110",
                    "stanag.2127",
                    "stanag.2175",
                    "stanag.2195",
                    "stanag.2266",
                    "stanag.2280",
                    "stanag.2320",
                    "stanag.2493",
                    "stanag.2500",
                    "stanag.2510",
                    "stanag.2550",
                    "stanag.2596",
                    "stanag.2615",
                    "stanag.3000",
                    "stanag.3011",
                    "stanag.3066",
                    "stanag.3114",
                    "stanag.3140",
                    "stanag.3150",
                    "stanag.3200",
                    "stanag.3224",
                    "stanag.3244",
                    "stanag.3246",
                    "stanag.3312",
                    "stanag.3370",
                    "stanag.3400",
                    "stanag.3445",
                    "stanag.3500",
                    "stanag.3516",
                    "stanag.3526",
                    "stanag.3610",
                    "stanag.3615",
                    "stanag.3630",
                    "stanag.3667",
                    "stanag.3726",
                    "stanag.3745",
                    "stanag.3756",
                    "stanag.3805",
                    "stanag.3816",
                    "stanag.3821",
                    "stanag.3838",
                    "stanag.3860",
                    "stanag.3870",
                    "stanag.3890",
                    "stanag.3910",
                    "stanag.3915",
                    "stanag.3933",
                    "stanag.3940",
                    "stanag.3973",
                    "stanag.3994",
                    "stanag.4145",
                    "stanag.4158",
                    "stanag.4162",
                    "stanag.4168",
                    "stanag.4170",
                    "stanag.4175",
                    "stanag.4203",
                    "stanag.4227",
                    "stanag.4234",
                    "stanag.4246",
                    "stanag.4285",
                    "stanag.4296",
                    "stanag.4299",
                    "stanag.4304",
                    "stanag.4406",
                    "stanag.4420",
                    "stanag.4425",
                    "stanag.4514",
                    "stanag.4538",
                    "stanag.4540",
                    "stanag.4545",
                    "stanag.4554",
                    "stanag.4566",
                    "stanag.4575",
                    "stanag.4586",
                    "stanag.4607",
                    "stanag.4609",
                    "stanag.4610",
                    "stanag.4613",
                    "stanag.5001",
                    "stanag.5016",
                    "stanag.5021",
                    "stanag.5034",
                    "stanag.5038",
                    "stanag.5046",
                    "stanag.5070",
                    "stanag.5080",
                    "stanag.5100",
                    "stanag.5170",
                    "stanag.5178",
                    "stanag.5228",
                    "stanag.5511",
                    "stanag.5525",
                    "stanag.5529",
                    "stanag.5534",
                    "stanag.5615",
                    "stanag.5624",
                    "stanag.5630",
                    "stanag.6006",
                    "stanag.7021",
                    "stanag.7023",
                    "stanag.7024",
                    "stanag.7025",
                    "stanag.7034",
                ],
                "count": 90,
            },
            "c4isr_systems": {
                "description": "Command, Control, Communications, Computers, Intelligence, Surveillance, Reconnaissance",
                "reference": "NATO C4ISR Architecture Framework, MIL-STD-499C",
                "fields": [
                    "c4isr.sensor_id",
                    "c4isr.sensor_type",
                    "c4isr.sensor_location",
                    "c4isr.sensor_latitude",
                    "c4isr.sensor_longitude",
                    "c4isr.sensor_altitude",
                    "c4isr.sensor_azimuth",
                    "c4isr.sensor_elevation",
                    "c4isr.sensor_range",
                    "c4isr.sensor_field_of_view",
                    "c4isr.sensor_resolution",
                    "c4isr.sensor_frequency",
                    "c4isr.sensor_bandwidth",
                    "c4isr.sensor_mode",
                    "c4isr.sensor_status",
                    "c4isr.sensor_alive",
                    "c4isr.sensor_health",
                    "c4isr.command_node_id",
                    "c4isr.command_node_type",
                    "c4isr.command_node_location",
                    "c4isr.command_node_level",
                    "c4isr.command_node_status",
                    "c4isr.command_center",
                    "c4isr.operations_center",
                    "c4isr.tactical_center",
                    "c4isr.command_post",
                    "c4isr.comm_node_id",
                    "c4isr.comm_type",
                    "c4isr.comm_frequency",
                    "c4isr.comm_channel",
                    "c4isr.comm_band",
                    "c4isr.comm_mode",
                    "c4isr.comm_status",
                    "c4isr.comm_security",
                    "c4isr.comm_encryption",
                    "c4isr.comms_voice",
                    "c4isr.comms_data",
                    "c4isr.comms_video",
                    "c4isr.network_id",
                    "c4isr.network_type",
                    "c4isr.network_topology",
                    "c4isr.network_status",
                    "c4isr.network_bandwidth",
                    "c4isr.network_latency",
                    "c4isr.network_jitter",
                    "c4isr.network_packet_loss",
                    "c4isr.intelligence_id",
                    "c4isr.intelligence_type",
                    "c4isr.intelligence_source",
                    "c4isr.intelligence_confidence",
                    "c4isr.intelligence_timeliness",
                    "c4isr.intelligence_classification",
                    "c4isr.intelligence_report",
                    "c4isr.intelligence_update",
                    "c4isr.surveillance_id",
                    "c4isr.surveillance_type",
                    "c4isr.surveillance_area",
                    "c4isr.surveillance_coverage",
                    "c4isr.surveillance_status",
                    "c4isr.reconnaissance_id",
                    "c4isr.reconnaissance_type",
                    "c4isr.reconnaissance_mission",
                    "c4isr.reconnaissance_report",
                    "c4isr.reconnaissance_result",
                    "c4isr.situational_awareness",
                    "c4isr.situational_picture",
                    "c4isr.common_operational_picture",
                    "c4isr.common_tactical_picture",
                    "c4isr.track_data",
                    "c4isr.track_id",
                    "c4isr.track_number",
                    "c4isr.track_type",
                    "c4isr.track_status",
                    "c4isr.track_quality",
                    "c4isr.track_source",
                    "c4isr.track_update",
                    "c4isr.track_history",
                    "c4isr.track_prediction",
                    "c4isr.target_designation",
                    "c4isr.target_id",
                    "c4isr.target_type",
                    "c4isr.target_location",
                    "c4isr.target_priority",
                    "c4isr.target_status",
                    "c4isr.friendly_forces",
                    "c4isr.hostile_forces",
                    "c4isr.neutral_forces",
                    "c4isr.civilian",
                    "c4isr.rules_of_engagement",
                    "c4isr.fire_support",
                    "c4isr.air_defense",
                    "c4isr.electronic_warfare",
                    "c4isr.signal_intelligence",
                    "c4isr.comms_intelligence",
                    "c4isr.imagery_intelligence",
                    "c4isr.measurement_intelligence",
                    "c4isr.humint",
                    "c4isr.osint",
                    "c4isr.geoint",
                    "c4isr.datastream",
                    "c4isr.broadcast_channel",
                    "c4isr.broadcast_frequency",
                    "c4isr.broadcast_schedule",
                    "c4isr.alert_status",
                    "c4isr.readiness_state",
                    "c4isr.deployment_status",
                    "c4isr.logistics_status",
                    "c4isr.maintenance_status",
                    "c4isr.supply_status",
                ],
                "count": 100,
            },
            "geospatial_military": {
                "description": "MGRS, NATO GIS, terrain analysis, military mapping, geodetic systems",
                "reference": "NATO STANAG 2218, MGRS, DMH, MIL-STD-2401",
                "fields": [
                    "mgrs.coordinate",
                    "mgrs.zone",
                    "mgrs.band",
                    "mgrs.grid_square",
                    "mgrs.easting",
                    "mgrs.northing",
                    "mgrs.precision",
                    "mgrs.100km_square",
                    "mgrs.10km_square",
                    "mgrs.1km_square",
                    "mgrs.100m_square",
                    "mgrs.10m_square",
                    "mgrs.1m_square",
                    "mgrs.latitude",
                    "mgrs.longitude",
                    "mgrs.elevation",
                    "mgrs.datum",
                    "mgrs.ellipsoid",
                    "mgrs.projection",
                    "mgrs.scale_factor",
                    "mgrs.convergence",
                    "mgrs.grid_convergence",
                    "mgrs.point_grid",
                    "mgrs.line_grid",
                    "mgrs.area_grid",
                    "nato_gis.layer_id",
                    "nato_gis.layer_name",
                    "nato_gis.layer_type",
                    "nato_gis.layer_scale",
                    "nato_gis.layer_resolution",
                    "nato_gis.coverage_area",
                    "nato_gis.feature_id",
                    "nato_gis.feature_type",
                    "nato_gis.feature_class",
                    "nato_gis.feature_attribute",
                    "nato_gis.spatial_extent",
                    "nato_gis.temporal_extent",
                    "nato_gis.classification",
                    "terrain.elevation_model",
                    "terrain.digital_elevation_model",
                    "terrain.contour_interval",
                    "terrain.slope",
                    "terrain.aspect",
                    "terrain.roughness",
                    "terrain.vegetation_type",
                    "terrain.vegetation_density",
                    "terrain.soil_type",
                    "terrain.ground_cover",
                    "terrain.surface_material",
                    "terrain.friction_coefficient",
                    "terrain.trafficability",
                    "terrain.obstacle_type",
                    "terrain.obstacle_height",
                    "terrain.obstacle_width",
                    "terrain.obstacle_depth",
                    "terrain.urban_area",
                    "terrain.urban_density",
                    "terrain.building_height",
                    "terrain.road_network",
                    "terrain.road_type",
                    "terrain.road_surface",
                    "terrain.road_width",
                    "terrain.bridge_load",
                    "terrain.water_feature",
                    "terrain.water_depth",
                    "terrain.water_velocity",
                    "terrain.ford_depth",
                    "terrain.swamp_area",
                    "terrain.forest_density",
                    "terrain.tree_height",
                    "terrain.clearing_size",
                    "terrain.hillshade",
                    "terrain.viewshed",
                    "terrain.line_of_sight",
                    "terrain.radio_horizon",
                    "terrain.radar_coverage",
                    "terrain.terrain_obstruction",
                    "terrain.slope_gradient",
                    "terrain.slope_direction",
                    "terrain.elevation_contour",
                    "terrain.spot_elevation",
                    "terrain.terrain_profile",
                    "terrain.cross_country_movement",
                    "terrain.military_climb",
                    "terrain.aerial_delivery",
                    "terrain.drop_zone",
                    "terrain.landing_zone",
                    "terrain.extraction_zone",
                    "terrain.pickup_zone",
                    "terrain.ammo_point",
                    "terrain.fuel_point",
                    "terrain.supply_point",
                    "terrain.assembly_area",
                    "terrain.release_point",
                    "terrain.checkpoint",
                    "terrain.phase_line",
                    "terrain.objective",
                    "terrain.coordinating_points",
                    "terrain.deception_target",
                    "terrain.tactical_cover",
                    "terrain.concealment",
                    "terrain.caves",
                    "terrain.tunnels",
                    "terrain.underground",
                    "mapping.cartographic_scale",
                    "mapping.projection_type",
                    "mapping.grid_reference",
                    "mapping.geodetic_datum",
                    "mapping.vertical_datum",
                    "mapping.map_sheet",
                    "mapping.map_series",
                    "mapping.map_edition",
                    "mapping.map_date",
                    "mapping.map_authentication",
                    "mapping.map_classification",
                    "mapping.aeronautical_chart",
                    "mapping.nautical_chart",
                    "mapping.topographic_map",
                    "mapping.thematic_map",
                    "mapping.special_map",
                    "mapping.city_map",
                    "mapping.terrain_model",
                    "mapping.tactical_map",
                    "mapping.operation_map",
                ],
                "count": 100,
            },
        },
        "totals": {
            "categories": 6,
            "total_fields": 600,
        }
    }

    return INVENTORY


def main():
    print("=" * 70)
    print("DEFENSE AND MILITARY METADATA FIELD INVENTORY")
    print("=" * 70)
    print()

    inventory = generate_defense_inventory()

    print(f"Generated: {inventory['generated_at']}")
    print(f"Categories: {inventory['totals']['categories']}")
    print(f"Total Fields: {inventory['totals']['total_fields']:,}")
    print()

    print("FIELD COUNTS BY CATEGORY:")
    print("-" * 50)
    for cat_name, cat_data in sorted(inventory['categories'].items(), key=lambda x: x[1]['count'], reverse=True):
        ref = cat_data.get('reference', '')[:40]
        print(f"  {cat_name:30s}: {cat_data['count']:>4}  [{ref}]")

    output_dir = Path("dist/defense_inventory")
    output_dir.mkdir(parents=True, exist_ok=True)

    output_file = output_dir / "defense_inventory.json"
    output_file.write_text(json.dumps(inventory, indent=2, sort_keys=True), encoding="utf-8")
    print()
    print(f"Wrote: {output_file}")

    summary = {
        "generated_at": inventory["generated_at"],
        "source": inventory["source"],
        "description": inventory["description"],
        "totals": inventory["totals"],
        "field_counts_by_category": {}
    }

    for cat_name, cat_data in inventory["categories"].items():
        summary["field_counts_by_category"][cat_name] = {
            "description": cat_data["description"],
            "count": cat_data["count"],
            "reference": cat_data.get("reference", "N/A")
        }

    summary_file = output_dir / "defense_summary.json"
    summary_file.write_text(json.dumps(summary, indent=2), encoding="utf-8")
    print(f"Wrote: {summary_file}")


if __name__ == "__main__":
    main()
