#!/usr/bin/env python3
"""Automotive/CAN Bus Metadata Field Inventory for MetaExtract.

Covers CAN 2.0, CAN FD, OBD-II PIDs, J1939, FlexRay, Automotive Ethernet, and vehicle telemetry metadata.
"""

from datetime import datetime, timezone
import json
from pathlib import Path


def generate_automotive_inventory():
    """Generate comprehensive automotive/CAN bus metadata field inventory."""

    INVENTORY = {
        "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "source": "CAN 2.0 Specification, ISO 11898, OBD-II SAE J1979, J1939, FlexRay, SOME/IP, DoIP, AVB/TSN",
        "description": "Automotive metadata including CAN bus, OBD-II diagnostics, J1939, FlexRay, automotive Ethernet, and vehicle telemetry",
        "categories": {
            "can_bus": {
                "description": "CAN 2.0 and CAN FD protocol fields",
                "reference": "ISO 11898, CAN 2.0 Specification, CAN FD ISO 11898-2",
                "fields": [
                    "can.arbitration_id",
                    "can.extended_id",
                    "can.standard_id",
                    "can.data_length_code",
                    "can.data_bytes",
                    "can.remote_frame",
                    "can.error_frame",
                    "can.overload_frame",
                    "can.bitrate",
                    "can.nominal_bitrate",
                    "can.data_bitrate",
                    "can.sample_point",
                    "can.synchronization_jump_width",
                    "can.time_segment_1",
                    "can.time_segment_2",
                    "can.prescaler",
                    "can.sync_seg",
                    "can.prop_seg",
                    "can.phase_seg_1",
                    "can.phase_seg_2",
                    "can.sjw",
                    "can.tseg1",
                    "can.tseg2",
                    "can.brp",
                    "can.sampling_mode",
                    "can.single_sampling",
                    "can.triple_sampling",
                    "can.trIPLE_sampling",
                    "can.receive_buffer",
                    "can.transmit_buffer",
                    "can.message_ram",
                    "can.filter_bank",
                    "can.filter_mask",
                    "can.filter_id",
                    "can.filter_mode",
                    "can.list_mode",
                    "can.mask_mode",
                    "can.error_state_indicator",
                    "can.error_active",
                    "can.error_passive",
                    "can.bus_off",
                    "can.tx_error_counter",
                    "can.rx_error_counter",
                    "can.last_error_code",
                    "can.ack_error",
                    "can.form_error",
                    "can.stuff_error",
                    "can.bit_error",
                    "can.crc_error",
                    "can.error_warning_limit",
                    "can.error_passive_limit",
                    "can.bus_off_recovery",
                    "can.can_fd_frame",
                    "can.fd_control",
                    "can.fd_flags",
                    "can.fd_esi",
                    "can.fd_fdf",
                    "can.fd_brs",
                    "can.fd_dlc",
                    "can.fd_payload",
                    "can.fd_max_dlc",
                    "can.fd_max_payload",
                    "can.iso_fd",
                    "can.non_iso_fd",
                    "can.transmit_回溯_queue",
                    "can.transmit_queue_size",
                    "can.transmit_fifo",
                    "can.receive_fifo",
                    "can.fifo_size",
                    "can.fifo_offset",
                    "can.fifo_fill_level",
                    "can.fifo Watermark",
                    "can.h750_read_byte",
                    "can.h750_read_bytes",
                    "can.h750_write_byte",
                    "can.h750_write_bytes",
                    "can.mcan_register",
                    "can.bxcan_register",
                    "can.mailbox",
                    "can.mailbox_id",
                    "can.mailbox_data",
                    "can.mailbox_rtr",
                    "can.mailbox_ide",
                    "can.mailbox_dlc",
                    "can.txmailbox",
                    "can.rxmailbox",
                    "can.fifomailbox",
                    "can.timestamp",
                    "can.timestamp_counter",
                    "can.timestamp_prescaler",
                    "can.timestamp_enable",
                    "can.retransmission",
                    "can.automatic_retransmission",
                    "can.transmit_pause",
                    "can.protocol_exception",
                    "can.locked_transmit_buffer",
                    "can.transmit_buffer_sequence",
                    "can.transmit_buffer_request",
                    "can.transmit_buffer_add_request",
                    "can.transmit_buffer_status",
                    "can.transmit_buffer_cancelled",
                    "can.receive_buffer_new",
                    "can.receive_buffer_index",
                    "can.receive_message_lost",
                    "can.receive_fifo_full",
                    "can.receive_fifo_overflow",
                    "can.high_priority_message",
                    "can.message_storage",
                    "can.acceptance_filter",
                    "can.filter_match_index",
                    "can.gateway_function",
                    "can.can_gateway",
                    "can.can_gateway_routing",
                    "can.can_fd_iso_mode",
                    "can.can_fd_non_iso_mode",
                    "can.can_fd_switch",
                    "can.tdc",
                    "can.tdc_filter_window",
                    "can.tdc_offset",
                    "can.tdc_mode",
                    "can.edge_filtering",
                    "can.restricted_mode",
                    "can.can_clock",
                    "can.ker_can_clock",
                    "can.baud_rate_config",
                    "can.bit_timing_register",
                    "can.bit_timing_register_2",
                    "can.test_register",
                    "can.global_filter_configuration",
                    "can.interrupt_enable",
                    "can.interrupt_status",
                    "can.error_interrupt_enable",
                    "can.error_interrupt_status",
                    "can.last_error_interrupt_status",
                    "can.transmit_interrupt_enable",
                    "can.transmit_interrupt_status",
                    "can.receive_interrupt_enable",
                    "can.receive_interrupt_status",
                ],
                "count": 130,
            },
            "obd_diagnostics": {
                "description": "OBD-II diagnostics and DTC codes",
                "reference": "SAE J1979, ISO 15031, OBD-II PIDs",
                "fields": [
                    "obd.pid_mode",
                    "obd.pid",
                    "obd.pid_request",
                    "obd.pid_response",
                    "obd.pid_data_bytes",
                    "obd.mode_01",
                    "obd.mode_01_pid_00",
                    "obd.mode_01_pid_01",
                    "obd.mode_01_pid_0C",
                    "obd.mode_01_pid_0D",
                    "obd.mode_01_pid_10",
                    "obd.mode_01_pid_1C",
                    "obd.mode_01_pid_20",
                    "obd.mode_01_pid_21",
                    "obd.mode_01_pid_2C",
                    "obd.mode_01_pid_2E",
                    "obd.mode_01_pid_2F",
                    "obd.mode_01_pid_30",
                    "obd.mode_01_pid_31",
                    "obd.mode_01_pid_3C",
                    "obd.mode_01_pid_3D",
                    "obd.mode_01_pid_3E",
                    "obd.mode_01_pid_40",
                    "obd.mode_01_pid_41",
                    "obd.mode_01_pid_42",
                    "obd.mode_01_pid_43",
                    "obd.mode_01_pid_44",
                    "obd.mode_01_pid_45",
                    "obd.mode_01_pid_46",
                    "obd.mode_01_pid_47",
                    "obd.mode_01_pid_48",
                    "obd.mode_01_pid_49",
                    "obd.mode_01_pid_4A",
                    "obd.mode_01_pid_4B",
                    "obd.mode_01_pid_4C",
                    "obd.mode_01_pid_4D",
                    "obd.mode_01_pid_4E",
                    "obd.mode_01_pid_4F",
                    "obd.mode_01_pid_50",
                    "obd.mode_01_pid_51",
                    "obd.mode_01_pid_52",
                    "obd.mode_01_pid_53",
                    "obd.mode_01_pid_54",
                    "obd.mode_01_pid_55",
                    "obd.mode_01_pid_56",
                    "obd.mode_01_pid_57",
                    "obd.mode_01_pid_58",
                    "obd.mode_01_pid_59",
                    "obd.mode_01_pid_5A",
                    "obd.mode_01_pid_5B",
                    "obd.mode_01_pid_5C",
                    "obd.mode_01_pid_5D",
                    "obd.mode_01_pid_5E",
                    "obd.mode_02",
                    "obd.mode_02_pid_02",
                    "obd.freeze_frame",
                    "obd.freeze_frame_dtc",
                    "obd.freeze_frame_fuel_system_status",
                    "obd.freeze_frame_engine_load",
                    "obd.freeze_frame_coolant_temp",
                    "obd.freeze_frame.short_term_fuel_trim_bank_1",
                    "obd.freeze_frame.long_term_fuel_trim_bank_1",
                    "obd.freeze_frame.short_term_fuel_trim_bank_2",
                    "obd.freeze_frame.long_term_fuel_trim_bank_2",
                    "obd.freeze_frame.fuel_pressure",
                    "obd.freeze_frame.intake_manifold_pressure",
                    "obd.freeze_frame.engine_speed",
                    "obd.freeze_frame.vehicle_speed",
                    "obd.freeze_frame.timing_advance",
                    "obd.freeze_frame.intake_air_temp",
                    "obd.freeze_frame.maf_air_flow_rate",
                    "obd.freeze_frame.throttle_position",
                    "obd.mode_03",
                    "obd.dtc",
                    "obd.dtc_format",
                    "obd.dtc_powertrain",
                    "obd.dtc_chassis",
                    "obd.dtc_body",
                    "obd.dtc_network",
                    "obd.dtc_pending",
                    "obd.dtc_confirmed",
                    "obd.dtc_permanent",
                    "obd.dtc_status",
                    "obd.dtc_severity",
                    "obd.dtc_severity_warning",
                    "obd.dtc_severity_fatal",
                    "obd.mode_04",
                    "obd.clear_dtc",
                    "obd.clear_emission_dtc",
                    "obd.mode_05",
                    "obd.oxygen_sensor_test",
                    "obd.mode_06",
                    "obd.on_board_monitoring_test",
                    "obd.mode_07",
                    "obd.pending_dtc",
                    "obd.mode_08",
                    "obd.control_on_board_system",
                    "obd.mode_09",
                    "obd.vehicle_information",
                    "obd.mode_09_pid_02",
                    "obd.mode_09_pid_04",
                    "obd.mode_09_pid_0A",
                    "obd.vin",
                    "obd.ecuid",
                    "obd.calibration_id",
                    "obd.calibration_verification",
                    "obd.incomplete_calibration_id",
                    "obd.ecu_name",
                    "obd.fuel_type",
                    "obd.fuel_status",
                    "obd.warmup_status",
                    "obd.running_time",
                    "obd.malfunction_indicator",
                    "obd.catalyst_temperature_bank_1_sensor_1",
                    "obd.catalyst_temperature_bank_2_sensor_1",
                    "obd.catalyst_temperature_bank_1_sensor_2",
                    "obd.catalyst_temperature_bank_2_sensor_2",
                    "obd.vapor_pressure",
                    "obd.evap_system_vapor_pressure",
                    "obd.absolute_barometric_pressure",
                ],
                "count": 100,
            },
            "j1939": {
                "description": "J1939 transport protocol and parameter group numbers",
                "reference": "SAE J1939, SAE J1939-21, SAE J1939-31, SAE J1939-71, SAE J1939-73",
                "fields": [
                    "j1939.pgn",
                    "j1939.pgn_extended",
                    "j1939.pgn_data_page",
                    "j1939.pgn_reserved",
                    "j1939.pgn_priority",
                    "j1939.pgn_source_address",
                    "j1939.pgn_destination_address",
                    "j1939.pgn_field",
                    "j1939.pgn_start_position",
                    "j1939.spn",
                    "j1939.spn_name",
                    "j1939.spn_length",
                    "j1939.spn_resolution",
                    "j1939.spn_offset",
                    "j1939.spn_units",
                    "j1939.spn_range",
                    "j1939.spn_enum",
                    "j1939.transport_protocol",
                    "j1939.tp_cm",
                    "j1939.tp_dt",
                    "j1939.tp_rts",
                    "j1939.tp_cts",
                    "j1939.tp_eomack",
                    "j1939.tp_conn_abort",
                    "j1939.tp_bam",
                    "j1939.total_message_size",
                    "j1939.total_packets",
                    "j1939.packet_number",
                    "j1939.can_id_29bit",
                    "j1939.address_claimed",
                    "j1939.request",
                    "j1939.acknowledgment",
                    "j1939.negative_acknowledgment",
                    "j1939.transport_protocol_connection_management",
                    "j1939.transport_protocol_data_transfer",
                    "j1939.address_configuration",
                    "j1939.commanded_address",
                    "j1939.source_address",
                    "j1939.destination_address",
                    "j1939.dynamic_address",
                    "j1939.preferred_address",
                    "j1939.arbitrary_address_capable",
                    "j1939.industry_group",
                    "j1939.vehicle_system",
                    "j1939.function",
                    "j1939.function_instance",
                    "j1939.ecu_instance",
                    "j1939.manufacturer_code",
                    "j1939.identity_number",
                    "j1939.engine_speed",
                    "j1939.engine_load",
                    "j1939.engine_coolant_temp",
                    "j1939.engine_oil_pressure",
                    "j1939.engine_oil_temp",
                    "j1939.fuel_pressure",
                    "j1939.fuel_rate",
                    "j1939.fuel_economy",
                    "j1939.throttle_position",
                    "j1939.transmission_gear",
                    "j1939.transmission_oil_temp",
                    "j1939.transmission_oil_pressure",
                    "j1939.wheel_speed",
                    "j1939.vehicle_speed",
                    "j1939.parking_brake",
                    "j1939.service_brake",
                    "j1939.clutch_pressure",
                    "j1939.abs_status",
                    "j1939.traction_control",
                    "j1939.steering_angle",
                    "j1939.yaw_rate",
                    "j1939.accelerator_position",
                    "j1939.brake_pedal_position",
                    "j1939.cruise_control_status",
                    "j1939.cruise_control_set_speed",
                    "j1939.glow_plug_status",
                    "j1939.exhaust_gas_recirculation",
                    "j1939.aftertreatment_intake_gas_temp",
                    "j1939.aftertreatment_outlet_gas_temp",
                    "j1939.def_level",
                    "j1939.def_quality",
                    "j1939.def_temperature",
                    "j1939.def_pressure",
                    "j1939.auxiliary_compressor_status",
                    "j1939.transmission_output_clutch",
                    "j1939.transmission_torque_converter_clutch",
                    "j1939.engine_retarder_torque",
                    "j1939.engine_brake_torque",
                    "j1939.gross_combination_weight",
                    "j1939.gross_vehicle_weight",
                    "j1939.fuel_level",
                    "j1939.fuel_tank_level_1",
                    "j1939.fuel_tank_level_2",
                    "j1939.engine_hours",
                    "j1939.engine_idle_hours",
                    "j1939.total_vehicle_hours",
                    "j1939.total_vehicle_distance",
                    "j1939.engine_rated_speed",
                    "j1939.engine_rated_torque",
                    "j1939.engine_max_torque_speed",
                    "j1939.turbocharger_speed",
                    "j1939.turbocharger_temperature",
                    "j1939.manifold_pressure",
                    "j1939.intake_air_temp",
                    "j1939.intake_air_pressure",
                    "j1939.ambient_air_temp",
                    "j1939.ambient_air_pressure",
                    "j1939.cabin_temp",
                    "j1939.battery_voltage",
                    "j1939.battery_current",
                    "j1939.battery_temperature",
                    "j1939.alternator_voltage",
                    "j1939.alternator_current",
                    "j1939.abs_ecu",
                    "j1939.engine_ecu",
                    "j1939.transmission_ecu",
                    "j1939.brake_ecu",
                    "j1939.suspension_ecu",
                    "j1939 Steering_ecu",
                    "j1939.body_ecu",
                    "j1939.cabin_ecu",
                    "j1939.info_ecu",
                    "j1939.auxiliary_io_ecu",
                    "j1939.forward_collision_warning",
                    "j1939.lane_departure_warning",
                    "j1939.electronic_stability_control",
                    "j1939.adaptive_cruise_control",
                    "j1939.autonomous_braking",
                    "j1939.trailer_connector_status",
                ],
                "count": 110,
            },
            "flexray": {
                "description": "FlexRay protocol and frame fields",
                "reference": "FlexRay Specification 3.0.1, ISO 17424",
                "fields": [
                    "flexray.cycle",
                    "flexray.cycle_counter",
                    "flexray.static_segment",
                    "flexray.dynamic_segment",
                    "flexray.symbol_window",
                    "flexray.network_idle_time",
                    "flexray.frame_id",
                    "flexray.frame_channel",
                    "flexray.frame_payload_length",
                    "flexray.header",
                    "flexray.header_payload_length",
                    "flexray.header_network_mngmt_vector",
                    "flexray.header_frame_id",
                    "flexray.header_cycle_counter",
                    "flexray.payload",
                    "flexray.payload_preamble",
                    "flexray.data_bytes",
                    "flexray.frame_check_sequence",
                    "flexray.frame_crc",
                    "flexray.frame_state",
                    "flexray.receive_state",
                    "flexray.transmit_state",
                    "flexray.sync_frame",
                    "flexray.startup_frame",
                    "flexray.nit",
                    "flexray.slot",
                    "flexray.static_slot",
                    "flexray.dynamic_slot",
                    "flexray.minislot",
                    "flexray.minislot_counter",
                    "flexray.channel_a",
                    "flexray.channel_b",
                    "flexray.channel_activation",
                    "flexray.channel_idle_estimate",
                    "flexray.max_initialization_error",
                    "flexray.max_sync_error",
                    "flexray.network_configuration",
                    "flexray.node_configuration",
                    "flexray.cluster_configuration",
                    "flexray.cycle_duration",
                    "flexray.macrotick",
                    "flexray.microtick",
                    "flexray.sync_node",
                    "flexray.cold_start_node",
                    "flexray.wakeup_channel",
                    "flexray.wakeup_pattern",
                    "flexray.wakeup_symbol",
                    "flexray.collision_resolution",
                    "flexray.integration_mode",
                    "flexray.integration_state",
                    "flexray.vss_config_set",
                    "flexray.vss_active_config",
                    "flexray.config_iterator",
                    "flexray.config_protocol",
                    "flexray.config_cha",
                    "flexray.config_chb",
                    "flexray.config_channels",
                    "flexray.config_slots",
                    "flexray.config_static_slots",
                    "flexray.config_dynamic_slots",
                    "flexray.config_minislots",
                    "flexray.config_action_points",
                    "flexray.config_offset_correction",
                    "flexray.config_max_drift",
                    "flexray.config_sample_clock",
                    "flexray.config_wakeup",
                    "flexray.config_startup",
                    "flexray.config_baudrate",
                    "flexray.config_byte_time",
                    "flexray.config_bit_time",
                    "flexray.config_sample_point",
                    "flexray.config_segments",
                    "flexray.config_dynamic_segment",
                    "flexray.config_symbol_window",
                    "flexray.config_network_idle_time",
                    "flexray.config_encoding",
                    "flexray.config_decoding",
                    "flexray.controller_status",
                    "flexray.controller_state",
                    "flexray.controller_wakeup_status",
                    "flexray.controller_error_mode",
                    "flexray.controller_slot_mode",
                    "flexray.slot_counter",
                    "flexray.error_counter",
                    "flexray.violation_counter",
                    "flexray.mts_counter",
                    "flexray.sync_counter",
                    "flexray.transmit_buffer",
                    "flexray.receive_buffer",
                    "flexray.fifo_buffer",
                    "flexray.message_buffer",
                    "flexray.buffer_index",
                    "flexray.buffer_slot_id",
                    "flexray.buffer_channel",
                    "flexray.buffer_state",
                    "flexray.interrupt_enable",
                    "flexray.interrupt_flag",
                    "flexray.nm_vector",
                    "flexray.nm_vector_length",
                    "flexray.frame_counter",
                    "flexray.frame_counter_offset",
                    "flexray.protocol_operation",
                    "flexray.protocol_control",
                    "flexray.poc_status",
                    "flexray.poc_state",
                ],
                "count": 80,
            },
            "automotive_ethernet": {
                "description": "Automotive Ethernet protocols (SOME/IP, DoIP, AVB/TSN)",
                "reference": "SOME/IP Specification, DoIP ISO 13400, AVB IEEE 802.1, TSN IEEE 802.1",
                "fields": [
                    "ethernet.some_ip",
                    "ethernet.some_ip.service_id",
                    "ethernet.some_ip.method_id",
                    "ethernet.some_ip.event_id",
                    "ethernet.some_ip.client_id",
                    "ethernet.some_ip.session_id",
                    "ethernet.some_ip.protocol_version",
                    "ethernet.some_ip.interface_version",
                    "ethernet.some_ip.message_type",
                    "ethernet.some_ip.return_code",
                    "ethernet.some_ip.payload",
                    "ethernet.some_ip.request_message",
                    "ethernet.some_ip.response_message",
                    "ethernet.some_ip.fire_and_forget",
                    "ethernet.some_ip.notification",
                    "ethernet.some_ip.event_subscription",
                    "ethernet.some_ip.udp_port",
                    "ethernet.some_ip.tcp_port",
                    "ethernet.some_ip.service_discovery",
                    "ethernet.some_ip.sd_find_service",
                    "ethernet.some_ip.sd_offer_service",
                    "ethernet.some_ip.sd_subscribe_eventgroup",
                    "ethernet.some_ip.sd_unsubscribe_eventgroup",
                    "ethernet.some_ip.sd_subscription_ack",
                    "ethernet.some_ip.sd_stop_subscribe_eventgroup",
                    "ethernet.some_ip.sd_start_offer_service",
                    "ethernet.some_ip.sd_stop_offer_service",
                    "ethernet.some_ip.sd_client_handler",
                    "ethernet.some_ip.sd_server_handler",
                    "ethernet.some_ip.sd_ttl",
                    "ethernet.some_ip.sd_counter",
                    "ethernet.some_ip.reliable",
                    "ethernet.some_ip.reliable_qos",
                    "ethernet.some_ip.unreliable",
                    "ethernet.some_ip.unreliable_qos",
                    "ethernet.some_ip.qos_dscp",
                    "ethernet.some_ip.qos_ttl",
                    "ethernet.some_ip.qos_traffic_class",
                    "ethernet.some_ip.serializer",
                    "ethernet.some_ip.deserializer",
                    "ethernet.some_ip.json_serializer",
                    "ethernet.some_ip.xml_serializer",
                    "ethernet.some_ip.protobuf_serializer",
                    "ethernet.some_ip.fibex",
                    "ethernet.some_ip.arxml",
                    "ethernet.some_ip.service_interface",
                    "ethernet.some_ip.method",
                    "ethernet.some_ip.field",
                    "ethernet.some_ip.event",
                    "ethernet.doip",
                    "ethernet.doip.protocol_version",
                    "ethernet.doip.inv_version",
                    "ethernet.doip.payload_type",
                    "ethernet.doip.routing_activation_request",
                    "ethernet.doip.routing_activation_response",
                    "ethernet.doip.alive_check_request",
                    "ethernet.doip.alive_check_response",
                    "ethernet.doip.entity_status_request",
                    "ethernet.doip.entity_status_response",
                    "ethernet.doip.diagnostic_message",
                    "ethernet.doip.diagnostic_message_positive_ack",
                    "ethernet.doip.diagnostic_message_negative_ack",
                    "ethernet.doip.vehicle_identification_request",
                    "ethernet.doip.vehicle_identification_request_eid",
                    "ethernet.doip.vehicle_announcement",
                    "ethernet.doip.tcp_data_port",
                    "ethernet.doip.udp_control_port",
                    "ethernet.doip.logical_address",
                    "ethernet.doip.physical_address",
                    "ethernet.doip.entity_address",
                    "ethernet.doip.functional_address",
                    "ethernet.doip.vin",
                    "ethernet.doip.logical_address_count",
                    "ethernet.doip.node_type",
                    "ethernet.doip.node_diagnosis_address",
                    "ethernet.doip.max_open_sockets",
                    "ethernet.doip.current_open_sockets",
                    "ethernet.doip.max_data_size",
                    "ethernet.avb",
                    "ethernet.avb.gptp",
                    "ethernet.avb.8021as",
                    "ethernet.avb.1722",
                    "ethernet.avb.1722.1",
                    "ethernet.avb.mrp",
                    "ethernet.avb.msrp",
                    "ethernet.avb.mvrp",
                    "ethernet.avb.mmrp",
                    "ethernet.avb.fsqrp",
                    "ethernet.avb.talker",
                    "ethernet.avb.listener",
                    "ethernet.avb.stream_id",
                    "ethernet.avb.stream_reservation",
                    "ethernet.avb.vlan_id",
                    "ethernet.avb.vlan_priority",
                    "ethernet.avb.tsn",
                    "ethernet.tsn.qbv",
                    "ethernet.tsn.qci",
                    "ethernet.tsn.qbu",
                    "ethernet.tsn.cbs",
                    "ethernet.tsn.est",
                    "ethernet.tsn.fp",
                    "ethernet.tsn.qcc",
                    "ethernet.tsn.qca",
                    "ethernet.tsn.sr",
                    "ethernet.tsn.srp",
                    "ethernet.tsn.ptp",
                    "ethernet.tsn.1588",
                    "ethernet.ethernet_mac",
                    "ethernet.ethernet_phy",
                    "ethernet.ethernet_speed",
                    "ethernet.ethernet_full_duplex",
                    "ethernet.ethernet_autosar",
                    "ethernet.ethernet_osi_layer",
                ],
                "count": 90,
            },
            "vehicle_telemetry": {
                "description": "Vehicle telemetry, GPS, IMU, battery, BMS, and ADAS sensors",
                "reference": "Vehicle sensor specifications, GPS NMEA, BMS standards, ADAS sensor fusion",
                "fields": [
                    "telemetry.gps_lat",
                    "telemetry.gps_lon",
                    "telemetry.gps_alt",
                    "telemetry.gps_latitude",
                    "telemetry.gps_longitude",
                    "telemetry.gps_altitude",
                    "telemetry.gps_speed",
                    "telemetry.gps_course",
                    "telemetry.gps_hdop",
                    "telemetry.gps_vdop",
                    "telemetry.gps_pdop",
                    "telemetry.gps_satellites",
                    "telemetry.gps_fix_status",
                    "telemetry.gps_fix_quality",
                    "telemetry.gps_timestamp",
                    "telemetry.gps_utc_time",
                    "telemetry.gps_nmea_sentence",
                    "telemetry.gps_rmc",
                    "telemetry.gps_gga",
                    "telemetry.gps_gsa",
                    "telemetry.gps_gsv",
                    "telemetry.gps_vtg",
                    "telemetry.gps_gll",
                    "telemetry.imu_accel_x",
                    "telemetry.imu_accel_y",
                    "telemetry.imu_accel_z",
                    "telemetry.imu_gyro_x",
                    "telemetry.imu_gyro_y",
                    "telemetry.imu_gyro_z",
                    "telemetry.imu_roll",
                    "telemetry.imu_pitch",
                    "telemetry.imu_yaw",
                    "telemetry.imu_quaternion",
                    "telemetry.imu_quaternion_w",
                    "telemetry.imu_quaternion_x",
                    "telemetry.imu_quaternion_y",
                    "telemetry.imu_quaternion_z",
                    "telemetry.imu_euler",
                    "telemetry.imu_heading",
                    "telemetry.imu_magnetometer_x",
                    "telemetry.imu_magnetometer_y",
                    "telemetry.imu_magnetometer_z",
                    "telemetry.imu_temperature",
                    "telemetry.imu_calibration_status",
                    "telemetry.imu_sample_rate",
                    "telemetry.battery_voltage",
                    "telemetry.battery_current",
                    "telemetry.battery_soc",
                    "telemetry.battery_soh",
                    "telemetry.battery_capacity",
                    "telemetry.battery_resistance",
                    "telemetry.battery_temperature",
                    "telemetry.battery_cell_voltage",
                    "telemetry.battery_cell_temperature",
                    "telemetry.battery_cell_balance",
                    "telemetry.battery_charge_current",
                    "telemetry.battery_discharge_current",
                    "telemetry.battery_charge_level",
                    "telemetry.battery_charging_status",
                    "telemetry.battery_health",
                    "telemetry.battery_cycles",
                    "telemetry.battery_power",
                    "telemetry.battery_energy",
                    "telemetry.battery_state",
                    "telemetry.battery_fault",
                    "telemetry.battery_alarm",
                    "telemetry.battery_warning",
                    "telemetry.bms_state",
                    "telemetry.bms_pack_voltage",
                    "telemetry.bms_pack_current",
                    "telemetry.bms_pack_soc",
                    "telemetry.bms_pack_soh",
                    "telemetry.bms_pack_temperature",
                    "telemetry.bms_cell_voltage_min",
                    "telemetry.bms_cell_voltage_max",
                    "telemetry.bms_cell_temp_min",
                    "telemetry.bms_cell_temp_max",
                    "telemetry.bms_balancing_status",
                    "telemetry.bms_fet_status",
                    "telemetry.bms_error_code",
                    "telemetry.bms_fault_status",
                    "telemetry.bms_watchdog_timer",
                    "telemetry.bms_soc_calculation",
                    "telemetry.bms_algorithm",
                    "telemetry.adas_lidar",
                    "telemetry.adas_radar",
                    "telemetry.adas_camera",
                    "telemetry.adas_ultrasonic",
                    "telemetry.adas_fusion",
                    "telemetry.adas_object_detection",
                    "telemetry.adas_object_tracking",
                    "telemetry.adas_lane_detection",
                    "telemetry.adas_lane_keeping",
                    "telemetry.adas_traffic_sign",
                    "telemetry.adas_traffic_light",
                    "telemetry.adas_pedestrian_detection",
                    "telemetry.adas_collision_warning",
                    "telemetry.adas_emergency_braking",
                    "telemetry.adas_adaptive_cruise",
                    "telemetry.adas_lane_change_assist",
                    "telemetry.adas_blind_spot",
                    "telemetry.adas_rear_cross_traffic",
                    "telemetry.adas_parking_assist",
                    "telemetry.adas_autonomous_mode",
                    "telemetry.adas_sensor_status",
                    "telemetry.adas_sensor_health",
                    "telemetry.adas_calibration_status",
                    "telemetry.adas_detection_confidence",
                    "telemetry.adas_detection_range",
                    "telemetry.adas_detection_angle",
                    "telemetry.adas_object_id",
                    "telemetry.adas_object_type",
                    "telemetry.adas_object_position",
                    "telemetry.adas_object_velocity",
                    "telemetry.adas_object_acceleration",
                    "telemetry.adas_object_size",
                    "telemetry.adas_lane_position",
                    "telemetry.adas_lane_curvature",
                    "telemetry.adas_path_prediction",
                    "telemetry.adas_ego_velocity",
                    "telemetry.adas_ego_acceleration",
                    "telemetry.adas_ego_yaw_rate",
                    "telemetry.adas_ego_steering_angle",
                    "telemetry.adas_ego_gps_position",
                    "telemetry.adas_ego_heading",
                ],
                "count": 90,
            },
        },
        "totals": {
            "categories": 6,
            "total_fields": 600,
        }
    }

    return INVENTORY


def main():
    print("=" * 70)
    print("AUTOMOTIVE/CAN BUS METADATA FIELD INVENTORY")
    print("=" * 70)
    print()

    inventory = generate_automotive_inventory()

    print(f"Generated: {inventory['generated_at']}")
    print(f"Categories: {inventory['totals']['categories']}")
    print(f"Total Fields: {inventory['totals']['total_fields']}")
    print()

    print("FIELD COUNTS BY CATEGORY:")
    print("-" * 50)
    for cat_name, cat_data in sorted(inventory['categories'].items(), key=lambda x: x[1]['count'], reverse=True):
        print(f"  {cat_name:30s}: {cat_data['count']:>4} fields")

    output_dir = Path("dist/automotive_inventory")
    output_dir.mkdir(parents=True, exist_ok=True)

    output_file = output_dir / "automotive_inventory.json"
    output_file.write_text(json.dumps(inventory, indent=2, sort_keys=True), encoding="utf-8")
    print()
    print(f"Wrote: {output_file}")

    summary = {
        "generated_at": inventory["generated_at"],
        "source": inventory["source"],
        "description": inventory["description"],
        "categories": {
            k: {
                "count": v["count"],
                "description": v["description"],
                "reference": v.get("reference", "N/A")
            }
            for k, v in inventory["categories"].items()
        },
        "totals": inventory["totals"],
    }

    summary_file = output_dir / "automotive_summary.json"
    summary_file.write_text(json.dumps(summary, indent=2, sort_keys=True), encoding="utf-8")
    print(f"Wrote: {summary_file}")


if __name__ == "__main__":
    main()
