#!/usr/bin/env python3
"""Financial Format Metadata Field Inventory for MetaExtract.

Covers FIX, SWIFT, OFX, XBRL, and other financial data formats.
"""

from datetime import datetime, timezone
from pathlib import Path


def generate_financial_inventory():
    """Generate comprehensive financial format metadata field inventory."""

    INVENTORY = {
        "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "source": "FIX Protocol 5.0 SP2, SWIFT MT/ISO 20022, OFX 2.2, XBRL 2.1, Financial standards",
        "description": "Financial format metadata including FIX, SWIFT, OFX, XBRL, and trading/financial formats",
        "categories": {
            "fix_protocol": {
                "description": "FIX (Financial Information eXchange) protocol fields",
                "reference": "FIX 5.0 SP2, FIXT 1.1",
                "fields": [
                    "fix.BeginString",
                    "fix.BodyLength",
                    "fix.MsgType",
                    "fix.SenderCompID",
                    "fix.TargetCompID",
                    "fix.OnBehalfOfCompID",
                    "fix.DeliverToCompID",
                    "fix.SecureDataLen",
                    "fix.SecureData",
                    "fix.MsgSeqNum",
                    "fix.SendMsgLen",
                    "fix.PossDupFlag",
                    "fix.PossResend",
                    "fix.SendingTime",
                    "fix.OrigSendingTime",
                    "fix.XmlDataLen",
                    "fix.XmlData",
                    "fix.MessageEncoding",
                    "fix.DefaultApplVerID",
                    "fix.ApplReqID",
                    "fix.ApplReqType",
                    "fix.ApplResponseID",
                    "fix.ApplResponseType",
                    "fix.CstmApplMsgID",
                    "fix.TradSesReqID",
                    "fix.TradSesMode",
                    "fix.TradSesStatus",
                    "fix.TradSesEvent",
                    "fix.TradSesTime",
                    "fix.TradSesOpenTime",
                    "fix.TradSesCloseTime",
                    "fix.TradSesVol",
                    "fix.TradeDate",
                    "fix.TransactTime",
                    "fix.UtcTimeOnly",
                    "fix.UtcDateOnly",
                    "fix.LocalMktDate",
                    "fix.OrigTime",
                    "fix.ReceiveTime",
                    "fix.ExpireTime",
                    "fix.AvgPx",
                    "fix.AvgPxPrecision",
                    "fix.Price",
                    "fix.PriceType",
                    "fix.Price2",
                    "fix.Currency",
                    "fix.QuotePriceType",
                    "fix.QuoteType",
                    "fix.UnderlyingPrice",
                    "fix.UnderlyingCurrency",
                    "fix.MarketDataEntryID",
                    "fix.MarketDataEntryType",
                    "fix.MarketDataEntryPx",
                    "fix.MarketDataEntrySize",
                    "fix.MarketDataEntryTime",
                    "fix.MDEntryType",
                    "fix.MDUpdateAction",
                    "fix.MDEntryRefID",
                    "fix.MDEntryPositionNo",
                    "fix.MDStreamID",
                    "fix.MDEntryBuyer",
                    "fix.MDEntrySeller",
                    "fix.MDEntryPosition",
                    "fix.MDEntryTime",
                    "fix.MDEntrySize",
                    "fix.MDEntryPx",
                    "fix.MDEntryType",
                    "fix.MDEntryDateTime",
                    "fix.MDQuoteType",
                    "fix.MDOrderPriority",
                    "fix.MDOrderType",
                    "fix.TimeInForce",
                    "fix.ExpireDate",
                    "fix.ExpireTime",
                    "fix.MinQty",
                    "fix.MaxFloor",
                    "fix.MaxShow",
                    "fix.OrderID",
                    "fix.SecondaryOrderID",
                    "fix.ClOrdID",
                    "fix.OrigClOrdID",
                    "fix.QuoteID",
                    "fix.RefOrderID",
                    "fix.RefOrderType",
                    "fix.OrderStatus",
                    "fix.OrderType",
                    "fix.Side",
                    "fix.OrderQty",
                    "fix.OrderQty2",
                    "fix.OrdType",
                    "fix.ExecInst",
                    "fix.OrdRejReason",
                    "fix.RejectText",
                    "fix.FeeMultiplier",
                    "fix.SettlCurrency",
                    "fix.SettlDate",
                    "fix.SettlDate2",
                    "fix.SettlType",
                    "fix.SettlTime",
                    "fix.SettlDeliveryType",
                    "fix.MaturityMonthYear",
                    "fix.PutOrCall",
                    "fix.OptAttribute",
                    "fix.SecurityID",
                    "fix.SecurityIDSource",
                    "fix.SecurityExchange",
                    "fix.SecurityDesc",
                    "fix.SecurityType",
                    "fix.MaturityDate",
                    "fix.StrikePrice",
                    "fix.OptPrice",
                    "fix.ContractMultiplier",
                    "fix.CouponRate",
                    "fix.ExCouponDate",
                    "fix.IssueDate",
                    "fix.RepoCollateralSecurities",
                    "fix.RepurchaseRate",
                    "fix.RepurchaseTerm",
                    "fix.RepurchaseTotal",
                    "fix.ConvCode",
                    "fix.EncodedSecurityDescLen",
                    "fix.EncodedSecurityDesc",
                    "fix.EncodedListExecInstLen",
                    "fix.EncodedListExecInst",
                    "fix.EncryptedPasswordMethod",
                    "fix.EncryptedPasswordLen",
                    "fix.EncryptedPassword",
                    "fix.EncryptedNewPasswordLen",
                    "fix.EncryptedNewPassword",
                    "fix.NewPassword",
                    "fix.MasterPassword",
                    "fix.Min Tender Size",
                    "fix.SecondaryOrderID",
                    "fix.RefTagID",
                    "fix.RefMsgType",
                    "fix.RefApplVerID",
                    "fix.DefaultApplExtID",
                    "fix.DefaultCstmApplExtID",
                    "fix.ApplicationSystemName",
                    "fix.ApplicationSystemVersion",
                    "fix.ApplicationSystemType",
                    "fix.CstmApplID",
                    "fix.CstmApplVerID",
                    "fix.CstmApplExtID",
                    "fix.MarketDataIncrementalRefresh",
                    "fix.MarketDataRequestReject",
                    "fix.MarketSnapshotFullRefresh",
                    "fix.MarketDataHistory",
                    "fix.SecurityDefinitionRequest",
                    "fix.SecurityDefinition",
                    "fix.SecurityStatusRequest",
                    "fix.SecurityStatus",
                    "fix.TradingSessionStatusRequest",
                    "fix.TradingSessionStatus",
                    "fix.TradingSessionListRequest",
                    "fix.TradingSessionList",
                    "fix.NewOrderSingle",
                    "fix.ExecutionReport",
                    "fix.OrderCancelRequest",
                    "fix.OrderCancelReplaceRequest",
                    "fix.OrderCancelReject",
                    "fix.OrderStatusRequest",
                    "fix.OrderMassCancelRequest",
                    "fix.OrderMassCancelReport",
                    "fix.OrderMassStatusRequest",
                    "fix.QuoteRequest",
                    "fix.Quote",
                    "fix.QuoteCancel",
                    "fix.QuoteStatusRequest",
                    "fix.QuoteStatusReport",
                    "fix.TradeCaptureReportRequest",
                    "fix.TradeCaptureReport",
                    "fix.TradeCaptureReportAck",
                    "fix.PositionReport",
                    "fix.PositionMassCancelRequest",
                    "fix.PositionMassStatusRequest",
                    "fix.ConfigurationRequest",
                    "fix.ConfigurationReport",
                    "fix.MassQuote",
                    "fix.MassQuoteAcknowledgement",
                    "fix.QuoteResponse",
                    "fix.CollateralRequest",
                    "fix.CollateralAssignment",
                    "fix.CollateralResponse",
                    "fix.CollateralReport",
                    "fix.CollateralInquiry",
                    "fix.CollateralInquiryAck",
                ],
                "count": 160,
            },
            "swift_mt": {
                "description": "SWIFT MT (Message Type) format fields",
                "reference": "SWIFT Standards MT User Handbook",
                "fields": [
                    "swift.application_id",
                    "swift.service_id",
                    "swift.logical_terminal",
                    "swift.session_number",
                    "swift.sequence_number",
                    "swift.block1",
                    "swift.block1.application_id",
                    "swift.block1.service_id",
                    "swift.block1.logical_terminal",
                    "swift.block1.session_number",
                    "swift.block1.sequence_number",
                    "swift.block2",
                    "swift.block2.input_output",
                    "swift.block2.message_type",
                    "swift.block2.receiver_address",
                    "swift.block2.proprietary",
                    "swift.block3",
                    "swift.block4",
                    "swift.block4.tag",
                    "swift.block4.field",
                    "swift.block4.value",
                    "swift.block5",
                    "swift.block5.trailer",
                    "swift.block5.checksum",
                    "swift.mt103",
                    "swift.mt103.sender",
                    "swift.mt103.receiver",
                    "swift.mt103.message_type",
                    "swift.mt103.trn",
                    "swift.mt103.value_date",
                    "swift.mt103.currency",
                    "swift.mt103.amount",
                    "swift.mt103.ordering_customer",
                    "swift.mt103.ordering_institution",
                    "swift.mt103.senders_correspondent",
                    "swift.mt103.receivers_correspondent",
                    "swift.mt103.third_reimbursement",
                    "swift.mt103.account_with_institution",
                    "swift.mt103.beneficiary_customer",
                    "swift.mt103.remittance_information",
                    "swift.mt103.details_of_charges",
                    "swift.mt103.sender_to_receiver",
                    "swift.mt103.cover_method",
                    "swift.mt202",
                    "swift.mt202.sender",
                    "swift.mt202.receiver",
                    "swift.mt202.message_type",
                    "swift.mt202.trn",
                    "swift.mt202.related_reference",
                    "swift.mt202.value_date_currency_amount",
                    "swift.mt202.sender_correspondent",
                    "swift.mt202.receiver_correspondent",
                    "swift.mt202.account_with_institution",
                    "swift.mt202.charges",
                    "swift.mt202.sender_to_receiver",
                    "swift.mt202.flag",
                    "swift.mt910",
                    "swift.mt910.sender",
                    "swift.mt910.receiver",
                    "swift.mt910.message_type",
                    "swift.mt910.trn",
                    "swift.mt910.related_reference",
                    "swift.mt910.account_identification",
                    "swift.mt910.type_of_operations",
                    "swift.mt910.related_reference_1",
                    "swift.mt910.value_date_currency",
                    "swift.mt910.available_funds",
                    "swift.mt910.balance",
                    "swift.mt910.available_balance",
                    "swift.mt950",
                    "swift.mt950.sender",
                    "swift.mt950.receiver",
                    "swift.mt950.message_type",
                    "swift.mt950.trn",
                    "swift.mt950.account_identification",
                    "swift.mt950.statement_number",
                    "swift.mt950.sequence_number",
                    "swift.mt950.opening_balance",
                    "swift.mt950.closing_balance",
                    "swift.mt950.available_balance",
                    "swift.mt950.closing_available_balance",
                    "swift.mt950.account_turnover",
                    "swift.mt950.info_to_account_owner",
                    "swift.mt940",
                    "swift.mt940.sender",
                    "swift.mt940.receiver",
                    "swift.mt940.message_type",
                    "swift.mt940.trn",
                    "swift.mt940.account_identification",
                    "swift.mt940.statement_number",
                    "swift.mt940.sequence_number",
                    "swift.mt940.opening_balance",
                    "swift.mt940.opening_balance.date",
                    "swift.mt940.opening_balance.currency",
                    "swift.mt940.opening_balance.type",
                    "swift.mt940.opening_balance.amount",
                    "swift.mt940.closing_balance",
                    "swift.mt940.available_balance",
                    "swift.mt940.transactions",
                    "swift.mt940.transactions.ref",
                    "swift.mt940.transactions.date",
                    "swift.mt940.transactions.entry_date",
                    "swift.mt940.transactions.funds_code",
                    "swift.mt940.transactions.amount",
                    "swift.mt940.transactions.type",
                    "swift.mt940.transactions.bank_reference",
                    "swift.mt940.transactions.availability",
                    "swift.mt940.transactions.party",
                    "swift.mt940.transactions.remittance",
                    "swift.mt940.transactions.details",
                    "swift.mt940.transactions.machine",
                    "swift.mt940.transactions.payer",
                    "swift.mt940.transactions.payee",
                ],
                "count": 142,
            },
            "ofx_format": {
                "description": "OFX (Open Financial eXchange) format fields",
                "reference": "OFX 2.2 Specification",
                "fields": [
                    "ofx.version",
                    "ofx.signon_msgreg",
                    "ofx.signon",
                    "ofx.signon.username",
                    "ofx.signon.userpass",
                    "ofx.signon.fid",
                    "ofx.signon.fintype",
                    "ofx.signon.oid",
                    "ofx.signon.sesscookie",
                    "ofx.signon.appid",
                    "ofx.signon.appver",
                    "ofx.signon.language",
                    "ofx.signon.country",
                    "ofx.signon.assoc_type",
                    "ofx.signon.svfpid",
                    "ofx.signon.mfa",
                    "ofx.bank_msgreg",
                    "ofx.stmttrnrs",
                    "ofx.stmttrnrs.trnuid",
                    "ofx.stmttrnrs.status",
                    "ofx.stmttrnrs.status.code",
                    "ofx.stmttrnrs.status.severity",
                    "ofx.stmttrnrs.status.message",
                    "ofx.stmttrnrs.org",
                    "ofx.stmttrnrs.dtacctup",
                    "ofx.bankacctfrom",
                    "ofx.bankacctfrom.bankid",
                    "ofx.bankacctfrom.acctid",
                    "ofx.bankacctfrom.accttype",
                    "ofx.bankacctfrom.name",
                    "ofx.stmttrnrs.stmttrnrq",
                    "ofx.stmttrnrq.dtstart",
                    "ofx.stmttrnrq.dtend",
                    "ofx.stmttrnrq.incstmt",
                    "ofx.stmttrnrq.acctinfo",
                    "ofx.stmttrnrq.ledgerbal",
                    "ofx.stmttrnrq.availbal",
                    "ofx.stmttrns",
                    "ofx.stmttrns.dtstart",
                    "ofx.stmttrns.dtend",
                    "ofx.stmttrns.trntype",
                    "ofx.stmttrns.trnid",
                    "ofx.stmttrns.dtposted",
                    "ofx.stmttrns.dtuser",
                    "ofx.stmttrns.trnamt",
                    "ofx.stmttrns.feeamt",
                    "ofx.stmttrns.interest",
                    "ofx.stmttrns.correctfi",
                    "ofx.stmttrns.correctaction",
                    "ofx.stmttrns.rev dtposted",
                    "ofx.stmttrns.rev trnamt",
                    "ofx.stmttrns.rev feeamt",
                    "ofx.stmttrns.rev interest",
                    "ofx.stmttrns.rev correctfi",
                    "ofx.stmttrns.name",
                    "ofx.stmttrns.memo",
                    "ofx.stmttrns.payeeid",
                    "ofx.stmttrns.payee",
                    "ofx.stmttrns.payee.routingnum",
                    "ofx.stmttrns.payee.accountid",
                    "ofx.stmttrns.payee.name",
                    "ofx.stmttrns.payee.addr1",
                    "ofx.stmttrns.payee.addr2",
                    "ofx.stmttrns.payee.city",
                    "ofx.stmttrns.payee.state",
                    "ofx.stmttrns.payee.postalcode",
                    "ofx.stmttrns.payee.country",
                    "ofx.stmttrns.checknum",
                    "ofx.stmttrns.sic",
                    "ofx.stmttrns.proccenter",
                    "ofx.stmttrns.reversal",
                    "ofx.stmttrns.superseded",
                    "ofx.ledgerbal",
                    "ofx.ledgerbal.balamt",
                    "ofx.ledgerbal.dtasof",
                    "ofx.availbal",
                    "ofx.availbal.balamt",
                    "ofx.availbal.dtasof",
                    "ofx.invstmt_msgreg",
                    "ofx.invstmtrs",
                    "ofx.invstmtrs.trnuid",
                    "ofx.invstmtrs.status",
                    "ofx.invstmtrs.org",
                    "ofx.invstmtrs.dtacctup",
                    "ofx.invacctfrom",
                    "ofx.invacctfrom.brokerid",
                    "ofx.invacctfrom.acctid",
                    "ofx.invstmtrq",
                    "ofx.invstmtrq.dtstart",
                    "ofx.invstmtrq.dtend",
                    "ofx.invstmtrq.incstock",
                    "ofx.invstmtrq.invmngrsec",
                    "ofx.invstmtrq.reiatr",
                    "ofx.invstmtrq.incomings",
                    "ofx.invstmtrq.balance",
                    "ofx.invstmtrs.invtran",
                    "ofx.invstmtrs.invtran.trntype",
                    "ofx.invstmtrs.invtran.dtposted",
                    "ofx.invstmtrs.invtran.dttrade",
                    "ofx.invstmtrs.invtran.dtsettle",
                    "ofx.invstmtrs.invtran.reversewith",
                    "ofx.invstmtrs.invtran.fees",
                    "ofx.invstmtrs.invtran.commission",
                    "ofx.invstmtrs.invtran.taxes",
                    "ofx.invstmtrs.invtran.postingpric",
                    "ofx.invstmtrs.invtran.postingunits",
                    "ofx.invstmtrs.invtran.invtype",
                    "ofx.invstmtrs.invtran.secid",
                    "ofx.invstmtrs.invtran.secname",
                    "ofx.invstmtrs.invtran.ticker",
                    "ofx.invstmtrs.invtran.fiid",
                    "ofx.invstmtrs.invtran.qty",
                    "ofx.invstmtrs.invtran.unitprice",
                    "ofx.invstmtrs.invtran.total",
                    "ofx.invstmtrs.invtran.subacct",
                    "ofx.invstmtrs.invtran.transferaction",
                    "ofx.invstmtrs.invtran.transfertype",
                    "ofx.invstmtrs.invtran.waive_fee",
                    "ofx.invstmtrs.invposition",
                    "ofx.invstmtrs.invposition.secid",
                    "ofx.invstmtrs.invposition.held",
                    "ofx.invstmtrs.invposition.qty",
                    "ofx.invstmtrs.invposition.unitprice",
                    "ofx.invstmtrs.invposition.value",
                    "ofx.invstmtrs.invposition.costbasis",
                    "ofx.invstmtrs.invposition.unrealizedgl",
                    "ofx.invstmtrs.invposition.totalestimatedyield",
                    "ofx.invstmtrs.invposition.acctype",
                    "ofx.invstmtrs.invposition.subacct",
                    "ofx.invstmtrs.invposition.sellall",
                    "ofx.invstmtrs.bal",
                    "ofx.invstmtrs.bal.amt",
                    "ofx.invstmtrs.bal.unit",
                    "ofx.invstmtrs.bal.qty",
                    "ofx.invstmtrs.bal.availcash",
                    "ofx.invstmtrs.bal.buypower",
                    "ofx.invstmtrs.bal.marginbalance",
                    "ofx.invstmtrs.bal.shortbalance",
                    "ofx.invstmtrs.bal.balanceid",
                ],
                "count": 142,
            },
            "xbrl_format": {
                "description": "XBRL (eXtensible Business Reporting Language) fields",
                "reference": "XBRL 2.1, IFRS, US GAAP Taxonomy",
                "fields": [
                    "xbrl.xbrl",
                    "xbrl.schemaRef",
                    "xbrl.context",
                    "xbrl.context.id",
                    "xbrl.context.entity",
                    "xbrl.context.entity.identifier",
                    "xbrl.context.entity.scheme",
                    "xbrl.context.period",
                    "xbrl.context.period.instant",
                    "xbrl.context.period.startDate",
                    "xbrl.context.period.endDate",
                    "xbrl.context.segment",
                    "xbrl.context.dimensional",
                    "xbrl.context.dimensional.explicit",
                    "xbrl.context.dimensional.typed",
                    "xbrl.unit",
                    "xbrl.unit.id",
                    "xbrl.unit.measure",
                    "xbrl.unit.multiply",
                    "xbrl.unit.add",
                    "xbrl.fact",
                    "xbrl.fact.namespace",
                    "xbrl.fact.localname",
                    "xbrl.fact.contextRef",
                    "xbrl.fact.unitRef",
                    "xbrl.fact.precision",
                    "xbrl.fact.decimals",
                    "xbrl.fact.value",
                    "xbrl.fact.scale",
                    "xbrl.fact.sign",
                    "xbrl.fact.footnoteRef",
                    "xbrl.footnote",
                    "xbrl.footnote.id",
                    "xbrl.footnote.label",
                    "xbrl.footnote.arcrole",
                    "xbrl.linkbase",
                    "xbrl.linkbaseRef",
                    "xbrl.linkbaseRef.type",
                    "xbrl.linkbaseRef.href",
                    "xbrl.linkbaseRef.role",
                    "xbrl.linkbaseRef.arcrole",
                    "xbrl.link",
                    "xbrl.loc",
                    "xbrl.loc.href",
                    "xbrl.loc.label",
                    "xbrl.loc.title",
                    "xbrl.loc.type",
                    "xbrl.arc",
                    "xbrl.arc.from",
                    "xbrl.arc.to",
                    "xbrl.arc.order",
                    "xbrl.arc.use",
                    "xbrl.arc.preferredLabel",
                    "xbrl.arc.role",
                    "xbrl.arc.arcrole",
                    "xbrl.presentation",
                    "xbrl.calculation",
                    "xbrl.formula",
                    "xbrl.label",
                    "xbrl.label.role",
                    "xbrl.label.lang",
                    "xbrl.label.text",
                    "xbrl.reference",
                    "xbrl.reference.role",
                    "xbrl.reference.href",
                    "xbrl.reference.text",
                    "xbrl.definition",
                    "xbrl.definition.role",
                    "xbrl.definition.arcrole",
                    "xbrl.genLink",
                    "xbrl.resource",
                    "xbrl.resource.id",
                    "xbrl.resource.type",
                    "xbrl.resource.role",
                    "xbrl.resource.title",
                    "xbrl.resource.arcrole",
                    "xbrl.resource.href",
                    "xbrl.resource.text",
                    "xbrl.resource.lang",
                    "xbrl.taxonomy",
                    "xbrl.taxonomy.schema",
                    "xbrl.taxonomy.linkbase",
                    "xbrl.roleType",
                    "xbrl.roleType.id",
                    "xbrl.roleType.definition",
                    "xbrl.roleType.name",
                    "xbrl.roleType.usable",
                    "xbrl.arcroleType",
                    "xbrl.arcroleType.id",
                    "xbrl.arcroleType.definition",
                    "xbrl.arcroleType.name",
                    "xbrl.arcroleType.usable",
                    "xbrl.imports",
                    "xbrl.imports.namespace",
                    "xbrl.imports.schemaLocation",
                    "xbrl.imports.role",
                    "xbrl.imports.arcrole",
                    "xbrl.element",
                    "xbrl.element.id",
                    "xbrl.element.name",
                    "xbrl.element.type",
                    "xbrl.element.substitutionGroup",
                    "xbrl.element.abstract",
                    "xbrl.element.nillable",
                    "xbrl.element.type",
                    "xbrl.element.periodType",
                    "xbrl.element.balance",
                    "xbrl.element.crusable",
                    "xbrl.element.default",
                    "xbrl.element.fixed",
                    "xbrl.element.scale",
                    "xbrl.element.sign",
                    "xbrl.element.dimArch",
                    "xbrl.element.dimMember",
                    "xbrl.element.domain",
                    "xbrl.element.typedMember",
                    "xbrl.element.tuple",
                    "xbrl.element.tuple.order",
                    "xbrl.element.tuple.maxOccurs",
                    "xbrl.element.tuple.minOccurs",
                    "xbrl.element.attrName",
                    "xbrl.element.attrType",
                    "xbrl.element.attrUse",
                    "xbrl.element.attrFixed",
                    "xbrl.element.attrDefault",
                    "xbrl.xsd",
                    "xbrl.xsd.version",
                    "xbrl.xsd.targetNamespace",
                    "xbrl.xsd.xmlns",
                    "xbrl.xsd.elementFormDefault",
                    "xbrl.xsd.attributeFormDefault",
                    "xbrl.xsd.blockDefault",
                    "xbrl.xsd.finalDefault",
                    "xbrl.xsd.schemaLocation",
                ],
                "count": 134,
            },
            "crypto_transaction": {
                "description": "Cryptocurrency transaction and blockchain fields",
                "reference": "Bitcoin, Ethereum, Blockchain protocols",
                "fields": [
                    "crypto.txid",
                    "crypto.version",
                    "crypto.locktime",
                    "crypto.vin",
                    "crypto.vin.prevout",
                    "crypto.vin.prevout.hash",
                    "crypto.vin.prevout.n",
                    "crypto.vin.scriptSig",
                    "crypto.vin.scriptSig.asm",
                    "crypto.vin.scriptSig.hex",
                    "crypto.vin.sequence",
                    "crypto.vin.txinwitness",
                    "crypto.vout",
                    "crypto.vout.value",
                    "crypto.vout.n",
                    "crypto.vout.scriptPubKey",
                    "crypto.vout.scriptPubKey.asm",
                    "crypto.vout.scriptPubKey.hex",
                    "crypto.vout.scriptPubKey.type",
                    "crypto.vout.scriptPubKey.reqSigs",
                    "crypto.vout.scriptPubKey.addresses",
                    "crypto.vout.opReturn",
                    "crypto.vout.opReturn.data",
                    "crypto.vin_count",
                    "crypto.vout_count",
                    "crypto.fee",
                    "crypto.fee_rate",
                    "crypto.size",
                    "crypto.vsize",
                    "crypto.weight",
                    "crypto.confirmations",
                    "crypto.blockhash",
                    "crypto.blockindex",
                    "crypto.blocktime",
                    "crypto.time",
                    "crypto.hex",
                    "crypto.token_transfers",
                    "crypto.token_transfers.from",
                    "crypto.token_transfers.to",
                    "crypto.token_transfers.value",
                    "crypto.token_transfers.contract",
                    "crypto.token_transfers.tx_hash",
                    "crypto.token_transfers.log_index",
                    "crypto.token_transfers.block_number",
                    "crypto.nft_transfers",
                    "crypto.nft_transfers.from",
                    "crypto.nft_transfers.to",
                    "crypto.nft_transfers.token_id",
                    "crypto.nft_transfers.contract",
                    "crypto.nft_transfers.tx_hash",
                    "crypto.token_metadata",
                    "crypto.token_metadata.name",
                    "crypto.token_metadata.symbol",
                    "crypto.token_metadata.decimals",
                    "crypto.token_metadata.total_supply",
                    "crypto.token_metadata.holders",
                    "crypto.token_metadata.transfers",
                    "crypto.token_metadata.price",
                    "crypto.token_metadata.market_cap",
                    "crypto.token_metadata.volume",
                    "crypto.contract_address",
                    "crypto.contract_creator",
                    "crypto.contract_tx_hash",
                    "crypto.contract_deployer",
                    "crypto.contract_gas_used",
                    "crypto.contract_gas_limit",
                    "crypto.contract_init_code",
                    "crypto.contract_runtime",
                    "crypto.contract_evm_version",
                    "crypto.contract_verified",
                    "crypto.contract_source_code",
                    "crypto.contract_abi",
                    "crypto.contract_bytecode",
                    "crypto.contract_storage",
                    "crypto.contract_storage.root",
                    "crypto.contract_storage.slots",
                    "crypto.contract_storage.proof",
                    "crypto.internal_transactions",
                    "crypto.internal_transactions.type",
                    "crypto.internal_transactions.from",
                    "crypto.internal_transactions.to",
                    "crypto.internal_transactions.value",
                    "crypto.internal_transactions.tx_hash",
                    "crypto.internal_transactions.index",
                    "crypto.internal_transactions.input",
                    "crypto.internal_transactions.trace_address",
                    "crypto.internal_transactions.call_type",
                    "crypto.internal_transactions.revert_reason",
                    "crypto.logs",
                    "crypto.logs.address",
                    "crypto.logs.topics",
                    "crypto.logs.data",
                    "crypto.logs.tx_hash",
                    "crypto.logs.log_index",
                    "crypto.logs.block_number",
                    "crypto.logs.block_hash",
                    "crypto.logs.removed",
                    "crypto.state_changes",
                    "crypto.state_changes.block_number",
                    "crypto.state_changes.tx_hash",
                    "crypto.state_changes.address",
                    "crypto.state_changes.balance",
                    "crypto.state_changes.storage",
                    "crypto.state_changes.storage.key",
                    "crypto.state_changes.storage.value",
                    "crypto.state_changes.nonce",
                    "crypto.state_changes.code",
                    "crypto.trace",
                    "crypto.trace.id",
                    "crypto.trace.block_number",
                    "crypto.trace.tx_hash",
                    "crypto.trace.trace_address",
                    "crypto.trace.action",
                    "crypto.trace.result",
                    "crypto.trace.subtraces",
                    "crypto.trace.error",
                    "crypto.trace.type",
                ],
                "count": 124,
            },
        },
        "totals": {
            "categories": 5,
            "total_fields": 702,
        }
    }

    return INVENTORY


def main():
    print("=" * 70)
    print("FINANCIAL FORMAT METADATA FIELD INVENTORY")
    print("=" * 70)
    print()

    inventory = generate_financial_inventory()

    print(f"Generated: {inventory['generated_at']}")
    print(f"Categories: {inventory['totals']['categories']}")
    print(f"Total Fields: {inventory['totals']['total_fields']}")
    print()

    print("FIELD COUNTS BY CATEGORY:")
    print("-" * 50)
    for cat_name, cat_data in sorted(inventory['categories'].items(), key=lambda x: x[1]['count'], reverse=True):
        print(f"  {cat_name:35s}: {cat_data['count']:>4} fields")

    output_dir = Path("dist/financial_inventory")
    output_dir.mkdir(parents=True, exist_ok=True)

    output_file = output_dir / "financial_inventory.json"
    import json
    output_file.write_text(json.dumps(inventory, indent=2, sort_keys=True), encoding="utf-8")
    print()
    print(f"Wrote: {output_file}")

    summary = {
        "generated_at": inventory["generated_at"],
        "description": inventory["description"],
        "categories": {k: {"count": v["count"], "description": v["description"]} for k, v in inventory["categories"].items()},
        "totals": inventory["totals"],
    }

    summary_file = output_dir / "financial_summary.json"
    summary_file.write_text(json.dumps(summary, indent=2, sort_keys=True), encoding="utf-8")
    print(f"Wrote: {summary_file}")


if __name__ == "__main__":
    main()
