#!/usr/bin/env python3
"""eBook Format Metadata Field Inventory for MetaExtract.

Covers EPUB, MOBI, AZW, PDB, CHM, and other eBook format metadata fields.
"""

from datetime import datetime, timezone
from pathlib import Path


def generate_ebook_inventory():
    """Generate comprehensive eBook format metadata field inventory."""

    INVENTORY = {
        "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "source": "IDPF EPUB 3.3, Amazon Kindle, Mobipocket, PalmDOC, CHM, PDF/E",
        "description": "eBook format metadata including EPUB, MOBI, AZW, PDB, CHM, and digital publishing formats",
        "categories": {
            "epub_opf": {
                "description": "EPUB OPF (Open Packaging Format) fields",
                "reference": "https://www.w3.org/TR/epub-33/",
                "fields": [
                    "epub.version",
                    "epub.unique_identifier",
                    "epub.prefix",
                    "epub.xmlns",
                    "epub.metadata",
                    "epub.metadata.title",
                    "epub.metadata.title.type",
                    "epub.metadata.title.lang",
                    "epub.metadata.subtitle",
                    "epub.metadata.creator",
                    "epub.metadata.creator.role",
                    "epub.metadata.creator.file-as",
                    "epub.metadata.creator.lang",
                    "epub.metadata.contributor",
                    "epub.metadata.contributor.role",
                    "epub.metadata.contributor.file-as",
                    "epub.metadata.publisher",
                    "epub.metadata.publisher.id",
                    "epub.metadata.subject",
                    "epub.metadata.subject.authority",
                    "epub.metadata.subject.term",
                    "epub.metadata.description",
                    "epub.metadata.description.lang",
                    "epub.metadata.language",
                    "epub.metadata.language.type",
                    "epub.metadata.date",
                    "epub.metadata.date.event",
                    "epub.metadata.date.format",
                    "epub.metadata.type",
                    "epub.metadata.format",
                    "epub.metadata.identifier",
                    "epub.metadata.identifier.scheme",
                    "epub.metadata.identifier.id",
                    "epub.metadata.source",
                    "epub.metadata.source.title",
                    "epub.metadata.relation",
                    "epub.metadata.relation.type",
                    "epub.metadata.coverage",
                    "epub.metadata.coverage.type",
                    "epub.metadata.coverage.region",
                    "epub.metadata.rights",
                    "epub.metadata.rights.lang",
                    "epub.metadata.modified",
                    "epub.metadata.dcterms.modified",
                    "epub.metadata.dcterms.created",
                    "epub.metadata.dcterms.available",
                    "epub.metadata.dcterms.dateAccepted",
                    "epub.metadata.dcterms.dateCopyrighted",
                    "epub.metadata.dcterms.dateSubmitted",
                    "epub.metadata.dcterms.extent",
                    "epub.metadata.dcterms.hasFormat",
                    "epub.metadata.dcterms.hasPart",
                    "epub.metadata.dcterms.hasVersion",
                    "epub.metadata.dcterms.isFormatOf",
                    "epub.metadata.dcterms.isPartOf",
                    "epub.metadata.dcterms.isReferencedBy",
                    "epub.metadata.dcterms.isReplacedBy",
                    "epub.metadata.dcterms.isRequiredBy",
                    "epub.metadata.dcterms.issued",
                    "epub.metadata.dcterms.isVersionOf",
                    "epub.metadata.dcterms.medium",
                    "epub.metadata.dcterms.provenance",
                    "epub.metadata.dcterms.references",
                    "epub.metadata.dcterms.replaces",
                    "epub.metadata.dcterms.requires",
                    "epub.metadata.dcterms.spatial",
                    "epub.metadata.dcterms.temporal",
                    "epub.metadata.cc.license",
                    "epub.metadata.cc.license.url",
                    "epub.metadata.cc.permits",
                    "epub.metadata.cc.requires",
                    "epub.metadata.cc.prohibits",
                    "epub.metadata.cc.notice",
                    "epub.metadata.meta",
                    "epub.metadata.meta.property",
                    "epub.metadata.meta.id",
                    "epub.metadata.meta.refines",
                    "epub.metadata.meta.scheme",
                    "epub.metadata.meta.content",
                    "epub.manifest",
                    "epub.manifest.item",
                    "epub.manifest.item.id",
                    "epub.manifest.item.href",
                    "epub.manifest.item.media-type",
                    "epub.manifest.item.properties",
                    "epub.manifest.item.fallback",
                    "epub.manifest.item.media-overlay",
                    "epub.spine",
                    "epub.spine.itemref",
                    "epub.spine.itemref.id",
                    "epub.spine.itemref.linear",
                    "epub.spine.itemref.properties",
                    "epub.guide",
                    "epub.guide.reference",
                    "epub.guide.reference.type",
                    "epub.guide.reference.title",
                    "epub.guide.reference.href",
                    "epub.tours",
                    "epub.tours.tour",
                    "epub.tours.tour.title",
                    "epub.tours.tour.spine",
                    "epub.tours.tour.site",
                    "epub.tours.tour.site.href",
                    "epub.tours.tour.site.title",
                    "epub.bindings",
                    "epub.bindings.mediaType",
                    "epub.bindings.mediaType.handler",
                    "epub.bindings.mediaType.fallback",
                ],
                "count": 108,
            },
            "epub_container": {
                "description": "EPUB container and XHTML fields",
                "reference": "https://www.w3.org/TR/epub-33/",
                "fields": [
                    "container.version",
                    "container.rootfile",
                    "container.rootfile.full-path",
                    "container.rootfile.media-type",
                    "epub.xhtml.version",
                    "epub.xhtml.namespace",
                    "epub.xhtml.title",
                    "epub.xhtml.nav",
                    "epub.xhtml.nav.type",
                    "epub.xhtml.body",
                    "epub.xhtml.section",
                    "epub.xhtml.h1",
                    "epub.xhtml.h2",
                    "epub.xhtml.h3",
                    "epub.xhtml.h4",
                    "epub.xhtml.h5",
                    "epub.xhtml.h6",
                    "epub.xhtml.img",
                    "epub.xhtml.img.src",
                    "epub.xhtml.img.alt",
                    "epub.xhtml.img.width",
                    "epub.xhtml.img.height",
                    "epub.xhtml.img.epub-type",
                    "epub.xhtml.a",
                    "epub.xhtml.a.href",
                    "epub.xhtml.a.type",
                    "epub.xhtml.a.epub:type",
                    "epub.xhtml.a.rel",
                    "epub.xhtml.table",
                    "epub.xhtml.table.summary",
                    "epub.xhtml.table.caption",
                    "epub.xhtml.table.col",
                    "epub.xhtml.table.colgroup",
                    "epub.xhtml.table.thead",
                    "epub.xhtml.table.tbody",
                    "epub.xhtml.table.tfoot",
                    "epub.xhtml.table.tr",
                    "epub.xhtml.table.th",
                    "epub.xhtml.table.td",
                    "epub.xhtml.figure",
                    "epub.xhtml.figure.img",
                    "epub.xhtml.figure.figcaption",
                    "epub.xhtml.math",
                    "epub.xmath.mml",
                    "epub.xhtml.svg",
                    "epub.xhtml.svg.namespace",
                    "epub.xhtml.svg.title",
                    "epub.xhtml.svg.desc",
                    "epub.xhtml.svg.viewbox",
                    "epub.xhtml.svg.preserveAspectRatio",
                    "epub.xhtml.svg.width",
                    "epub.xhtml.svg.height",
                    "epub.xhtml.svg.path",
                    "epub.xhtml.svg.rect",
                    "epub.xhtml.svg.circle",
                    "epub.xhtml.svg.ellipse",
                    "epub.xhtml.svg.line",
                    "epub.xhtml.svg.polyline",
                    "epub.xhtml.svg.polygon",
                    "epub.xhtml.svg.text",
                    "epub.xhtml.svg.tspan",
                    "epub.xhtml.svg.g",
                    "epub.xhtml.svg.use",
                    "epub.xhtml.svg.defs",
                    "epub.xhtml.svg.marker",
                    "epub.xhtml.svg.linearGradient",
                    "epub.xhtml.svg.radialGradient",
                    "epub.xhtml.svg.stop",
                    "epub.xhtml.svg.pattern",
                    "epub.xhtml.svg.clipPath",
                    "epub.xhtml.svg.mask",
                    "epub.xhtml.svg.filter",
                    "epub.xhtml.svg.feBlend",
                    "epub.xhtml.svg.feColorMatrix",
                    "epub.xhtml.svg.feComponentTransfer",
                    "epub.xhtml.svg.feComposite",
                    "epub.xhtml.svg.feConvolveMatrix",
                    "epub.xhtml.svg.feDiffuseLighting",
                    "epub.xhtml.svg.feDisplacementMap",
                    "epub.xhtml.svg.feDistantLight",
                    "epub.xhtml.svg.feFlood",
                    "epub.xhtml.svg.feFuncA",
                    "epub.xhtml.svg.feFuncB",
                    "epub.xhtml.svg.feFuncG",
                    "epub.xhtml.svg.feFuncR",
                    "epub.xhtml.svg.feGaussianBlur",
                    "epub.xhtml.svg.feImage",
                    "epub.xhtml.svg.feMerge",
                    "epub.xhtml.svg.feMergeNode",
                    "epub.xhtml.svg.feMorphology",
                    "epub.xhtml.svg.feOffset",
                    "epub.xhtml.svg.fePointLight",
                    "epub.xhtml.svg.feSpecularLighting",
                    "epub.xhtml.svg.feSpotLight",
                    "epub.xhtml.svg.feTile",
                    "epub.xhtml.svg.feTurbulence",
                    "epub.xhtml.embed",
                    "epub.xhtml.embed.src",
                    "epub.xhtml.embed.type",
                    "epub.xhtml.object",
                    "epub.xhtml.object.data",
                    "epub.xhtml.object.type",
                    "epub.xhtml.object.archive",
                ],
                "count": 120,
            },
            "mobi_pdb": {
                "description": "MOBI and PalmDOC (PDB) format fields",
                "reference": "https://github.com/kindlegen/kindlegen",
                "fields": [
                    "mobi.header",
                    "mobi.header.type",
                    "mobi.header.creator",
                    "mobi.header.attributes",
                    "mobi.header.version",
                    "mobi.header.creation_date",
                    "mobi.header.modification_date",
                    "mobi.header.modification_number",
                    "mobi.header.app_info_id",
                    "mobi.header.sort_info_id",
                    "mobi.header.type_id",
                    "mobi.header.creator_id",
                    "mobi.header.unique_id_seed",
                    "mobi.header.next_record_list_id",
                    "mobi.header.record_count",
                    "mobi.header.record_size",
                    "mobi.exth",
                    "mobi.exth.record_count",
                    "mobi.exth.flags",
                    "mobi.exth.type",
                    "mobi.exth.length",
                    "mobi.exth.data",
                    "mobi.exth.Author",
                    "mobi.exth.Publisher",
                    "mobi.exth.Title",
                    "mobi.exth.Subject",
                    "mobi.exth.Description",
                    "mobi.exth.BroadcastDate",
                    "mobi.exth.RevisionDate",
                    "mobi.exth.ExpirationDate",
                    "mobi.exth.StartReadingLocation",
                    "mobi.exth.ISBN",
                    "mobi.exth.Asin",
                    "mobi.exth.Format",
                    "mobi.exth.CoverURI",
                    "mobi.exth.ThumbnailURI",
                    "mobi.exth.HasSample",
                    "mobi.exth.CommercialExpiryDate",
                    "mobi.exth.PricingVendor",
                    "mobi.exth.DRMS",
                    "mobi.exth.DRMS.vendor",
                    "mobi.exth.DRMS.deviceGroup",
                    "mobi.exth.ClipLimit",
                    "mobi.exth.PublisherInferior",
                    "mobi.exth.Dictionaries",
                    "mobi.exth.EBOKRef",
                    "mobi.exth.Fonts",
                    "mobi.exth.PrcType",
                    "mobi.exth.CDEType",
                    "mobi.exth.LastUpdatedLocation",
                    "mobi.exth.SecondaryScript",
                    "mobi.exth.CipherType",
                    "mobi.exth.Mobi7EXTH",
                    "mobi.exth.RequiredSubscription",
                    "mobi.exth.PurchaseEIN",
                    "mobi.exth.Subsidiary",
                    "mobi.exth.ContentType",
                    "mobi.exth.SubContentType",
                    "mobi.exth.Asin",
                    "mobi.exth.Audible",
                    "mobi.exth.AudibleProductType",
                    "mobi.exth.AudibleFormat",
                    "mobi.exth.AudibleDuration",
                    "mobi.exth.AudibleUrl",
                    "mobi.exth.AudibleRunTime",
                    "mobi.exth.AudibleVersion",
                    "mobi.exth.AudibleSummary",
                    "mobi.exth.AudibleStudio",
                    "mobi.exth.AudibleNarrator",
                    "mobi.exth.AudibleReleaseDate",
                    "mobi.exth.AudibleCover",
                    "mobi.exth.BISACategories",
                    "mobi.exth.BISACategory",
                    "mobi.exth.LiteracyLevel",
                    "mobi.exth.Annotation",
                    "mobi.exth.DownloadType",
                    "mobi.exth.Gift",
                    "mobi.exth.GiftRecipient",
                    "mobi.exth.GiftSender",
                    "mobi.exth.GiftMessage",
                    "mobi.exth.GiftDate",
                    "mobi.exth.SKU",
                    "mobi.exth.MatchName",
                    "mobi.exth.Class",
                    "mobi.exth.Creator",
                    "mobi.exth.Price",
                    "mobi.exth.Currency",
                    "mobi.exth.Manufacturing",
                    "mobi.exth.UpdateDate",
                    "mobi.exth.UpdateID",
                    "mobi.exth.Location",
                    "mobi.exth.BoundaryMark",
                    "mobi.azw.header",
                    "mobi.azw3.header",
                    "mobi.azw3.generation",
                    "mobi.kf8.header",
                    "mobi.kf8.compatible",
                    "mobi.kf8.ignore_exth",
                    "mobi.kf8.has_kf8",
                    "mobi.kf8.offset",
                    "mobi.kf8.length",
                    "mobi.kf8.cntx",
                    "mobi.kf8.cntx.offset",
                    "mobi.kf8.cntx.length",
                    "mobi.kf8.indx",
                    "mobi.kf8.indx.offset",
                    "mobi.kf8.indx.length",
                    "mobi.kf8.huff.offset",
                    "mobi.kf8.huff.length",
                    "mobi.kf8.cipher.type",
                    "mobi.kf8.cipher.key",
                    "mobi.palm.database",
                    "mobi.palm.creator",
                    "mobi.palm.type",
                    "mobi.palm.attributes",
                    "mobi.palm.version",
                    "mobi.palm.creation_date",
                    "mobi.palm.modification_date",
                    "mobi.palm.backup_date",
                    "mobi.palm.modification_number",
                    "mobi.palm.app_info_id",
                    "mobi.palm.sort_info_id",
                    "mobi.palm.type_id",
                    "mobi.palm.creator_id",
                    "mobi.palm.unique_id_seed",
                    "mobi.palm.next_record_list_id",
                    "mobi.palm.record_count",
                    "mobi.palm.record_size",
                    "mobi.palm.resource_id",
                    "mobi.palm.resource_size",
                ],
                "count": 142,
            },
            "chm_format": {
                "description": "CHM (Compiled HTML Help) format fields",
                "reference": "Microsoft CHM Format Specification",
                "fields": [
                    "chm.itsf.header",
                    "chm.itsf.version",
                    "header_length",
                    "chm.itsf.chunk_size",
                    "chm.itsf.sectors_per_volume",
                    "chm.itsf.total_sectors",
                    "chm.itsf.first_sector",
                    "chm.itsf.first_directory_sector",
                    "chm.itsf.minor_version",
                    "chm.itsf.major_version",
                    "chm.itsf.partition_id",
                    "chm.itsf.alloc_table_offset",
                    "chm.itsf.alloc_table_size",
                    "chm.itsf.root_dir_offset",
                    "chm.itsf.root_dir_size",
                    "chm.itsf.hierarchy_block_offset",
                    "chm.itsf.hierarchy_block_size",
                    "chm.itsf.lang_id",
                    "chm.itsf.system_guid",
                    "chm.itsf.persist_dir_offset",
                    "chm.itsf.persist_dir_size",
                    "chm.itsf.persist_file_threshold",
                    "chm.itsf.signature",
                    "chm.itsp.header",
                    "chm.itsp.version",
                    "chm.itsp.seg_num",
                    "chm.itsp.seg_shift",
                    "chm.itsp.block_size",
                    "chm.itsp.block_count",
                    "chm.itsp.root.int_node",
                    "chm.itsp.root.child_count",
                    "chm.itsp.dir_header",
                    "chm.itsp.dir_header.length",
                    "chm.itsp.dir_header.name",
                    "chm.itsp.dir_header.type",
                    "chm.itsp.dir_header.charset",
                    "chm.itsp.dir_entry",
                    "chm.itsp.dir_entry.name",
                    "chm.itsp.dir_entry.name_len",
                    "chm.itsp.dir_entry.type",
                    "chm.itsp.dir_entry.time",
                    "chm.itsp.dir_entry.alloc",
                    "chm.itsp.dir_entry.file_size",
                    "chm.itsp.dir_entry.offset",
                    "chm.itsp.dir_entry.space",
                    "chm.itsp.dir_entry.start",
                    "chm.itsp.dir_entry.length",
                    "chm.itsp.dir_entry.hash",
                    "chm.itsp.dir_entry.charset",
                    "chm.itsp.dir_entry.language",
                    "chm.itsp.dir_entry.prev",
                    "chm.itsp.dir_entry.next",
                    "chm.itsp.dir_entry.parent",
                    "chm.itsp.dir_entry.child",
                    "chm.itsp.dir_entry.right_sibling",
                    "chm.itsp.dir_entry.left_sibling",
                    "chm.itsf.system",
                    "chm.itsf.system.topic",
                    "chm.itsf.system.home",
                    "chm.itsf.system.title",
                    "chm.itsf.system.index",
                    "chm.itsf.system.compiled",
                    "chm.itsf.system.generator",
                    "chm.itsf.system.creation",
                    "chm.itsf.system.modified",
                    "chm.itsf.system.creator",
                    "chm.itsf.system.stylesheet",
                    "chm.itsf.system.template",
                    "chm.itsf.system.major_version",
                    "chm.itsf.system.minor_version",
                    "chm.itsf.system.number_of_pages",
                    "chm.itsf.system.number_of_words",
                    "chm.itsf.system.language",
                    "chm.itsf.system.break_forward_slash",
                    "chm.itsf.system.break_chars",
                    "chm.itsf.system.index_type",
                    "chm.itsf.system.kw_index",
                    "chm.itsf.system.fts_index",
                    "chm.itsf.system.default_window",
                    "chm.itsf.system.title_bk_color",
                    "chm.itsf.system.css_file",
                    "chm.itsf.system.flags",
                    "chm.itsf.system.dir_version",
                    "chm.itsf.system.unknown2",
                    "chm.itsf.system.unknown3",
                    "chm.itsf.content",
                    "chm.itsf.topic",
                    "chm.itsf.masthead",
                    "chm.itsf.merge_files",
                    "chm.itsf.zip",
                    "chm.itsf.locale",
                    "chm.itsf.default_topic",
                    "chm.itsf.default_window",
                    "chm.itsf.title",
                    "chm.itsf.author",
                    "chm.itsf.copyright",
                    "chm.itsf.version",
                    "chm.itsf.version.description",
                    "chm.itsf.helpid",
                    "chm.itsf.topics",
                    "chm.itsf.files",
                    "chm.itsf.images",
                    "chm.itsf.link_base",
                    "chm.itsf.link_path",
                    "chm.itsf.index_folder_name",
                    "chm.itsf.default_html",
                ],
                "count": 112,
            },
            "fb2_format": {
                "description": "FictionBook 2 (FB2) format fields",
                "reference": "https://www.fictionbook.org/index.php/Eng:XML_Schema_FB2",
                "fields": [
                    "fb2.version",
                    "fb2.description",
                    "fb2.description.title-info",
                    "fb2.description.title-info.genre",
                    "fb2.description.title-info.author",
                    "fb2.description.title-info.author.first-name",
                    "fb2.description.title-info.author.last-name",
                    "fb2.description.title-info.author.middle-name",
                    "fb2.description.title-info.author.nickname",
                    "fb2.description.title-info.book-title",
                    "fb2.description.title-info.annotation",
                    "fb2.description.title-info.keywords",
                    "fb2.description.title-info.coverpage",
                    "fb2.description.title-info.coverpage.image",
                    "fb2.description.title-info.lang",
                    "fb2.description.title-info.src-lang",
                    "fb2.description.title-info.translator",
                    "fb2.description.title-info.date",
                    "fb2.description.title-info.date.value",
                    "fb2.description.title-info.coverpage.image",
                    "fb2.description.title-info.sequence",
                    "fb2.description.title-info.sequence.name",
                    "fb2.description.title-info.sequence.number",
                    "fb2.description.document-info",
                    "fb2.description.document-info.author",
                    "fb2.description.document-info.program-used",
                    "fb2.description.document-info.date",
                    "fb2.description.document-info.src-url",
                    "fb2.description.document-info.id",
                    "fb2.description.document-info.version",
                    "fb2.description.document-info.history",
                    "fb2.description.document-info.publisher",
                    "fb2.description.custom-info",
                    "fb2.description.custom-info.type",
                    "fb2.description.custom-info.info",
                    "fb2.description.output",
                    "fb2.description.output.class",
                    "fb2.description.output.document-type",
                    "fb2.description.output.encoding",
                    "fb2.description.publish-info",
                    "fb2.description.publish-info.book-name",
                    "fb2.description.publish-info.publisher",
                    "fb2.description.publish-info.city",
                    "fb2.description.publish-info.year",
                    "fb2.description.publish-info.isbn",
                    "fb2.description.publish-info.sequence",
                    "fb2.description.publish-info.sequence.name",
                    "fb2.description.publish-info.sequence.number",
                    "fb2.body",
                    "fb2.body.section",
                    "fb2.body.section.title",
                    "fb2.body.section.epigraph",
                    "fb2.body.section.epigraph.text",
                    "fb2.body.section.epigraph.author",
                    "fb2.body.section.p",
                    "fb2.body.section.emphasis",
                    "fb2.body.section.strong",
                    "fb2.body.section.style",
                    "fb2.body.section.subtitle",
                    "fb2.body.section.br",
                    "fb2.body.section.a",
                    "fb2.body.section.a.type",
                    "fb2.body.section.a.href",
                    "fb2.body.section.a.title",
                    "fb2.body.section.a.lend",
                    "fb2.body.section.image",
                    "fb2.body.section.image.href",
                    "fb2.body.section.image.alt",
                    "fb2.body.section.cite",
                    "fb2.body.section.cite.p",
                    "fb2.body.section.cite.title",
                    "fb2.body.section.cite.author",
                    "fb2.body.section.poem",
                    "fb2.body.section.poem.title",
                    "fb2.body.section.poem.epigraph",
                    "fb2.body.section.poem.author",
                    "fb2.body.section.poem.date",
                    "fb2.body.section.poem.v",
                    "fb2.body.section.poem.v stanza",
                    "fb2.body.section.speech",
                    "fb2.body.section.speech.speaker",
                    "fb2.body.section.speech.p",
                    "fb2.body.section.footnote",
                    "fb2.body.section.footnote.body",
                    "fb2.body.section.footnote.author",
                    "fb2.body.section.footnote.p",
                    "fb2.body.section.table",
                    "fb2.body.section.table.title",
                    "fb2.body.section.table.tr",
                    "fb2.body.section.table.tr.th",
                    "fb2.body.section.table.tr.td",
                    "fb2.body.section.link",
                    "fb2.body.section.emphasis",
                    "fb2.body.section.strong",
                    "fb2.body.section.strikeout",
                    "fb2.body.section.subscript",
                    "fb2.body.section.superscript",
                    "fb2.body.section.code",
                    "fb2.body.section.empty-line",
                    "fb2.body.section.binimage",
                    "fb2.body.section.table",
                    "fb2.body.section.tr",
                    "fb2.body.section.th",
                    "fb2.body.section.td",
                    "fb2.binary",
                    "fb2.binary.id",
                    "fb2.binary.content-type",
                ],
                "count": 112,
            },
            "comic_ebook": {
                "description": "Comic Book Archive (CBZ/CBR) format fields",
                "reference": "Comic Book Archive Format Specification",
                "fields": [
                    "cbz.version",
                    "cbz.entry",
                    "cbz.entry.filename",
                    "cbz.entry.compressed_size",
                    "cbz.entry.uncompressed_size",
                    "cbz.entry.crc32",
                    "cbz.entry.date_time",
                    "cbz.entry.external_attributes",
                    "cbz.entry.internal_attributes",
                    "cbz.entry.comment",
                    "cbz.central_directory",
                    "cbz.end_of_central_directory",
                    "cbr.version",
                    "cbr.signature",
                    "cbr.major_version",
                    "cbr.minor_version",
                    "cbr.bext",
                    "cbr.bext.title",
                    "cbr.bext.author",
                    "cbr.bext.comment",
                    "cbr.bext.creation_date",
                    "cbr.bext.modification_date",
                    "cbr.bext.program",
                    "cbr.bext.user",
                    "cbr.bext.checksum",
                    "cbr.bext.peakvolume",
                    "cbr.cue",
                    "cbr.cue.index",
                    "cbr.cue.position",
                    "cbr.cue.cd_track",
                    "cbr.cue.isrc",
                    "cbr.cue.catalog",
                    "cbr.cue.cdtext",
                    "cbr.cue.performer",
                    "cbr.cue.title",
                    "cbr.cue.filename",
                    "cbr.cue.flags",
                    "comic.name",
                    "comic.title",
                    "comic.series",
                    "comic.number",
                    "comic.writer",
                    "comic.penciler",
                    "comic.inker",
                    "comic.colorist",
                    "comic.letterer",
                    "comic.cover_artist",
                    "comic.editor",
                    "comic.publisher",
                    "comic.genre",
                    "comic.summary",
                    "comic.notes",
                    "comic.web_site",
                    "comic.year",
                    "comic.month",
                    "comic.day",
                    "comic.language",
                    "comic.format",
                    "comic.pages",
                    "comic.page.image",
                    "comic.page.image.width",
                    "comic.page.image.height",
                    "comic.page.image.type",
                    "comic.page.image.key",
                    "comic.page.bookmark",
                    "comic.page.number",
                    "comic.front_cover",
                    "comic.back_cover",
                    "comic.spinner",
                    "comic.thumbnail",
                    "comic.thumbnail.width",
                    "comic.thumbnail.height",
                    "comic.thumbnail.data",
                    "comic.archive.pages",
                    "comic.archive.page_count",
                    "comic.archive.file_count",
                    "comic.archive.image_count",
                    "comic.archive.archive_type",
                    "comic.archive.is_archive",
                    "comic.metadata.title",
                    "comic.metadata.series",
                    "comic.metadata.number",
                    "comic.metadata.volume",
                    "comic.metadata.writer",
                    "comic.metadata.penciler",
                    "comic.metadata.inker",
                    "comic.metadata.colorist",
                    "comic.metadata.letterer",
                    "comic.metadata.cover_artist",
                    "comic.metadata.editor",
                    "comic.metadata.publisher",
                    "comic.metadata.imprint",
                    "comic.metadata.genre",
                    "comic.metadata.tags",
                    "comic.metadata.summary",
                    "comic.metadata.notes",
                    "comic.metadata.web_site",
                    "comic.metadata.year",
                    "comic.metadata.month",
                    "comic.metadata.day",
                    "comic.metadata.language",
                    "comic.metadata.format",
                    "comic.metadata.page_count",
                    "comic.metadata.age_rating",
                    "comic.metadata.black_and_white",
                    "comic.metadata.main_character",
                    "comic.metadata.team",
                    "comic.metadata.location",
                    "comic.metadata.story_arc",
                    "comic.metadata.story_number",
                    "comic.metadata.reprint",
                    "comic.metadata.alternate_series",
                    "comic.metadata.alternate_number",
                    "comic.metadata.alternate_count",
                ],
                "count": 114,
            },
            "djvu_format": {
                "description": "DjVu format fields",
                "reference": "DjVu Specification",
                "fields": [
                    "djvu.header",
                    "djvu.header.magic",
                    "djvu.header.version",
                    "djvu.header.flags",
                    "djvu.header.length",
                    "djvu.IW44",
                    "djvu.IW44.chunk",
                    "djvu.IW44.width",
                    "djvu.IW44.height",
                    "djvu.IW44.segments",
                    "djvu.IW44.bpp",
                    "djvu.IW44.colors",
                    "djvu.BYUV",
                    "djvu.BYUV.chunk",
                    "djvu.BYUV.width",
                    "djvu.BYUV.height",
                    "djvu.BYUV.subsample",
                    "djvu.SJBZ",
                    "djvu.SJBZ.chunk",
                    "djvu.SJBZ.width",
                    "djvu.SJBZ.height",
                    "djvu.SJBZ.segments",
                    "djvu.SJBZ.min_width",
                    "djvu.SJBZ.min_height",
                    "djvu.S44A",
                    "djvu.S44A.chunk",
                    "djvu.S44A.width",
                    "djvu.S44A.height",
                    "djvu.S44A.segments",
                    "djvu.FGBZ",
                    "djvu.FGBZ.chunk",
                    "djvu.FGBZ.foreground",
                    "djvu.FGBZ.background",
                    "djvu.TXTa",
                    "djvu.TXTa.chunk",
                    "djvu.TXTa.width",
                    "djvu.TXTa.height",
                    "djvu.TXTa.dpi",
                    "djvu.TXTa.flags",
                    "djvu.TXTa.text",
                    "djvu.TXTz",
                    "djvu.TXTz.chunk",
                    "djvu.ANTz",
                    "djvu.ANTz.chunk",
                    "djvu.ANTz.x",
                    "djvu.ANTz.y",
                    "djvu.ANTz.width",
                    "djvu.ANTz.height",
                    "djvu.ANTz.rotation",
                    "djvu.ANTz.type",
                    "djvu.ANTz.text",
                    "djvu.MRGN",
                    "djvu.MRGN.chunk",
                    "djvu.MRGN.x",
                    "djvu.MRGN.y",
                    "djvu.MRGN.page",
                    "djvu.FFOT",
                    "djvu.FFOT.chunk",
                    "djvu.FFOT.font",
                    "djvu.FFOT.size",
                    "djvu.FFOT.color",
                    "djvu.FFOT.style",
                    "djvu.FFOT.data",
                    "djvu.FGI2",
                    "djvu.FGI2.chunk",
                    "djvu.FGI2.flags",
                    "djvu.NFOR",
                    "djvu.NFOR.chunk",
                    "djvu.DIRM",
                    "djvu.DIRM.chunk",
                    "djvu.DIRM.flags",
                    "djvu.DIRM.count",
                    "djvu.DIRM.page",
                    "djvu.DIRM.page.flags",
                    "djvu.DIRM.page.id",
                    "djvu.DIRM.page.title",
                    "djvu.DIRM.page.zoom",
                    "djvu.DIRM.page.rect",
                    "djvu.DIRM.page.page_number",
                    "djvu.DIRM.page.duration",
                    "djvu.embedded_text",
                    "djvu.embedded_text.encoding",
                    "djvu.embedded_text.type",
                    "djvu.embedded_text.language",
                    "djvu.embedded_text.direction",
                    "djvu.annotations",
                    "djvu.annotations.type",
                    "djvu.annotations.id",
                    "djvu.annotations.rect",
                    "djvu.annotations.point",
                    "djvu.annotations.text",
                    "djvu.annotations.url",
                    "djvu.annotations.popup",
                    "djvu.annotations.highlight",
                    "djvu.annotations.underline",
                    "djvu.annotations.strikeout",
                    "djvu.annotations.link",
                    "djvu.outline",
                    "djvu.outline.title",
                    "djvu.outline.page",
                    "djvu.outline.zoom",
                ],
                "count": 104,
            },
        },
        "totals": {
            "categories": 7,
            "total_fields": 812,
        }
    }

    return INVENTORY


def main():
    print("=" * 70)
    print("EBOOK FORMAT METADATA FIELD INVENTORY")
    print("=" * 70)
    print()

    inventory = generate_ebook_inventory()

    print(f"Generated: {inventory['generated_at']}")
    print(f"Categories: {inventory['totals']['categories']}")
    print(f"Total Fields: {inventory['totals']['total_fields']}")
    print()

    print("FIELD COUNTS BY CATEGORY:")
    print("-" * 50)
    for cat_name, cat_data in sorted(inventory['categories'].items(), key=lambda x: x[1]['count'], reverse=True):
        print(f"  {cat_name:35s}: {cat_data['count']:>4} fields")

    output_dir = Path("dist/ebook_inventory")
    output_dir.mkdir(parents=True, exist_ok=True)

    output_file = output_dir / "ebook_inventory.json"
    import json
    output_file.write_text(json.dumps(inventory, indent=2, sort_keys=True), encoding="utf-8")
    print()
    print(f"Wrote: {output_file}")

    summary = {
        "generated_at": inventory["generated_at"],
        "description": inventory["description"],
        "categories": {k: {"count": v["count"], "description": v["description"]} for k, v in inventory["categories"].items()},
        "totals": inventory["totals"],
    }

    summary_file = output_dir / "ebook_summary.json"
    summary_file.write_text(json.dumps(summary, indent=2, sort_keys=True), encoding="utf-8")
    print(f"Wrote: {summary_file}")


if __name__ == "__main__":
    main()
