#!/usr/bin/env python3
"""Quantum Computing Metadata Field Inventory for MetaExtract.

Covers qubit types, quantum gates, circuits, calibration, algorithms, control systems, and error correction.
"""

from datetime import datetime, timezone
import json
from pathlib import Path


def generate_quantum_inventory():
    """Generate comprehensive quantum computing metadata field inventory."""

    INVENTORY = {
        "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "source": "IBM Quantum, Google Quantum AI, Rigetti, IonQ, Honeywell, AWS Braket specifications",
        "description": "Quantum computing metadata including qubit types, gates, circuits, calibration, algorithms, control systems, and error correction",
        "categories": {
            "qubit_superconducting": {
                "description": "Superconducting qubit parameters and characteristics",
                "reference": "IBM Quantum, Google Quantum AI, Rigetti specifications",
                "fields": [
                    "qubit.superconducting.frequency",
                    "qubit.superconducting.frequency_coupling",
                    "qubit.superconducting.frequency_transition",
                    "qubit.superconducting.anharmonicity",
                    "qubit.superconducting.t1",
                    "qubit.superconducting.t2",
                    "qubit.superconducting.t2_echo",
                    "qubit.superconducting.t2_ramsey",
                    "qubit.superconducting.readout_fidelity",
                    "qubit.superconducting.readout_error",
                    "qubit.superconducting.readout_assign_prob",
                    "qubit.superconducting.readout_confusion_matrix",
                    "qubit.superconducting.gate_fidelity_single",
                    "qubit.superconducting.gate_error_single",
                    "qubit.superconducting.gate_length_single",
                    "qubit.superconducting.gate_dephasing_rate",
                    "qubit.superconducting.qubit_qubit_coupling",
                    "qubit.superconducting.coupling_strength",
                    "qubit.superconducting.crosstalk",
                    "qubit.superconducting.leakage_rate",
                    "qubit.superconducting.leakage_population",
                    "qubit.superconducting.dispersive_shift",
                    "qubit.superconducting.quantum_efficiency",
                    "qubit.superconducting.thermal_population",
                    "qubit.superconducting.excitation_probability",
                    "qubit.superconducting.population_decay_rate",
                    "qubit.superconducting.dephasing_rate",
                    "qubit.superconducting.purity",
                    "qubit.superconducting.quantum_volume",
                    "qubit.superconducting.coherence_time",
                    "qubit.superconducting.energy_relaxation_time",
                    "qubit.superconducting.dephasing_time",
                    "qubit.superconducting.higher_level_population",
                    "qubit.superconducting.dressed_frequency",
                    "qubit.superconducting.bare_frequency",
                    "qubit.superconducting.flux_sensitivity",
                    "qubit.superconducting.flux_offset",
                    "qubit.superconducting.dc_flux_range",
                    "qubit.superconducting.yield_point",
                    "qubit.superconducting.josephson_energy",
                    "qubit.superconducting.charging_energy",
                    "qubit.superconducting.capacitance",
                    "qubit.superconducting.inductance",
                    "qubit.superconducting.critical_current",
                    "qubit.superconducting.qubit_temperature",
                    "qubit.superconducting.mixing_time",
                    "qubit.superconducting.quasiparticle_density",
                ],
                "count": 45,
            },
            "qubit_trapped_ion": {
                "description": "Trapped ion qubit parameters and characteristics",
                "reference": "IonQ, Honeywell, AQT specifications",
                "fields": [
                    "qubit.trapped_ion.ion_species",
                    "qubit.trapped_ion.ion_mass",
                    "qubit.trapped_ion.ion_charge",
                    "qubit.trapped_ion.nuclear_spin",
                    "qubit.trapped_ion.ground_state",
                    "qubit.trapped_ion.metastable_state",
                    "qubit.trapped_ion.clock_transition_frequency",
                    "qubit.trapped_ion.micromotion_frequency",
                    "qubit.trapped_ion.micromotion_amplitude",
                    "qubit.trapped_ion.electric_quadrupole_moment",
                    "qubit.trapped_ion.laser_wavelength",
                    "qubit.trapped_ion.laser_frequency",
                    "qubit.trapped_ion.laser_power",
                    "qubit.trapped_ion.rabi_frequency",
                    "qubit.trapped_ion.rabi_decay_rate",
                    "qubit.trapped_ion.dephasing_rate",
                    "qubit.trapped_ion.coherence_time",
                    "qubit.trapped_ion.t1",
                    "qubit.trapped_ion.t2",
                    "qubit.trapped_ion.shelving_fidelity",
                    "qubit.trapped_ion.state_detection_fidelity",
                    "qubit.trapped_ion.readout_error",
                    "qubit.trapped_ion.single_qubit_gate_fidelity",
                    "qubit.trapped_ion.single_qubit_gate_time",
                    "qubit.trapped_ion.two_qubit_gate_fidelity",
                    "qubit.trapped_ion.two_qubit_gate_time",
                    "qubit.trapped_ion.motional_mode_frequency",
                    "qubit.trapped_ion.motional_mode_count",
                    "qubit.trapped_ion.axial_frequency",
                    "qubit.trapped_ion.radial_frequency",
                    "qubit.trapped_ion.secular_frequency",
                    "qubit.trapped_ion.detrapping_rate",
                    "qubit.trapped_ion.ion_chain_stability",
                    "qubit.trapped_ion.ion_temperature",
                    "qubit.trapped_ion.doppler_cooling_limit",
                    "qubit.trapped_ion.sideband_cooling_depth",
                    "qubit.trapped_ion.heat_rate",
                    "qubit.trapped_ion.rayleigh_scattering_rate",
                    "qubit.trapped_ion.ac_stark_shift",
                    "qubit.trapped_ion.dc_stark_shift",
                    "qubit.trapped_ion.photoionization_rate",
                    "qubit.trapped_ion.reionization_efficiency",
                    "qubit.trapped_ion.trap_depth",
                    "qubit.trapped_ion.trap_frequency",
                    "qubit.trapped_ion.electric_field_noise",
                    "qubit.trapped_ion.magnetic_field_noise",
                    "qubit.trapped_ion.ion_position_error",
                ],
                "count": 48,
            },
            "qubit_photonic": {
                "description": "Photonic qubit parameters and characteristics",
                "reference": "Xanadu, PsiQuantum, Amazon Braket specifications",
                "fields": [
                    "qubit.photonic.encoding_type",
                    "qubit.photonic.polarization",
                    "qubit.photonic.path_encoding",
                    "qubit.photonic.time_bin_encoding",
                    "qubit.photonic.frequency_bin_encoding",
                    "qubit.photonic.orbital_angular_momentum",
                    "qubit.photonic.wavelength",
                    "qubit.photonic.frequency",
                    "qubit.photonic.photon_number",
                    "qubit.photonic.heralding_efficiency",
                    "qubit.photonic.single_photon_source_type",
                    "qubit.photonic.spandar_source_efficiency",
                    "qubit.photonic.spandar_source_purity",
                    "qubit.photonic.spandar_source_indistinguishability",
                    "qubit.photonic.detector_efficiency",
                    "qubit.photonic.detector_timing_resolution",
                    "qubit.photonic.detector_dark_count_rate",
                    "qubit.photonic.detector_jitter",
                    "qubit.photonic.detector_dead_time",
                    "qubit.photonic.detector_type",
                    "qubit.photonic.interferometer_visibility",
                    "qubit.photonic.interferometer_stability",
                    "qubit.photonic.loss_rate",
                    "qubit.photonic.transmission_loss",
                    "qubit.photonic.scattering_rate",
                    "qubit.photonic.decoherence_time",
                    "qubit.photonic.dephasing_time",
                    "qubit.photonic.t1",
                    "qubit.photonic.t2",
                    "qubit.photonic.fiber_coupling_efficiency",
                    "qubit.photonic.free_space_coupling_efficiency",
                    "qubit.photonic.optical_depth",
                    "qubit.photonic.nonlinear_phase_shift",
                    "qubit.photonic.kerr_coefficient",
                    "qubit.photonic.cross_phase_modulation",
                    "qubit.photonic.raman_gain",
                    "qubit.photonic.four_wave_mixing_efficiency",
                    "qubit.photonic.spectral_brightness",
                    "qubit.photonic.temporal_width",
                    "qubit.photonic.spatial_mode_quality",
                    "qubit.photonic.beam_quality_factor",
                    "qubit.photonic.extinction_ratio",
                    "qubit.photonic.on_chip_loss",
                    "qubit.photonic.waveguide_length",
                    "qubit.photonic.bending_radius",
                    "qubit.photonic.thermal_tuning_range",
                    "qubit.photonic.electro_optic_tuning_speed",
                ],
                "count": 48,
            },
            "qubit_topological": {
                "description": "Topological qubit parameters and characteristics",
                "reference": "Microsoft Quantum, research specifications",
                "fields": [
                    "qubit.topological.particle_type",
                    "qubit.topological.island_size",
                    "qubit.topological.island_shape",
                    "qubit.topological.majorana_zero_mode",
                    "qubit.topological.branch_overlap",
                    "qubit.topological.topological_gap",
                    "qubit.topological.charging_energy",
                    "qubit.topological.induced_gap",
                    "qubit.topological.tunnel_coupling",
                    "qubit.topological.tunnel_rate",
                    "qubit.topological.coherence_time",
                    "qubit.topological.t1",
                    "qubit.topological.t2",
                    "qubit.topological.gate_fidelity",
                    "qubit.topological.readout_fidelity",
                    "qubit.topological.readout_error",
                    "qubit.topological.initialization_fidelity",
                    "qubit.topological.topological_protection_level",
                    "qubit.topological.error_suppression_factor",
                    "qubit.topological.non_abelian_statistics",
                    "qubit.topological.braid_operation_time",
                    "qubit.topological.fusion_success_probability",
                    "qubit.topological.energy_splitting",
                    "qubit.topological.coupling_strength",
                    "qubit.topological.crosstalk",
                    "qubit.topological.host_material",
                    "qubit.topological.superconductor_type",
                    "qubit.topological.semiconductor_material",
                    "qubit.topological.wire_width",
                    "qubit.topological.wire_length",
                    "qubit.topological.barrier_width",
                    "qubit.topological.gate_voltage",
                    "qubit.topological.magnetic_field",
                    "qubit.topological.temperature",
                    "qubit.topological.epitaxial_quality",
                    "qubit.topological interface_quality",
                    "qubit.topological.majorana_detection_fidelity",
                    "qubit.topological.topological_qubit_encoding",
                    "qubit.topological.logical_qubit_overhead",
                ],
                "count": 40,
            },
            "gate_single_qubit": {
                "description": "Single-qubit gate parameters and specifications",
                "reference": "Quantum gate set tomography standards",
                "fields": [
                    "gate.single_qubit.x.rotation_angle",
                    "gate.single_qubit.x.axis",
                    "gate.single_qubit.x.duration",
                    "gate.single_qubit.x.fidelity",
                    "gate.single_qubit.x.error_rate",
                    "gate.single_qubit.y.rotation_angle",
                    "gate.single_qubit.y.axis",
                    "gate.single_qubit.y.duration",
                    "gate.single_qubit.y.fidelity",
                    "gate.single_qubit.y.error_rate",
                    "gate.single_qubit.z.rotation_angle",
                    "gate.single_qubit.z.duration",
                    "gate.single_qubit.z.fidelity",
                    "gate.single_qubit.z.error_rate",
                    "gate.single_qubit.hadamard.rotation_angle",
                    "gate.single_qubit.hadamard.duration",
                    "gate.single_qubit.hadamard.fidelity",
                    "gate.single_qubit.hadamard.error_rate",
                    "gate.single_qubit.phase.rotation_angle",
                    "gate.single_qubit.phase.duration",
                    "gate.single_qubit.phase.fidelity",
                    "gate.single_qubit.phase.error_rate",
                    "gate.single_qubit.t.rotation_angle",
                    "gate.single_qubit.t.duration",
                    "gate.single_qubit.t.fidelity",
                    "gate.single_qubit.t.error_rate",
                    "gate.single_qubit.s.rotation_angle",
                    "gate.single_qubit.s.duration",
                    "gate.single_qubit.s.fidelity",
                    "gate.single_qubit.s.error_rate",
                    "gate.single_qubit.rx.rotation_angle",
                    "gate.single_qubit.rx.axis",
                    "gate.single_qubit.rx.duration",
                    "gate.single_qubit.rx.fidelity",
                    "gate.single_qubit.rx.error_rate",
                    "gate.single_qubit.ry.rotation_angle",
                    "gate.single_qubit.ry.axis",
                    "gate.single_qubit.ry.duration",
                    "gate.single_qubit.ry.fidelity",
                    "gate.single_qubit.ry.error_rate",
                    "gate.single_qubit.rz.rotation_angle",
                    "gate.single_qubit.rz.axis",
                    "gate.single_qubit.rz.duration",
                    "gate.single_qubit.rz.fidelity",
                    "gate.single_qubit.rz.error_rate",
                    "gate.single_qubit.sqrt_x.duration",
                    "gate.single_qubit.sqrt_x.fidelity",
                    "gate.single_qubit.sqrt_x.error_rate",
                    "gate.single_qubit.sqrt_y.duration",
                    "gate.single_qubit.sqrt_y.fidelity",
                    "gate.single_qubit.sqrt_y.error_rate",
                    "gate.single_qubit.virtual_axis.rotation_axis",
                    "gate.single_qubit.virtual_axis.duration",
                ],
                "count": 50,
            },
            "gate_two_qubit": {
                "description": "Two-qubit gate parameters and specifications",
                "reference": "Cross-entropy benchmarking, XEB standards",
                "fields": [
                    "gate.two_qubit.cnot.control_qubit",
                    "gate.two_qubit.cnot.target_qubit",
                    "gate.two_qubit.cnot.duration",
                    "gate.two_qubit.cnot.fidelity",
                    "gate.two_qubit.cnot.error_rate",
                    "gate.two_qubit.cnot.crosstalk",
                    "gate.two_qubit.cz.duration",
                    "gate.two_qubit.cz.fidelity",
                    "gate.two_qubit.cz.error_rate",
                    "gate.two_qubit.cz.crosstalk",
                    "gate.two_qubit.iswap.duration",
                    "gate.two_qubit.iswap.fidelity",
                    "gate.two_qubit.iswap.error_rate",
                    "gate.two_qubit.iswap.exchange_interaction",
                    "gate.two_qubit.rzz.rotation_angle",
                    "gate.two_qubit.rzz.duration",
                    "gate.two_qubit.rzz.fidelity",
                    "gate.two_qubit.rzz.error_rate",
                    "gate.two_qubit.rxx.rotation_angle",
                    "gate.two_qubit.rxx.duration",
                    "gate.two_qubit.rxx.fidelity",
                    "gate.two_qubit.rxx.error_rate",
                    "gate.two_qubit.ryy.rotation_angle",
                    "gate.two_qubit.ryy.duration",
                    "gate.two_qubit.ryy.fidelity",
                    "gate.two_qubit.ryy.error_rate",
                    "gate.two_qubit.cphase.duration",
                    "gate.two_qubit.cphase.fidelity",
                    "gate.two_qubit.cphase.error_rate",
                    "gate.two_qubit.sqrt_cnot.duration",
                    "gate.two_qubit.sqrt_cnot.fidelity",
                    "gate.two_qubit.sqrt_cnot.error_rate",
                    "gate.two_qubit.xy.duration",
                    "gate.two_qubit.xy.fidelity",
                    "gate.two_qubit.xy.error_rate",
                    "gate.two_qubit.ms.interaction_time",
                    "gate.two_qubit.ms.fidelity",
                    "gate.two_qubit.ms.error_rate",
                    "gate.two_qubit.molmer_sorensen.duration",
                    "gate.two_qubit.molmer_sorensen.fidelity",
                    "gate.two_qubit.molmer_sorensen.error_rate",
                    "gate.two_qubit.cx.duration",
                    "gate.two_qubit.cx.fidelity",
                    "gate.two_qubit.cx.error_rate",
                    "gate.two_qubit.cx.crosstalk",
                    "gate.two_qubit.conditional_phase.duration",
                    "gate.two_qubit.conditional_phase.fidelity",
                    "gate.two_qubit.conditional_phase.error_rate",
                ],
                "count": 42,
            },
            "gate_chinese": {
                "description": "Quantum gate parameters (Chinese/中文门参数)",
                "reference": "Chinese quantum computing specifications",
                "fields": [
                    "gate.门的类型",
                    "gate.单量子比特门",
                    "gate.双量子比特门",
                    "gate.多量子比特门",
                    "gate.哈达玛德门",
                    "gate.相位门",
                    "gate.T门",
                    "gate.S门",
                    "gate.X门",
                    "gate.Y门",
                    "gate.Z门",
                    "gate.CNOT门",
                    "gate.CZ门",
                    "gate.SWAP门",
                    "gate.iSWAP门",
                    "gate.控制相位门",
                    "gate.纠缠门",
                    "gate.幺正门",
                    "gate.旋转门",
                    "gate.泡利门",
                    "gate.门的保真度",
                    "gate.门的错误率",
                    "gate.门的持续时间",
                    "gate.门的振幅",
                    "gate.门的频率",
                    "gate.门的相位",
                    "gate.门的旋转角度",
                    "gate.门的轴",
                    "gate.门序列",
                    "gate.门的编译",
                    "gate.门的优化",
                    "gate.门的时间",
                    "gate.门的延迟",
                    "gate.门的校准",
                    "gate.门的参数",
                    "gate.门的控制",
                    "gate.门的测量",
                    "gate.门的初始化",
                ],
                "count": 38,
            },
            "circuit_parameters": {
                "description": "Quantum circuit parameters and metrics",
                "reference": "Quantum circuit analysis standards",
                "fields": [
                    "circuit.depth",
                    "circuit.width",
                    "circuit.qubit_count",
                    "circuit.gate_count",
                    "circuit.total_gates",
                    "circuit.single_qubit_gate_count",
                    "circuit.two_qubit_gate_count",
                    "circuit.depth_per_layer",
                    "circuit.layer_count",
                    "circuit.circuit_fidelity",
                    "circuit.process_fidelity",
                    "circuit.state_fidelity",
                    "circuit.average_gate_fidelity",
                    "circuit.gate_set_fidelity",
                    "circuit.local_gate_fidelity",
                    "circuit.nonlocal_gate_fidelity",
                    "circuit.circuit_error_rate",
                    "circuit.error_budget",
                    "circuit.noise_model",
                    "circuit.noise_strength",
                    "circuit.decoherence_time",
                    "circuit.gate_error",
                    "circuit.readout_error",
                    "circuit.leakage_error",
                    "circuit.crosstalk_error",
                    "circuit.spam_error",
                    "circuit.total_error_rate",
                    "circuit.parallel_execution",
                    "circuit.sequential_execution",
                    "circuit.circuit_structure",
                    "circuit.topology",
                    "circuit.connectivity",
                    "circuit.coupling_map",
                    "circuit.entanglement_map",
                    "circuit.circuit_operations",
                    "circuit.measurement_operations",
                    "circuit.initialization_operations",
                    "circuit.middleware_operations",
                    "circuit.quantum_volume",
                    "circuit.quantum_supremacy_circuit",
                    "circuit.random_circuit_sampling",
                    "circuit.sycamore_circuit",
                    "circuit.transpiler_optimization_level",
                    "circuit.transpiler_pass_manager",
                    "circuit.circuit_properties",
                ],
                "count": 45,
            },
            "calibration_t1_t2": {
                "description": "T1 and T2 coherence calibration parameters",
                "reference": "Quantum coherence measurement standards",
                "fields": [
                    "calibration.t1.value",
                    "calibration.t1.unit",
                    "calibration.t1.measurement_time",
                    "calibration.t1.exponential_fit",
                    "calibration.t1.amplitude",
                    "calibration.t1.offset",
                    "calibration.t1.residual",
                    "calibration.t1.uncertainty",
                    "calibration.t1.temperature_dependence",
                    "calibration.t1.flux_dependence",
                    "calibration.t2.value",
                    "calibration.t2.unit",
                    "calibration.t2.measurement_time",
                    "calibration.t2.ramsey_oscillations",
                    "calibration.t2.exponential_fit",
                    "calibration.t2.amplitude",
                    "calibration.t2.offset",
                    "calibration.t2.uncertainty",
                    "calibration.t2.dephasing_rate",
                    "calibration.t2_echo.value",
                    "calibration.t2_echo.unit",
                    "calibration.t2_echo.measurement_time",
                    "calibration.t2_echo.hahn_echo_sequence",
                    "calibration.t2_echo.exponential_fit",
                    "calibration.t2_echo.amplitude",
                    "calibration.t2_echo.uncertainty",
                    "calibration.t2_echo.dephasing_rate",
                    "calibration.t2_ramsey.value",
                    "calibration.t2_ramsey.unit",
                    "calibration.t2_ramsey.measurement_time",
                    "calibration.t2_ramsey.detuning",
                    "calibration.t2_ramsey.oscillation_frequency",
                    "calibration.t2_ramsey.uncertainty",
                    "calibration.coherence_times",
                    "calibration.coherence_averages",
                    "calibration.coherence_std_dev",
                    "calibration.coherence_temperature_sweep",
                    "calibration.coherence_flux_sweep",
                    "calibration.t1_mapping",
                    "calibration.t2_mapping",
                    "calibration.coherence_heatmap",
                ],
                "count": 42,
            },
            "calibration_fidelity": {
                "description": "Gate and readout fidelity calibration parameters",
                "reference": "Randomized benchmarking, GST standards",
                "fields": [
                    "calibration.gate_fidelity.single_qubit",
                    "calibration.gate_fidelity.two_qubit",
                    "calibration.gate_fidelity.average",
                    "calibration.gate_fidelity.local",
                    "calibration.gate_fidelity.nonlocal",
                    "calibration.gate_fidelity.gate_set",
                    "calibration.gate_fidelity.rb_sequences",
                    "calibration.gate_fidelity.rb_depths",
                    "calibration.gate_fidelity.rb_averages",
                    "calibration.gate_fidelity.rb_error",
                    "calibration.gate_fidelity.xeb_fidelity",
                    "calibration.gate_fidelity.xeb_cycles",
                    "calibration.gate_fidelity.gst_fidelity",
                    "calibration.gate_fidelity.gst_sequences",
                    "calibration.readout_fidelity",
                    "calibration.readout.assignment_probability",
                    "calibration.readout.confusion_matrix",
                    "calibration.readout.misclassification",
                    "calibration.readout.shelving_fidelity",
                    "calibration.readout.measurement_error",
                    "calibration.readout.preparation_error",
                    "calibration.leakage.rate",
                    "calibration.leakage.population",
                    "calibration.leakage.gate_induced",
                    "calibration.leakage.measurement_induced",
                    "calibration.leakage.thermal_population",
                    "calibration.leakage.ac_stark_shift",
                    "calibration.leakage.compensation_circuit",
                    "calibration.crosstalk.coefficient",
                    "calibration.crosstalk.spectral_density",
                    "calibration.crosstalk.temporal",
                    "calibration.crosstalk.spatial",
                    "calibration.crosstalk.markovian",
                    "calibration.crosstalk.neural_network_model",
                    "calibration.drag_coefficient",
                    "calibration.amplitude_scaling_factor",
                    "calibration.drag_correction",
                    "calibration.channel_inverse",
                    "calibration.pulse_correction",
                ],
                "count": 40,
            },
            "algorithm_shor": {
                "description": "Shor's algorithm parameters and configurations",
                "reference": "Shor's factoring algorithm specifications",
                "fields": [
                    "algorithm.shor.n",
                    "algorithm.shor.N",
                    "algorithm.shor.factoring_target",
                    "algorithm.shor.modulus",
                    "algorithm.shor.order_finding_circuit",
                    "algorithm.shor.quantum_fourier_transform",
                    "algorithm.shor.controlled_multiplication",
                    "algorithm.shor.controlled_addition",
                    "algorithm.shor.phase_estimation",
                    "algorithm.shor.iterations",
                    "algorithm.shor.shots",
                    "algorithm.shor.success_probability",
                    "algorithm.shor.classical_postprocessing",
                    "algorithm.shor.continued_fraction",
                    "algorithm.shor.gcd_computation",
                    "algorithm.shor.modular_exponentiation",
                    "algorithm.shor.quantum_circuit_depth",
                    "algorithm.shor.quantum_resources",
                    "algorithm.shor.ancilla_qubits",
                    "algorithm.shor.work_qubits",
                    "algorithm.shor.noise_model",
                    "algorithm.shor.error_correction",
                    "algorithm.shor.fault_tolerant",
                    "algorithm.shor.distillation",
                    "algorithm.shor.factored_number",
                    "algorithm.shor.prime_factors",
                    "algorithm.shor.execution_time",
                    "algorithm.shor.comparison_classical",
                    "algorithm.shor.quantum_advantage",
                    "algorithm.shor.resource_estimation",
                ],
                "count": 30,
            },
            "algorithm_grover": {
                "description": "Grover's algorithm parameters and configurations",
                "reference": "Grover's search algorithm specifications",
                "fields": [
                    "algorithm.grover.n_qubits",
                    "algorithm.grover.database_size",
                    "algorithm.grover.search_space",
                    "algorithm.grover.target_state",
                    "algorithm.grover.oracle_type",
                    "algorithm.grover.diffusion_operator",
                    "algorithm.grover.iterations",
                    "algorithm.grover.optimal_iterations",
                    "algorithm.grover.success_probability",
                    "algorithm.grover.amplitude_amplification",
                    "algorithm.grover.grover_operators",
                    "algorithm.grover.oracle_circuit",
                    "algorithm.grover.diffusion_circuit",
                    "algorithm.grover.measurement",
                    "algorithm.grover.shots",
                    "algorithm.grover.amplitude_estimation",
                    "algorithm.grover.quantum_counting",
                    "algorithm.grover.phase_oracle",
                    "algorithm.grover.exact_oracle",
                    "algorithm.grover.approximate_oracle",
                    "algorithm.grover.multi_target",
                    "algorithm.grover.amplitude_amplification",
                    "algorithm.grover.depth_speedup",
                    "algorithm.grover.quadratic_speedup",
                    "algorithm.grover.noise_effect",
                    "algorithm.grover.decoherence_sensitivity",
                    "algorithm.grover.classical_comparison",
                    "algorithm.grover.natural_oracle",
                    "algorithm.grover.structured_search",
                    "algorithm.grover.unstructured_search",
                ],
                "count": 30,
            },
            "algorithm_vqe_qaoa": {
                "description": "VQE and QAOA algorithm parameters",
                "reference": "Variational quantum algorithms specifications",
                "fields": [
                    "algorithm.vqe.hamiltonian",
                    "algorithm.vqe.observable",
                    "algorithm.vqe.ansatz",
                    "algorithm.vqe.ansatz_type",
                    "algorithm.vqe.para_qubits",
                    "algorithm.vqe.para_depth",
                    "algorithm.vqe.para_layers",
                    "algorithm.vqe.parameters",
                    "algorithm.vqe.parameter_count",
                    "algorithm.vqe.parameter_initialization",
                    "algorithm.vqe.optimizer",
                    "algorithm.vqe.optimizer_type",
                    "algorithm.vqe.optimizer_iterations",
                    "algorithm.vqe.optimizer_learning_rate",
                    "algorithm.vqe.optimizer_convergence",
                    "algorithm.vqe.energy_evaluation",
                    "algorithm.vqe.gradient_estimation",
                    "algorithm.vqe.gradient_type",
                    "algorithm.vqe.shift_rule",
                    "algorithm.vqe.parameter_shift",
                    "algorithm.vqe.measurements",
                    "algorithm.vqe.shots_per_circuit",
                    "algorithm.vqe.grouping",
                    "algorithm.vqe.observable_grouping",
                    "algorithm.vqe.excitation_operators",
                    "algorithm.vqe.fermionic_mapping",
                    "algorithm.vqe.jordan_wigner",
                    "algorithm.vqe.bravyi_kitaev",
                    "algorithm.vqe.parity_mapping",
                    "algorithm.qaoa.p",
                    "algorithm.qaoa.layers",
                    "algorithm.qaoa.gamma",
                    "algorithm.qaoa.beta",
                    "algorithm.qaoa.gamma_history",
                    "algorithm.qaoa.beta_history",
                    "algorithm.qaoa.mixer_hamiltonian",
                    "algorithm.qaoa.problem_hamiltonian",
                    "algorithm.qaoa.energy_landscape",
                    "algorithm.qaoa.maxcut_embedding",
                    "algorithm.qaoa.classical_optimization",
                ],
                "count": 42,
            },
            "pulse_microwave": {
                "description": "Microwave pulse control parameters",
                "reference": "Quantum control and pulse sequencing standards",
                "fields": [
                    "pulse.microwave.frequency",
                    "pulse.microwave.amplitude",
                    "pulse.microwave.phase",
                    "pulse.microwave.duration",
                    "pulse.microwave.start_time",
                    "pulse.microwave.end_time",
                    "pulse.microwave.envelope",
                    "pulse.microwave.envelope_type",
                    "pulse.microwave.gaussian_width",
                    "pulse.microwave.drag_coefficient",
                    "pulse.microwave.cutoff_frequency",
                    "pulse.microwave.bandwidth",
                    "pulse.microwave.sampling_rate",
                    "pulse.microwave.waveform_type",
                    "pulse.microwave.arbitrary_waveform",
                    "pulse.microwave.iq_modulation",
                    "pulse.microwave.i_value",
                    "pulse.microwave.q_value",
                    "pulse.microwave.carrier_frequency",
                    "pulse.microwave.lo_frequency",
                    "pulse.microwave.if_frequency",
                    "pulse.microwave.iq_mixer_correction",
                    "pulse.microwave.iq_skew",
                    "pulse.microwave.iq_imbalance",
                    "pulse.microwave.digital_to_analog_conversion",
                    "pulse.microwave.dac_resolution",
                    "pulse.microwave.dac_range",
                    "pulse.microwave.channel",
                    "pulse.microwave.qubit_channel",
                    "pulse.microwave.readout_channel",
                    "pulse.microwave.flux_channel",
                    "pulse.microwave.repetition_rate",
                    "pulse.microwave.duty_cycle",
                    "pulse.microwave.pulse_sequence",
                    "pulse.microwave.timing_diagram",
                    "pulse.microwave.delay",
                    "pulse.microwave.buffer",
                    "pulse.microwave.synchronization",
                    "pulse.microwave.clock_source",
                    "pulse.microwave.reference_frequency",
                ],
                "count": 40,
            },
            "pulse_laser_optical": {
                "description": "Laser and optical pulse control parameters",
                "reference": "Trapped ion and photonic quantum computing specifications",
                "fields": [
                    "pulse.laser.wavelength",
                    "pulse.laser.frequency",
                    "pulse.laser.linewidth",
                    "pulse.laser.power",
                    "pulse.laser.intensity",
                    "pulse.laser.fluence",
                    "pulse.laser.pulse_duration",
                    "pulse.laser.pulse_energy",
                    "pulse.laser.repetition_rate",
                    "pulse.laser.peak_power",
                    "pulse.laser.average_power",
                    "pulse.laser.beam_diameter",
                    "pulse.laser.beam_quality",
                    "pulse.laser.waist_size",
                    "pulse.laser.rayleigh_range",
                    "pulse.laser.focus_position",
                    "pulse.laser.polarization",
                    "pulse.laser.polarization_purity",
                    "pulse.laser.pointing_stability",
                    "pulse.laser.power_stability",
                    "pulse.laser.frequency_stability",
                    "pulse.laser.amplitude_stability",
                    "pulse.laser.temporal_profile",
                    "pulse.laser.gaussian_beam",
                    "pulse.laser.top_hat_beam",
                    "pulse.laser.acoustic_optical_modulator",
                    "pulse.laser.aom_frequency",
                    "pulse.laser.aom_efficiency",
                    "pulse.laser.electro_optic_modulator",
                    "pulse.laser.eom_voltage",
                    "pulse.laser.eom_bandwidth",
                    "pulse.laser.shutter_speed",
                    "pulse.laser.pulse_picker",
                    "pulse.laser.delay_generator",
                    "pulse.laser.synchronization",
                    "pulse.laser.trigger",
                    "pulse.laser.jitter",
                    "pulse.laser.stark_shift",
                    "pulse.laser.ac_stark_shift",
                    "pulse.laser.dc_stark_shift",
                ],
                "count": 40,
            },
            "error_correction_surface": {
                "description": "Surface code quantum error correction parameters",
                "reference": "Surface code and topological quantum computing specifications",
                "fields": [
                    "error_correction.surface_code.distance",
                    "error_correction.surface_code.layout",
                    "error_correction.surface_code.patch_size",
                    "error_correction.surface_code.physical_qubits",
                    "error_correction.surface_code.logical_qubits",
                    "error_correction.surface_code.code_distance",
                    "error_correction.surface_code.plaquette_stabilizers",
                    "error_correction.surface_code.vertex_stabilizers",
                    "error_correction.surface_code.measurements_per_cycle",
                    "error_correction.surface_code.cycle_time",
                    "error_correction.surface_code.decoder",
                    "error_correction.surface_code.decoder_type",
                    "error_correction.surface_code.minimum_weight_perfect_matching",
                    "error_correction.surface_code.neural_network_decoder",
                    "error_correction.surface_code.UF_decoherence_time",
                    "error_correction.surface_code.logical_error_rate",
                    "error_correction.surface_code.physical_error_rate",
                    "error_correction.surface_code.threshold",
                    "error_correction.surface_code.subrego_threshold",
                    "error_correction.surface_code.overhead",
                    "error_correction.surface_code.fault_tolerance",
                    "error_correction.surface_code.fault_tolerance_threshold",
                    "error_correction.surface_code.error_suppression",
                    "error_correction.surface_code.error_mitigation",
                    "error_correction.surface_code.zz_stabilizers",
                    "error_correction.surface_code.xx_stabilizers",
                    "error_correction.surface_code.boundary_conditions",
                    "error_correction.surface_code.distillation",
                    "error_correction.surface_code.state_distillation",
                    "error_correction.surface_code.gate_distillation",
                    "error_correction.surface_code.distillation_level",
                    "error_correction.surface_code.rotated_code",
                    "error_correction.surface_code.brickwork_code",
                ],
                "count": 34,
            },
            "error_correction_other": {
                "description": "Other quantum error correction codes",
                "reference": "Steane code, color code, repetition code specifications",
                "fields": [
                    "error_correction.steane_code.distance",
                    "error_correction.steane_code.logical_qubits",
                    "error_correction.steane_code.physical_qubits",
                    "error_correction.steane_code.encoded_logical_qubit",
                    "error_correction.steane_code.stabilizers",
                    "error_correction.steane_code.threshold",
                    "error_correction.color_code.distance",
                    "error_correction.color_code.logical_qubits",
                    "error_correction.color_code.physical_qubits",
                    "error_correction.color_code.plaquettes",
                    "error_correction.color_code.threshold",
                    "error_correction.repetition_code.distance",
                    "error_correction.repetition_code.logical_qubits",
                    "error_correction.repetition_code.physical_qubits",
                    "error_correction.repetition_code.round_count",
                    "error_correction.repetition_code.decoder",
                    "error_correction.bacon_shor_code.distance",
                    "error_correction.bacon_shor_code.logical_qubits",
                    "error_correction.bacon_shor_code.physical_qubits",
                    "error_correction.holographic_code",
                    "error_correction.subsystem_code",
                    "error_correction.topological_code",
                    "error_correction.catalytic_code",
                    "error_correction.subsystem_code",
                    "error_correction.fault_tolerant_gates",
                    "error_correction.fault_tolerant_measurements",
                    "error_correction.fault_tolerant_state_preparation",
                    "error_correction.logical_gate_fidelity",
                    "error_correction.logical_memory_lifetime",
                    "error_correction.logical_clock_cycle",
                    "error_correction.quantum_error_correction_overhead",
                    "error_correction.physical_to_logical_ratio",
                    "error_correction.code_capacity",
                    "error_correction.noise_threshold",
                    "error_correction.break_even_point",
                ],
                "count": 36,
            },
        },
        "totals": {
            "categories": 16,
            "total_fields": 550,
        }
    }

    return INVENTORY


def main():
    print("=" * 70)
    print("QUANTUM COMPUTING METADATA FIELD INVENTORY")
    print("=" * 70)
    print()

    inventory = generate_quantum_inventory()

    print(f"Generated: {inventory['generated_at']}")
    print(f"Categories: {inventory['totals']['categories']}")
    print(f"Total Fields: {inventory['totals']['total_fields']}")
    print()

    print("FIELD COUNTS BY CATEGORY:")
    print("-" * 50)
    for cat_name, cat_data in sorted(inventory['categories'].items(), key=lambda x: x[1]['count'], reverse=True):
        print(f"  {cat_name:35s}: {cat_data['count']:>4} fields")

    output_dir = Path("dist/quantum_inventory")
    output_dir.mkdir(parents=True, exist_ok=True)

    output_file = output_dir / "quantum_inventory.json"
    output_file.write_text(json.dumps(inventory, indent=2, sort_keys=True), encoding="utf-8")
    print()
    print(f"Wrote: {output_file}")

    summary = {
        "generated_at": inventory["generated_at"],
        "source": inventory["source"],
        "description": inventory["description"],
        "categories": {
            k: {
                "count": v["count"],
                "description": v["description"],
                "reference": v.get("reference", "N/A")
            }
            for k, v in inventory["categories"].items()
        },
        "totals": inventory["totals"],
    }

    summary_file = output_dir / "quantum_summary.json"
    summary_file.write_text(json.dumps(summary, indent=2, sort_keys=True), encoding="utf-8")
    print(f"Wrote: {summary_file}")


if __name__ == "__main__":
    main()
