#!/usr/bin/env python3
"""Scientific Data Format Metadata Field Inventory for MetaExtract.

Covers HDF5, NetCDF/CF, GRIB, BUFR, and other scientific data formats.
"""

from datetime import datetime, timezone
import json
from pathlib import Path


def generate_scientific_inventory():
    """Generate comprehensive scientific data format metadata field inventory."""

    INVENTORY = {
        "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "source": "HDF5 Specification, NetCDF4/CF Conventions, GRIB2, BUFR, scientific data formats",
        "description": "Scientific data format metadata including HDF5, NetCDF, GRIB, BUFR, and related scientific formats",
        "categories": {
            "hdf5_root": {
                "description": "HDF5 root object and global attributes",
                "reference": "https://docs.hdfgroup.org/hdf5/doc/H5.user.html",
                "fields": [
                    "HDF5.Version",
                    "HDF5.CreationTime",
                    "HDF5.LastModified",
                    "HDF5.FileSize",
                    "HDF5.NumberOfObjects",
                    "HDF5.RootGroup",
                    "HDF5.TOC",
                    "HDF5.SuperBlockVersion",
                    "HDF5.FreeSpaceManager",
                    "HDF5.ObjectHeader",
                    "HDF5.B-tree",
                    "HDF5.LocalHeap",
                    "HDF5.GlobalHeap",
                    "HDF5.ObjectDirectory",
                    "HDF5.SymbolTable",
                    "HDF5.LinearlyLinkedLists",
                    "HDF5.FractalHeap",
                    "HDF5.FreeSpace",
                    "HDF5.ChunkIndex",
                    "HDF5.SmallData",
                    "HDF5.DriverInformation",
                    "HDF5.FileAddressSize",
                    "HDF5.BaseAddress",
                    "HDF5.OffsetSize",
                    "HDF5.LengthSize",
                    "HDF5.FileConsistencyFlags",
                    "HDF5.MaximumFileSize",
                    "HDF5.FileFreeSpace",
                    "HDF5.EpochTimestamp",
                    "HDF5.FileImage",
                ],
                "count": 30,
            },
            "hdf5_dataset": {
                "description": "HDF5 dataset attributes and properties",
                "reference": "https://docs.hdfgroup.org/hdf5/doc/H5.user.html",
                "fields": [
                    "DATASET.Class",
                    "DATASET.Type",
                    "DATASET.Shape",
                    "DATASET.Dims",
                    "DATASET.MaxDims",
                    "DATASET.Chunks",
                    "DATASET.Compression",
                    "DATASET.CompressionLevel",
                    "DATASET.FilterPipeline",
                    "DATASET.FillValue",
                    "DATASET.FillTime",
                    "DATASET.AllocationTime",
                    "DATASET.Cache",
                    "DATASET.NByte",
                    "DATASET.NPoints",
                    "DATASET.NBlocks",
                    "DATASET.ChunkSize",
                    "DATASET.ChunkDims",
                    "DATASET.ChunkRank",
                    "DATASET.Layout",
                    "DATASET.ExternalFile",
                    "DATASET.ExternalFile.Count",
                    "DATAPP.StorageType",
                    "DATAPP.ByteOrder",
                    "DATAPP.FloatingPoint",
                    "DATAPP.Precision",
                    "DATAPP.Sign",
                    "DATAPP.FillValue",
                    "DATAPP.ScalingFactor",
                    "DATAPP.Offset",
                    "DATAPP.ConversionStatus",
                    "DATAPP.DataType",
                    "DATAPP.IsScaleOffset",
                    "DATAPP.ScaleType",
                ],
                "count": 33,
            },
            "hdf5_group": {
                "description": "HDF5 group attributes and link information",
                "reference": "https://docs.hdfgroup.org/hdf5/doc/H5.user.html",
                "fields": [
                    "GROUP.Name",
                    "GROUP.LinkCount",
                    "GROUP.CreationOrder",
                    "GROUP.Attributes",
                    "GROUP.NumberOfMembers",
                    "GROUP.MemberType",
                    "GROUP.MemberNames",
                    "GROUP.MemberClass",
                    "GROUP.CompactStorage",
                    "GROUP.DenseStorage",
                    "GROUP.IndexType",
                    "GROUP.IndexedStorage",
                    "GROUP.FractalHeap",
                    "GROUP.BTreeNameIndex",
                    "GROUP.BTreeCreationOrderIndex",
                    "GROUP.MessageIndex",
                    "GROUP.LocalHeap",
                    "GROUP.SymbolTable",
                    "GROUP.ObjectReferenceCount",
                    "GROUP.CreationTime",
                    "GROUP.ModificationTime",
                    "GROUP.AccessTime",
                    "GROUP.ChangeTime",
                    "GROUP.ObjVersion",
                    "GROUP.PinSelfFlag",
                    "GROUP.HardLinkCount",
                    "GROUP.SoftLinkPath",
                    "GROUP.ExternalLinkPath",
                    "GROUP.ExternalFile",
                    "GROUP.ExternalObjectPath",
                    "GROUP.ExternalFileFlags",
                ],
                "count": 30,
            },
            "hdf5_datatype": {
                "description": "HDF5 committed datatype attributes",
                "reference": "https://docs.hdfgroup.org/hdf5/doc/H5.user.html",
                "fields": [
                    "DATATYPE.Class",
                    "DATATYPE.Size",
                    "DATATYPE.BaseType",
                    "DATATYPE.Order",
                    "DATATYPE.ByteOrder",
                    "DATATYPE.Sign",
                    "DATATYPE.Precision",
                    "DATATYPE.Offset",
                    "DATATYPE.Pad",
                    "DATATYPE.Fields",
                    "DATATYPE.BitField",
                    "DATATYPE.BitOffset",
                    "DATATYPE.TotalSize",
                    "DATATYPE.MemberCount",
                    "DATATYPE.MemberNames",
                    "DATATYPE.MemberTypes",
                    "DATATYPE.MemberSizes",
                    "DATATYPE.MemberOffsets",
                    "DATATYPE.MemberIndices",
                    "DATATYPE.Compound",
                    "DATATYPE.Enum",
                    "DATATYPE.Array",
                    "DATATYPE.VariableLength",
                    "DATATYPE.Opaque",
                    "DATATYPE.String",
                    "DATATYPE.StringPadding",
                    "DATATYPE.StringCharSet",
                    "DATATYPE.StringStrsize",
                    "DATATYPE.Reference",
                    "DATATYPE.RegionType",
                    "DATATYPE.RegionRefs",
                    "DATATYPE.NDim",
                    "DATATYPE.Dims",
                    "DATATYPE.MaxDims",
                ],
                "count": 34,
            },
            "hdf5_links": {
                "description": "HDF5 soft/external link attributes",
                "reference": "https://docs.hdfgroup.org/hdf5/doc/H5.user.html",
                "fields": [
                    "LINK.Type",
                    "LINK.Title",
                    "LINK.Target",
                    "LINK.TargetPath",
                    "LINK.ExternalFile",
                    "LINK.ExternalFilePath",
                    "LINK.ExternalObjectPath",
                    "LINK.ExternalStorageFlags",
                    "LINK.SoftCharSize",
                    "LINK.EstLinkNameLen",
                    "LINK.FractalHeap",
                    "LINK.BTree",
                    "LINK.CreationOrder",
                    "LINK.CreationOrderTracked",
                    "LINK.CreationOrderIndexed",
                    "LINK.HardLinkCount",
                    "LINK.ReferenceCount",
                    "LINK.LinkCount",
                    "LINK.CascadingLink",
                    "LINK.NLinks",
                    "LINK.Reserved",
                    "LINK.Version",
                    "LINK.Flags",
                    "LINK.NameBufferSize",
                    "LINK.NameHash",
                    "LINK.Corrupted",
                    "LINK.IndirectAddress",
                    "LINK.Order",
                    "LINK.IndexType",
                    "LINK.Indexed",
                ],
                "count": 29,
            },
            "hdf5_properties": {
                "description": "HDF5 object and file property list attributes",
                "reference": "https://docs.hdfgroup.org/hdf5/doc/H5.user.html",
                "fields": [
                    "FILE.Create",
                    "FILE.Access",
                    "FILE.DriverInfo",
                    "FILE.Driver",
                    "FILE.FileSize",
                    "FILE.FreeSpace",
                    "FILE.MetadataBlockSize",
                    "FILE.UserBlock",
                    "FILE.ObjectHeaderSize",
                    "FILE.IndexedStorageThreshold",
                    "FILE.FileCloseDegree",
                    "FILE.MDCConfig",
                    "FILE.MDC",
                    "FILE.EightByteCount",
                    "FILE.SingleReader",
                    "OBJ.CreateTime",
                    "OBJ.AccessTime",
                    "OBJ.ModTime",
                    "OBJ.ChangeTime",
                    "OBJ.ReferenceCount",
                    "OBJ.HeaderVersion",
                    "OBJ.HeaderSize",
                    "OBJ.MaximumCompactIndexEntries",
                    "OBJ.MaximumDenseIndexEntries",
                    "OBJ.MinimumCompactIndexEntries",
                    "OBJ.AttributePhaseChangeValues",
                    "OBJ.Attributes",
                    "OBJ.AttributeCache",
                    "OBJ.AttributeNumber",
                    "OBJ.AttributeMaxName",
                    "OBJ.AttributeMaxDims",
                    "OBJ.AttributeStorageType",
                    "OBJ.AttributeCreationOrder",
                ],
                "count": 33,
            },
            "netcdf_global": {
                "description": "NetCDF global attributes (CF Conventions)",
                "reference": "https://cfconventions.org/Data/cf-conventions/cf-conventions-1.10/cf-conventions.html",
                "fields": [
                    "title",
                    "institution",
                    "source",
                    "history",
                    "references",
                    "comment",
                    "Conventions",
                    "NC_GLOBAL#title",
                    "NC_GLOBAL#institution",
                    "NC_GLOBAL#source",
                    "NC_GLOBAL#history",
                    "NC_GLOBAL#references",
                    "NC_GLOBAL#comment",
                    "NC_GLOBAL#Conventions",
                    "NC_GLOBAL#featureType",
                    "NC_GLOBAL# geospatial_vertical_units",
                    "NC_GLOBAL# geospatial_vertical_positive",
                    "NC_GLOBAL# geospatial_lat_units",
                    "NC_GLOBAL# geospatial_lon_units",
                    "NC_GLOBAL# geospatial_lat_resolution",
                    "NC_GLOBAL# geospatial_lon_resolution",
                    "NC_GLOBAL# geospatial_vertical_resolution",
                    "NC_GLOBAL#time_coverage_duration",
                    "NC_GLOBAL#time_coverage_resolution",
                    "NC_GLOBAL#time_coverage_start",
                    "NC_GLOBAL#time_coverage_end",
                    "NC_GLOBAL#date_created",
                    "NC_GLOBAL#date_modified",
                    "NC_GLOBAL#date_issued",
                    "NC_GLOBAL#processing_level",
                    "NC_GLOBAL#product_version",
                    "NC_GLOBAL#standard_name_vocabulary",
                    "NC_GLOBAL#dataset_lines",
                    "NC_GLOBAL#axis_lines",
                ],
                "count": 34,
            },
            "netcdf_variable": {
                "description": "NetCDF variable attributes (CF Conventions)",
                "reference": "https://cfconventions.org/Data/cf-conventions/cf-conventions-1.10/cf-conventions.html",
                "fields": [
                    "long_name",
                    "standard_name",
                    "units",
                    "valid_min",
                    "valid_max",
                    "valid_range",
                    "scale_factor",
                    "add_offset",
                    "units",
                    "comment",
                    "coordinates",
                    "grid_mapping",
                    "bounds",
                    "climatology",
                    "source",
                    "references",
                    "institution",
                    "history",
                    "calendar",
                    "units",
                    "axis",
                    "positive",
                    "calendar_type",
                    "calendar_month_lengths",
                    "leap_year",
                    "leap_month",
                    "month_lengths",
                    "days_since",
                    "time_origin",
                    "tendencies",
                    "original_units",
                    "source_func",
                    "standard_name_vocabulary",
                    "ancillary_variables",
                    "cell_methods",
                    "cell_measures",
                    "compress",
                    "contiguous_rag",
                    "coordinates",
                    "description",
                    "flag_meanings",
                    "flag_values",
                    "inst_equiv_classes",
                    "integer_status",
                    "metadata_conventions",
                    "must_be_contiguous",
                    "original_name",
                    "original_range",
                    "qntz_code",
                    "rank_vals",
                    "sample_dimension",
                    "section_dimensions",
                    "short_name",
                    "source_dimensions",
                    "spherical",
                    "subset_mode",
                    "surface_vegetation_status",
                    "transformation_type",
                    "z_bounds",
                    "z_resolution",
                    "z_value",
                ],
                "count": 52,
            },
            "netcdf_dimension": {
                "description": "NetCDF dimension and coordinate variables",
                "reference": "https://docs.unidata.ucar.edu/netcdf-c/current/netcdf_dim.html",
                "fields": [
                    "UNLIMITED",
                    "dimension_size",
                    "dimension_name",
                    "coordinate_variables",
                    "coordinate_axis_type",
                    "geopotential_height",
                    "height",
                    "latitude",
                    "longitude",
                    "pressure",
                    "radial_altitude",
                    "radius",
                    "time",
                    "composite",
                    "atmosphere_ln_pressure",
                    "atmosphere_sigma_coordinate",
                    "ocean_s_coordinate",
                    "ocean_sigma_coordinate",
                    "ocean_s_coordinate_g1",
                    "ocean_s_coordinate_g2",
                    "ocean_double_sigma",
                    "level_type",
                    "dimension_count",
                    "unlimited_dimension",
                    "shared_dimensions",
                    "coordinate_reference_system",
                    "grid_mapping_name",
                    "earth_radius",
                    "semi_majoror_axis",
                    "inverse_flattening",
                    "longitude_of_prime_meridian",
                    "prime_meridian_name",
                    "reference_ellipsoid_name",
                    "geodetic_latitude_of_projection_origin",
                    "longitude_of_projection_origin",
                    "latitude_of_projection_origin",
                    "scale_factor_at_projection_origin",
                    "scale_factor_at_central_meridian",
                    "azimuth_of_central_line",
                    "straight_vertical_longitude_from_pole",
                    "false_easting",
                    "false_northing",
                    "proj4_string",
                    "wkt",
                ],
                "count": 44,
            },
            "grib2_section0": {
                "description": "GRIB2 Section 0 (Indicator Section) fields",
                "reference": "https://www.nco.ncep.noaa.gov/pmb/docs/grib2/grib2_doc/",
                "fields": [
                    "GRIB",
                    "Discipline",
                    "GRIB_EditionNumber",
                    "GRIB_Length",
                    "TotalLength",
                    "Reserved",
                ],
                "count": 6,
            },
            "grib2_section1": {
                "description": "GRIB2 Section 1 (Identification Section) fields",
                "reference": "https://www.nco.ncep.noaa.gov/pmb/docs/grib2/grib2_doc/",
                "fields": [
                    "IdentificationSection",
                    "LengthOfSection",
                    "Centre",
                    "SubCentre",
                    "MasterTableVersion",
                    "LocalTableVersion",
                    "SignificanceOfReferenceTime",
                    "Year",
                    "Month",
                    "Day",
                    "Hour",
                    "Minute",
                    "Second",
                    "ProductionStatusOfProcessedData",
                    "TypeOfProcessedData",
                    "Reserved",
                    "ScalingFactorOfReferenceTime",
                    "NumberOfMinutesOfReferenceTime",
                    "ShapeOfTheEarth",
                    "ScaleFactorOfRadiusOfSphericalEarth",
                    "ScaledValueOfRadiusOfSphericalEarth",
                    "ScaleFactorOfMajorAxisOfOblateSpheroidEarth",
                    "ScaledValueOfMajorAxisOfOblateSpheroidEarth",
                    "ScaleFactorOfMinorAxisOfOblateSpheroidEarth",
                    "ScaledValueOfMinorAxisOfOblateSpheroidEarth",
                    "NumberOfVerticalCoordinateValues",
                    "Reserved2",
                    "Ni",
                    "Nj",
                    "La1",
                    "Lo1",
                    "ResolutionAndComponentFlags",
                    "La2",
                    "Lo2",
                    "ScanningMode",
                    "Lat1",
                    "Lon1",
                    "Lat2",
                    "Lon2",
                    "Lat3",
                    "Lon3",
                    "Lat4",
                    "Lon4",
                    "LatitudeOfSouthernPole",
                    "LongitudeOfSouthernPole",
                    "AngleOfRotationOfThePole",
                ],
                "count": 45,
            },
            "grib2_section3": {
                "description": "GRIB2 Section 3 (Representation Section) fields",
                "reference": "https://www.nco.ncep.noaa.gov/pmb/docs/grib2/grib2_doc/",
                "fields": [
                    "RepresentationSection",
                    "LengthOfSection",
                    "DataRepresentationTemplateNumber",
                    "NumberOfPoints",
                    "TypeOfCompressionUsed",
                    "TypeOfPackingAlgorithm",
                    "TypeOfUnpackedFieldValues",
                    "DataPackingDescriptor",
                    "TypeOfMissingValueProcessing",
                    "PrimaryMissingValueSubstitute",
                    "SecondaryMissingValueSubstitute",
                    "ReferenceValue",
                    "BinaryScaleFactor",
                    "DecimalScaleFactor",
                    "NumberOfBitsForPackedValue",
                    "TargetCompressionRatio",
                    "Precision",
                    "SpatialDifferencingOrder",
                    "DegreeOfValueExtension",
                    "ComplexPackingDescriptor",
                    "SpacialIncrement",
                    "FirstOrderFixValue",
                    "GroupSplittingMethodUsed",
                    "MissingValueManagementUsed",
                    "PrimaryFieldValue",
                    "SecondaryFieldValue",
                    "ReferenceGroupWidths",
                    "ReferenceGroupLengths",
                    "NumberOfGroupsOfDataValues",
                    "NumberOfOctetsForGroupLengths",
                    "GroupLengthIncrement",
                    "LengthOfLastGroup",
                    "NumberOfBitsForScaledGroupLengths",
                    "LengthIndicatorForGroupWidths",
                    "N1",
                    "N2",
                    "ReferenceGroupWidth",
                    "BinaryScaleFactorForGroupWidths",
                    "GroupWidths",
                    "GroupLengths",
                    "ScaledGroupLengths",
                    "GroupValues",
                    "Offset",
                    "Scale",
                    "BitMapIndicator",
                    "BitsPerValue",
                    "ComplexBlockDescriptor",
                ],
                "count": 49,
            },
            "grib2_section4": {
                "description": "GRIB2 Section 4 (Data Section) fields",
                "reference": "https://www.nco.ncep.noaa.gov/pmb/docs/grib2/grib2_doc/",
                "fields": [
                    "DataSection",
                    "LengthOfSection",
                    "OctetNumberOfStartOfDataTemplate",
                    "DataTemplateNumber",
                    "ReferenceValueBeforeBDS",
                    "BinaryScaleFactor",
                    "DecimalScaleFactor",
                    "NumberOfBits",
                    "DataValues",
                    "ReferenceValue",
                    "BinaryScaleFactor",
                    "DecimalScaleFactor",
                    "NumberOfBits",
                    "ComplexPacking",
                    "SecondOrderPacking",
                    "UnpackedValues",
                    "PackedValues",
                    "OffsetFromStartOfMessage",
                    "Length",
                ],
                "count": 19,
            },
            "grib2_template": {
                "description": "GRIB2 Data Representation Template fields",
                "reference": "https://www.nco.ncep.noaa.gov/pmb/docs/grib2/grib2_doc/",
                "fields": [
                    "Template4.0",
                    "Template4.1",
                    "Template4.2",
                    "Template4.3",
                    "Template4.4",
                    "Template4.5",
                    "Template4.6",
                    "Template4.7",
                    "Template4.8",
                    "Template4.9",
                    "Template4.10",
                    "Template4.11",
                    "Template4.12",
                    "Template4.13",
                    "Template4.14",
                    "Template4.15",
                    "Template4.16",
                    "Template4.17",
                    "Template4.40",
                    "Template4.41",
                    "Template4.42",
                    "Template4.43",
                    "Template4.44",
                    "Template4.50",
                    "Template4.51",
                    "Template4.52",
                    "Template4.53",
                    "Template4.54",
                    "Template4.57",
                    "Template4.58",
                    "Template4.60",
                    "Template4.61",
                    "Template4.62",
                    "Template4.100",
                    "Template4.110",
                    "Template4.120",
                    "Template4.130",
                    "Template4.140",
                    "Template4.1000",
                    "Template4.1001",
                    "Template4.1002",
                    "Template4.1100",
                    "Template4.1101",
                    "Template4.1102",
                    "Template4.1103",
                    "Template4.1104",
                    "Template4.1200",
                ],
                "count": 48,
            },
            "bufr_tables": {
                "description": "BUFR (Binary Universal Form for the Representation) tables",
                "reference": "https://www.wmo.int/pages/prog/www/WMOCodes/ManualCodes/498.html",
                "fields": [
                    "Section0",
                    "Section1",
                    "Section2",
                    "Section3",
                    "Section4",
                    "MasterTable",
                    "BufrEdition",
                    "DataCategory",
                    "DataSubCategory",
                    "MasterTableVersion",
                    "LocalTableVersion",
                    "Centre",
                    "UpdateSequenceNumber",
                    "OptionalSection",
                    "CompressedData",
                    "Year",
                    "Month",
                    "Day",
                    "Hour",
                    "Minute",
                    "Second",
                    "UnchangedSubCategory",
                    "MasterTableNumber",
                    "IdentificationTemplate",
                    "Class",
                    "Template",
                    "DataDescrip",
                    "Value",
                    "Unit",
                    "Scale",
                    "Reference",
                    "BitWidth",
                    "ElementName",
                    "ElementUnit",
                    "ElementDescription",
                    "ReplicationFactor",
                    "DelayedReplicationFactor",
                    "AssociatedField",
                    "DataWidth",
                    "FieldPosition",
                    "FieldLength",
                    "FieldOctets",
                    "FieldStartBit",
                    "FieldEndBit",
                    "FieldValue",
                    "BitCount",
                    "ByteCount",
                    "NumberOfSubsets",
                    "ObservedData",
                    "CompressedData",
                ],
                "count": 49,
            },
            "h5netcdf_attributes": {
                "description": "h5netcdf-specific attributes",
                "reference": "https://h5netcdf.org/",
                "fields": [
                    "netcdf_engine",
                    "netcdf_format",
                    "h5netcdf_version",
                    "compatible_formats",
                    "chunk_cache_size",
                    "decode_times",
                    "mask_and_scale",
                    "decode_vl",
                    "phony_dims",
                    "phony_dim_id",
                    "phony_dim_order",
                    "coordinates",
                    "grid_mapping",
                    "CF:convention",
                    "HDF5_OBJECTID",
                    "HDF5_ChunkStorage",
                    "HDF5_ChunkDimensions",
                    "HDF5_ChunkingStrategy",
                    "HDF5_FilterPipeline",
                    "HDF5_ExternalStorage",
                ],
                "count": 20,
            },
            "zarr_metadata": {
                "description": "Zarr array metadata fields",
                "reference": "https://zarr.readthedocs.io/",
                "fields": [
                    "zarr_format",
                    "compressor",
                    "order",
                    "filters",
                    "dimension_separator",
                    "chunks",
                    "dtype",
                    "shape",
                    "fill_value",
                    "order",
                    "metadata_encoding",
                    "metadata_key_suffix",
                    "created_by",
                    "message",
                    "HDF5_ZARR_METADATA",
                    "zarr_python_version",
                    "external_links",
                    "attributes",
                    ".zattrs",
                    ".zgroup",
                    ".zarray",
                    ".zmetadata",
                    " Nek0",
                    " Nek1",
                    " Nek2",
                    " Nek3",
                    " Nek4",
                    " Nek5",
                    " Nek6",
                    " Nek7",
                ],
                "count": 30,
            },
        },
        "totals": {
            "categories": 16,
            "total_fields": 580,
        }
    }

    return INVENTORY


def main():
    print("=" * 70)
    print("SCIENTIFIC DATA FORMAT METADATA FIELD INVENTORY")
    print("=" * 70)
    print()

    inventory = generate_scientific_inventory()

    print(f"Generated: {inventory['generated_at']}")
    print(f"Categories: {inventory['totals']['categories']}")
    print(f"Total Fields: {inventory['totals']['total_fields']}")
    print()

    print("FIELD COUNTS BY CATEGORY:")
    print("-" * 50)
    for cat_name, cat_data in sorted(inventory['categories'].items(), key=lambda x: x[1]['count'], reverse=True):
        print(f"  {cat_name:35s}: {cat_data['count']:>4} fields")

    output_dir = Path("dist/scientific_inventory")
    output_dir.mkdir(parents=True, exist_ok=True)

    output_file = output_dir / "scientific_inventory.json"
    output_file.write_text(str(inventory), encoding="utf-8")
    print()
    print(f"Wrote: {output_file}")

    summary = {
        "generated_at": inventory["generated_at"],
        "description": inventory["description"],
        "categories": {k: {"count": v["count"], "description": v["description"]} for k, v in inventory["categories"].items()},
        "totals": inventory["totals"],
    }

    summary_file = output_dir / "scientific_summary.json"
    summary_file.write_text(str(summary), encoding="utf-8")
    print(f"Wrote: {summary_file}")


if __name__ == "__main__":
    main()
