#!/usr/bin/env python3
"""Logistics/Supply Chain Metadata Field Inventory for MetaExtract.

Covers warehouse management, transportation, order management, customs/compliance,
packaging, reverse logistics, and RFID/barcode tracking metadata.
"""

from datetime import datetime, timezone
import json
from pathlib import Path


def generate_logistics_inventory():
    """Generate comprehensive logistics/supply chain metadata field inventory."""

    INVENTORY = {
        "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "source": "GS1 Standards, WMS Specifications, Transportation Standards, Customs Regulations, Packaging Standards, RFID EPC Gen2",
        "description": "Logistics and supply chain metadata including warehouse, transportation, order management, customs, packaging, returns, and RFID/barcode tracking",
        "categories": {
            "warehouse_management": {
                "description": "Warehouse management system fields - location, bin, pick path, inventory status",
                "reference": "WMS Specifications, GS1 Warehouse Management Guidelines",
                "fields": [
                    "warehouse.location_id",
                    "warehouse.zone",
                    "warehouse.aisle",
                    "warehouse.rack",
                    "warehouse.shelf",
                    "warehouse.bin",
                    "warehouse.bin_type",
                    "warehouse.bin_status",
                    "warehouse.pick_path",
                    "warehouse.pick_sequence",
                    "warehouse.pick_zone",
                    "warehouse.receiving_dock",
                    "warehouse.shipping_dock",
                    "warehouse.staging_area",
                    "warehouse.cross_dock_zone",
                    "warehouse.bulk_storage",
                    "warehouse.reserve_storage",
                    "warehouse.forward_pick_zone",
                    "warehouse.inventory_status",
                    "warehouse.stock_level",
                    "warehouse.on_hand_qty",
                    "warehouse.available_qty",
                    "warehouse.allocated_qty",
                    "warehouse.reserved_qty",
                    "warehouse.in_transit_qty",
                    "warehouse.on_order_qty",
                    "warehouse.safety_stock",
                    "warehouse.reorder_point",
                    "warehouse.cycle_count",
                    "warehouse.physical_inventory",
                    "warehouse.location_capacity",
                    "warehouse.max_capacity",
                    "warehouse.current_utilization",
                    "warehouse.warehouse_id",
                    "warehouse.warehouse_name",
                    "warehouse.warehouse_type",
                    "warehouse.temperature_zone",
                    "warehouse.tempControlled",
                    "warehouse.humidity_control",
                    "warehouse.zone_category",
                    "warehouse.flow_rack",
                    "warehouse.static_rack",
                    "warehouse.pallet_rack",
                    "warehouse.carton_flow",
                    "warehouse.shelf_life_tracking",
                    "warehouse.fifo_rotation",
                    "warehouse.lifo_rotation",
                    "warehouse.put_away_strategy",
                    "warehouse.pick_strategy",
                    "warehouse.labor_zone",
                    "warehouse.equipment_type",
                    "warehouse.aisle_width",
                    "warehouse.floor_load",
                    "warehouse.ceiling_height",
                    "warehouse.sprinkler_system",
                    "warehouse.fire_suppression",
                    "warehouse.hazmat_zone",
                    "warehouse.quarantine_area",
                    "warehouse.return_processing_area",
                    "warehouse.value_added_services",
                    "warehouse.kitting_area",
                    "warehouse.repack_area",
                ],
                "count": 60,
            },
            "transportation": {
                "description": "Transportation and freight management fields - carrier, route, freight class, tracking",
                "reference": "Transportation Standards, DOT Regulations, Carrier Specifications, GS1 Transport Logistics",
                "fields": [
                    "transport.tracking_number",
                    "transport.carrier",
                    "transport.carrier_code",
                    "transport.carrier_service",
                    "transport.carrier_service_level",
                    "transport.freight_class",
                    "transport.nmfc_code",
                    "transport.route_id",
                    "transport.route_sequence",
                    "transport.origin_id",
                    "transport.origin_name",
                    "transport.origin_address",
                    "transport.origin_city",
                    "transport.origin_state",
                    "transport.origin_zip",
                    "transport.origin_country",
                    "transport.destination_id",
                    "transport.destination_name",
                    "transport.destination_address",
                    "transport.destination_city",
                    "transport.destination_state",
                    "transport.destination_zip",
                    "transport.destination_country",
                    "transport.ship_date",
                    "transport.delivery_date",
                    "transport.delivery_window",
                    "transport.estimated_delivery",
                    "transport.actual_delivery",
                    "transport.weight",
                    "transport.weight_unit",
                    "transport.dimensional_weight",
                    "transport.dimensional_factor",
                    "transport.length",
                    "transport.width",
                    "transport.height",
                    "transport.dimension_unit",
                    "transport.cubic_feet",
                    "transport.shipment_id",
                    "transport.pro_number",
                    "transport.bol_number",
                    "transport.po_number",
                    "transport.reference_number",
                    "transport.shipment_status",
                    "transport.delivery_status",
                    "transport.transit_status",
                    "transport.exception_status",
                    "transport.delivery_confirmation",
                    "transport.signature_required",
                    "transport.signature_captured",
                    "transport.special_instructions",
                    "transport.accessorials",
                    "transport.insurance_value",
                    "transport.cod_amount",
                    "transport.fuel_surcharge",
                    "transport.actual_cost",
                    "transport.bill_to",
                    "transport.shipper_id",
                    "transport.consignee_id",
                ],
                "count": 50,
            },
            "order_management": {
                "description": "Order management and fulfillment fields - order ID, line items, fulfillment status",
                "reference": "Order Management System Specifications, E-Commerce Standards, Fulfillment Protocols",
                "fields": [
                    "order.order_id",
                    "order.order_number",
                    "order.order_type",
                    "order.order_source",
                    "order.order_channel",
                    "order.customer_id",
                    "order.customer_name",
                    "order.customer_email",
                    "order.customer_phone",
                    "order.ship_to_address",
                    "order.ship_to_city",
                    "order.ship_to_state",
                    "order.ship_to_zip",
                    "order.ship_to_country",
                    "order.bill_to_address",
                    "order.order_date",
                    "order.order_time",
                    "order.order_status",
                    "order.fulfillment_status",
                    "order.payment_status",
                    "order.credit_status",
                    "order.line_items",
                    "order.line_number",
                    "order.sku",
                    "order.upc",
                    "order.product_name",
                    "order.product_description",
                    "order.quantity",
                    "order.quantity_allocated",
                    "order.quantity_shipped",
                    "order.quantity_picked",
                    "order.quantity_packed",
                    "order.unit_price",
                    "order.total_price",
                    "order.discount",
                    "order.tax",
                    "order.shipping_cost",
                    "order.handling_fee",
                    "order.subtotal",
                    "order.order_total",
                    "order.currency",
                    "order.priority",
                    "order.rush_order",
                    "order.ship_complete",
                    "order.split_shipment",
                    "order.partial_fulfillment",
                    "order.cancel_date",
                    "order.cancel_reason",
                    "order.notes",
                    "order.internal_notes",
                    "order.pick_ticket",
                    "order.pick_status",
                    "order.pack_status",
                ],
                "count": 50,
            },
            "customs_compliance": {
                "description": "Customs and compliance fields - HS codes, duties, country of origin, FDA",
                "reference": "WTO HS System, FDA Regulations, USDA Requirements, Import/Export Compliance",
                "fields": [
                    "customs.hs_code",
                    "customs.tariff_code",
                    "customs.tariff_description",
                    "customs.country_of_origin",
                    "customs.manufacturer_country",
                    "customs.country_of_export",
                    "customs.country_of_transshipment",
                    "customs.port_of_entry",
                    "customs.port_of_export",
                    "customs.customs_value",
                    "customs.freight_value",
                    "customs.insurance_value",
                    "customs.duty_rate",
                    "customs.duty_amount",
                    "customs.vat_rate",
                    "customs.vat_amount",
                    "customs.excise_tax",
                    "customs.customs_fees",
                    "customs.bond_amount",
                    "customs.declaration_number",
                    "customs.entry_type",
                    "customs.entry_status",
                    "customs.importer_id",
                    "customs.importer_name",
                    "customs.importer_address",
                    "customs.exporter_id",
                    "customs.exporter_name",
                    "customs.exporter_address",
                    "customs.fda_registration",
                    "customs.fda_facility_id",
                    "customs.fda_product_code",
                    "customs.fda_prior_notice",
                    "customs.fda_inspection_status",
                    "customs.usda_license",
                    "customs.usda_inspection",
                    "customs.phytosanitary",
                    "customs.fumigation",
                    "customs.certificate_of_origin",
                    "customs.fta_certificate",
                    "customs.nafta_certificate",
                    "customs.ace_status",
                    "customs.ams_filing",
                    "customs.isf_filing",
                    "customs.10_2_filing",
                    "customs.pga_status",
                    "customs.cbp_hold",
                    "customs.fda_hold",
                    "customs.agriculture_hold",
                    "customs.compliance_notes",
                    "customs.restricted_items",
                    "customs.prohibited_items",
                    "customs.special_requirements",
                ],
                "count": 50,
            },
            "packaging": {
                "description": "Packaging and unitization fields - box dimensions, weight, palletization, shipping units",
                "reference": "Packaging Standards, GS1 Package Marking, Pallet Specifications, ISTA Testing",
                "fields": [
                    "packaging.pallet_type",
                    "packaging.pallet_size",
                    "packaging.pallet_material",
                    "packaging.pallet_grade",
                    "packaging.pallet_weight",
                    "packaging.pallet_height",
                    "packaging.pallet_capacity",
                    "packaging.cases_per_pallet",
                    "packaging.layers_per_pallet",
                    "packaging.cases_per_layer",
                    "packaging.pallet_id",
                    "packaging.pallet_serial",
                    "packaging.box_id",
                    "packaging.box_type",
                    "packaging.box_length",
                    "packaging.box_width",
                    "packaging.box_height",
                    "packaging.box_weight",
                    "packaging.box_volume",
                    "packaging.box_material",
                    "packaging.box_grade",
                    "packaging.inner_pack_qty",
                    "packaging.pack_qty",
                    "packaging.shipping_unit_id",
                    "packaging.shipping_unit_type",
                    "packaging.shipping_weight",
                    "packaging.shipping_dimensions",
                    "packaging.package_type",
                    "packaging.packaging_level",
                    "packaging.primary_packaging",
                    "packaging.secondary_packaging",
                    "packaging.tertiary_packaging",
                    "packaging.shipper_type",
                    "packaging.divider_type",
                    "packaging.cushioning_material",
                    "packaging.carton_style",
                    "packaging.tape_type",
                    "packaging.label_type",
                    "packaging.barcode_type",
                    "packaging.gtin",
                    "packaging.sscc",
                    "packaging.gln",
                    "packaging.serial_number",
                    "packaging.lot_number",
                    "packaging.batch_number",
                    "packaging.production_date",
                    "packaging.expiration_date",
                    "packaging.best_before_date",
                    "packaging.sell_by_date",
                    "packaging.stackability",
                    "packaging.ti_hi",
                    "packaging.package_integrity",
                    "packaging.fragile_marking",
                    "packaging.upside_down_marking",
                    "packaging.hazard_class",
                ],
                "count": 50,
            },
            "reverse_logistics": {
                "description": "Reverse logistics and returns processing fields - returns, refurbishment, RMA",
                "reference": "Returns Management Standards, RMA Processing, Refurbishment Protocols, Circular Economy",
                "fields": [
                    "returns.rma_id",
                    "returns.rma_number",
                    "returns.rma_type",
                    "returns.rma_reason",
                    "returns.rma_reason_code",
                    "returns.rma_status",
                    "returns.return_request_date",
                    "returns.return_approved_date",
                    "returns.return_ship_date",
                    "returns.return_received_date",
                    "returns.return_processed_date",
                    "returns.refund_date",
                    "returns.exchange_date",
                    "returns.original_order_id",
                    "returns.original_order_date",
                    "returns.customer_id",
                    "returns.customer_name",
                    "returns.customer_email",
                    "returns.product_id",
                    "returns.product_sku",
                    "returns.product_description",
                    "return.quantity_returned",
                    "return.quantity_received",
                    "return.quantity_damaged",
                    "return.quantity_salvagable",
                    "return.quantity_destroyed",
                    "return.condition_code",
                    "return.condition_description",
                    "return.damage_type",
                    "return.damage_severity",
                    "return.inspection_status",
                    "return.inspection_notes",
                    "return.refurbishment_status",
                    "return.refurbishment_level",
                    "return.repair_required",
                    "return.parts_replaced",
                    "return.quality_score",
                    "return.testing_status",
                    "return.certification",
                    "return.return_destination",
                    "return.warehouse_location",
                    "return.disposition_code",
                    "return.resellable",
                    "return.return_to_vendor",
                    "return.liquidation",
                    "return.recycling",
                    "return.donation",
                    "return.disposal",
                    "return.credit_amount",
                    "return.restocking_fee",
                    "return.return_shipping_cost",
                    "return.automation_status",
                ],
                "count": 50,
            },
            "rfid_barcode": {
                "description": "RFID and barcode identification fields - EPC, GTIN, GS1 standards, scan events",
                "reference": "EPC Gen2, GS1 EPCIS, GS1-128, DataMatrix, QR Code Standards",
                "fields": [
                    "rfid.epc_code",
                    "rfid.epc_pure_identity",
                    "rfid.epc_partition",
                    "rfid.epc_filter",
                    "rfid.epc_company_prefix",
                    "rfid.epc_item_reference",
                    "rfid.epc_serial_number",
                    "rfid.epc_tag_id",
                    "rfid.epc_encoded_data",
                    "rfid.epc_uri",
                    "rfid.tag_type",
                    "rfid.tag_class",
                    "rfid.frequency",
                    "rfid.memory_size",
                    "rfid.user_memory",
                    "rfid.write_cycles",
                    "rfid.read_cycles",
                    "rfid.lock_status",
                    "rfid.kill_password",
                    "rfid.access_password",
                    "rfid.antenna_id",
                    "rfid.reader_id",
                    "rfid.reader_name",
                    "rfid.reader_location",
                    "rfid.read_timestamp",
                    "rfid.read_event",
                    "rfid.scan_time",
                    "rfid.scan_location",
                    "rfid.scan_operator",
                    "rfid.scan_type",
                    "rfid.scan_result",
                    "rfid.first_seen",
                    "rfid.last_seen",
                    "rfid.location_history",
                    "barcode.gtin",
                    "barcode.gtin_14",
                    "barcode.upc",
                    "barcode.ean",
                    "barcode.sscc",
                    "barcode.gln",
                    "barcode.gs1_128",
                    "barcode.data_matrix",
                    "barcode.qr_code",
                    "barcode.code_128",
                    "barcode.code_39",
                    "barcode.codabar",
                    "barcode.itf_14",
                    "barcode.pdf417",
                ],
                "count": 40,
            },
        },
        "totals": {
            "categories": 7,
            "total_fields": 350,
        }
    }

    return INVENTORY


def main():
    print("=" * 70)
    print("LOGISTICS/SUPPLY CHAIN METADATA FIELD INVENTORY")
    print("=" * 70)
    print()

    inventory = generate_logistics_inventory()

    print(f"Generated: {inventory['generated_at']}")
    print(f"Categories: {inventory['totals']['categories']}")
    print(f"Total Fields: {inventory['totals']['total_fields']}")
    print()

    print("FIELD COUNTS BY CATEGORY:")
    print("-" * 50)
    for cat_name, cat_data in sorted(inventory['categories'].items(), key=lambda x: x[1]['count'], reverse=True):
        print(f"  {cat_name:30s}: {cat_data['count']:>4} fields")

    output_dir = Path("dist/logistics_inventory")
    output_dir.mkdir(parents=True, exist_ok=True)

    output_file = output_dir / "logistics_inventory.json"
    output_file.write_text(json.dumps(inventory, indent=2, sort_keys=True), encoding="utf-8")
    print()
    print(f"Wrote: {output_file}")

    summary = {
        "generated_at": inventory["generated_at"],
        "source": inventory["source"],
        "description": inventory["description"],
        "categories": {
            k: {
                "count": v["count"],
                "description": v["description"],
                "reference": v.get("reference", "N/A")
            }
            for k, v in inventory["categories"].items()
        },
        "totals": inventory["totals"],
    }

    summary_file = output_dir / "logistics_summary.json"
    summary_file.write_text(json.dumps(summary, indent=2, sort_keys=True), encoding="utf-8")
    print(f"Wrote: {summary_file}")


if __name__ == "__main__":
    main()
