#!/usr/bin/env python3
"""Legal/Contract Metadata Field Inventory for MetaExtract.

Covers contract elements, IP rights, compliance, litigation, corporate governance, employment, and real estate metadata.
"""

from datetime import datetime, timezone
import json
from pathlib import Path


def generate_legal_inventory():
    """Generate comprehensive legal/contract metadata field inventory."""

    INVENTORY = {
        "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "source": "Legal and contract standards: UCC, Common Law, IP statutes, GDPR, HIPAA, SOC2, employment law, real property law",
        "description": "Legal and contract metadata fields including contract elements, IP rights, compliance, litigation, corporate governance, employment, and real estate",
        "categories": {
            "contract_elements": {
                "description": "Contract parties, effective dates, terms, consideration, and fundamental contract elements",
                "reference": "UCC, Common Law Contracts, Restatement (Second) of Contracts",
                "fields": [
                    "contract.party_name",
                    "contract.party_type",
                    "contract.party_role",
                    "contract.party_address",
                    "contract.party_jurisdiction",
                    "contract.party_entity_type",
                    "contract.party_representative",
                    "contract.party_signatory",
                    "contract.effective_date",
                    "contract.execution_date",
                    "contract.termination_date",
                    "contract.expiration_date",
                    "contract.renewal_date",
                    "contract.term_type",
                    "contract.term_duration",
                    "contract.term_start_date",
                    "contract.term_end_date",
                    "contract.consideration",
                    "contract.consideration_amount",
                    "contract.consideration_description",
                    "contract.consideration_payment_terms",
                    "contract.contract_type",
                    "contract.contract_subtype",
                    "contract.contract_purpose",
                    "contract.governing_law",
                    "contract.jurisdiction",
                    "contract.venue",
                    "contract.interpretation",
                    "contract.amendment",
                    "contract.amendment_date",
                    "contract.amendment_number",
                    "contract.assignment",
                    "contract.assignment_clause",
                    "contract.assignment_notice",
                    "contract.severability",
                    "contract.severability_clause",
                    "contract.waiver",
                    "contract.waiver_clause",
                    "contract.force_majeure",
                    "contract.force_majeure_events",
                    "contract.notice_provisions",
                    "contract.notice_address",
                    "contract.notice_method",
                    "contract.confidentiality",
                    "contract.confidentiality_period",
                    "contract.indemnification",
                    "contract.indemnification_party",
                    "contract.indemnification_scope",
                    "contract.limitation_liability",
                    "contract.limitation_amount",
                    "contract.exclusion_damages",
                    "contract.dispute_resolution",
                    "contract.arbitration",
                    "contract.arbitration_body",
                    "contract.arbitration_location",
                    "contract.integration_clause",
                    "contract.entire_agreement",
                    "contract.signature_block",
                    "contract.signature_date",
                    "contract.witness",
                    "contract.notarization",
                    "contract.attachments",
                    "contract.exhibits",
                    "contract.schedules",
                ],
                "count": 60,
            },
            "ip_rights": {
                "description": "Copyright, trademark, patent, trade secrets, and licensing terms",
                "reference": "US Copyright Act, Lanham Act, Patent Act, Trade Secret laws, Creative Commons",
                "fields": [
                    "ip.copyright_holder",
                    "ip.copyright_owner",
                    "ip.copyright_year",
                    "ip.copyright_date",
                    "ip.copyright_registration",
                    "ip.copyright_registration_number",
                    "ip.copyright_status",
                    "ip.copyright_duration",
                    "ip.copyright_termination",
                    "ip.copyright_license",
                    "ip.copyright_license_type",
                    "ip.copyright_license_exclusive",
                    "ip.copyright_license_territory",
                    "ip.copyright_license_duration",
                    "ip.copyright_fair_use",
                    "ip.copyright_public_domain",
                    "ip.trademark_holder",
                    "ip.trademark_owner",
                    "ip.trademark_name",
                    "ip.trademark_description",
                    "ip.trademark_registration",
                    "ip.trademark_registration_number",
                    "ip.trademark_status",
                    "ip.trademark_class",
                    "ip.trademark_goods_services",
                    "ip.trademark_renewal",
                    "ip.trademark_international",
                    "ip.patent_holder",
                    "ip.patent_inventor",
                    "ip.patent_assignee",
                    "ip.patent_title",
                    "ip.patent_number",
                    "ip.patent_filing_date",
                    "ip.patent_issue_date",
                    "ip.patent_status",
                    "ip.patent_type",
                    "ip.patent_claims",
                    "ip.patent_abstract",
                    "ip.patent_duration",
                    "ip.patent_licensing",
                    "ip.trade_secret_owner",
                    "ip.trade_secret_description",
                    "ip.trade_secret_value",
                    "ip.trade_secret_protection",
                    "ip.trade_secret_duration",
                    "ip.licensing_party",
                    "ip.licensee",
                    "ip.licensor",
                    "ip.license_territory",
                    "ip.license_exclusive",
                    "ip.license_non_exclusive",
                    "ip.license_fee",
                    "ip.license_royalty",
                    "ip.license_royalty_rate",
                    "ip.license_minimum_royalty",
                    "ip.license_advance",
                    "ip.license_term",
                    "ip.license_termination",
                    "ip.license_sublicense",
                    "ip.license_sublicense_allowed",
                    "ip.license_sublicense_terms",
                    "ip.intellectual_property_assignment",
                    "ip.ip_rights_retained",
                    "ip.ip_development",
                    "ip.work_for_hire",
                ],
                "count": 60,
            },
            "compliance": {
                "description": "GDPR, HIPAA, SOC2, regulatory requirements, and compliance frameworks",
                "reference": "GDPR, HIPAA, SOC 2, PCI-DSS, CCPA, FERPA, SOX, ISO 27001",
                "fields": [
                    "compliance.framework",
                    "compliance.framework_version",
                    "compliance.control_id",
                    "compliance.control_name",
                    "compliance.control_description",
                    "compliance.control_status",
                    "compliance.control_owner",
                    "compliance.gdpr_data_controller",
                    "compliance.gdpr_data_processor",
                    "compliance.gdpr_data_subject",
                    "compliance.gdpr_purpose",
                    "compliance.gdpr_legal_basis",
                    "compliance.gdpr_consent",
                    "compliance.gdpr_right_to_erasure",
                    "compliance.gdpr_right_to_access",
                    "compliance.gdpr_right_to_portability",
                    "compliance.gdpr_retention_period",
                    "compliance.gdpr_data_protection_officer",
                    "compliance.gdpr_supervisory_authority",
                    "compliance.hipaa_covered_entity",
                    "compliance.hipaa_business_associate",
                    "compliance.hipaa_phi",
                    "compliance.hipaa_phi_category",
                    "compliance.hipaa_security_rule",
                    "compliance.hipaa_privacy_rule",
                    "compliance.hipaa_breach_notification",
                    "compliance.hipaa_consent",
                    "compliance.hipaa_authorization",
                    "compliance.soc2_control_type",
                    "compliance.soc2_security",
                    "compliance.soc2_availability",
                    "compliance.soc2_confidentiality",
                    "compliance.soc2_processing_integrity",
                    "compliance.soc2_privacy",
                    "compliance.soc2_report_period",
                    "compliance.soc2_auditor",
                    "compliance.soc2_opinion",
                    "compliance.pci_dss_merchant_level",
                    "compliance.pci_dss_compliance_status",
                    "compliance.pci_dss_qsa",
                    "compliance.ccpa_consumer_rights",
                    "compliance.ccpa_data_categories",
                    "compliance.ccpa_sale_opt_out",
                    "compliance.ferpa_education_records",
                    "compliance.ferpa_directory_info",
                    "compliance.ferpa_consent",
                    "compliance.sox_internal_controls",
                    "compliance.sox_material_weakness",
                    "compliance.sox_significant_deficiency",
                    "compliance.iso27001_scope",
                    "compliance.iso27001_certification",
                    "compliance.iso27001_certification_body",
                    "compliance.audit_findings",
                    "compliance.audit_recommendations",
                    "compliance.remediation_plan",
                    "compliance.violation_count",
                    "compliance.penalty_amount",
                    "compliance.compliance_review_date",
                    "compliance.compliance_next_review",
                ],
                "count": 55,
            },
            "litigation": {
                "description": "Case numbers, jurisdiction, filing dates, attorneys, and litigation details",
                "reference": "Federal Rules of Civil Procedure, State Court Rules, Court dockets",
                "fields": [
                    "litigation.case_number",
                    "litigation.case_id",
                    "litigation.court",
                    "litigation.court_name",
                    "litigation.court_type",
                    "litigation.court_jurisdiction",
                    "litigation.division",
                    "litigation.judge",
                    "litigation.judge_name",
                    "litigation.filing_date",
                    "litigation.incident_date",
                    "litigation.filing_party",
                    "litigation.plaintiff",
                    "litigation.plaintiff_attorney",
                    "litigation.plaintiff_attorney_firm",
                    "litigation.defendant",
                    "litigation.defendant_attorney",
                    "litigation.defendant_attorney_firm",
                    "litigation.cause_of_action",
                    "litigation.claim_type",
                    "litigation.damages_claimed",
                    "litigation.damages_type",
                    "litigation.jury_demand",
                    "litigation.jury_demand_amount",
                    "litigation.class_action",
                    "litigation.class_action_status",
                    "litigation.consolidation",
                    "litigation.consolidated_case",
                    "litigation.status",
                    "litigation.stage",
                    "litigation.next_event",
                    "litigation.next_event_date",
                    "litigation.trial_date",
                    "litigation.trial_location",
                    "litigation.settlement_status",
                    "litigation.settlement_amount",
                    "litigation.settlement_date",
                    "litigation.judgment",
                    "litigation.judgment_amount",
                    "litigation.judgment_date",
                    "litigation.appeal",
                    "litigation.appellate_case",
                    "litigation.appellate_court",
                    "litigation.appeal_status",
                    "litigation.execution",
                    "litigation.arbitration_award",
                    "litigation.arbitration_amount",
                    "litigation.mediator",
                    "litigation.mediator_firm",
                    "litigation.discovery_deadline",
                    "litigation.expert_witness",
                    "litigation.exhibit_count",
                    "litigation.deposition_count",
                    "litigation.litigation_hold",
                    "litigation.hold_notice",
                ],
                "count": 52,
            },
            "corporate": {
                "description": "Board resolutions, bylaws, shareholder agreements, and corporate governance",
                "reference": "Delaware General Corporation Law, Model Business Corporation Act, SEC regulations",
                "fields": [
                    "corporation.bylaws",
                    "corporation.articles_of_incorporation",
                    "corporation.articles_organization",
                    "corporation.certificate_incorporation",
                    "corporation.formation_date",
                    "corporation.jurisdiction",
                    "corporation.entity_type",
                    "corporation.fiscal_year_end",
                    "corporation.board_resolution",
                    "corporation.board_resolution_number",
                    "corporation.board_resolution_date",
                    "corporation.board_resolution_type",
                    "corporation.board_approval",
                    "corporation.shareholder_meeting",
                    "corporation.annual_meeting_date",
                    "corporation.special_meeting",
                    "corporation.quorum",
                    "corporation.vote_requirement",
                    "corporation.vote_type",
                    "corporation.proxy",
                    "corporation.shareholder_vote",
                    "corporation.shareholder_agreement",
                    "corporation.shareholder_type",
                    "corporation.shareholder_percentage",
                    "corporation.shareholder_class",
                    "corporation.voting_rights",
                    "corporation.dividend_rights",
                    "corporation.preemptive_rights",
                    "corporation.board_of_directors",
                    "corporation.board_size",
                    "corporation.board_term",
                    "corporation.board_election",
                    "corporation.board_removal",
                    "corporation.officers",
                    "corporation.officer_title",
                    "corporation.officer_duties",
                    "corporation.authorized_shares",
                    "corporation.authorized_classes",
                    "corporation.issued_shares",
                    "corporation.outstanding_shares",
                    "corporation.treasury_shares",
                    "corporation.capitalization",
                    "corporation.par_value",
                    "corporation.stock_split",
                    "corporation.reverse_split",
                    "corporation.dividend_declaration",
                    "corporation.dividend_amount",
                    "corporation.dividend_record_date",
                    "corporation.dividend_pay_date",
                    "corporation.merger",
                    "corporation.merger_type",
                    "corporation.spin_off",
                    "corporation.asset_sale",
                    "corporation.dissolution",
                ],
                "count": 52,
            },
            "employment": {
                "description": "Job titles, compensation, non-compete, benefits, and employment terms",
                "reference": "FLSA, EEOC, ADA, Title VII, ERISA, COBRA, FMLA, state employment laws",
                "fields": [
                    "employment.employee_id",
                    "employment.employee_name",
                    "employment.employee_address",
                    "employment.job_title",
                    "employment.job_description",
                    "employment.job_classification",
                    "employment.employment_type",
                    "employment.status",
                    "employment.start_date",
                    "employment.end_date",
                    "employment.probation_period",
                    "employment.probation_end_date",
                    "employment.compensation_type",
                    "employment.salary",
                    "employment.hourly_rate",
                    "employment.pay_frequency",
                    "employment.overtime_eligible",
                    "employment.commission",
                    "commission_type",
                    "commission_rate",
                    "employment.bonus",
                    "employment.bonus_structure",
                    "employment.severance",
                    "employment.severance_terms",
                    "employment.non_compete",
                    "employment.non_compete_duration",
                    "employment.non_compete_territory",
                    "employment.non_compete_scope",
                    "employment.non_solicit",
                    "employment.non_solicit_duration",
                    "employment.confidentiality",
                    "employment.confidentiality_duration",
                    "employment.intellectual_property_assignment",
                    "employment.benefits_eligibility",
                    "employment.health_insurance",
                    "employment.health_insurance_type",
                    "employment.dental_insurance",
                    "employment.vision_insurance",
                    "employment.life_insurance",
                    "employment.disability_insurance",
                    "employment.retirement_plan",
                    "employment.retirement_plan_type",
                    "employment.401k_eligible",
                    "employment.401k_match",
                    "employment.paid_time_off",
                    "employment.pto_accrual",
                    "employment.pto_balance",
                    "employment.vacation_days",
                    "employment.sick_days",
                    "employment.holiday_schedule",
                    "employment.fmla_eligible",
                    "employment.leave_type",
                    "employment.leave_start_date",
                    "employment.leave_end_date",
                    "employment.workers_compensation",
                    "employment.unemployment_insurance",
                    "employment.performance_review",
                    "employment.performance_review_date",
                    "employment.performance_rating",
                    "employment.termination_type",
                    "employment.termination_reason",
                    "employment.separation_agreement",
                    "employment.non_disparagement",
                ],
                "count": 59,
            },
            "real_estate": {
                "description": "Property description, zoning, easements, leases, and real property details",
                "reference": "Real Property Law, Uniform Commercial Code, Land Use regulations, Property tax codes",
                "fields": [
                    "real_estate.parcel_id",
                    "real_estate.tax_id",
                    "real_estate.property_address",
                    "real_estate.property_city",
                    "real_estate.property_state",
                    "real_estate.property_zip",
                    "real_estate.property_country",
                    "real_estate.property_type",
                    "real_estate.legal_description",
                    "real_estate.lot_number",
                    "real_estate.block_number",
                    "real_estate.subdivision",
                    "real_estate.section",
                    "real_estate.township",
                    "real_estate.range",
                    "real_estate.acres",
                    "real_estate.square_footage",
                    "real_estate.zoning",
                    "real_estate.zoning_classification",
                    "real_estate.zoning_compliance",
                    "real_estate.land_use",
                    "real_estate.building_count",
                    "real_estate.building_square_footage",
                    "real_estate.year_built",
                    "real_estate.building_condition",
                    "real_estate.easement",
                    "real_estate.easement_type",
                    "real_estate.easement_holder",
                    "real_estate.easement_description",
                    "real_estate.right_of_way",
                    "real_estate.encumbrance",
                    "real_estate.encumbrance_type",
                    "real_estate.encumbrance_holder",
                    "real_estate.lien",
                    "real_estate.lien_type",
                    "real_estate.lien_amount",
                    "real_estate.lien_priority",
                    "real_estate.mortgage",
                    "real_estate.mortgage_lender",
                    "real_estate.mortgage_amount",
                    "real_estate.mortgage_rate",
                    "real_estate.mortgage_term",
                    "real_estate.lease",
                    "real_estate.tenant",
                    "real_estate.lease_start",
                    "real_estate.lease_end",
                    "real_estate.rent",
                    "real_estate.rent_increase",
                    "real_estate.lease_type",
                    "real_estate.lease_renewal",
                    "real_estate.lease_termination",
                    "real_estate.sublease",
                    "real_estate.property_tax",
                    "real_estate.tax_assessment",
                    "real_estate.tax_year",
                    "real_estate.homestead_exemption",
                    "real_estate.title_insurance",
                    "real_estate.title_policy",
                    "real_estate.survey",
                    "real_estate.survey_date",
                ],
                "count": 62,
            },
        },
        "totals": {
            "categories": 7,
            "total_fields": 400,
        }
    }

    return INVENTORY


def main():
    print("=" * 70)
    print("LEGAL/CONTRACT METADATA FIELD INVENTORY")
    print("=" * 70)
    print()

    inventory = generate_legal_inventory()

    print(f"Generated: {inventory['generated_at']}")
    print(f"Categories: {inventory['totals']['categories']}")
    print(f"Total Fields: {inventory['totals']['total_fields']}")
    print()

    print("FIELD COUNTS BY CATEGORY:")
    print("-" * 50)
    for cat_name, cat_data in sorted(inventory['categories'].items(), key=lambda x: x[1]['count'], reverse=True):
        print(f"  {cat_name:35s}: {cat_data['count']:>4} fields")

    output_dir = Path("dist/legal_inventory")
    output_dir.mkdir(parents=True, exist_ok=True)

    output_file = output_dir / "legal_inventory.json"
    output_file.write_text(json.dumps(inventory, indent=2, sort_keys=True), encoding="utf-8")
    print()
    print(f"Wrote: {output_file}")

    summary = {
        "generated_at": inventory["generated_at"],
        "source": inventory["source"],
        "description": inventory["description"],
        "categories": {
            k: {
                "count": v["count"],
                "description": v["description"],
                "reference": v.get("reference", "N/A")
            }
            for k, v in inventory["categories"].items()
        },
        "totals": inventory["totals"],
    }

    summary_file = output_dir / "legal_summary.json"
    summary_file.write_text(json.dumps(summary, indent=2, sort_keys=True), encoding="utf-8")
    print(f"Wrote: {summary_file}")


if __name__ == "__main__":
    main()
