#!/usr/bin/env python3
"""Linguistics and Corpus Metadata Field Inventory for MetaExtract.

Covers corpus linguistics, phonetics/IPA, morphology, syntax/treebanks,
semantics, speech data, and language documentation formats.
"""

from datetime import datetime, timezone
import json
from pathlib import Path


def generate_linguistics_inventory():
    """Generate comprehensive linguistics/corpus metadata field inventory."""

    INVENTORY = {
        "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "source": " corpus linguistics specifications, IPA Unicode standards, ISO 639, ELAN, Fieldworks, Universal Dependencies",
        "description": "Linguistics and corpus metadata including corpus statistics, phonetics, morphology, syntax, semantics, speech, and language documentation",
        "categories": {
            "corpus_linguistics": {
                "description": "Corpus linguistics metadata - corpus size, tokens, types, POS tags",
                "reference": "https://corpora.uni-hamburg.de, https://www.clarin.eu",
                "fields": [
                    "corpus.token_count",
                    "corpus.type_count",
                    "corpus.lemma_count",
                    "corpus.sentence_count",
                    "corpus.paragraph_count",
                    "corpus.document_count",
                    "corpus.file_count",
                    "corpus.total_bytes",
                    "corpus.total_characters",
                    "corpus.total_words",
                    "corpus.average_sentence_length",
                    "corpus.average_word_length",
                    "corpus.average_token_length",
                    "corpus.lexical_density",
                    "corpus.type_token_ratio",
                    "corpus.hapax_legomena",
                    "corpus.hapax_dislegomena",
                    "corpus.rare_word_ratio",
                    "corpus.vocabulary_richness",
                    "corpus.lexical_diversity",
                    "corpus.pos_distribution",
                    "corpus.pos_tags_present",
                    "corpus.noun_frequency",
                    "corpus.verb_frequency",
                    "corpus.adjective_frequency",
                    "corpus.adverb_frequency",
                    "corpus.pronoun_frequency",
                    "corpus.preposition_frequency",
                    "corpus.conjunction_frequency",
                    "corpus.determiner_frequency",
                    "corpus.interjection_frequency",
                    "corpus.punctuation_frequency",
                    "corpus.corpus_name",
                    "corpus.corpus_id",
                    "corpus.corpus_version",
                    "corpus.corpus_description",
                    "corpus.corpus_url",
                    "corpus.corpus_license",
                    "corpus.corpus_contact",
                    "corpus.corpus_owner",
                    "corpus.corpus_annotation_level",
                    "corpus.corpus_balanced",
                    "corpus.corpus_sampling_method",
                    "corpus.corpus_time_period",
                    "corpus.corpus_genre_coverage",
                    "corpus.corpus_domain",
                    "corpus.corpus_register",
                    "corpus.corpus_style",
                    "corpus.corpus_native_speakers",
                    "corpus.corpus_non_native_speakers",
                    "corpus.corpus_location",
                    "corpus.corpus_language",
                    "corpus.corpus_language_code",
                    "corpus.corpus_language_family",
                    "corpus.corpus_dialect_coverage",
                    "corpus.corpus_creation_date",
                    "corpus.corpus_last_updated",
                    "corpus.corpus_access_status",
                    "corpus.corpus_downloadable",
                    "corpus.corpus_size_category",
                    "corpus.corpus_text_type",
                    "corpus.corpus_mode",
                    "corpus.corpus_interaction_type",
                ],
                "count": 70,
            },
            "phonetics_ipa": {
                "description": "Phonetics and IPA metadata - IPA symbols, phoneme inventories, formants",
                "reference": "https://www.internationalphoneticassociation.org, https://unicode.org/charts/PDF/U0250.pdf",
                "fields": [
                    "ipa.symbol",
                    "ipa.unicode_value",
                    "ipa.ipa_number",
                    "ipa.xsampa",
                    "ipa.kirshenbaum",
                    "ipa.description",
                    "ipa.manner_of_articulation",
                    "ipa.place_of_articulation",
                    "ipa.phonation",
                    "ipa.vowel_height",
                    "ipa.vowel_backness",
                    "ipa.vowel_roundedness",
                    "ipa.vowel_nasalization",
                    "ipa.consonantal",
                    "ipa.syllabic",
                    "ipa.approximant",
                    "ipa.tap",
                    "ipa.trill",
                    "ipa.flap",
                    "ipa.lateral",
                    "ipa.delayed_release",
                    "ipa.affricate",
                    "ipa.fricative",
                    "ipa.plosive",
                    "ipa.nasal",
                    "ipa.glide",
                    "ipa.diphthong",
                    "ipa.triphthong",
                    "ipa.diphthong_direction",
                    "ipa.roundedness",
                    "ipa.centralization",
                    "ipa.creaky_voicing",
                    "ipa.breathy_voicing",
                    "ipa.phoneme_inventory_size",
                    "ipa.consonant_count",
                    "ipa.vowel_count",
                    "ipa.diphthong_count",
                    "ipa.tone_marks",
                    "ipa.intonation_patterns",
                    "ipa.stress_pattern",
                    "ipa.syllable_structure",
                    "ipa.max_onset",
                    "ipa.max_coda",
                    "ipa.nucleus_types",
                    "ipa.formant_f1",
                    "ipa.formant_f2",
                    "ipa.formant_f3",
                    "ipa.formant_values",
                    "ipa.f0_values",
                    "ipa.duration_values",
                    "ipa.intensity_values",
                ],
                "count": 50,
            },
            "morphology": {
                "description": "Morphology metadata - stem, affix, inflection, derivation rules",
                "reference": "https://universaldependencies.org, https://morphology.unipv.it",
                "fields": [
                    "morph.stem_type",
                    "morph.root",
                    "morph.stem",
                    "morph.affix_type",
                    "morph.prefix",
                    "morph.suffix",
                    "morph.infix",
                    "morph.circumfix",
                    "morph.interfix",
                    "morph.transfix",
                    "morph.suffixing",
                    "morph.prefixing",
                    "morph.inflection_type",
                    "morph.derivation_type",
                    "morph.compounding_type",
                    "morph.word_formation_process",
                    "morph.morpheme_count",
                    "morph.bound_morpheme",
                    "morph.free_morpheme",
                    "morph.allomorph",
                    "morph.allomorphy",
                    "morph.morphophonemic",
                    "morph.alternation",
                    "morph.reduplication",
                    "morph.full_reduplication",
                    "morph.partial_reduplication",
                    "morph.redup_type",
                    "morph.inflection_category",
                    "morph.tense",
                    "morph.aspect",
                    "morph.mood",
                    "morph.voice",
                    "morph.person",
                    "morph.number",
                    "morph.gender",
                    "morph.case",
                    "morph.degree",
                    "morph.definiteness",
                    "morph.possessor",
                    "morph.derivational_morphemes",
                    "morph.complex_word",
                    "morph.word_structure",
                    "morph.morphosyntactic_features",
                    "morph.pos_change",
                    "morph.meaning_change",
                    "morph.productiveness",
                    "morph.productivity",
                    "morph.productivity_index",
                    "morph.productivity_score",
                    "morph.gloss",
                    "morph.gloss_abbrev",
                ],
                "count": 50,
            },
            "syntax_treebanks": {
                "description": "Syntax and treebank metadata - constituency, dependency, parse trees",
                "reference": "https://universaldependencies.org, https://nlp.stanford.edu",
                "fields": [
                    "syntax.dependency_type",
                    "syntax.constituency_type",
                    "syntax.parse_tree",
                    "syntax.treebank_id",
                    "syntax.treebank_name",
                    "syntax.treebank_version",
                    "syntax.dependency_relation",
                    "syntax.dependency_head",
                    "syntax.dependency_child",
                    "syntax.dependency_label",
                    "syntax.nsubj",
                    "syntax.dobj",
                    "syntax.iobj",
                    "syntax.csubj",
                    "syntax.ccomp",
                    "syntax.xcomp",
                    "syntax.advcl",
                    "syntax.advmod",
                    "syntax.amod",
                    "syntax.appos",
                    "syntax.aux",
                    "syntax.auxpass",
                    "syntax.cop",
                    "syntax.mark",
                    "syntax.relcl",
                    "syntax.det",
                    "syntax.expl",
                    "syntax.neg",
                    "syntax.nummod",
                    "syntax.quantmod",
                    "syntax.acl",
                    "syntax.advcl",
                    "syntax.cleft",
                    "syntax.wh_movement",
                    "syntax.antecedent",
                    "syntax.anaphora",
                    "syntax.coreference",
                    "syntax.bracket_type",
                    "syntax.phrase_type",
                    "syntax.np_type",
                    "syntax.vp_type",
                    "syntax.pp_type",
                    "syntax.s_type",
                    "syntax.sbar_type",
                    "syntax.wh_phrase_type",
                    "syntax.tree_depth",
                    "syntax.branching_factor",
                    "syntax.constituent_order",
                    "syntax.word_order_type",
                    "syntax.head_direction",
                    "syntax.argument_structure",
                    "syntax.theta_roles",
                    "syntax.parsing_algorithm",
                    "syntax.parse_accuracy",
                    "syntax.parse_f1",
                    "syntax.gold_standard",
                ],
                "count": 60,
            },
            "semantics": {
                "description": "Semantics metadata - WordNet, FrameNet, sense annotations",
                "reference": "https://wordnet.princeton.edu, https://framenet.icsi.berkeley.edu",
                "fields": [
                    "sem.wordnet_id",
                    "sem.wordnet_offset",
                    "sem.wordnet_pos",
                    "sem.wordnet_synset",
                    "sem.wordnet_definition",
                    "sem.wordnet_example",
                    "sem.wordnet_hypernym",
                    "sem.wordnet_hyponym",
                    "sem.wordnet_meronym",
                    "sem.wordnet_holonym",
                    "sem.wordnet_antonym",
                    "sem.wordnet_synonym",
                    "sem.wordnet_hyponym_tree_depth",
                    "sem.wordnet_gloss",
                    "sem.wordnet_latin",
                    "sem.framenet_id",
                    "sem.framenet_name",
                    "sem.framenet_frame",
                    "sem.framenet_frame_type",
                    "sem.framenet_frame_definition",
                    "sem.framenet_frame_elements",
                    "sem.framenet_lexical_units",
                    "sem.framenet_lu_name",
                    "sem.framenet_lu_type",
                    "sem.framenet_fe_core",
                    "sem.framenet_fe_non_core",
                    "sem.sense_number",
                    "sem.sense_definition",
                    "sem.sense_example",
                    "sem.sense_usage",
                    "sem.sense_domain",
                    "sem.sense_frequency",
                    "sem.semantic_relation",
                    "sem.entailment",
                    "sem.presupposition",
                    "sem.implicature",
                    "sem.lexical_semantics",
                    "sem.compositional_semantics",
                    "sem.argument_semantics",
                    "sem.theta_semantics",
                    "sem.selectional_restrictions",
                    "sem.isa_relation",
                    "sem.has_part_relation",
                    "sem.made_of_relation",
                    "sem.used_for_relation",
                    "sem.capable_of_relation",
                    "sem.related_to_relation",
                    "sem.semantic_field",
                    "sem.ontology",
                    "sem.conceptnet_id",
                ],
                "count": 50,
            },
            "speech_data": {
                "description": "Speech data metadata - ASR transcripts, pronunciation, duration",
                "reference": "https://commonvoice.mozilla.org, https://librivox.org",
                "fields": [
                    "speech.transcript",
                    "speech.transcript_id",
                    "speech.transcript_type",
                    "speech.transcript_language",
                    "speech.transcript_quality",
                    "speech.word_alignment",
                    "speech.phoneme_alignment",
                    "speech.alignment_method",
                    "speech.pronunciation",
                    "speech.pronunciation_variant",
                    "speech.phonetic_transcription",
                    "speech.phonemic_transcription",
                    "speech.orthographic_transcription",
                    "speech.duration_ms",
                    "speech.duration_seconds",
                    "speech.segment_duration",
                    "speech.silence_duration",
                    "speech.speech_rate",
                    "speech.speaking_rate",
                    "speech.articulation_rate",
                    "speech.pause_count",
                    "speech.pause_frequency",
                    "speech.asr_model",
                    "speech.asr_confidence",
                    "speech.asr_timestamp",
                    "speech.asr_word_confidence",
                    "speech.asr_wer",
                    "speech.asr_cer",
                    "speech.wav_file",
                    "speech.sample_rate",
                    "speech.bit_depth",
                    "speech.channels",
                    "speech.audio_format",
                    "speech.audio_codec",
                    "speech.bitrate",
                    "speech.recording_quality",
                    "speech.noise_level",
                    "speech.signal_to_noise_ratio",
                    "speech.speaker_id",
                    "speech.speaker_count",
                    "speech.speaker_gender",
                    "speech.speaker_age",
                    "speech.speaker_dialect",
                    "speech.speaker_accent",
                    "speech.session_id",
                    "speech.recording_date",
                    "speech.recording_location",
                    "speech.recording_device",
                    "speech.microphone_type",
                    "speech.environment_type",
                    "speech.overlap_speech",
                    "speech.disfluency",
                    "speech.repetition",
                    "speech.repair",
                    "speech.filled_pause",
                    "speech.intonation_pattern",
                    "speech.pitch_range",
                    "speech.loudness",
                ],
                "count": 60,
            },
            "language_documentation": {
                "description": "Language documentation metadata - ELAN, Fieldworks, metadata schema",
                "reference": "https://archive.mpi.nl/tla/ELAN, https://www.fieldworks.org",
                "fields": [
                    "elan.tier_id",
                    "elan.tier_type",
                    "elan.tier_linguistic_type",
                    "elan.tier_parent",
                    "elan.annotation_id",
                    "elan.annotation_type",
                    "elan.annotation_value",
                    "elan.annotation_begin",
                    "elan.annotation_end",
                    "elan.annotation_duration",
                    "elan.ControlledVocabulary",
                    "elan.LinguisticType",
                    "elan.LexiconRef",
                    "elan.TimeSlot",
                    "elan.TimeSlot_type",
                    "elan.TimeOrder",
                    "elan.Locale",
                    "elan.Header",
                    "elan.MediaDescriptor",
                    "elan.MediaDescriptor_media_url",
                    "elan.MediaDescriptor_mime_type",
                    "elan.MediaDescriptor_rel_path",
                    "elan.Project",
                    "elan.Project_name",
                    "elan.Project_id",
                    "elan.Project_version",
                    "fieldworks.project",
                    "fieldworks.project_id",
                    "fieldworks.lexicon_entry",
                    "fieldworks.lexeme",
                    "fieldworks.morphology",
                    "fieldworks.phonology",
                    "fieldworks.semantics",
                    "fieldworks.examples",
                    "fieldworks.citations",
                    "fieldworks.environmental_context",
                    "fieldworks.elicitation_method",
                    "fieldworks.speaker_profile",
                    "fieldworks.session_metadata",
                    "fieldworks.collection_method",
                    "fieldworks.workflow_status",
                    "fieldworks.validation_status",
                    "fieldworks.interlinear_gloss",
                    "fieldworks.gloss_abbrev",
                    "fieldworks.analysis_language",
                    "fieldworks.translation_language",
                    "fieldworks.source_language",
                    "fieldworks.target_language",
                    "meta.language_code",
                    "meta.language_name",
                    "meta.language_family",
                    "meta.language_genus",
                    "meta.language_status",
                    "meta.cultural_context",
                    "meta.geographic_location",
                    "meta.recording_date",
                    "meta.recorder",
                    "meta.elicitor",
                    "meta.date_elicited",
                    "meta.speaker_consent",
                    "meta.copyright",
                    "meta.access_restrictions",
                    "meta.metadata_schema",
                    "meta.metadata_standard",
                    "meta.iso639",
                    "meta.iso639_1",
                    "meta.iso639_3",
                    "meta.glottocode",
                ],
                "count": 60,
            },
        },
        "totals": {
            "categories": 7,
            "total_fields": 400,
        }
    }

    return INVENTORY


def main():
    print("=" * 70)
    print("LINGUISTICS AND CORPUS METADATA FIELD INVENTORY")
    print("=" * 70)
    print()

    inventory = generate_linguistics_inventory()

    print(f"Generated: {inventory['generated_at']}")
    print(f"Categories: {inventory['totals']['categories']}")
    print(f"Total Fields: {inventory['totals']['total_fields']}")
    print()

    print("FIELD COUNTS BY CATEGORY:")
    print("-" * 50)
    for cat_name, cat_data in sorted(inventory['categories'].items(), key=lambda x: x[1]['count'], reverse=True):
        print(f"  {cat_name:35s}: {cat_data['count']:>4} fields")

    output_dir = Path("dist/linguistics_inventory")
    output_dir.mkdir(parents=True, exist_ok=True)

    output_file = output_dir / "linguistics_inventory.json"
    output_file.write_text(json.dumps(inventory, indent=2, sort_keys=True), encoding="utf-8")
    print()
    print(f"Wrote: {output_file}")

    summary = {
        "generated_at": inventory["generated_at"],
        "description": inventory["description"],
        "categories": {k: {"count": v["count"], "description": v["description"]} for k, v in inventory["categories"].items()},
        "totals": inventory["totals"],
    }

    summary_file = output_dir / "linguistics_summary.json"
    summary_file.write_text(json.dumps(summary, indent=2, sort_keys=True), encoding="utf-8")
    print(f"Wrote: {summary_file}")


if __name__ == "__main__":
    main()
