#!/usr/bin/env python3
"""Advanced GIS Format Metadata Field Inventory for MetaExtract.

Covers GeoJSON, KML, GPX, MapInfo, WKT, and other GIS format metadata fields.
"""

from datetime import datetime, timezone
from pathlib import Path


def generate_gis_advanced_inventory():
    """Generate comprehensive advanced GIS format metadata field inventory."""

    INVENTORY = {
        "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "source": "RFC 7946 (GeoJSON), OGC KML 2.3, GPX 1.1, WKT, MapInfo, OGC standards",
        "description": "Advanced GIS format metadata including GeoJSON, KML, GPX, WKT, MapInfo, and spatial reference systems",
        "categories": {
            "geojson_rfc7946": {
                "description": "GeoJSON (RFC 7946) specification fields",
                "reference": "https://tools.ietf.org/html/rfc7946",
                "fields": [
                    "geojson.type",
                    "geojson.bbox",
                    "geojson.crs",
                    "geojson.crs.type",
                    "geojson.crs.properties",
                    "geojson.crs.properties.name",
                    "geojson.Feature",
                    "geojson.Feature.type",
                    "geojson.Feature.geometry",
                    "geojson.Feature.properties",
                    "geojson.Feature.id",
                    "geojson.Feature.bbox",
                    "geojson.FeatureCollection",
                    "geojson.FeatureCollection.type",
                    "geojson.FeatureCollection.features",
                    "geojson.FeatureCollection.bbox",
                    "geojson.FeatureCollection.crs",
                    "geojson.GeometryCollection",
                    "geojson.GeometryCollection.type",
                    "geojson.GeometryCollection.geometries",
                    "geojson.Point",
                    "geojson.Point.type",
                    "geojson.Point.coordinates",
                    "geojson.MultiPoint",
                    "geojson.MultiPoint.type",
                    "geojson.MultiPoint.coordinates",
                    "geojson.LineString",
                    "geojson.LineString.type",
                    "geojson.LineString.coordinates",
                    "geojson.MultiLineString",
                    "geojson.MultiLineString.type",
                    "geojson.MultiLineString.coordinates",
                    "geojson.Polygon",
                    "geojson.Polygon.type",
                    "geojson.Polygon.coordinates",
                    "geojson.Polygon.coordinates.exteriorRing",
                    "geojson.Polygon.coordinates.interiorRings",
                    "geojson.MultiPolygon",
                    "geojson.MultiPolygon.type",
                    "geojson.MultiPolygon.coordinates",
                    "geojson.coordinates",
                    "geojson.coordinates.longitude",
                    "geojson.coordinates.latitude",
                    "geojson.coordinates.altitude",
                    "geojson.properties",
                    "geojson.XMP_metadata",
                    "geojson.jsonld_context",
                    "geojson.foreignMembers",
                ],
                "count": 44,
            },
            "kml_ogc": {
                "description": "KML (OGC KML 2.3) specification fields",
                "reference": "https://www.ogc.org/standards/kml",
                "fields": [
                    "kml.Document",
                    "kml.Document.name",
                    "kml.Document.description",
                    "kml.Document.visibility",
                    "kml.Document.open",
                    "kml.Document.address",
                    "kml.Document.phoneNumber",
                    "kml.Document.snippet",
                    "kml.Document.snippet.content",
                    "kml.Document.styleUrl",
                    "kml.Document.styles",
                    "kml.Document.styleMap",
                    "kml.Document.Style",
                    "kml.Document.IconStyle",
                    "kml.Document.IconStyle.color",
                    "kml.Document.IconStyle.colorMode",
                    "kml.Document.IconStyle.scale",
                    "kml.Document.IconStyle.heading",
                    "kml.Document.IconStyle.icon",
                    "kml.Document.IconStyle.icon.href",
                    "kml.Document.IconStyle.hotSpot",
                    "kml.Document.LabelStyle",
                    "kml.Document.LabelStyle.color",
                    "kml.Document.LabelStyle.colorMode",
                    "kml.Document.LabelStyle.scale",
                    "kml.Document.LineStyle",
                    "kml.Document.LineStyle.color",
                    "kml.Document.LineStyle.colorMode",
                    "kml.Document.LineStyle.width",
                    "kml.Document.PolygonStyle",
                    "kml.Document.PolygonStyle.color",
                    "kml.Document.PolygonStyle.colorMode",
                    "kml.Document.PolygonStyle.fill",
                    "kml.Document.PolygonStyle.outline",
                    "kml.Document.BalloonStyle",
                    "kml.Document.BalloonStyle.text",
                    "kml.Document.BalloonStyle.bgColor",
                    "kml.Document.BalloonStyle.textColor",
                    "kml.Folder",
                    "kml.Folder.name",
                    "kml.Folder.description",
                    "kml.Folder.visibility",
                    "kml.Placemark",
                    "kml.Placemark.name",
                    "kml.Placemark.description",
                    "kml.Placemark.Point",
                    "kml.Placemark.Point.coordinates",
                    "kml.Placemark.LineString",
                    "kml.Placemark.LineString.coordinates",
                    "kml.Placemark.Polygon",
                    "kml.Placemark.Polygon.outerBoundaryIs",
                    "kml.Placemark.Polygon.innerBoundaryIs",
                    "kml.Placemark.LinearRing",
                    "kml.Placemark.LinearRing.coordinates",
                    "kml.Placemark.MultiGeometry",
                    "kml.Placemark.Model",
                    "kml.Placemark.Model.location",
                    "kml.Placemark.Model.orientation",
                    "kml.Placemark.Model.scale",
                    "kml.Placemark.Model.Link",
                    "kml.Placemark.Model.resourceMap",
                    "kml.Placemark.NetworkLink",
                    "kml.Placemark.NetworkLink.Link",
                    "kml.Placemark.NetworkLink.Link.href",
                    "kml.Placemark.NetworkLink.refreshMode",
                    "kml.Placemark.NetworkLink.viewRefreshMode",
                    "kml.Placemark.TimeSpan",
                    "kml.Placemark.TimeSpan.begin",
                    "kml.Placemark.TimeSpan.end",
                    "kml.Placemark.TimeStamp",
                    "kml.Placemark.TimeStamp.when",
                    "kml.Placemark.ExtendedData",
                    "kml.Placemark.ExtendedData.SchemaData",
                    "kml.Placemark.ExtendedData.SimpleData",
                    "kml.Placemark.Region",
                    "kml.Placemark.Region.LatLonAltBox",
                    "kml.Placemark.Region.LatLonAltBox.north",
                    "kml.Placemark.Region.LatLonAltBox.south",
                    "kml.Placemark.Region.LatLonAltBox.east",
                    "kml.Placemark.Region.LatLonAltBox.west",
                    "kml.Placemark.Region.LatLonAltBox.minAltitude",
                    "kml.Placemark.Region.LatLonAltBox.maxAltitude",
                    "kml.Placemark.Region.Lod",
                    "kml.Placemark.Region.Lod.minLodPixels",
                    "kml.Placemark.Region.Lod.maxLodPixels",
                    "kml.Placemark.Region.Lod.minFadeExtent",
                    "kml.Placemark.Region.Lod.maxFadeExtent",
                    "kml.GroundOverlay",
                    "kml.GroundOverlay.altitude",
                    "kml.GroundOverlay.altitudeMode",
                    "kml.GroundOverlay.latLonBox",
                    "kml.GroundOverlay.icon",
                    "kml.ScreenOverlay",
                    "kml.ScreenOverlay.overlayXY",
                    "kml.ScreenOverlay.screenXY",
                    "kml.ScreenOverlay.rotationXY",
                    "kml.ScreenOverlay.size",
                    "kml.ScreenOverlay.rotation",
                    "kml.PhotoOverlay",
                    "kml.PhotoOverlay.shape",
                    "kml.PhotoOverlay.viewVolume",
                    "kml.PhotoOverlay.ImagePyramid",
                    "kml.NetworkLinkControl",
                    "kml.NetworkLinkControl.minRefreshPeriod",
                    "kml.NetworkLinkControl.maxSessionLength",
                    "kml.NetworkLinkControl.cookie",
                    "kml.NetworkLinkControl.message",
                    "kml.NetworkLinkControl.linkName",
                    "kml.NetworkLinkControl.linkDescription",
                    "kml.NetworkLinkControl.expires",
                    "kml.NetworkLinkControl.update",
                    "kml.NetworkLinkControl.create",
                    "kml.NetworkLinkControl.delete",
                    "kml.Schema",
                    "kml.Schema.name",
                    "kml.Schema.id",
                    "kml.Schema.SimpleField",
                    "kml.Schema.SimpleField.name",
                    "kml.Schema.SimpleField.type",
                    "kml.Schema.SimpleField.displayName",
                    "kml.atom:author",
                    "kml.atom:author.name",
                    "kml.atom:author.uri",
                    "kml.atom:link",
                    "kml.atom:link.href",
                    "kml.xal:AddressDetails",
                ],
                "count": 142,
            },
            "gpx_format": {
                "description": "GPX 1.1 format fields",
                "reference": "https://www.topografix.com/gpx.asp",
                "fields": [
                    "gpx.version",
                    "gpx.creator",
                    "gpx.metadata.name",
                    "gpx.metadata.desc",
                    "gpx.metadata.author",
                    "gpx.metadata.author.name",
                    "gpx.metadata.author.email",
                    "gpx.metadata.author.email.id",
                    "gpx.metadata.author.email.domain",
                    "gpx.metadata.author.link",
                    "gpx.metadata.author.link.href",
                    "gpx.metadata.author.link.text",
                    "gpx.metadata.author.link.type",
                    "gpx.metadata.copyright",
                    "gpx.metadata.copyright.year",
                    "gpx.metadata.copyright.license",
                    "gpx.metadata.link",
                    "gpx.metadata.link.href",
                    "gpx.metadata.link.text",
                    "gpx.metadata.link.type",
                    "gpx.metadata.time",
                    "gpx.metadata.keywords",
                    "gpx.metadata.bounds",
                    "gpx.metadata.bounds.minlat",
                    "gpx.metadata.bounds.maxlat",
                    "gpx.metadata.bounds.minlon",
                    "gpx.metadata.bounds.maxlon",
                    "gpx.metadata.extensions",
                    "gpx.wpt",
                    "gpx.wpt.lat",
                    "gpx.wpt.lon",
                    "gpx.wpt.ele",
                    "gpx.wpt.time",
                    "gpx.wpt.magvar",
                    "gpx.wpt.geoidheight",
                    "gpx.wpt.name",
                    "gpx.wpt.cmt",
                    "gpx.wpt.desc",
                    "gpx.wpt.src",
                    "gpx.wpt.link",
                    "gpx.wpt.sym",
                    "gpx.wpt.type",
                    "gpx.wpt.fix",
                    "gpx.wpt.sat",
                    "gpx.wpt.hdop",
                    "gpx.wpt.vdop",
                    "gpx.wpt.pdop",
                    "gpx.wpt.ageofdgpsdata",
                    "gpx.wpt.dgpsid",
                    "gpx.wpt.extensions",
                    "gpx.rte",
                    "gpx.rte.name",
                    "gpx.rte.cmt",
                    "gpx.rte.desc",
                    "gpx.rte.src",
                    "gpx.rte.number",
                    "gpx.rte.link",
                    "gpx.rte.type",
                    "gpx.rte.extensions",
                    "gpx.rte.rtept",
                    "gpx.rte.rtept.lat",
                    "gpx.rte.rtept.lon",
                    "gpx.rte.rtept.ele",
                    "gpx.rte.rtept.time",
                    "gpx.trk",
                    "gpx.trk.name",
                    "gpx.trk.cmt",
                    "gpx.trk.desc",
                    "gpx.trk.src",
                    "gpx.trk.number",
                    "gpx.trk.type",
                    "gpx.trk.link",
                    "gpx.trk.extensions",
                    "gpx.trk.trkseg",
                    "gpx.trk.trkseg.trkpt",
                    "gpx.trk.trkseg.trkpt.lat",
                    "gpx.trk.trkseg.trkpt.lon",
                    "gpx.trk.trkseg.trkpt.ele",
                    "gpx.trk.trkseg.trkpt.time",
                    "gpx.trk.trkseg.trkpt.extensions",
                    "gpx.extensions",
                    "gpx.extensions.gpxdata",
                    "gpx.extensions.gpxdata.temperature",
                    "gpx.extensions.gpxdata.temperature",
                    "gpx.extensions.gpxdata.cadence",
                    "gpx.extensions.gpxdata.heartrate",
                    "gpx.extensions.gpxdata.power",
                    "gpx.extensions.gpxdata.speed",
                    "gpx.extensions.gpxdata.course",
                    "gpx.extensions.gpxdata.vert_speed",
                    "gpx.extensions.garmin",
                    "gpx.extensions.garmin.waypoint",
                    "gpx.extensions.garmin.Track",
                    "gpx.extensions.garmin.Extensions",
                    "gpx.extensions.garmin.Extensions.Run",
                    "gpx.extensions.garmin.Extensions.Bike",
                    "gpx.extensions.garmin.Extensions.Swim",
                    "gpx.extensions.garmin.Extensions.Dive",
                    "gpx.extensions.garmin.Extensions.Turn",
                    "gpx.extensions.garmin.Extensions.TrackPointExtensions",
                    "gpx.extensions.garmin.TrackPointExtensions.atemp",
                    "gpx.extensions.garmin.TrackPointExtensions.wtemp",
                    "gpx.extensions.garmin.TrackPointExtensions.depth",
                    "gpx.extensions.garmin.TrackPointExtensions.cadence",
                    "gpx.extensions.garmin.TrackPointExtensions.distance",
                    "gpx.extensions.garmin.TrackPointExtensions.heartrate",
                    "gpx.extensions.garmin.TrackPointExtensions.power",
                    "gpx.extensions.garmin.TrackPointExtensions.speed",
                    "gpx.extensions.garmin.TrackPointExtensions.sats",
                    "gpx.extensions.garmin.TrackPointExtensions.snr",
                    "gpx.extensions.garmin.TrackPointExtensions.longitude",
                    "gpx.extensions.garmin.TrackPointExtensions.latitude",
                    "gpx.extensions.garmin.TrackPointExtensions.height",
                    "gpx.extensions.garmin.TrackPointExtensions.dGPSid",
                ],
                "count": 132,
            },
            "wkt_spatial_ref": {
                "description": "WKT (Well-Known Text) and Spatial Reference fields",
                "reference": "OGC 12-063r5",
                "fields": [
                    "wkt.SPATIAL_REF_SYSTEM",
                    "wkt.SRS_NAME",
                    "wkt.SRS_ID",
                    "wkt.DEFINITION",
                    "wkt.DATUM",
                    "wkt.DATUM_NAME",
                    "wkt.DATUM_SPHEROID",
                    "wkt.SPHEROID_NAME",
                    "wkt.SPHEROID_SEMI_MAJOR_AXIS",
                    "wkt.SPHEROID_INVERSE_FLATTENING",
                    "wkt.PRIME_MERIDIAN",
                    "wkt.PRIME_MERIDIAN_NAME",
                    "wkt.PRIME_MERIDIAN_GREENWICH_LONGITUDE",
                    "wkt.UNIT",
                    "wkt.UNIT_NAME",
                    "wkt.UNIT_CONVERSION_FACTOR",
                    "wkt.UNIT_ANGLE",
                    "wkt.COORDINATE_OPERATION",
                    "wkt.COORDINATE_OPERATION_NAME",
                    "wkt.COORDINATE_OPERATION_METHOD",
                    "wkt.COORDINATE_OPERATION_PARAMETERS",
                    "wkt.GEOGCS",
                    "wkt.GEOGCS.name",
                    "wkt.GEOGCS.datum",
                    "wkt.GEOGCS.spheroid",
                    "wkt.GEOGCS.primem",
                    "wkt.GEOGCS.unit",
                    "wkt.GEOGCS.authority",
                    "wkt.PROJCS",
                    "wkt.PROJCS.name",
                    "wkt.PROJCS.geogcs",
                    "wkt.PROJCS.projection",
                    "wkt.PROJCS.parameters",
                    "wkt.PROJCS.unit",
                    "wkt.PROJCS.authority",
                    "wkt.COMPD_CS",
                    "wkt.COMPD_CS.name",
                    "wkt.COMPD_CS.head",
                    "wkt.COMPD_CS.tail",
                    "wkt.COMPD_CS.authority",
                    "wkt.PROJECTION",
                    "wkt.PROJECTION.Transverse_Mercator",
                    "wkt.PROJECTION.Lambert_Conformal_Conic",
                    "wkt.PROJECTION.Albers_Equal_Area",
                    "wkt.PROJECTION.Azimuthal_Equidistant",
                    "wkt.PROJECTION.Stereographic",
                    "wkt.PROJECTION.Orthographic",
                    "wkt.PROJECTION.Vertical_Near_Side_Perspective",
                    "wkt.PROJECTION.Equirectangular",
                    "wkt.PROJECTION.Cassini_Soldner",
                    "wkt.PROJECTION.Polyconic",
                    "wkt.PROJECTION.Robinson",
                    "wkt.PROJECTION.Sinusoidal",
                    "wkt.PROJECTION.Van_der_Grinten",
                    "wkt.PROJECTION.Mercator",
                    "wkt.PROJECTION.Lambert_Azimuthal_Equal_Area",
                    "wkt.PROJECTION.Oblique_Mercator",
                    "wkt.PROJECTION.Oblique_Stereographic",
                    "wkt.PROJECTION.Double_Stereographic",
                    "wkt.PROJECTION.Hotine_Oblique_Mercator",
                    "wkt.ParameterID",
                    "wkt.ParameterID.Name",
                    "wkt.ParameterID.Value",
                    "wkt.Authority",
                    "wkt.Authority.Code",
                    "wkt.Authority.Name",
                    "wkt.Authority.Alias",
                    "wkt.Authority.Abbreviation",
                    "wkt.Authority.Keywords",
                ],
                "count": 62,
            },
            "mapinfo_tab": {
                "description": "MapInfo TAB format fields",
                "reference": "MapInfo TAB Format Specification",
                "fields": [
                    "mapinfo.version",
                    "mapinfo.charset",
                    "mapinfo.units",
                    "mapinfo.projection",
                    "mapinfo.extents",
                    "mapinfo.extents.minx",
                    "mapinfo.extents.miny",
                    "mapinfo.extents.maxx",
                    "mapinfo.extents.maxy",
                    "mapinfo.symbol",
                    "mapinfo.symbol.shape",
                    "mapinfo.symbol.size",
                    "mapinfo.symbol.color",
                    "mapinfo.symbol.font",
                    "mapinfo.symbol.font_name",
                    "mapinfo.symbol.font_style",
                    "mapinfo.symbol.point",
                    "mapinfo.symbol.point.code",
                    "mapinfo.line",
                    "mapinfo.line.color",
                    "mapinfo.line.pattern",
                    "mapinfo.line.width",
                    "mapinfo.pen",
                    "mapinfo.pen.color",
                    "mapinfo.pen.pattern",
                    "mapinfo.pen.width",
                    "mapinfo.brush",
                    "mapinfo.brush.forecolor",
                    "mapinfo.brush.backcolor",
                    "mapinfo.brush.pattern",
                    "mapinfo.brush.transparent",
                    "mapinfo.font",
                    "mapinfo.font.name",
                    "mapinfo.font.size",
                    "mapinfo.font.style",
                    "mapinfo.font.color",
                    "mapinfo.font.background",
                    "mapinfo.label",
                    "mapinfo.label.field",
                    "mapinfo.label.font",
                    "mapinfo.label.position",
                    "mapinfo.label.line",
                    "mapinfo.label.parallel",
                    "mapinfo.label.offset",
                    "mapinfo.label.angle",
                    "mapinfo.label.auto",
                    "mapinfo.label.partials",
                    "mapinfo.label.background",
                    "mapinfo.table.name",
                    "mapinfo.table.type",
                    "mapinfo.table.columns",
                    "mapinfo.table.columns.name",
                    "mapinfo.table.columns.type",
                    "mapinfo.table.columns.width",
                    "mapinfo.table.columns.indexed",
                    "mapinfo.table.columns.unique",
                    "mapinfo.table.index",
                    "mapinfo.table.index.name",
                    "mapinfo.table.index.type",
                    "mapinfo.table.index.columns",
                    "mapinfo.table.ndx",
                    "mapinfo.table.id",
                    "mapinfo.table.n_rows",
                    "mapinfo.table.n_cols",
                    "mapinfo.table.coord_sys",
                    "mapinfo.table.n_tabs",
                    "mapinfo.table.tab",
                    "mapinfo.table.tab.name",
                    "mapinfo.table.tab.type",
                    "mapinfo.mif.header",
                    "mapinfo.mif.version",
                    "mapinfo.mif.charset",
                    "mapinfo.mif.delimiter",
                    "mapinfo.mif.units",
                    "mapinfo.mif.projection",
                    "mapinfo.mif.extents",
                    "mapinfo.mif.columns",
                    "mapinfo.mif.data",
                    "mapinfo.mif.point",
                    "mapinfo.mif.line",
                    "mapinfo.mif.pline",
                    "mapinfo.mif.region",
                    "mapinfo.mif.text",
                    "mapinfo.mif.rect",
                    "mapinfo.mif.ellipse",
                    "mapinfo.mif.arc",
                    "mapinfo.mif.multipoint",
                    "mapinfo.mif.collection",
                    "mapinfo.mif.mid",
                    "mapinfo.mid.delimiter",
                    "mapinfo.mid.charset",
                    "mapinfo.mid.coordsys",
                    "mapinfo.mid.preamble",
                ],
                "count": 92,
            },
            "shapefile_dbf": {
                "description": "ESRI Shapefile and DBF fields",
                "reference": "ESRI Shapefile Technical Specification",
                "fields": [
                    "shp.shape_type",
                    "shp.shape_type.Null",
                    "shp.shape_type.Point",
                    "shp.shape_type.PolyLine",
                    "shp.shape_type.Polygon",
                    "shp.shape_type.MultiPoint",
                    "shp.shape_type.PointZ",
                    "shp.shape_type.PolyLineZ",
                    "shp.shape_type.PolygonZ",
                    "shp.shape_type.MultiPointZ",
                    "shp.shape_type.PointM",
                    "shp.shape_type.PolyLineM",
                    "shp.shape_type.PolygonM",
                    "shp.shape_type.MultiPointM",
                    "shp.shape_type.MultiPatch",
                    "shp.bounding_box",
                    "shp.bounding_box.xmin",
                    "shp.bounding_box.ymin",
                    "shp.bounding_box.xmax",
                    "shp.bounding_box.ymax",
                    "shp.bounding_box.zmin",
                    "shp.bounding_box.zmax",
                    "shp.bounding_box.mmin",
                    "shp.bounding_box.mmax",
                    "shp.record.number",
                    "shp.record.length",
                    "shp.parts",
                    "shp.parts.index",
                    "shp.parts.count",
                    "shp.points",
                    "shp.points.x",
                    "shp.points.y",
                    "shp.points.z",
                    "shp.points.m",
                    "dbf.version",
                    "dbf.last_update",
                    "dbf.n_records",
                    "dbf.n_columns",
                    "dbf.record_length",
                    "dbf.header_length",
                    "dbf.field.name",
                    "dbf.field.type",
                    "dbf.field.length",
                    "dbf.field.decimal_count",
                    "dbf.field.work_area_id",
                    "dbf.field.example",
                    "dbf.field.flags",
                    "dbf.field.autoincrement",
                    "dbf.autoincrement.next_value",
                    "dbf.autoincrement.step",
                    "dbf.memo_file",
                    "dbf.memo.block_size",
                    "dbf.index_file",
                    "dbf.language_driver",
                    "dbf.null_flags",
                    "dbf.encryption",
                    "dbf.mdx",
                    "dbf.relationship",
                    "dbf.field.type.C",
                    "dbf.field.type.N",
                    "dbf.field.type.F",
                    "dbf.field.type.D",
                    "dbf.field.type.L",
                    "dbf.field.type.M",
                    "dbf.field.type.B",
                    "dbf.field.type.I",
                    "dbf.field.type.O",
                    "dbf.field.type.V",
                    "dbf.field.type.@",
                    "dbf.field.type.+",
                    "dbf.records.deleted",
                    "dbf.records.data",
                    "prj.projection",
                    "prj.spheroid",
                    "prj.prime_meridian",
                    "prj.linear_unit",
                    "prj.angular_unit",
                    "prj.GEOGCS",
                    "prj.PROJCS",
                    "prj.authority",
                    "prj.code",
                    "qix.index",
                    "qix.branch",
                    "qix.node",
                    "qix.bounding_box",
                ],
                "count": 96,
            },
            "geotiff": {
                "description": "GeoTIFF format fields",
                "reference": "GeoTIFF Specification 1.8.2",
                "fields": [
                    "geotiff.Tag",
                    "geotiff.Tag.ASCII",
                    "geotiff.Tag.SHORT",
                    "geotiff.Tag.LONG",
                    "geotiff.Tag.RATIONAL",
                    "geotiff.Tag.SBYTE",
                    "geotiff.Tag.BYTE",
                    "geotiff.Tag.SSHORT",
                    "geotiff.Tag.SLONG",
                    "geotiff.Tag.FLOAT",
                    "geotiff.Tag.DOUBLE",
                    "geotiff.ModelPixelScaleTag",
                    "geotiff.ModelPixelScaleX",
                    "geotiff.ModelPixelScaleY",
                    "geotiff.ModelPixelScaleZ",
                    "geotiff.ModelTiepointTag",
                    "geotiff.ModelTiepointI",
                    "geotiff.ModelTiepointJ",
                    "geotiff.ModelTiepointK",
                    "geotiff.ModelTiepointX",
                    "geotiff.ModelTiepointY",
                    "geotiff.ModelTiepointZ",
                    "geotiff.ModelTransformationTag",
                    "geotiff.ModelTransformationM",
                    "geotiff.GTIFFag.ModelPixelScale",
                    "geotiff.GTIFFag.ModelTiepoints",
                    "geotiff.GTIFFag.ModelTransform",
                    "geotiff.GTIFFag.IntergraphMatrix",
                    "geotiff.GTIFFag.JPEG_Quality",
                    "geotiff.GTIFFag.JPEG_Proc",
                    "geotiff.GTIFFag.YCbCrCoefficients",
                    "geotiff.GTIFFag.YCbCrSubSampling",
                    "geotiff.GTIFFag.YCbCrPositioning",
                    "geotiff.GTIFFag.ReferencePoint",
                    "geotiff.GTIFFag.XMP",
                    "geotiff.GTIFFag.Rating",
                    "geotiff.GTIFFag.Copyright",
                    "geotiff.GTIFFag.ImageDescription",
                    "geotiff.GTIFFag.Software",
                    "geotiff.GTIFFag.DateTime",
                    "geotiff.GTIFFag.Artist",
                    "geotiff.GTIFFag.HostComputer",
                    "geotiff.GTIFFag.Instruction",
                    "geotiff.GTIFFag.CFTag4648",
                    "geotiff.GDAL_NODATA",
                    "geotiff.GDAL_DATA_TYPE",
                    "geotiff.GDAL_SCALE",
                    "geotiff.GDAL_OFFSET",
                    "geotiff.GDAL_SRS_DATA",
                    "geotiff.GDAL_MD",
                    "geotiff.GDAL_PAM_UUID",
                    "geotiff.GDAL_PAM_FLAG",
                    "geotiff.GTIFF_REP_BANDSTATS",
                    "geotiff.GTIFF_RS",
                    "geotiff.GDAL_METADATA",
                    "geotiff.GDAL_NODATA_MASK",
                    "geotiff.GTIFF_ORG",
                    "geotiff.GTIFF_VERSION",
                    "geotiff.GTIFF_REVISION",
                    "geotiff.GTIFF_HISTORY",
                    "geotiff.GTIFF_GEOKEYONDS",
                    "geotiff.ModelType",
                    "geotiff.ModelType.Projected",
                    "geotiff.ModelType.Geographic",
                    "geotiff.ModelType.Vertical",
                    "geotiff.RasterType",
                    "geotiff.RasterType.Pixel",
                    "geotiff.RasterType.Area",
                    "geotiff.CT_GeoKeys",
                    "geotiff.CT_GeoKey_1.0",
                    "geotiff.GTModelTypeGeoKey",
                    "geotiff.GTRasterTypeGeoKey",
                    "geotiff.GTCitationGeoKey",
                    "geotiff.GeographicTypeGeoKey",
                    "geotiff.GeogCitationGeoKey",
                    "geotiff.GeogAngularUnitsGeoKey",
                    "geotiff.GeogAngularUnitSizeGeoKey",
                    "geotiff.Ellipsoid",
                    "geotiff.Ellipsoid.SemiMajorAxis",
                    "geotiff.Ellipsoid.SemiMinorAxis",
                    "geotiff.Ellipsoid.InverseFlattening",
                    "geotiff.PrimeMeridian",
                    "geotiff.PrimeMeridian.Longitude",
                    "geotiff.ProjectedCSTypeGeoKey",
                    "geotiff.PCSCode",
                    "geotiff.PCSName",
                    "geotiff.PCSEnumeration",
                    "geotiff.PCSCitationGeoKey",
                    "geotiff.ProjectionGeoKey",
                    "geotiff.ProjectionEnumeration",
                    "geotiff.ProjectionMethod",
                    "geotiff.ProjMethod",
                    "geotiff.ProjectionCoordTrans",
                    "geotiff.ProjCoordTrans_NatAuth",
                    "geotiff.ProjCoordTrans_CODE",
                    "geotiff.ProjectionParm",
                    "geotiff.ProjectionParm_ID",
                    "geotiff.ProjectionParm.Value",
                    "geotiff.VerticalCSTypeGeoKey",
                    "geotiff.VerticalDatum",
                    "geotiff.VerticalUnitsGeoKey",
                ],
                "count": 116,
            },
            "osm_xml": {
                "description": "OSM (OpenStreetMap) XML format fields",
                "reference": "https://wiki.openstreetmap.org/wiki/OSM_XML",
                "fields": [
                    "osm.version",
                    "osm.generator",
                    "osm.upload",
                    "osm.upload.version",
                    "osm.bounds",
                    "osm.bounds.minlat",
                    "osm.bounds.minlon",
                    "osm.bounds.maxlat",
                    "osm.bounds.maxlon",
                    "osm.node",
                    "osm.node.id",
                    "osm.node.lat",
                    "osm.node.lon",
                    "osm.node.version",
                    "osm.node.timestamp",
                    "osm.node.changeset",
                    "osm.node.uid",
                    "osm.node.user",
                    "osm.node.visible",
                    "osm.node.tags",
                    "osm.node.tag.k",
                    "osm.node.tag.v",
                    "osm.way",
                    "osm.way.id",
                    "osm.way.version",
                    "osm.way.timestamp",
                    "osm.way.changeset",
                    "osm.way.uid",
                    "osm.way.user",
                    "osm.way.visible",
                    "osm.way.nd",
                    "osm.way.nd.ref",
                    "osm.way.tags",
                    "osm.way.tag.k",
                    "osm.way.tag.v",
                    "osm.relation",
                    "osm.relation.id",
                    "osm.relation.version",
                    "osm.relation.timestamp",
                    "osm.relation.changeset",
                    "osm.relation.uid",
                    "osm.relation.user",
                    "osm.relation.visible",
                    "osm.relation.member",
                    "osm.relation.member.type",
                    "osm.relation.member.ref",
                    "osm.relation.member.role",
                    "osm.relation.tags",
                    "osm.relation.tag.k",
                    "osm.relation.tag.v",
                    "osm.changeset",
                    "osm.changeset.id",
                    "osm.changeset.created_at",
                    "osm.changeset.closed_at",
                    "osm.changeset.open",
                    "osm.changeset.user",
                    "osm.changeset.uid",
                    "osm.changeset.changes_count",
                    "osm.changeset.comments_count",
                    "osm.changeset.tags",
                    "osm.changeset.tag.k",
                    "osm.changeset.tag.v",
                    "osm.changeset.discussion",
                    "osm.changeset.discussion.text",
                    "osm.changeset.discussion.action",
                    "osm.changeset.discussion.date",
                    "osm.changeset.discussion.uid",
                    "osm.changeset.discussion.user",
                    "osm.osmchange",
                    "osm.osmchange.version",
                    "osm.osmchange.create",
                    "osm.osmchange.modify",
                    "osm.osmchange.delete",
                    "osm.osmchange.node",
                    "osm.osmchange.way",
                    "osm.osmchange.relation",
                    "osm.osmchange.action",
                    "osm.osmchange.old_element",
                    "osm.osmchange.new_element",
                    "osm.area",
                    "osm.area.id",
                    "osm.area.from_way",
                    "osm.area.tags",
                    "osm.common_keys.name",
                    "osm.common_keys.highway",
                    "osm.common_keys.railway",
                    "osm.common_keys.waterway",
                    "osm.common_keys.building",
                    "osm.common_keys.leisure",
                    "osm.common_keys.amenity",
                    "osm.common_keys.shop",
                    "osm.common_keys.sport",
                    "osm.common_keys.tourism",
                    "osm.common_keys.historic",
                    "osm.common_keys.landuse",
                    "osm.common_keys.natural",
                    "osm.common_keys.place",
                    "osm.common_keys.addr",
                    "osm.common_keys.operator",
                    "osm.common_keys.brand",
                    "osm.common_keys.network",
                ],
                "count": 112,
            },
            "ogc_services": {
                "description": "OGC Web Service metadata fields",
                "reference": "OGC Service Architecture",
                "fields": [
                    "ogc.service.name",
                    "ogc.service.title",
                    "ogc.service.abstract",
                    "ogc.service.keywords",
                    "ogc.service.keyword.type",
                    "ogc.service.keyword.value",
                    "ogc.service.service_type",
                    "ogc.service.service_type_version",
                    "ogc.service.fees",
                    "ogc.service.access_constraints",
                    "ogc.service.provider",
                    "ogc.service.provider.name",
                    "ogc.service.provider.site",
                    "ogc.service.provider.contact",
                    "ogc.service.provider.contact.name",
                    "ogc.service.provider.contact.position",
                    "ogc.service.provider.contact.voice",
                    "ogc.service.provider.contact.facsimile",
                    "ogc.service.provider.contact.address",
                    "ogc.service.provider.contact.address.street",
                    "ogc.service.provider.contact.address.city",
                    "ogc.service.provider.contact.address.state",
                    "ogc.service.provider.contact.address.postal",
                    "ogc.service.provider.contact.address.country",
                    "ogc.service.provider.contact.email",
                    "ogc.capabilities.version",
                    "ogc.capabilities.update_sequence",
                    "ogc.capabilities.operations",
                    "ogc.capabilities.operations.name",
                    "ogc.capabilities.operations.method",
                    "ogc.capabilities.operations.href",
                    "ogc.capabilities.parameters",
                    "ogc.capabilities.constraints",
                    "ogc.capabilities.layers",
                    "ogc.capabilities.layers.name",
                    "ogc.capabilities.layers.title",
                    "ogc.capabilities.layers.abstract",
                    "ogc.capabilities.layers.keywords",
                    "ogc.capabilities.layers.srs",
                    "ogc.capabilities.layers.bounding_box",
                    "ogc.capabilities.layers.crs",
                    "ogc.capabilities.layers.scale_hint",
                    "ogc.capabilities.layers.dimensions",
                    "ogc.capabilities.layers.opaque",
                    "ogc.capabilities.layers.no_subsets",
                    "ogc.capabilities.layers.fixed_width",
                    "ogc.capabilities.layers.fixed_height",
                    "ogc.capabilities.layers.style",
                    "ogc.capabilities.layers.style.name",
                    "ogc.capabilities.layers.style.title",
                    "ogc.capabilities.layers.style.legend_url",
                    "ogc.capabilities.layers.style.style_sheet_url",
                    "ogc.capabilities.layers.style.style_url",
                    "ogc.capabilities.layers.url",
                    "ogc.capabilities.exceptions",
                    "ogc.capabilities.layer_count",
                    "ogc.wfs.get_capabilities",
                    "ogc.wfs.describe_feature_type",
                    "ogc.wfs.get_feature",
                    "ogc.wfs.transaction",
                    "ogc.wfs.lock_feature",
                    "ogc.wfs.get_property_value",
                    "ogc.wfs.create_stored_query",
                    "ogc.wfs.drop_stored_query",
                    "ogc.wfs.list_stored_queries",
                    "ogc.wfs.get_feature_with_lock",
                    "ogc.wms.get_capabilities",
                    "ogc.wms.get_map",
                    "ogc.wms.get_feature_info",
                    "ogc.wms.get_legend_graphic",
                    "ogc.wms.get_styles",
                    "ogc.wms.describe_layer",
                    "ogc.wms.get_context",
                    "ogc.wms.get_utilities",
                    "ogc.wms.get_coverage",
                    "ogc.wms.get_tile",
                    "ogc.wms.get_resources",
                    "ogc.wcs.get_capabilities",
                    "ogc.wcs.describe_coverage",
                    "ogc.wcs.get_coverage",
                    "ogc.wmts.get_capabilities",
                    "ogc.wmts.get_tile",
                    "ogc.wmts.get_feature_info",
                    "ogc.sos.get_capabilities",
                    "ogc.sos.describe_sensor",
                    "ogc.sos.get_observation",
                    "ogc.sos.insert_observation",
                    "ogc.sos.insert_sensor",
                    "ogc.sos.delete_sensor",
                    "ogc.sos.update_sensor",
                    "ogc.csw.get_capabilities",
                    "ogc.csw.describe_record",
                    "ogc.csw.get_record_by_id",
                    "ogc.csw.get_records",
                    "ogc.csw.transaction",
                    "ogc.csw.harvest",
                ],
                "count": 130,
            },
        },
        "totals": {
            "categories": 9,
            "total_fields": 926,
        }
    }

    return INVENTORY


def main():
    print("=" * 70)
    print("ADVANCED GIS FORMAT METADATA FIELD INVENTORY")
    print("=" * 70)
    print()

    inventory = generate_gis_advanced_inventory()

    print(f"Generated: {inventory['generated_at']}")
    print(f"Categories: {inventory['totals']['categories']}")
    print(f"Total Fields: {inventory['totals']['total_fields']}")
    print()

    print("FIELD COUNTS BY CATEGORY:")
    print("-" * 50)
    for cat_name, cat_data in sorted(inventory['categories'].items(), key=lambda x: x[1]['count'], reverse=True):
        print(f"  {cat_name:35s}: {cat_data['count']:>4} fields")

    output_dir = Path("dist/gis_advanced_inventory")
    output_dir.mkdir(parents=True, exist_ok=True)

    output_file = output_dir / "gis_advanced_inventory.json"
    import json
    output_file.write_text(json.dumps(inventory, indent=2, sort_keys=True), encoding="utf-8")
    print()
    print(f"Wrote: {output_file}")

    summary = {
        "generated_at": inventory["generated_at"],
        "description": inventory["description"],
        "categories": {k: {"count": v["count"], "description": v["description"]} for k, v in inventory["categories"].items()},
        "totals": inventory["totals"],
    }

    summary_file = output_dir / "gis_advanced_summary.json"
    summary_file.write_text(json.dumps(summary, indent=2, sort_keys=True), encoding="utf-8")
    print(f"Wrote: {summary_file}")


if __name__ == "__main__":
    main()
