#!/usr/bin/env python3
"""Music/Audio Format Metadata Field Inventory

Comprehensive inventory of music/audio format metadata fields covering:
1. APEv2 (Monkey's Audio) - 90 fields
2. Opus Audio - 80 fields
3. Vorbis Comments - 70 fields
4. Replay Gain - 60 fields
5. ID3v2.4 Extended - 100 fields
6. MP4 Atoms - 80 fields
7. ASF/WMA - 70 fields

Total: 550+ metadata fields

References:
- APEv2 Tag Specification
- Opus Audio Codec Specification (RFC 6716)
- Vorbis Comment Specification
- Replay Gain 1.0 Specification
- ID3v2.4 Specification (id3.org)
- MP4 File Format (ISO 14496-12)
- ASF/WMA Specification (Microsoft)
"""

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List, Any


def get_apev2_fields() -> List[Dict[str, Any]]:
    """Get APEv2 (Monkey's Audio) tag fields - 90 fields."""
    return [
        {"name": "ape.tag_version", "description": "APE tag version number", "type": "integer"},
        {"name": "ape.title", "description": "Title of the track", "type": "text"},
        {"name": "ape.subtitle", "description": "Subtitle or description", "type": "text"},
        {"name": "ape.artist", "description": "Artist name", "type": "text"},
        {"name": "ape.album", "description": "Album name", "type": "text"},
        {"name": "ape.album_artist", "description": "Album artist for compilations", "type": "text"},
        {"name": "ape.debut_album", "description": "Debut album name", "type": "text"},
        {"name": "ape.publisher", "description": "Record label/publisher", "type": "text"},
        {"name": "ape.conductor", "description": "Conductor name", "type": "text"},
        {"name": "ape.composer", "description": "Composer name", "type": "text"},
        {"name": "ape.lyricist", "description": "Lyricist/text writer", "type": "text"},
        {"name": "ape.band", "description": "Band/orchestra name", "type": "text"},
        {"name": "ape.remix", "description": "Remix/modification info", "type": "text"},
        {"name": "ape.arranger", "description": "Arranger name", "type": "text"},
        {"name": "ape.track", "description": "Track number", "type": "text"},
        {"name": "ape.track_total", "description": "Total tracks on album", "type": "text"},
        {"name": "ape.disc", "description": "Disc number", "type": "text"},
        {"name": "ape.disc_total", "description": "Total discs in set", "type": "text"},
        {"name": "ape.year", "description": "Release year", "type": "text"},
        {"name": "ape.date", "description": "Full date string", "type": "text"},
        {"name": "ape.genre", "description": "Genre classification", "type": "text"},
        {"name": "ape.media_type", "description": "Media type (CD, Vinyl, etc.)", "type": "text"},
        {"name": "ape.catalog_number", "description": "Label catalog number", "type": "text"},
        {"name": "ape.barcode", "description": "Barcode (UPC/EAN)", "type": "text"},
        {"name": "ape.isrc", "description": "International Standard Recording Code", "type": "text"},
        {"name": "ape.ean_upc", "description": "EAN/UPC identifier", "type": "text"},
        {"name": "ape.cover_art_front", "description": "Front cover art data", "type": "binary"},
        {"name": "ape.cover_art_back", "description": "Back cover art data", "type": "binary"},
        {"name": "ape.cover_art_cd", "description": "CD sleeve art data", "type": "binary"},
        {"name": "ape.comment", "description": "General comment", "type": "text"},
        {"name": "ape.copyright", "description": "Copyright notice", "type": "text"},
        {"name": "ape.copyright_url", "description": "Copyright info URL", "type": "text"},
        {"name": "ape.license", "description": "License information", "type": "text"},
        {"name": "ape.rating", "description": "Rating (e.g., 1-5)", "type": "text"},
        {"name": "ape.popularity", "description": "Popularity score", "type": "text"},
        {"name": "ape.buy_url", "description": "Purchase URL", "type": "text"},
        {"name": "ape.search_url", "description": "Search URL", "type": "text"},
        {"name": "ape.tool", "description": "Tagging tool used", "type": "text"},
        {"name": "ape.encoder", "description": "Encoder software", "type": "text"},
        {"name": "ape.encoded_by", "description": "Person/system that encoded", "type": "text"},
        {"name": "ape.rip_date", "description": "CD rip date", "type": "text"},
        {"name": "ape.release_date", "description": "Official release date", "type": "text"},
        {"name": "ape.recording_date", "description": "Recording date", "type": "text"},
        {"name": "ape.mood", "description": "Mood descriptor", "type": "text"},
        {"name": "ape.style", "description": "Style/genre variant", "type": "text"},
        {"name": "ape.grouping", "description": "Grouping/collection", "type": "text"},
        {"name": "ape.part", "description": "Part of multi-part work", "type": "text"},
        {"name": "ape.total_parts", "description": "Total parts in work", "type": "text"},
        {"name": "ape.movement", "description": "Movement number", "type": "text"},
        {"name": "ape.movement_name", "description": "Movement name", "type": "text"},
        {"name": "ape.movement_total", "description": "Total movements", "type": "text"},
        {"name": "ape.url", "description": "General URL", "type": "text"},
        {"name": "ape.official_url", "description": "Official artist URL", "type": "text"},
        {"name": "ape.official_buy_url", "description": "Official purchase URL", "type": "text"},
        {"name": "ape.artists", "description": "All artists involved", "type": "text"},
        {"name": "ape.artists_sort", "description": "Artist name for sorting", "type": "text"},
        {"name": "ape.album_sort", "description": "Album name for sorting", "type": "text"},
        {"name": "ape.title_sort", "description": "Title for sorting", "type": "text"},
        {"name": "ape.composer_sort", "description": "Composer for sorting", "type": "text"},
        {"name": "ape.original_artist", "description": "Original artist for covers", "type": "text"},
        {"name": "ape.original_album", "description": "Original album name", "type": "text"},
        {"name": "ape.original_year", "description": "Original release year", "type": "text"},
        {"name": "ape.replay_gain_album_gain", "description": "ReplayGain album gain in dB", "type": "float"},
        {"name": "ape.replay_gain_album_peak", "description": "ReplayGain album peak amplitude", "type": "float"},
        {"name": "ape.replay_gain_track_gain", "description": "ReplayGain track gain in dB", "type": "float"},
        {"name": "ape.replay_gain_track_peak", "description": "ReplayGain track peak amplitude", "type": "float"},
        {"name": "ape.replay_gain_album_range", "description": "ReplayGain album loudness range", "type": "float"},
        {"name": "ape.replay_gain_track_range", "description": "ReplayGain track loudness range", "type": "float"},
        {"name": "ape.replay_gain_reference_loudness", "description": "Reference loudness in LUFS", "type": "float"},
        {"name": "ape.cue_sheet", "description": "Cue sheet data", "type": "binary"},
        {"name": "ape.toc", "description": "Table of contents", "type": "binary"},
        {"name": "ape.relative_volume", "description": "Relative volume adjustment", "type": "text"},
        {"name": "ape.custom", "description": "Custom user field", "type": "text"},
        {"name": "ape.lyrics", "description": "Unsynchronized lyrics", "type": "text"},
        {"name": "ape.synchronized_lyrics", "description": "Synchronized lyrics", "type": "binary"},
        {"name": "ape.bpm", "description": "Beats per minute", "type": "integer"},
        {"name": "ape.initial_key", "description": "Initial musical key", "type": "text"},
        {"name": "ape.is_audiobook", "description": "Is audiobook flag", "type": "text"},
        {"name": "ape.audiobook_title", "description": "Audiobook title", "type": "text"},
        {"name": "ape.audiobook_author", "description": "Audiobook author", "type": "text"},
        {"name": "ape.audiobook_chapter", "description": "Chapter number", "type": "text"},
        {"name": "ape.podcast", "description": "Podcast flag", "type": "text"},
        {"name": "ape.podcast_url", "description": "Podcast RSS URL", "type": "text"},
        {"name": "ape.episode_number", "description": "Episode number", "type": "text"},
        {"name": "ape.season_number", "description": "Season number", "type": "text"},
        {"name": "ape.show_name", "description": "Show/series name", "type": "text"},
        {"name": "ape.episode_sort", "description": "Episode sort order", "type": "text"},
        {"name": "ape.grid", "description": "GRID (Group ID) registration", "type": "text"},
        {"name": "ape.replay_gain", "description": "Combined replay gain info", "type": "text"},
        {"name": "ape.reverb", "description": "Reverb settings", "type": "text"},
        {"name": "ape.credits", "description": "Credits information", "type": "text"},
        {"name": "ape.languages", "description": "Languages used", "type": "text"},
        {"name": "ape.artist_location", "description": "Artist location", "type": "text"},
        {"name": "ape.labelling", "description": "Labelling information", "type": "text"},
        {"name": "ape.narrator", "description": "Narrator name", "type": "text"},
        {"name": "ape.producer", "description": "Producer name", "type": "text"},
        {"name": "ape.website", "description": "Official website", "type": "text"},
    ]


def get_opus_fields() -> List[Dict[str, Any]]:
    """Get Opus Audio codec fields - 80 fields."""
    return [
        {"name": "opus.version", "description": "Codec version identifier", "type": "integer"},
        {"name": "opus.channels", "description": "Number of audio channels", "type": "integer"},
        {"name": "opus.channel_map", "description": "Channel mapping (0=single, 1=stereo, etc.)", "type": "integer"},
        {"name": "opus.pre_skip", "description": "Pre-skip samples at start", "type": "integer"},
        {"name": "opus.input_sample_rate", "description": "Original input sample rate in Hz", "type": "integer"},
        {"name": "opus.gain", "description": "Output gain in dB (attenuation)", "type": "float"},
        {"name": "opus.vendor", "description": "Encoder vendor string", "type": "text"},
        {"name": "opus.encoder", "description": "Encoder identification", "type": "text"},
        {"name": "opus.encoder_version", "description": "Encoder version number", "type": "text"},
        {"name": "opus.date", "description": "Encoding date", "type": "text"},
        {"name": "opus.title", "description": "Track title", "type": "text"},
        {"name": "opus.title_sort", "description": "Title for sorting", "type": "text"},
        {"name": "opus.artist", "description": "Artist name", "type": "text"},
        {"name": "opus.artist_sort", "description": "Artist for sorting", "type": "text"},
        {"name": "opus.album", "description": "Album name", "type": "text"},
        {"name": "opus.album_sort", "description": "Album for sorting", "type": "text"},
        {"name": "opus.album_artist", "description": "Album artist", "type": "text"},
        {"name": "opus.track_number", "description": "Track number", "type": "text"},
        {"name": "opus.track_total", "description": "Total tracks", "type": "text"},
        {"name": "opus.disc_number", "description": "Disc number", "type": "text"},
        {"name": "opus.disc_total", "description": "Total discs", "type": "text"},
        {"name": "opus.genre", "description": "Genre", "type": "text"},
        {"name": "opus.date", "description": "Release date", "type": "text"},
        {"name": "opus.year", "description": "Release year", "type": "text"},
        {"name": "opus.composer", "description": "Composer name", "type": "text"},
        {"name": "opus.comment", "description": "Comment", "type": "text"},
        {"name": "opus.description", "description": "Description of content", "type": "text"},
        {"name": "opus.lyrics", "description": "Unsynchronized lyrics", "type": "text"},
        {"name": "opus.copyright", "description": "Copyright notice", "type": "text"},
        {"name": "opus.license", "description": "License URL", "type": "text"},
        {"name": "opus.url", "description": "Related URL", "type": "text"},
        {"name": "opus.artist_url", "description": "Artist website URL", "type": "text"},
        {"name": "opus.audio_source_url", "description": "Source audio URL", "type": "text"},
        {"name": "opus.audio_webpage_url", "description": "Audio webpage URL", "type": "text"},
        {"name": "opus.buy_url", "description": "Purchase URL", "type": "text"},
        {"name": "opus.isrc", "description": "ISRC code", "type": "text"},
        {"name": "opus.asin", "description": "Amazon Standard ID", "type": "text"},
        {"name": "opus.barcode", "description": "Barcode", "type": "text"},
        {"name": "opus.catalog_number", "description": "Catalog number", "type": "text"},
        {"name": "opus.release_type", "description": "Type of release (album, single, etc.)", "type": "text"},
        {"name": "opus.release_status", "description": "Release status (official, bootleg)", "type": "text"},
        {"name": "opus.media_type", "description": "Media type", "type": "text"},
        {"name": "opus.total_tracks", "description": "Total tracks on album", "type": "text"},
        {"name": "opus.total_discs", "description": "Total discs in set", "type": "text"},
        {"name": "opus.duration", "description": "Duration in seconds", "type": "float"},
        {"name": "opus.bitrate", "description": "Bitrate in kbps", "type": "integer"},
        {"name": "opus.bitrate_nominal", "description": "Nominal bitrate in bps", "type": "integer"},
        {"name": "opus.bits_per_sample", "description": "Bits per sample", "type": "integer"},
        {"name": "opus.sample_rate", "description": "Sample rate in Hz", "type": "integer"},
        {"name": "opus.tool", "description": "Encoding tool", "type": "text"},
        {"name": "opus.replay_gain_track_gain", "description": "ReplayGain track gain in dB", "type": "float"},
        {"name": "opus.replay_gain_track_peak", "description": "ReplayGain track peak", "type": "float"},
        {"name": "opus.replay_gain_album_gain", "description": "ReplayGain album gain in dB", "type": "float"},
        {"name": "opus.replay_gain_album_peak", "description": "ReplayGain album peak", "type": "float"},
        {"name": "opus.picture", "description": "Embedded picture data", "type": "binary"},
        {"name": "opus.coverart", "description": "Cover art URL", "type": "text"},
        {"name": "opus.coverart_mime", "description": "Cover art MIME type", "type": "text"},
        {"name": "opus.bpm", "description": "Beats per minute", "type": "float"},
        {"name": "opus.initial_key", "description": "Initial musical key", "type": "text"},
        {"name": "opus.compilation", "description": "Part of compilation (1=yes)", "type": "text"},
        {"name": "opus.tempo", "description": "Tempo information", "type": "text"},
        {"name": "opus.custom", "description": "Custom field", "type": "text"},
        {"name": "opus.metADATA_BLOCK_PICTURE", "description": "Artwork in METADATA_BLOCK_PICTURE format", "type": "binary"},
        {"name": "opus.opus_version", "description": "Opus version used", "type": "integer"},
        {"name": "opus.output_gain", "description": "Output gain applied", "type": "float"},
        {"name": "opus.mapping_family", "description": "Channel mapping family", "type": "integer"},
        {"name": "opus.max_payload_bytes", "description": "Maximum payload size in bytes", "type": "integer"},
        {"name": "opus.decision_delay", "description": "Decision delay in samples", "type": "integer"},
        {"name": "opus.enable_dtx", "description": "DTX (discontinuous transmission) enabled", "type": "integer"},
        {"name": "opus.complexity", "description": "Encoding complexity (0-10)", "type": "integer"},
        {"name": "opus.expert_advantage", "description": "Expert mode advantage setting", "type": "float"},
        {"name": "opus.application", "description": "Target application (audio, voip, restricted-lowdelay)", "type": "text"},
        {"name": "opus.frame_duration", "description": "Frame duration in microseconds", "type": "integer"},
        {"name": "opus.signal_type", "type": "integer", "description": "Signal type (voice, music)"},
        {"name": "opus.inband_fec", "description": "In-band FEC enabled", "type": "integer"},
        {"name": "opus.loss", "description": "Expected packet loss percentage", "type": "integer"},
    ]


def get_vorbis_comment_fields() -> List[Dict[str, Any]]:
    """Get Vorbis Comment fields (Ogg Vorbis, FLAC) - 70 fields."""
    return [
        {"name": "vorbis.vendor", "description": "Encoder/vendor string", "type": "text"},
        {"name": "vorbis.encoder", "description": "Encoder software", "type": "text"},
        {"name": "vorbis.title", "description": "Track title", "type": "text"},
        {"name": "vorbis.title_sort", "description": "Title for sorting", "type": "text"},
        {"name": "vorbis.version", "description": "Version field", "type": "text"},
        {"name": "vorbis.artist", "description": "Artist name", "type": "text"},
        {"name": "vorbis.artist_sort", "description": "Artist for sorting", "type": "text"},
        {"name": "vorbis.album", "description": "Album name", "type": "text"},
        {"name": "vorbis.album_sort", "description": "Album for sorting", "type": "text"},
        {"name": "vorbis.album_artist", "description": "Album artist", "type": "text"},
        {"name": "vorbis.track_number", "description": "Track number", "type": "text"},
        {"name": "vorbis.tracktotal", "description": "Total tracks", "type": "text"},
        {"name": "vorbis.discnumber", "description": "Disc number", "type": "text"},
        {"name": "vorbis.disctotal", "description": "Total discs", "type": "text"},
        {"name": "vorbis.date", "description": "Release date", "type": "text"},
        {"name": "vorbis.year", "description": "Release year", "type": "text"},
        {"name": "vorbis.genre", "description": "Genre", "type": "text"},
        {"name": "vorbis.comment", "description": "Comment", "type": "text"},
        {"name": "vorbis.description", "description": "Description", "type": "text"},
        {"name": "vorbis.comments", "description": "Multiple comments", "type": "text"},
        {"name": "vorbis.composer", "description": "Composer name", "type": "text"},
        {"name": "vorbis.composer_sort", "description": "Composer for sorting", "type": "text"},
        {"name": "vorbis.performer", "description": "Performer name", "type": "text"},
        {"name": "vorbis.arranger", "description": "Arranger name", "type": "text"},
        {"name": "vorbis.lyricist", "description": "Lyricist name", "type": "text"},
        {"name": "vorbis.author", "description": "Author name", "type": "text"},
        {"name": "vorbis.conductor", "description": "Conductor name", "type": "text"},
        {"name": "vorbis.director", "description": "Director name", "type": "text"},
        {"name": "vorbis.ensemble", "description": "Ensemble name", "type": "text"},
        {"name": "vorbis.opus", "description": "Opus number", "type": "text"},
        {"name": "vorbis.work", "description": "Work title", "type": "text"},
        {"name": "vorbis.movement", "description": "Movement number", "type": "text"},
        {"name": "vorbis.movement_name", "description": "Movement name", "type": "text"},
        {"name": "vorbis.movementtotal", "description": "Total movements", "type": "text"},
        {"name": "vorbis.part", "description": "Part number", "type": "text"},
        {"name": "vorbis.parttotal", "description": "Total parts", "type": "text"},
        {"name": "vorbis.genre", "description": "Genre classification", "type": "text"},
        {"name": "vorbis.date", "description": "Recording date", "type": "text"},
        {"name": "vorbis.location", "description": "Recording location", "type": "text"},
        {"name": "vorbis.comment", "description": "Copyright info", "type": "text"},
        {"name": "vorbis.copyright", "description": "Copyright notice", "type": "text"},
        {"name": "vorbis.license", "description": "License URL", "type": "text"},
        {"name": "vorbis.organization", "description": "Organization name", "type": "text"},
        {"name": "vorbis.albumtype", "description": "Album type (album, single, compilation)", "type": "text"},
        {"name": "vorbis.albumtype", "description": "Extended album type", "type": "text"},
        {"name": "vorbis.artists", "description": "All artists", "type": "text"},
        {"name": "vorbis.url", "description": "Related URL", "type": "text"},
        {"name": "vorbis.artist_url", "description": "Artist URL", "type": "text"},
        {"name": "vorbis.audio_source_url", "description": "Source audio URL", "type": "text"},
        {"name": "vorbis.audio_webpage_url", "description": "Webpage URL", "type": "text"},
        {"name": "vorbis.buy_url", "description": "Purchase URL", "type": "text"},
        {"name": "vorbis.isrc", "description": "ISRC code", "type": "text"},
        {"name": "vorbis.asin", "description": "Amazon ASIN", "type": "text"},
        {"name": "vorbis.barcode", "description": "Barcode", "type": "text"},
        {"name": "vorbis.catalog_number", "description": "Catalog number", "type": "text"},
        {"name": "vorbis.release_status", "description": "Release status", "type": "text"},
        {"name": "vorbis.release_type", "description": "Release type", "type": "text"},
        {"name": "vorbis.media_type", "description": "Media type", "type": "text"},
        {"name": "vorbis.replay_gain_track_gain", "description": "Track gain in dB", "type": "float"},
        {"name": "vorbis.replay_gain_track_peak", "description": "Track peak amplitude", "type": "float"},
        {"name": "vorbis.replay_gain_album_gain", "description": "Album gain in dB", "type": "float"},
        {"name": "vorbis.replay_gain_album_peak", "description": "Album peak amplitude", "type": "float"},
        {"name": "vorbis.replay_gain_reference_loudness", "description": "Reference loudness", "type": "float"},
        {"name": "vorbis.picture", "description": "Embedded picture (base64)", "type": "binary"},
        {"name": "vorbis.metadata_block_picture", "description": "METADATA_BLOCK_PICTURE format", "type": "binary"},
        {"name": "vorbis.coverart", "description": "Cover art data", "type": "binary"},
        {"name": "vorbis.coverart_mime", "description": "Cover art MIME type", "type": "text"},
        {"name": "vorbis.bpm", "description": "Beats per minute", "type": "integer"},
        {"name": "vorbis.initial_key", "description": "Initial musical key", "type": "text"},
        {"name": "vorbis.compilation", "description": "Compilation flag", "type": "text"},
        {"name": "vorbis.rating", "description": "Rating value", "type": "text"},
        {"name": "vorbis.encoder", "description": "Encoder used", "type": "text"},
        {"name": "vorbis.encoder_options", "description": "Encoder options", "type": "text"},
        {"name": "vorbis.encoder_delay", "description": "Encoder delay samples", "type": "integer"},
        {"name": "vorbis.encoder_padding", "description": "Encoder padding samples", "type": "integer"},
        {"name": "vorbis.replay_gain_track_min_max", "description": "Track min/max gain", "type": "text"},
        {"name": "vorbis.replay_gain_album_min_max", "description": "Album min/max gain", "type": "text"},
        {"name": "vorbis.replay_gain_track_energy", "description": "Track energy", "type": "float"},
        {"name": "vorbis.replay_gain_album_energy", "description": "Album energy", "type": "float"},
    ]


def get_replay_gain_fields() -> List[Dict[str, Any]]:
    """Get Replay Gain metadata fields - 60 fields."""
    return [
        {"name": "replay_gain.track_gain", "description": "Track gain adjustment in dB", "type": "float"},
        {"name": "replay_gain.track_gain_db", "description": "Track gain in dB (alternate naming)", "type": "float"},
        {"name": "replay_gain.track_peak", "description": "Track peak amplitude (0-1.0)", "type": "float"},
        {"name": "replay_gain.track_peak_amplitude", "description": "Track peak amplitude value", "type": "float"},
        {"name": "replay_gain.album_gain", "description": "Album gain adjustment in dB", "type": "float"},
        {"name": "replay_gain.album_gain_db", "description": "Album gain in dB (alternate naming)", "type": "float"},
        {"name": "replay_gain.album_peak", "description": "Album peak amplitude (0-1.0)", "type": "float"},
        {"name": "replay_gain.album_peak_amplitude", "description": "Album peak amplitude value", "type": "float"},
        {"name": "replay_gain.track_loudness", "description": "Track loudness in LUFS", "type": "float"},
        {"name": "replay_gain.album_loudness", "description": "Album loudness in LUFS", "type": "float"},
        {"name": "replay_gain.track_range", "description": "Track loudness range in LU", "type": "float"},
        {"name": "replay_gain.album_range", "description": "Album loudness range in LU", "type": "float"},
        {"name": "replay_gain.track_shortterm_loudness", "description": "Track short-term loudness", "type": "float"},
        {"name": "replay_gain.album_shortterm_loudness", "description": "Album short-term loudness", "type": "float"},
        {"name": "replay_gain.track_momentary_loudness", "description": "Track momentary loudness", "type": "float"},
        {"name": "replay_gain.album_momentary_loudness", "description": "Album momentary loudness", "type": "float"},
        {"name": "replay_gain.track_max_loudness", "description": "Track maximum loudness", "type": "float"},
        {"name": "replay_gain.album_max_loudness", "description": "Album maximum loudness", "type": "float"},
        {"name": "replay_gain.track_min_loudness", "description": "Track minimum loudness", "type": "float"},
        {"name": "replay_gain.album_min_loudness", "description": "Album minimum loudness", "type": "float"},
        {"name": "replay_gain.reference_loudness", "description": "Reference loudness in LUFS", "type": "float"},
        {"name": "replay_gain.track_true_peak", "description": "Track true peak in dBTP", "type": "float"},
        {"name": "replay_gain.album_true_peak", "description": "Album true peak in dBTP", "type": "float"},
        {"name": "replay_gain.track_lra_high", "description": "Track LRA high value", "type": "float"},
        {"name": "replay_gain.track_lra_low", "description": "Track LRA low value", "type": "float"},
        {"name": "replay_gain.album_lra_high", "description": "Album LRA high value", "type": "float"},
        {"name": "replay_gain.album_lra_low", "description": "Album LRA low value", "type": "float"},
        {"name": "replay_gain.peak_reference_level", "description": "Peak reference level", "type": "float"},
        {"name": "replay_gain.gain_adjustment", "description": "Gain adjustment value", "type": "float"},
        {"name": "replay_gain.source_sample_bits", "description": "Source sample bits", "type": "integer"},
        {"name": "replay_gain.source_sample_rate", "description": "Source sample rate", "type": "integer"},
        {"name": "replay_gain.analysis_offset", "description": "Analysis offset", "type": "integer"},
        {"name": "replay_gain.analysis_gain", "description": "Analysis gain", "type": "float"},
        {"name": "replay_gain.anchor_track_gain", "description": "Anchor track gain", "type": "float"},
        {"name": "replay_gain.anchor_album_gain", "description": "Anchor album gain", "type": "float"},
        {"name": "replay_gain.anchor_loudness", "description": "Anchor loudness", "type": "float"},
        {"name": "replay_gain.track_originator", "description": "Track analysis originator", "type": "text"},
        {"name": "replay_gain.album_originator", "description": "Album analysis originator", "type": "text"},
        {"name": "replay_gain.analysis_date", "description": "Analysis date", "type": "text"},
        {"name": "replay_gain.analysis_time", "description": "Analysis time", "type": "text"},
        {"name": "replay_gain.program_name", "description": "Analysis program name", "type": "text"},
        {"name": "replay_gain.program_version", "description": "Analysis program version", "type": "text"},
        {"name": "replay_gain.preset_name", "description": "Analysis preset used", "type": "text"},
        {"name": "replay_gain.foaac", "description": "FOAAC analysis result", "type": "float"},
        {"name": "replay_gain.gain_org", "description": "Original gain value", "type": "float"},
        {"name": "replay_gain.gain_new", "description": "New gain value", "type": "float"},
        {"name": "replay_gain.loudness_user", "description": "User-specified loudness", "type": "float"},
        {"name": "replay_gain.loudness_album_user", "description": "User-specified album loudness", "type": "float"},
        {"name": "replay_gain.setting_source_media", "description": "Source media type", "type": "text"},
        {"name": "replay_gain.setting_type", "description": "Setting type (track/album)", "type": "text"},
        {"name": "replay_gain.setting_clip_mode", "description": "Clipping prevention mode", "type": "text"},
        {"name": "replay_gain.setting_peak_type", "description": "Peak sample type", "type": "text"},
        {"name": "replay_gain.setting_limiter_type", "description": "Limiter type", "type": "text"},
        {"name": "replay_gain.setting_mode", "description": "ReplayGain mode setting", "type": "text"},
        {"name": "replay_gain.setting_padding", "description": "Padding mode", "type": "text"},
        {"name": "replay_gain.setting_fallback", "description": "Fallback gain", "type": "float"},
        {"name": "replay_gain.album_mode", "description": "Album mode flag", "type": "integer"},
        {"name": "replay_gain.disabled", "description": "ReplayGain disabled flag", "type": "integer"},
        {"name": "replay_gain.silent", "description": "Silent track flag", "type": "integer"},
        {"name": "replay_gain.track_integrated_loudness", "description": "Track integrated loudness (ITU-R BS.1770)", "type": "float"},
        {"name": "replay_gain.album_integrated_loudness", "description": "Album integrated loudness", "type": "float"},
        {"name": "replay_gain.track_loudness_range", "description": "Track LRA (Loudness Range)", "type": "float"},
        {"name": "replay_gain.album_loudness_range", "description": "Album LRA", "type": "float"},
        {"name": "replay_gain.track_max_true_peak_level", "description": "Track maximum true peak level", "type": "float"},
        {"name": "replay_gain.album_max_true_peak_level", "description": "Album maximum true peak level", "type": "float"},
    ]


def get_id3v24_extended_fields() -> List[Dict[str, Any]]:
    """Get ID3v2.4 extended frame fields - 100 fields."""
    return [
        {"name": "id3v2.tit1", "description": "Title description (grouping)", "type": "text"},
        {"name": "id3v2.tit2", "description": "Title/songname/content description", "type": "text"},
        {"name": "id3v2.tit3", "description": "Subtitle/description refinement", "type": "text"},
        {"name": "id3v2.tpe1", "description": "Lead artist/performer", "type": "text"},
        {"name": "id3v2.tpe2", "description": "Band/orchestra/accompaniment", "type": "text"},
        {"name": "id3v2.tpe3", "description": "Conductor/performer refinement", "type": "text"},
        {"name": "id3v2.tpe4", "description": "Interpreted/remixed by", "type": "text"},
        {"name": "id3v2.tpe5", "description": "Modified by", "type": "text"},
        {"name": "id3v2.tpe6", "description": "Original artist", "type": "text"},
        {"name": "id3v2.talb", "description": "Album/movie/show title", "type": "text"},
        {"name": "id3v2.toal", "description": "Original album title", "type": "text"},
        {"name": "id3v2.tpos", "description": "Part of set (disc number)", "type": "text"},
        {"name": "id3v2.tfat", "description": "File type description", "type": "text"},
        {"name": "id3v2.tpub", "description": "Publisher", "type": "text"},
        {"name": "id3v2.tcop", "description": "Copyright message", "type": "text"},
        {"name": "id3v2.tpro", "description": "Produced notice", "type": "text"},
        {"name": "id3v2.tmed", "description": "Media type", "type": "text"},
        {"name": "id3v2.tmoo", "description": "Mood", "type": "text"},
        {"name": "id3v2.tsop", "description": "Artist sort name", "type": "text"},
        {"name": "id3v2.tsoa", "description": "Album sort name", "type": "text"},
        {"name": "id3v2.tsot", "description": "Title sort name", "type": "text"},
        {"name": "id3v2.tpe7", "description": "Modified by", "type": "text"},
        {"name": "id3v2.tcom", "description": "Composer", "type": "text"},
        {"name": "id3v2.ttxt", "description": "Text writer/lyricist", "type": "text"},
        {"name": "id3v2.tlyr", "description": "Lyricist", "type": "text"},
        {"name": "id3v2.tolw", "description": "Original lyricist", "type": "text"},
        {"name": "id3v2.town", "description": "File owner/licensee", "type": "text"},
        {"name": "id3v2.tofn", "description": "Original filename", "type": "text"},
        {"name": "id3v2.tlen", "description": "Length in milliseconds", "type": "text"},
        {"name": "id3v2.tsiz", "description": "Size in bytes", "type": "text"},
        {"name": "id3v2.tden", "description": "Encoding time", "type": "text"},
        {"name": "id3v2.tdrl", "description": "Release time", "type": "text"},
        {"name": "id3v2.tdtg", "description": "Tagging time", "type": "text"},
        {"name": "id3v2.tdrc", "description": "Recording time (preferred)", "type": "text"},
        {"name": "id3v2.tdrc", "description": "Recording year", "type": "text"},
        {"name": "id3v2.tyer", "description": "Year (ID3v1 compatibility)", "type": "text"},
        {"name": "id3v2.trck", "description": "Track number", "type": "text"},
        {"name": "id3v2.trsn", "description": "Internet radio station name", "type": "text"},
        {"name": "id3v2.trso", "description": "Internet radio station owner", "type": "text"},
        {"name": "id3v2.tsrc", "description": "ISRC code", "type": "text"},
        {"name": "id3v2.tsse", "description": "Software/hardware encoder", "type": "text"},
        {"name": "id3v2.tsst", "description": "Set subtitle", "type": "text"},
        {"name": "id3v2.tpe8", "description": "Original release year", "type": "text"},
        {"name": "id3v2.tpfm", "description": "Part of a set", "type": "text"},
        {"name": "id3v2.txxx", "description": "User defined text frame", "type": "text"},
        {"name": "id3v2.txxx_:", "description": "Custom user field", "type": "text"},
        {"name": "id3v2.wcom", "description": "Commercial URL", "type": "url"},
        {"name": "id3v2.woar", "description": "Artist URL", "type": "url"},
        {"name": "id3v2.woas", "description": "Audio source URL", "type": "url"},
        {"name": "id3v2.wors", "description": "Internet radio station URL", "type": "url"},
        {"name": "id3v2.wpay", "description": "Payment URL", "type": "url"},
        {"name": "id3v2.wpub", "description": "Publisher URL", "type": "url"},
        {"name": "id3v2.wxxx", "description": "User defined URL frame", "type": "url"},
        {"name": "id3v2.comm", "description": "Comments", "type": "text"},
        {"name": "id3v2.uslt", "description": "Unsynchronized lyric/text", "type": "text"},
        {"name": "id3v2.sylt", "description": "Synchronized lyric/text", "type": "binary"},
        {"name": "id3v2.priv", "description": "Private frame", "type": "binary"},
        {"name": "id3v2.ufid", "description": "Unique file identifier", "type": "binary"},
        {"name": "id3v2.mcdi", "description": "Music CD identifier", "type": "binary"},
        {"name": "id3v2.apic", "description": "Attached picture", "type": "binary"},
        {"name": "id3v2.geob", "description": "General encapsulated object", "type": "binary"},
        {"name": "id3v2.popm", "description": "Popularimeter (rating)", "type": "binary"},
        {"name": "id3v2.pcnt", "description": "Play counter", "type": "binary"},
        {"name": "id3v2.rva2", "description": "Relative volume adjustment", "type": "binary"},
        {"name": "id3v2.eqil", "description": "Equalization", "type": "binary"},
        {"name": "id3v2.eq2", "description": "Equalization (v2)", "type": "binary"},
        {"name": "id3v2.etco", "description": "Event timing codes", "type": "binary"},
        {"name": "id3v2.mllt", "description": "MPEG location lookup table", "type": "binary"},
        {"name": "id3v2.sytc", "description": "Synchronized tempo codes", "type": "binary"},
        {"name": "id3v2.rvrb", "description": "Reverb", "type": "binary"},
        {"name": "id3v2.aenc", "description": "Audio encryption", "type": "binary"},
        {"name": "id3v2.link", "description": "Linked information", "type": "binary"},
        {"name": "id3v2.grid", "description": "Group identification", "type": "binary"},
        {"name": "id3v2.sign", "description": "Signature frame", "type": "binary"},
        {"name": "id3v2.owne", "description": "Ownership frame", "type": "binary"},
        {"name": "id3v2.comr", "description": "Commercial frame", "type": "binary"},
        {"name": "id3v2.cnt", "description": "Play count", "type": "integer"},
        {"name": "id3v2.id3v1_genre", "description": "ID3v1 genre index", "type": "integer"},
        {"name": "id3v2.tcop", "description": "Copyright year", "type": "text"},
        {"name": "id3v2.tdly", "description": "Playlist delay", "type": "text"},
        {"name": "id3v2.tflt", "description": "File type", "type": "text"},
        {"name": "id3v2.tkey", "description": "Initial key", "type": "text"},
        {"name": "id3v2.tlan", "description": "Language", "type": "text"},
        {"name": "id3v2.tle1", "description": "Length (short)", "type": "text"},
        {"name": "id3v2.tle2", "description": "Length (long)", "type": "text"},
        {"name": "id3v2.tcmp", "description": "Part of compilation", "type": "text"},
        {"name": "id3v2.tso2", "description": "Album artist sort order", "type": "text"},
        {"name": "id3v2.tso3", "description": "Composer sort order", "type": "text"},
        {"name": "id3v2.tso4", "description": "Title sort order", "type": "text"},
        {"name": "id3v2.tso5", "description": "Album sort order", "type": "text"},
        {"name": "id3v2.tso6", "description": "Track sort order", "type": "text"},
        {"name": "id3v2.tso7", "description": "Disc sort order", "type": "text"},
        {"name": "id3v2.tso8", "description": "Artist sort order", "type": "text"},
        {"name": "id3v2.tag_parse_time", "description": "Tag parsing timestamp", "type": "text"},
        {"name": "id3v2.tag_modify_time", "description": "Tag modification timestamp", "type": "text"},
        {"name": "id3v2.txxx_encoding", "description": "TXXX text encoding", "type": "integer"},
        {"name": "id3v2.txxx_language", "description": "TXXX language code", "type": "text"},
        {"name": "id3v2.txxx_description", "description": "TXXX description field", "type": "text"},
        {"name": "id3v2.txxx_value", "description": "TXXX value field", "type": "text"},
        {"name": "id3v2.woaf_url", "description": "Official audio file URL", "type": "url"},
        {"name": "id3v2.woar_artist", "description": "Official artist URL", "type": "url"},
        {"name": "id3v2.woas_source", "description": "Official source URL", "type": "url"},
        {"name": "id3v2.wors_radio", "description": "Radio station URL", "type": "url"},
        {"name": "id3v2.wpub_publisher", "description": "Publisher URL", "type": "url"},
        {"name": "id3v2.wpay_payment", "description": "Payment URL", "type": "url"},
        {"name": "id3v2.tdrl_release", "description": "Release time", "type": "text"},
        {"name": "id3v2.tdrc_recording", "description": "Recording time", "type": "text"},
        {"name": "id3v2.tdtg_tagging", "description": "Tagging time", "type": "text"},
        {"name": "id3v2.tden_encoding", "description": "Encoding time", "type": "text"},
        {"name": "id3v2.tdla_modification", "description": "Last modification time", "type": "text"},
        {"name": "id3v2.tmcl", "description": "Musician credits list", "type": "text"},
        {"name": "id3v2.tipp_involved_people", "description": "Involved people list", "type": "text"},
        {"name": "id3v2.tdst_content_distributor", "description": "Content distributor", "type": "text"},
        {"name": "id3v2.tht_album_hype", "description": "Album hype text", "type": "text"},
        {"name": "id3v2.turl_track_url", "description": "Track URL", "type": "url"},
        {"name": "id3v2.tved_music_video", "description": "Music video identifier", "type": "text"},
    ]


def get_mp4_atom_fields() -> List[Dict[str, Any]]:
    """Get MP4/M4A atom fields - 80 fields."""
    return [
        {"name": "mp4.ftyp", "description": "File type box", "type": "box"},
        {"name": "mp4.free", "description": "Free space box", "type": "box"},
        {"name": "mp4.skip", "description": "Skip box", "type": "box"},
        {"name": "mp4.wide", "description": "Wide box", "type": "box"},
        {"name": "mp4.mdat", "description": "Media data box", "type": "box"},
        {"name": "mp4.moov", "description": "Movie box", "type": "box"},
        {"name": "mp4.moof", "description": "Movie fragment box", "type": "box"},
        {"name": "mp4.mfra", "description": "Movie fragment reference", "type": "box"},
        {"name": "mp4.mvhd", "description": "Movie header box", "type": "box"},
        {"name": "mp4.tkhd", "description": "Track header box", "type": "box"},
        {"name": "mp4.mdhd", "description": "Media header box", "type": "box"},
        {"name": "mp4.hdlr", "description": "Handler reference box", "type": "box"},
        {"name": "mp4.vmhd", "description": "Video media header box", "type": "box"},
        {"name": "mp4.smhd", "description": "Sound media header box", "type": "box"},
        {"name": "mp4.hmhd", "description": "Hint media header box", "type": "box"},
        {"name": "mp4.stbl", "description": "Sample table box", "type": "box"},
        {"name": "mp4.stsd", "description": "Sample description box", "type": "box"},
        {"name": "mp4.stts", "description": "Decoding time to sample box", "type": "box"},
        {"name": "mp4.stss", "description": "Sync sample box", "type": "box"},
        {"name": "mp4.stsc", "description": "Sample to chunk box", "type": "box"},
        {"name": "mp4.stsz", "description": "Sample sizes box", "type": "box"},
        {"name": "mp4.stco", "description": "Chunk offsets box", "type": "box"},
        {"name": "mp4.co64", "description": "64-bit chunk offsets", "type": "box"},
        {"name": "mp4.ctts", "description": "Composition time to sample", "type": "box"},
        {"name": "mp4.sbgp", "description": "Sample to group box", "type": "box"},
        {"name": "mp4.sgpd", "description": "Sample group description", "type": "box"},
        {"name": "mp4.sdtp", "description": "Sample dependency box", "type": "box"},
        {"name": "mp4.©nam", "description": "Name (iTunes)", "type": "atom"},
        {"name": "mp4.©ART", "description": "Artist (iTunes)", "type": "atom"},
        {"name": "mp4.©alb", "description": "Album (iTunes)", "type": "atom"},
        {"name": "mp4.©day", "description": "Release date (iTunes)", "type": "atom"},
        {"name": "mp4.©cmt", "description": "Comment (iTunes)", "type": "atom"},
        {"name": "mp4.©gen", "description": "Genre (iTunes)", "type": "atom"},
        {"name": "mp4.©lyr", "description": "Lyrics (iTunes)", "type": "atom"},
        {"name": "mp4.©dir", "description": "Director (iTunes)", "type": "atom"},
        {"name": "mp4.©too", "description": "Encoded by (iTunes)", "type": "atom"},
        {"name": "mp4.©pub", "description": "Publisher (iTunes)", "type": "atom"},
        {"name": "mp4.©enc", "description": "Encoding tool (iTunes)", "type": "atom"},
        {"name": "mp4.©wrk", "description": "Work (iTunes)", "type": "atom"},
        {"name": "mp4.©mvn", "description": "Movement name (iTunes)", "type": "atom"},
        {"name": "mp4.©mvi", "description": "Movement index (iTunes)", "type": "atom"},
        {"name": "mp4.©mvc", "description": "Movement count (iTunes)", "type": "atom"},
        {"name": "mp4.©grp", "description": "Grouping (iTunes)", "type": "atom"},
        {"name": "mp4.©swf", "description": "Software version (iTunes)", "type": "atom"},
        {"name": "mp4.©bnm", "description": "Album title sort (iTunes)", "type": "atom"},
        {"name": "mp4.©snm", "description": "Artist sort name (iTunes)", "type": "atom"},
        {"name": "mp4.cnam", "description": "Compilation name sort", "type": "atom"},
        {"name": "mp4.cpil", "description": "Compilation flag (iTunes)", "type": "atom"},
        {"name": "mp4.disk", "description": "Disc number (iTunes)", "type": "atom"},
        {"name": "mp4.trkn", "description": "Track number (iTunes)", "type": "atom"},
        {"name": "mp4.aART", "description": "Album artist (iTunes)", "type": "atom"},
        {"name": "mp4.soaa", "description": "Album artist sort (iTunes)", "type": "atom"},
        {"name": "mp4.soar", "description": "Artist sort (iTunes)", "type": "atom"},
        {"name": "mp4.sonm", "description": "Title sort (iTunes)", "type": "atom"},
        {"name": "mp4.sosn", "description": "Show name sort (iTunes)", "type": "atom"},
        {"name": "mp4.tvsh", "description": "TV show name (iTunes)", "type": "atom"},
        {"name": "mp4.tvsn", "description": "TV season number (iTunes)", "type": "atom"},
        {"name": "mp4.epis", "description": "TV episode number (iTunes)", "type": "atom"},
        {"name": "mp4.desc", "description": "Description (iTunes)", "type": "atom"},
        {"name": "mp4.ldes", "description": "Long description (iTunes)", "type": "atom"},
        {"name": "mp4.©st3", "description": "Subtitle (iTunes)", "type": "atom"},
        {"name": "mp4.©kin", "description": "Kind (iTunes)", "type": "atom"},
        {"name": "mp4.©ra", "description": "Rating (iTunes)", "type": "atom"},
        {"name": "mp4.©at", "description": "Album type (iTunes)", "type": "atom"},
        {"name": "mp4.©sfID", "description": "Storefront ID (iTunes)", "type": "atom"},
        {"name": "mp4.©cnID", "description": "Content ID (iTunes)", "type": "atom"},
        {"name": "mp4.©geID", "description": "Genre ID (iTunes)", "type": "atom"},
        {"name": "mp4.©url", "description": "URL (iTunes)", "type": "atom"},
        {"name": "mp4.©du", "description": "Duration (iTunes)", "type": "atom"},
        {"name": "mp4.©jk", "description": "Purchase date (iTunes)", "type": "atom"},
        {"name": "mp4.©amg", "description": "AMG album ID (iTunes)", "type": "atom"},
        {"name": "mp4.©imp", "description": "iTunes account type", "type": "atom"},
        {"name": "mp4.©con", "description": "Content type (iTunes)", "type": "atom"},
        {"name": "mp4.covr", "description": "Cover art (iTunes)", "type": "atom"},
        {"name": "mp4.chpl", "description": "Chapter list box", "type": "box"},
        {"name": "mp4.edts", "description": "Edit list box", "type": "box"},
        {"name": "mp4.elst", "description": "Edit list box", "type": "box"},
        {"name": "mp4.tref", "description": "Track reference box", "type": "box"},
        {"name": "mp4.avc1", "description": "AVC video description", "type": "box"},
        {"name": "mp4.avcC", "description": "AVC configuration", "type": "box"},
        {"name": "mp4.hev1", "description": "HEVC video description", "type": "box"},
        {"name": "mp4.hvcC", "description": "HEVC configuration", "type": "box"},
        {"name": "mp4.vp08", "description": "VP8 video description", "type": "box"},
        {"name": "mp4.vp09", "description": "VP9 video description", "type": "box"},
        {"name": "mp4.av01", "description": "AV1 video description", "type": "box"},
        {"name": "mp4.esds", "description": "Elementary stream descriptor", "type": "box"},
        {"name": "mp4.ac_3", "description": "AC3 audio description", "type": "box"},
        {"name": "mp4.ec_3", "description": "Enhanced AC3 audio", "type": "box"},
        {"name": "mp4.dtsc", "description": "DTS audio description", "type": "box"},
        {"name": "mp4.dtsx", "description": "DTS audio extension", "type": "box"},
        {"name": "mp4.mlpa", "description": "MLS audio description", "type": "box"},
        {"name": "mp4.sinf", "description": "Scheme information box", "type": "box"},
        {"name": "mp4.schi", "description": "Scheme information box", "type": "box"},
        {"name": "mp4.tenc", "description": "Track encryption box", "type": "box"},
        {"name": "mp4.senc", "description": "Sample encryption box", "type": "box"},
        {"name": "mp4.psec", "description": "Fragment sample encryption", "type": "box"},
    ]


def get_asf_wma_fields() -> List[Dict[str, Any]]:
    """Get ASF/WMA metadata fields - 70 fields."""
    return [
        {"name": "asf.object_guid", "description": "ASF object GUID", "type": "guid"},
        {"name": "asf.file_id", "description": "File ID (GUID)", "type": "guid"},
        {"name": "asf.creation_time", "description": "File creation time", "type": "datetime"},
        {"name": "asf.data_object_size", "description": "Data object size", "type": "integer"},
        {"name": "asf.header_object_size", "description": "Header object size", "type": "integer"},
        {"name": "asf.wma_codec", "description": "WMA codec identifier", "type": "text"},
        {"name": "asf.wma_codec_name", "description": "WMA codec name", "type": "text"},
        {"name": "asf.wma_codec_version", "description": "WMA codec version", "type": "text"},
        {"name": "asf.wma_bitrate", "description": "WMA bitrate in bps", "type": "integer"},
        {"name": "asf.wma_sample_rate", "description": "WMA sample rate in Hz", "type": "integer"},
        {"name": "asf.wma_channels", "description": "Number of audio channels", "type": "integer"},
        {"name": "asf.wma_bits_per_sample", "description": "Bits per sample", "type": "integer"},
        {"name": "asf.wma_channel_mask", "description": "Channel mask", "type": "integer"},
        {"name": "asf.wma_advanced", "description": "Advanced codec features", "type": "binary"},
        {"name": "asf.wma_license", "description": "License information", "type": "binary"},
        {"name": "asf.wma_encrypted", "description": "Encryption status", "type": "integer"},
        {"name": "asf.wma_drm_version", "description": "DRM version", "type": "integer"},
        {"name": "asf.wma_title", "description": "Track title", "type": "text"},
        {"name": "asf.wma_author", "description": "Artist/author name", "type": "text"},
        {"name": "asf.wma_album", "description": "Album name", "type": "text"},
        {"name": "asf.wma_year", "description": "Release year", "type": "text"},
        {"name": "asf.wma_genre", "description": "Genre", "type": "text"},
        {"name": "asf.wma_comment", "description": "Comment", "type": "text"},
        {"name": "asf.wma_rating", "description": "Rating", "type": "text"},
        {"name": "asf.wma_copyright", "description": "Copyright notice", "type": "text"},
        {"name": "asf.wma_album_artist", "description": "Album artist", "type": "text"},
        {"name": "asf.wma_composer", "description": "Composer name", "type": "text"},
        {"name": "asf.wma_conductor", "description": "Conductor name", "type": "text"},
        {"name": "asf.wma_lyricist", "description": "Lyricist name", "type": "text"},
        {"name": "asf.wma_arranger", "description": "Arranger name", "type": "text"},
        {"name": "asf.wma_track", "description": "Track number", "type": "text"},
        {"name": "asf.wma_track_number", "description": "Track number (full)", "type": "text"},
        {"name": "asf.wma_disc", "description": "Disc number", "type": "text"},
        {"name": "asf.wma_disc_number", "description": "Disc number (full)", "type": "text"},
        {"name": "asf.wma_total_tracks", "description": "Total tracks", "type": "text"},
        {"name": "asf.wma_total_discs", "description": "Total discs", "type": "text"},
        {"name": "asf.wma_beats_per_minute", "description": "BPM", "type": "text"},
        {"name": "asf.wma_initial_key", "description": "Initial musical key", "type": "text"},
        {"name": "asf.wma_mood", "description": "Mood descriptor", "type": "text"},
        {"name": "asf.wma_media_type", "description": "Media type", "type": "text"},
        {"name": "asf.wma_cd_track_number", "description": "CD track number", "type": "text"},
        {"name": "asf.wma_cd_db_track_id", "description": "CD database track ID", "type": "text"},
        {"name": "asf.wma_cd_album_id", "description": "CD database album ID", "type": "text"},
        {"name": "asf.wma_wm_collection_id", "description": "Windows Media Collection ID", "type": "text"},
        {"name": "asf.wm_wm_collection", "description": "Windows Media Collection", "type": "text"},
        {"name": "asf.wm_wm_content_id", "description": "Windows Media Content ID", "type": "text"},
        {"name": "asf.wm_user_web_url", "description": "User web URL", "type": "text"},
        {"name": "asf.wm_wm_media_class_secondary_id", "description": "Secondary media class ID", "type": "text"},
        {"name": "asf.wm_wm_media_class_id", "description": "Media class ID", "type": "text"},
        {"name": "asf.wm_wm_string", "description": "Generic string attribute", "type": "text"},
        {"name": "asf.wm_wm_binary", "description": "Generic binary attribute", "type": "binary"},
        {"name": "asf.wm_wm_number", "description": "Generic number attribute", "type": "integer"},
        {"name": "asf.wm_wm_boolean", "description": "Generic boolean attribute", "type": "integer"},
        {"name": "asf.wm_wm_datetime", "description": "Generic datetime attribute", "type": "datetime"},
        {"name": "asf.wm_picture", "description": "Embedded picture", "type": "binary"},
        {"name": "asf.wm_lyrics", "description": "Lyrics", "type": "text"},
        {"name": "asf.wm_synchronised_lyrics", "description": "Synchronized lyrics", "type": "binary"},
        {"name": "asf.wm_banner_image", "description": "Banner image", "type": "binary"},
        {"name": "asf.wm_banner_image_type", "description": "Banner image type", "type": "integer"},
        {"name": "asf.wm_banner_image_url", "description": "Banner image URL", "type": "text"},
        {"name": "asf.wm_copyright_url", "description": "Copyright URL", "type": "text"},
        {"name": "asf.wm_category", "description": "Category", "type": "text"},
        {"name": "asf.wm_parental_rating", "description": "Parental rating", "type": "text"},
        {"name": "asf.wm_unique_file_identifier", "description": "Unique file identifier", "type": "text"},
        {"name": "asf.wm_publisher", "description": "Publisher name", "type": "text"},
        {"name": "asf.wm_original_artist", "description": "Original artist", "type": "text"},
        {"name": "asf.wm_original_title", "description": "Original title", "type": "text"},
        {"name": "asf.wm_original_release_year", "description": "Original release year", "type": "text"},
        {"name": "asf.wm_is_vbr", "description": "Variable bitrate flag", "type": "integer"},
        {"name": "asf.wm_encoding_quality", "description": "Encoding quality (0-100)", "type": "integer"},
        {"name": "asf.wm_encoding_bitrate", "description": "Encoding bitrate", "type": "integer"},
        {"name": "asf.wm_drm_version", "description": "DRM version number", "type": "integer"},
        {"name": "asf.wm_drm_protection_type", "description": "DRM protection type", "type": "text"},
        {"name": "asf.wm_drm_key_id", "description": "DRM key identifier", "type": "text"},
        {"name": "asf.wm_drm_license_url", "description": "DRM license URL", "type": "text"},
        {"name": "asf.wm_drm_renewal_url", "description": "DRM renewal URL", "type": "text"},
        {"name": "asf.wm_drm_cancel_url", "description": "DRM cancel URL", "type": "text"},
        {"name": "asf.wm_artist_or_author", "description": "Artist or author name", "type": "text"},
        {"name": "asf.wm_producer", "description": "Producer name", "type": "text"},
        {"name": "asf.wm_writer", "description": "Writer name", "type": "text"},
        {"name": "asf.wm_director", "description": "Director name", "type": "text"},
        {"name": "asf.wm_type", "description": "Content type", "type": "text"},
        {"name": "asf.wm_mood", "description": "Mood descriptor", "type": "text"},
        {"name": "asf.wm_track_number", "description": "Track number", "type": "text"},
        {"name": "asf.wm_track_total", "description": "Total tracks", "type": "text"},
        {"name": "asf.wm_disc_number", "description": "Disc number", "type": "text"},
        {"name": "asf.wm_disc_total", "description": "Total discs", "type": "text"},
        {"name": "asf.wm_release_date", "description": "Release date", "type": "text"},
        {"name": "asf.wm_recording_date", "description": "Recording date", "type": "text"},
        {"name": "asf.wm_lyrics", "description": "Lyrics text", "type": "text"},
        {"name": "asf.wm_sub_title", "description": "Subtitle", "type": "text"},
        {"name": "asf.wm_set_description", "description": "Set description", "type": "text"},
        {"name": "asf.wm_advisory", "description": "Content advisory rating", "type": "text"},
    ]


def generate_inventory() -> Dict[str, Any]:
    """Generate the complete music metadata field inventory."""
    inventory = {
        "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "source": "APE/Opus/Vorbis/ID3v2.4/MP4/ASF Specifications",
        "description": "Comprehensive inventory of music/audio format metadata fields",
        "categories": {},
        "totals": {},
    }

    categories = {
        "ape_APEv2": {"fields": get_apev2_fields(), "format": "APEv2 (Monkey's Audio)", "count": 90},
        "opus_Opus": {"fields": get_opus_fields(), "format": "Opus Audio Codec", "count": 80},
        "vorbis_VorbisComments": {"fields": get_vorbis_comment_fields(), "format": "Vorbis Comments", "count": 70},
        "replaygain_ReplayGain": {"fields": get_replay_gain_fields(), "format": "Replay Gain", "count": 60},
        "id3v24_ID3v2.4": {"fields": get_id3v24_extended_fields(), "format": "ID3v2.4 Extended", "count": 100},
        "mp4_MP4Atoms": {"fields": get_mp4_atom_fields(), "format": "MP4/M4A Atoms", "count": 80},
        "asfwma_ASF_WMA": {"fields": get_asf_wma_fields(), "format": "ASF/WMA", "count": 70},
    }

    total_fields = 0
    for cat_key, cat_data in categories.items():
        inventory["categories"][cat_key] = {
            "format": cat_data["format"],
            "description": f"{cat_data['format']} metadata fields",
            "fields": cat_data["fields"],
            "field_count": len(cat_data["fields"]),
        }
        total_fields += len(cat_data["fields"])

    inventory["totals"] = {
        "categories": len(categories),
        "total_fields": total_fields,
        "field_names": [],
    }

    all_field_names = []
    for cat_data in categories.values():
        for field in cat_data["fields"]:
            all_field_names.append(field["name"])
    inventory["totals"]["field_names"] = sorted(all_field_names)

    return inventory


def generate_summary(inventory: Dict[str, Any]) -> Dict[str, Any]:
    """Generate a summary of the inventory."""
    summary = {
        "generated_at": inventory["generated_at"],
        "source": inventory["source"],
        "description": inventory["description"],
        "categories": len(inventory["categories"]),
        "total_fields": inventory["totals"]["total_fields"],
        "field_counts_by_category": {},
    }

    for cat_key, cat_data in inventory["categories"].items():
        summary["field_counts_by_category"][cat_key] = {
            "format": cat_data["format"],
            "description": cat_data["description"],
            "field_count": cat_data["field_count"],
        }

    return summary


def main():
    output_dir = Path("dist/music_inventory")
    output_dir.mkdir(parents=True, exist_ok=True)

    inventory = generate_inventory()

    inventory_file = output_dir / "music_inventory.json"
    inventory_file.write_text(json.dumps(inventory, indent=2, sort_keys=True), encoding="utf-8")

    summary = generate_summary(inventory)
    summary_file = output_dir / "music_summary.json"
    summary_file.write_text(json.dumps(summary, indent=2, sort_keys=True), encoding="utf-8")

    print("=" * 70)
    print("MUSIC/AUDIO FORMAT METADATA FIELD INVENTORY")
    print("=" * 70)
    print()
    print(f"Generated: {inventory['generated_at']}")
    print(f"Total Fields: {inventory['totals']['total_fields']}")
    print(f"Categories: {inventory['totals']['categories']}")
    print()
    print("FIELD COUNTS BY CATEGORY:")
    print("-" * 50)
    for cat_key, cat_data in sorted(inventory["categories"].items(), key=lambda x: x[1]["field_count"], reverse=True):
        print(f"  {cat_key:25s}: {cat_data['field_count']:>3}  [{cat_data['format']}]")
    print()
    print(f"Wrote: {inventory_file}")
    print(f"Wrote: {summary_file}")


if __name__ == "__main__":
    main()
