#!/usr/bin/env python3
"""3D Printing and Additive Manufacturing Metadata Field Inventory for MetaExtract.

Covers 3MF format, STL/Mesh quality, G-Code, slicer settings, material properties,
and build parameters for FDM, SLA, SLS, and other 3D printing technologies.
"""

from datetime import datetime, timezone
from pathlib import Path
import json


def generate_3dprinting_inventory():
    """Generate comprehensive 3D printing/additive manufacturing metadata field inventory."""

    INVENTORY = {
        "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "source": "3MF Consortium Specification, ASTM F42 Additive Manufacturing Standards, ISO/ASTM 52900, G-Code Reference, Slicer Documentation",
        "description": "3D printing and additive manufacturing metadata fields including 3MF format, STL mesh quality, G-Code toolpaths, slicer profiles, material properties, and build parameters",
        "categories": {
            "3mf_format": {
                "description": "3MF (3D Manufacturing Format) fields for additive manufacturing",
                "reference": "https://3mf.io/specification/",
                "fields": [
                    "3mf.version",
                    "3mf.header",
                    "3mf.unit",
                    "3mf.unit.mm",
                    "3mf.unit.cm",
                    "3mf.unit.m",
                    "3mf.unit.inch",
                    "3mf.unit.foot",
                    "3mf.metadata",
                    "3mf.materials",
                    "3mf.resources",
                    "3mf.build",
                    "3mf.asssets",
                    "3mf.base",
                    "3mf.model",
                    "3mf.slices",
                    "3mf.beam",
                    "3mf.production",
                    "3mf.multipart",
                    "3mf.tessellation",
                    "3mf.object",
                    "3mf.object.id",
                    "3mf.object.type",
                    "3mf.object.partnumber",
                    "3mf.object.name",
                    "3mf.object.uuid",
                    "3mf.mesh",
                    "3mf.mesh.vertices",
                    "3mf.mesh.triangleindices",
                    "3mf.mesh.position",
                    "3mf.mesh.orientation",
                    "3mf.mesh.extents",
                    "3mf.mesh.extents.minx",
                    "3mf.mesh.extents.miny",
                    "3mf.mesh.extents.minz",
                    "3mf.mesh.extents.maxx",
                    "3mf.mesh.extents.maxy",
                    "3mf.mesh.extents.maxz",
                    "3mf.mesh.vertexcount",
                    "3mf.mesh.trianglecount",
                    "3mf.components",
                    "3mf.component.objectid",
                    "3mf.component.transform",
                    "3mf.component.translation",
                    "3mf.component.rotation",
                    "3mf.component.scale",
                    "3mf.component.offset",
                    "3mf.content.materials",
                    "3mf.content.material",
                    "3mf.content.type",
                    "3mf.content.value",
                    "3mf.content.base",
                    "3mf.content.definition",
                    "3mf.build.item",
                    "3mf.build.objectid",
                    "3mf.build.transform",
                    "3mf.build.translation",
                    "3mf.build.rotation",
                    "3mf.build.scale",
                    "3mf.build.offset",
                    "3mf.build.plate",
                    "3mf.slice.references",
                    "3mf.slice.height",
                    "3mf.slice.service",
                    "3mf.slice.polygons",
                    "3mf.slice.vertices",
                    "3mf.slice.layerheight",
                    "3mf.slice.extruder",
                    "3mf.slice.ztop",
                    "3mf.slice.numpolygons",
                    "3mf.beam.lc",
                    "3mf.beam.p",
                    "3mf.beam.d",
                    "3mf.beam.crossover",
                    "3mf.beam.nominalfilament",
                    "3mf.beam.mesh.position",
                    "3mf.beam.mesh.rotation",
                    "3mf.beam.mesh.scale",
                    "3mf.beam.mesh.extents",
                    "3mf.production.metadata",
                    "3mf.production.time",
                    "3mf.production.total_time",
                    "3mf.production.material_volume",
                    "3mf.production.material_weight",
                    "3mf.production.machine_name",
                    "3mf.production.machine_uuid",
                    "3mf.generator.application",
                    "3mf.generator.version",
                    "3mf.generator.platform",
                    "3mf.producer",
                    "3mf.copyright",
                    "3mf.creationdate",
                    "3mf.modificationdate",
                    "3mf.comment",
                    "3mf.manufacturer",
                    "3mf.modelname",
                    "3mf.modeldescription",
                    "3mf.modelkeywords",
                    "3mf.modelnumber",
                    "3mf.partnumber",
                    "3mf.customer",
                    "3mf.customerid",
                ],
                "count": 102,
            },
            "stl_mesh": {
                "description": "STL file format and mesh quality metadata fields",
                "reference": "https://en.wikipedia.org/wiki/STL_(file_format)",
                "fields": [
                    "stl.format",
                    "stl.format.ascii",
                    "stl.format.binary",
                    "stl.header",
                    "stl.header.name",
                    "stl.header.byteCount",
                    "stl.triangle.count",
                    "stl.triangle.normal",
                    "stl.triangle.vertex1",
                    "stl.triangle.vertex2",
                    "stl.triangle.vertex3",
                    "stl.attribute.byteCount",
                    "stl.solid.name",
                    "stl.facet.normal",
                    "stl.facet.normal.nx",
                    "stl.facet.normal.ny",
                    "stl.facet.normal.nz",
                    "stl.outer.loop",
                    "stl.vertex",
                    "stl.vertex.x",
                    "stl.vertex.y",
                    "stl.vertex.z",
                    "stl.vertex1",
                    "stl.vertex2",
                    "stl.vertex3",
                    "stl.endloop",
                    "stl.endfacet",
                    "stl.endsolid",
                    "stl.missing_normals",
                    "stl.degenerate_triangles",
                    "stl.non_manifold_edges",
                    "stl.holes",
                    "stl.surface_area",
                    "stl.volume",
                    "stl.bounds",
                    "stl.bounds.minx",
                    "stl.bounds.miny",
                    "stl.bounds.minz",
                    "stl.bounds.maxx",
                    "stl.bounds.maxy",
                    "stl.bounds.maxz",
                    "stl.center",
                    "stl.mesh_quality",
                    "stl.min_edge_length",
                    "stl.max_edge_length",
                    "stl.avg_edge_length",
                    "stl.aspect_ratio",
                    "stl.min_angle",
                    "stl.max_angle",
                    "stl.avg_angle",
                    "stl.triangle_size",
                    "stl.tolerance",
                    "stl.surface_tolerance",
                    "stl.angle_tolerance",
                    "stl.max_angle_deviation",
                    "stl.normal_deviation",
                    "stl.vertex_welding",
                    "stl.weld_threshold",
                    "stl.stitching",
                    "stl.fill_holes",
                    "stl.remove_cavities",
                    "stl.eliminate_degenerate",
                    "stl.normal_consistency",
                    "stl.fix_normal_direction",
                    "stl.manifoldness",
                    "stl.boundary_edges",
                    "stl.watertight",
                    "stl.orientation",
                    "stl.face_count",
                    "stl.vertex_count",
                    "stl.edge_count",
                    "stl.mesh_density",
                    "stl.resolution",
                    "stl.adaptive_deformation",
                    "stl.curvature_tolerance",
                    "stl.regenerate_normals",
                    "stl.stl_unit",
                    "stl.unit",
                    "stl.scale_factor",
                    "stl.centroid",
                    "stl.bounding_box",
                    "stl.bounding_sphere",
                    "stl.convex_hull",
                    "stl.genus",
                    "stl.euler_characteristic",
                    "stl.genus_components",
                    "stl.connected_components",
                    "stl.simplified_mesh",
                    "stl.simplification_ratio",
                    "stl.target_triangles",
                    "stl.decimation_error",
                    "stl.mesh_smoothing",
                    "stl.smooth_iterations",
                    "stl.smooth_factor",
                    "stl.laplacian_smooth",
                    "stl.taubin_smooth",
                    "stl.feature_detection",
                    "stl.feature_angle",
                    "stl.sharp_edges",
                    "stl.flat_faces",
                    "stl.curved_surfaces",
                    "stl.mesh_inspection",
                    "stl.thickness_analysis",
                    "stl.min_thickness",
                    "stl.max_thickness",
                    "stl.self_intersection",
                    "stl.self_intersection_count",
                ],
                "count": 107,
            },
            "gcode": {
                "description": "G-Code toolpath and CNC/3D printer machine code fields",
                "reference": "https://www.reprap.org/wiki/G-code",
                "fields": [
                    "gcode.version",
                    "gcode.flavor",
                    "gcode.flavor.reprap",
                    "gcode.flavor.marlin",
                    "gcode.flavor.teacup",
                    "gcode.flavor.smoothie",
                    "gcode.flavor.repetier",
                    "gcode.flavor.nuttx",
                    "gcode.flavor.klipper",
                    "gcode.unit",
                    "gcode.unit.mm",
                    "gcode.unit.inch",
                    "gcode.absolute_positioning",
                    "gcode.relative_positioning",
                    "gcode.inches_mode",
                    "gcode.mm_mode",
                    "gcode.layer_count",
                    "gcode.layer_height",
                    "gcode.layer_height.current",
                    "gcode.first_layer_height",
                    "gcode.print_temperature",
                    "gcode.bed_temperature",
                    "gcode.chamber_temperature",
                    "gcode.build_plate_temperature",
                    "gcode.filament.diameter",
                    "gcode.filament.temperature",
                    "gcode.filament.flow",
                    "gcode.filament.density",
                    "gcode.filament.cost",
                    "gcode.filament.vendor",
                    "gcode.filament.material",
                    "gcode.filament.color",
                    "gcode.filament.id",
                    "gcode.nozzle.diameter",
                    "gcode.nozzle.name",
                    "gcode.nozzle.temperature",
                    "gcode.bed.size",
                    "gcode.bed.shape",
                    "gcode.bed.origin",
                    "gcode.print_center",
                    "gcode.print_bed_temperature",
                    "gcode.build_volume",
                    "gcode.build_volume.x",
                    "gcode.build_volume.y",
                    "gcode.build_volume.z",
                    "gcode.axis.x",
                    "gcode.axis.y",
                    "gcode.axis.z",
                    "gcode.axis.e",
                    "gcode.feedrate",
                    "gcode.feedrate.units_per_min",
                    "gcode.feedrate.units_per_sec",
                    "gcode.feedrate.xy",
                    "gcode.feedrate.z",
                    "gcode.feedrate.e",
                    "gcode.speed",
                    "gcode.speed.print",
                    "gcode.speed.travel",
                    "gcode.speed.infill",
                    "gcode.speed.wall",
                    "gcode.speed.shell",
                    "gcode.speed.topbottom",
                    "gcode.speed.brim",
                    "gcode.speed.raft",
                    "gcode.speed.support",
                    "gcode.speed.retract",
                    "gcode.speed.deretract",
                    "gcode.acceleration",
                    "gcode.acceleration.print",
                    "gcode.acceleration.travel",
                    "gcode.acceleration.outer_before_wall",
                    "gcode.acceleration.inner_before_wall",
                    "gcode.acceleration.layer_z_hop",
                    "gcode.jerk",
                    "gcode.jerk.xy",
                    "gcode.jerk.z",
                    "gcode.jerk.e",
                    "gcode.retraction",
                    "gcode.retraction.enable",
                    "gcode.retraction.distance",
                    "gcode.retraction.speed",
                    "gcode.retraction.deretraction_speed",
                    "gcode.retraction.min_travel",
                    "gcode.retraction.z_hop",
                    "gcode.retraction.z_hop_over",
                    "gcode.wipe",
                    "gcode.wipe.distance",
                    "gcode.wipe.retract",
                    "gcode.wipe.pause",
                    "gcode.coolant",
                    "gcode.coolant.flood",
                    "gcode.coolant.mist",
                    "gcode.coolant.off",
                    "gcode.spindle.speed",
                    "gcode.spindle.direction",
                    "gcode.spindle.enable",
                    "gcode.dwell",
                    "gcode.home",
                    "gcode.home.x",
                    "gcode.home.y",
                    "gcode.home.z",
                    "gcode.absolute_extruder",
                    "gcode.relative_extruder",
                    "gcode.extruder.count",
                    "gcode.extruder.current",
                    "gcode.extruder.shared_heater",
                    "gcode.primed",
                    "gcode.prime",
                    "gcode.prime_speed",
                    "gcode.prime_length",
                    "gcode.prime_pause",
                    "gcode.layer_pause",
                    "gcode.color_change",
                    "gcode.filament_change",
                    "gcode.m600",
                    "gcode.m601",
                    "gcode.m603",
                    "gcode.m603.t",
                    "gcode.m603.l",
                    "gcode.m604",
                    "gcode.time_estimate",
                    "gcode.filament_used",
                    "gcode.filament_used.mm",
                    "gcode.filament_used.cm3",
                    "gcode.filament_used.g",
                    "gcode.total_filament",
                    "gcode.layer_time",
                    "gcode.layer_time.avg",
                    "gcode.layer_time.min",
                    "gcode.layer_time.max",
                    "gcode.print_time",
                    "gcode.print_time.total",
                    "gcode.print_time.days",
                    "gcode.print_time.hours",
                    "gcode.print_time.minutes",
                    "gcode.by_layer",
                    "gcode.by_extruder",
                    "gcode.tool_changes",
                    "gcode.tool_change_speed",
                    "gcode.nozzle_changes",
                ],
                "count": 140,
            },
            "slicer_settings": {
                "description": "Slicer software profile settings (Cura, PrusaSlicer, Simplify3D)",
                "reference": "Ultimaker Cura Wiki, PrusaSlicer Documentation, Simplify3D User Manual",
                "fields": [
                    "slicer.name",
                    "slicer.version",
                    "slicer.profile.name",
                    "slicer.profile.id",
                    "slicer.profile.description",
                    "slicer.quality",
                    "slicer.quality.layer_height",
                    "slicer.quality.layer_height.initial",
                    "slicer.quality.layer_line_width",
                    "slicer.quality.wall_line_count",
                    "slicer.quality.top_bottom_thickness",
                    "slicer.quality.top_layers",
                    "slicer.quality.bottom_layers",
                    "slicer.quality.shell_thickness",
                    "slicer.quality.optimize_wall",
                    "slicer.quality.minimum_wall_line_width",
                    "slicer.quality.wall_transition_angle",
                    "slicer.quality.wall_distribution_count",
                    "slicer.quality.min_wall_line_width_ratio",
                    "slicer.infill",
                    "slicer.infill.density",
                    "slicer.infill.pattern",
                    "slicer.infill.pattern.gyroid",
                    "slicer.infill.pattern.grid",
                    "slicer.infill.pattern.triangles",
                    "slicer.infill.pattern.trihexagon",
                    "slicer.infill.pattern.cubic",
                    "slicer.infill.pattern.cubicsubdiv",
                    "slicer.infill.pattern.octet",
                    "slicer.infill.pattern.lines",
                    "slicer.infill.pattern.zigzag",
                    "slicer.infill.sparse",
                    "slicer.infill.multiplier",
                    "slicer.infill.overlap",
                    "slicer.infill.overlap.percentage",
                    "slicer.infill.gradual_infill_steps",
                    "slicer.infill.gradual_infill_step_height",
                    "slicer.infill.bridge",
                    "slicer.infill.bridge.settings",
                    "slicer.material",
                    "slicer.material.id",
                    "slicer.material.name",
                    "slicer.material.type",
                    "slicer.material.temperature",
                    "slicer.material.temperature.print",
                    "slicer.material.temperature.initial",
                    "slicer.material.temperature.bed",
                    "slicer.material.temperature.vitro",
                    "slicer.material.bed_temperature",
                    "slicer.material.raft",
                    "slicer.material.support",
                    "slicer.material.build_plate",
                    "slicer.material.brim",
                    "slicer.material.materials",
                    "slicer.material.filament_vendor",
                    "slicer.speed",
                    "slicer.speed.print",
                    "slicer.speed.infill",
                    "slicer.speed.wall",
                    "slicer.speed.wall.inner",
                    "slicer.speed.wall.outer",
                    "slicer.speed.topbottom",
                    "slicer.speed.embed",
                    "slicer.speed.support",
                    "slicer.speed.support_interface",
                    "slicer.speed.travel",
                    "slicer.speed.travel_avoid",
                    "slicer.speed.retract",
                    "slicer.speed.initial_layer",
                    "slicer.speed.initial_layer.print",
                    "slicer.speed.initial_layer.travel",
                    "slicer.speed.skirt_brim",
                    "slicer.speed.prime_tower",
                    "slicer.speed.z_hop",
                    "slicer.speed.layer_0",
                    "slicer.speed.smooth",
                    "slicer.travel",
                    "slicer.travel.combing",
                    "slicer.travel.combing_mode",
                    "slicer.travel.avoid_supports",
                    "slicer.travel.avoid_bed",
                    "slicer.travel.avoid_obstacles",
                    "slicer.travel.z_hop_only_retract",
                    "slicer.travel.retract_before_outer_wall",
                    "slicer.support",
                    "slicer.support.enable",
                    "slicer.support.type",
                    "slicer.support.type.interface",
                    "slicer.support.angle",
                    "slicer.support.pattern",
                    "slicer.support.pattern.spacing",
                    "slicer.support.density",
                    "slicer.support.density.percentage",
                    "slicer.support.density.interface",
                    "slicer.support.bridge",
                    "slicer.support.connect_z_overhang",
                    "slicer.support.join_distance",
                    "slicer.support.structures",
                    "slicer.support.adhesion_type",
                    "slicer.support.extruder_nr",
                    "slicer.support.extruder_nr.interface",
                    "slicer.support.extruder_nr.initial",
                    "slicer.support.z_distance",
                    "slicer.support.top_distance",
                    "slicer.support.bottom_distance",
                    "slicer.support.horizontal_expansion",
                    "slicer.support.horizontal_compensation",
                    "slicer.support.stair_step_height",
                    "slicer.support.stair_step_width",
                    "slicer.support.interface_layers",
                    "slicer.support.interface_pattern",
                    "slicer.support.interface_density",
                    "slicer.support.interface_line_width",
                    "slicer.adhesion",
                    "slicer.adhesion.type",
                    "slicer.adhesion.skirt",
                    "slicer.adhesion.skirt.line_count",
                    "slicer.adhesion.skirt.distance",
                    "slicer.adhesion.skirt.min_length",
                    "slicer.adhesion.brim",
                    "slicer.adhesion.brim.line_count",
                    "slicer.adhesion.brim.width",
                    "slicer.adhesion.brim.gap",
                    "slicer.adhesion.raft",
                    "slicer.adhesion.raft.layers",
                    "slicer.adhesion.raft.spacing",
                    "slicer.adhesion.raft.margin",
                    "slicer.adhesion.raft.surface",
                    "slicer.adhesion.raft.surface_layers",
                    "slicer.adhesion.raft.line_width",
                    "slicer.adhesion.raft.speed",
                    "slicer.adhesion.initial_layer",
                    "slicer.adhesion.initial_layer.line_width",
                    "slicer.adhesion.initial_layer.speed",
                    "slicer.adhesion.initial_layer.height",
                    "slicer.adhesion.initial_layer.extrusion",
                    "slicer.adhesion.build_plate",
                    "slicer.adhesion.build_plate.type",
                    "slicer.adhesion.build_plate.temperature",
                ],
                "count": 139,
            },
            "material_properties": {
                "description": "3D printing material and filament properties",
                "reference": "ASTM F42 Additive Manufacturing Standards, Material Supplier Datasheets",
                "fields": [
                    "material.type",
                    "material.filament",
                    "material.resin",
                    "material.powder",
                    "material.composite",
                    "material.family",
                    "material.family.pla",
                    "material.family.abs",
                    "material.family.petg",
                    "material.family.tpu",
                    "material.family.nylon",
                    "material.family.pp",
                    "material.family.pc",
                    "material.family.asa",
                    "material.family.pva",
                    "material.family.bvoh",
                    "material.family.silk",
                    "material.family.wood",
                    "material.family.carbon",
                    "material.family.glow",
                    "material.family.flex",
                    "material.family.hybrid",
                    "material.temperature",
                    "material.temperature.print",
                    "material.temperature.print.min",
                    "material.temperature.print.max",
                    "material.temperature.nozzle",
                    "material.temperature.nozzle.min",
                    "material.temperature.nozzle.max",
                    "material.temperature.bed",
                    "material.temperature.bed.min",
                    "material.temperature.bed.max",
                    "material.temperature.chamber",
                    "material.temperature.chamber.min",
                    "material.temperature.chamber.max",
                    "material.temperature.annealing",
                    "material.temperature.annealing.temp",
                    "material.temperature.annealing.time",
                    "material.filament.diameter",
                    "material.filament.diameter.tolerance",
                    "material.filament.nominal",
                    "material.filament.spool",
                    "material.filament.spool.weight",
                    "material.filament.spool.material",
                    "material.filament.color",
                    "material.filament.color.hex",
                    "material.filament.color.name",
                    "material.filament.density",
                    "material.filament.melt_flow_index",
                    "material.filament.melt_flow_index.value",
                    "material.filament.melt_flow_index.temp",
                    "material.filament.tensile_strength",
                    "material.filament.yield_strength",
                    "material.filament.break_strength",
                    "material.filament.elongation",
                    "material.filament.elongation.at_break",
                    "material.filament.elongation.at_yield",
                    "material.filament.modulus",
                    "material.filament.modulus.elastic",
                    "material.filament.modulus.flexural",
                    "material.filament.impact",
                    "material.filament.impact.strength",
                    "material.filament.impact.notch",
                    "material.filament.hardness",
                    "material.filament.hardness.shore",
                    "material.filament.hardness.rockwell",
                    "material.filament.thermal",
                    "material.filament.thermal.deflection",
                    "material.filament.thermal.softening",
                    "material.filament.thermal.vicat",
                    "material.filament.thermal.expansion",
                    "material.filament.shrinkage",
                    "material.filament.warp",
                    "material.filament.warp.rate",
                    "material.filament.adhesion",
                    "material.filament.interlayer",
                    "material.filament.interlayer.bond",
                    "material.filament.wetting",
                    "material.filament.viscosity",
                    "material.filament.odor",
                    "material.filament.fumes",
                    "material.filament.food_safe",
                    "material.filament.biodegradable",
                    "material.filament.recommended",
                    "material.filament.storage",
                    "material.filament.drying",
                    "material.filament.drying.temp",
                    "material.filament.drying.time",
                    "material.filament.humidity",
                    "material.filament.humidity.storage",
                    "material.vendor",
                    "material.vendor.name",
                    "material.vendor.brand",
                    "material.product.name",
                    "material.product.sku",
                    "material.product.lot",
                    "material.certification",
                    "material.certification.rohs",
                    "material.certification.fda",
                    "material.certification.ul",
                    "material.safety",
                    "material.safety.msds",
                    "material.safety.data",
                ],
                "count": 103,
            },
            "build_parameters": {
                "description": "3D printing build and layer parameters",
                "reference": "ISO/ASTM 52900 Additive Manufacturing Terminology",
                "fields": [
                    "build.layer_height",
                    "build.layer_height.nominal",
                    "build.layer_height.min",
                    "build.layer_height.max",
                    "build.layer_height.initial",
                    "build.first_layer_height",
                    "build.first_layer_height.absolute",
                    "build.first_layer_height.percentage",
                    "build.line_width",
                    "build.line_width.nominal",
                    "build.line_width.wall",
                    "build.line_width.inner",
                    "build.line_width.outer",
                    "build.line_width.topbottom",
                    "build.line_width.initial_layer",
                    "build.line_width.support",
                    "build.infill",
                    "build.infill.density",
                    "build.infill.percentage",
                    "build.infill.pattern",
                    "build.infill.line_distance",
                    "build.infill.overlap",
                    "build.infill.overlap.percentage",
                    "build.infill.gradual_steps",
                    "build.infill.gradual_step_height",
                    "build.walls",
                    "build.walls.count",
                    "build.walls.min",
                    "build.walls.layer0",
                    "build.walls.jerk_oriented",
                    "build.thickness",
                    "build.thickness.top",
                    "build.thickness.bottom",
                    "build.thickness.shell",
                    "build.thickness.min",
                    "build.supports",
                    "build.supports.enable",
                    "build.supports.type",
                    "build.supports.pattern",
                    "build.supports.angle",
                    "build.supports.density",
                    "build.supports.extruder",
                    "build.supports.z_distance",
                    "build.supports.xy_distance",
                    "build.supports.join_distance",
                    "build.supports.stair_step",
                    "build.supports.interface",
                    "build.supports.interface.layers",
                    "build.supports.interface.spacing",
                    "build.brim",
                    "build.brim.enable",
                    "build.brim.width",
                    "build.brim.line_count",
                    "build.brim.gap",
                    "build.brim.outer_only",
                    "build.brim.type",
                    "build.raft",
                    "build.raft.enable",
                    "build.raft.layers",
                    "build.raft.spacing",
                    "build.raft.margin",
                    "build.raft.surface_layers",
                    "build.raft.line_width",
                    "build.raft.speed",
                    "build.skirt",
                    "build.skirt.enable",
                    "build.skirt.line_count",
                    "build.skirt.distance",
                    "build.skirt.min_length",
                    "build.skirt.brim_speed",
                    "build.offset",
                    "build.offset.x",
                    "build.offset.y",
                    "build.offset.z",
                    "build.orientation",
                    "build.orientation.angle",
                    "build.orientation.angle.x",
                    "build.orientation.angle.y",
                    "build.orientation.angle.z",
                    "build.orientation.Optimize",
                    "build.prime",
                    "build.prime.enable",
                    "build.prime.type",
                    "build.prime.blob",
                    "build.prime.amount",
                    "build.prime.speed",
                    "build.prime.position",
                    "build.retraction",
                    "build.retraction.enable",
                    "build.retraction.distance",
                    "build.retraction.speed",
                    "build.retraction.deretraction_speed",
                    "build.retraction.min_travel",
                    "build.retraction.z_hop",
                    "build.retraction.comb",
                    "build.retraction.comb.min",
                    "build.cooling",
                    "build.cooling.fan",
                    "build.cooling.fan_speed",
                    "build.cooling.fan_speed.min",
                    "build.cooling.fan_speed.max",
                    "build.cooling.standby",
                    "build.cooling.initial",
                    "build.cooling.initial.speed",
                    "build.cooling.initial.layer",
                    "build.cooling.full",
                    "build.cooling.full.layer",
                ],
                "count": 107,
            },
        },
        "totals": {
            "categories": 6,
            "total_fields": 698,
        }
    }

    return INVENTORY


def main():
    print("=" * 70)
    print("3D PRINTING METADATA FIELD INVENTORY")
    print("=" * 70)
    print()

    inventory = generate_3dprinting_inventory()

    print(f"Generated: {inventory['generated_at']}")
    print(f"Categories: {inventory['totals']['categories']}")
    print(f"Total Fields: {inventory['totals']['total_fields']}")
    print()

    print("FIELD COUNTS BY CATEGORY:")
    print("-" * 50)
    for cat_name, cat_data in sorted(inventory['categories'].items(), key=lambda x: x[1]['count'], reverse=True):
        print(f"  {cat_name:35s}: {cat_data['count']:>4} fields")

    output_dir = Path("dist/3dprinting_inventory")
    output_dir.mkdir(parents=True, exist_ok=True)

    output_file = output_dir / "3dprinting_inventory.json"
    output_file.write_text(json.dumps(inventory, indent=2, sort_keys=True), encoding="utf-8")
    print()
    print(f"Wrote: {output_file}")

    summary = {
        "generated_at": inventory["generated_at"],
        "description": inventory["description"],
        "categories": {k: {"count": v["count"], "description": v["description"]} for k, v in inventory["categories"].items()},
        "totals": inventory["totals"],
    }

    summary_file = output_dir / "3dprinting_summary.json"
    summary_file.write_text(json.dumps(summary, indent=2, sort_keys=True), encoding="utf-8")
    print(f"Wrote: {summary_file}")


if __name__ == "__main__":
    main()
