#!/usr/bin/env python3
"""3D Format Metadata Field Inventory for MetaExtract.

Covers OBJ, FBX, GLTF/GLB, USD, Blender, 3MF, STL, and other 3D format metadata fields.
"""

from datetime import datetime, timezone
from pathlib import Path


def generate_3d_inventory():
    """Generate comprehensive 3D format metadata field inventory."""

    INVENTORY = {
        "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "source": "Khronos GLTF Spec, Autodesk FBX, USD Format, Wavefront OBJ, 3MF Consortium, STL format",
        "description": "3D format metadata including GLTF, OBJ, FBX, USD, Blender, 3MF, STL, and related 3D formats",
        "categories": {
            "gltf_binary": {
                "description": "GLTF/GLB binary format fields",
                "reference": "https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html",
                "fields": [
                    "gltf.header",
                    "gltf.magic",
                    "gltf.version",
                    "gltf.length",
                    "gltf.scene",
                    "gltf.asset.version",
                    "gltf.asset.generator",
                    "gltf.asset.minVersion",
                    "gltf.extras",
                    "gltf.extensions",
                    "gltf.extensionsRequired",
                    "gltf.extensionsUsed",
                    "gltf.accessors[]",
                    "gltf.accessors[].bufferView",
                    "gltf.accessors[].byteOffset",
                    "gltf.accessors[].componentType",
                    "gltf.accessors[].count",
                    "gltf.accessors[].type",
                    "gltf.accessors[].max",
                    "gltf.accessors[].min",
                    "gltf.accessors[].sparse",
                    "gltf.animations[]",
                    "gltf.animations[].channels[]",
                    "gltf.animations[].channels[].sampler",
                    "gltf.animations[].channels[].target.node",
                    "gltf.animations[].channels[].target.path",
                    "gltf.animations[].name",
                    "gltf.animations[].samplers[]",
                    "gltf.animations[].samplers[].input",
                    "gltf.animations[].samplers[].interpolation",
                    "gltf.animations[].samplers[].output",
                    "gltf.buffers[]",
                    "gltf.buffers[].byteLength",
                    "gltf.buffers[].uri",
                    "gltf.buffers[].name",
                    "gltf.bufferViews[]",
                    "gltf.bufferViews[].buffer",
                    "gltf.bufferViews[].byteOffset",
                    "gltf.bufferViews[].byteLength",
                    "gltf.bufferViews[].byteStride",
                    "gltf.bufferViews[].target",
                    "gltf.bufferViews[].name",
                    "gltf.cameras[]",
                    "gltf.cameras[].type",
                    "gltf.cameras[].perspective",
                    "gltf.cameras[].perspective.aspectRatio",
                    "gltf.cameras[].perspective.yfov",
                    "gltf.cameras[].perspective.zfar",
                    "gltf.cameras[].perspective.znear",
                    "gltf.cameras[].orthographic",
                    "gltf.cameras[].orthographic.xmag",
                    "gltf.cameras[].orthographic.ymag",
                    "gltf.cameras[].orthographic.zfar",
                    "gltf.cameras[].orthographic.znear",
                    "gltf.cameras[].name",
                    "gltf.cameras[].extras",
                    "gltf.images[]",
                    "gltf.images[].uri",
                    "gltf.images[].mimeType",
                    "gltf.images[].bufferView",
                    "gltf.images[].name",
                    "gltf.images[].extras",
                    "gltf.materials[]",
                    "gltf.materials[].name",
                    "gltf.materials[].pbrMetallicRoughness",
                    "gltf.materials[].pbrMetallicRoughness.baseColorFactor",
                    "gltf.materials[].pbrMetallicRoughness.baseColorTexture",
                    "gltf.materials[].pbrMetallicRoughness.metallicFactor",
                    "gltf.materials[].pbrMetallicRoughness.roughnessFactor",
                    "gltf.materials[].pbrMetallicRoughness.metallicRoughnessTexture",
                    "gltf.materials[].normalTexture",
                    "gltf.materials[].normalTexture.scale",
                    "gltf.materials[].normalTexture.index",
                    "gltf.materials[].occlusionTexture",
                    "gltf.materials[].occlusionTexture.strength",
                    "gltf.materials[].occlusionTexture.index",
                    "gltf.materials[].emissiveFactor",
                    "gltf.materials[].emissiveTexture",
                    "gltf.materials[].emissiveTexture.index",
                    "gltf.materials[].alphaMode",
                    "gltf.materials[].alphaCutoff",
                    "gltf.materials[].doubleSided",
                    "gltf.materials[].extensions",
                    "gltf.materials[].extras",
                    "gltf.meshes[]",
                    "gltf.meshes[].name",
                    "gltf.meshes[].primitives[]",
                    "gltf.meshes[].primitives[].attributes",
                    "gltf.meshes[].primitives[].indices",
                    "gltf.meshes[].primitives[].material",
                    "gltf.meshes[].primitives[].mode",
                    "gltf.meshes[].primitives[].targets",
                    "gltf.meshes[].weights[]",
                    "gltf.meshes[].names[]",
                    "gltf.meshes[].extensions",
                    "gltf.meshes[].extras",
                    "gltf.nodes[]",
                    "gltf.nodes[].name",
                    "gltf.nodes[].camera",
                    "gltf.nodes[].children[]",
                    "gltf.nodes[].skin",
                    "gltf.nodes[].matrix",
                    "gltf.nodes[].rotation",
                    "gltf.nodes[].scale",
                    "gltf.nodes[].translation",
                    "gltf.nodes[].weights[]",
                    "gltf.nodes[].extensions",
                    "gltf.nodes[].extras",
                    "gltf.samplers[]",
                    "gltf.samplers[].magFilter",
                    "gltf.samplers[].minFilter",
                    "gltf.samplers[].wrapS",
                    "gltf.samplers[].wrapT",
                    "gltf.samplers[].name",
                    "gltf.samplers[].extras",
                    "gltf.scene",
                    "gltf.scenes[]",
                    "gltf.scenes[].name",
                    "gltf.scenes[].nodes[]",
                    "gltf.scenes[].extras",
                    "gltf.skins[]",
                    "gltf.skins[].inverseBindMatrices",
                    "gltf.skins[].joints[]",
                    "gltf.skins[].skeleton",
                    "gltf.skins[].name",
                    "gltf.skins[].extras",
                    "gltf.textures[]",
                    "gltf.textures[].sampler",
                    "gltf.textures[].source",
                    "gltf.textures[].name",
                    "gltf.textures[].extras",
                    "gltf.extensions",
                    "gltf.extensions.KHR_draco_mesh_compression",
                    "gltf.extensions.KHR_materials_pbrSpecularGlossiness",
                    "gltf.extensions.KHR_materials_unlit",
                    "gltf.extensions.KHR_texture_transform",
                    "gltf.extensions.KHR_mesh_quantization",
                    "gltf.extensions.EXT_meshopt_compression",
                ],
                "count": 120,
            },
            "wavefront_obj": {
                "description": "Wavefront OBJ format fields",
                "reference": "http://www.martinreddy.net/gfx/3d/OBJ-spec.pdf",
                "fields": [
                    "v",
                    "v.x",
                    "v.y",
                    "v.z",
                    "v.w",
                    "vt",
                    "vt.u",
                    "vt.v",
                    "vt.w",
                    "vn",
                    "vn.i",
                    "vn.j",
                    "vn.k",
                    "vp",
                    "vp.u",
                    "vp.v",
                    "vp.w",
                    "p",
                    "l",
                    "f",
                    "f.v1",
                    "f.v2",
                    "f.v3",
                    "f.vt1",
                    "f.vt2",
                    "f.vt3",
                    "f.vn1",
                    "f.vn2",
                    "f.vn3",
                    "fo",
                    "usemtl",
                    "mtllib",
                    "s",
                    "g",
                    "o",
                    "s",
                    "bevel",
                    "bmat",
                    "step_size",
                    "ctech",
                    "stech",
                    "c_interp",
                    "d_interp",
                    "lod",
                    "usemap",
                    "maplib",
                    "bsp",
                    "bpt",
                    "cstype",
                    "cstype.parm",
                    "cstype.deg",
                    "end",
                    "con",
                    "cmd",
                    "r",
                    "mg",
                    "ShadowObj",
                    "ShadowObjSrc",
                    "TraceObj",
                    "TraceObjSrc",
                    "c",
                    "cl",
                    "cal",
                    "cdc",
                    "cdp",
                    "co",
                    "w",
                    "mcs",
                    "gama",
                    "imfchan",
                    "lwm",
                    "密接",
                    "sup",
                    "model",
                    "reverse",
                    "mtl_reverse",
                    "scr",
                    "off",
                    "eq",
                    "ev",
                    "em",
                    "ed",
                    "ns",
                    "ni",
                    "ne",
                    "t",
                    "tm",
                    "lu",
                    "lp",
                    "ipr",
                    "ipo",
                    "icc",
                    "ico",
                    "ir",
                    "ip",
                    "fn",
                    "fr",
                    "fpr",
                    "fpl",
                ],
                "count": 94,
            },
            "stl_format": {
                "description": "STL (Stereolithography) format fields",
                "reference": "https://en.wikipedia.org/wiki/STL_(file_format)",
                "fields": [
                    "solid",
                    "facet.normal",
                    "facet.normal.nx",
                    "facet.normal.ny",
                    "facet.normal.nz",
                    "outer.loop",
                    "vertex",
                    "vertex.x",
                    "vertex.y",
                    "vertex.z",
                    "vertex1",
                    "vertex2",
                    "vertex3",
                    "endloop",
                    "endfacet",
                    "endsolid",
                    "facet.normal",
                    "header",
                    "header.name",
                    "header.byteCount",
                    "triangle.count",
                    "triangle.normal",
                    "triangle.vertex1",
                    "triangle.vertex2",
                    "triangle.vertex3",
                    "attribute.byteCount",
                    "littleEndian",
                    "binary.triangle",
                    "binary.normal",
                    "binary.vertices",
                    "binary.attribute",
                ],
                "count": 30,
            },
            "fbx_format": {
                "description": "Autodesk FBX format fields",
                "reference": "https://docs.unrealengine.com/en-US/ImportingFbxFiles/index.html",
                "fields": [
                    "FBXHeaderExtension",
                    "FBXHeaderVersion",
                    "FBXVersion",
                    "EncryptionType",
                    "CreationTimeStamp",
                    "CreationTimeStamp.Year",
                    "CreationTimeStamp.Month",
                    "CreationTimeStamp.Day",
                    "CreationTimeStamp.Hour",
                    "CreationTimeStamp.Minute",
                    "CreationTimeStamp.Second",
                    "CreationTimeStamp.Millisecond",
                    "Creator",
                    "SceneInfo",
                    "GlobalSettings",
                    "Properties70",
                    "P",
                    "P.Name",
                    "P.Type",
                    "P.Label",
                    "P.TypeName",
                    "P.FolderName",
                    "P.FileName",
                    "P.RelativeFilename",
                    "P.ModelingPackFlag",
                    "P.Transform",
                    "P.Rotation",
                    "P.RotationOffset",
                    "P.RotationPivot",
                    "P.PreRotation",
                    "P.PostRotation",
                    "P.RotationOrder",
                    "P.RotationSpace",
                    "P.RotationStiffness",
                    "P.AxisLen",
                    "P.Pivot",
                    "P.Translation",
                    "P.TranslationActive",
                    "P.TranslationMin",
                    "P.TranslationMax",
                    "P.TranslationLocal",
                    "P.Scaling",
                    "P.ScalingActive",
                    "P.ScalingMin",
                    "P.ScalingMax",
                    "P.ScalingLocal",
                    "P.LclTranslation",
                    "P.LclRotation",
                    "P.LclScaling",
                    "P.RestPose",
                    "P.Visibility",
                    "P.LayeredTexture",
                    "P.Texture",
                    "P.Photo",
                    "P.Video",
                    "P.Material",
                    "P.Constraint",
                    "P.Pose",
                    "P.Morph",
                    "P.Character",
                    "NodeAttribute",
                    "Geometry",
                    "Model",
                    "Material",
                    "Texture",
                    "Video",
                    "AnimationStack",
                    "AnimationLayer",
                    "AnimationCurve",
                    "AnimationCurveNode",
                    "Deformer",
                    "BlendShape",
                    "Skin",
                    "Cluster",
                    "Index",
                    "Transform",
                    "TransformLink",
                    "TransformAssociateModel",
                    "Shape",
                    "Lcl_Animation",
                    "Constraint",
                    "Objects",
                    "Connections",
                    "Takes",
                    "CurrentTake",
                    "Animation",
                ],
                "count": 82,
            },
            "usd_format": {
                "description": "USD (Universal Scene Description) format fields",
                "reference": "https://graphics.pixar.com/usd/docs/index.html",
                "fields": [
                    "upAxis",
                    "metersPerUnit",
                    "centimetersPerUnit",
                    "timeCodesPerSecond",
                    "timeCode",
                    "startTimeCode",
                    "endTimeCode",
                    "author",
                    "copyright",
                    "creationDate",
                    "modificationDate",
                    "description",
                    "title",
                    "subject",
                    "keywords",
                    "comment",
                    "contributor",
                    "creator",
                    "identifier",
                    "language",
                    "publisher",
                    "rights",
                    "source",
                    "type",
                    "version",
                    "prim.path",
                    "prim.typeName",
                    "prim.specifier",
                    "prim.active",
                    "prim.hidden",
                    "prim.instanceable",
                    "prim.variantSets",
                    "prim.variantSet",
                    "prim.variants",
                    "references",
                    "payload",
                    "inheritPaths",
                    "specializes",
                    "xformOpOrder",
                    "xformOp",
                    "xformOp.translate",
                    "xformOp.rotateXYZ",
                    "xformOp.rotateX",
                    "xformOp.rotateY",
                    "xformOp.rotateZ",
                    "xformOp.scale",
                    "xformOp.matrix",
                    "xformOp.pivot",
                    "displayName",
                    "displayGroup",
                    "documentation",
                    "apiSchemas",
                    "customData",
                    "renderSettings",
                    "camera.frustum",
                    "camera.focalLength",
                    "camera.focusDistance",
                    "camera.fStop",
                    "material.binding",
                    "material.diffuseColor",
                    "material.roughness",
                    "material.metallic",
                    "material.normal",
                    "material.emissiveColor",
                    "mesh.points",
                    "mesh.vertexCounts",
                    "mesh.faceVertexIndices",
                    "mesh.faceVertexCounts",
                    "mesh.primvars",
                    "mesh.subdivision",
                    "points.positions",
                    "points.widths",
                    "curves.widths",
                    "curves.lengths",
                    "curves.points",
                    "basisCurves.type",
                    "basisCurves.wrap",
                    "scope.name",
                    "group.name",
                    "over.path",
                    "over.protoPath",
                ],
                "count": 90,
            },
            "blender_format": {
                "description": "Blender format (BLEND) metadata fields",
                "reference": "https://docs.blender.org/manual/en/latest/files/index.html",
                "fields": [
                    "blender.version",
                    "blender.min_version",
                    "blender.file_id",
                    "blender.crc",
                    "scene",
                    "scene.name",
                    "scene.frame_start",
                    "scene.frame_end",
                    "scene.fps",
                    "scene.fps_base",
                    "scene.render",
                    "scene.render.resolution",
                    "scene.render.resolution_x",
                    "scene.render.resolution_y",
                    "scene.render.pixel_aspect_x",
                    "scene.render.pixel_aspect_y",
                    "scene.render.engine",
                    "scene.render.film_transparent",
                    "scene.world",
                    "scene.world.name",
                    "scene.world.use_nodes",
                    "scene.world.node_tree",
                    "camera.name",
                    "camera.data",
                    "camera.data.type",
                    "camera.data.ortho_scale",
                    "camera.data.sensor_width",
                    "camera.data.sensor_height",
                    "camera.data.lens",
                    "camera.data.shift_x",
                    "camera.data.shift_y",
                    "object.name",
                    "object.type",
                    "object.location",
                    "object.rotation_euler",
                    "object.rotation_quaternion",
                    "object.scale",
                    "object.matrix_world",
                    "object.parent",
                    "object.modifiers",
                    "object.modifiers.type",
                    "object.modifiers.name",
                    "object.modifiers.solidify_thickness",
                    "object.modifiers.subdivision_levels",
                    "object.data",
                    "object.data.materials",
                    "object.data.vertices",
                    "object.data.edges",
                    "object.data.polygons",
                    "object.data.uv_layers",
                    "object.data.vertex_colors",
                    "material.name",
                    "material.use_nodes",
                    "material.node_tree",
                    "material.diffuse_color",
                    "material.roughness",
                    "material.metallic",
                    "material.specular_intensity",
                    "material.alpha",
                    "mesh.vertices",
                    "mesh.polygons",
                    "mesh.uv_textures",
                    "mesh.vertex_groups",
                    "mesh.shape_keys",
                    "mesh.smooth",
                    "armature.name",
                    "armature.bones",
                    "armature.pose_position",
                    "action.name",
                    "action.frame_range",
                    "action.fcurves",
                    "action.groups",
                    "texture.name",
                    "texture.type",
                    "texture.image",
                    "texture.image.name",
                    "texture.image.filepath",
                    "texture.image.size",
                    "texture.image.colorspace",
                    "texture.slot.blend_type",
                    "texture.slot.offset",
                    "texture.slot.scale",
                    "world.node_tree",
                    "world.node_tree.nodes",
                    "world.background_color",
                    "linestyle.name",
                    "linestyle.color",
                    "linestyle.thickness",
                    "linestyle.alpha",
                    "cache.file_path",
                    "cache.format",
                    "point_cache",
                    "particle_systems",
                    "particle_settings",
                    "sequence_editor",
                    "sequence_strips",
                    "movieclip.name",
                    "movieclip.source_path",
                    "mask.name",
                    "mask.animation_frame_start",
                    "mask.animation_frame_end",
                ],
                "count": 122,
            },
            "threeMF": {
                "description": "3MF (3D Manufacturing Format) fields",
                "reference": "https://3mf.io/specification/",
                "fields": [
                    "3MF.asssets",
                    "3MF.base",
                    "3MF.model",
                    "3MF.materials",
                    "3MF.slices",
                    "3MF.metadata",
                    "3MF.beam",
                    "3MF.production",
                    "object.type",
                    "object.id",
                    "object.partnumber",
                    "object.name",
                    "mesh.vertices",
                    "mesh.triangleindices",
                    "mesh.position",
                    "mesh.orientation",
                    "mesh.extents",
                    "mesh.extents.minx",
                    "mesh.extents.miny",
                    "mesh.extents.minz",
                    "mesh.extents.maxx",
                    "mesh.extents.maxy",
                    "mesh.extents.maxz",
                    "content.materials",
                    "content.material",
                    "content.type",
                    "content.value",
                    "build.item",
                    "build.objectid",
                    "build.transform",
                    "build.translation",
                    "build.rotation",
                    "build.scale",
                    "build.offset",
                    "slice.references",
                    "slice.height",
                    "slice.service",
                    "slice.polygons",
                    "slice.vertices",
                    "slice.layerheight",
                    "slice.extruder",
                    "beam.lc",
                    "beam.p",
                    "beam.d",
                    "beam.crossover",
                    "beam.nominalfilament",
                    "beam.mesh.position",
                    "beam.mesh.rotation",
                    "beam.mesh.scale",
                    "metadata.name",
                    "metadata.value",
                    "metadata.type",
                    "unit",
                    "unit.mm",
                    "unit.cm",
                    "unit.m",
                    "unit.inch",
                    "unit.foot",
                    "unit.yard",
                    "language",
                    "generator",
                    "generator.application",
                    "generator.version",
                    "generator.platform",
                    "producer",
                    "copyright",
                    "creationdate",
                    "modificationdate",
                    "comment",
                ],
                "count": 72,
            },
            "vr_3dxml": {
                "description": "3DXML (Dassault Systemes) format fields",
                "reference": "https://www.3ds.com/fileautomation/3DXML_Open_Specification.pdf",
                "fields": [
                    "3dxml.root",
                    "3dxml.header",
                    "3dxml.version",
                    "3dxml.productStructure",
                    "3dxml.references",
                    "3dxml.occurrence",
                    "3dxml.instance",
                    "3dxml.reference3D",
                    "3dxml.aggregates",
                    "3dxml.surfaceAttributes",
                    "3dxml.materials",
                    "3dxml.textures",
                    "3dxml.pictures",
                    "3dxml.shaders",
                    "Product",
                    "Product.version",
                    "Product.root",
                    "Product.type",
                    "Product.number",
                    "Product.label",
                    "Product.nature",
                    "Product.description",
                    "Product.vpd",
                    "Product.vpm",
                    "Reference3D",
                    "Reference3D.id",
                    "Reference3D.name",
                    "Reference3D.format",
                    "Reference3D.stream",
                    "Reference3D.aggregates",
                    "Instance3D",
                    "Instance3D.id",
                    "Instance3D.reference",
                    "Instance3D.localisation",
                    "Instance3D.transformation",
                    "Instance3D.matrix",
                    "Occurrence3D",
                    "Occurrence3D.id",
                    "Occurrence3D.parent",
                    "Occurrence3D.reference",
                    "Occurrence3D.localisation",
                    "Occurrence3D.properties",
                    "Material",
                    "Material.name",
                    "Material.type",
                    "Material.diffuseColor",
                    "Material.specularColor",
                    "Material.ambientColor",
                    "Material.emissiveColor",
                    "Material.shininess",
                    "Material.alpha",
                    "Material.texture",
                    "Texture",
                    "Texture.name",
                    "Texture.filename",
                    "Texture.image",
                    "Texture.mimeType",
                    "Texture.width",
                    "Texture.height",
                    "Texture.depth",
                    "Picture",
                    "Picture.name",
                    "Picture.filename",
                    "Picture.data",
                    "Picture.mimeType",
                    "Picture.width",
                    "Picture.height",
                    "Picture.depth",
                    "Shader",
                    "Shader.name",
                    "Shader.type",
                    "Shader.parameters",
                    "Annotation",
                    "Annotation.value",
                    "Annotation.position",
                    "View",
                    "View.name",
                    "View.camera",
                    "View.lookAt",
                    "View.up",
                    "View.projection",
                    "View.fieldOfView",
                    "View.nearPlane",
                    "View.farPlane",
                    "Lighting",
                    "Lighting.type",
                    "Lighting.environment",
                    "Lighting.intensity",
                ],
                "count": 95,
            },
            "x3d_format": {
                "description": "X3D (Web3D) format fields",
                "reference": "https://www.web3d.org/standards",
                "fields": [
                    "X3D.version",
                    "X3D.profile",
                    "X3D.component",
                    "X3D.unit",
                    "X3D.head",
                    "X3D.scene",
                    "Scene.background",
                    "Scene.Fog",
                    "Scene.NavigationInfo",
                    "Scene.Viewpoint",
                    "Scene.background.skyColor",
                    "Scene.background.skyAngle",
                    "Scene.background.bottomUrl",
                    "Scene.background.topUrl",
                    "Scene.Fog.visibilityRange",
                    "Scene.Fog.color",
                    "Scene.NavigationInfo.type",
                    "Scene.NavigationInfo.speed",
                    "Scene.NavigationInfo.avatarSize",
                    "Scene.NavigationInfo.headlight",
                    "Scene.NavigationInfo.collide",
                    "Viewpoint.position",
                    "Viewpoint.orientation",
                    "Viewpoint.centerOfRotation",
                    "Viewpoint.fieldOfView",
                    "Viewpoint.description",
                    "Viewpoint.bind",
                    "Viewpoint.nearClipPlane",
                    "Viewpoint.farClipPlane",
                    "Transform.translation",
                    "Transform.rotation",
                    "Transform.scale",
                    "Transform.center",
                    "Transform.scaleOrientation",
                    "Transform.matrix",
                    "Shape.appearance",
                    "Shape.geometry",
                    "Appearance.material",
                    "Appearance.texture",
                    "Appearance.fillProperties",
                    "Appearance.lineProperties",
                    "Material.diffuseColor",
                    "Material.specularColor",
                    "Material.emissiveColor",
                    "Material.ambientIntensity",
                    "Material.shininess",
                    "Material.transparency",
                    "Material.alpha",
                    "ImageTexture.url",
                    "ImageTexture.repeatS",
                    "ImageTexture.repeatT",
                    "PixelTexture.image",
                    "PixelTexture.repeatS",
                    "PixelTexture.repeatT",
                    "MovieTexture.url",
                    "MovieTexture.loop",
                    "MovieTexture.speed",
                    "Box.size",
                    "Sphere.radius",
                    "Cylinder.radius",
                    "Cylinder.height",
                    "Cone.bottomRadius",
                    "Cone.height",
                    "IndexedFaceSet.coordIndex",
                    "IndexedFaceSet.coord",
                    "IndexedFaceSet.normalIndex",
                    "IndexedFaceSet.texCoordIndex",
                    "IndexedLineSet.coordinateIndex",
                    "IndexedLineSet.coordinate",
                    "IndexedLineSet.colorPerVertex",
                    "Coordinate.point",
                    "Coordinate.normal",
                    "Coordinate.texCoord",
                    "Color.color",
                    "ColorPerVertex",
                    "Normal.vector",
                    "TextureCoordinate.point",
                    "NurbsSurface",
                    "NurbsCurve",
                    "NurbsTrimmedSurface",
                    "GeoLocation",
                    "GeoOrigin",
                    "GeoElevationGrid",
                    "LOD.level",
                    "LOD.range",
                    "Switch.whichChoice",
                    "Switch.choice",
                    "Billboard.axisOfRotation",
                    "Collision.enabled",
                    "Collision.collideTime",
                    "PROTO",
                    "ROUTE",
                    "IS",
                    "field",
                    "fieldType",
                    "fieldAccess",
                    "fieldValue",
                    "externProtoDeclare",
                    "ProtoDeclare",
                    "ProtoInterface",
                    "ProtoImplementation",
                    "ProtoBody",
                    "ProtoInstance",
                ],
                "count": 118,
            },
        },
        "totals": {
            "categories": 9,
            "total_fields": 823,
        }
    }

    return INVENTORY


def main():
    print("=" * 70)
    print("3D FORMAT METADATA FIELD INVENTORY")
    print("=" * 70)
    print()

    inventory = generate_3d_inventory()

    print(f"Generated: {inventory['generated_at']}")
    print(f"Categories: {inventory['totals']['categories']}")
    print(f"Total Fields: {inventory['totals']['total_fields']}")
    print()

    print("FIELD COUNTS BY CATEGORY:")
    print("-" * 50)
    for cat_name, cat_data in sorted(inventory['categories'].items(), key=lambda x: x[1]['count'], reverse=True):
        print(f"  {cat_name:35s}: {cat_data['count']:>4} fields")

    output_dir = Path("dist/3d_inventory")
    output_dir.mkdir(parents=True, exist_ok=True)

    output_file = output_dir / "3d_inventory.json"
    import json
    output_file.write_text(json.dumps(inventory, indent=2, sort_keys=True), encoding="utf-8")
    print()
    print(f"Wrote: {output_file}")

    summary = {
        "generated_at": inventory["generated_at"],
        "description": inventory["description"],
        "categories": {k: {"count": v["count"], "description": v["description"]} for k, v in inventory["categories"].items()},
        "totals": inventory["totals"],
    }

    summary_file = output_dir / "3d_summary.json"
    summary_file.write_text(json.dumps(summary, indent=2, sort_keys=True), encoding="utf-8")
    print(f"Wrote: {summary_file}")


if __name__ == "__main__":
    main()
