#!/usr/bin/env python3
"""Archive Format Metadata Field Inventory for MetaExtract.

Covers ZIP, tar, 7z, RAR, and other archive format metadata fields.
"""

from datetime import datetime, timezone
import json
from pathlib import Path


def generate_archive_inventory():
    """Generate comprehensive archive format metadata field inventory."""

    INVENTORY = {
        "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "source": "ZIP (APPNOTE), tar (POSIX), 7z (7-Zip), RAR5, ISO 9660, DMG, VHD",
        "description": "Archive format metadata including ZIP, tar, 7z, RAR, ISO, DMG, VHD, and related container formats",
        "categories": {
            "zip_central_directory": {
                "description": "ZIP Central Directory record fields",
                "reference": "https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT",
                "fields": [
                    "central_file_header",
                    "signature",
                    "version_made_by",
                    "version_needed",
                    "general_purpose_bit_flag",
                    "compression_method",
                    "last_mod_file_time",
                    "last_mod_file_date",
                    "crc-32",
                    "compressed_size",
                    "uncompressed_size",
                    "file_name_length",
                    "extra_field_length",
                    "file_comment_length",
                    "disk_number_start",
                    "internal_file_attributes",
                    "external_file_attributes",
                    "relative_offset_local_header",
                    "file_name",
                    "extra_field",
                    "file_comment",
                    "number_of_this_disk",
                    "disk_where_cd_starts",
                    "number_of_records_on_disk",
                    "total_number_of_records",
                    "size_of_central_directory",
                    "offset_of_start_of_central_directory",
                    "comment_length",
                    "ZIP64_end_of_central_directory_locator",
                    "ZIP64_end_of_central_directory_record",
                    "ZIP64_end_of_central_directory.offset",
                    "ZIP64_end_of_central_directory.size",
                    "ZIP64_end_of_central_directory.number_of_entries",
                ],
                "count": 34,
            },
            "zip_local_header": {
                "description": "ZIP Local File Header fields",
                "reference": "https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT",
                "fields": [
                    "local_file_header",
                    "signature",
                    "version_needed_to_extract",
                    "general_purpose_bit_flag",
                    "compression_method",
                    "last_mod_file_time",
                    "last_mod_file_date",
                    "crc-32",
                    "compressed_size",
                    "uncompressed_size",
                    "file_name_length",
                    "extra_field_length",
                    "file_name",
                    "extra_field",
                    "data_descriptor",
                    "data_descriptor.signature",
                    "data_descriptor.crc-32",
                    "data_descriptor.compressed_size",
                    "data_descriptor.uncompressed_size",
                    "ZIP64_extended_information_extra_field",
                    "extensible_data_fields",
                    "file_name_encoding",
                    "encrypted_file_header",
                    "encryption_header",
                    "check_byte",
                    "last_mod_time",
                    "last_mod_date",
                    "dos_time",
                    "dos_date",
                    "ntfs_time",
                    "ntfs_mtime",
                    "ntfs_atime",
                    "ntfs_ctime",
                    "unix_uid",
                    "unix_gid",
                    "unix_mode",
                ],
                "count": 34,
            },
            "zip64_format": {
                "description": "ZIP64 format extension fields",
                "reference": "https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT",
                "fields": [
                    "ZIP64_extended_information_extra_field",
                    "tag",
                    "size",
                    "original_size",
                    "compressed_size",
                    "relative_header_offset",
                    "disk_number_start",
                    "ZIP64_end_of_central_directory_record",
                    "signature",
                    "size_of_record",
                    "version_made_by",
                    "version_needed",
                    "number_of_this_disk",
                    "disk_where_cd_starts",
                    "number_of_records_on_this_disk",
                    "total_number_of_entries_on_this_disk",
                    "size_of_central_directory",
                    "offset_of_start_of_central_directory",
                    "extensible_sector",
                    "ZIP64_end_of_central_directory_locator",
                    "signature",
                    "disk_where_cd_starts",
                    "offset_of_cd_record",
                    "total_number_of_disks",
                    "ZIP64_central_directory_extensible",
                ],
                "count": 25,
            },
            "zip_encryption": {
                "description": "ZIP encryption and password protection fields",
                "reference": "https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT",
                "fields": [
                    "encryption_header",
                    "check_byte",
                    "encryption_algorithm",
                    "weak_key_detection",
                    "key_correction",
                    "key_length",
                    "key",
                    "verification_bytes",
                    "compressed_data",
                    "decryption_header",
                    "crypto_metadata",
                    "AE-1",
                    "AE-2",
                    "AES256",
                    "aes_version",
                    "vendor_id",
                    "aes_mode",
                    "compression_method",
                    "password_verifier",
                    "auth_code",
                    "password_check",
                    "integrity_check",
                    "check_value",
                    "block_cipher",
                    "iv_length",
                    "key_length",
                    "salt_length",
                    "salt_value",
                    "iv_value",
                    "cipher_text",
                    "hmac",
                    "pad",
                ],
                "count": 31,
            },
            "posix_tar": {
                "description": "POSIX tar (USTAR/POSIX.1-2001) header fields",
                "reference": "https://pubs.opengroup.org/onlinepubs/9699919799/utilities/pax.html",
                "fields": [
                    "name",
                    "mode",
                    "uid",
                    "gid",
                    "size",
                    "mtime",
                    "chksum",
                    "typeflag",
                    "linkname",
                    "magic",
                    "version",
                    "uname",
                    "gname",
                    "devmajor",
                    "devminor",
                    "atime",
                    "ctime",
                    "offset",
                    "longname",
                    "size",
                    "gnu_longname",
                    "gnu_sparse",
                    "gnu_sparse.major",
                    "gnu_sparse.minor",
                    "gnu_sparse.realsize",
                    "pax_header",
                    "pax_global_header",
                    "pax_attribute",
                    "pax_keyword",
                    "pax_value",
                    "ustar.magic",
                    "ustar.version",
                    "ustar.name",
                    "ustar.mode",
                    "ustar.uid",
                    "ustar.gid",
                    "ustar.size",
                    "ustar.mtime",
                    "ustar.chksum",
                    "ustar.typeflag",
                    "ustar.linkname",
                    "ustar.uname",
                    "ustar.gname",
                    "ustar.devmajor",
                    "ustar.devminor",
                ],
                "count": 43,
            },
            "gnu_tar_extensions": {
                "description": "GNU tar extensions and sparse file support",
                "reference": "GNU tar documentation",
                "fields": [
                    "GNU.sparse.name",
                    "GNU.sparse.realsize",
                    "GNU.sparse.offset",
                    "GNU.sparse.numbytes",
                    "GNU.sparse.map",
                    "GNU.sparse.ahx",
                    "GNU.sparse.at",
                    "GNU.extensions",
                    "GNU.volume.label",
                    "GNU.volume.size",
                    "GNU.chksum",
                    "GNU.privs",
                    "GNU.machine",
                    "GNU.name.prefix",
                    "GNU.renamed",
                    "GNU.dumpdir",
                    "GNU.linker",
                    "GNU.realsize",
                    "GNU.offset",
                    "GNU.sparse.status",
                    "GNU.sparse.major",
                    "GNU.sparse.minor",
                    "star.header",
                    "star.magic",
                    "star.padding",
                    "star.arch",
                    "star.atime",
                    "star.ctime",
                    "star.birthtime",
                    "star.filetype",
                    "star.flags",
                    "star.strlen",
                    "star.restype",
                    "star.nlink",
                    "star.check",
                    "star.sparse",
                    "star.realsize",
                ],
                "count": 36,
            },
            "seven_zip": {
                "description": "7z (7-Zip) format fields",
                "reference": "https://www.7-zip.org/7z.html",
                "fields": [
                    "7z.Header",
                    "7z.MainHeader",
                    "7z.ArchiveProperties",
                    "7z.AdditionalStreamsInfo",
                    "7z.MainStreamsInfo",
                    "7z.FilesInfo",
                    "7z.StartHeader",
                    "7z.Version",
                    "7z.StartHeaderSize",
                    "7z.StartHeaderCrc",
                    "7z.ArchiveStartPosition",
                    "7z.ArchiveStartPositionInVolume",
                    "7z.Folders",
                    "7z.Coders",
                    "7z.Bond",
                    "7z.BindPair",
                    "7z.CRCs",
                    "7z.Encrypted",
                    "7z.ST_SIZE",
                    "7z.Folder",
                    "7z.CRC",
                    "7z.File",
                    "7z.FileNames",
                    "7z.FileTime",
                    "7z.FileAttributes",
                    "7z.Stream",
                    "7z.AdditionalStreams",
                    "7z.Method",
                    "7z.Property",
                    "7z.HeaderCRC",
                    "7z.EncodedHeader",
                    "7z.CompressedStream",
                    "7z.UnpackSize",
                    "7z.NumPackStreams",
                    "7z.Coder",
                    "7z.MethodID",
                    "7z.Properties",
                    "7z.NumBindPairs",
                    "7z.NumInStreams",
                    "7z.NumOutStreams",
                    "7z.AES",
                    "7z.BZip2",
                    "7z.Deflate",
                    "7z.LZMA",
                    "7z.PPMD",
                ],
                "count": 44,
            },
            "rar_format": {
                "description": "RAR5 format header and block fields",
                "reference": "https://www.rarlab.com/technote.htm",
                "fields": [
                    "RAR.signature",
                    "RAR.version",
                    "RAR.header_type",
                    "RAR.flags",
                    "RAR.header_size",
                    "RAR.extra_size",
                    "RAR.data_size",
                    "RAR.archive_flags",
                    "RAR.archive_encryption",
                    "RAR.archive_volume",
                    "RAR.archive_solid",
                    "RAR.archive_recovery",
                    "RAR.file_flags",
                    "FILE.name_length",
                    "FILE.name",
                    "FILE.mtime",
                    "FILE.crc",
                    "FILE.uncompressed_size",
                    "FILE.compressed_size",
                    "FILE.compression_method",
                    "FILE.file_attributes",
                    "FILE.encryption",
                    "FILE.host_os",
                    "FILE.data_crc",
                    "FILE.file_time",
                    "FILE.creation_time",
                    "FILE.access_time",
                    "FILE.attributes",
                    "FILE.name_encoded",
                    "FILE.redir_type",
                    "FILE.redir_flags",
                    "FILE.redir_name",
                    "FILE.wnd_size",
                    "FILE.wnd_addr",
                    "BLOCK.CRC",
                    "BLOCK.size",
                    "BLOCK.type",
                    "BLOCK.flags",
                    "BLOCK.extra",
                    "BLOCK.data",
                    "END.signature",
                    "END.location",
                    "END.arc_size",
                    "END.encrypt_ver",
                    "END.encrypt_strength",
                    "END.last_block",
                    "END.enc_data",
                ],
                "count": 46,
            },
            "iso9660": {
                "description": "ISO 9660 (ECMA-119) directory record fields",
                "reference": "https://www.ecma-international.org/publications-and-standards/standards/ecma-119/",
                "fields": [
                    "length",
                    "extended_attribute_record_length",
                    "location_of_extent",
                    "data_length",
                    "recording_date_and_time",
                    "file_flags",
                    "file_unit_size",
                    "interleave_gap_size",
                    "volume_sequence_number",
                    "length_of_file_identifier",
                    "file_identifier",
                    "padding_field",
                    "system_use",
                    "volume_descriptor_type",
                    "volume_descriptor_version",
                    "system_id",
                    "volume_id",
                    "volume_space_size",
                    "volume_set_id",
                    "publisher_id",
                    "preparer_id",
                    "application_id",
                    "copyright_file_id",
                    "abstract_file_id",
                    "bibliographic_file_id",
                    "volume_creation_date",
                    "volume_modification_date",
                    "volume_expiration_date",
                    "volume_effective_date",
                    "file_structure_version",
                    "application_use",
                    "root_directory_record",
                    "path_table_location",
                    "path_table_size",
                    "type_L_path_table",
                    "type_M_path_table",
                    "directory_record",
                    "XOR_offsets",
                    "Eltorito.boot",
                    "Eltorito.boot_catalog",
                    "Eltorito.boot_image",
                    "UDF.anchor",
                    "UDF.vds",
                    "UDF.bt",
                    "UDF.fsd",
                ],
                "count": 45,
            },
            "apple_dmg": {
                "description": "Apple DMG (UDRW/SPARSE/BZIP2/XAR) format fields",
                "reference": "https://github.com/aurora/opendmg",
                "fields": [
                    "DMG.signature",
                    "DMG.version",
                    "DMG.header_size",
                    "DMG.flags",
                    "DMG.run_count",
                    "DMG.run_data",
                    "XML.koly",
                    "XML.plist",
                    "XML.seg_num",
                    "XML.seg_off",
                    "XML.seg_len",
                    "XML.UDWO",
                    "XML.COW",
                    "XML.SPARSE",
                    "XML.SPARSEBUNDLE",
                    "XML.GPT",
                    "XML.HFS",
                    "XML.jumpstart",
                    "XML.com.apple.boot",
                    "XML.integral",
                    "XML.encrypted",
                    "XML.encryption_type",
                    "XML.efi_start",
                    "XML.efi_len",
                    "XML.checksum",
                    "XML.block_size",
                    "XML.blocks",
                    "XML.freespace",
                    "XML.unique",
                    "XML.CFUUID",
                    "XML.timestamp",
                    "XML.system_domain",
                    "XML.os_version",
                    "XML.build_version",
                    "XML.signature",
                    "XML.signature_2",
                    "UDF.PrimaryVolumeDescriptor",
                    "UDF.SecondaryVolumeDescriptor",
                    "UDF.AnchorVolumeDescriptor",
                    "UDF.LogicalVolumeDescriptor",
                    "UDF.FileSetDescriptor",
                    "UDF.FileEntry",
                    "UDF.ExtendedAttribute",
                    "UDF.AllocationDescriptor",
                ],
                "count": 44,
            },
            "vhd": {
                "description": "VHD (Virtual Hard Disk) format fields",
                "reference": "https://docs.microsoft.com/en-us/previous-versions/windows/desktop/legacy/dd323700(v=vs.85)",
                "fields": [
                    "VHD.footer.signature",
                    "VHD.footer.features",
                    "VHD.footer.format_version",
                    "VHD.footer.data_offset",
                    "VHD.footer.time_stamp",
                    "VHD.footer.creator_application",
                    "VHD.footer.creator_version",
                    "VHD.footer.creator_host_os",
                    "VHD.footer.original_size",
                    "VHD.footer.current_size",
                    "VHD.footer.geometry.cylinders",
                    "VHD.footer.geometry.heads",
                    "VHD.footer.geometry.sectors_per_track",
                    "VHD.footer.disk_type",
                    "VHD.footer.checksum",
                    "VHD.footer.unique_id",
                    "VHD.footer.saved_state",
                    "VHD.header.signature",
                    "VHD.header.table_offset",
                    "VHD.header.header_version",
                    "VHD.header.max_table_entries",
                    "VHD.header.block_size",
                    "VHD.header.parent_unique_id",
                    "VHD.header.parent_time_stamp",
                    "VHD.header.reserved",
                    "VHD.header.parent_name",
                    "VHD.header.locator_entry[0]",
                    "VHD.header.locator_entry[1]",
                    "VHD.header.locator_entry[2]",
                    "VHD.header.locator_entry[3]",
                    "VHD.header.locator_entry[4]",
                    "VHD.header.locator_entry[5]",
                    "VHD.header.locator_entry[6]",
                    "VHD.header.locator_entry[7]",
                    "VHD.bat.bat_header",
                    "VHD.bat.bat_entries",
                    "VHD.sector.sector_map",
                    "VHD.differencing.parent",
                    "VHD.differencing.bitmap",
                    "VHD.dyndisk.mt",
                    "VHD.fixed.footer",
                    "VHD.vhdx.footer",
                    "VHD.vhdx.header",
                    "VHD.vhdx.metadata",
                ],
                "count": 41,
            },
            "xz_format": {
                "description": "XZ (LZMA2) format fields",
                "reference": "https://tukaani.org/xz/xz-file-format.txt",
                "fields": [
                    "XZ.stream_header",
                    "XZ.stream_flags",
                    "XZ.backward_size",
                    "XZ.stream_footer",
                    "XZ.block_header",
                    "XZ.block_flags",
                    "XZ.block.compressed_size",
                    "XZ.block.uncompressed_size",
                    "XZ.block.filter_count",
                    "XZ.filter.id",
                    "XZ.filter.options",
                    "LZMA2_props",
                    "LZMA2_props.dict_size",
                    "LZMA2_props.lzma_version",
                    "LZMA2_props.lzma_dict_size",
                    "LZMA2_props.lzma_fast",
                    "LZMA2_props.lzma_mode",
                    "LZMA2_props.lzma_nice_len",
                    "LZMA2_props.lzma.mf",
                    "XZ.check.type",
                    "XZ.check.size",
                    "XZ.check.crc32",
                    "XZ.check.crc64",
                    "XZ.check.sha256",
                    "XZ.index.record.count",
                    "XZ.index.record.unpadded",
                    "XZ.index.record.uncompressed",
                    "XZ.index.indicator",
                    "XZ.index.padding",
                    "XZ.stream_flags.decode",
                    "XZ.block_header.decode",
                    "XZ.filter_flags.decode",
                ],
                "count": 31,
            },
            "zstd_format": {
                "description": "Zstandard (zstd) format fields",
                "reference": "https://datatracker.ietf.org/doc/html/rfc8878",
                "fields": [
                    "ZSTD.frame_header",
                    "ZSTD.magic_number",
                    "ZSTD.frame_descriptor",
                    "ZSTD.frame_content_size_flag",
                    "ZSTD.single_segment_flag",
                    "ZSTD.reserved_flag",
                    "ZSTD.dictionary_id_flag",
                    "ZSTD.sequence_compression_flag",
                    "ZSTD.content_checksum_flag",
                    "ZSTD.header_size",
                    "ZSTD.window_log",
                    "ZSTD.dict_id",
                    "ZSTD.dict_log",
                    "ZSTD.min_match",
                    "ZSTD.target_length",
                    "ZSTD.max_bracket_id",
                    "ZSTD.target_prefix_max_parsed",
                    "ZSTD.block_max_size",
                    "ZSTD.tseg_commit_flag",
                    "ZSTD.tseg_nb_seq_max",
                    "ZSTD.skippable_frame",
                    "ZSTD.skippable_magic",
                    "ZSTD.skippable_size",
                    "ZSTD.data",
                    "ZSTD.legacy_frame",
                    "ZSTD.legacy_magic",
                    "ZSTD.legacy_version",
                    "ZSTD.legacy_descriptor",
                    "ZSTD.checksum",
                    "ZSTD.segment_header",
                    "ZSTD.literal_length_header",
                    "ZSTD.literals_block_type",
                    "ZSTD.literals_compressed",
                    "ZSTD.literals_raw",
                    "ZSTD.literals.rle",
                    "ZSTD.sequence_header",
                    "ZSTD.sequence.offsets",
                    "ZSTD.sequence.lengths",
                    "ZSTD.prefix.start",
                    "ZSTD.prefix.end",
                    "ZSTD.dictionary.content",
                    "ZSTD.dictionary.ids",
                ],
                "count": 41,
            },
            "brotli_format": {
                "description": "Brotli format fields",
                "reference": "https://github.com/google/brotli/blob/master/docs/spec.md",
                "fields": [
                    "BROTLI.signature",
                    "BROTLI.window_bits",
                    "BROTLI.literal_context_bits",
                    "BROTLI.distance_context_bits",
                    "BROTLI.num_literal_插入s",
                    "BROTLI.num_commands",
                    "BROTLI.num_direct_distance_codes",
                    "BROTLI.postfix",
                    "BROTLI.distance_postfix",
                    "BROTLI.block_count",
                    "BROTLI.block_count.literal",
                    "BROTLI.block_count.distance",
                    "BROTLI.block_length.literal",
                    "BROTLI.block_length.distance",
                    "BROTLI.stream_offset",
                    "BROTLI.compressed_size",
                    "BROTLI.uncompressed_size",
                    "BROTLI.is_last",
                    "BROTLI.insert_copy_length",
                    "BROTLI.copy_length",
                    "BROTLI.distance_code",
                    "BROTLI.distance_short",
                    "BROTLI.distance_value",
                    "BROTLI.literal",
                    "BROTLI.command",
                    "BROTLI.huffman",
                    "BROTLI.prefix.code",
                    "BROTLI.prefix.extra",
                    "BROTLI.huffman_count",
                    "BROTLI.huffman.tree",
                    "BROTLI.huffman.bits",
                    "BROTLI.huffman.values",
                    "BROTLI.meta-block",
                    "BROTLI.metacount",
                    "BROTLI.metadata_length",
                    "BROTLI.padding",
                ],
                "count": 35,
            },
        },
        "totals": {
            "categories": 14,
            "total_fields": 530,
        }
    }

    return INVENTORY


def main():
    print("=" * 70)
    print("ARCHIVE FORMAT METADATA FIELD INVENTORY")
    print("=" * 70)
    print()

    inventory = generate_archive_inventory()

    print(f"Generated: {inventory['generated_at']}")
    print(f"Categories: {inventory['totals']['categories']}")
    print(f"Total Fields: {inventory['totals']['total_fields']}")
    print()

    print("FIELD COUNTS BY CATEGORY:")
    print("-" * 50)
    for cat_name, cat_data in sorted(inventory['categories'].items(), key=lambda x: x[1]['count'], reverse=True):
        print(f"  {cat_name:35s}: {cat_data['count']:>4} fields")

    output_dir = Path("dist/archive_inventory")
    output_dir.mkdir(parents=True, exist_ok=True)

    output_file = output_dir / "archive_inventory.json"
    output_file.write_text(str(inventory), encoding="utf-8")
    print()
    print(f"Wrote: {output_file}")

    summary = {
        "generated_at": inventory["generated_at"],
        "description": inventory["description"],
        "categories": {k: {"count": v["count"], "description": v["description"]} for k, v in inventory["categories"].items()},
        "totals": inventory["totals"],
    }

    summary_file = output_dir / "archive_summary.json"
    summary_file.write_text(str(summary), encoding="utf-8")
    print(f"Wrote: {summary_file}")


if __name__ == "__main__":
    main()
