#!/usr/bin/env python3
"""Container Format Metadata Field Inventory for MetaExtract.

Covers Docker images, OCI specs, Kubernetes manifests, container orchestration,
and related container format metadata fields.
"""

import json
from datetime import datetime, timezone
from pathlib import Path


def generate_containers_inventory():
    """Generate comprehensive container format metadata field inventory."""

    INVENTORY = {
        "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "source": "OCI Image Spec v1.1, Docker v2.2, Kubernetes manifests, Containerd, CRI-O",
        "description": "Container format metadata including Docker images, OCI specs, Kubernetes manifests, and orchestration metadata",
        "categories": {
            "oci_image_manifest": {
                "description": "OCI Image Manifest Specification v1.1 fields",
                "reference": "https://github.com/opencontainers/image-spec/blob/main/manifest.md",
                "fields": [
                    "schemaVersion",
                    "mediaType",
                    "config.mediaType",
                    "config.digest",
                    "config.size",
                    "layers[].mediaType",
                    "layers[].digest",
                    "layers[].size",
                    "layers[].urls",
                    "annotations",
                    "subject",
                    "artifactType",
                    "manifests[].mediaType",
                    "manifests[].digest",
                    "manifests[].size",
                    "manifests[].platform.os",
                    "manifests[].platform.os.version",
                    "manifests[].platform.os.features",
                    "manifests[].platform.architecture",
                    "manifests[].platform.variant",
                    "manifests[].platform.features",
                    "manifests[].annotations",
                ],
                "count": 22,
            },
            "oci_image_index": {
                "description": "OCI Image Index (Multi-architecture manifest) fields",
                "reference": "https://github.com/opencontainers/image-spec/blob/main/image-index.md",
                "fields": [
                    "schemaVersion",
                    "mediaType",
                    "manifests[].mediaType",
                    "manifests[].digest",
                    "manifests[].size",
                    "manifests[].platform.os",
                    "manifests[].platform.os.version",
                    "manifests[].platform.architecture",
                    "manifests[].platform.variant",
                    "manifests[].platform.features",
                    "manifests[].annotations",
                    "manifests[].subject",
                    "manifests[].artifactType",
                    "annotations",
                    "subject",
                ],
                "count": 15,
            },
            "oci_config_blob": {
                "description": "OCI Image Configuration (Config blob) fields",
                "reference": "https://github.com/opencontainers/image-spec/blob/main/config.md",
                "fields": [
                    "created",
                    "author",
                    "architecture",
                    "os",
                    "os.version",
                    "os.features",
                    "variant",
                    "architecture",
                    "config.User",
                    "config.WorkingDir",
                    "config.Labels",
                    "config.Cmd",
                    "config.Entrypoint",
                    "config.ExposedPorts",
                    "config.Env",
                    "config.Volumes",
                    "config.Hostname",
                    "config.Domainname",
                    "config.AttachStdin",
                    "config.OpenStdin",
                    "config.Tty",
                    "config.AttachStdout",
                    "config.AttachStderr",
                    "config.ExposedPorts",
                    "config.Healthcheck.Test",
                    "config.Healthcheck.Interval",
                    "config.Healthcheck.Timeout",
                    "config.Healthcheck.Retries",
                    "config.Healthcheck.StartPeriod",
                    "config.Healthcheck.ExposedForm",
                    "rootfs.type",
                    "rootfs.diff_ids",
                    "history[].created",
                    "history[].author",
                    "history[].created_by",
                    "history[].comment",
                    "history[].empty_layer",
                ],
                "count": 38,
            },
            "docker_manifest_v1": {
                "description": "Docker Manifest Schema v1 fields (legacy)",
                "reference": "Docker Image Manifest V2 Schema 1",
                "fields": [
                    "schemaVersion",
                    "name",
                    "tag",
                    "architecture",
                    "fsLayers[].blobSum",
                    "history[].v1Compatibility",
                    "manifests[].mediaType",
                    "manifests[].size",
                    "manifests[].digest",
                    "manifests[].platform.architecture",
                    "manifests[].platform.os",
                    "manifests[].platform.os.version",
                    "manifests[].platform.variant",
                    "manifests[].platform.features",
                    "manifests[].annotations",
                    "config.digest",
                    "config.mediaType",
                ],
                "count": 17,
            },
            "docker_manifest_v2_s2": {
                "description": "Docker Manifest Schema v2 fields (Docker 2.2+)",
                "reference": "Docker Image Manifest V2 Schema 2",
                "fields": [
                    "schemaVersion",
                    "mediaType",
                    "config.mediaType",
                    "config.digest",
                    "config.size",
                    "layers[].mediaType",
                    "layers[].digest",
                    "layers[].size",
                ],
                "count": 8,
            },
            "docker_content_trust": {
                "description": "Docker Content Trust (Notary) metadata fields",
                "reference": "Docker Content Trust / Notary Protocol",
                "fields": [
                    "signatures[].key_id",
                    "signatures[].signer_role",
                    "signatures[].signature",
                    "signed[].name",
                    "signed[].tag",
                    "signed[].digest",
                    "signed[].history[].created",
                    "signed[].history[].author",
                    "signed[].history[].command",
                    "signed[].metadata.name",
                    "signed[].metadata.tag",
                    "tuf.keys[].keyid",
                    "tuf.keys[].keyval",
                    "tuf.keys[].role",
                    "tuf.snapshot.version",
                    "tuf.timestamp.version",
                    "tuf.snapshot.expires",
                    "tuf.timestamp.expires",
                    "tuf.snapshot.signed",
                    "tuf.timestamp.signed",
                ],
                "count": 20,
            },
            "kubernetes_pod": {
                "description": "Kubernetes Pod specification fields",
                "reference": "https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.28/#podspec-v1-core",
                "fields": [
                    "apiVersion",
                    "kind",
                    "metadata.name",
                    "metadata.namespace",
                    "metadata.uid",
                    "metadata.resourceVersion",
                    "metadata.generateName",
                    "metadata.labels",
                    "metadata.annotations",
                    "metadata.ownerReferences",
                    "spec.volumes",
                    "spec.initContainers",
                    "spec.containers",
                    "spec.serviceAccountName",
                    "spec.serviceAccount",
                    "spec.automountServiceAccountToken",
                    "spec.nodeName",
                    "spec.hostNetwork",
                    "spec.hostPID",
                    "spec.hostIPC",
                    "spec.hostname",
                    "spec.subdomain",
                    "spec.affinity",
                    "spec.nodeSelector",
                    "spec.restartPolicy",
                    "spec.terminationGracePeriodSeconds",
                    "spec.activeDeadlineSeconds",
                    "spec.dnsPolicy",
                    "spec.nodeSelectorTerms",
                    "spec.imagePullSecrets",
                    "spec.initContainers[].name",
                    "spec.initContainers[].image",
                    "spec.initContainers[].command",
                    "spec.initContainers[].args",
                    "spec.initContainers[].workingDir",
                    "spec.initContainers[].volumeMounts",
                    "spec.initContainers[].env",
                    "spec.initContainers[].resources",
                    "spec.containers[].name",
                    "spec.containers[].image",
                    "spec.containers[].command",
                    "spec.containers[].args",
                    "spec.containers[].workingDir",
                    "spec.containers[].ports",
                    "spec.containers[].env",
                    "spec.containers[].envFrom",
                    "spec.containers[].volumeMounts",
                    "spec.containers[].livenessProbe",
                    "spec.containers[].readinessProbe",
                    "spec.containers[].startupProbe",
                    "spec.containers[].resources",
                    "spec.containers[].securityContext",
                    "spec.containers[].imagePullPolicy",
                    "status.phase",
                    "status.conditions",
                    "status.podIP",
                    "status.hostIP",
                    "status.qosClass",
                ],
                "count": 56,
            },
            "kubernetes_deployment": {
                "description": "Kubernetes Deployment specification fields",
                "reference": "https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.28/#deploymentSpec-v1-apps",
                "fields": [
                    "apiVersion",
                    "kind",
                    "metadata.name",
                    "metadata.namespace",
                    "metadata.uid",
                    "metadata.labels",
                    "metadata.annotations",
                    "spec.replicas",
                    "spec.selector",
                    "spec.selector.matchLabels",
                    "spec.selector.matchExpressions",
                    "spec.template",
                    "spec.template.metadata",
                    "spec.template.spec",
                    "spec.strategy.type",
                    "spec.strategy.rollingUpdate.maxUnavailable",
                    "spec.strategy.rollingUpdate.maxSurge",
                    "spec.strategy.recreate.pause",
                    "spec.minReadySeconds",
                    "spec.revisionHistoryLimit",
                    "spec.paused",
                    "spec.progressDeadlineSeconds",
                    "spec.selector.matchLabels",
                    "status.replicas",
                    "status.readyReplicas",
                    "status.availableReplicas",
                    "status.unavailableReplicas",
                    "status.observedGeneration",
                    "status.conditions.type",
                    "status.conditions.status",
                    "status.conditions.reason",
                    "status.conditions.message",
                    "status.conditions.lastTransitionTime",
                ],
                "count": 32,
            },
            "kubernetes_configmap": {
                "description": "Kubernetes ConfigMap fields",
                "reference": "https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.28/#configmap-v1-core",
                "fields": [
                    "apiVersion",
                    "kind",
                    "metadata.name",
                    "metadata.namespace",
                    "metadata.uid",
                    "metadata.resourceVersion",
                    "metadata.labels",
                    "metadata.annotations",
                    "data",
                    "binaryData",
                    "immutable",
                ],
                "count": 11,
            },
            "kubernetes_secret": {
                "description": "Kubernetes Secret fields",
                "reference": "https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.28/#secret-v1-core",
                "fields": [
                    "apiVersion",
                    "kind",
                    "metadata.name",
                    "metadata.namespace",
                    "metadata.uid",
                    "metadata.resourceVersion",
                    "metadata.labels",
                    "metadata.annotations",
                    "type",
                    "data",
                    "stringData",
                    "immutable",
                ],
                "count": 12,
            },
            "kubernetes_service": {
                "description": "Kubernetes Service specification fields",
                "reference": "https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.28/#serviceSpec-v1-core",
                "fields": [
                    "apiVersion",
                    "kind",
                    "metadata.name",
                    "metadata.namespace",
                    "metadata.labels",
                    "metadata.annotations",
                    "spec.type",
                    "spec.clusterIP",
                    "spec.externalIPs",
                    "spec.externalName",
                    "spec.externalTrafficPolicy",
                    "spec.healthCheckNodePort",
                    "spec.ports[].name",
                    "spec.ports[].protocol",
                    "spec.ports[].port",
                    "spec.ports[].targetPort",
                    "spec.ports[].nodePort",
                    "spec.selector",
                    "spec.sessionAffinity",
                    "spec.sessionAffinityConfig.clientIP.timeoutSeconds",
                    "spec.loadBalancerIP",
                    "spec.loadBalancerSourceRanges",
                    "spec.publishNotReadyAddresses",
                    "status.loadBalancer.ingress",
                ],
                "count": 23,
            },
            "kubernetes_ingress": {
                "description": "Kubernetes Ingress specification fields",
                "reference": "https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.28/#ingressSpec-v1-networking-k8s-io",
                "fields": [
                    "apiVersion",
                    "kind",
                    "metadata.name",
                    "metadata.namespace",
                    "metadata.labels",
                    "metadata.annotations",
                    "spec.ingressClassName",
                    "spec.defaultBackend",
                    "spec.defaultBackend.service.name",
                    "spec.defaultBackend.service.port",
                    "spec.rules[].host",
                    "spec.rules[].http.paths[].path",
                    "spec.rules[].http.paths[].pathType",
                    "spec.rules[].http.paths[].backend.service.name",
                    "spec.rules[].http.paths[].backend.service.port.number",
                    "spec.rules[].http.paths[].backend.service.port.name",
                    "spec.rules[].http.paths[].backend.resource.apiGroup",
                    "spec.rules[].http.paths[].backend.resource.kind",
                    "spec.tls[].secretName",
                    "spec.tls[].hosts",
                    "spec.tls[].issuerRef.name",
                    "spec.tls[].issuerRef.kind",
                    "status.loadBalancer.ingress",
                ],
                "count": 22,
            },
            "containerd_config": {
                "description": "Containerd configuration fields",
                "reference": "https://github.com/containerd/containerd/blob/main/docs/cri/config.md",
                "fields": [
                    "version",
                    "root",
                    "state",
                    "OOMScore",
                    "grpc.address",
                    "metrics.address",
                    "metrics.grpcHistogram",
                    "snapshotter",
                    "default_runtime_name",
                    "runtimes",
                    "runtimes[].runtime_type",
                    "runtimes[].runtime_engine",
                    "runtimes[].runtime_root",
                    "runtimes[].options",
                    "runtimes[].privileged_without_host_devices",
                    "cni_bin_dir",
                    "cni_conf_dir",
                    "cni_conf_template",
                    "image_plugin_runtime_constraint",
                    "disable_tcp_service",
                    "enable_selinux",
                    "enable_cdi",
                    "cdi_spec_dirs",
                    "imagepull_progress_timeout",
                    "pulloffload_priority",
                    "runtime_prio_utilization",
                    "runtime_untrusted_workload",
                    "max_container_log_line_size",
                    "restrict_oom_score_adj",
                ],
                "count": 29,
            },
            "crio_config": {
                "description": "CRI-O configuration fields",
                "reference": "https://github.com/cri-o/cri-o/blob/main/docs/crio.conf.5.md",
                "fields": [
                    "crio.version",
                    "crio.runtime",
                    "crio.runtime.handler",
                    "crio.runtime.runtimes",
                    "crio.runtime.default_runtime",
                    "crio.runtime.conmon",
                    "crio.storage",
                    "crio.storage.driver",
                    "crio.storage.driver_options",
                    "crio.storage.image_volumes",
                    "crio.network",
                    "crio.network.network_backend",
                    "crio.network.cni_plugin_dirs",
                    "crio.network.host_ipc",
                    "crio.network.host_netns_not_separate",
                    "crio.image",
                    "crio.image.unqualified_search_registry",
                    "crio.image.insecure_registries",
                    "crio.image.blocked_registries",
                    "crio.image.registry",
                    "crio.image.registry.mirrors",
                    "crio.metrics",
                    "crio.metrics.listen_address",
                    "crio.metrics.enable_metrics",
                    "crio.metrics.metrics_option",
                    "crio.signatures",
                    "crio.signatures.default_docker_reference",
                    "crio.signatures.forced_signatures",
                    "crio.systemd",
                    "crio.systemd.cgroup_driver",
                    "crio.systemd.enable_timers",
                ],
                "count": 31,
            },
            "docker_daemon_config": {
                "description": "Docker daemon configuration (daemon.json) fields",
                "reference": "https://docs.docker.com/engine/reference/commandline/dockerd/#daemon-configuration-file",
                "fields": [
                    "storage-driver",
                    "storage-opts",
                    "log-driver",
                    "log-opts",
                    "live-restore",
                    "live-restore-interval",
                    "max-concurrent-downloads",
                    "max-concurrent-uploads",
                    "debug",
                    "hosts",
                    "tls",
                    "tlsverify",
                    "tlscacert",
                    "tlscert",
                    "tlskey",
                    "cluster-store",
                    "cluster-advertise",
                    "cluster-store-opt",
                    "auths",
                    "credsStore",
                    "credHelpers",
                    "image-gc-high-threshold",
                    "image-gc-low-threshold",
                    "default-address-pdns",
                    "ools",
                    "dns-opts",
                    "dns-search",
                    "metricsaddr",
                    "-experimental",
                    "features",
                    "builder",
                    "builder.engine",
                    "builder.gc.enabled",
                    "builder.gc.defaultKeepStorage",
                    "builder.gc.pruneProbing",
                    "swarm",
                    "swarm.default-address-pools",
                    "swarm.data-path-address",
                    "swarm.ipv6",
                    "swarm.default-addr-pool",
                    "swarm.default-addr-pool-masklength",
                    "swarm.default-addr-pool-base-size",
                    "swarm.default-addr-pool-size",
                ],
                "count": 43,
            },
            "docker_compose": {
                "description": "Docker Compose specification fields",
                "reference": "https://docs.docker.com/compose/compose-file/",
                "fields": [
                    "version",
                    "services",
                    "services[].image",
                    "services[].build",
                    "services[].build.context",
                    "services[].build.dockerfile",
                    "services[].build.args",
                    "services[].build.labels",
                    "services[].build.cache_from",
                    "services[].command",
                    "services[].hostname",
                    "services[].domainname",
                    "services[].user",
                    "working_dir",
                    "services[].entrypoint",
                    "services[].environment",
                    "services[].env_file",
                    "services[].volumes",
                    "services[].volumes[].type",
                    "services[].volumes[].source",
                    "services[].volumes[].target",
                    "services[].ports",
                    "services[].expose",
                    "services[].labels",
                    "services[].restart",
                    "services[].depends_on",
                    "services[].healthcheck",
                    "services[].healthcheck.test",
                    "services[].healthcheck.interval",
                    "services[].healthcheck.timeout",
                    "services[].healthcheck.retries",
                    "services[].healthcheck.start_period",
                    "services[].networks",
                    "services[].networks[].aliases",
                    "services[].deploy",
                    "services[].deploy.resources.limits.memory",
                    "services[].deploy.resources.reservations.memory",
                    "services[].deploy.placement",
                    "services[].deploy.placement.constraints",
                    "services[].deploy.placement.preferences",
                    "services[].deploy.replicas",
                    "services[].deploy.update_config.parallelism",
                    "services[].deploy.update_config.delay",
                    "services[].profiles",
                    "services[].stop_grace_period",
                    "services[].init",
                    "services[].initializer",
                    "services[].privileged",
                    "services[].ports[].target",
                    "services[].ports[].published",
                    "services[].ports[].protocol",
                    "services[].ports[].mode",
                    "networks",
                    "networks[].driver",
                    "networks[].driver_opts",
                    "networks[].ipam.driver",
                    "networks[].ipam.config.subnet",
                    "networks[].ipam.config.gateway",
                    "volumes",
                    "volumes[].driver",
                    "volumes[].driver_opts",
                    "secrets",
                    "secrets[].file",
                    "secrets[].external",
                    "configs",
                    "configs[].file",
                    "configs[].external",
                ],
                "count": 67,
            },
            "helm_chart": {
                "description": "Helm Chart metadata fields",
                "reference": "https://helm.sh/docs/topics/charts/",
                "fields": [
                    "apiVersion",
                    "name",
                    "version",
                    "kubeVersion",
                    "description",
                    "type",
                    "keywords",
                    "home",
                    "sources[].type",
                    "sources[].url",
                    "dependencies[].name",
                    "dependencies[].version",
                    "dependencies[].repository",
                    "dependencies[].condition",
                    "dependencies[].tags",
                    "dependencies[].enabled",
                    "dependencies[].import-values",
                    "dependencies[].alias",
                    "maintainers[].name",
                    "maintainers[].email",
                    "maintainers[].url",
                    "icon",
                    "appVersion",
                    "deprecated",
                    "annotations",
                    "annotations.category",
                    "annotations.licenses",
                    "annotations.repository",
                    "annotations.helm.sh/hook",
                    "annotations.helm.sh/hook-weight",
                    "annotations.helm.sh/hook-delete-policy",
                    "values.schema",
                    "templates",
                    "crds",
                    "Chart.yaml",
                    "requirements.yaml",
                    "values.yaml",
                ],
                "count": 38,
            },
            "helm_values": {
                "description": "Helm Chart values.yaml common fields",
                "reference": "https://helm.sh/docs/chart_template_guide/values_files/",
                "fields": [
                    "replicaCount",
                    "image.repository",
                    "image.pullPolicy",
                    "image.tag",
                    "image.pullSecrets",
                    "nameOverride",
                    "fullnameOverride",
                    "serviceAccount.create",
                    "serviceAccount.annotations",
                    "serviceAccount.name",
                    "podSecurityContext.fsGroup",
                    "podSecurityContext.runAsUser",
                    "podSecurityContext.runAsNonRoot",
                    "securityContext.readOnlyRootFilesystem",
                    "securityContext.privileged",
                    "securityContext.capabilities.drop",
                    "securityContext.capabilities.add",
                    "livenessProbe.httpGet.path",
                    "livenessProbe.httpGet.port",
                    "livenessProbe.initialDelaySeconds",
                    "livenessProbe.periodSeconds",
                    "livenessProbe.timeoutSeconds",
                    "livenessProbe.failureThreshold",
                    "readinessProbe.httpGet.path",
                    "readinessProbe.httpGet.port",
                    "readinessProbe.initialDelaySeconds",
                    "readinessProbe.periodSeconds",
                    "readinessProbe.timeoutSeconds",
                    "readinessProbe.failureThreshold",
                    "startupProbe.httpGet.path",
                    "startupProbe.httpGet.port",
                    "startupProbe.initialDelaySeconds",
                    "startupProbe.periodSeconds",
                    "startupProbe.timeoutSeconds",
                    "startupProbe.failureThreshold",
                    "resources.limits.cpu",
                    "resources.limits.memory",
                    "resources.requests.cpu",
                    "resources.requests.memory",
                    "autoscaling.minReplicas",
                    "autoscaling.maxReplicas",
                    "autoscaling.targetCPUUtilizationPercentage",
                    "autoscaling.targetMemoryUtilizationPercentage",
                    "nodeSelector",
                    "tolerations",
                    "affinity",
                    "topologySpreadConstraints.maxSkew",
                    "topologySpreadConstraints.topologyKey",
                    "topologySpreadConstraints.whenUnsatisfiable",
                    "priorityClassName",
                    "terminationGracePeriodSeconds",
                    "ingress.enabled",
                    "ingress.className",
                    "ingress.hosts[].host",
                    "ingress.hosts[].paths[].path",
                    "ingress.hosts[].paths[].pathType",
                    "ingress.tls[].secretName",
                    "ingress.tls[].hosts",
                    "service.type",
                    "service.port",
                    "service.nodePort",
                    "service.clusterIP",
                    "service.externalIPs",
                    "service.loadBalancerIP",
                    "service.loadBalancerSourceRanges",
                    "service.annotations",
                    "configMap",
                    "secret",
                    "extraEnv",
                    "extraEnvFrom",
                    "extraVolumeMounts",
                    "extraVolumes",
                    "initContainers",
                    "sidecars",
                    "imagePullSecrets",
                ],
                "count": 78,
            },
        },
        "totals": {
            "categories": 17,
            "total_fields": 602,
        }
    }

    return INVENTORY


def main():
    print("=" * 70)
    print("CONTAINER FORMAT METADATA FIELD INVENTORY")
    print("=" * 70)
    print()

    inventory = generate_containers_inventory()

    print(f"Generated: {inventory['generated_at']}")
    print(f"Categories: {inventory['totals']['categories']}")
    print(f"Total Fields: {inventory['totals']['total_fields']}")
    print()

    print("FIELD COUNTS BY CATEGORY:")
    print("-" * 50)
    for cat_name, cat_data in sorted(inventory['categories'].items(), key=lambda x: x[1]['count'], reverse=True):
        ref = cat_data.get('reference', 'N/A')
        if len(ref) > 50:
            ref = ref[:47] + "..."
        print(f"  {cat_name:35s}: {cat_data['count']:>4} fields")
        print(f"    Ref: {ref}")

    output_dir = Path("dist/containers_inventory")
    output_dir.mkdir(parents=True, exist_ok=True)

    output_file = output_dir / "containers_inventory.json"
    output_file.write_text(json.dumps(inventory, indent=2, sort_keys=True), encoding="utf-8")
    print()
    print(f"Wrote: {output_file}")

    summary = {
        "generated_at": inventory["generated_at"],
        "description": inventory["description"],
        "categories": {k: {"count": v["count"], "description": v["description"]} for k, v in inventory["categories"].items()},
        "totals": inventory["totals"],
    }

    summary_file = output_dir / "containers_summary.json"
    summary_file.write_text(json.dumps(summary, indent=2, sort_keys=True), encoding="utf-8")
    print(f"Wrote: {summary_file}")


if __name__ == "__main__":
    main()
