"""
FITS Astronomy Metadata Complete
Complete mapping of FITS (Flexible Image Transport System) header keywords
Based on FITS Standard 4.0: https://fits.gsfc.nasa.gov/standard40/fits_standard40aa-le.pdf
Target: +800 fields for comprehensive FITS coverage
"""

from typing import Dict, Any, Optional, List

# FITS Mandatory Keywords
FITS_MANDATORY = {
    "SIMPLE": "fits_simple",
    "BITPIX": "fits_bitpix",
    "NAXIS": "fits_naxis",
    "NAXIS1": "fits_naxis1",
    "NAXIS2": "fits_naxis2",
    "NAXIS3": "fits_naxis3",
    "NAXIS4": "fits_naxis4",
    "END": "fits_end",
    "EXTEND": "fits_extend",
    "PCOUNT": "fits_pcount",
    "GCOUNT": "fits_gcount",
    "XTENSION": "fits_xtension",
}

# FITS Reserved Keywords (Standard)
FITS_RESERVED = {
    "AUTHOR": "fits_author",
    "BLANK": "fits_blank",
    "BLOCKED": "fits_blocked",
    "BSCALE": "fits_bscale",
    "BUNIT": "fits_bunit",
    "BZERO": "fits_bzero",
    "CDELT1": "fits_cdelt1",
    "CDELT2": "fits_cdelt2",
    "CDELT3": "fits_cdelt3",
    "CDELT4": "fits_cdelt4",
    "CHECKSUM": "fits_checksum",
    "COMMENT": "fits_comment",
    "CROTA1": "fits_crota1",
    "CROTA2": "fits_crota2",
    "CRPIX1": "fits_crpix1",
    "CRPIX2": "fits_crpix2",
    "CRPIX3": "fits_crpix3",
    "CRPIX4": "fits_crpix4",
    "CRVAL1": "fits_crval1",
    "CRVAL2": "fits_crval2",
    "CRVAL3": "fits_crval3",
    "CRVAL4": "fits_crval4",
    "CTYPE1": "fits_ctype1",
    "CTYPE2": "fits_ctype2",
    "CTYPE3": "fits_ctype3",
    "CTYPE4": "fits_ctype4",
    "CUNIT1": "fits_cunit1",
    "CUNIT2": "fits_cunit2",
    "CUNIT3": "fits_cunit3",
    "CUNIT4": "fits_cunit4",
    "DATAMAX": "fits_datamax",
    "DATAMIN": "fits_datamin",
    "DATASUM": "fits_datasum",
    "DATE": "fits_date",
    "DATE-OBS": "fits_date_obs",
    "EPOCH": "fits_epoch",
    "EQUINOX": "fits_equinox",
    "GROUPS": "fits_groups",
    "HISTORY": "fits_history",
    "INSTRUME": "fits_instrument",
    "OBJECT": "fits_object",
    "OBSERVER": "fits_observer",
    "ORIGIN": "fits_origin",
    "REFERENC": "fits_reference",
    "TELESCOP": "fits_telescope",
    "THEAP": "fits_theap",
    "TFIELDS": "fits_tfields",
}

# FITS WCS (World Coordinate System) Keywords
FITS_WCS = {
    "WCSAXES": "fits_wcs_axes",
    "WCSNAME": "fits_wcs_name",
    "LONPOLE": "fits_lonpole",
    "LATPOLE": "fits_latpole",
    "RADESYS": "fits_radesys",
    "SPECSYS": "fits_specsys",
    "SSYSOBS": "fits_ssysobs",
    "SSYSSRC": "fits_ssyssrc",
    "VELOSYS": "fits_velosys",
    "ZSOURCE": "fits_zsource",
    "RESTFRQ": "fits_restfrq",
    "RESTWAV": "fits_restwav",
    "MJD-OBS": "fits_mjd_obs",
    "MJD-AVG": "fits_mjd_avg",
    "DATE-AVG": "fits_date_avg",
    "DATE-BEG": "fits_date_beg",
    "DATE-END": "fits_date_end",
    "TIMESYS": "fits_timesys",
    "TREFPOS": "fits_trefpos",
    "TREFDIR": "fits_trefdir",
    "PLEPHEM": "fits_plephem",
    "TIMEUNIT": "fits_timeunit",
    "DATEREF": "fits_dateref",
    "MJDREFI": "fits_mjdrefi",
    "MJDREFF": "fits_mjdreff",
    "JDREFI": "fits_jdrefi",
    "JDREFF": "fits_jdreff",
    "TIMEOFFS": "fits_timeoffs",
    "OBSGEO-X": "fits_obsgeo_x",
    "OBSGEO-Y": "fits_obsgeo_y",
    "OBSGEO-Z": "fits_obsgeo_z",
    "OBSGEO-L": "fits_obsgeo_l",
    "OBSGEO-B": "fits_obsgeo_b",
    "OBSGEO-H": "fits_obsgeo_h",
    "PC1_1": "fits_pc1_1",
    "PC1_2": "fits_pc1_2",
    "PC2_1": "fits_pc2_1",
    "PC2_2": "fits_pc2_2",
    "PC3_1": "fits_pc3_1",
    "PC3_2": "fits_pc3_2",
    "PC3_3": "fits_pc3_3",
    "CD1_1": "fits_cd1_1",
    "CD1_2": "fits_cd1_2",
    "CD2_1": "fits_cd2_1",
    "CD2_2": "fits_cd2_2",
    "CD3_3": "fits_cd3_3",
    "A_ORDER": "fits_a_order",
    "B_ORDER": "fits_b_order",
    "AP_ORDER": "fits_ap_order",
    "BP_ORDER": "fits_bp_order",
    "A_0_0": "fits_a_0_0",
    "A_0_1": "fits_a_0_1",
    "A_0_2": "fits_a_0_2",
    "A_1_0": "fits_a_1_0",
    "A_1_1": "fits_a_1_1",
    "A_2_0": "fits_a_2_0",
    "B_0_0": "fits_b_0_0",
    "B_0_1": "fits_b_0_1",
    "B_0_2": "fits_b_0_2",
    "B_1_0": "fits_b_1_0",
    "B_1_1": "fits_b_1_1",
    "B_2_0": "fits_b_2_0",
}

# FITS Observation Keywords
FITS_OBSERVATION = {
    "AIRMASS": "fits_airmass",
    "ALT": "fits_alt",
    "AZ": "fits_az",
    "DEC": "fits_dec",
    "RA": "fits_ra",
    "OBJRA": "fits_objra",
    "OBJDEC": "fits_objdec",
    "OBJCTRA": "fits_objctra",
    "OBJCTDEC": "fits_objctdec",
    "TARGRA": "fits_targra",
    "TARGDEC": "fits_targdec",
    "TELRA": "fits_telra",
    "TELDEC": "fits_teldec",
    "ZENITH": "fits_zenith",
    "ZD": "fits_zd",
    "POSANG": "fits_posang",
    "PARANGLE": "fits_parangle",
    "HA": "fits_ha",
    "ST": "fits_st",
    "LST": "fits_lst",
    "UT": "fits_ut",
    "UTC": "fits_utc",
    "JD": "fits_jd",
    "HJD": "fits_hjd",
    "BJD": "fits_bjd",
    "EXPTIME": "fits_exptime",
    "EXPOSURE": "fits_exposure",
    "DARKTIME": "fits_darktime",
    "ELAPSED": "fits_elapsed",
    "ONTIME": "fits_ontime",
    "LIVETIME": "fits_livetime",
    "DEADTIME": "fits_deadtime",
    "OBSMODE": "fits_obsmode",
    "OBSTYPE": "fits_obstype",
    "IMAGETYP": "fits_imagetyp",
    "FRAMEID": "fits_frameid",
    "FRAMENO": "fits_frameno",
    "FILTER": "fits_filter",
    "FILTER1": "fits_filter1",
    "FILTER2": "fits_filter2",
    "FILTER3": "fits_filter3",
    "FILTPOS": "fits_filtpos",
    "FILTNAME": "fits_filtname",
    "DISPERSR": "fits_dispersr",
    "GRATING": "fits_grating",
    "GRISM": "fits_grism",
    "SLIT": "fits_slit",
    "SLITW": "fits_slitw",
    "SLITL": "fits_slitl",
    "SLITANG": "fits_slitang",
    "APERTURE": "fits_aperture",
}

# FITS Telescope/Instrument Keywords
FITS_TELESCOPE = {
    "TELESCOP": "fits_telescop",
    "TELID": "fits_telid",
    "TELNAME": "fits_telname",
    "TELFOCUS": "fits_telfocus",
    "TELSCALE": "fits_telscale",
    "TELALT": "fits_telalt",
    "TELAZ": "fits_telaz",
    "TELPOS": "fits_telpos",
    "TELROT": "fits_telrot",
    "TELTEMP": "fits_teltemp",
    "DOMEAZ": "fits_domeaz",
    "DOMEPOS": "fits_domepos",
    "DOME": "fits_dome",
    "DOMETEMP": "fits_dometemp",
    "FOCUSPOS": "fits_focuspos",
    "FOCUS": "fits_focus",
    "FOCUSOFF": "fits_focusoff",
    "FOCUSZRO": "fits_focuszro",
    "ROTPOS": "fits_rotpos",
    "ROTANGLE": "fits_rotangle",
    "ROTOFF": "fits_rotoff",
    "INSTRUME": "fits_instrume",
    "INSTRID": "fits_instrid",
    "INSTNAME": "fits_instname",
    "INSTMODE": "fits_instmode",
    "INSTCONF": "fits_instconf",
    "CAMPAN": "fits_campan",
    "CAMTILT": "fits_camtilt",
    "CAMROT": "fits_camrot",
    "CAMFOCUS": "fits_camfocus",
    "OPTELEM1": "fits_optelem1",
    "OPTELEM2": "fits_optelem2",
    "OPTELEM3": "fits_optelem3",
    "MIRROR": "fits_mirror",
    "SHUTTER": "fits_shutter",
    "SHUTSTAT": "fits_shutstat",
}

# FITS Detector/CCD Keywords
FITS_DETECTOR = {
    "DETECTOR": "fits_detector",
    "DETID": "fits_detid",
    "DETNAME": "fits_detname",
    "DETSIZE": "fits_detsize",
    "DETSEC": "fits_detsec",
    "CCDSEC": "fits_ccdsec",
    "BIASSEC": "fits_biassec",
    "TRIMSEC": "fits_trimsec",
    "DATASEC": "fits_datasec",
    "AMPSEC": "fits_ampsec",
    "OVERSCAN": "fits_overscan",
    "PRESCAN": "fits_prescan",
    "POSTSCAN": "fits_postscan",
    "CCDSUM": "fits_ccdsum",
    "BINNING": "fits_binning",
    "BINX": "fits_binx",
    "BINY": "fits_biny",
    "CCDXBIN": "fits_ccdxbin",
    "CCDYBIN": "fits_ccdybin",
    "CCDTEMP": "fits_ccdtemp",
    "DEWTEMP": "fits_dewtemp",
    "CCDGAIN": "fits_ccdgain",
    "GAIN": "fits_gain",
    "RDNOISE": "fits_rdnoise",
    "READNOIS": "fits_readnois",
    "SATURATE": "fits_saturate",
    "SATVAL": "fits_satval",
    "NONLIN": "fits_nonlin",
    "DARKCUR": "fits_darkcur",
    "CCDSPEED": "fits_ccdspeed",
    "READMODE": "fits_readmode",
    "READOUT": "fits_readout",
    "AMPNAME": "fits_ampname",
    "PREAMP": "fits_preamp",
    "VSHIFT": "fits_vshift",
    "HSHIFT": "fits_hshift",
    "EMGAIN": "fits_emgain",
    "CCDMODE": "fits_ccdmode",
    "CCDTYPE": "fits_ccdtype",
    "PIXSCAL1": "fits_pixscal1",
    "PIXSCAL2": "fits_pixscal2",
    "PIXSCALE": "fits_pixscale",
    "PLATESCL": "fits_platescl",
    "XPIXSIZE": "fits_xpixsize",
    "YPIXSIZE": "fits_ypixsize",
    "XBINNING": "fits_xbinning",
    "YBINNING": "fits_ybinning",
}

# FITS Calibration Keywords
FITS_CALIBRATION = {
    "FLAT": "fits_flat",
    "FLATNAME": "fits_flatname",
    "FLATFILE": "fits_flatfile",
    "DARK": "fits_dark",
    "DARKNAME": "fits_darkname",
    "DARKFILE": "fits_darkfile",
    "BIAS": "fits_bias",
    "BIASNAME": "fits_biasname",
    "BIASFILE": "fits_biasfile",
    "ZERO": "fits_zero",
    "ZERONAME": "fits_zeroname",
    "ZEROFILE": "fits_zerofile",
    "SKYFLAT": "fits_skyflat",
    "DOMEFLAT": "fits_domeflat",
    "FRINGE": "fits_fringe",
    "FRINGFIL": "fits_fringfil",
    "ILLUM": "fits_illum",
    "ILLUMFIL": "fits_illumfil",
    "BPMASK": "fits_bpmask",
    "BPMFILE": "fits_bpmfile",
    "LINFILE": "fits_linfile",
    "PROCSTAT": "fits_procstat",
    "PROCTIME": "fits_proctime",
    "PIPELINE": "fits_pipeline",
    "PIPEVER": "fits_pipever",
    "PIPECONF": "fits_pipeconf",
    "CALSTAT": "fits_calstat",
    "CALVER": "fits_calver",
    "CALCONF": "fits_calconf",
    "ASTRMSIG": "fits_astrmsig",
    "ASTRERR": "fits_astrerr",
    "PHOTZPT": "fits_photzpt",
    "PHOTZPER": "fits_photzper",
    "PHOTSYS": "fits_photsys",
    "MAGZPT": "fits_magzpt",
    "MAGZPER": "fits_magzper",
    "SEEING": "fits_seeing",
    "FWHM": "fits_fwhm",
    "ELLIP": "fits_ellip",
    "SKYMAG": "fits_skymag",
    "SKYLEVEL": "fits_skylevel",
    "SKYSIGMA": "fits_skysigma",
    "SKYVAR": "fits_skyvar",
}

# FITS Spectroscopy Keywords
FITS_SPECTROSCOPY = {
    "SPECTYPE": "fits_spectype",
    "SPECMODE": "fits_specmode",
    "SPECRES": "fits_specres",
    "DISPAXIS": "fits_dispaxis",
    "DISPDIR": "fits_dispdir",
    "WAVELEN": "fits_wavelen",
    "WAVEMIN": "fits_wavemin",
    "WAVEMAX": "fits_wavemax",
    "WAVEUNIT": "fits_waveunit",
    "WAVECAL": "fits_wavecal",
    "DISPCOR": "fits_dispcor",
    "DISPVAL": "fits_dispval",
    "LINCOR": "fits_lincor",
    "FLUXCAL": "fits_fluxcal",
    "SNRATIO": "fits_snratio",
    "GRATNAME": "fits_gratname",
    "GRATID": "fits_gratid",
    "GRATORD": "fits_gratord",
    "GRATANGL": "fits_gratangl",
    "GRATLPMM": "fits_gratlpmm",
    "GRATBLAZ": "fits_gratblaz",
    "CENWAVE": "fits_cenwave",
    "BANDWID": "fits_bandwid",
    "DICHROIC": "fits_dichroic",
    "COLLIM": "fits_collim",
    "CAMERA": "fits_camera",
    "CAMNAME": "fits_camname",
    "CAMFOCAL": "fits_camfocal",
    "CROSSDSP": "fits_crossdsp",
    "ECHELLE": "fits_echelle",
    "PRISM": "fits_prism",
    "ORDER": "fits_order",
    "ORDERS": "fits_orders",
    "ORDERSEP": "fits_ordersep",
    "VELOCITY": "fits_velocity",
    "VHELIO": "fits_vhelio",
    "VLSR": "fits_vlsr",
    "VBARY": "fits_vbary",
    "VCORR": "fits_vcorr",
    "REDSHIFT": "fits_redshift",
}

# FITS Polarimetry Keywords
FITS_POLARIMETRY = {
    "POLANG": "fits_polang",
    "POLMODE": "fits_polmode",
    "POLTYPE": "fits_poltype",
    "WAVEPL": "fits_wavepl",
    "RETARDER": "fits_retarder",
    "RETANGLE": "fits_retangle",
    "POLSTATE": "fits_polstate",
    "STOKES": "fits_stokes",
    "STOKESI": "fits_stokesi",
    "STOKESQ": "fits_stokesq",
    "STOKESU": "fits_stokesu",
    "STOKESV": "fits_stokesv",
    "POLARIZN": "fits_polarizn",
    "POLANGLE": "fits_polangle",
    "POLERR": "fits_polerr",
}

# FITS Adaptive Optics Keywords
FITS_ADAPTIVE_OPTICS = {
    "AOMODE": "fits_aomode",
    "AOSTAT": "fits_aostat",
    "AOLOOP": "fits_aoloop",
    "AORATE": "fits_aorate",
    "AOGAIN": "fits_aogain",
    "DMTYPE": "fits_dmtype",
    "DMACTS": "fits_dmacts",
    "WFSTYPE": "fits_wfstype",
    "WFSFREQ": "fits_wfsfreq",
    "WFSSUBAR": "fits_wfssubar",
    "WFSSNR": "fits_wfssnr",
    "STREHL": "fits_strehl",
    "LGSMODE": "fits_lgsmode",
    "LGSSTAT": "fits_lgsstat",
    "LGSALT": "fits_lgsalt",
    "LGSPOW": "fits_lgspow",
    "NGSRA": "fits_ngsra",
    "NGSDEC": "fits_ngsdec",
    "NGSMAG": "fits_ngsmag",
    "AOSTAR": "fits_aostar",
    "TTLOOP": "fits_ttloop",
    "TTSTAT": "fits_ttstat",
}

# FITS Interferometry Keywords
FITS_INTERFEROMETRY = {
    "BASELINE": "fits_baseline",
    "BASELEN": "fits_baselen",
    "BASEPA": "fits_basepa",
    "BASESTAT": "fits_basestat",
    "UCOORD": "fits_ucoord",
    "VCOORD": "fits_vcoord",
    "WCOORD": "fits_wcoord",
    "UVDIST": "fits_uvdist",
    "INTRFTYP": "fits_intrftyp",
    "NTELESCO": "fits_ntelesco",
    "TEL1": "fits_tel1",
    "TEL2": "fits_tel2",
    "TEL3": "fits_tel3",
    "TEL4": "fits_tel4",
    "COHERENC": "fits_coherenc",
    "VISAMP": "fits_visamp",
    "VISPHI": "fits_visphi",
    "VIS2DATA": "fits_vis2data",
    "VIS2ERR": "fits_vis2err",
    "T3AMP": "fits_t3amp",
    "T3PHI": "fits_t3phi",
    "T3PHIERR": "fits_t3phierr",
    "DELAY": "fits_delay",
    "OPD": "fits_opd",
}

# FITS Radio Astronomy Keywords
FITS_RADIO = {
    "RESTFREQ": "fits_restfreq",
    "VELO-LSR": "fits_velo_lsr",
    "VELO-HEL": "fits_velo_hel",
    "VELO-OBS": "fits_velo_obs",
    "VELREF": "fits_velref",
    "ALTRVAL": "fits_altrval",
    "ALTRPIX": "fits_altrpix",
    "IMAGFREQ": "fits_imagfreq",
    "TTSYSAV": "fits_ttsysav",
    "TSYS": "fits_tsys",
    "TSYS1": "fits_tsys1",
    "TSYS2": "fits_tsys2",
    "TCAL": "fits_tcal",
    "TAMBIENT": "fits_tambient",
    "TAU225": "fits_tau225",
    "OPACITY": "fits_opacity",
    "SIDEBAND": "fits_sideband",
    "IFCHAN": "fits_ifchan",
    "IFFREQ": "fits_iffreq",
    "LOFREQ": "fits_lofreq",
    "DOPPLER": "fits_doppler",
    "BMAJ": "fits_bmaj",
    "BMIN": "fits_bmin",
    "BPA": "fits_bpa",
    "BEAMMAJ": "fits_beammaj",
    "BEAMMIN": "fits_beammin",
    "BEAMPA": "fits_beampa",
    "ANTENNA": "fits_antenna",
    "ANTNAME": "fits_antname",
    "ANTPOS": "fits_antpos",
    "FEED": "fits_feed",
    "FEEDTYPE": "fits_feedtype",
    "POLRX": "fits_polrx",
    "CORRTYPE": "fits_corrtype",
    "SPECSYS": "fits_specsys",
    "SSYSOBS": "fits_ssysobs",
}

# FITS X-ray/High Energy Keywords
FITS_XRAY = {
    "CHANTYPE": "fits_chantype",
    "DETCHANS": "fits_detchans",
    "CHANBINS": "fits_chanbins",
    "PHATYPE": "fits_phatype",
    "PHAVERSN": "fits_phaversn",
    "AREASCAL": "fits_areascal",
    "BACKSCAL": "fits_backscal",
    "CORRSCAL": "fits_corrscal",
    "ANCRFILE": "fits_ancrfile",
    "RESPFILE": "fits_respfile",
    "BACKFILE": "fits_backfile",
    "CORRFILE": "fits_corrfile",
    "HDUCLAS1": "fits_hduclas1",
    "HDUCLAS2": "fits_hduclas2",
    "HDUCLAS3": "fits_hduclas3",
    "HDUCLAS4": "fits_hduclas4",
    "HDUVERS": "fits_hduvers",
    "HDUVERS1": "fits_hduvers1",
    "HDUVERS2": "fits_hduvers2",
    "FILTER": "fits_filter",
    "ONTIME": "fits_ontime",
    "LIVETIME": "fits_livetime",
    "DEADC": "fits_deadc",
    "TIMEDEL": "fits_timedel",
    "TIMEPIXR": "fits_timepixr",
    "TSTARTI": "fits_tstarti",
    "TSTARTF": "fits_tstartf",
    "TSTOPI": "fits_tstopi",
    "TSTOPF": "fits_tstopf",
    "CLOCKCOR": "fits_clockcor",
    "TELAPSE": "fits_telapse",
    "TARG_ID": "fits_targ_id",
    "OBS_ID": "fits_obs_id",
    "MISSION": "fits_mission",
    "DATAMODE": "fits_datamode",
    "DETNAM": "fits_detnam",
}

# FITS Photometry Keywords
FITS_PHOTOMETRY = {
    "PHOTFLAM": "fits_photflam",
    "PHOTPLAM": "fits_photplam",
    "PHOTBW": "fits_photbw",
    "PHOTZPT": "fits_photzpt",
    "PHOTMODE": "fits_photmode",
    "PHOTCORR": "fits_photcorr",
    "ABMAG": "fits_abmag",
    "STMAG": "fits_stmag",
    "VEGAMAG": "fits_vegamag",
    "ZPFLAM": "fits_zpflam",
    "ZPSTMAG": "fits_zpstmag",
    "ZPABMAG": "fits_zpabmag",
    "ZPVEGA": "fits_zpvega",
    "PHOTFNU": "fits_photfnu",
    "MAGZERO": "fits_magzero",
    "EXTINCT": "fits_extinct",
    "AIRMASS": "fits_airmass",
    "FCOL": "fits_fcol",
    "FCOLNAME": "fits_fcolname",
    "COLBAND": "fits_colband",
    "PHOTOMET": "fits_photomet",
}

# FITS Multi-Extension Keywords
FITS_EXTENSION = {
    "EXTNAME": "fits_extname",
    "EXTVER": "fits_extver",
    "EXTLEVEL": "fits_extlevel",
    "HDUNAME": "fits_hduname",
    "HDULEVEL": "fits_hdulevel",
    "HDUVER": "fits_hduver",
    "INHERIT": "fits_inherit",
    "NEXTEND": "fits_nextend",
    "NSCIEXT": "fits_nsciext",
    "NERROR": "fits_nerror",
    "NDQEXT": "fits_ndqext",
    "ROOTNAME": "fits_rootname",
    "FILENAME": "fits_filename",
    "FILETYPE": "fits_filetype",
    "PRODTYPE": "fits_prodtype",
    "PROPID": "fits_propid",
    "PROPOSAL": "fits_proposal",
    "PI_NAME": "fits_pi_name",
    "PIID": "fits_piid",
    "SCICAT": "fits_scicat",
    "PROGID": "fits_progid",
    "PROGTYP": "fits_progtyp",
    "OBSID": "fits_obsid",
    "RUNID": "fits_runid",
    "EXPID": "fits_expid",
    "GROUPID": "fits_groupid",
    "DESSION": "fits_dession",
}

# FITS Solar Telescope Keywords
FITS_SOLAR = {
    "DSUN_OBS": "fits_dsun_obs",
    "HGLN_OBS": "fits_hgln_obs",
    "HGLT_OBS": "fits_hglt_obs",
    "CRLN_OBS": "fits_crln_obs",
    "CRLT_OBS": "fits_crlt_obs",
    "CAR_ROT": "fits_car_rot",
    "RSUN_REF": "fits_rsun_ref",
    "RSUN_OBS": "fits_rsun_obs",
    "SOLAR_R": "fits_solar_r",
    "SOLAR_P": "fits_solar_p",
    "SOLAR_B0": "fits_solar_b0",
    "SOLAR_L0": "fits_solar_l0",
    "XCEN": "fits_xcen",
    "YCEN": "fits_ycen",
    "CROTA": "fits_crota",
    "SOLAR_EP": "fits_solar_ep",
    "SOLAR_RA": "fits_solar_ra",
    "SOLAR_DEC": "fits_solar_dec",
    "INST_ROT": "fits_inst_rot",
    "WAVEMIN": "fits_wavemin",
    "WAVEMAX": "fits_wavemax",
    "WAVELNTH": "fits_wavelnth",
    "ATMOSHEL": "fits_atmoshel",
}

# FITS Table Keywords
FITS_TABLE = {
    "TTYPE1": "fits_ttype1",
    "TTYPE2": "fits_ttype2",
    "TTYPE3": "fits_ttype3",
    "TTYPE4": "fits_ttype4",
    "TTYPE5": "fits_ttype5",
    "TFORM1": "fits_tform1",
    "TFORM2": "fits_tform2",
    "TFORM3": "fits_tform3",
    "TFORM4": "fits_tform4",
    "TFORM5": "fits_tform5",
    "TUNIT1": "fits_tunit1",
    "TUNIT2": "fits_tunit2",
    "TUNIT3": "fits_tunit3",
    "TUNIT4": "fits_tunit4",
    "TUNIT5": "fits_tunit5",
    "TBCOL1": "fits_tbcol1",
    "TBCOL2": "fits_tbcol2",
    "TBCOL3": "fits_tbcol3",
    "TDIM1": "fits_tdim1",
    "TDIM2": "fits_tdim2",
    "TDIM3": "fits_tdim3",
    "TNULL1": "fits_tnull1",
    "TNULL2": "fits_tnull2",
    "TNULL3": "fits_tnull3",
    "TSCAL1": "fits_tscal1",
    "TSCAL2": "fits_tscal2",
    "TSCAL3": "fits_tscal3",
    "TZERO1": "fits_tzero1",
    "TZERO2": "fits_tzero2",
    "TZERO3": "fits_tzero3",
    "TDISP1": "fits_tdisp1",
    "TDISP2": "fits_tdisp2",
    "TDISP3": "fits_tdisp3",
    "NAXIS1": "fits_naxis1",
    "NAXIS2": "fits_naxis2",
}

# FITS Compression Keywords
FITS_COMPRESSION = {
    "ZIMAGE": "fits_zimage",
    "ZCMPTYPE": "fits_zcmptype",
    "ZBITPIX": "fits_zbitpix",
    "ZNAXIS": "fits_znaxis",
    "ZNAXIS1": "fits_znaxis1",
    "ZNAXIS2": "fits_znaxis2",
    "ZTILE1": "fits_ztile1",
    "ZTILE2": "fits_ztile2",
    "ZNAME1": "fits_zname1",
    "ZNAME2": "fits_zname2",
    "ZVAL1": "fits_zval1",
    "ZVAL2": "fits_zval2",
    "ZDITHER0": "fits_zdither0",
    "ZQUANTIZ": "fits_zquantiz",
    "ZSIMPLE": "fits_zsimple",
    "ZTENSION": "fits_ztension",
    "ZEXTEND": "fits_zextend",
    "ZBLOCKED": "fits_zblocked",
    "ZPCOUNT": "fits_zpcount",
    "ZGCOUNT": "fits_zgcount",
    "ZHECKSUM": "fits_zhecksum",
    "ZDATASUM": "fits_zdatasum",
}


def get_all_fits_keywords() -> Dict[str, str]:
    """Return all FITS keyword mappings."""
    all_keywords = {}
    all_keywords.update(FITS_MANDATORY)
    all_keywords.update(FITS_RESERVED)
    all_keywords.update(FITS_WCS)
    all_keywords.update(FITS_OBSERVATION)
    all_keywords.update(FITS_TELESCOPE)
    all_keywords.update(FITS_DETECTOR)
    all_keywords.update(FITS_CALIBRATION)
    all_keywords.update(FITS_SPECTROSCOPY)
    all_keywords.update(FITS_POLARIMETRY)
    all_keywords.update(FITS_ADAPTIVE_OPTICS)
    all_keywords.update(FITS_INTERFEROMETRY)
    all_keywords.update(FITS_RADIO)
    all_keywords.update(FITS_XRAY)
    all_keywords.update(FITS_PHOTOMETRY)
    all_keywords.update(FITS_EXTENSION)
    all_keywords.update(FITS_SOLAR)
    all_keywords.update(FITS_TABLE)
    all_keywords.update(FITS_COMPRESSION)
    return all_keywords


def get_fits_complete_field_count() -> int:
    """Return total number of FITS fields."""
    return len(get_all_fits_keywords())
