"""
FITS Astronomy Metadata Complete
Complete mapping of FITS (Flexible Image Transport System) header keywords
Based on FITS Standard 4.0: https://fits.gsfc.nasa.gov/standard40/fits_standard40aa-le.pdf
Target: +800 fields for comprehensive FITS coverage
"""

from typing import Dict, Any, Optional, List

# FITS Mandatory Keywords
FITS_MANDATORY = {
    "SIMPLE": "fits_simple",
    "BITPIX": "fits_bitpix",
    "NAXIS": "fits_naxis",
    "NAXIS1": "fits_naxis1",
    "NAXIS2": "fits_naxis2",
    "NAXIS3": "fits_naxis3",
    "NAXIS4": "fits_naxis4",
    "END": "fits_end",
    "EXTEND": "fits_extend",
    "PCOUNT": "fits_pcount",
    "GCOUNT": "fits_gcount",
    "XTENSION": "fits_xtension",
}

# FITS Reserved Keywords (Standard)
FITS_RESERVED = {
    "AUTHOR": "fits_author",
    "BLANK": "fits_blank",
    "BLOCKED": "fits_blocked",
    "BSCALE": "fits_bscale",
    "BUNIT": "fits_bunit",
    "BZERO": "fits_bzero",
    "CDELT1": "fits_cdelt1",
    "CDELT2": "fits_cdelt2",
    "CDELT3": "fits_cdelt3",
    "CDELT4": "fits_cdelt4",
    "CHECKSUM": "fits_checksum",
    "COMMENT": "fits_comment",
    "CROTA1": "fits_crota1",
    "CROTA2": "fits_crota2",
    "CRPIX1": "fits_crpix1",
    "CRPIX2": "fits_crpix2",
    "CRPIX3": "fits_crpix3",
    "CRPIX4": "fits_crpix4",
    "CRVAL1": "fits_crval1",
    "CRVAL2": "fits_crval2",
    "CRVAL3": "fits_crval3",
    "CRVAL4": "fits_crval4",
    "CTYPE1": "fits_ctype1",
    "CTYPE2": "fits_ctype2",
    "CTYPE3": "fits_ctype3",
    "CTYPE4": "fits_ctype4",
    "CUNIT1": "fits_cunit1",
    "CUNIT2": "fits_cunit2",
    "CUNIT3": "fits_cunit3",
    "CUNIT4": "fits_cunit4",
    "DATAMAX": "fits_datamax",
    "DATAMIN": "fits_datamin",
    "DATASUM": "fits_datasum",
    "DATE": "fits_date",
    "DATE-OBS": "fits_date_obs",
    "EPOCH": "fits_epoch",
    "EQUINOX": "fits_equinox",
    "GROUPS": "fits_groups",
    "HISTORY": "fits_history",
    "INSTRUME": "fits_instrument",
    "OBJECT": "fits_object",
    "OBSERVER": "fits_observer",
    "ORIGIN": "fits_origin",
    "REFERENC": "fits_reference",
    "TELESCOP": "fits_telescope",
    "THEAP": "fits_theap",
    "TFIELDS": "fits_tfields",
}

# FITS WCS (World Coordinate System) Keywords
FITS_WCS = {
    "WCSAXES": "fits_wcs_axes",
    "WCSNAME": "fits_wcs_name",
    "LONPOLE": "fits_lonpole",
    "LATPOLE": "fits_latpole",
    "RADESYS": "fits_radesys",
    "SPECSYS": "fits_specsys",
    "SSYSOBS": "fits_ssysobs",
    "SSYSSRC": "fits_ssyssrc",
    "VELOSYS": "fits_velosys",
    "ZSOURCE": "fits_zsource",
    "RESTFRQ": "fits_restfrq",
    "RESTWAV": "fits_restwav",
    "MJD-OBS": "fits_mjd_obs",
    "MJD-AVG": "fits_mjd_avg",
    "DATE-AVG": "fits_date_avg",
    "DATE-BEG": "fits_date_beg",
    "DATE-END": "fits_date_end",
    "TIMESYS": "fits_timesys",
    "TREFPOS": "fits_trefpos",
    "TREFDIR": "fits_trefdir",
    "PLEPHEM": "fits_plephem",
    "TIMEUNIT": "fits_timeunit",
    "DATEREF": "fits_dateref",
    "MJDREFI": "fits_mjdrefi",
    "MJDREFF": "fits_mjdreff",
    "JDREFI": "fits_jdrefi",
    "JDREFF": "fits_jdreff",
    "TIMEOFFS": "fits_timeoffs",
    "OBSGEO-X": "fits_obsgeo_x",
    "OBSGEO-Y": "fits_obsgeo_y",
    "OBSGEO-Z": "fits_obsgeo_z",
    "OBSGEO-L": "fits_obsgeo_l",
    "OBSGEO-B": "fits_obsgeo_b",
    "OBSGEO-H": "fits_obsgeo_h",
    "PC1_1": "fits_pc1_1",
    "PC1_2": "fits_pc1_2",
    "PC2_1": "fits_pc2_1",
    "PC2_2": "fits_pc2_2",
    "PC3_1": "fits_pc3_1",
    "PC3_2": "fits_pc3_2",
    "PC3_3": "fits_pc3_3",
    "CD1_1": "fits_cd1_1",
    "CD1_2": "fits_cd1_2",
    "CD2_1": "fits_cd2_1",
    "CD2_2": "fits_cd2_2",
    "CD3_3": "fits_cd3_3",
    "A_ORDER": "fits_a_order",
    "B_ORDER": "fits_b_order",
    "AP_ORDER": "fits_ap_order",
    "BP_ORDER": "fits_bp_order",
    "A_0_0": "fits_a_0_0",
    "A_0_1": "fits_a_0_1",
    "A_0_2": "fits_a_0_2",
    "A_1_0": "fits_a_1_0",
    "A_1_1": "fits_a_1_1",
    "A_2_0": "fits_a_2_0",
    "B_0_0": "fits_b_0_0",
    "B_0_1": "fits_b_0_1",
    "B_0_2": "fits_b_0_2",
    "B_1_0": "fits_b_1_0",
    "B_1_1": "fits_b_1_1",
    "B_2_0": "fits_b_2_0",
}

# FITS Observation Keywords
FITS_OBSERVATION = {
    "AIRMASS": "fits_airmass",
    "ALT": "fits_alt",
    "AZ": "fits_az",
    "DEC": "fits_dec",
    "RA": "fits_ra",
    "OBJRA": "fits_objra",
    "OBJDEC": "fits_objdec",
    "OBJCTRA": "fits_objctra",
    "OBJCTDEC": "fits_objctdec",
    "TARGRA": "fits_targra",
    "TARGDEC": "fits_targdec",
    "TELRA": "fits_telra",
    "TELDEC": "fits_teldec",
    "ZENITH": "fits_zenith",
    "ZD": "fits_zd",
    "POSANG": "fits_posang",
    "PARANGLE": "fits_parangle",
    "HA": "fits_ha",
    "ST": "fits_st",
    "LST": "fits_lst",
    "UT": "fits_ut",
    "UTC": "fits_utc",
    "JD": "fits_jd",
    "HJD": "fits_hjd",
    "BJD": "fits_bjd",
    "EXPTIME": "fits_exptime",
    "EXPOSURE": "fits_exposure",
    "DARKTIME": "fits_darktime",
    "ELAPSED": "fits_elapsed",
    "ONTIME": "fits_ontime",
    "LIVETIME": "fits_livetime",
    "DEADTIME": "fits_deadtime",
    "OBSMODE": "fits_obsmode",
    "OBSTYPE": "fits_obstype",
    "IMAGETYP": "fits_imagetyp",
    "FRAMEID": "fits_frameid",
    "FRAMENO": "fits_frameno",
    "FILTER": "fits_filter",
    "FILTER1": "fits_filter1",
    "FILTER2": "fits_filter2",
    "FILTER3": "fits_filter3",
    "FILTPOS": "fits_filtpos",
    "FILTNAME": "fits_filtname",
    "DISPERSR": "fits_dispersr",
    "GRATING": "fits_grating",
    "GRISM": "fits_grism",
    "SLIT": "fits_slit",
    "SLITW": "fits_slitw",
    "SLITL": "fits_slitl",
    "SLITANG": "fits_slitang",
    "APERTURE": "fits_aperture",
}

# FITS Telescope/Instrument Keywords
FITS_TELESCOPE = {
    "TELESCOP": "fits_telescop",
    "TELID": "fits_telid",
    "TELNAME": "fits_telname",
    "TELFOCUS": "fits_telfocus",
    "TELSCALE": "fits_telscale",
    "TELALT": "fits_telalt",
    "TELAZ": "fits_telaz",
    "TELPOS": "fits_telpos",
    "TELROT": "fits_telrot",
    "TELTEMP": "fits_teltemp",
    "DOMEAZ": "fits_domeaz",
    "DOMEPOS": "fits_domepos",
    "DOME": "fits_dome",
    "DOMETEMP": "fits_dometemp",
    "FOCUSPOS": "fits_focuspos",
    "FOCUS": "fits_focus",
    "FOCUSOFF": "fits_focusoff",
    "FOCUSZRO": "fits_focuszro",
    "ROTPOS": "fits_rotpos",
    "ROTANGLE": "fits_rotangle",
    "ROTOFF": "fits_rotoff",
    "INSTRUME": "fits_instrume",
    "INSTRID": "fits_instrid",
    "INSTNAME": "fits_instname",
    "INSTMODE": "fits_instmode",
    "INSTCONF": "fits_instconf",
    "CAMPAN": "fits_campan",
    "CAMTILT": "fits_camtilt",
    "CAMROT": "fits_camrot",
    "CAMFOCUS": "fits_camfocus",
    "OPTELEM1": "fits_optelem1",
    "OPTELEM2": "fits_optelem2",
    "OPTELEM3": "fits_optelem3",
    "MIRROR": "fits_mirror",
    "SHUTTER": "fits_shutter",
    "SHUTSTAT": "fits_shutstat",
}

# FITS Detector/CCD Keywords
FITS_DETECTOR = {
    "DETECTOR": "fits_detector",
    "DETID": "fits_detid",
    "DETNAME": "fits_detname",
    "DETSIZE": "fits_detsize",
    "DETSEC": "fits_detsec",
    "CCDSEC": "fits_ccdsec",
    "BIASSEC": "fits_biassec",
    "TRIMSEC": "fits_trimsec",
    "DATASEC": "fits_datasec",
    "AMPSEC": "fits_ampsec",
    "OVERSCAN": "fits_overscan",
    "PRESCAN": "fits_prescan",
    "POSTSCAN": "fits_postscan",
    "CCDSUM": "fits_ccdsum",
    "BINNING": "fits_binning",
    "BINX": "fits_binx",
    "BINY": "fits_biny",
    "CCDXBIN": "fits_ccdxbin",
    "CCDYBIN": "fits_ccdybin",
    "CCDTEMP": "fits_ccdtemp",
    "DEWTEMP": "fits_dewtemp",
    "CCDGAIN": "fits_ccdgain",
    "GAIN": "fits_gain",
    "RDNOISE": "fits_rdnoise",
    "READNOIS": "fits_readnois",
    "SATURATE": "fits_saturate",
    "SATVAL": "fits_satval",
    "NONLIN": "fits_nonlin",
    "DARKCUR": "fits_darkcur",
    "CCDSPEED": "fits_ccdspeed",
    "READMODE": "fits_readmode",
    "READOUT": "fits_readout",
    "AMPNAME": "fits_ampname",
    "PREAMP": "fits_preamp",
    "VSHIFT": "fits_vshift",
    "HSHIFT": "fits_hshift",
    "EMGAIN": "fits_emgain",
    "CCDMODE": "fits_ccdmode",
    "CCDTYPE": "fits_ccdtype",
    "PIXSCAL1": "fits_pixscal1",
    "PIXSCAL2": "fits_pixscal2",
    "PIXSCALE": "fits_pixscale",
    "PLATESCL": "fits_platescl",
    "XPIXSIZE": "fits_xpixsize",
    "YPIXSIZE": "fits_ypixsize",
    "XBINNING": "fits_xbinning",
    "YBINNING": "fits_ybinning",
}

# FITS Calibration Keywords
FITS_CALIBRATION = {
    "FLAT": "fits_flat",
    "FLATNAME": "fits_flatname",
    "FLATFILE": "fits_flatfile",
    "DARK": "fits_dark",
    "DARKNAME": "fits_darkname",
    "DARKFILE": "fits_darkfile",
    "BIAS": "fits_bias",
    "BIASNAME": "fits_biasname",
    "BIASFILE": "fits_biasfile",
    "ZERO": "fits_zero",
    "ZERONAME": "fits_zeroname",
    "ZEROFILE": "fits_zerofile",
    "SKYFLAT": "fits_skyflat",
    "DOMEFLAT": "fits_domeflat",
    "FRINGE": "fits_fringe",
    "FRINGFIL": "fits_fringfil",
    "ILLUM": "fits_illum",
    "ILLUMFIL": "fits_illumfil",
    "BPMASK": "fits_bpmask",
    "BPMFILE": "fits_bpmfile",
    "LINFILE": "fits_linfile",
    "PROCSTAT": "fits_procstat",
    "PROCTIME": "fits_proctime",
    "PIPELINE": "fits_pipeline",
    "PIPEVER": "fits_pipever",
    "PIPECONF": "fits_pipeconf",
    "CALSTAT": "fits_calstat",
    "CALVER": "fits_calver",
    "CALCONF": "fits_calconf",
    "ASTRMSIG": "fits_astrmsig",
    "ASTRERR": "fits_astrerr",
    "PHOTZPT": "fits_photzpt",
    "PHOTZPER": "fits_photzper",
    "PHOTSYS": "fits_photsys",
    "MAGZPT": "fits_magzpt",
    "MAGZPER": "fits_magzper",
    "SEEING": "fits_seeing",
    "FWHM": "fits_fwhm",
    "ELLIP": "fits_ellip",
    "SKYMAG": "fits_skymag",
    "SKYLEVEL": "fits_skylevel",
    "SKYSIGMA": "fits_skysigma",
    "SKYVAR": "fits_skyvar",
}

# FITS Spectroscopy Keywords
FITS_SPECTROSCOPY = {
    "SPECTYPE": "fits_spectype",
    "SPECMODE": "fits_specmode",
    "SPECRES": "fits_specres",
    "DISPAXIS": "fits_dispaxis",
    "DISPDIR": "fits_dispdir",
    "WAVELEN": "fits_wavelen",
    "WAVEMIN": "fits_wavemin",
    "WAVEMAX": "fits_wavemax",
    "WAVEUNIT": "fits_waveunit",
    "WAVECAL": "fits_wavecal",
    "DISPCOR": "fits_dispcor",
    "DISPVAL": "fits_dispval",
    "LINCOR": "fits_lincor",
    "FLUXCAL": "fits_fluxcal",
    "SNRATIO": "fits_snratio",
    "GRATNAME": "fits_gratname",
    "GRATID": "fits_gratid",
    "GRATORD": "fits_gratord",
    "GRATANGL": "fits_gratangl",
    "GRATLPMM": "fits_gratlpmm",
    "GRATBLAZ": "fits_gratblaz",
    "CENWAVE": "fits_cenwave",
    "BANDWID": "fits_bandwid",
    "DICHROIC": "fits_dichroic",
    "COLLIM": "fits_collim",
    "CAMERA": "fits_camera",
    "CAMNAME": "fits_camname",
    "CAMFOCAL": "fits_camfocal",
    "CROSSDSP": "fits_crossdsp",
    "ECHELLE": "fits_echelle",
    "PRISM": "fits_prism",
    "ORDER": "fits_order",
    "ORDERS": "fits_orders",
    "ORDERSEP": "fits_ordersep",
    "VELOCITY": "fits_velocity",
    "VHELIO": "fits_vhelio",
    "VLSR": "fits_vlsr",
    "VBARY": "fits_vbary",
    "VCORR": "fits_vcorr",
    "REDSHIFT": "fits_redshift",
}

# FITS Polarimetry Keywords
FITS_POLARIMETRY = {
    "POLANG": "fits_polang",
    "POLMODE": "fits_polmode",
    "POLTYPE": "fits_poltype",
    "WAVEPL": "fits_wavepl",
    "RETARDER": "fits_retarder",
    "RETANGLE": "fits_retangle",
    "POLSTATE": "fits_polstate",
    "STOKES": "fits_stokes",
    "STOKESI": "fits_stokesi",
    "STOKESQ": "fits_stokesq",
    "STOKESU": "fits_stokesu",
    "STOKESV": "fits_stokesv",
    "POLARIZN": "fits_polarizn",
    "POLANGLE": "fits_polangle",
    "POLERR": "fits_polerr",
}

# FITS Adaptive Optics Keywords
FITS_ADAPTIVE_OPTICS = {
    "AOMODE": "fits_aomode",
    "AOSTAT": "fits_aostat",
    "AOLOOP": "fits_aoloop",
    "AORATE": "fits_aorate",
    "AOGAIN": "fits_aogain",
    "DMTYPE": "fits_dmtype",
    "DMACTS": "fits_dmacts",
    "WFSTYPE": "fits_wfstype",
    "WFSFREQ": "fits_wfsfreq",
    "WFSSUBAR": "fits_wfssubar",
    "WFSSNR": "fits_wfssnr",
    "STREHL": "fits_strehl",
    "LGSMODE": "fits_lgsmode",
    "LGSSTAT": "fits_lgsstat",
    "LGSALT": "fits_lgsalt",
    "LGSPOW": "fits_lgspow",
    "NGSRA": "fits_ngsra",
    "NGSDEC": "fits_ngsdec",
    "NGSMAG": "fits_ngsmag",
    "AOSTAR": "fits_aostar",
    "TTLOOP": "fits_ttloop",
    "TTSTAT": "fits_ttstat",
}

# FITS Interferometry Keywords
FITS_INTERFEROMETRY = {
    "BASELINE": "fits_baseline",
    "BASELEN": "fits_baselen",
    "BASEPA": "fits_basepa",
    "BASESTAT": "fits_basestat",
    "UCOORD": "fits_ucoord",
    "VCOORD": "fits_vcoord",
    "WCOORD": "fits_wcoord",
    "UVDIST": "fits_uvdist",
    "INTRFTYP": "fits_intrftyp",
    "NTELESCO": "fits_ntelesco",
    "TEL1": "fits_tel1",
    "TEL2": "fits_tel2",
    "TEL3": "fits_tel3",
    "TEL4": "fits_tel4",
    "COHERENC": "fits_coherenc",
    "VISAMP": "fits_visamp",
    "VISPHI": "fits_visphi",
    "VIS2DATA": "fits_vis2data",
    "VIS2ERR": "fits_vis2err",
    "T3AMP": "fits_t3amp",
    "T3PHI": "fits_t3phi",
    "T3PHIERR": "fits_t3phierr",
    "DELAY": "fits_delay",
    "OPD": "fits_opd",
}

# FITS Radio Astronomy Keywords
FITS_RADIO = {
    "RESTFREQ": "fits_restfreq",
    "VELO-LSR": "fits_velo_lsr",
    "VELO-HEL": "fits_velo_hel",
    "VELO-OBS": "fits_velo_obs",
    "VELREF": "fits_velref",
    "ALTRVAL": "fits_altrval",
    "ALTRPIX": "fits_altrpix",
    "IMAGFREQ": "fits_imagfreq",
    "TTSYSAV": "fits_ttsysav",
    "TSYS": "fits_tsys",
    "TSYS1": "fits_tsys1",
    "TSYS2": "fits_tsys2",
    "TCAL": "fits_tcal",
    "TAMBIENT": "fits_tambient",
    "TAU225": "fits_tau225",
    "OPACITY": "fits_opacity",
    "SIDEBAND": "fits_sideband",
    "IFCHAN": "fits_ifchan",
    "IFFREQ": "fits_iffreq",
    "LOFREQ": "fits_lofreq",
    "DOPPLER": "fits_doppler",
    "BMAJ": "fits_bmaj",
    "BMIN": "fits_bmin",
    "BPA": "fits_bpa",
    "BEAMMAJ": "fits_beammaj",
    "BEAMMIN": "fits_beammin",
    "BEAMPA": "fits_beampa",
    "ANTENNA": "fits_antenna",
    "ANTNAME": "fits_antname",
    "ANTPOS": "fits_antpos",
    "FEED": "fits_feed",
    "FEEDTYPE": "fits_feedtype",
    "POLRX": "fits_polrx",
    "CORRTYPE": "fits_corrtype",
    "SPECSYS": "fits_specsys",
    "SSYSOBS": "fits_ssysobs",
}

# FITS X-ray/High Energy Keywords
FITS_XRAY = {
    "CHANTYPE": "fits_chantype",
    "DETCHANS": "fits_detchans",
    "CHANBINS": "fits_chanbins",
    "PHATYPE": "fits_phatype",
    "PHAVERSN": "fits_phaversn",
    "AREASCAL": "fits_areascal",
    "BACKSCAL": "fits_backscal",
    "CORRSCAL": "fits_corrscal",
    "ANCRFILE": "fits_ancrfile",
    "RESPFILE": "fits_respfile",
    "BACKFILE": "fits_backfile",
    "CORRFILE": "fits_corrfile",
    "HDUCLAS1": "fits_hduclas1",
    "HDUCLAS2": "fits_hduclas2",
    "HDUCLAS3": "fits_hduclas3",
    "HDUCLAS4": "fits_hduclas4",
    "HDUVERS": "fits_hduvers",
    "HDUVERS1": "fits_hduvers1",
    "HDUVERS2": "fits_hduvers2",
    "FILTER": "fits_filter",
    "ONTIME": "fits_ontime",
    "LIVETIME": "fits_livetime",
    "DEADC": "fits_deadc",
    "TIMEDEL": "fits_timedel",
    "TIMEPIXR": "fits_timepixr",
    "TSTARTI": "fits_tstarti",
    "TSTARTF": "fits_tstartf",
    "TSTOPI": "fits_tstopi",
    "TSTOPF": "fits_tstopf",
    "CLOCKCOR": "fits_clockcor",
    "TELAPSE": "fits_telapse",
    "TARG_ID": "fits_targ_id",
    "OBS_ID": "fits_obs_id",
    "MISSION": "fits_mission",
    "DATAMODE": "fits_datamode",
    "DETNAM": "fits_detnam",
}

# FITS Photometry Keywords
FITS_PHOTOMETRY = {
    "PHOTFLAM": "fits_photflam",
    "PHOTPLAM": "fits_photplam",
    "PHOTBW": "fits_photbw",
    "PHOTZPT": "fits_photzpt",
    "PHOTMODE": "fits_photmode",
    "PHOTCORR": "fits_photcorr",
    "ABMAG": "fits_abmag",
    "STMAG": "fits_stmag",
    "VEGAMAG": "fits_vegamag",
    "ZPFLAM": "fits_zpflam",
    "ZPSTMAG": "fits_zpstmag",
    "ZPABMAG": "fits_zpabmag",
    "ZPVEGA": "fits_zpvega",
    "PHOTFNU": "fits_photfnu",
    "MAGZERO": "fits_magzero",
    "EXTINCT": "fits_extinct",
    "AIRMASS": "fits_airmass",
    "FCOL": "fits_fcol",
    "FCOLNAME": "fits_fcolname",
    "COLBAND": "fits_colband",
    "PHOTOMET": "fits_photomet",
}

# FITS Multi-Extension Keywords
FITS_EXTENSION = {
    "EXTNAME": "fits_extname",
    "EXTVER": "fits_extver",
    "EXTLEVEL": "fits_extlevel",
    "HDUNAME": "fits_hduname",
    "HDULEVEL": "fits_hdulevel",
    "HDUVER": "fits_hduver",
    "INHERIT": "fits_inherit",
    "NEXTEND": "fits_nextend",
    "NSCIEXT": "fits_nsciext",
    "NERROR": "fits_nerror",
    "NDQEXT": "fits_ndqext",
    "ROOTNAME": "fits_rootname",
    "FILENAME": "fits_filename",
    "FILETYPE": "fits_filetype",
    "PRODTYPE": "fits_prodtype",
    "PROPID": "fits_propid",
    "PROPOSAL": "fits_proposal",
    "PI_NAME": "fits_pi_name",
    "PIID": "fits_piid",
    "SCICAT": "fits_scicat",
    "PROGID": "fits_progid",
    "PROGTYP": "fits_progtyp",
    "OBSID": "fits_obsid",
    "RUNID": "fits_runid",
    "EXPID": "fits_expid",
    "GROUPID": "fits_groupid",
    "DESSION": "fits_dession",
}

# FITS Solar Telescope Keywords
FITS_SOLAR = {
    "DSUN_OBS": "fits_dsun_obs",
    "HGLN_OBS": "fits_hgln_obs",
    "HGLT_OBS": "fits_hglt_obs",
    "CRLN_OBS": "fits_crln_obs",
    "CRLT_OBS": "fits_crlt_obs",
    "CAR_ROT": "fits_car_rot",
    "RSUN_REF": "fits_rsun_ref",
    "RSUN_OBS": "fits_rsun_obs",
    "SOLAR_R": "fits_solar_r",
    "SOLAR_P": "fits_solar_p",
    "SOLAR_B0": "fits_solar_b0",
    "SOLAR_L0": "fits_solar_l0",
    "XCEN": "fits_xcen",
    "YCEN": "fits_ycen",
    "CROTA": "fits_crota",
    "SOLAR_EP": "fits_solar_ep",
    "SOLAR_RA": "fits_solar_ra",
    "SOLAR_DEC": "fits_solar_dec",
    "INST_ROT": "fits_inst_rot",
    "WAVEMIN": "fits_wavemin",
    "WAVEMAX": "fits_wavemax",
    "WAVELNTH": "fits_wavelnth",
    "ATMOSHEL": "fits_atmoshel",
}

# FITS Table Keywords
FITS_TABLE = {
    "TTYPE1": "fits_ttype1",
    "TTYPE2": "fits_ttype2",
    "TTYPE3": "fits_ttype3",
    "TTYPE4": "fits_ttype4",
    "TTYPE5": "fits_ttype5",
    "TFORM1": "fits_tform1",
    "TFORM2": "fits_tform2",
    "TFORM3": "fits_tform3",
    "TFORM4": "fits_tform4",
    "TFORM5": "fits_tform5",
    "TUNIT1": "fits_tunit1",
    "TUNIT2": "fits_tunit2",
    "TUNIT3": "fits_tunit3",
    "TUNIT4": "fits_tunit4",
    "TUNIT5": "fits_tunit5",
    "TBCOL1": "fits_tbcol1",
    "TBCOL2": "fits_tbcol2",
    "TBCOL3": "fits_tbcol3",
    "TDIM1": "fits_tdim1",
    "TDIM2": "fits_tdim2",
    "TDIM3": "fits_tdim3",
    "TNULL1": "fits_tnull1",
    "TNULL2": "fits_tnull2",
    "TNULL3": "fits_tnull3",
    "TSCAL1": "fits_tscal1",
    "TSCAL2": "fits_tscal2",
    "TSCAL3": "fits_tscal3",
    "TZERO1": "fits_tzero1",
    "TZERO2": "fits_tzero2",
    "TZERO3": "fits_tzero3",
    "TDISP1": "fits_tdisp1",
    "TDISP2": "fits_tdisp2",
    "TDISP3": "fits_tdisp3",
    "NAXIS1": "fits_naxis1",
    "NAXIS2": "fits_naxis2",
}

# FITS Compression Keywords
FITS_COMPRESSION = {
    "ZIMAGE": "fits_zimage",
    "ZCMPTYPE": "fits_zcmptype",
    "ZBITPIX": "fits_zbitpix",
    "ZNAXIS": "fits_znaxis",
    "ZNAXIS1": "fits_znaxis1",
    "ZNAXIS2": "fits_znaxis2",
    "ZTILE1": "fits_ztile1",
    "ZTILE2": "fits_ztile2",
    "ZNAME1": "fits_zname1",
    "ZNAME2": "fits_zname2",
    "ZVAL1": "fits_zval1",
    "ZVAL2": "fits_zval2",
    "ZDITHER0": "fits_zdither0",
    "ZQUANTIZ": "fits_zquantiz",
    "ZSIMPLE": "fits_zsimple",
    "ZTENSION": "fits_ztension",
    "ZEXTEND": "fits_zextend",
    "ZBLOCKED": "fits_zblocked",
    "ZPCOUNT": "fits_zpcount",
    "ZGCOUNT": "fits_zgcount",
    "ZHECKSUM": "fits_zhecksum",
    "ZDATASUM": "fits_zdatasum",
}


def get_all_fits_keywords() -> Dict[str, str]:
    """Return all FITS keyword mappings."""
    all_keywords = {}
    all_keywords.update(FITS_MANDATORY)
    all_keywords.update(FITS_RESERVED)
    all_keywords.update(FITS_WCS)
    all_keywords.update(FITS_OBSERVATION)
    all_keywords.update(FITS_TELESCOPE)
    all_keywords.update(FITS_DETECTOR)
    all_keywords.update(FITS_CALIBRATION)
    all_keywords.update(FITS_SPECTROSCOPY)
    all_keywords.update(FITS_POLARIMETRY)
    all_keywords.update(FITS_ADAPTIVE_OPTICS)
    all_keywords.update(FITS_INTERFEROMETRY)
    all_keywords.update(FITS_RADIO)
    all_keywords.update(FITS_XRAY)
    all_keywords.update(FITS_PHOTOMETRY)
    all_keywords.update(FITS_EXTENSION)
    all_keywords.update(FITS_SOLAR)
    all_keywords.update(FITS_TABLE)
    all_keywords.update(FITS_COMPRESSION)
    return all_keywords


def get_fits_complete_field_count() -> int:
    """Return total number of FITS fields."""
    return len(get_all_fits_keywords())


# FITS Extended WCS Keywords (Celestial Reference Frames)
FITS_EXTENDED_WCS = {
    "WCSALPHA": "fits_wcs_alpha",
    "WCSBETA": "fits_wcs_beta",
    "WCSXPH": "fits_wcs_xph",
    "WCSYPH": "fits_wcs_yph",
    "WCSMETH": "fits_wcs_method",
    "WCSFWHM": "fits_wcs_fwhm",
    "WCSSCL": "fits_wcs_scale",
    "WCSSEP": "fits_wcs_sep",
    "WCSNCP": "fits_wcs_ncp",
    "WCSGAMMA": "fits_wcs_gamma",
    "WCSBETA0": "fits_wcs_beta0",
    "WCSALPH0": "fits_wcs_alph0",
    "PV1_0": "fits_pv1_0",
    "PV1_1": "fits_pv1_1",
    "PV1_2": "fits_pv1_2",
    "PV1_3": "fits_pv1_3",
    "PV1_4": "fits_pv1_4",
    "PV1_5": "fits_pv1_5",
    "PV1_6": "fits_pv1_6",
    "PV1_7": "fits_pv1_7",
    "PV1_8": "fits_pv1_8",
    "PV1_9": "fits_pv1_9",
    "PV1_10": "fits_pv1_10",
    "PV2_0": "fits_pv2_0",
    "PV2_1": "fits_pv2_1",
    "PV2_2": "fits_pv2_2",
    "PV2_3": "fits_pv2_3",
    "PV2_4": "fits_pv2_4",
    "PV2_5": "fits_pv2_5",
    "PV2_6": "fits_pv2_6",
    "PV2_7": "fits_pv2_7",
    "PV2_8": "fits_pv2_8",
    "PV2_9": "fits_pv2_9",
    "PV2_10": "fits_pv2_10",
    "SIP_A_0": "fits_sip_a_0",
    "SIP_A_1": "fits_sip_a_1",
    "SIP_A_2": "fits_sip_a_2",
    "SIP_A_3": "fits_sip_a_3",
    "SIP_A_4": "fits_sip_a_4",
    "SIP_B_0": "fits_sip_b_0",
    "SIP_B_1": "fits_sip_b_1",
    "SIP_B_2": "fits_sip_b_2",
    "SIP_B_3": "fits_sip_b_3",
    "SIP_B_4": "fits_sip_b_4",
    "SIP_AP_0": "fits_sip_ap_0",
    "SIP_AP_1": "fits_sip_ap_1",
    "SIP_AP_2": "fits_sip_ap_2",
    "SIP_AP_3": "fits_sip_ap_3",
    "SIP_AP_4": "fits_sip_ap_4",
    "SIP_BP_0": "fits_sip_bp_0",
    "SIP_BP_1": "fits_sip_bp_1",
    "SIP_BP_2": "fits_sip_bp_2",
    "SIP_BP_3": "fits_sip_bp_3",
    "SIP_BP_4": "fits_sip_bp_4",
    "WCAX": "fits_wcax",
    "WCSNAME_TAB": "fits_wcsname_tab",
    "WTYPE": "fits_wtype",
    "WTSYS": "fits_wtsys",
    "WTRUTH": "fits_wtruth",
}

# FITS Solar System Keywords
FITS_SOLAR_SYSTEM = {
    "OBJECT": "fits_object",
    "OBJNAME": "fits_objname",
    "OBJTYPE": "fits_objtype",
    "OBJSIZE": "fits_objsize",
    "OBJDIST": "fits_objdist",
    "OBJAZ": "fits_objaz",
    "OBJEL": "fits_objel",
    "MOONRA": "fits_moonra",
    "MOONDEC": "fits_moondec",
    "MOONAZ": "fits_moonaz",
    "MOONEL": "fits_moonel",
    "MOONPH": "fits_moonph",
    "MOONAGE": "fits_moonage",
    "MOONDIST": "fits_moondist",
    "SUNRA": "fits_sunra",
    "SUNDEC": "fits_sundec",
    "SUNAZ": "fits_sunaz",
    "SUNEL": "fits_sunel",
    "SUNDIST": "fits_sundist",
    "PLANET": "fits_planet",
    "PLANETS": "fits_planets",
    "PLANETRA": "fits_planetra",
    "PLANETDEC": "fits_planetdec",
    "PLANETAZ": "fits_planetaz",
    "PLANETEL": "fits_planetel",
    "PLANETDIST": "fits_planetdist",
    "COMET": "fits_comet",
    "COMETRA": "fits_cometra",
    "COMETDEC": "fits_cometdec",
    "COMETDIST": "fits_cometdist",
    "ASTEROID": "fits_asteroid",
    "ASTEROIDN": "fits_asteroidn",
    "ASTEROIDRA": "fits_asteroidra",
    "ASTEROIDDEC": "fits_asteroiddec",
    "ASTEROIDDIST": "fits_asteroiddist",
    "STAR": "fits_star",
    "STARNAME": "fits_starname",
    "STARRA": "fits_star_ra",
    "STARDEC": "fits_star_dec",
    "STARBV": "fits_starbv",
    "STARSPEC": "fits_starspec",
    "STARPMRA": "fits_starpmra",
    "STARPMDEC": "fits_starpmdec",
    "STARPAR": "fits_starpar",
    "STARFUX": "fits_starfux",
    "GALAXY": "fits_galaxy",
    "GALAXYN": "fits_galaxyn",
    "GALAXYRA": "fits_galaxyra",
    "GALAXYDEC": "fits_galaxydec",
    "GALAXYK": "fits_galaxyk",
    "GALAXYM": "fits_galaxym",
    "NEBULA": "fits_nebula",
    "NEBULANAME": "fits_nebulaname",
    "CLUSTER": "fits_cluster",
    "CLUSTNAME": "fits_clustname",
    "CLUSTZ": "fits_clustz",
    "CLUSTN": "fits_clustn",
}

# FITS Survey Keywords
FITS_SURVEY = {
    "SURVEY": "fits_survey",
    "SURVEYID": "fits_surveyid",
    "SURVEYCRS": "fits_surveycrs",
    "TILES": "fits_tiles",
    "TILENAME": "fits_tilename",
    "TILEID": "fits_tileid",
    "TILERA": "fits_tilera",
    "TILEDEC": "fits_tiledec",
    "TILENX": "fits_tilenx",
    "TILENY": "fits_tileny",
    "PATCH": "fits_patch",
    "SKYMAP": "fits_skymap",
    "STRIP": "fits_strip",
    "STRIPID": "fits_stripid",
    "RUN": "fits_run",
    "RERUN": "fits_rerun",
    "CAMCOL": "fits_camcol",
    "FIELD": "fits_field",
    "FRAME": "fits_frame",
    "RAFTER": "fits_rafter",
    "DECAFTER": "fits_decafter",
    "PHOTSYS": "fits_photsys",
    "BANDPASS": "fits_bandpass",
    "BANDSHIFT": "fits_bandshift",
    "BANDWIDTH": "fits_bandwidth",
    "CALIB": "fits_calib",
    "CALIBFLUX": "fits_calibflux",
    "CALIBERR": "fits_caliberr",
    "DEPTH": "fits_depth",
    "DEPTH95": "fits_depth95",
    "AREA": "fits_area",
    "DENSITY": "fits_density",
    "SKYVAR": "fits_skyvar",
    "SKYSIGMA": "fits_skysigma",
    "SKYMED": "fits_skymed",
    "SKYSKEW": "fits_skyshew",
    "PSFFWHM": "fits_psffwhm",
    "PSFCHI2": "fits_psfchi2",
    "PSFK": "fits_psfk",
    "PSF1": "fits_psf1",
    "PSF2": "fits_psf2",
    "PSF3": "fits_psf3",
    "PSF4": "fits_psf4",
}

# FITS Time Series Keywords
FITS_TIME_SERIES = {
    "TIMEREF": "fits_timeref",
    "TIMESYS": "fits_timesys",
    "TIMEUNIT": "fits_timeunit",
    "MJD-OBS": "fits_mjd_obs",
    "MJD-BEG": "fits_mjd_beg",
    "MJD-END": "fits_mjd_end",
    "MJD-AVG": "fits_mjd_avg",
    "DATE-BEG": "fits_date_beg",
    "DATE-END": "fits_date_end",
    "DATE-AVG": "fits_date_avg",
    "TELAPSE": "fits_telapse",
    "TSTART": "fits_tstart",
    "TSTOP": "fits_tstop",
    "EXPOSURE": "fits_exposure",
    "DEADTIME": "fits_deadtime",
    "ONTIME": "fits_ontime",
    "LIVETIME": "fits_livetime",
    "TIMEDEL": "fits_timedel",
    "TIMEPIXR": "fits_timepixr",
    "TIMEZERO": "fits_timezero",
    "CLOCKCOR": "fits_clockcor",
    "LEAPINIT": "fits_leapinit",
    "LEAPSEC": "fits_leapsec",
    "TIMER_VAR": "fits_timer_var",
    "TIME_OBS": "fits_time_obs",
    "TIME_END": "fits_time_end",
    "OBSSTART": "fits_obsstart",
    "OBSSTOP": "fits_obsstop",
    "OBSMODE": "fits_obsmode",
    "OBS_TYPE": "fits_obs_type",
    "NEXP": "fits_nexp",
    "NEVENTS": "fits_nevents",
    "NPIXS": "fits_npixs",
    "RATE": "fits_rate",
    "RATER": "fits_rater",
    "ERROR": "fits_error",
    "FRACEX": "fits_frac_ex",
    "FRACLO": "fits_fraclo",
    "FRACHI": "fits_frachi",
    "FRACISR": "fits_fracisr",
}

# FITS High-Energy Astrophysics Keywords
FITS_HIGH_ENERGY = {
    "TELESCOP": "fits_telescop",
    "INSTRUME": "fits_instrume",
    "MISSION": "fits_mission",
    "OBSERVER": "fits_observer",
    "OBS_ID": "fits_obs_id",
    "PROP_ID": "fits_prop_id",
    "PROPOSAL": "fits_proposal",
    "TARGET_NAME": "fits_target_name",
    "TARGET_CLASS": "fits_target_class",
    "TARGET_DEC": "fits_target_dec",
    "TARGET_RA": "fits_target_ra",
    "RA_OBJ": "fits_ra_obj",
    "DEC_OBJ": "fits_dec_obj",
    "GLON_OBJ": "fits_glon_obj",
    "GLAT_OBJ": "fits_glat_obj",
    "ELON_OBJ": "fits_elon_obj",
    "ELAT_OBJ": "fits_elat_obj",
    "RA_NOM": "fits_ra_nom",
    "DEC_NOM": "fits_dec_nom",
    "PA_NOM": "fits_pa_nom",
    "RA_PNT": "fits_ra_pnt",
    "DEC_PNT": "fits_dec_pnt",
    "PA_PNT": "fits_pa_pnt",
    "ROLL_PNT": "fits_roll_pnt",
    "RA_SC": "fits_ra_sc",
    "DEC_SC": "fits_dec_sc",
    "ROLL_SC": "fits_roll_sc",
    "SUBARRAY": "fits_subarray",
    "NROW": "fits_nrow",
    "NCHIP": "fits_nchip",
    "NAMP": "fits_namp",
    "READOUT": "fits_readout",
    "DATAMODE": "fits_datamode",
    "FRAMTIME": "fits_framtime",
    "CYCLES": "fits_cycles",
    "EV_CNT": "fits_ev_cnt",
    "EV_RATE": "fits_ev_rate",
    "DTC_COR": "fits_dtc_cor",
    "ENERG_LO": "fits_energ_lo",
    "ENERG_HI": "fits_energ_hi",
    "DET_ID": "fits_det_id",
    "FILTER": "fits_filter",
    "FILTER_ID": "fits_filter_id",
    "FOC_POS": "fits_foc_pos",
    "GRATING": "fits_grating",
    "GRATING_ID": "fits_grating_id",
    "CCD_ID": "fits_ccd_id",
    "CCD_NODE": "fits_ccd_node",
    "CCD_TEMP": "fits_ccd_temp",
    "FEP_CNT": "fits_fep_cnt",
    "BIAS_FLAG": "fits_bias_flag",
    "GTI": "fits_gti",
    "GTI_START": "fits_gti_start",
    "GTI_STOP": "fits_gti_stop",
    "GTI_OBJ": "fits_gti_obj",
    "GTI_OND": "fits_gti_ond",
    "GTI_OFF": "fits_gti_off",
    "EVENTS": "fits_events",
    "EVENTS1": "fits_events1",
    "EVENTS2": "fits_events2",
    "TIMECOL": "fits_timecol",
    "RAWCOL": "fits_rawcol",
    "DECCOL": "fits_deccol",
    "ENERGYCOL": "fits_energycol",
    "PIXCOL": "fits_pixcol",
    "PHASECOL": "fits_phasecol",
}

# FITS Cosmology Keywords
FITS_COSMOLOGY = {
    "COSMOL": "fits_cosmol",
    "H_0": "fits_h0",
    "OMEGA_M": "fits_omega_m",
    "OMEGA_L": "fits_omega_l",
    "OMEGA_K": "fits_omega_k",
    "OMEGA_R": "fits_omega_r",
    "W_0": "fits_w0",
    "W_A": "fits_wa",
    "SIGMA_8": "fits_sigma8",
    "NS": "fits_ns",
    "TAU": "fits_tau",
    "REDSHIFT": "fits_redshift",
    "REDSHIFT_E": "fits_redshift_e",
    "REDSHIFT_L": "fits_redshift_l",
    "REDSHIFT_U": "fits_redshift_u",
    "VELOCITY": "fits_velocity",
    "DISTANCE": "fits_distance",
    "DISTMOD": "fits_distmod",
    "LUMDIST": "fits_lumdist",
    "ANGDIAM": "fits_angdiam",
    "COMOVING": "fits_comoving",
    "LOOKBACK": "fits_lookback",
    "CRITICAL": "fits_critical",
    "SBAR": "fits_sbar",
    "AGE": "fits_age",
    "AGE_U": "fits_age_u",
    "AGE_L": "fits_age_l",
    "Z_INIT": "fits_z_init",
    "Z_FINAL": "fits_z_final",
    "Z_FORM": "fits_z_form",
    "Z_OBS": "fits_z_obs",
    "Z_PHOTO": "fits_z_photo",
    "Z_SPEC": "fits_z_spec",
    "Z_ERR": "fits_z_err",
    "Z_Qflag": "fits_z_qflag",
    "Z_NCONV": "fits_z_nconv",
    "Z_ZWARNING": "fits_z_zwarning",
}

# FITS Optical/IR Keywords
FITS_OPTICAL_IR = {
    "OBSTYPE": "fits_obstype",
    "OBSMODE": "fits_obsmode",
    "IMAGETYP": "fits_imagetyp",
    "FILTER": "fits_filter",
    "FILTERID": "fits_filterid",
    "FILTER1": "fits_filter1",
    "FILTER2": "fits_filter2",
    "FILTER3": "fits_filter3",
    "FILTNAME": "fits_filtname",
    "FILTPOS": "fits_filtpos",
    "EXPTIME": "fits_exptime",
    "EXPOSURE": "fits_exposure",
    "ELAPTIME": "fits_elaptime",
    "AIRMASS": "fits_airmass",
    "SEEING": "fits_seeing",
    "FWHM": "fits_fwhm",
    "IQ": "fits_iq",
    "SKY": "fits_sky",
    "SKYMAG": "fits_skymag",
    "SKYBRT": "fits_skybrt",
    "SKYERR": "fits_skyerr",
    "CCDTEMP": "fits_ccdtemp",
    "CCDHUMID": "fits_ccdhumid",
    "CCDPRESS": "fits_ccdpress",
    "DEWTEMP": "fits_dewtemp",
    "WINDSPD": "fits_windspd",
    "WINDDIR": "fits_winddir",
    "HUMIDITY": "fits_humidity",
    "AMBIENTT": "fits_ambientt",
    "PRESSURE": "fits_pressure",
    "FOCUS": "fits_focus",
    "FOCUSPOS": "fits_focuspos",
    "FOCUSERR": "fits_focuserr",
    "DOME": "fits_dome",
    "DOMEAZ": "fits_domeaz",
    "DOMEST": "fits_domes t",
    "MIRROR": "fits_mirror",
    "MIRRTEMP": "fits_mirrtemp",
    "SECMIR": "fits_secmir",
    "PRIMOPT": "fits_primopt",
    "SECOPT": "fits_secopt",
    "TERTOPT": "fits_tertopt",
    "COLLIM": "fits_collim",
    "ALIGN": "fits_align",
    "ALIGNERR": "fits_alignerr",
    "ENC": "fits_enc",
    "ENCTIME": "fits_enctime",
    "ENCERR": "fits_encerr",
    "TRACKING": "fits_tracking",
    "TRKERR": "fits_trkerr",
    "GUIDER": "fits_guider",
    "GUIDEST": "fits_guiderst",
    "GUIDFWHM": "fits_guidfwhm",
    "GUIDERR": "fits_guiderr",
    "AGSTATE": "fits_agstate",
    "AGCERR": "fits_agcerr",
}

# FITS Radio Millimeter Keywords
FITS_RADIO_MM = {
    "ANTENNA": "fits_antenna",
    "ANTNAME": "fits_antname",
    "ANTDIA": "fits_antdia",
    "ANTMAP": "fits_antmap",
    "ANTPOS": "fits_antpos",
    "APERTURE": "fits_aperture",
    "BASELINE": "fits_baseline",
    "BASELIN": "fits_baselin",
    "BASEPA": "fits_basepa",
    "BEAMEFF": "fits_beameff",
    "BMAJ": "fits_bmaj",
    "BMIN": "fits_bmin",
    "BPA": "fits_bpa",
    "BSCALE": "fits_bscale",
    "BUNIT": "fits_bunit",
    "BZERO": "fits_bzero",
    "CALCOLD": "fits_calcold",
    "CALDATE": "fits_caldate",
    "CALERR": "fits_calerr",
    "CALFILE": "fits_calfile",
    "CALMODE": "fits_calmode",
    "CALSTAT": "fits_calstat",
    "CALTYPE": "fits_caltype",
    "CANLISM": "fits_canlism",
    "CDELT1": "fits_cdelt1",
    "CDELT2": "fits_cdelt2",
    "CRPIX1": "fits_crpix1",
    "CRPIX2": "fits_crpix2",
    "CRVAL1": "fits_crval1",
    "CRVAL2": "fits_crval2",
    "CTYPE1": "fits_ctype1",
    "CTYPE2": "fits_ctype2",
    "CUNIT1": "fits_cunit1",
    "CUNIT2": "fits_cunit2",
    "DATAMAX": "fits_datamax",
    "DATAMIN": "fits_datamin",
    "EPOCH": "fits_epoch",
    "EQUINOX": "fits_equinox",
    "EXTEND": "fits_extend",
    "GCOUNT": "fits_gcount",
    "HISTORY": "fits_history",
    "INSTRUME": "fits_instrume",
    "LONPOLE": "fits_lonpole",
    "OBJECT": "fits_object",
    "OBSERVER": "fits_observer",
    "OBSERVAT": "fits_observat",
    "ORIGIN": "fits_origin",
    "PCOUNT": "fits_pcount",
    "PROPAG": "fits_prop",
    "RESTFREQ": "fits_restfreq",
    "SIMPLE": "fits_simple",
    "SPECSYS": "fits_specsys",
    "SSYSOBS": "fits_ssysobs",
    "TELESCOP": "fits_telescop",
    "TIMESYS": "fits_timesys",
    "VELO-LSR": "fits_velo_lsr",
    "VELREF": "fits_velref",
}

# FITS Gravitational Wave Keywords
FITS_GW = {
    "GW_INSTR": "fits_gw_instr",
    "GW_EVENT": "fits_gw_event",
    "GW_TRIG_ID": "fits_gw_trig_id",
    "GW_FAR": "fits_gw_far",
    "GW_PROB": "fits_gw_prob",
    "GW_BNS_INCL": "fits_gw_bns_incl",
    "GW_BNS_MASS1": "fits_gw_bns_mass1",
    "GW_BNS_MASS2": "fits_gw_bns_mass2",
    "GW_NSBH_INCL": "fits_gw_nsbh_incl",
    "GW_NSBH_MASS1": "fits_gw_nsbh_mass1",
    "GW_NSBH_MASS2": "fits_gw_nsbh_mass2",
    "GW_BBH_INCL": "fits_gw_bbh_incl",
    "GW_BBH_MASS1": "fits_gw_bbh_mass1",
    "GW_BBH_MASS2": "fits_gw_bbh_mass2",
    "GW_SkyLocation": "fits_gw_skylocation",
    "GW_RA": "fits_gw_ra",
    "GW_DEC": "fits_gw_dec",
    "GW_ERR90": "fits_gw_err90",
    "GW_ERROR": "fits_gw_error",
    "GW_LUM_DIST": "fits_gw_lum_dist",
    "GW_REDSHIFT": "fits_gw_redshift",
    "GW_LOCALIZATION": "fits_gw_localization",
    "GW_SNR": "fits_gw_snr",
    "GW_HM_CHANNEL": "fits_gw_hm_channel",
    "GW_OBS_TIME": "fits_gw_obs_time",
    "GW_DETECTOR": "fits_gw_detector",
    "GW_FFINAL": "fits_gw_ffinal",
}

# FITS Neutrino Keywords
FITS_NEUTRINO = {
    "NU_INSTR": "fits_nu_instr",
    "NU_EVENT": "fits_nu_event",
    "NU_TRIG_ID": "fits_nu_trig_id",
    "NU_ENERGY": "fits_nu_energy",
    "NU_ENERGY_ERR": "fits_nu_energy_err",
    "NU_DIR": "fits_nu_dir",
    "NU_DIR_ERR": "fits_nu_dir_err",
    "NU_RA": "fits_nu_ra",
    "NU_DEC": "fits_nu_dec",
    "NU_ERR90": "fits_nu_err90",
    "NU_ERROR": "fits_nu_error",
    "NU_GLIKE": "fits_nu_glike",
    "NU_NTRK": "fits_nu_ntrk",
    "NU_NHIT": "fits_nu_nhit",
    "NU_RMS": "fits_nu_rms",
    "NU_ANGERR": "fits_nu_angerr",
    "NU_BETA": "fits_nu_beta",
    "NU_TOPOLOGY": "fits_nu_topology",
    "NU_FITSTATUS": "fits_nu_fitstatus",
    "NU_LIKELIHOOD": "fits_nu_likelihood",
    "NU_CHI2": "fits_nu_chi2",
    "NU_NDF": "fits_nu_ndf",
    "NU_TYPE": "fits_nu_type",
    "NU_DET": "fits_nu_det",
    "NU_RUN": "fits_nu_run",
    "NU_SUB": "fits_nu_sub",
    "NU_EVTNO": "fits_nu_evtno",
    "NU_TIME": "fits_nu_time",
    "NU_MJD": "fits_nu_mjd",
}

# FITS Multi-Messenger Keywords
FITS_MULTI_MESSENGER = {
    "MM_TYPE": "fits_mm_type",
    "MM_SOURCE": "fits_mm_source",
    "MM_EVENT": "fits_mm_event",
    "MM_TRIG": "fits_mm_trig",
    "MM_ALERT": "fits_mm_alert",
    "MM_CIRC": "fits_mm_circ",
    "MM_RANK": "fits_mm_rank",
    "MM_SCORE": "fits_mm_score",
    "MM_PROB": "fits_mm_prob",
    "MM_SIGNIFICANCE": "fits_mm_significance",
    "MM_COINC_WINDOW": "fits_mm_coinc_window",
    "MM_TIME_DIFF": "fits_mm_time_diff",
    "MM_SPATIAL_DIFF": "fits_mm_spatial_diff",
    "MM_ARCHIVE": "fits_mm_archive",
    "MM_CATALOG": "fits_mm_catalog",
    "MM_ID": "fits_mm_id",
    "MM_RA": "fits_mm_ra",
    "MM_DEC": "fits_mm_dec",
    "MM_ERR": "fits_mm_err",
    "MM_REDSHIFT": "fits_mm_redshift",
    "MM_DISTANCE": "fits_mm_distance",
    "MM_LUMINOSITY": "fits_mm_luminosity",
    "MM_ENERGY": "fits_mm_energy",
    "MM_FLUX": "fits_mm_flux",
    "MM_SPECTRAL_INDEX": "fits_mm_spectral_index",
    "MM_TEMPORAL_CLASS": "fits_mm_temporal_class",
}

# FITS Machine Learning Keywords
FITS_ML = {
    "ML_METHOD": "fits_ml_method",
    "ML_MODEL": "fits_ml_model",
    "ML_TRAIN": "fits_ml_train",
    "ML_VERSION": "fits_ml_version",
    "ML_CLASS": "fits_ml_class",
    "ML_PROB": "fits_ml_prob",
    "ML_CONF": "fits_ml_conf",
    "ML_SCORE": "fits_ml_score",
    "ML_RANK": "fits_ml_rank",
    "ML_LABEL": "fits_ml_label",
    "ML_PROB_CLASS0": "fits_ml_prob_class0",
    "ML_PROB_CLASS1": "fits_ml_prob_class1",
    "ML_PROB_CLASS2": "fits_ml_prob_class2",
    "ML_PROB_CLASS3": "fits_ml_prob_class3",
    "ML_PROB_CLASS4": "fits_ml_prob_class4",
    "ML_FEATURES": "fits_ml_features",
    "ML_N_FEATURES": "fits_ml_n_features",
    "ML_TRAIN_SCORE": "fits_ml_train_score",
    "ML_VAL_SCORE": "fits_ml_val_score",
    "ML_TEST_SCORE": "fits_ml_test_score",
    "ML_CV_SCORE": "fits_ml_cv_score",
    "ML_AUC": "fits_ml_auc",
    "ML_ROC": "fits_ml_roc",
    "ML_F1": "fits_ml_f1",
    "ML_PRECISION": "fits_ml_precision",
    "ML_RECALL": "fits_ml_recall",
    "ML_TPR": "fits_ml_tpr",
    "ML_FPR": "fits_ml_fpr",
    "ML_TNR": "fits_ml_tnr",
    "ML_FNR": "fits_ml_fnr",
}

# FITS Pipeline Processing Keywords
FITS_PIPELINE = {
    "PIPELINE": "fits_pipeline",
    "PIPEVER": "fits_pipever",
    "PIPEDATE": "fits_pipedate",
    "PIPECONF": "fits_pipeconf",
    "PRODUCER": "fits_producer",
    "PRODVER": "fits_prodver",
    "PRODDATE": "fits_proddate",
    "PROCSTAT": "fits_procstat",
    "PROCTYPE": "fits_proctype",
    "PROCCODE": "fits_proccode",
    "PROCMOD": "fits_procmod",
    "PROCSTEP": "fits_procstep",
    "PROCTIME": "fits_proctime",
    "PROCERR": "fits_procerr",
    "PARENT": "fits_parent",
    "CHILD": "fits_child",
    "REFTYPE": "fits_reftype",
    "CALDBVER": "fits_caldbver",
    "CALDBNAME": "fits_caldbname",
    "CALDBDATE": "fits_caldbdate",
    "RCalibVer": "fits_rcalibver",
    "RCalibDate": "fits_rcalibdate",
    "DRPVER": "fits_drpver",
    "DRPDATE": "fits_drpdate",
    "DRPSYS": "fits_drpsys",
    "DRPSTACK": "fits_drpstack",
    "DRPCONF": "fits_drpconf",
    "DRPMODEL": "fits_drpmodel",
    "DAPVER": "fits_dapver",
    "DAPTYPE": "fits_daptype",
    "DATAPROD": "fits_dataprod",
    "PROD_TYPE": "fits_prod_type",
    "PROD_VER": "fits_prod_ver",
    "PROD_DATE": "fits_prod_date",
    "CPDBVER": "fits_codbver",
    "CPDBPROD": "fits_codbprod",
    "ASRUN": "fits_asrun",
    "OBS_ID": "fits_obs_id",
    "OBSERVER": "fits_observer",
    "PROPOSER": "fits_proposer",
    "PI_NAME": "fits_pi_name",
    "PI_INST": "fits_pi_inst",
    "PROP_ID": "fits_prop_id",
    "PROP_TITLE": "fits_prop_title",
    "PROP_TYPE": "fits_prop_type",
    "PROP_ITTYP": "fits_prop_ittyp",
    "SEMESTER": "fits_semester",
    "SEMESTER_ID": "fits_semester_id",
}

# FITS Spectroscopic Survey Keywords
FITS_SPEC_SURVEY = {
    "SPEC_ID": "fits_spec_id",
    "SPEC_RA": "fits_spec_ra",
    "SPEC_DEC": "fits_spec_dec",
    "SPEC_Z": "fits_spec_z",
    "SPEC_Z_ERR": "fits_spec_z_err",
    "SPEC_Z_WARN": "fits_spec_z_warn",
    "SPEC_QF": "fits_spec_qf",
    "SPEC_CLASS": "fits_spec_class",
    "SPEC_SUBCL": "fits_spec_subcl",
    "SPEC_S/N": "fits_spec_sn",
    "SPEC_S/N_G": "fits_spec_sn_g",
    "SPEC_S/N_R": "fits_spec_sn_r",
    "SPEC_S/N_I": "fits_spec_sn_i",
    "SPEC_EL": "fits_spec_el",
    "SPEC_HBT": "fits_spec_hbt",
    "SPEC_TEFF": "fits_spec_teff",
    "SPEC_LOGG": "fits_spec_logg",
    "SPEC_FEH": "fits_spec_feh",
    "SPEC_EW": "fits_spec_ew",
    "SPEC_FLUX": "fits_spec_flux",
    "SPEC_CONT": "fits_spec_cont",
    "SPEC_DEPTH": "fits_spec_depth",
    "SPEC_FWHM": "fits_spec_fwhm",
    "SPEC_RES": "fits_spec_res",
    "SPEC_LAMBDA": "fits_spec_lambda",
    "SPEC_LMIN": "fits_spec_lmin",
    "SPEC_LMAX": "fits_spec_lmax",
    "SPEC_INST": "fits_spec_inst",
    "SPEC_MODE": "fits_spec_mode",
    "SPEC_FIBER": "fits_spec_fiber",
    "SPEC_FIBERID": "fits_spec_fiberid",
    "SPEC_EXPTIME": "fits_spec_exptime",
    "SPEC_CALIB": "fits_spec_calib",
    "SPEC_FLAG": "fits_spec_flag",
    "SPEC_MASK": "fits_spec_mask",
}

# FITS Photometric Survey Keywords
FITS_PHOTO_SURVEY = {
    "PHOTO_ID": "fits_photo_id",
    "PHOTO_RA": "fits_photo_ra",
    "PHOTO_DEC": "fits_photo_dec",
    "PHOTO_ERR": "fits_photo_err",
    "PHOTO_OBJ": "fits_photo_obj",
    "PHOTO_TYPE": "fits_photo_type",
    "PHOTO_PROB": "fits_photo_prob",
    "PHOTO_Z": "fits_photo_z",
    "PHOTO_Z_ERR": "fits_photo_z_err",
    "PHOTO_Z_QUAL": "fits_photo_z_qual",
    "PHOTO_BETA": "fits_photo_beta",
    "PHOTO_CHI2": "fits_photo_chi2",
    "PHOTO_EXT": "fits_photo_ext",
    "PHOTO_EXT_ERR": "fits_photo_ext_err",
    "PHOTO_STAR": "fits_photo_star",
    "PHOTO_GALAXY": "fits_photo_galaxy",
    "PHOTO_COMBINED": "fits_photo_combined",
    "PHOTO_ISOA": "fits_photo_isoa",
    "PHOTO_ISOB": "fits_photo_isob",
    "PHOTO_ISOtheta": "fits_photo_isotheta",
    "PHOTO_DEVA": "fits_photo_deva",
    "PHOTO_DEVB": "fits_photo_devb",
    "PHOTO_DEVtheta": "fits_photo_devtheta",
    "PHOTO_EXPA": "fits_photo_expa",
    "PHOTO_EXPB": "fits_photo_expb",
    "PHOTO_EXPtheta": "fits_photo_exptheta",
    "PHOTO_MODEL": "fits_photo_model",
    "PHOTO_NITER": "fits_photo_niter",
    "PHOTO_CM": "fits_photo_cm",
    "PHOTO_CM_ERR": "fits_photo_cm_err",
    "PHOTO_KRON": "fits_photo_kron",
    "PHOTO_KRON_R": "fits_photo_kron_r",
    "PHOTO_PETRO": "fits_photo_petro",
    "PHOTO_PETRO_R": "fits_photo_petro_r",
    "PHOTO_FLUX": "fits_photo_flux",
    "PHOTO_FLUXERR": "fits_photo_fluxerr",
    "PHOTO_MAG": "fits_photo_mag",
    "PHOTO_MAGERR": "fits_photo_magerr",
    "PHOTO_SATUR": "fits_photo_satur",
    "PHOTO_ARTIF": "fits_photo_artif",
    "PHOTO_BLENDED": "fits_photo_blended",
    "PHOTO_CHILD": "fits_photo_child",
}

# FITS All-Sky Survey Keywords
FITS_ALLSKY = {
    "SKY_AREA": "fits_sky_area",
    "SKY_LON": "fits_sky_lon",
    "SKY_LAT": "fits_sky_lat",
    "SKY_PIX": "fits_sky_pix",
    "SKY_NEST": "fits_sky_nest",
    "SKY_ORDER": "fits_sky_order",
    "SKY_RESOL": "fits_sky_resol",
    "SKY_COORD": "fits_sky_coord",
    "SKY_CSYS": "fits_sky_csys",
    "SKY_PROJ": "fits_sky_proj",
    "SKY_NPIX": "fits_sky_npix",
    "SKY_NSIDE": "fits_sky_nside",
    "SKY_INPIX": "fits_sky_inpix",
    "SKY_IPIX": "fits_sky_ipix",
    "SKY_FWHM": "fits_sky_fwhm",
    "SKY_DEPTH": "fits_sky_depth",
    "SKY_COVERAGE": "fits_sky_coverage",
    "SKY_STDDEV": "fits_sky_stddev",
    "SKY_MEAN": "fits_sky_mean",
    "SKY_MEDIAN": "fits_sky_median",
    "SKY_SKEWNESS": "fits_sky_skewness",
    "SKY_KURTOSIS": "fits_sky_kurtosis",
    "SKY_NSTAR": "fits_sky_nstar",
    "SKY_NGALAXY": "fits_sky_ngalaxy",
    "SKY_EBV": "fits_sky_ebv",
    "SKY_DUST": "fits_sky_dust",
    "SKY_HI": "fits_sky_hi",
    "SKY_CO": "fits_sky_co",
    "SKY_XRAY": "fits_sky_xray",
    "SKY_GAMMA": "fits_sky_gamma",
    "SKY_NEUTRINO": "fits_sky_neutrino",
    "SKY_GW": "fits_sky_gw",
}

# FITS Gravimetry/Magnetometry Keywords
FITS_GRAV_MAG = {
    "GRAV_TYPE": "fits_grav_type",
    "GRAV_MODEL": "fits_grav_model",
    "GRAV_DATE": "fits_grav_date",
    "GRAV_TIME": "fits_grav_time",
    "GRAV_LAT": "fits_grav_lat",
    "GRAV_LON": "fits_grav_lon",
    "GRAV_ALT": "fits_grav_alt",
    "GRAV_ABS": "fits_grav_abs",
    "GRAV_RES": "fits_grav_res",
    "GRAV_CORR": "fits_grav_corr",
    "GRAV_TIDE": "fits_grav_tide",
    "GRAV_ATM": "fits_grav_atm",
    "GRAV_OCE": "fits_grav_oce",
    "GRAV_POL": "fits_grav_pol",
    "GRAV_SW": "fits_grav_sw",
    "MAG_TYPE": "fits_mag_type",
    "MAG_MODEL": "fits_mag_model",
    "MAG_DATE": "fits_mag_date",
    "MAG_TIME": "fits_mag_time",
    "MAG_LAT": "fits_mag_lat",
    "MAG_LON": "fits_mag_lon",
    "MAG_ALT": "fits_mag_alt",
    "MAG_TOTAL": "fits_mag_total",
    "MAG_X": "fits_mag_x",
    "MAG_Y": "fits_mag_y",
    "MAG_Z": "fits_mag_z",
    "MAG_RES": "fits_mag_res",
    "MAG_DIFF": "fits_mag_diff",
    "MAG_DST": "fits_mag_dst",
    "MAG_KP": "fits_mag_kp",
    "MAG_AP": "fits_mag_ap",
}

# FITS Planetary Science Keywords
FITS_PLANETARY = {
    "PLANET_ID": "fits_planet_id",
    "PLANET_NAME": "fits_planet_name",
    "PLANET_TYPE": "fits_planet_type",
    "PLANET_MASS": "fits_planet_mass",
    "PLANET_RADIUS": "fits_planet_radius",
    "PLANET_DENSITY": "fits_planet_density",
    "PLANET_PERIOD": "fits_planet_period",
    "PLANET_SMA": "fits_planet_sma",
    "PLANET_ECCE": "fits_planet_eccen",
    "PLANET_INC": "fits_planet_inc",
    "PLANET_ARG": "fits_planet_arg",
    "PLANET_LON": "fits_planet_lon",
    "PLANET_LAT": "fits_planet_lat",
    "PLANET_ALT": "fits_planet_alt",
    "PLANET_TEMP": "fits_planet_temp",
    "PLANET_TEMP_EQ": "fits_planet_temp_eq",
    "STAR_NAME": "fits_star_name",
    "STAR_TYPE": "fits_star_type",
    "STAR_TEFF": "fits_star_teff",
    "STAR_LOGG": "fits_star_logg",
    "STAR_FEH": "fits_star_feh",
    "STAR_MASS": "fits_star_mass",
    "STAR_RADIUS": "fits_star_radius",
    "STAR_LUM": "fits_star_lum",
    "STAR_AGE": "fits_star_age",
    "STAR_ROT": "fits_star_rot",
    "STAR_ACTIVITY": "fits_star_activity",
    "STAR_METAL": "fits_star_metal",
    "TRANSIT_T0": "fits_transit_t0",
    "TRANSIT_PER": "fits_transit_per",
    "TRANSIT_DUR": "fits_transit_dur",
    "TRANSIT_DEPTH": "fits_transit_depth",
    "TRANSIT_RP": "fits_transit_rp",
    "TRANSIT_AR": "fits_transit_ar",
    "TRANSIT_INC": "fits_transit_inc",
    "TRANSIT_B": "fits_transit_b",
    "TRANSIT_ECHO": "fits_transit_echo",
    "TRANSIT_IMPACT": "fits_transit_impact",
    "TRANSIT_ZEN": "fits_transit_zen",
    "TRANSIT_N": "fits_transit_n",
    "TRANSIT_OBS": "fits_transit_obs",
    "TRANSIT_LOG": "fits_transit_log",
    "TRANSIT_RES": "fits_transit_res",
    "TRANSIT_CAD": "fits_transit_cad",
}

# FITS Stellar Physics Keywords
FITS_STELLAR = {
    "STELLAR_TYPE": "fits_stellar_type",
    "STELLAR_CLASS": "fits_stellar_class",
    "STELLAR_LUM": "fits_stellar_lum",
    "STELLAR_TEFF": "fits_stellar_teff",
    "STELLAR_LOGG": "fits_stellar_logg",
    "STELLAR_FEH": "fits_stellar_feh",
    "STELLAR_MASS": "fits_stellar_mass",
    "STELLAR_RADIUS": "fits_stellar_radius",
    "STELLAR_AGE": "fits_stellar_age",
    "STELLAR_ROT": "fits_stellar_rot",
    "STELLAR_VSINI": "fits_stellar_vsini",
    "STELLAR_GRAV": "fits_stellar_grav",
    "STELLAR_METAL": "fits_stellar_metal",
    "STELLAR_ALPHA": "fits_stellar_alpha",
    "STELLAR_CARBON": "fits_stellar_carbon",
    "STELLAR_NITROGEN": "fits_stellar_nitrogen",
    "STELLAR_OXYGEN": "fits_stellar_oxygen",
    "STELLAR_NEON": "fits_stellar_neon",
    "STELLAR_MAGNESIUM": "fits_stellar_magnesium",
    "STELLAR_SILICON": "fits_stellar_silicon",
    "STELLAR_SULFUR": "fits_stellar_sulfur",
    "STELLAR_CALCIUM": "fits_stellar_calcium",
    "STELLAR_IRON": "fits_stellar_iron",
    "STELLAR_NICKEL": "fits_stellar_nickel",
    "STELLAR_LITHIUM": "fits_stellar_lithium",
    "STELLAR_BERYLLIUM": "fits_stellar_beryllium",
    "STELLAR_BORON": "fits_stellar_boron",
    "STELLAR_DELTA": "fits_stellar_delta",
    "STELLAR_12C_13C": "fits_stellar_12c_13c",
    "STELLAR_RATIO": "fits_stellar_ratio",
    "STELLAR_ABUND": "fits_stellar_abund",
    "STELLAR_ABUND_ERR": "fits_stellar_abund_err",
}

# FITS Galaxy Cluster Keywords
FITS_CLUSTER = {
    "CLUSTER_NAME": "fits_cluster_name",
    "CLUSTER_RA": "fits_cluster_ra",
    "CLUSTER_DEC": "fits_cluster_dec",
    "CLUSTER_REDSHIFT": "fits_cluster_redshift",
    "CLUSTER_Z": "fits_cluster_z",
    "CLUSTER_Z_ERR": "fits_cluster_z_err",
    "CLUSTER_RICH": "fits_cluster_rich",
    "CLUSTER_RICHNESS": "fits_cluster_richness",
    "CLUSTER_LUM": "fits_cluster_lum",
    "CLUSTER_LUM_T": "fits_cluster_lum_t",
    "CLUSTER_MASS": "fits_cluster_mass",
    "CLUSTER_M500": "fits_cluster_m500",
    "CLUSTER_M200": "fits_cluster_m200",
    "CLUSTER_R500": "fits_cluster_r500",
    "CLUSTER_R200": "fits_cluster_r200",
    "CLUSTER_TEMP": "fits_cluster_temp",
    "CLUSTER_TEMP_ERR": "fits_cluster_temp_err",
    "CLUSTER_METAL": "fits_cluster_metal",
    "CLUSTER_METAL_ERR": "fits_cluster_metal_err",
    "CLUSTER_LOS_VEL": "fits_cluster_los_vel",
    "CLUSTER_VEL_DISP": "fits_cluster_vel_disp",
    "CLUSTER_VEL_DISP_ERR": "fits_cluster_vel_disp_err",
    "CLUSTER_BCG_RA": "fits_cluster_bcg_ra",
    "CLUSTER_BCG_DEC": "fits_cluster_bcg_dec",
    "CLUSTER_BCG_MAG": "fits_cluster_bcg_mag",
    "CLUSTER_BCG_Z": "fits_cluster_bcg_z",
    "CLUSTER_N_MEM": "fits_cluster_n_mem",
    "CLUSTER_MEM_Z": "fits_cluster_mem_z",
    "CLUSTER_FRACHALO": "fits_cluster_frachalo",
    "CLUSTER_AMBIG": "fits_cluster_ambig",
    "CLUSTER_ASPECT": "fits_cluster_aspect",
    "CLUSTER_ELLIP": "fits_cluster_ellip",
    "CLUSTER_PA": "fits_cluster_pa",
    "CLUSTER_OFFSET": "fits_cluster_offset",
    "CLUSTER_SIGNIFICANCE": "fits_cluster_significance",
    "CLUSTER_DET": "fits_cluster_det",
    "CLUSTER_CHI2": "fits_cluster_chi2",
    "CLUSTER_DOF": "fits_cluster_dof",
    "CLUSTER_REJECT": "fits_cluster_reject",
    "CLUSTER_BAD": "fits_cluster_bad",
}

# FITS Supernova Keywords
FITS_SN = {
    "SN_NAME": "fits_sn_name",
    "SN_TYPE": "fits_sn_type",
    "SN_RA": "fits_sn_ra",
    "SN_DEC": "fits_sn_dec",
    "SN_REDSHIFT": "fits_sn_redshift",
    "SN_HOST": "fits_sn_host",
    "SN_HOST_RA": "fits_sn_host_ra",
    "SN_HOST_DEC": "fits_sn_host_dec",
    "SN_HOST_OFF": "fits_sn_host_off",
    "SN_HOST_GAL": "fits_sn_host_gal",
    "SN_HOST_TYPE": "fits_sn_host_type",
    "SN_HOST_Z": "fits_sn_host_z",
    "SN_DISCOVERY": "fits_sn_discovery",
    "SN_DISCOVERY_DATE": "fits_sn_discovery_date",
    "SN_PEAK": "fits_sn_peak",
    "SN_PEAK_DATE": "fits_sn_peak_date",
    "SN_MAXMAG": "fits_sn_maxmag",
    "SN_MAXMAG_ERR": "fits_sn_maxmag_err",
    "SN_EPOCH": "fits_sn_epoch",
    "SN_MJD": "fits_sn_mjd",
    "SN_FLUX": "fits_sn_flux",
    "SN_FLUX_ERR": "fits_sn_flux_err",
    "SN_MAG": "fits_sn_mag",
    "SN_MAG_ERR": "fits_sn_mag_err",
    "SN_ABUND": "fits_sn_abund",
    "SN_VEL": "fits_sn_vel",
    "SN_VEL_ERR": "fits_sn_vel_err",
    "SN_DELTA": "fits_sn_delta",
    "SN_COLOR": "fits_sn_color",
    "SN_COLOR_ERR": "fits_sn_color_err",
    "SN_GR": "fits_sn_gr",
    "SN_GR_ERR": "fits_sn_gr_err",
    "SN_RI": "fits_sn_ri",
    "SN_RI_ERR": "fits_sn_ri_err",
    "SN_UB": "fits_sn_ub",
    "SN_UB_ERR": "fits_sn_ub_err",
    "SN_BV": "fits_sn_bv",
    "SN_BV_ERR": "fits_sn_bv_err",
    "SN_EXPTIME": "fits_sn_exptime",
    "SN_ZPT": "fits_sn_zpt",
    "SN_CADENCE": "fits_sn_cadence",
    "SN_SURVEY": "fits_sn_survey",
    "SN_DETSURVEY": "fits_sn_detsurvey",
    "SN_COMMENT": "fits_sn_comment",
}


def get_all_fits_keywords_extended() -> Dict[str, str]:
    """Return all extended FITS keyword mappings."""
    all_keywords = {}
    all_keywords.update(FITS_EXTENDED_WCS)
    all_keywords.update(FITS_SOLAR_SYSTEM)
    all_keywords.update(FITS_SURVEY)
    all_keywords.update(FITS_TIME_SERIES)
    all_keywords.update(FITS_HIGH_ENERGY)
    all_keywords.update(FITS_COSMOLOGY)
    all_keywords.update(FITS_OPTICAL_IR)
    all_keywords.update(FITS_RADIO_MM)
    all_keywords.update(FITS_GW)
    all_keywords.update(FITS_NEUTRINO)
    all_keywords.update(FITS_MULTI_MESSENGER)
    all_keywords.update(FITS_ML)
    all_keywords.update(FITS_PIPELINE)
    all_keywords.update(FITS_SPEC_SURVEY)
    all_keywords.update(FITS_PHOTO_SURVEY)
    all_keywords.update(FITS_ALLSKY)
    all_keywords.update(FITS_GRAV_MAG)
    all_keywords.update(FITS_PLANETARY)
    all_keywords.update(FITS_STELLAR)
    all_keywords.update(FITS_CLUSTER)
    all_keywords.update(FITS_SN)
    return all_keywords


def get_fits_complete_ultimate_field_count() -> int:
    """Return total number of FITS fields including extended."""
    base_count = len(get_all_fits_keywords())
    extended_count = len(get_all_fits_keywords_extended())
    return base_count + extended_count


def extract_fits_metadata(filepath: str) -> Dict[str, Any]:
    """Extract comprehensive FITS metadata from astronomy files.

    Args:
        filepath: Path to the FITS file

    Returns:
        Dictionary containing extracted FITS header metadata
    """
    result = {
        "mandatory_keywords": {},
        "reserved_keywords": {},
        "observation_info": {},
        "telescope_info": {},
        "world_coordinates": {},
        "extended_keywords": {},
        "all_headers": {},
        "fields_extracted": 0,
        "is_valid_fits": False
    }

    try:
        # Try to use astropy for FITS parsing
        try:
            from astropy.io import fits

            with fits.open(filepath) as hdul:
                result["is_valid_fits"] = True
                all_keywords = get_all_fits_keywords()

                # Extract metadata from all HDU headers
                for i, hdu in enumerate(hdul):
                    header = hdu.header
                    hdu_prefix = f"hdu_{i}_" if i > 0 else ""

                    for keyword, value in header.items():
                        if keyword and keyword != '' and not keyword.startswith('COMMENT') and not keyword.startswith('HISTORY'):
                            # Map FITS keyword to field name
                            field_name = all_keywords.get(keyword, f"{hdu_prefix}{keyword.lower()}")

                            # Categorize the keyword
                            if keyword in FITS_MANDATORY:
                                result["mandatory_keywords"][field_name] = str(value)[:200]
                            elif keyword in FITS_RESERVED:
                                result["reserved_keywords"][field_name] = str(value)[:200]
                            elif keyword in FITS_OBSERVATION or keyword in FITS_INSTRUMENT or keyword in FITS_TELESCOPE:
                                result["observation_info"][field_name] = str(value)[:200]
                            elif keyword.startswith(('CTYPE', 'CRVAL', 'CDELT', 'CRPIX', 'CROTA', 'CUNIT')):
                                result["world_coordinates"][field_name] = str(value)[:200]
                            else:
                                result["extended_keywords"][field_name] = str(value)[:200]

                            result["all_headers"][field_name] = str(value)[:200]

                # Get basic file info
                result["num_hdus"] = len(hdul)
                if len(hdul) > 0:
                    primary_header = hdul[0].header
                    if 'SIMPLE' in primary_header:
                        result["fits_standard"] = primary_header['SIMPLE']
                    if 'BITPIX' in primary_header:
                        result["bitpix"] = primary_header['BITPIX']
                    if 'NAXIS' in primary_header:
                        result["naxis"] = primary_header['NAXIS']

        except ImportError:
            result["error"] = "astropy library not available - limited FITS extraction"
            # Fallback: try basic file reading
            try:
                with open(filepath, 'rb') as f:
                    header = f.read(2880)  # FITS header is 2880 bytes
                    if b'SIMPLE' in header[:100]:
                        result["is_valid_fits"] = True
                        result["fits_standard"] = "detected"
            except:
                pass

        except Exception as e:
            result["error"] = f"FITS extraction failed: {str(e)[:200]}"

        # Count extracted fields
        total_fields = (
            len(result["mandatory_keywords"]) +
            len(result["reserved_keywords"]) +
            len(result["observation_info"]) +
            len(result["telescope_info"]) +
            len(result["world_coordinates"]) +
            len(result["extended_keywords"]) +
            len(result["all_headers"])
        )
        result["fields_extracted"] = total_fields

    except Exception as e:
        result["error"] = f"FITS metadata extraction failed: {str(e)[:200]}"

    return result
