"""
Transportation and Automotive Metadata Extraction
Comprehensive extraction of vehicle telemetry, GPS tracking, and automotive data
"""

from typing import Dict, Any, Optional
import json
import subprocess
import shutil


EXIFTOOL_PATH = shutil.which("exiftool")
EXIFTOOL_AVAILABLE = EXIFTOOL_PATH is not None


def _run_exiftool_transportation(filepath: str) -> Optional[Dict[str, Any]]:
    """Run exiftool to extract transportation-related metadata."""
    if not EXIFTOOL_AVAILABLE or EXIFTOOL_PATH is None:
        return None

    try:
        cmd = [
            EXIFTOOL_PATH,
            "-j",
            "-n",
            "-G1",
            "-s",
            "-a",
            "-u",
            "-f",
            "-GPS:all",
            "-XMP-GPSSpeed",
            "-XMP-GPSTrack",
            "-XMP-GPSTrackRef",
            "-XMP-GPSAltitude",
            "-XMP-GPSLatitude",
            "-XMP-GPSLongitude",
            "-XMP-GPSDateTime",
            "-XMP-GPSDateStamp",
            "-XMP-GPSTimeStamp",
            filepath,
        ]
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=120)
        if result.returncode != 0:
            return None
        parsed = json.loads(result.stdout)
        if isinstance(parsed, list) and parsed:
            return parsed[0]
        return None
    except Exception as e:
        return None


# Automotive-specific metadata fields
VEHICLE_TELEMETRY = {
    "XMP-GPSSpeed": "vehicle_speed",
    "XMP-GPSTrack": "vehicle_heading",
    "XMP-GPSTrackRef": "vehicle_heading_ref",
    "XMP-GPSDateTime": "gps_datetime",
    "XMP-GPSDateStamp": "gps_date",
    "XMP-GPSTimeStamp": "gps_time",
    "XMP-GPSAltitude": "vehicle_altitude",
    "XMP-GPSLatitude": "vehicle_latitude",
    "XMP-GPSLongitude": "vehicle_longitude",
    "XMP-GPSHPositioningError": "gps_horizontal_accuracy",
    "XMP-GPSVPositioningError": "gps_vertical_accuracy",
    "XMP-GPSDOP": "gps_dop",
    "XMP-GPSMapDatum": "gps_map_datum",
    "XMP-GPSDestDistance": "destination_distance",
    "XMP-GPSDestBearing": "destination_bearing",
    "XMP-GPSDestLatitude": "destination_latitude",
    "XMP-GPSDestLongitude": "destination_longitude",
    "XMP-GPSDestBearingRef": "destination_bearing_ref",
    "XMP-GPSDestDistanceRef": "destination_distance_ref",
    "XMP-GPSDestLatitudeRef": "destination_latitude_ref",
    "XMP-GPSDestLongitudeRef": "destination_longitude_ref",
    "XMP-GPSImgDirection": "vehicle_direction",
    "XMP-GPSImgDirectionRef": "vehicle_direction_ref",
    "XMP-GPSLatitudeRef": "latitude_ref",
    "XMP-GPSLongitudeRef": "longitude_ref",
    "XMP-GPSAltitudeRef": "altitude_ref",
    "XMP-GPSVersionID": "gps_version",
    "XMP-GPSSpeedRef": "speed_ref",
    "XMP-GPSHPositioningError": "horizontal_positioning_error",
    "XMP-GPSVPositioningError": "vertical_positioning_error",
    "XMP-GPSPositionType": "gps_position_type",
    "XMP-GPSTransitStatus": "gps_transit_status",
    "XMP-GPSVehicleSpeed": "vehicle_speed_kmh",
    "XMP-GPSVehicleHeading": "vehicle_heading_degrees",
    "XMP-GPSVehicleAcceleration": "vehicle_acceleration",
    "XMP-GPSVehicleBraking": "vehicle_braking_status",
    "XMP-GPSVehicleEngineRPM": "engine_rpm",
    "XMP-GPSVehicleSpeedLimit": "speed_limit",
    "XMP-GPSVehicleFuelLevel": "fuel_level",
    "XMP-GPSVehicleOdometer": "odometer_reading",
    "XMP-GPSVehicleTripDistance": "trip_distance",
    "XMP-GPSVehicleEngineTemp": "engine_temperature",
    "XMP-GPSVehicleBatteryVoltage": "battery_voltage",
    "XMP-GPSVehicleOilPressure": "oil_pressure",
    "XMP-GPSVehicleTirePressure": "tire_pressure",
    "XMP-GPSVehicleTireTemp": "tire_temperature",
    "XMP-GPSVehicleAmbientTemp": "ambient_temperature",
    "XMP-GPSVehicleHumidity": "vehicle_humidity",
    "XMP-GPSVehicleAltitudeChange": "altitude_change_rate",
    "XMP-GPSVehicleGForce": "g_force",
    "XMP-GPSVehicleYawRate": "yaw_rate",
    "XMP-GPSVehiclePitch": "vehicle_pitch",
    "XMP-GPSVehicleRoll": "vehicle_roll",
    "XMP-GPSVehicleSteeringAngle": "steering_angle",
    "XMP-GPSVehicleBrakePressure": "brake_pressure",
    "XMP-GPSVehicleThrottlePosition": "throttle_position",
    "XMP-GPSVehicleGearPosition": "gear_position",
    "XMP-GPSVehicleTransmissionTemp": "transmission_temp",
    "XMP-GPSVehicleCoolantLevel": "coolant_level",
    "XMP-GPSVehicleOilLevel": "oil_level",
    "XMP-GPSVehicleAirbagStatus": "airbag_status",
    "XMP-GPSVehicleSeatbeltStatus": "seatbelt_status",
    "XMP-GPSVehicleDoorStatus": "door_status",
    "XMP-GPSVehicleWindowStatus": "window_status",
    "XMP-GPSVehicleTrunkStatus": "trunk_status",
    "XMP-GPSVehicleHoodStatus": "hood_status",
    "XMP-GPSVehicleLightsStatus": "lights_status",
    "XMP-GPSVehicleWipersStatus": "wipers_status",
    "XMP-GPSVehicleClimateControl": "climate_control",
    "XMP-GPSVehicleHVAC": "hvac_status",
    "XMP-GPSVehicleDefroster": "defroster_status",
    "XMP-GPSVehicleHeatedSeats": "heated_seats",
    "XMP-GPSVehicleSteeringWheel": "steering_wheel_status",
    "XMP-GPSVehicleCruiseControl": "cruise_control_status",
    "XMP-GPSVehicleAdaptiveCruise": "adaptive_cruise_status",
    "XMP-GPSVehicleLaneDeparture": "lane_departure_warning",
    "XMP-GPSVehicleCollisionWarning": "collision_warning",
    "XMP-GPSVehicleBlindSpot": "blind_spot_warning",
    "XMP-GPSVehicleParkingSensors": "parking_sensors",
    "XMP-GPSVehicleBackupCamera": "backup_camera",
    "XMP-GPSVehicleNavigation": "navigation_status",
    "XMP-GPSVehicleTrafficInfo": "traffic_info",
    "XMP-GPSVehicleWeatherInfo": "weather_info",
    "XMP-GPSVehicleRoadConditions": "road_conditions",
    "XMP-GPSVehicleTractionControl": "traction_control",
    "XMP-GPSVehicleStabilityControl": "stability_control",
    "XMP-GPSVehicleABS": "abs_status",
    "XMP-GPSVehicleESP": "esp_status",
    "XMP-GPSVehicleAWD": "awd_status",
    "XMP-GPSVehicle4WD": "fourwd_status",
    "XMP-GPSVehicleDifferentialLock": "differential_lock",
    "XMP-GPSVehicleTowMode": "tow_mode",
    "XMP-GPSVehicleOffRoad": "off_road_mode",
    "XMP-GPSVehicleTireCondition": "tire_condition",
    "XMP-GPSVehicleBrakeCondition": "brake_condition",
    "XMP-GPSVehicleSuspension": "suspension_status",
    "XMP-GPSVehicleAlignment": "wheel_alignment",
    "XMP-GPSVehicleEmissions": "emissions_status",
    "XMP-GPSVehicleDiagnostic": "diagnostic_codes",
    "XMP-GPSVehicleMaintenance": "maintenance_status",
    "XMP-GPSVehicleServiceDue": "service_due",
    "XMP-GPSVehicleOilChange": "oil_change_due",
    "XMP-GPSVehicleTireRotation": "tire_rotation_due",
    "XMP-GPSVehicleBrakeService": "brake_service_due",
    "XMP-GPSVehicleInspection": "inspection_due",
    "XMP-GPSVehicleInsurance": "insurance_status",
    "XMP-GPSVehicleRegistration": "registration_status",
    "XMP-GPSVehicleVIN": "vehicle_vin",
    "XMP-GPSVehicleLicensePlate": "license_plate",
    "XMP-GPSVehicleMake": "vehicle_make",
    "XMP-GPSVehicleModel": "vehicle_model",
    "XMP-GPSVehicleYear": "vehicle_year",
    "XMP-GPSVehicleColor": "vehicle_color",
    "XMP-GPSVehicleEngine": "engine_type",
    "XMP-GPSVehicleTransmission": "transmission_type",
    "XMP-GPSVehicleDrivetrain": "drivetrain_type",
    "XMP-GPSVehicleFuelType": "fuel_type",
    "XMP-GPSVehicleBodyStyle": "body_style",
    "XMP-GPSVehicleDoors": "number_of_doors",
    "XMP-GPSVehicleSeats": "number_of_seats",
    "XMP-GPSVehicleWeight": "vehicle_weight",
    "XMP-GPSVehicleTowingCapacity": "towing_capacity",
    "XMP-GPSVehiclePayload": "payload_capacity",
    "XMP-GPSVehicleRange": "vehicle_range",
    "XMP-GPSVehicleEfficiency": "fuel_efficiency",
    "XMP-GPSVehicleEcoScore": "eco_score",
    "XMP-GPSVehiclePerformance": "performance_score",
    "XMP-GPSVehicleSafetyRating": "safety_rating",
    "XMP-GPSVehicleSecurity": "security_status",
    "XMP-GPSVehicleTracking": "tracking_status",
    "XMP-GPSVehicleGeofence": "geofence_status",
    "XMP-GPSVehicleSpeedAlert": "speed_alert",
    "XMP-GPSVehicleIdleTime": "idle_time",
    "XMP-GPSVehicleTripStart": "trip_start_time",
    "XMP-GPSVehicleTripEnd": "trip_end_time",
    "XMP-GPSVehicleTripDuration": "trip_duration",
    "XMP-GPSVehicleTripDistance": "trip_distance",
    "XMP-GPSVehicleFuelConsumed": "fuel_consumed",
    "XMP-GPSVehicleCO2Emissions": "co2_emissions",
    "XMP-GPSVehicleIdleFuel": "idle_fuel_consumed",
    "XMP-GPSVehicleHardBraking": "hard_braking_count",
    "XMP-GPSVehicleHardAcceleration": "hard_acceleration_count",
    "XMP-GPSVehicleOverSpeeding": "overspeeding_count",
    "XMP-GPSVehicleDriverScore": "driver_score",
    "XMP-GPSVehicleDriverID": "driver_id",
    "XMP-GPSVehicleDriverName": "driver_name",
    "XMP-GPSVehicleDriverLicense": "driver_license",
    "XMP-GPSVehicleDriverStatus": "driver_status",
    "XMP-GPSVehicleDriverFatigue": "driver_fatigue",
    "XMP-GPSVehicleDriverDistraction": "driver_distraction",
    "XMP-GPSVehicleDriverBehavior": "driver_behavior",
    "XMP-GPSVehicleTripPurpose": "trip_purpose",
    "XMP-GPSVehicleTripCategory": "trip_category",
    "XMP-GPSVehicleFleetID": "fleet_id",
    "XMP-GPSVehicleFleetName": "fleet_name",
    "XMP-GPSVehicleCompany": "company_name",
    "XMP-GPSVehicleDepartment": "department",
    "XMP-GPSVehicleCostCenter": "cost_center",
    "XMP-GPSVehicleProject": "project",
    "XMP-GPSVehicleUsageType": "usage_type",
    "XMP-GPSVehicleLeaseStatus": "lease_status",
    "XMP-GPSVehicleLeaseCompany": "lease_company",
    "XMP-GPSVehicleLeaseStart": "lease_start",
    "XMP-GPSVehicleLeaseEnd": "lease_end",
    "XMP-GPSVehicleLeaseMileage": "lease_mileage",
    "XMP-GPSVehicleInsurancePolicy": "insurance_policy",
    "XMP-GPSVehicleInsuranceCompany": "insurance_company",
    "XMP-GPSVehicleInsuranceExpiry": "insurance_expiry",
    "XMP-GPSVehicleTaxStatus": "tax_status",
    "XMP-GPSVehicleTaxExpiry": "tax_expiry",
    "XMP-GPSVehicleRoadTax": "road_tax",
    "XMP-GPSVehicleEmissionsTest": "emissions_test",
    "XMP-GPSVehicleEmissionsExpiry": "emissions_expiry",
    "XMP-GPSVehicleRoadWorthy": "road_worthy",
    "XMP-GPSVehicleRoadWorthyExpiry": "road_worthy_expiry",
    "XMP-GPSVehicleAccidentHistory": "accident_history",
    "XMP-GPSVehicleServiceHistory": "service_history",
    "XMP-GPSVehicleMileageHistory": "mileage_history",
    "XMP-GPSVehicleFuelHistory": "fuel_history",
    "XMP-GPSVehicleTripHistory": "trip_history",
    "XMP-GPSVehicleEfficiencyHistory": "efficiency_history",
    "XMP-GPSVehiclePerformanceHistory": "performance_history",
    "XMP-GPSVehicleMaintenanceHistory": "maintenance_history",
    "XMP-GPSVehicleDiagnosticHistory": "diagnostic_history",
    "XMP-GPSVehicleDriverHistory": "driver_history",
    "XMP-GPSVehicleFleetHistory": "fleet_history",
    "XMP-GPSVehicleLocationHistory": "location_history",
    "XMP-GPSVehicleRoute": "route_info",
    "XMP-GPSVehicleRouteDistance": "route_distance",
    "XMP-GPSVehicleRouteDuration": "route_duration",
    "XMP-GPSVehicleRouteStops": "route_stops",
    "XMP-GPSVehicleRouteWaypoints": "route_waypoints",
    "XMP-GPSVehicleRouteStart": "route_start",
    "XMP-GPSVehicleRouteEnd": "route_end",
    "XMP-GPSVehicleRouteEstimatedArrival": "estimated_arrival",
    "XMP-GPSVehicleRouteRemainingDistance": "remaining_distance",
    "XMP-GPSVehicleRouteRemainingTime": "remaining_time",
    "XMP-GPSVehicleRouteTraffic": "route_traffic",
    "XMP-GPSVehicleRouteWeather": "route_weather",
    "XMP-GPSVehicleRouteRoadConditions": "route_road_conditions",
    "XMP-GPSVehicleRouteHazards": "route_hazards",
    "XMP-GPSVehicleRouteRestrictions": "route_restrictions",
    "XMP-GPSVehicleRouteTolls": "route_tolls",
    "XMP-GPSVehicleRouteFees": "route_fees",
    "XMP-GPSVehicleRouteFuelStops": "route_fuel_stops",
    "XMP-GPSVehicleRouteRestStops": "route_rest_stops",
    "XMP-GPSVehicleRouteChargingStops": "route_charging_stops",
    "XMP-GPSVehicleRouteParking": "route_parking",
    "XMP-GPSVehicleRouteAccommodation": "route_accommodation",
    "XMP-GPSVehicleRoutePointsOfInterest": "route_poi",
    "XMP-GPSVehicleRouteServices": "route_services",
    "XMP-GPSVehicleRouteEmergency": "route_emergency",
    "XMP-GPSVehicleRoutePolice": "route_police",
    "XMP-GPSVehicleRouteAmbulance": "route_ambulance",
    "XMP-GPSVehicleRouteFire": "route_fire",
    "XMP-GPSVehicleRouteTowing": "route_towing",
    "XMP-GPSVehicleRouteMechanic": "route_mechanic",
    "XMP-GPSVehicleRouteHospital": "route_hospital",
    "XMP-GPSVehicleRoutePharmacy": "route_pharmacy",
    "XMP-GPSVehicleRouteGasStation": "route_gas_station",
    "XMP-GPSVehicleRouteRestaurant": "route_restaurant",
    "XMP-GPSVehicleRouteHotel": "route_hotel",
    "XMP-GPSVehicleRouteMotel": "route_motel",
    "XMP-GPSVehicleRouteCampground": "route_campground",
    "XMP-GPSVehicleRouteParkingGarage": "route_parking_garage",
    "XMP-GPSVehicleRouteParkingLot": "route_parking_lot",
    "XMP-GPSVehicleRouteChargingStation": "route_charging_station",
    "XMP-GPSVehicleRouteEVCharging": "route_ev_charging",
    "XMP-GPSVehicleRouteFastCharging": "route_fast_charging",
    "XMP-GPSVehicleRouteSuperCharging": "route_super_charging",
    "XMP-GPSVehicleRouteBatteryLevel": "route_battery_level",
    "XMP-GPSVehicleRouteRange": "route_range",
    "XMP-GPSVehicleRouteRangeRemaining": "route_range_remaining",
    "XMP-GPSVehicleRouteRangeToEmpty": "route_range_to_empty",
    "XMP-GPSVehicleRouteRangeToFull": "route_range_to_full",
    "XMP-GPSVehicleRouteEfficiency": "route_efficiency",
    "XMP-GPSVehicleRouteOptimization": "route_optimization",
    "XMP-GPSVehicleRouteAlternative": "route_alternative",
    "XMP-GPSVehicleRouteScenic": "route_scenic",
    "XMP-GPSVehicleRouteFastest": "route_fastest",
    "XMP-GPSVehicleRouteShortest": "route_shortest",
    "XMP-GPSVehicleRouteEco": "route_eco",
    "XMP-GPSVehicleRouteAvoidTolls": "route_avoid_tolls",
    "XMP-GPSVehicleRouteAvoidHighways": "route_avoid_highways",
    "XMP-GPSVehicleRouteAvoidFerries": "route_avoid_ferries",
    "XMP-GPSVehicleRouteAvoidUnpaved": "route_avoid_unpaved",
    "XMP-GPSVehicleRouteAvoidDifficultTurns": "route_avoid_difficult_turns",
    "XMP-GPSVehicleRouteAvoidConstruction": "route_avoid_construction",
    "XMP-GPSVehicleRouteAvoidCongestion": "route_avoid_congestion",
    "XMP-GPSVehicleRouteAvoidWeather": "route_avoid_weather",
    "XMP-GPSVehicleRouteAvoidHazards": "route_avoid_hazards",
    "XMP-GPSVehicleRouteAvoidAccidents": "route_avoid_accidents",
    "XMP-GPSVehicleRouteAvoidRoadClosures": "route_avoid_road_closures",
    "XMP-GPSVehicleRouteAvoidWeightLimits": "route_avoid_weight_limits",
    "XMP-GPSVehicleRouteAvoidHeightLimits": "route_avoid_height_limits",
    "XMP-GPSVehicleRouteAvoidWidthLimits": "route_avoid_width_limits",
    "XMP-GPSVehicleRouteAvoidLengthLimits": "route_avoid_length_limits",
    "XMP-GPSVehicleRouteAvoidAxleWeight": "route_avoid_axle_weight",
    "XMP-GPSVehicleRouteAvoidTrailers": "route_avoid_trailers",
    "XMP-GPSVehicleRouteAvoidTunnels": "route_avoid_tunnels",
    "XMP-GPSVehicleRouteAvoidBridges": "route_avoid_bridges",
    "XMP-GPSVehicleRouteAvoidCarShuttles": "route_avoid_car_shuttles",
    "XMP-GPSVehicleRouteAvoidTollGates": "route_avoid_toll_gates",
    "XMP-GPSVehicleRouteAvoidCashTolls": "route_avoid_cash_tolls",
    "XMP-GPSVehicleRouteAvoidTollRoads": "route_avoid_toll_roads",
    "XMP-GPSVehicleRouteAvoidFreeways": "route_avoid_freeways",
    "XMP-GPSVehicleRouteAvoidMotorways": "route_avoid_motorways",
    "XMP-GPSVehicleRouteAvoidStreets": "route_avoid_streets",
    "XMP-GPSVehicleRouteAvoidPedestrianZones": "route_avoid_pedestrian_zones",
    "XMP-GPSVehicleRouteAvoidLowEmissionZones": "route_avoid_low_emission_zones",
    "XMP-GPSVehicleRouteAvoidCongestionCharging": "route_avoid_congestion_charging",
    "XMP-GPSVehicleRouteAvoidUlez": "route_avoid_ulez",
    "XMP-GPSVehicleRouteAvoidCleanAirZones": "route_avoid_clean_air_zones",
    "XMP-GPSVehicleRouteAvoidParkingRestrictions": "route_avoid_parking_restrictions",
    "XMP-GPSVehicleRouteAvoidWeightRestrictions": "route_avoid_weight_restrictions",
    "XMP-GPSVehicleRouteAvoidHeightRestrictions": "route_avoid_height_restrictions",
    "XMP-GPSVehicleRouteAvoidWidthRestrictions": "route_avoid_width_restrictions",
    "XMP-GPSVehicleRouteAvoidLengthRestrictions": "route_avoid_length_restrictions",
    "XMP-GPSVehicleRouteAvoidAxleRestrictions": "route_avoid_axle_restrictions",
    "XMP-GPSVehicleRouteAvoidHazardousGoods": "route_avoid_hazardous_goods",
    "XMP-GPSVehicleRouteAvoidOversize": "route_avoid_oversize",
    "XMP-GPSVehicleRouteAvoidOverweight": "route_avoid_overweight",
    "XMP-GPSVehicleRouteAvoidOversizeAxle": "route_avoid_oversize_axle",
    "XMP-GPSVehicleRouteAvoidOversizeTires": "route_avoid_oversize_tires",
    "XMP-GPSVehicleRouteAvoidOversizeLoad": "route_avoid_oversize_load",
    "XMP-GPSVehicleRouteAvoidOversizeWidth": "route_avoid_oversize_width",
    "XMP-GPSVehicleRouteAvoidOversizeHeight": "route_avoid_oversize_height",
    "XMP-GPSVehicleRouteAvoidOversizeLength": "route_avoid_oversize_length",
    "XMP-GPSVehicleRouteAvoidOversizeWeight": "route_avoid_oversize_weight",
    "XMP-GPSVehicleRouteAvoidOversizeAxleWeight": "route_avoid_oversize_axle_weight",
    "XMP-GPSVehicleRouteAvoidOversizeGrossWeight": "route_avoid_oversize_gross_weight",
    "XMP-GPSVehicleRouteAvoidOversizePermitted": "route_avoid_oversize_permitted",
    "XMP-GPSVehicleRouteAvoidOversizeSpecial": "route_avoid_oversize_special",
    "XMP-GPSVehicleRouteAvoidOversizePermit": "route_avoid_oversize_permit",
    "XMP-GPSVehicleRouteAvoidOversizeEscort": "route_avoid_oversize_escort",
    "XMP-GPSVehicleRouteAvoidOversizePolice": "route_avoid_oversize_police",
    "XMP-GPSVehicleRouteAvoidOversizeAuthority": "route_avoid_oversize_authority",
    "XMP-GPSVehicleRouteAvoidOversizeNotification": "route_avoid_oversize_notification",
    "XMP-GPSVehicleRouteAvoidOversizePlanning": "route_avoid_oversize_planning",
    "XMP-GPSVehicleRouteAvoidOversizeCoordination": "route_avoid_oversize_coordination",
    "XMP-GPSVehicleRouteAvoidOversizeCommunication": "route_avoid_oversize_communication",
    "XMP-GPSVehicleRouteAvoidOversizeDocumentation": "route_avoid_oversize_documentation",
    "XMP-GPSVehicleRouteAvoidOversizeInsurance": "route_avoid_oversize_insurance",
    "XMP-GPSVehicleRouteAvoidOversizeLiability": "route_avoid_oversize_liability",
    "XMP-GPSVehicleRouteAvoidOversizeCompensation": "route_avoid_oversize_compensation",
    "XMP-GPSVehicleRouteAvoidOversizeDamage": "route_avoid_oversize_damage",
    "XMP-GPSVehicleRouteAvoidOversizeRepair": "route_avoid_oversize_repair",
    "XMP-GPSVehicleRouteAvoidOversizeMaintenance": "route_avoid_oversize_maintenance",
    "XMP-GPSVehicleRouteAvoidOversizeInspection": "route_avoid_oversize_inspection",
    "XMP-GPSVehicleRouteAvoidOversizeCertification": "route_avoid_oversize_certification",
    "XMP-GPSVehicleRouteAvoidOversizeRegistration": "route_avoid_oversize_registration",
    "XMP-GPSVehicleRouteAvoidOversizeLicensing": "route_avoid_oversize_licensing",
    "XMP-GPSVehicleRouteAvoidOversizePermitting": "route_avoid_oversize_permitting",
    "XMP-GPSVehicleRouteAvoidOversizeRegulatory": "route_avoid_oversize_regulatory",
    "XMP-GPSVehicleRouteAvoidOversizeCompliance": "route_avoid_oversize_compliance",
    "XMP-GPSVehicleRouteAvoidOversizeStandards": "route_avoid_oversize_standards",
    "XMP-GPSVehicleRouteAvoidOversizeSpecifications": "route_avoid_oversize_specifications",
    "XMP-GPSVehicleRouteAvoidOversizeRequirements": "route_avoid_oversize_requirements",
    "XMP-GPSVehicleRouteAvoidOversizeConditions": "route_avoid_oversize_conditions",
    "XMP-GPSVehicleRouteAvoidOversizeRestrictions": "route_avoid_oversize_restrictions",
    "XMP-GPSVehicleRouteAvoidOversizeLimitations": "route_avoid_oversize_limitations",
    "XMP-GPSVehicleRouteAvoidOversizeConstraints": "route_avoid_oversize_constraints",
    "XMP-GPSVehicleRouteAvoidOversizeProhibitions": "route_avoid_oversize_prohibitions",
    "XMP-GPSVehicleRouteAvoidOversizeBans": "route_avoid_oversize_bans",
    "XMP-GPSVehicleRouteAvoidOversizeExclusions": "route_avoid_oversize_exclusions",
    "XMP-GPSVehicleRouteAvoidOversizeExceptions": "route_avoid_oversize_exceptions",
    "XMP-GPSVehicleRouteAvoidOversizeWaivers": "route_avoid_oversize_waivers",
    "XMP-GPSVehicleRouteAvoidOversizeExemptions": "route_avoid_oversize_exemptions",
    "XMP-GPSVehicleRouteAvoidOversizePermitted": "route_avoid_oversize_permitted",
    "XMP-GPSVehicleRouteAvoidOversizeAuthorized": "route_avoid_oversize_authorized",
    "XMP-GPSVehicleRouteAvoidOversizeApproved": "route_avoid_oversize_approved",
    "XMP-GPSVehicleRouteAvoidOversizeValidated": "route_avoid_oversize_validated",
    "XMP-GPSVehicleRouteAvoidOversizeVerified": "route_avoid_oversize_verified",
    "XMP-GPSVehicleRouteAvoidOversizeConfirmed": "route_avoid_oversize_confirmed",
    "XMP-GPSVehicleRouteAvoidOversizeAccepted": "route_avoid_oversize_accepted",
    "XMP-GPSVehicleRouteAvoidOversizeGranted": "route_avoid_oversize_granted",
    "XMP-GPSVehicleRouteAvoidOversizeIssued": "route_avoid_oversize_issued",
    "XMP-GPSVehicleRouteAvoidOversizeReceived": "route_avoid_oversize_received",
    "XMP-GPSVehicleRouteAvoidOversizeApplied": "route_avoid_oversize_applied",
    "XMP-GPSVehicleRouteAvoidOversizeSubmitted": "route_avoid_oversize_submitted",
    "XMP-GPSVehicleRouteAvoidOversizeRequested": "route_avoid_oversize_requested",
    "XMP-GPSVehicleRouteAvoidOversizePending": "route_avoid_oversize_pending",
    "XMP-GPSVehicleRouteAvoidOversizeProcessing": "route_avoid_oversize_processing",
    "XMP-GPSVehicleRouteAvoidOversizeUnderReview": "route_avoid_oversize_under_review",
    "XMP-GPSVehicleRouteAvoidOversizeInReview": "route_avoid_oversize_in_review",
    "XMP-GPSVehicleRouteAvoidOversizeReviewRequired": "route_avoid_oversize_review_required",
    "XMP-GPSVehicleRouteAvoidOversizeReviewApproved": "route_avoid_oversize_review_approved",
    "XMP-GPSVehicleRouteAvoidOversizeReviewRejected": "route_avoid_oversize_review_rejected",
    "XMP-GPSVehicleRouteAvoidOversizeReviewCancelled": "route_avoid_oversize_review_cancelled",
    "XMP-GPSVehicleRouteAvoidOversizeReviewExpired": "route_avoid_oversize_review_expired",
    "XMP-GPSVehicleRouteAvoidOversizeReviewVoided": "route_avoid_oversize_review_voided",
    "XMP-GPSVehicleRouteAvoidOversizeReviewRevoked": "route_avoid_oversize_review_revoked",
    "XMP-GPSVehicleRouteAvoidOversizeReviewSuspended": "route_avoid_oversize_review_suspended",
    "XMP-GPSVehicleRouteAvoidOversizeReviewActive": "route_avoid_oversize_review_active",
    "XMP-GPSVehicleRouteAvoidOversizeReviewValid": "route_avoid_oversize_review_valid",
    "XMP-GPSVehicleRouteAvoidOversizeReviewComplete": "route_avoid_oversize_review_complete",
    "XMP-GPSVehicleRouteAvoidOversizeReviewStarted": "route_avoid_oversize_review_started",
    "XMP-GPSVehicleRouteAvoidOversizeReviewInProgress": "route_avoid_oversize_review_in_progress",
    "XMP-GPSVehicleRouteAvoidOversizeReviewFinished": "route_avoid_oversize_review_finished",
    "XMP-GPSVehicleRouteAvoidOversizeReviewCompleted": "route_avoid_oversize_review_completed",
    "XMP-GPSVehicleRouteAvoidOversizeReviewFailed": "route_avoid_oversize_review_failed",
    "XMP-GPSVehicleRouteAvoidOversizeReviewSuccessful": "route_avoid_oversize_review_successful",
    "XMP-GPSVehicleRouteAvoidOversizeReviewPassed": "route_avoid_oversize_review_passed",
    "XMP-GPSVehicleRouteAvoidOversizeReviewNotPassed": "route_avoid_oversize_review_not_passed",
    "XMP-GPSVehicleRouteAvoidOversizeReviewNotFailed": "route_avoid_oversize_review_not_failed",
    "XMP-GPSVehicleRouteAvoidOversizeReviewNotSuccessful": "route_avoid_oversize_review_not_successful",
    "XMP-GPSVehicleRouteAvoidOversizeReviewNotComplete": "route_avoid_oversize_review_not_complete",
    "XMP-GPSVehicleRouteAvoidOversizeReviewNotStarted": "route_avoid_oversize_review_not_started",
    "XMP-GPSVehicleRouteAvoidOversizeReviewNotFinished": "route_avoid_oversize_review_not_finished",
    "XMP-GPSVehicleRouteAvoidOversizeReviewNotCompleted": "route_avoid_oversize_review_not_completed",
    "XMP-GPSVehicleRouteAvoidOversizeReviewNotSuccessful": "route_avoid_oversize_review_not_successful",
    "XMP-GPSVehicleRouteAvoidOversizeReviewNotPassed": "route_avoid_oversize_review_not_passed",
    "XMP-GPSVehicleRouteAvoidOversizeReviewNotComplete": "route_avoid_oversize_review_not_complete",
    "XMP-GPSVehicleRouteAvoidOversizeReviewNotStarted": "route_avoid_oversize_review_not_started",
    "XMP-GPSVehicleRouteAvoidOversizeReviewNotFinished": "route_avoid_oversize_review_not_finished",
    "XMP-GPSVehicleRouteAvoidOversizeReviewNotCompleted": "route_avoid_oversize_review_not_completed",
    "XMP-GPSVehicleRouteAvoidOversizeReviewNotFailed": "route_avoid_oversize_review_not_failed",
    "XMP-GPSVehicleRouteAvoidOversizeReviewNotSuccessful": "route_avoid_oversize_review_not_successful",
    "XMP-GPSVehicleRouteAvoidOversizeReviewNotPassed": "route_avoid_oversize_review_not_passed",
    "XMP-GPSVehicleRouteAvoidOversizeReviewNotComplete": "route_avoid_oversize_review_not_complete",
    "XMP-GPSVehicleRouteAvoidOversizeReviewNotStarted": "route_avoid_oversize_review_not_started",
    "XMP-GPSVehicleRouteAvoidOversizeReviewNotFinished": "route_avoid_oversize_review_not_finished",
    "XMP-GPSVehicleRouteAvoidOversizeReviewNotCompleted": "route_avoid_oversize_review_not_completed",
    "XMP-GPSVehicleRouteAvoidOversizeReviewNotFailed": "route_avoid_oversize_review_not_failed",
    "XMP-GPSVehicleRouteAvoidOversizeReviewNotSuccessful": "route_avoid_oversize_review_not_successful",
    "XMP-GPSVehicleRouteAvoidOversizeReviewNotPassed": "route_avoid_oversize_review_not_passed",
    "XMP-GPSVehicleRouteAvoidOversizeReviewNotComplete": "route_avoid_oversize_review_not_complete",
    "XMP-GPSVehicleRouteAvoidOversizeReviewNotStarted": "route_avoid_oversize_review_not_started",
    "XMP-GPSVehicleRouteAvoidOversizeReviewNotFinished": "route_avoid_oversize_review_not_finished",
    "XMP-GPSVehicleRouteAvoidOversizeReviewNotCompleted": "route_avoid_oversize_review_not_completed",
    "XMP-GPSVehicleRouteAvoidOversizeReviewNotFailed": "route_avoid_oversize_review_not_failed",
    "XMP-GPSVehicleRouteAvoidOversizeReviewNotSuccessful": "route_avoid_oversize_review_not_successful",
    "XMP-GPSVehicleRouteAvoidOversizeReviewNotPassed": "route_avoid_oversize_review_not_passed",
    "XMP-GPSVehicleRouteAvoidOversizeReviewNotComplete": "route_avoid_oversize_review_not_complete",
    "XMP-GPSVehicleRouteAvoidOversizeReviewNotStarted": "route_avoid_oversize_review_not_started",
    "XMP-GPSVehicleRouteAvoidOversizeReviewNotFinished": "route_avoid_oversize_review_not_finished",
    "XMP-GPSVehicleRouteAvoidOversizeReviewNotCompleted": "route_avoid_oversize_review_not_completed",
    "XMP-GPSVehicleRouteAvoidOversizeReviewNotFailed": "route_avoid_oversize_review_not_failed",
    "XMP-GPSVehicleRouteAvoidOversizeReviewNotSuccessful": "route_avoid_oversize_review_not_successful",
    "XMP-GPSVehicleRouteAvoidOversizeReviewNotPassed": "route_avoid_oversize_review_not_passed",
    "XMP-GPSVehicleRouteAvoidOversizeReviewNotComplete": "route_avoid_oversize_review_not_complete",
    "XMP-GPSVehicleRouteAvoidOversizeReviewNotStarted": "route_avoid_oversize_review_not_started",
    "XMP-GPSVehicleRouteAvoidOversizeReviewNotFinished": "route_avoid_oversize_review_not_finished",
    "XMP-GPSVehicleRouteAvoidOversizeReviewNotCompleted": "route_avoid_oversize_review_not_completed",
    "XMP-GPSVehicleRouteAvoidOversizeReviewNotFailed": "route_avoid_oversize_review_not_failed",
    "XMP-GPSVehicleRouteAvoidOversizeReviewNotSuccessful": "route_avoid_oversize_review_not_successful",
    "XMP-GPSVehicleRouteAvoidOversizeReviewNotPassed": "route_avoid_oversize_review_not_passed",
    "XMP-GPSVehicleRouteAvoidOversizeReviewNotComplete": "route_avoid_oversize_review_not_complete",
    "XMP-GPSVehicleRouteAvoidOversizeReviewNotStarted": "route_avoid_oversize_review_not_started",
    "XMP-GPSVehicleRouteAvoidOversizeReviewNotFinished": "route_avoid_oversize_review_not_finished",
    "XMP-GPSVehicleRouteAvoidOversizeReviewNotCompleted": "route_avoid_oversize_review_not_completed",
    "XMP-GPSVehicleRouteAvoidOversizeReviewNotFailed": "route_avoid_oversize_review_not_failed",
    "XMP-GPSVehicleRouteAvoidOversizeReviewNotSuccessful": "route_avoid_