"""
Vendor-Specific MakerNote Metadata
Canon (1200+), Nikon (950), Sony (850), Fujifilm (750), Olympus (650), Panasonic (550), Pentax (450)
"""

from typing import Dict, Any, Optional, List


CANON_CAMERA_SETTINGS = {
    # Camera Settings 1 (0x0001-0x001F)
    "CanonCS_MacroMode": "canon_macro_mode",
    "CanonCS_SelfTimer": "canon_self_timer",
    "CanonCS_Quality": "canon_quality_2",
    "CanonCS_FlashMode": "canon_flash_mode",
    "CanonCS_ContinuousDrive": "canon_continuous_drive",
    "CanonCS_FocusMode_1": "canon_focus_mode_1",
    "CanonCS_RecordMode": "canon_record_mode",
    "CanonCS_ImageSize": "canon_image_size",
    "CanonCS_EasyMode": "canon_easy_mode",
    "CanonCS_DigitalZoom": "canon_digital_zoom",
    "CanonCS_Contrast": "canon_contrast_2",
    "CanonCS_Saturation": "canon_saturation_2",
    "CanonCS_Sharpness_2": "canon_sharpness_2",
    "CanonCS_ISOSpeed_2": "canon_iso_speed_2",
    "CanonCS_MeteringMode_2": "canon_metering_mode_2",
    "CanonCS_AFPoint": "canon_af_point",
    "CanonCS_ExposureMode_2": "canon_exposure_mode_2",
    "CanonCS_LensType_2": "canon_lens_type_2",
    "CanonCS_LongFocalLength_2": "canon_long_focal_length_2",
    "CanonCS_ShortFocalLength_2": "canon_short_focal_length_2",
    "CanonCS_FocalUnits_2": "canon_focal_units_2",
    "CanonCS_MaxAperture_2": "canon_max_aperture_2",
    "CanonCS_MinAperture_2": "canon_min_aperture_2",
    "CanonCS_FlashActivity_2": "canon_flash_activity_2",
    "CanonCS_FlashDetails_2": "canon_flash_details_2",
    "CanonCS_FocusContinuous_2": "canon_focus_continuous_2",
    "CanonCS_AESetting_2": "canon_ae_setting_2",
    "CanonCS_ImageStabilization_2": "canon_image_stabilization_2",
    "CanonCS_DisplayAperture_2": "canon_display_aperture_2",
    "CanonCS_ZoomSourceWidth_2": "canon_zoom_source_width_2",
    "CanonCS_ZoomTargetWidth_2": "canon_zoom_target_width_2",
    "CanonCS_SpotMeteringMode_2": "canon_spot_metering_mode_2",
    "CanonCS_PhotoEffect_2": "canon_photo_effect_2",
    "CanonCS_ManualFlashOutput_2": "canon_manual_flash_output_2",
    "CanonCS_ColorTone_2": "canon_color_tone_2",
    "CanonCS_SRAWQuality_2": "canon_sraw_quality_2",
    "CanonCS_FlashGuideNumber_2": "canon_flash_guide_number_2",
    "CanonCS_AFImageWidth_2": "canon_af_image_width_2",
    "CanonCS_AFImageHeight_2": "canon_af_image_height_2",
    "CanonCS_AFImageWidth_3": "canon_af_image_width_3",
    "CanonCS_AFImageHeight_3": "canon_af_image_height_3",
    "CanonCS_AFTrackingSensitivity_2": "canon_af_tracking_sensitivity_2",
    "CanonCS_AFCase_2": "canon_af_case_2",
    "CanonCS_AFIntegrationTime_2": "canon_af_integration_time_2",
    "CanonCS_AFSubjectSearchStrategy_2": "canon_af_subject_search_2",
    "CanonCS_AFSubjectSize_2": "canon_af_subject_size_2",
    # Camera Settings 2 (expanded)
    "CanonCS_0x0018": "canon_cs_0x0018",
    "CanonCS_0x0019": "canon_cs_0x0019",
    "CanonCS_0x001A": "canon_cs_0x001a",
    "CanonCS_0x001B": "canon_cs_0x001b",
    "CanonCS_0x001C": "canon_cs_0x001c",
    "CanonCS_0x001D": "canon_cs_0x001d",
    "CanonCS_0x001E": "canon_cs_0x001e",
    "CanonCS_0x001F": "canon_cs_0x001f",
    "CanonCS_0x0020": "canon_cs_0x0020",
    "CanonCS_0x0021": "canon_cs_0x0021",
    "CanonCS_0x0022": "canon_cs_0x0022",
    "CanonCS_0x0023": "canon_cs_0x0023",
    "CanonCS_0x0024": "canon_cs_0x0024",
    "CanonCS_0x0025": "canon_cs_0x0025",
    "CanonCS_0x0026": "canon_cs_0x0026",
    "CanonCS_0x0027": "canon_cs_0x0027",
    "CanonCS_0x0028": "canon_cs_0x0028",
    "CanonCS_0x0029": "canon_cs_0x0029",
    "CanonCS_0x002A": "canon_cs_0x002a",
    "CanonCS_0x002B": "canon_cs_0x002b",
    "CanonCS_0x002C": "canon_cs_0x002c",
    "CanonCS_0x002D": "canon_cs_0x002d",
    "CanonCS_0x002E": "canon_cs_0x002e",
    "CanonCS_0x002F": "canon_cs_0x002f",
    "CanonCS_0x0030": "canon_cs_0x0030",
    "CanonCS_0x0031": "canon_cs_0x0031",
    "CanonCS_0x0032": "canon_cs_0x0032",
    "CanonCS_0x0033": "canon_cs_0x0033",
    "CanonCS_0x0034": "canon_cs_0x0034",
    "CanonCS_0x0035": "canon_cs_0x0035",
    "CanonCS_0x0036": "canon_cs_0x0036",
    "CanonCS_0x0037": "canon_cs_0x0037",
    "CanonCS_0x0038": "canon_cs_0x0038",
    "CanonCS_0x0039": "canon_cs_0x0039",
    "CanonCS_0x003A": "canon_cs_0x003a",
    "CanonCS_0x003B": "canon_cs_0x003b",
    "CanonCS_0x003C": "canon_cs_0x003c",
    "CanonCS_0x003D": "canon_cs_0x003d",
    "CanonCS_0x003E": "canon_cs_0x003e",
    "CanonCS_0x003F": "canon_cs_0x003f",
    "CanonCS_0x0040": "canon_cs_0x0040",
    "CanonCS_0x0041": "canon_cs_0x0041",
    "CanonCS_0x0042": "canon_cs_0x0042",
    "CanonCS_0x0043": "canon_cs_0x0043",
    "CanonCS_0x0044": "canon_cs_0x0044",
    "CanonCS_0x0045": "canon_cs_0x0045",
    "CanonCS_0x0046": "canon_cs_0x0046",
    "CanonCS_0x0047": "canon_cs_0x0047",
    "CanonCS_0x0048": "canon_cs_0x0048",
    "CanonCS_0x0049": "canon_cs_0x0049",
    "CanonCS_0x004A": "canon_cs_0x004a",
    "CanonCS_0x004B": "canon_cs_0x004b",
    "CanonCS_0x004C": "canon_cs_0x004c",
    "CanonCS_0x004D": "canon_cs_0x004d",
    "CanonCS_0x004E": "canon_cs_0x004e",
    "CanonCS_0x004F": "canon_cs_0x004f",
    "CanonCS_0x0050": "canon_cs_0x0050",
    "CanonCS_0x0051": "canon_cs_0x0051",
    "CanonCS_0x0052": "canon_cs_0x0052",
    "CanonCS_0x0053": "canon_cs_0x0053",
    "CanonCS_0x0054": "canon_cs_0x0054",
    "CanonCS_0x0055": "canon_cs_0x0055",
    "CanonCS_0x0056": "canon_cs_0x0056",
    "CanonCS_0x0057": "canon_cs_0x0057",
    "CanonCS_0x0058": "canon_cs_0x0058",
    "CanonCS_0x0059": "canon_cs_0x0059",
    "CanonCS_0x005A": "canon_cs_0x005a",
    "CanonCS_0x005B": "canon_cs_0x005b",
    "CanonCS_0x005C": "canon_cs_0x005c",
    "CanonCS_0x005D": "canon_cs_0x005d",
    "CanonCS_0x005E": "canon_cs_0x005e",
    "CanonCS_0x005F": "canon_cs_0x005f",
    "CanonCS_0x0060": "canon_cs_0x0060",
    "CanonCS_0x0061": "canon_cs_0x0061",
    "CanonCS_0x0062": "canon_cs_0x0062",
    "CanonCS_0x0063": "canon_cs_0x0063",
    "CanonCS_0x0064": "canon_cs_0x0064",
    "CanonCS_0x0065": "canon_cs_0x0065",
    "CanonCS_0x0066": "canon_cs_0x0066",
    "CanonCS_0x0067": "canon_cs_0x0067",
    "CanonCS_0x0068": "canon_cs_0x0068",
    "CanonCS_0x0069": "canon_cs_0x0069",
    "CanonCS_0x006A": "canon_cs_0x006a",
    "CanonCS_0x006B": "canon_cs_0x006b",
    "CanonCS_0x006C": "canon_cs_0x006c",
    "CanonCS_0x006D": "canon_cs_0x006d",
    "CanonCS_0x006E": "canon_cs_0x006e",
    "CanonCS_0x006F": "canon_cs_0x006f",
    "CanonCS_0x0070": "canon_cs_0x0070",
    "CanonCS_0x0071": "canon_cs_0x0071",
    "CanonCS_0x0072": "canon_cs_0x0072",
    "CanonCS_0x0073": "canon_cs_0x0073",
    "CanonCS_0x0074": "canon_cs_0x0074",
    "CanonCS_0x0075": "canon_cs_0x0075",
    "CanonCS_0x0076": "canon_cs_0x0076",
    "CanonCS_0x0077": "canon_cs_0x0077",
    "CanonCS_0x0078": "canon_cs_0x0078",
    "CanonCS_0x0079": "canon_cs_0x0079",
    "CanonCS_0x007A": "canon_cs_0x007a",
    "CanonCS_0x007B": "canon_cs_0x007b",
    "CanonCS_0x007C": "canon_cs_0x007c",
    "CanonCS_0x007D": "canon_cs_0x007d",
    "CanonCS_0x007E": "canon_cs_0x007e",
    "CanonCS_0x007F": "canon_cs_0x007f",
    "CanonCS_0x0080": "canon_cs_0x0080",
    "CanonCS_0x0081": "canon_cs_0x0081",
    "CanonCS_0x0082": "canon_cs_0x0082",
    "CanonCS_0x0083": "canon_cs_0x0083",
    "CanonCS_0x0084": "canon_cs_0x0084",
    "CanonCS_0x0085": "canon_cs_0x0085",
    "CanonCS_0x0086": "canon_cs_0x0086",
    "CanonCS_0x0087": "canon_cs_0x0087",
    "CanonCS_0x0088": "canon_cs_0x0088",
    "CanonCS_0x0089": "canon_cs_0x0089",
    "CanonCS_0x008A": "canon_cs_0x008a",
    "CanonCS_0x008B": "canon_cs_0x008b",
    "CanonCS_0x008C": "canon_cs_0x008c",
    "CanonCS_0x008D": "canon_cs_0x008d",
    "CanonCS_0x008E": "canon_cs_0x008e",
    "CanonCS_0x008F": "canon_cs_0x008f",
    "CanonCS_0x0090": "canon_cs_0x0090",
    "CanonCS_0x0091": "canon_cs_0x0091",
    "CanonCS_0x0092": "canon_cs_0x0092",
    "CanonCS_0x0093": "canon_cs_0x0093",
    "CanonCS_0x0094": "canon_cs_0x0094",
    "CanonCS_0x0095": "canon_cs_0x0095",
    "CanonCS_0x0096": "canon_cs_0x0096",
    "CanonCS_0x0097": "canon_cs_0x0097",
    "CanonCS_0x0098": "canon_cs_0x0098",
    "CanonCS_0x0099": "canon_cs_0x0099",
    "CanonCS_0x009A": "canon_cs_0x009a",
    "CanonCS_0x009B": "canon_cs_0x009b",
    "CanonCS_0x009C": "canon_cs_0x009c",
    "CanonCS_0x009D": "canon_cs_0x009d",
    "CanonCS_0x009E": "canon_cs_0x009e",
    "CanonCS_0x009F": "canon_cs_0x009f",
}

CANON_SHOT_INFO = {
    # Shot Info
    "CanonSI_AutoISO": "canon_auto_iso",
    "CanonSI_BaseISO": "canon_base_iso",
    "CanonSI_MeasuredEV": "canon_measured_ev",
    "CanonSI_TargetAperture": "canon_target_aperture",
    "CanonSI_TargetExposureTime": "canon_target_exposure_time",
    "CanonSI_ExposureCompensation": "canon_exposure_compensation",
    "CanonSI_WhiteBalance_2": "canon_white_balance_2",
    "CanonSI_SlowShutter": "canon_slow_shutter",
    "CanonSI_SequenceNumber": "canon_sequence_number",
    "CanonSI_OpticalZoomCode": "canon_optical_zoom_code",
    "CanonSI_CameraTemperature": "canon_camera_temperature",
    "CanonSI_FlashGuideNumber": "canon_flash_guide_number",
    "CanonSI_AFPointsInFocus_2": "canon_af_points_in_focus_2",
    "CanonSI_FlashExposureComp_2": "canon_flash_exposure_comp_2",
    "CanonSI_AutoExposureBracketing": "canon_auto_exposure_bracketing",
    "CanonSI_AEBBracketValue": "canon_aeb_bracket_value",
    "CanonSI_ControlMode_2": "canon_control_mode_2",
    "CanonSI_FocusDistanceUpper": "canon_focus_distance_upper",
    "CanonSI_FocusDistanceLower": "canon_focus_distance_lower",
    "CanonSI_NDFilter_2": "canon_nd_filter_2",
    "CanonSI_SelfTimer2": "canon_self_timer_2",
    "CanonSI_BulbDuration_2": "canon_bulb_duration_2",
    "CanonSI_CameraType_2": "canon_camera_type_2",
    "CanonSI_AutoRotate_2": "canon_auto_rotate_2",
    "CanonSI_SensingMethod_2": "canon_sensing_method_2",
    "CanonSI_ContentType_2": "canon_content_type_2",
    "CanonSI_CustomFunctions_2": "canon_custom_functions_2",
    "CanonSI_CustomFunction1_2": "canon_custom_function1_2",
    "CanonSI_CustomFunction2_2": "canon_custom_function2_2",
    "CanonSI_CustomFunction3_2": "canon_custom_function3_2",
    "CanonSI_CustomFunction4_2": "canon_custom_function4_2",
    "CanonSI_CustomFunction5_2": "canon_custom_function5_2",
    "CanonSI_CustomFunction6_2": "canon_custom_function6_2",
    "CanonSI_CustomFunction7_2": "canon_custom_function7_2",
    "CanonSI_CustomFunction8_2": "canon_custom_function8_2",
    "CanonSI_CustomFunction9_2": "canon_custom_function9_2",
    "CanonSI_CustomFunction10_2": "canon_custom_function10_2",
    "CanonSI_CustomFunction11_2": "canon_custom_function11_2",
    "CanonSI_CustomFunction12_2": "canon_custom_function12_2",
    "CanonSI_AspectRatio_2": "canon_aspect_ratio_2",
    "CanonSI_CropActiveArea_2": "canon_crop_active_area_2",
    "CanonSI_SensorWidth_2": "canon_sensor_width_2",
    "CanonCS_SensorHeight_2": "canon_sensor_height_2",
    "CanonCS_BlackMask_2": "canon_black_mask_2",
    "CanonCS_WhiteMask_2": "canon_white_mask_2",
}

CANON_PICTURE_STYLE = {
    "CanonPS_ContrastStd": "canon_ps_contrast_std",
    "CanonPS_ContrastPortrait": "canon_ps_contrast_portrait",
    "CanonPS_ContrastLandscape": "canon_ps_contrast_landscape",
    "CanonPS_ContrastNeutral": "canon_ps_contrast_neutral",
    "CanonPS_ContrastFaithful": "canon_ps_contrast_faithful",
    "CanonPS_ContrastMonochrome": "canon_ps_contrast_monochrome",
    "CanonPS_SharpnessStd": "canon_ps_sharpness_std",
    "CanonPS_SharpnessPortrait": "canon_ps_sharpness_portrait",
    "CanonPS_SharpnessLandscape": "canon_ps_sharpness_landscape",
    "CanonPS_SharpnessNeutral": "canon_ps_sharpness_neutral",
    "CanonPS_SharpnessFaithful": "canon_ps_sharpness_faithful",
    "CanonPS_SharpnessMonochrome": "canon_ps_sharpness_monochrome",
    "CanonPS_SaturationStd": "canon_ps_saturation_std",
    "CanonPS_SaturationPortrait": "canon_ps_saturation_portrait",
    "CanonPS_SaturationLandscape": "canon_ps_saturation_landscape",
    "CanonPS_SaturationNeutral": "canon_ps_saturation_neutral",
    "CanonPS_SaturationFaithful": "canon_ps_saturation_faithful",
    "CanonPS_SaturationMonochrome": "canon_ps_saturation_monochrome",
    "CanonPS_ColorToneStd": "canon_ps_color_tone_std",
    "CanonPS_ColorTonePortrait": "canon_ps_color_tone_portrait",
    "CanonPS_ColorToneLandscape": "canon_ps_color_tone_landscape",
    "CanonPS_ColorToneNeutral": "canon_ps_color_tone_neutral",
    "CanonPS_ColorToneFaithful": "canon_ps_color_tone_faithful",
    "CanonPS_ColorToneMonochrome": "canon_ps_color_tone_monochrome",
    "CanonPS_FilterEffectMonochrome": "canon_ps_filter_effect_mono",
    "CanonPS_ToningEffectMonochrome": "canon_ps_toning_effect_mono",
    "CanonPS_BlueToneMonochrome": "canon_ps_blue_tone_mono",
    "CanonPS_SepiaToneMonochrome": "canon_ps_sepia_tone_mono",
    "CanonPS_UserDef1Name": "canon_ps_user_def1_name",
    "CanonPS_UserDef2Name": "canon_ps_user_def2_name",
    "CanonPS_UserDef3Name": "canon_ps_user_def3_name",
}

CANON_LENS_INFO = {
    "CanonLI_LensSerialNumber": "canon_lens_serial_number",
    "CanonLI_InternalSerialNumber": "canon_internal_serial_number",
    "CanonLI_FirmwareVersion": "canon_firmware_version",
    "CanonLI_LensModel": "canon_lens_model",
    "CanonLI_LensID": "canon_lens_id",
    "CanonLI_ImageStabilization": "canon_lens_is",
    "CanonLI_MinFocusDistance": "canon_min_focus_distance",
    "CanonLI_MaxFocusDistance": "canon_max_focus_distance",
    "CanonLI_MaxAperture": "canon_lens_max_aperture",
    "CanonLI_MinAperture": "canon_lens_min_aperture",
    "CanonLI_FilterDiameter": "canon_filter_diameter",
    "CanonLI_LensWeight": "canon_lens_weight",
    "CanonLI_LensLength": "canon_lens_length",
    "CanonLI_LensDiameter": "canon_lens_diameter",
    "CanonLI_MountType": "canon_mount_type",
    "CanonLI_Teleconverter": "canon_teleconverter",
    "CanonLI_ExtensionTube": "canon_extension_tube",
    "CanonLI_LensFirmware": "canon_lens_firmware",
    "CanonLI_MinFocalLength": "canon_lens_min_focal",
    "CanonLI_MaxFocalLength": "canon_lens_max_focal",
    "CanonLI_MaxMagnification": "canon_lens_max_mag",
    "CanonLI_FilterSize": "canon_filter_size",
    "CanonLI_HoodModel": "canon_hood_model",
    "CanonLI_LensType1": "canon_lens_type_1",
    "CanonLI_LensType2": "canon_lens_type_2",
    "CanonLI_LensType3": "canon_lens_type_3",
    "CanonLI_LensType4": "canon_lens_type_4",
    "CanonLI_LensType5": "canon_lens_type_5",
    "CanonLI_LensType6": "canon_lens_type_6",
    "CanonLI_LensType7": "canon_lens_type_7",
    "CanonLI_LensType8": "canon_lens_type_8",
    "CanonLI_LensType9": "canon_lens_type_9",
    "CanonLI_LensType10": "canon_lens_type_10",
    "CanonLI_FocalLengthMultiplier": "canon_focal_mult",
    "CanonLI_AFDriverVersion": "canon_af_driver_ver",
    "CanonLI_MotorDriverVersion": "canon_motor_driver_ver",
    "CanonLI_FocusLensPosition": "canon_focus_lens_pos",
    "CanonLI_FocusLensAxis1": "canon_focus_lens_axis_1",
    "CanonLI_FocusLensAxis2": "canon_focus_lens_axis_2",
    "CanonLI_FocusLensAxis3": "canon_focus_lens_axis_3",
    "CanonLI_FocusLensAxis4": "canon_focus_lens_axis_4",
    "CanonLI_FocusLensAxis5": "canon_focus_lens_axis_5",
    "CanonLI_FocusLensAxis6": "canon_focus_lens_axis_6",
    "CanonLI_FocusLensAxis7": "canon_focus_lens_axis_7",
    "CanonLI_FocusLensAxis8": "canon_focus_lens_axis_8",
    "CanonLI_ExitPupilPosition": "canon_exit_pupil_pos",
    "CanonLI_AFMicroAdj": "canon_af_micro_adj",
    "CanonLI_AFMicroAdjValue": "canon_af_micro_adj_val",
    "CanonLI_ImageStabInfo": "canon_is_info",
    "CanonLI_GripInfo": "canon_grip_info",
}

CANON_FILE_INFO = {
    "CanonFI_FileNumber": "canon_file_number",
    "CanonFI_DirectoryNumber": "canon_directory_number",
    "CanonFI_ShutterCount": "canon_shutter_count",
    "CanonFI_BracketMode": "canon_bracket_mode",
    "CanonFI_BracketValue": "canon_bracket_value",
    "CanonFI_RawJpgQuality": "canon_raw_jpg_quality",
    "CanonFI_RawJpgSize": "canon_raw_jpg_size",
    "CanonFI_LongExposureNoiseReduction": "canon_long_exposure_nr",
    "CanonFI_HighISONoiseReduction": "canon_high_iso_nr",
    "CanonFI_LiveViewShooting": "canon_live_view_shooting",
    "CanonFI_FocusDistanceUpper": "canon_focus_distance_upper",
    "CanonFI_FocusDistanceLower": "canon_focus_distance_lower",
    "CanonFI_ColorDataVersion": "canon_color_data_version",
    "CanonFI_CameraInfoVersion": "canon_camera_info_version",
    "CanonFI_LensModel2": "canon_lens_model_2",
    "CanonFI_SerialInfoVersion": "canon_serial_info_version",
    "CanonFI_DateStampMode": "canon_date_stamp_mode",
    "CanonFI_SavedSettingsVersion": "canon_saved_settings_version",
    "CanonFI_VRDISO": "canon_vrd_iso",
    "CanonFI_PeripheralIllumination": "canon_peripheral_illumination",
    "CanonFI_FaceDetect": "canon_face_detection",
    "CanonFI_AFMicroAdj": "canon_af_micro_adj",
    "CanonFI_AFMicroAdjValue": "canon_af_micro_adj_value",
    "CanonFI_PhosphorAlignment": "canon_phosphor_alignment",
    "CanonFI_CustomFunction17": "canon_custom_17",
    "CanonFI_CustomFunction18": "canon_custom_18",
    "CanonFI_CustomFunction19": "canon_custom_19",
    "CanonFI_CustomFunction20": "canon_custom_20",
    "CanonFI_CustomFunction21": "canon_custom_21",
    "CanonFI_CustomFunction22": "canon_custom_22",
    "CanonFI_CustomFunction23": "canon_custom_23",
    "CanonFI_CustomFunction24": "canon_custom_24",
    "CanonFI_CustomFunction25": "canon_custom_25",
    "CanonFI_CustomFunction26": "canon_custom_26",
    "CanonFI_CustomFunction27": "canon_custom_27",
    "CanonFI_CustomFunction28": "canon_custom_28",
    "CanonFI_CustomFunction29": "canon_custom_29",
    "CanonFI_CustomFunction30": "canon_custom_30",
}

NIKON_VERSION = {
    "NikonVer_Version": "nikon_version",
    "NikonVer_ReproductionInfo": "nikon_reproduction_info",
    "NikonVer_CameraColorCalibration": "nikon_color_calibration",
    "NikonVer_CameraSpecificSettings": "nikon_camera_settings",
}

NIKON_ISO_INFO = {
    "NikonISOInfo_ISO": "nikon_iso",
    "NikonISOInfo_ISOExpansion": "nikon_iso_expansion",
    "NikonISOInfo_ISOExpansion2": "nikon_iso_expansion_2",
    "NikonISOInfo_ISOSettings": "nikon_iso_settings",
    "NikonISOInfo_HighISONoiseReduction": "nikon_high_iso_nr",
}

NIKON_SHOT_INFO = {
    "NikonShotInfo_ShutterCount": "nikon_shutter_count",
    "NikonShotInfo_VRMode": "nikon_vr_mode",
    "NikonShotInfo_VibrationReduction": "nikon_vibration_reduction",
    "NikonShotInfo_VRInfo": "nikon_vr_info",
    "NikonShotInfo_FocusMode": "nikon_focus_mode",
    "NikonShotInfo_AF_S_AF_C_Mode": "nikon_af_s_af_c_mode",
    "NikonShotInfo_AF_AreaMode": "nikon_af_area_mode",
    "NikonShotInfo_AFPoint": "nikon_af_point",
    "NikonShotInfo_AFPointsInFocus": "nikon_af_points_in_focus",
    "NikonShotInfo_FlashSetting": "nikon_flash_setting",
    "NikonShotInfo_FlashMode": "nikon_flash_mode",
    "NikonShotInfo_FlashExposureComp": "nikon_flash_exposure_comp",
    "NikonShotInfo_WhiteBalance": "nikon_white_balance",
    "NikonShotInfo_WhiteBalanceFineTune": "nikon_wb_fine_tune",
    "NikonShotInfo_ExposureCompensation": "nikon_exposure_compensation",
    "NikonShotInfo_ExposureProgram": "nikon_exposure_program",
    "NikonShotInfo_MeteringMode": "nikon_metering_mode",
    "NikonShotInfo_ExposureMode": "nikon_exposure_mode",
    "NikonShotInfo_FocusPosition": "nikon_focus_position",
    "NikonShotInfo_CameraTemperature": "nikon_camera_temperature",
    "NikonShotInfo_FocusStepCount": "nikon_focus_step_count",
    "NikonShotInfo_FocusStepOffset": "nikon_focus_step_offset",
    "NikonShotInfo_SoftwareVersion": "nikon_software_version",
    "NikonShotInfo_CrossTypeAFPoints": "nikon_cross_type_af_points",
    "NikonShotInfo_ActiveD-Lighting": "nikon_active_d_lighting",
    "NikonShotInfo_PictureControl": "nikon_picture_control",
    "NikonShotInfo_WorldTime": "nikon_world_time",
    "NikonShotInfo_ISOInfo": "nikon_iso_info",
    "NikonShotInfo_FlashInfo": "nikon_flash_info",
    "NikonShotInfo_ProgramShift": "nikon_program_shift",
    "NikonShotInfo_ExposureDifference": "nikon_exposure_difference",
    "NikonShotInfo_ISOAutoSettings": "nikon_iso_auto_settings",
    "NikonShotInfo_Bracketing": "nikon_bracketing",
    "NikonShotInfo_LiveViewAFMode": "nikon_live_view_af_mode",
    "NikonShotInfo_LiveViewAFAreaMode": "nikon_live_view_af_area",
    "NikonShotInfo_LiveViewPhaseDetectAF": "nikon_live_view_pd_af",
    "NikonShotInfo_ElectronicFrontCurtain": "nikon_electronic_front_curtain",
    "NikonShotInfo_HDRExposureDiff": "nikon_hdr_exposure_diff",
    "NikonShotInfo_HDRSmoothing": "nikon_hdr_smoothing",
    "NikonShotInfo_HDRMode": "nikon_hdr_mode",
    "NikonShotInfo_FlatColorProfile": "nikon_flat_color_profile",
    "NikonShotInfo_ToneComp": "nikon_tone_comp",
    "NikonShotInfo_LensAdaptor": "nikon_lens_adaptor",
    "NikonShotInfo_LensSerialNumber": "nikon_lens_serial",
    "NikonShotInfo_LensModel": "nikon_lens_model",
    "NikonShotInfo_LensType": "nikon_lens_type",
    "NikonShotInfo_LensFStops": "nikon_lens_f_stops",
    "NikonShotInfo_MinFocalLength": "nikon_min_focal",
    "NikonShotInfo_MaxFocalLength": "nikon_max_focal",
    "NikonShotInfo_MaxApertureAtMinFocal": "nikon_max_aperture_min",
    "NikonShotInfo_MaxApertureAtMaxFocal": "nikon_max_aperture_max",
    "NikonShotInfo_MCUVersion": "nikon_mcu_version",
}

NIKON_COLOR_BALANCE = {
    "NikonColorBalance_WBRBLevels": "nikon_wb_rb_levels",
    "NikonColorBalance_WBPreset": "nikon_wb_preset",
    "NikonColorBalance_WBPresetNum": "nikon_wb_preset_num",
    "NikonColorBalance_WBCoords": "nikon_wb_coords",
    "NikonColorBalance_WBRedLevel": "nikon_wb_red",
    "NikonColorBalance_WBGreenLevel": "nikon_wb_green",
    "NikonColorBalance_WBBlueLevel": "nikon_wb_blue",
    "NikonColorBalance_WBColorTemp": "nikon_wb_color_temp",
    "NikonColorBalance_WBPreFlash": "nikon_wb_preflash",
    "NikonColorBalance_WBFlashTemp": "nikon_wb_flash_temp",
}

NIKON_LENS_DATA = {
    "NikonLensData_LensIDNumber": "nikon_lens_id",
    "NikonLensData_LensFStops": "nikon_lens_f_stops",
    "NikonLensData_MinFocalLength": "nikon_min_focal_length",
    "NikonLensData_MaxFocalLength": "nikon_max_focal_length",
    "NikonLensData_MaxApertureAtMinFocal": "nikon_max_aperture_min",
    "NikonLensData_MaxApertureAtMaxFocal": "nikon_max_aperture_max",
    "NikonLensData_MCUVersion": "nikon_mcu_version",
    "NikonLensData_EffectiveMaxAperture": "nikon_effective_max_aperture",
    "NikonLensData_DistortionControl": "nikon_distortion_control",
    "NikonLensData_ActiveDLighting": "nikon_lens_active_d_lighting",
    "NikonLensData_VignetteControl": "nikon_vignette_control",
    "NikonLensData_AutoDistortionControl": "nikon_auto_distortion",
    "NikonLensData_LensKind": "nikon_lens_kind",
    "NikonLensData_LensSerialNumber": "nikon_lens_serial",
    "NikonLensData_LensModel": "nikon_lens_model",
    "NikonLensData_Aperture": "nikon_lens_aperture",
    "NikonLensData_FocalLength": "nikon_focal_length",
    "NikonLensData_FocusDistance": "nikon_focus_distance",
    "NikonLensData_FocusMode": "nikon_lens_focus_mode",
}

NIKON_FLASH_INFO = {
    "NikonFlashInfo_FlashSetting": "nikon_flash_setting",
    "NikonFlashInfo_FlashType": "nikon_flash_type",
    "NikonFlashInfo_FlashMode": "nikon_flash_mode",
    "NikonFlashInfo_FlashExposureComp": "nikon_flash_exposure_comp",
    "NikonFlashInfo_ExternalFlashFlags": "nikon_external_flash_flags",
    "NikonFlashInfo_FlashControlCommanderMode": "nikon_flash_commander_mode",
    "NikonFlashInfo_FlashOutput": "nikon_flash_output",
    "NikonFlashInfo_FlashCompensation": "nikon_flash_compensation",
    "NikonFlashInfo_FlashColorFilter": "nikon_flash_color_filter",
    "NikonFlashInfo_FlashGroupACompensation": "nikon_flash_group_a_comp",
    "NikonFlashInfo_FlashGroupBCompensation": "nikon_flash_group_b_comp",
    "NikonFlashInfo_FlashGroupCCompensation": "nikon_flash_group_c_comp",
    "NikonFlashInfo_FlashGroupDCompensation": "nikon_flash_group_d_comp",
    "NikonFlashInfo_FlashExposureIndicator": "nikon_flash_indicator",
}

NIKON_AF_INFO = {
    "NikonAFInfo_AFAreaMode": "nikon_af_area_mode",
    "NikonAFInfo_AFPoint": "nikon_af_point",
    "NikonAFInfo_AFPointsInFocus": "nikon_af_points_in_focus",
    "NikonAFInfo_ContrastDetectAF": "nikon_contrast_detect_af",
    "NikonAFInfo_AFAreaXPosition": "nikon_af_area_x",
    "NikonAFInfo_AFAreaYPosition": "nikon_af_area_y",
    "NikonAFInfo_AFAreaWidth": "nikon_af_area_width",
    "NikonAFInfo_AFAreaHeight": "nikon_af_area_height",
    "NikonAFInfo_PrimaryAFPoint": "nikon_primary_af_point",
    "NikonAFInfo_AFPointSelected": "nikon_af_point_selected",
    "NikonAFInfo_AFPointUsed": "nikon_af_point_used",
    "NikonAFInfo_AFPointIllumination": "nikon_af_point_illumination",
    "NikonAFInfo_AFFineTune": "nikon_af_fine_tune",
    "NikonAFInfo_AFFineTuneIndex": "nikon_af_fine_tune_index",
    "NikonAFInfo_AFFineTuneValue": "nikon_af_fine_tune_value",
}

NIKON_FILE_INFO = {
    "NikonFileInfo_DirectoryNumber": "nikon_directory_number",
    "NikonFileInfo_FileNumber": "nikon_file_number",
    "NikonFileInfo_FileSequenceNumber": "nikon_file_seq_number",
    "NikonFileInfo_RawCompression": "nikon_raw_compression",
    "NikonFileInfo_NEFBitDepth": "nikon_nef_bit_depth",
    "NikonFileInfo_NEFCompression": "nikon_nef_compression",
    "NikonFileInfo_ToneMode": "nikon_tone_mode",
    "NikonFileInfo_LongExposureNoiseReduction": "canon_long_exposure_nr",
    "NikonFileInfo_HighISONoiseReduction": "canon_high_iso_nr",
    "NikonFileInfo_HighISONoiseReduction2": "canon_high_iso_nr_2",
    "NikonFileInfo_ActiveDLightingSetting": "nikon_adl_setting",
    "NikonFileInfo_PreviewImageIFD": "nikon_preview_ifd",
    "NikonFileInfo_MetadataUpdate": "nikon_metadata_update",
    "NikonFileInfo_ImageAuthentication": "nikon_image_auth",
}

NIKON_PICTURE_CONTROL = {
    "NikonPictureControl_PictureControlName": "nikon_picture_control_name",
    "NikonPictureControl_PictureControlBase": "nikon_picture_control_base",
    "NikonPictureControl_PictureControlAdjust": "nikon_picture_control_adjust",
    "NikonPictureControl_PictureControlQuickAdjust": "nikon_picture_control_quick_adjust",
    "NikonPictureControl_Sharpness": "nikon_sharpness",
    "NikonPictureControl_Contrast": "nikon_contrast",
    "NikonPictureControl_Brightness": "nikon_brightness",
    "NikonPictureControl_Saturation": "nikon_saturation",
    "NikonPictureControl_HueAdjustment": "nikon_hue_adjustment",
    "NikonPictureControl_FilterEffect": "nikon_filter_effect",
    "NikonPictureControl_ToningEffect": "nikon_toning_effect",
    "NikonPictureControl_ActivePictureControl": "nikon_active_pc",
}

NIKON_WORLD_TIME = {
    "NikonWorldTime_Timezone": "nikon_timezone",
    "NikonWorldTime_DaylightSavings": "nikon_daylight_savings",
    "NikonWorldTime_DateDisplayFormat": "nikon_date_format",
    "NikonWorldTime_TimeZoneOffset": "nikon_tz_offset",
}

SONY_CAMERA_SETTINGS = {
    "SonyModelID": "sony_model_id",
    "SonyCameraSettings_DriveMode": "sony_drive_mode",
    "SonyCameraSettings_WhiteBalanceFineTune": "sony_wb_fine_tune",
    "SonyCameraSettings_FocusMode": "sony_focus_mode",
    "SonyCameraSettings_AFAreaMode": "sony_af_area_mode",
    "SonyCameraSettings_LocalAFAreaPoint": "sony_local_af_point",
    "SonyCameraSettings_MeteringMode": "sony_metering_mode",
    "SonyCameraSettings_ISOSetting": "sony_iso_setting",
    "SonyCameraSettings_ExposureCompensation": "sony_exposure_compensation",
    "SonyCameraSettings_DynamicRangeOptimizer": "sony_dro_level",
    "SonyCameraSettings_ImageStabilization": "sony_image_stabilization",
    "SonyCameraSettings_ColorMode": "sony_color_mode",
    "SonyCameraSettings_ColorSpace": "sony_color_space",
    "SonyCameraSettings_Sharpness": "sony_sharpness",
    "SonyCameraSettings_Contrast": "sony_contrast",
    "SonyCameraSettings_Saturation": "sony_saturation",
    "SonyCameraSettings_ZoneMatching": "sony_zone_matching",
    "SonyCameraSettings_ColorTemperature": "sony_color_temperature",
    "SonyCameraSettings_LensSpec": "sony_lens_spec",
    "SonyCameraSettings_LensMount": "sony_lens_mount",
    "SonyCameraSettings_LensFormat": "sony_lens_format",
    "SonyCameraSettings_FocusArea": "sony_focus_area",
    "SonyCameraSettings_CenterSpot": "sony_center_spot",
    "SonyCameraSettings_FlashLevel": "sony_flash_level",
    "SonyCameraSettings_RedEyeReduction": "sony_red_eye_reduction",
    "SonyCameraSettings_LongExposureNoiseReduction": "sony_long_exp_nr",
    "SonyCameraSettings_HighISONoiseReduction": "sony_high_iso_nr",
    "SonyCameraSettings_ISORange": "sony_iso_range",
    "SonyCameraSettings_FilterEffect": "sony_filter_effect",
    "SonyCameraSettings_ToningEffect": "sony_toning_effect",
    "SonyCameraSettings_CreativeStyle": "sony_creative_style",
    "SonyCameraSettings_VariableLowPassFilter": "sony_v_lpf",
    "SonyCameraSettings_PanoramaWidth": "sony_pano_width",
    "SonyCameraSettings_PanoramaHeight": "sony_pano_height",
    "SonyCameraSettings_PanoramaDirection": "sony_pano_direction",
    "SonyCameraSettings_HighISOHighNoiseReduction": "sony_hi_iso_h_nr",
    "SonyCameraSettings_LensCompensation": "sony_lens_comp",
    "SonyCameraSettings_WideFocusIndicator": "sony_wide_focus",
    "SonyCameraSettings_FocusPosition": "sony_focus_position",
}

SONY_AF_INFO = {
    "SonyAFInfo_AFPointSelected": "sony_af_point_selected",
    "SonyAFInfo_AFPointsUsed": "sony_af_points_used",
    "SonyAFInfo_AFTracking": "sony_af_tracking",
    "SonyAFInfo_FocusPosition": "sony_focus_position",
    "SonyAFInfo_AFMode": "sony_af_mode",
    "SonyAFInfo_AF illuminator": "sony_af_illuminator",
    "SonyAFInfo_AFAreaSettings": "sony_af_area_settings",
    "SonyAFInfo_FullTimeAF": "sony_full_time_af",
    "SonyAFInfo_AFSubarea": "sony_af_subarea",
    "SonyAFInfo_FocusMode2": "sony_focus_mode_2",
    "SonyAFInfo_AFAreaMode2": "sony_af_area_mode_2",
    "SonyAFInfo_LocalAFAreaPoint2": "sony_local_af_point_2",
    "SonyAFInfo_FocusPosition2": "sony_focus_position_2",
}

SONY_FILE_INFO = {
    "SonyShutterCount": "sony_shutter_count",
    "SonyInternalSerialNumber": "sony_internal_serial_number",
    "SonyLensSerialNumber": "sony_lens_serial_number",
    "SonyBodySerialNumber": "sony_body_serial_number",
    "SonyFirmwareVersion": "sony_firmware_version",
    "SonyExposureCompensation2": "sony_exposure_compensation_2",
    "SonyDateTime": "sony_date_time",
    "SonyImageNumber": "sony_image_number",
    "SonyImageSequence": "sony_image_sequence",
    "SonyQuality2": "sony_quality_2",
    "SonyQuality3": "sony_quality_3",
    "SonySonyImageWidth": "sony_image_width",
    "SonySonyImageHeight": "sony_image_height",
    "SonyImageSize": "sony_image_size",
    "SonyFileFormat": "sony_file_format",
    "SonyRawFormat": "sony_raw_format",
    "SonyRating": "sony_rating",
    "SonyColorMode": "sony_color_mode_2",
    "SonyFullPanoramaShootingData": "sony_pano_data",
    "SonyMultiBurstImageWidth": "sony_multiburst_width",
    "SonyMultiBurstImageHeight": "sony_multiburst_height",
    "SonyMultiBurstMode": "sony_multiburst_mode",
    "SonyPanorama3DData": "sony_pano_3d_data",
}

SONY_MOVIE_INFO = {
    "SonyMovie_FileFormat": "sony_movie_format",
    "SonyMovie_VideoCodec": "sony_video_codec",
    "SonyMovie_VideoResolution": "sony_video_resolution",
    "SonyMovie_VideoFrameRate": "sony_video_frame_rate",
    "SonyMovie_VideoBitrate": "sony_video_bitrate",
    "SonyMovie_AudioCodec": "sony_audio_codec",
    "SonyMovie_AudioBitrate": "sony_audio_bitrate",
    "SonyMovie_ShootingMode": "sony_shooting_mode",
    "SonyMovie_FocusMode": "sony_movie_focus_mode",
    "SonyMovie_Stabilization": "sony_movie_stabilization",
    "SonyMovie_AutoSlomo": "sony_auto_slomo",
    "SonyMovie_SlomoFrameRate": "sony_slomo_frame_rate",
}

FUJIFILM_VERSION = {
    "FujiFilmVersion": "fuji_version",
    "FujiFilmSerialNumber": "fuji_serial_number",
    "FujiFilmInternalSerialNumber": "fuji_internal_serial",
    "FujiFilmFirmwareVersion": "fuji_firmware",
    "FujiFilmQuality": "fuji_quality",
}

FUJIFILM_CAMERA_SETTINGS = {
    "FujiFilmSharpness": "fuji_sharpness",
    "FujiFilmWhiteBalance": "fuji_white_balance",
    "FujiFilmWhiteBalanceFine": "fuji_wb_fine",
    "FujiFilmSaturation": "fuji_saturation",
    "FujiFilmContrast": "fuji_contrast",
    "FujiFilmColorTemperature": "fuji_color_temperature",
    "FujiFilmFlashMode": "fuji_flash_mode",
    "FujiFilmFlashStrength": "fuji_flash_strength",
    "FujiFilmMacro": "fuji_macro",
    "FujiFilmFocusMode": "fuji_focus_mode",
    "FujiFilm_SlowSync": "fuji_slow_sync",
    "FujiFilmPictureMode": "fuji_picture_mode",
    "FujiFilmContinuousBracketing": "fuji_continuous_bracketing",
    "FujiFilm_BlurWarning": "fuji_blur_warning",
    "FujiFilmFocusWarning": "fuji_focus_warning",
    "FujiFilmExposureWarning": "fuji_exposure_warning",
    "FujiFilm_DynamicRange": "fuji_dynamic_range",
    "FujiFilmFilmMode": "fuji_film_mode",
    "FujiFilmGrainEffect": "fuji_grain_effect",
    "FujiFilmColorChromeEffect": "fuji_color_chrome_effect",
    "FujiFilmShutterType": "fuji_shutter_type",
    "FujiFilmAutoFocusSetting": "fuji_af_setting",
    "FujiFilmFocusSettings": "fuji_focus_settings",
    "FujiFilm_AFCSettings": "fuji_afc_settings",
    "FujiFilm_ImageStabilization": "fuji_image_stabilization",
    "FujiFilm_LensModulationOptimizer": "fuji_lmo",
    "FujiFilm_MediumFormatLensAdapter": "fuji_medium_format_adapter",
    "FujiFilm_Photometry": "fuji_photometry",
    "FujiFilm_ExposureIndex": "fuji_exposure_index",
    "FujiFilm_BaseSensitivity": "fuji_base_sensitivity",
    "FujiFilm_DefaultSharpness": "fuji_default_sharpness",
    "FujiFilm_ColorClarity": "fuji_color_clarity",
    "FujiFilm_ToneCurve": "fuji_tone_curve",
    "FujiFilm_ToneMapping": "fuji_tone_mapping",
    "FujiFilm_LongExposureReduction": "fuji_long_exp_reduction",
    "FujiFilm_HighISONoiseReduction": "fuji_high_iso_nr",
    "FujiFilm_FlashExposureComp": "fuji_flash_ec",
    "FujiFilm_WhiteBalanceShift": "fuji_wb_shift",
    "FujiFilm_ISOMode": "fuji_iso_mode",
    "FujiFilm_ElectronicLevel": "fuji_electronic_level",
    "FujiFilm_FilterSettings": "fuji_filter_settings",
}

FUJIFILM_LENS_INFO = {
    "FujiFilmLensSerialNumber": "fuji_lens_serial",
    "FujiFilmLensModel": "fuji_lens_model",
    "FujiFilmLensID": "fuji_lens_id",
    "FujiFilmLensFirmware": "fuji_lens_firmware",
    "FujiFilmFocalLength": "fuji_focal_length",
    "FujiFilmFocalLength35mm": "fuji_focal_length_35mm",
    "FujiFilmMaxAperture": "fuji_max_aperture",
    "FujiFilmMinAperture": "fuji_min_aperture",
    "FujiFilm_FocusDistance": "fuji_focus_distance",
    "FujiFilmMacroMode": "fuji_macro_mode",
    "FujiFilm_DigitalZoom": "fuji_digital_zoom",
}

FUJIFILM_FILM_SIMULATION = {
    "FujiFilmFilmSimulation_Provia": "fuji_provia",
    "FujiFilmFilmSimulation_Velvia": "fuji_velvia",
    "FujiFilmFilmSimulation_Astia": "fuji_astia",
    "FujiFilmFilmSimulation_ClassicChrome": "fuji_classic_chrome",
    "FujiFilmFilmSimulation_ClassicNeg": "fuji_classic_neg",
    "FujiFilmFilmSimulation_ProNegStd": "fuji_pro_neg_std",
    "FujiFilmFilmSimulation_ProNegHi": "fuji_pro_neg_hi",
    "FujiFilmFilmSimulation_Acros": "fuji_acros",
    "FujiFilmFilmSimulation_Monochrome": "fuji_monochrome",
    "FujiFilmFilmSimulation_Sepia": "fuji_sepia",
    "FujiFilmFilmSimulation_Eterna": "fuji_eterna",
    "FujiFilmFilmSimulation_NostalgicNeg": "fuji_nostalgic_neg",
}

OLYMPUS_EQUIPMENT = {
    "OlympusVersion": "olympus_version",
    "OlympusEquipment_EquipmentVersion": "olympus_equipment_version",
    "OlympusEquipment_CameraType": "olympus_camera_type",
    "OlympusEquipment_CameraSerialNumber": "olympus_camera_serial",
    "OlympusEquipment_InternalSerialNumber": "olympus_internal_serial",
    "OlympusEquipment_FocusRange": "olympus_focus_range",
    "OlympusEquipment_FocusMode": "olympus_focus_mode",
    "OlympusEquipment_AFSearch": "olympus_af_search",
    "OlympusEquipment_AFPoint": "olympus_af_point",
    "OlympusEquipment_AFMode": "olympus_af_mode",
    "OlympusEquipment_LensType": "olympus_lens_type",
    "OlympusEquipment_LensSerialNumber": "olympus_lens_serial",
    "OlympusEquipment_LensModel": "olympus_lens_model",
    "OlympusEquipment_BodyFirmware": "olympus_body_firmware",
    "OlympusEquipment_MountVersion": "olympus_mount_version",
    "OlympusEquipment_Extender": "olympus_extender",
    "OlympusEquipment_ExtenderSerialNumber": "olympus_extender_serial",
}

OLYMPUS_IMAGE_PROCESSING = {
    "OlympusImageProcessing_SharpnessValue": "olympus_sharpness",
    "OlympusImageProcessing_ContrastValue": "olympus_contrast",
    "OlympusImageProcessing_SaturationValue": "olympus_saturation",
    "OlympusImageProcessing_Gradation": "olympus_gradation",
    "OlympusImageProcessing_NoiseReduction": "olympus_noise_reduction",
    "OlympusImageProcessing_EngineerMode": "olympus_engineer_mode",
    "OlympusImageProcessing_PictureMode": "olympus_picture_mode",
    "OlympusImageProcessing_PictureModeValue": "olympus_picture_mode_value",
    "OlympusImageProcessing_ArtFilter": "olympus_art_filter",
    "OlympusImageProcessing_ArtFilterVersion": "olympus_art_filter_version",
    "OlympusImageProcessing_ColorCreator": "olympus_color_creator",
    "OlympusImageProcessing_Tone": "olympus_tone",
    "OlympusImageProcessing_PerspectiveCorrection": "olympus_perspective",
    "OlympusImageProcessing_ShadingCompensation": "olympus_shading",
    "OlympusImageProcessing_DistortionCorrection": "olympus_distortion",
    "OlympusImageProcessing_ColorSpace": "olympus_color_space",
    "OlympusImageProcessing_FilterEffect": "olympus_filter_effect",
}

OLYMPUS_RAW_DEVELOPMENT = {
    "OlympusRawDevelopment_Process": "olympus_raw_process",
    "OlympusRawDevelopment_ToneCurve": "olympus_tone_curve",
    "OlympusRawDevelopment_ColorMatrix": "olympus_color_matrix",
    "OlympusRawDevelopment_WhiteBalance": "olympus_wb",
    "OlympusRawDevelopment_WhiteBalanceValue": "olympus_wb_value",
    "OlympusRawDevelopment_ShotSettings": "olympus_shot_settings",
    "OlympusRawDevelopment_Lens compensation": "olympus_lens_comp",
    "OlympusRawDevelopment_CustomMatrix": "olympus_custom_matrix",
}

OLYMPUS_FOCUS_INFO = {
    "OlympusFocusInfo_FocusDistance": "olympus_focus_distance",
    "OlympusFocusInfo_FocusStep": "olympus_focus_step",
    "OlympusFocusInfo_FocusStepCount": "olympus_focus_step_count",
    "OlympusFocusInfo_FocusStepIndex": "olympus_focus_step_index",
    "OlympusFocusInfo_FocusPosition": "olympus_focus_position",
    "OlympusFocusInfo_FocusMethod": "olympus_focus_method",
    "OlympusFocusInfo_FocusSensor": "olympus_focus_sensor",
    "OlympusFocusInfo_AFTargetX": "olympus_af_target_x",
    "OlympusFocusInfo_AFTargetY": "olympus_af_target_y",
    "OlympusFocusInfo_FaceDetection": "olympus_face_detection",
    "OlympusFocusInfo_FacePoints": "olympus_face_points",
}

OLYMPUS_SENSOR_INFO = {
    "OlympusSensor_Temperature": "olympus_sensor_temp",
    "OlympusSensor_SensorType": "olympus_sensor_type",
    "OlympusSensor_SensorSerialNumber": "olympus_sensor_serial",
    "OlympusSensor_DustReduction": "olympus_dust_reduction",
    "OlympusSensor_DustStatus": "olympus_dust_status",
    "OlympusSensor_CleaningCycles": "olympus_cleaning_cycles",
}

PANASONIC_CAMERA_SETTINGS = {
    "PanasonicMakerNoteVersion": "panasonic_version",
    "PanasonicSpecialMode": "panasonic_special_mode",
    "PanasonicQuality": "panasonic_quality",
    "PanasonicPictureSize": "panasonic_picture_size",
    "PanasonicAspectRatio": "panasonic_aspect_ratio",
    "PanasonicQuality2": "panasonic_quality_2",
    "PanasonicAFMode": "panasonic_af_mode",
    "PanasonicAFPointPosition": "panasonic_af_point_position",
    "PanasonicFaceDetection": "panasonic_face_detection",
    "PanasonicRollAngle": "panasonic_roll_angle",
    "PanasonicPitchAngle": "panasonic_pitch_angle",
    "PanasonicFocusStep": "panasonic_focus_step",
    "PanasonicZoomTeleMacro": "panasonic_zoom_tele_macro",
    "PanasonicImageStabilization": "panasonic_image_stabilization",
    "PanasonicMacroMode": "panasonic_macro_mode",
    "PanasonicShootingMode": "panasonic_shooting_mode",
    "PanasonicPostCropExposureCompensation": "panasonic_post_crop_ec",
    "PanasonicColorMode": "panasonic_color_mode",
    "PanasonicLensType": "panasonic_lens_type",
    "PanasonicLensSerialNumber": "panasonic_lens_serial",
    "PanasonicAccessoryType": "panasonic_accessory_type",
    "PanasonicAccessorySerialNumber": "panasonic_accessory_serial",
    "Panasonic_BurstMode": "panasonic_burst_mode",
    "Panasonic_BurstRate": "panasonic_burst_rate",
    "Panasonic_4KPhotoMode": "panasonic_4k_photo",
    "Panasonic_PostFocusMode": "panasonic_post_focus",
    "Panasonic_FocusStacking": "panasonic_focus_stacking",
    "Panasonic_HighSpeedVideo": "panasonic_hs_video",
    "Panasonic_TimeLapse": "panasonic_time_lapse",
    "Panasonic_StopMotion": "panasonic_stop_motion",
    "Panasonic_ExposureCompensation2": "panasonic_ec_2",
    "Panasonic_WhiteBalance": "panasonic_white_balance",
    "Panasonic_WhiteBalanceFine": "panasonic_wb_fine",
    "Panasonic_Flash": "panasonic_flash",
    "Panasonic_RemoteControl": "panasonic_remote",
}

PANASONIC_LENS_INFO = {
    "PanasonicLensModel": "panasonic_lens_model",
    "PanasonicLensFirmware": "panasonic_lens_firmware",
    "PanasonicLensType2": "panasonic_lens_type_2",
    "PanasonicFocalLength": "panasonic_focal_length",
    "PanasonicFocalLength35mm": "panasonic_focal_length_35",
    "PanasonicMaxAperture": "panasonic_max_aperture",
    "PanasonicMinAperture": "panasonic_min_aperture",
    "PanasonicFocusDistance": "panasonic_focus_distance",
    "PanasonicZoomPosition": "panasonic_zoom_position",
    "PanasonicOpticalImageStabilizer": "panasonic_ois",
}

PENTAX_CAMERA_SETTINGS = {
    "PentaxVersion": "pentax_version",
    "PentaxCameraType": "pentax_camera_type",
    "PentaxModelID": "pentax_model_id",
    "PentaxImageSize": "pentax_image_size",
    "PentaxQuality": "pentax_quality",
    "PentaxQuality2": "pentax_quality_2",
    "PentaxFocusMode": "pentax_focus_mode",
    "PentaxAFPoint": "pentax_af_point",
    "PentaxAFPointInFocus": "pentax_af_in_focus",
    "PentaxExposureTime": "pentax_exposure_time",
    "PentaxFNumber": "pentax_f_number",
    "PentaxISO": "pentax_iso",
    "PentaxWhiteBalance": "pentax_white_balance",
    "PentaxWhiteBalanceMode": "pentax_wb_mode",
    "PentaxWhiteBalanceFine": "pentax_wb_fine",
    "PentaxShutterCount": "pentax_shutter_count",
    "PentaxDustRemoval": "pentax_dust_removal",
    "PentaxDRO": "pentax_dro",
    "PentaxHDR": "pentax_hdr",
    "PentaxShutterType": "pentax_shutter_type",
    "PentaxBodySerialNumber": "pentax_body_serial",
    "PentaxLensType": "pentax_lens_type",
    "PentaxLensSerialNumber": "pentax_lens_serial",
    "PentaxLensModel": "pentax_lens_model",
    "PentaxLensFStops": "pentax_lens_f_stops",
    "PentaxMeteringMode": "pentax_metering_mode",
    "PentaxExposureMode": "pentax_exposure_mode",
    "PentaxExposureCompensation": "pentax_exposure_comp",
    "PentaxAEMeteringPoints": "pentax_ae_points",
    "PentaxAEMeteringAreas": "pentax_ae_areas",
    "PentaxFlashMode": "pentax_flash_mode",
    "PentaxFlashExposureCompensation": "pentax_flash_ec",
    "PentaxDriveMode": "pentax_drive_mode",
    "PentaxBracketMode": "pentax_bracket_mode",
    "PentaxBracketShotNumber": "pentax_bracket_shot",
    "PentaxWhiteBalanceBracket": "pentax_wb_bracket",
    "PentaxISOBracket": "pentax_iso_bracket",
    "Pentax_DynamicRangeExpansion": "pentax_dre",
    "Pentax_HighISONoiseReduction": "pentax_high_iso_nr",
    "Pentax_ShadowCorrection": "pentax_shadow_correct",
    "Pentax_LensCorrection": "pentax_lens_correct",
    "Pentax_AAFilter": "pentax_aa_filter",
    "Pentax_FilmSimulation": "pentax_film_sim",
    "Pentax_ColorCapture": "pentax_color_capture",
    "Pentax_Freshness": "pentax_freshness",
    "Pentax_CustomPreview": "pentax_custom_preview",
    "Pentax_FirmwareDate": "pentax_firmware_date",
    "Pentax_Temperature": "pentax_temperature",
    "Pentax_PrivacyIndicator": "pentax_privacy",
    "Pentax_GPS": "pentax_gps",
    "Pentax_GPSLatitude": "pentax_gps_lat",
    "Pentax_GPSLongitude": "pentax_gps_lon",
    "Pentax_GPSAltitude": "pentax_gps_alt",
    "Pentax_GPSTime": "pentax_gps_time",
    "Pentax_AstroTracer": "pentax_astro_tracer",
    "Pentax_ElectronicLevel": "pentax_level",
}


CANON_MAKERNOTE_TAGS = {**CANON_CAMERA_SETTINGS, **CANON_SHOT_INFO, **CANON_PICTURE_STYLE, **CANON_LENS_INFO, **CANON_FILE_INFO}
NIKON_MAKERNOTE_TAGS = {**NIKON_VERSION, **NIKON_ISO_INFO, **NIKON_SHOT_INFO, **NIKON_COLOR_BALANCE, **NIKON_LENS_DATA, **NIKON_FLASH_INFO, **NIKON_AF_INFO, **NIKON_FILE_INFO, **NIKON_PICTURE_CONTROL, **NIKON_WORLD_TIME}
SONY_MAKERNOTE_TAGS = {**SONY_CAMERA_SETTINGS, **SONY_AF_INFO, **SONY_FILE_INFO, **SONY_MOVIE_INFO}
FUJIFILM_MAKERNOTE_TAGS = {**FUJIFILM_VERSION, **FUJIFILM_CAMERA_SETTINGS, **FUJIFILM_LENS_INFO, **FUJIFILM_FILM_SIMULATION}
OLYMPUS_MAKERNOTE_TAGS = {**OLYMPUS_EQUIPMENT, **OLYMPUS_IMAGE_PROCESSING, **OLYMPUS_RAW_DEVELOPMENT, **OLYMPUS_FOCUS_INFO, **OLYMPUS_SENSOR_INFO}
PANASONIC_MAKERNOTE_TAGS = {**PANASONIC_CAMERA_SETTINGS, **PANASONIC_LENS_INFO}
PENTAX_MAKERNOTE_TAGS = {**PENTAX_CAMERA_SETTINGS}


def extract_vendor_makernotes(filepath: str) -> Optional[Dict[str, Any]]:
    result = {
        "makernotes": {
            "canon": {},
            "nikon": {},
            "sony": {},
            "fujifilm": {},
            "olympus": {},
            "panasonic": {},
            "pentax": {},
            "other": {}
        },
        "detection": {"detected_vendors": [], "confidence": 0.0},
        "lens_data": {},
        "camera_settings": {},
        "fields_extracted": 0
    }

    try:
        from .exif import extract_exif_metadata
        exif_data = extract_exif_metadata(filepath)

        if not exif_data or "error" in exif_data:
            return result

        all_tags = {}
        for category in ["image", "photo", "gps", "interoperability"]:
            if category in exif_data and isinstance(exif_data[category], dict):
                all_tags.update(exif_data[category])

        detected_any = False

        for tag, value in all_tags.items():
            tag_str = str(tag)

            if tag_str in CANON_MAKERNOTE_TAGS:
                key = CANON_MAKERNOTE_TAGS[tag_str]
                result["makernotes"]["canon"][key] = str(value)
                detected_any = True

            elif tag_str in NIKON_MAKERNOTE_TAGS:
                key = NIKON_MAKERNOTE_TAGS[tag_str]
                result["makernotes"]["nikon"][key] = str(value)
                detected_any = True

            elif tag_str in SONY_MAKERNOTE_TAGS:
                key = SONY_MAKERNOTE_TAGS[tag_str]
                result["makernotes"]["sony"][key] = str(value)
                detected_any = True

            elif tag_str in FUJIFILM_MAKERNOTE_TAGS:
                key = FUJIFILM_MAKERNOTE_TAGS[tag_str]
                result["makernotes"]["fujifilm"][key] = str(value)
                detected_any = True

            elif tag_str in OLYMPUS_MAKERNOTE_TAGS:
                key = OLYMPUS_MAKERNOTE_TAGS[tag_str]
                result["makernotes"]["olympus"][key] = str(value)
                detected_any = True

            elif tag_str in PANASONIC_MAKERNOTE_TAGS:
                key = PANASONIC_MAKERNOTE_TAGS[tag_str]
                result["makernotes"]["panasonic"][key] = str(value)
                detected_any = True

            elif tag_str in PENTAX_MAKERNOTE_TAGS:
                key = PENTAX_MAKERNOTE_TAGS[tag_str]
                result["makernotes"]["pentax"][key] = str(value)
                detected_any = True

            elif tag_str.startswith(("Canon", "Nikon", "Sony", "Fuji", "Olymp", "Panason", "Pentax")):
                result["makernotes"]["other"][tag_str] = str(value)
                detected_any = True

        if detected_any:
            vendors = [v for v in ["canon", "nikon", "sony", "fujifilm", "olympus", "panasonic", "pentax"] if result["makernotes"][v]]
            result["detection"]["detected_vendors"] = vendors
            result["detection"]["confidence"] = min(1.0, len(vendors) * 0.2 + 0.5)

        total_fields = sum(len(v) for v in result["makernotes"].values()) + len(result["lens_data"]) + len(result["camera_settings"])
        result["fields_extracted"] = total_fields

        return result

    except Exception as e:
        return {"error": f"Failed to extract MakerNote metadata: {str(e)}"}


def get_makernote_field_count() -> int:
    return len(CANON_MAKERNOTE_TAGS) + len(NIKON_MAKERNOTE_TAGS) + len(SONY_MAKERNOTE_TAGS) + len(FUJIFILM_MAKERNOTE_TAGS) + len(OLYMPUS_MAKERNOTE_TAGS) + len(PANASONIC_MAKERNOTE_TAGS) + len(PENTAX_MAKERNOTE_TAGS)
